// Operator-Specific Cost Line Templates
// Source: docs/food-costing-reference-data.md Section 4
// When a chef selects their operation type, these templates pre-populate
// the cost-plus calculator with relevant line items.

import type { OperatorType } from './knowledge'

export interface OperatorCostLine {
  id: string
  label: string
  category:
    | 'food'
    | 'labor'
    | 'overhead'
    | 'incidental'
    | 'platform'
    | 'packaging'
    | 'logistics'
    | 'regulatory'
  amountCents: number // default amount (0 = chef fills in)
  frequency: 'per_event' | 'per_order' | 'per_unit' | 'monthly' | 'annual' | 'one_time'
  operatorTypes: OperatorType[]
  isDefault: boolean
  notes?: string
}

// ---------------------------------------------------------------------------
// Cost line templates by operator type
// ---------------------------------------------------------------------------

const COST_LINES: OperatorCostLine[] = [
  // --- Private Chef ---
  {
    id: 'pc-mileage',
    label: 'Travel (mileage)',
    category: 'logistics',
    amountCents: 0,
    frequency: 'per_event',
    operatorTypes: ['private_chef'],
    isDefault: true,
    notes: 'IRS rate $0.67/mile in 2026 or actual fuel',
  },
  {
    id: 'pc-travel-time',
    label: 'Travel time',
    category: 'labor',
    amountCents: 0,
    frequency: 'per_event',
    operatorTypes: ['private_chef'],
    isDefault: true,
    notes: 'Hourly rate x drive hours',
  },
  {
    id: 'pc-parking',
    label: 'Parking',
    category: 'incidental',
    amountCents: 0,
    frequency: 'per_event',
    operatorTypes: ['private_chef'],
    isDefault: false,
    notes: '$0-50 per event',
  },
  {
    id: 'pc-shopping',
    label: 'Grocery shopping time',
    category: 'labor',
    amountCents: 0,
    frequency: 'per_event',
    operatorTypes: ['private_chef'],
    isDefault: true,
    notes: '1-3 hours x hourly rate',
  },
  {
    id: 'pc-kitchen-limits',
    label: 'Client kitchen limitations',
    category: 'incidental',
    amountCents: 0,
    frequency: 'per_event',
    operatorTypes: ['private_chef'],
    isDefault: false,
    notes: '$0-200 rental equipment',
  },
  {
    id: 'pc-disposables',
    label: 'Disposables',
    category: 'incidental',
    amountCents: 0,
    frequency: 'per_event',
    operatorTypes: ['private_chef'],
    isDefault: true,
    notes: '$5-30 per event',
  },
  {
    id: 'pc-cleaning',
    label: 'Cleaning supplies',
    category: 'incidental',
    amountCents: 0,
    frequency: 'per_event',
    operatorTypes: ['private_chef'],
    isDefault: false,
    notes: '$5-15 per event',
  },

  // --- Catering ---
  {
    id: 'cat-venue',
    label: 'Venue rental',
    category: 'overhead',
    amountCents: 0,
    frequency: 'per_event',
    operatorTypes: ['catering'],
    isDefault: true,
    notes: '$0-5,000 per event',
  },
  {
    id: 'cat-equip-rental',
    label: 'Equipment rental',
    category: 'overhead',
    amountCents: 0,
    frequency: 'per_event',
    operatorTypes: ['catering'],
    isDefault: true,
    notes: '$100-2,000 per event',
  },
  {
    id: 'cat-linen',
    label: 'Linen rental',
    category: 'overhead',
    amountCents: 0,
    frequency: 'per_event',
    operatorTypes: ['catering'],
    isDefault: false,
    notes: '$100-800 per event',
  },
  {
    id: 'cat-tableware',
    label: 'China/glass/flatware rental',
    category: 'overhead',
    amountCents: 0,
    frequency: 'per_event',
    operatorTypes: ['catering'],
    isDefault: false,
    notes: '$3-15 per setting',
  },
  {
    id: 'cat-warmers',
    label: 'Chafing dishes / warmers',
    category: 'overhead',
    amountCents: 0,
    frequency: 'per_event',
    operatorTypes: ['catering'],
    isDefault: false,
    notes: '$8-25 each',
  },
  {
    id: 'cat-staff',
    label: 'Event staff (servers, bartenders)',
    category: 'labor',
    amountCents: 0,
    frequency: 'per_event',
    operatorTypes: ['catering'],
    isDefault: true,
    notes: '$25-45/hr per person',
  },
  {
    id: 'cat-delivery',
    label: 'Delivery/transport',
    category: 'logistics',
    amountCents: 0,
    frequency: 'per_event',
    operatorTypes: ['catering'],
    isDefault: true,
    notes: '$50-500 per event',
  },
  {
    id: 'cat-floral',
    label: 'Floral/decor',
    category: 'incidental',
    amountCents: 0,
    frequency: 'per_event',
    operatorTypes: ['catering'],
    isDefault: false,
    notes: '$0-5,000 if included',
  },
  {
    id: 'cat-permits',
    label: 'Permits / licenses',
    category: 'regulatory',
    amountCents: 0,
    frequency: 'per_event',
    operatorTypes: ['catering'],
    isDefault: false,
    notes: '$50-500 per event',
  },

  // --- Food Truck ---
  {
    id: 'ft-commissary',
    label: 'Commissary kitchen rental',
    category: 'overhead',
    amountCents: 0,
    frequency: 'monthly',
    operatorTypes: ['food_truck'],
    isDefault: true,
    notes: '$500-2,000/month',
  },
  {
    id: 'ft-generator',
    label: 'Generator fuel',
    category: 'overhead',
    amountCents: 0,
    frequency: 'per_event',
    operatorTypes: ['food_truck'],
    isDefault: true,
    notes: '$15-40/day',
  },
  {
    id: 'ft-vending',
    label: 'Parking permit / vending fee',
    category: 'regulatory',
    amountCents: 0,
    frequency: 'per_event',
    operatorTypes: ['food_truck'],
    isDefault: true,
    notes: '$25-500/day',
  },
  {
    id: 'ft-vehicle-maint',
    label: 'Vehicle maintenance',
    category: 'overhead',
    amountCents: 0,
    frequency: 'monthly',
    operatorTypes: ['food_truck'],
    isDefault: true,
    notes: '$200-600/month',
  },
  {
    id: 'ft-vehicle-ins',
    label: 'Vehicle insurance',
    category: 'overhead',
    amountCents: 0,
    frequency: 'monthly',
    operatorTypes: ['food_truck'],
    isDefault: true,
    notes: '$200-500/month',
  },
  {
    id: 'ft-propane',
    label: 'Propane',
    category: 'overhead',
    amountCents: 0,
    frequency: 'per_event',
    operatorTypes: ['food_truck'],
    isDefault: false,
    notes: '$20-40/tank',
  },
  {
    id: 'ft-pos',
    label: 'POS system fees',
    category: 'platform',
    amountCents: 0,
    frequency: 'monthly',
    operatorTypes: ['food_truck'],
    isDefault: false,
    notes: '$30-100/month',
  },
  {
    id: 'ft-packaging',
    label: 'Packaging (containers, bags, utensils)',
    category: 'packaging',
    amountCents: 0,
    frequency: 'per_order',
    operatorTypes: ['food_truck'],
    isDefault: true,
    notes: '$0.50-1.50 per order',
  },

  // --- Ghost Kitchen ---
  {
    id: 'gk-rent',
    label: 'Kitchen rental (shared space)',
    category: 'overhead',
    amountCents: 0,
    frequency: 'monthly',
    operatorTypes: ['ghost_kitchen'],
    isDefault: true,
    notes: '$1,500-5,000/month',
  },
  {
    id: 'gk-commission',
    label: 'Platform commission',
    category: 'platform',
    amountCents: 0,
    frequency: 'per_order',
    operatorTypes: ['ghost_kitchen'],
    isDefault: true,
    notes: '15-30% of order total',
  },
  {
    id: 'gk-packaging',
    label: 'Packaging per order',
    category: 'packaging',
    amountCents: 0,
    frequency: 'per_order',
    operatorTypes: ['ghost_kitchen'],
    isDefault: true,
    notes: '$0.75-2.50 per order',
  },
  {
    id: 'gk-tablet',
    label: 'Tablet fees (platform)',
    category: 'platform',
    amountCents: 0,
    frequency: 'monthly',
    operatorTypes: ['ghost_kitchen'],
    isDefault: false,
    notes: '$0-200/month',
  },
  {
    id: 'gk-photo',
    label: 'Photography / menu content',
    category: 'incidental',
    amountCents: 0,
    frequency: 'one_time',
    operatorTypes: ['ghost_kitchen'],
    isDefault: false,
    notes: '$200-1,000',
  },
  {
    id: 'gk-marketing',
    label: 'Platform marketing / promotions',
    category: 'incidental',
    amountCents: 0,
    frequency: 'monthly',
    operatorTypes: ['ghost_kitchen'],
    isDefault: false,
    notes: '$100-500/month',
  },

  // --- Bakery ---
  {
    id: 'bk-packaging',
    label: 'Packaging (boxes, bags, inserts, labels)',
    category: 'packaging',
    amountCents: 0,
    frequency: 'per_unit',
    operatorTypes: ['bakery'],
    isDefault: true,
    notes: '$0.25-3.00 per item',
  },
  {
    id: 'bk-decoration',
    label: 'Decoration labor (cakes)',
    category: 'labor',
    amountCents: 0,
    frequency: 'per_order',
    operatorTypes: ['bakery'],
    isDefault: true,
    notes: '$25-75/hr, 2-20 hrs per piece',
  },
  {
    id: 'bk-specialty-equip',
    label: 'Specialty equipment (molds, rings, tips)',
    category: 'overhead',
    amountCents: 0,
    frequency: 'one_time',
    operatorTypes: ['bakery'],
    isDefault: false,
    notes: '$50-500, amortized',
  },
  {
    id: 'bk-waste',
    label: 'Waste rate (unsold perishables)',
    category: 'food',
    amountCents: 0,
    frequency: 'per_event',
    operatorTypes: ['bakery'],
    isDefault: true,
    notes: '5-15% of daily production',
  },
  {
    id: 'bk-display',
    label: 'Display materials',
    category: 'overhead',
    amountCents: 0,
    frequency: 'monthly',
    operatorTypes: ['bakery'],
    isDefault: false,
    notes: '$50-300/month',
  },

  // --- Restaurant ---
  {
    id: 'rest-rent',
    label: 'Rent / lease',
    category: 'overhead',
    amountCents: 0,
    frequency: 'monthly',
    operatorTypes: ['restaurant'],
    isDefault: true,
    notes: '$2,000-25,000/month',
  },
  {
    id: 'rest-utilities',
    label: 'Utilities',
    category: 'overhead',
    amountCents: 0,
    frequency: 'monthly',
    operatorTypes: ['restaurant'],
    isDefault: true,
    notes: '$500-3,000/month',
  },
  {
    id: 'rest-beverage',
    label: 'Beverage program (COGS)',
    category: 'food',
    amountCents: 0,
    frequency: 'monthly',
    operatorTypes: ['restaurant'],
    isDefault: true,
    notes: '18-35% of bev revenue',
  },
  {
    id: 'rest-comps',
    label: 'Comps / voids',
    category: 'food',
    amountCents: 0,
    frequency: 'monthly',
    operatorTypes: ['restaurant'],
    isDefault: false,
    notes: '1-3% of food revenue',
  },
  {
    id: 'rest-linen',
    label: 'Linen service',
    category: 'overhead',
    amountCents: 0,
    frequency: 'monthly',
    operatorTypes: ['restaurant'],
    isDefault: false,
    notes: '$200-600/month',
  },
  {
    id: 'rest-smallwares',
    label: 'Smallwares replacement',
    category: 'overhead',
    amountCents: 0,
    frequency: 'monthly',
    operatorTypes: ['restaurant'],
    isDefault: false,
    notes: '$100-500/month',
  },
  {
    id: 'rest-pos',
    label: 'POS system',
    category: 'platform',
    amountCents: 0,
    frequency: 'monthly',
    operatorTypes: ['restaurant'],
    isDefault: true,
    notes: '$100-400/month',
  },
  {
    id: 'rest-cc',
    label: 'Credit card processing',
    category: 'overhead',
    amountCents: 0,
    frequency: 'per_order',
    operatorTypes: ['restaurant'],
    isDefault: true,
    notes: '2.5-3.5% of revenue',
  },
  {
    id: 'rest-waste',
    label: 'Waste removal',
    category: 'overhead',
    amountCents: 0,
    frequency: 'monthly',
    operatorTypes: ['restaurant'],
    isDefault: false,
    notes: '$100-500/month',
  },
  {
    id: 'rest-pest',
    label: 'Pest control',
    category: 'overhead',
    amountCents: 0,
    frequency: 'monthly',
    operatorTypes: ['restaurant'],
    isDefault: false,
    notes: '$50-150/month',
  },
  {
    id: 'rest-music',
    label: 'Music licensing (BMI/ASCAP)',
    category: 'regulatory',
    amountCents: 0,
    frequency: 'annual',
    operatorTypes: ['restaurant'],
    isDefault: false,
    notes: '$300-1,500/year',
  },

  // --- Meal Prep ---
  {
    id: 'mp-containers',
    label: 'Containers + lids',
    category: 'packaging',
    amountCents: 0,
    frequency: 'per_unit',
    operatorTypes: ['meal_prep'],
    isDefault: true,
    notes: '$0.30-1.00 per meal',
  },
  {
    id: 'mp-labels',
    label: 'Labels (nutritional, branding)',
    category: 'packaging',
    amountCents: 0,
    frequency: 'per_unit',
    operatorTypes: ['meal_prep'],
    isDefault: true,
    notes: '$0.05-0.15 per label',
  },
  {
    id: 'mp-insulation',
    label: 'Insulated packaging',
    category: 'packaging',
    amountCents: 0,
    frequency: 'per_order',
    operatorTypes: ['meal_prep'],
    isDefault: true,
    notes: '$1.50-4.00 per shipment',
  },
  {
    id: 'mp-gel-packs',
    label: 'Gel packs / cold chain',
    category: 'packaging',
    amountCents: 0,
    frequency: 'per_order',
    operatorTypes: ['meal_prep'],
    isDefault: true,
    notes: '$0.50-1.50 per shipment',
  },
  {
    id: 'mp-delivery',
    label: 'Delivery labor or service',
    category: 'logistics',
    amountCents: 0,
    frequency: 'per_order',
    operatorTypes: ['meal_prep'],
    isDefault: true,
    notes: '$3-10 per delivery',
  },
  {
    id: 'mp-platform',
    label: 'Subscription platform fees',
    category: 'platform',
    amountCents: 0,
    frequency: 'monthly',
    operatorTypes: ['meal_prep'],
    isDefault: false,
    notes: '$50-300/month',
  },
  {
    id: 'mp-nutrition',
    label: 'Nutritional analysis software',
    category: 'platform',
    amountCents: 0,
    frequency: 'monthly',
    operatorTypes: ['meal_prep'],
    isDefault: false,
    notes: '$30-100/month',
  },

  // --- Wholesale / CPG ---
  {
    id: 'ws-copacking',
    label: 'Co-packing fees',
    category: 'labor',
    amountCents: 0,
    frequency: 'per_order',
    operatorTypes: ['wholesale_cpg'],
    isDefault: true,
    notes: '$5,000-50,000 per run',
  },
  {
    id: 'ws-packaging',
    label: 'Packaging (jars, bottles, labels, cartons)',
    category: 'packaging',
    amountCents: 0,
    frequency: 'per_unit',
    operatorTypes: ['wholesale_cpg'],
    isDefault: true,
    notes: '$0.50-5.00 per unit',
  },
  {
    id: 'ws-freight',
    label: 'Freight / distribution',
    category: 'logistics',
    amountCents: 0,
    frequency: 'per_unit',
    operatorTypes: ['wholesale_cpg'],
    isDefault: true,
    notes: '$0.25-2.00 per unit',
  },
  {
    id: 'ws-slotting',
    label: 'Slotting fees (retail placement)',
    category: 'platform',
    amountCents: 0,
    frequency: 'one_time',
    operatorTypes: ['wholesale_cpg'],
    isDefault: false,
    notes: '$5,000-25,000 per SKU per chain',
  },
  {
    id: 'ws-broker',
    label: 'Broker commissions',
    category: 'platform',
    amountCents: 0,
    frequency: 'per_unit',
    operatorTypes: ['wholesale_cpg'],
    isDefault: true,
    notes: '5-10% of wholesale price',
  },
  {
    id: 'ws-liability',
    label: 'Product liability insurance',
    category: 'regulatory',
    amountCents: 0,
    frequency: 'annual',
    operatorTypes: ['wholesale_cpg'],
    isDefault: true,
    notes: '$500-5,000/year',
  },
  {
    id: 'ws-lab',
    label: 'Lab testing / nutritional analysis',
    category: 'regulatory',
    amountCents: 0,
    frequency: 'one_time',
    operatorTypes: ['wholesale_cpg'],
    isDefault: false,
    notes: '$500-2,000 per SKU',
  },
  {
    id: 'ws-spoilage',
    label: 'Spoilage / returns',
    category: 'food',
    amountCents: 0,
    frequency: 'per_unit',
    operatorTypes: ['wholesale_cpg'],
    isDefault: false,
    notes: '2-8% of shipped product',
  },

  // --- Pop-Up ---
  {
    id: 'pu-venue',
    label: 'Venue fee / booth rental',
    category: 'overhead',
    amountCents: 0,
    frequency: 'per_event',
    operatorTypes: ['popup'],
    isDefault: true,
    notes: '$100-5,000 per event',
  },
  {
    id: 'pu-permit',
    label: 'Temporary health permit',
    category: 'regulatory',
    amountCents: 0,
    frequency: 'per_event',
    operatorTypes: ['popup'],
    isDefault: true,
    notes: '$50-500 per event',
  },
  {
    id: 'pu-transport',
    label: 'Equipment transport',
    category: 'logistics',
    amountCents: 0,
    frequency: 'per_event',
    operatorTypes: ['popup'],
    isDefault: true,
    notes: '$50-300 per event',
  },
  {
    id: 'pu-setup',
    label: 'Setup / breakdown labor',
    category: 'labor',
    amountCents: 0,
    frequency: 'per_event',
    operatorTypes: ['popup'],
    isDefault: true,
    notes: '2-6 hours x rate',
  },
  {
    id: 'pu-tent',
    label: 'Tent / canopy rental',
    category: 'overhead',
    amountCents: 0,
    frequency: 'per_event',
    operatorTypes: ['popup'],
    isDefault: false,
    notes: '$100-1,000',
  },
  {
    id: 'pu-tables',
    label: 'Tables / display rental',
    category: 'overhead',
    amountCents: 0,
    frequency: 'per_event',
    operatorTypes: ['popup'],
    isDefault: false,
    notes: '$50-300',
  },
  {
    id: 'pu-signage',
    label: 'Signage / branding',
    category: 'incidental',
    amountCents: 0,
    frequency: 'per_event',
    operatorTypes: ['popup'],
    isDefault: false,
    notes: '$50-500',
  },

  // --- Institutional ---
  {
    id: 'inst-contract',
    label: 'Contract price lock',
    category: 'food',
    amountCents: 0,
    frequency: 'per_unit',
    operatorTypes: ['institutional'],
    isDefault: true,
    notes: 'Fixed per meal, 6-12 months',
  },
  {
    id: 'inst-nutrition',
    label: 'Nutritional compliance overhead',
    category: 'labor',
    amountCents: 0,
    frequency: 'monthly',
    operatorTypes: ['institutional'],
    isDefault: true,
    notes: '2-5% of labor',
  },
  {
    id: 'inst-commodity',
    label: 'Commodity program credits',
    category: 'food',
    amountCents: 0,
    frequency: 'per_unit',
    operatorTypes: ['institutional'],
    isDefault: false,
    notes: '-$0.10-0.50 per meal (offset)',
  },
  {
    id: 'inst-waste-doc',
    label: 'Waste documentation labor',
    category: 'labor',
    amountCents: 0,
    frequency: 'per_event',
    operatorTypes: ['institutional'],
    isDefault: true,
    notes: '0.5-1 hr/day',
  },
  {
    id: 'inst-dietary',
    label: 'Specialized dietary prep',
    category: 'labor',
    amountCents: 0,
    frequency: 'per_unit',
    operatorTypes: ['institutional'],
    isDefault: false,
    notes: '+10-20% labor on restricted meals',
  },
  {
    id: 'inst-washing',
    label: 'Tray / dish washing (industrial)',
    category: 'overhead',
    amountCents: 0,
    frequency: 'per_unit',
    operatorTypes: ['institutional'],
    isDefault: false,
    notes: '$0.15-0.40 per tray',
  },

  // --- Universal (all operator types) ---
  {
    id: 'uni-cc',
    label: 'Credit card processing',
    category: 'overhead',
    amountCents: 0,
    frequency: 'per_order',
    operatorTypes: [
      'private_chef',
      'catering',
      'food_truck',
      'ghost_kitchen',
      'bakery',
      'meal_prep',
      'popup',
      'institutional',
      'wholesale_cpg',
    ],
    isDefault: false,
    notes: '2.5-3.5% of revenue',
  },
  {
    id: 'uni-sales-tax',
    label: 'Sales tax (prepared food)',
    category: 'regulatory',
    amountCents: 0,
    frequency: 'per_order',
    operatorTypes: [
      'private_chef',
      'catering',
      'food_truck',
      'ghost_kitchen',
      'bakery',
      'meal_prep',
      'popup',
      'restaurant',
    ],
    isDefault: false,
    notes: '0-10% by jurisdiction',
  },
  {
    id: 'uni-insurance',
    label: 'Business insurance (liability)',
    category: 'regulatory',
    amountCents: 0,
    frequency: 'annual',
    operatorTypes: [
      'private_chef',
      'catering',
      'food_truck',
      'ghost_kitchen',
      'bakery',
      'meal_prep',
      'popup',
      'restaurant',
      'institutional',
      'wholesale_cpg',
    ],
    isDefault: false,
    notes: '$500-3,000/year',
  },
  {
    id: 'uni-health-dept',
    label: 'Health department fees',
    category: 'regulatory',
    amountCents: 0,
    frequency: 'annual',
    operatorTypes: [
      'private_chef',
      'catering',
      'food_truck',
      'ghost_kitchen',
      'bakery',
      'meal_prep',
      'popup',
      'restaurant',
      'institutional',
    ],
    isDefault: false,
    notes: '$100-500/year',
  },
  {
    id: 'uni-biz-license',
    label: 'Business license',
    category: 'regulatory',
    amountCents: 0,
    frequency: 'annual',
    operatorTypes: [
      'private_chef',
      'catering',
      'food_truck',
      'ghost_kitchen',
      'bakery',
      'meal_prep',
      'popup',
      'restaurant',
      'institutional',
      'wholesale_cpg',
    ],
    isDefault: false,
    notes: '$50-500/year',
  },
  {
    id: 'uni-accounting',
    label: 'Accounting / bookkeeping',
    category: 'overhead',
    amountCents: 0,
    frequency: 'monthly',
    operatorTypes: [
      'private_chef',
      'catering',
      'food_truck',
      'ghost_kitchen',
      'bakery',
      'meal_prep',
      'restaurant',
      'institutional',
      'wholesale_cpg',
    ],
    isDefault: false,
    notes: '$100-500/month',
  },
]

// ---------------------------------------------------------------------------
// Lookup helpers
// ---------------------------------------------------------------------------

/**
 * Get all cost lines for a specific operator type, sorted: defaults first.
 */
export function getCostLinesForOperator(operatorType: OperatorType): OperatorCostLine[] {
  return COST_LINES.filter((line) => line.operatorTypes.includes(operatorType)).sort((a, b) => {
    if (a.isDefault && !b.isDefault) return -1
    if (!a.isDefault && b.isDefault) return 1
    return a.label.localeCompare(b.label)
  })
}

/**
 * Get only the default (pre-populated) cost lines for an operator type.
 */
export function getDefaultCostLines(operatorType: OperatorType): OperatorCostLine[] {
  return COST_LINES.filter((line) => line.operatorTypes.includes(operatorType) && line.isDefault)
}

/**
 * Get all unique cost line categories.
 */
export function getCostLineCategories(): string[] {
  return [...new Set(COST_LINES.map((l) => l.category))].sort()
}
