'use client'

import { useTransition } from 'react'
import Link from 'next/link'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Repeat } from '@/components/ui/icons'
import { acknowledgeAutoGeneratedEvent } from '@/lib/scheduling/recurring-actions'
import { toast } from 'sonner'

interface AutoDraft {
  id: string
  eventId: string
  scheduleId: string
  clientName: string
  eventDate: string
  generatedAt: string
}

interface AutoGeneratedDraftsCardProps {
  drafts: AutoDraft[]
}

export function AutoGeneratedDraftsCard({ drafts }: AutoGeneratedDraftsCardProps) {
  const [isPending, startTransition] = useTransition()

  if (drafts.length === 0) return null

  function handleAcknowledge(id: string) {
    startTransition(async () => {
      try {
        await acknowledgeAutoGeneratedEvent(id)
        toast.success('Dismissed')
      } catch {
        toast.error('Failed to dismiss')
      }
    })
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-base">
          <Repeat className="h-4 w-4 text-brand-400" />
          Auto-Generated Drafts
          <Badge variant="info">{drafts.length}</Badge>
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-2">
        {drafts.map((draft) => (
          <div
            key={draft.id}
            className="flex items-center justify-between rounded-md border border-stone-800 bg-stone-900/50 px-3 py-2"
          >
            <div className="space-y-0.5">
              <p className="text-sm font-medium text-stone-200">Draft for {draft.clientName}</p>
              <p className="text-xs text-stone-500">{draft.eventDate}</p>
            </div>
            <div className="flex items-center gap-2">
              <Link href={`/events/${draft.eventId}`}>
                <Button variant="secondary" size="sm">
                  View
                </Button>
              </Link>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => handleAcknowledge(draft.id)}
                disabled={isPending}
              >
                Dismiss
              </Button>
            </div>
          </div>
        ))}
      </CardContent>
    </Card>
  )
}
