'use server'

// Instacart Developer Platform — cart link builder.
// Generates a shareable URL that opens a pre-filled Instacart cart.
// Chef picks their store inside Instacart (Hannaford, Stop & Shop, Shaw's,
// Whole Foods, Market Basket, and 85,000+ other stores globally).
//
// Requires: INSTACART_API_KEY environment variable (ChefFlow platform key).
// Degrades gracefully to null if the key is not configured.
//
// API docs: https://docs.instacart.com/developer_platform_api/api/products/create_shopping_list_page/

export type InstacartLineItem = {
  name: string
  quantity: number
  unit: string
}

export async function buildInstacartCartLink(
  items: InstacartLineItem[]
): Promise<string | null> {
  const apiKey = process.env.INSTACART_API_KEY
  if (!apiKey || items.length === 0) return null

  try {
    // Instacart requires integer quantities ≥ 1
    const lineItems = items
      .filter((item) => item.name.trim().length > 0)
      .map((item) => ({
        name: item.name.trim(),
        quantity: Math.max(1, Math.round(item.quantity)),
        unit: item.unit || 'each',
        display_text: `${item.name} — ${item.quantity} ${item.unit}`,
      }))

    if (lineItems.length === 0) return null

    const body = {
      title: 'ChefFlow Grocery List',
      line_items: lineItems,
      partner_linkback_url:
        process.env.NEXT_PUBLIC_APP_URL ?? 'https://app.chefflow.com',
      instructions:
        'Generated by ChefFlow. Please verify quantities before checkout.',
    }

    const res = await fetch(
      'https://connect.instacart.com/idp/v1/products/products_link',
      {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${apiKey}`,
          'Content-Type': 'application/json',
          Accept: 'application/json',
        },
        body: JSON.stringify(body),
      }
    )

    if (!res.ok) return null

    const data = await res.json()
    return (data.products_link_url as string) ?? null
  } catch {
    return null
  }
}
