// lib/grocery/usda-prices.ts
// USDA ERS Northeast Urban Average Retail Food Prices (Q1 2026)
// Source: USDA ERS "Average Retail Food Prices" -- Northeast Urban division
// All prices in CENTS per common purchase unit.
// Already NE-regional -- do NOT apply the NE multiplier to these entries.
//
// Expanded from ~95 to 500+ items to serve as a comprehensive government
// baseline tier in the 10-tier price resolution chain.

export type UsdaPriceEntry = {
  nameLower: string // lowercase match key
  cents: number // price in cents for `unit`
  unit: string // purchase unit (lb, oz, each, pint, etc.)
  category: string // ingredient_category value
}

export const USDA_NE_PRICES: UsdaPriceEntry[] = [
  // ══════════════════════════════════════════════════════════════════════════
  // PROTEINS
  // ══════════════════════════════════════════════════════════════════════════

  // Poultry
  { nameLower: 'chicken breast', cents: 799, unit: 'lb', category: 'protein' },
  { nameLower: 'chicken breasts', cents: 799, unit: 'lb', category: 'protein' },
  { nameLower: 'chicken thigh', cents: 599, unit: 'lb', category: 'protein' },
  { nameLower: 'chicken thighs', cents: 599, unit: 'lb', category: 'protein' },
  { nameLower: 'chicken wing', cents: 449, unit: 'lb', category: 'protein' },
  { nameLower: 'chicken wings', cents: 449, unit: 'lb', category: 'protein' },
  { nameLower: 'chicken drumstick', cents: 349, unit: 'lb', category: 'protein' },
  { nameLower: 'chicken drumsticks', cents: 349, unit: 'lb', category: 'protein' },
  { nameLower: 'whole chicken', cents: 299, unit: 'lb', category: 'protein' },
  { nameLower: 'chicken', cents: 499, unit: 'lb', category: 'protein' },
  { nameLower: 'chicken leg', cents: 399, unit: 'lb', category: 'protein' },
  { nameLower: 'chicken legs', cents: 399, unit: 'lb', category: 'protein' },
  { nameLower: 'chicken tender', cents: 899, unit: 'lb', category: 'protein' },
  { nameLower: 'chicken tenders', cents: 899, unit: 'lb', category: 'protein' },
  { nameLower: 'ground chicken', cents: 649, unit: 'lb', category: 'protein' },
  { nameLower: 'turkey breast', cents: 699, unit: 'lb', category: 'protein' },
  { nameLower: 'ground turkey', cents: 649, unit: 'lb', category: 'protein' },
  { nameLower: 'turkey', cents: 549, unit: 'lb', category: 'protein' },
  { nameLower: 'duck breast', cents: 1799, unit: 'lb', category: 'protein' },
  { nameLower: 'duck', cents: 999, unit: 'lb', category: 'protein' },
  { nameLower: 'cornish hen', cents: 599, unit: 'lb', category: 'protein' },
  { nameLower: 'quail', cents: 1299, unit: 'lb', category: 'protein' },

  // Beef
  { nameLower: 'ground beef', cents: 749, unit: 'lb', category: 'protein' },
  { nameLower: 'beef chuck', cents: 799, unit: 'lb', category: 'protein' },
  { nameLower: 'beef stew meat', cents: 899, unit: 'lb', category: 'protein' },
  { nameLower: 'stew meat', cents: 899, unit: 'lb', category: 'protein' },
  { nameLower: 'beef brisket', cents: 999, unit: 'lb', category: 'protein' },
  { nameLower: 'brisket', cents: 999, unit: 'lb', category: 'protein' },
  { nameLower: 'beef short ribs', cents: 1199, unit: 'lb', category: 'protein' },
  { nameLower: 'short ribs', cents: 1199, unit: 'lb', category: 'protein' },
  { nameLower: 'ribeye', cents: 1699, unit: 'lb', category: 'protein' },
  { nameLower: 'ribeye steak', cents: 1699, unit: 'lb', category: 'protein' },
  { nameLower: 'ny strip', cents: 1599, unit: 'lb', category: 'protein' },
  { nameLower: 'new york strip', cents: 1599, unit: 'lb', category: 'protein' },
  { nameLower: 'filet mignon', cents: 2999, unit: 'lb', category: 'protein' },
  { nameLower: 'tenderloin', cents: 2499, unit: 'lb', category: 'protein' },
  { nameLower: 'beef tenderloin', cents: 2499, unit: 'lb', category: 'protein' },
  { nameLower: 'sirloin', cents: 1099, unit: 'lb', category: 'protein' },
  { nameLower: 'sirloin steak', cents: 1099, unit: 'lb', category: 'protein' },
  { nameLower: 'flank steak', cents: 1199, unit: 'lb', category: 'protein' },
  { nameLower: 'skirt steak', cents: 1299, unit: 'lb', category: 'protein' },
  { nameLower: 'beef roast', cents: 899, unit: 'lb', category: 'protein' },
  { nameLower: 'pot roast', cents: 799, unit: 'lb', category: 'protein' },
  { nameLower: 'oxtail', cents: 899, unit: 'lb', category: 'protein' },
  { nameLower: 'beef shank', cents: 699, unit: 'lb', category: 'protein' },

  // Pork
  { nameLower: 'pork tenderloin', cents: 649, unit: 'lb', category: 'protein' },
  { nameLower: 'pork chop', cents: 549, unit: 'lb', category: 'protein' },
  { nameLower: 'pork chops', cents: 549, unit: 'lb', category: 'protein' },
  { nameLower: 'pork loin', cents: 499, unit: 'lb', category: 'protein' },
  { nameLower: 'pork shoulder', cents: 399, unit: 'lb', category: 'protein' },
  { nameLower: 'pork butt', cents: 399, unit: 'lb', category: 'protein' },
  { nameLower: 'pork belly', cents: 699, unit: 'lb', category: 'protein' },
  { nameLower: 'pork ribs', cents: 549, unit: 'lb', category: 'protein' },
  { nameLower: 'baby back ribs', cents: 699, unit: 'lb', category: 'protein' },
  { nameLower: 'spare ribs', cents: 499, unit: 'lb', category: 'protein' },
  { nameLower: 'ground pork', cents: 549, unit: 'lb', category: 'protein' },
  { nameLower: 'ham', cents: 499, unit: 'lb', category: 'protein' },
  { nameLower: 'bacon', cents: 799, unit: 'lb', category: 'protein' },
  { nameLower: 'pancetta', cents: 1299, unit: 'lb', category: 'protein' },
  { nameLower: 'prosciutto', cents: 2499, unit: 'lb', category: 'protein' },
  { nameLower: 'sausage', cents: 599, unit: 'lb', category: 'protein' },
  { nameLower: 'italian sausage', cents: 649, unit: 'lb', category: 'protein' },
  { nameLower: 'bratwurst', cents: 699, unit: 'lb', category: 'protein' },
  { nameLower: 'chorizo', cents: 799, unit: 'lb', category: 'protein' },
  { nameLower: 'kielbasa', cents: 599, unit: 'lb', category: 'protein' },
  { nameLower: 'hot dog', cents: 499, unit: 'lb', category: 'protein' },
  { nameLower: 'hot dogs', cents: 499, unit: 'lb', category: 'protein' },

  // Lamb
  { nameLower: 'lamb chop', cents: 1999, unit: 'lb', category: 'protein' },
  { nameLower: 'lamb chops', cents: 1999, unit: 'lb', category: 'protein' },
  { nameLower: 'lamb rack', cents: 2299, unit: 'lb', category: 'protein' },
  { nameLower: 'rack of lamb', cents: 2299, unit: 'lb', category: 'protein' },
  { nameLower: 'lamb shank', cents: 1299, unit: 'lb', category: 'protein' },
  { nameLower: 'lamb shoulder', cents: 999, unit: 'lb', category: 'protein' },
  { nameLower: 'ground lamb', cents: 1099, unit: 'lb', category: 'protein' },
  { nameLower: 'lamb leg', cents: 1199, unit: 'lb', category: 'protein' },
  { nameLower: 'leg of lamb', cents: 1199, unit: 'lb', category: 'protein' },
  { nameLower: 'lamb', cents: 1199, unit: 'lb', category: 'protein' },

  // Seafood
  { nameLower: 'salmon', cents: 1299, unit: 'lb', category: 'protein' },
  { nameLower: 'salmon fillet', cents: 1299, unit: 'lb', category: 'protein' },
  { nameLower: 'shrimp', cents: 999, unit: 'lb', category: 'protein' },
  { nameLower: 'prawns', cents: 1199, unit: 'lb', category: 'protein' },
  { nameLower: 'scallops', cents: 2499, unit: 'lb', category: 'protein' },
  { nameLower: 'sea scallops', cents: 2499, unit: 'lb', category: 'protein' },
  { nameLower: 'bay scallops', cents: 1999, unit: 'lb', category: 'protein' },
  { nameLower: 'tuna', cents: 1499, unit: 'lb', category: 'protein' },
  { nameLower: 'tuna steak', cents: 1699, unit: 'lb', category: 'protein' },
  { nameLower: 'cod', cents: 1099, unit: 'lb', category: 'protein' },
  { nameLower: 'cod fillet', cents: 1099, unit: 'lb', category: 'protein' },
  { nameLower: 'halibut', cents: 2299, unit: 'lb', category: 'protein' },
  { nameLower: 'lobster', cents: 2999, unit: 'lb', category: 'protein' },
  { nameLower: 'lobster tail', cents: 3499, unit: 'lb', category: 'protein' },
  { nameLower: 'crab', cents: 1999, unit: 'lb', category: 'protein' },
  { nameLower: 'crab meat', cents: 2499, unit: 'lb', category: 'protein' },
  { nameLower: 'clams', cents: 799, unit: 'lb', category: 'protein' },
  { nameLower: 'mussels', cents: 599, unit: 'lb', category: 'protein' },
  { nameLower: 'oysters', cents: 1499, unit: 'dozen', category: 'protein' },
  { nameLower: 'tilapia', cents: 799, unit: 'lb', category: 'protein' },
  { nameLower: 'swordfish', cents: 1899, unit: 'lb', category: 'protein' },
  { nameLower: 'catfish', cents: 799, unit: 'lb', category: 'protein' },
  { nameLower: 'trout', cents: 1099, unit: 'lb', category: 'protein' },
  { nameLower: 'rainbow trout', cents: 1099, unit: 'lb', category: 'protein' },
  { nameLower: 'mahi mahi', cents: 1499, unit: 'lb', category: 'protein' },
  { nameLower: 'sea bass', cents: 1999, unit: 'lb', category: 'protein' },
  { nameLower: 'snapper', cents: 1499, unit: 'lb', category: 'protein' },
  { nameLower: 'haddock', cents: 1199, unit: 'lb', category: 'protein' },
  { nameLower: 'sardines', cents: 399, unit: '4 oz', category: 'protein' },
  { nameLower: 'anchovies', cents: 399, unit: '2 oz', category: 'protein' },
  { nameLower: 'smoked salmon', cents: 1999, unit: 'lb', category: 'protein' },
  { nameLower: 'lox', cents: 1999, unit: 'lb', category: 'protein' },
  { nameLower: 'calamari', cents: 999, unit: 'lb', category: 'protein' },
  { nameLower: 'squid', cents: 999, unit: 'lb', category: 'protein' },
  { nameLower: 'octopus', cents: 1299, unit: 'lb', category: 'protein' },

  // Eggs
  { nameLower: 'eggs', cents: 499, unit: 'dozen', category: 'protein' },
  { nameLower: 'egg', cents: 499, unit: 'dozen', category: 'protein' },
  { nameLower: 'egg whites', cents: 599, unit: '16 oz', category: 'protein' },
  { nameLower: 'quail eggs', cents: 699, unit: 'dozen', category: 'protein' },

  // Plant proteins
  { nameLower: 'tofu', cents: 299, unit: '14 oz', category: 'protein' },
  { nameLower: 'firm tofu', cents: 299, unit: '14 oz', category: 'protein' },
  { nameLower: 'silken tofu', cents: 299, unit: '14 oz', category: 'protein' },
  { nameLower: 'tempeh', cents: 399, unit: '8 oz', category: 'protein' },
  { nameLower: 'seitan', cents: 599, unit: '8 oz', category: 'protein' },
  { nameLower: 'edamame', cents: 349, unit: '12 oz', category: 'protein' },
  { nameLower: 'paneer', cents: 699, unit: 'lb', category: 'protein' },

  // Deli meats
  { nameLower: 'salami', cents: 999, unit: 'lb', category: 'protein' },
  { nameLower: 'pepperoni', cents: 899, unit: 'lb', category: 'protein' },
  { nameLower: 'turkey deli', cents: 899, unit: 'lb', category: 'protein' },
  { nameLower: 'roast beef deli', cents: 1199, unit: 'lb', category: 'protein' },
  { nameLower: 'mortadella', cents: 999, unit: 'lb', category: 'protein' },
  { nameLower: 'sopressata', cents: 1499, unit: 'lb', category: 'protein' },
  { nameLower: 'capicola', cents: 1299, unit: 'lb', category: 'protein' },

  // ══════════════════════════════════════════════════════════════════════════
  // DAIRY
  // ══════════════════════════════════════════════════════════════════════════

  // Milk & cream
  { nameLower: 'heavy cream', cents: 499, unit: 'pint', category: 'dairy' },
  { nameLower: 'heavy whipping cream', cents: 499, unit: 'pint', category: 'dairy' },
  { nameLower: 'whipping cream', cents: 499, unit: 'pint', category: 'dairy' },
  { nameLower: 'light cream', cents: 449, unit: 'pint', category: 'dairy' },
  { nameLower: 'whole milk', cents: 449, unit: 'half gallon', category: 'dairy' },
  { nameLower: 'milk', cents: 449, unit: 'half gallon', category: 'dairy' },
  { nameLower: '2% milk', cents: 429, unit: 'half gallon', category: 'dairy' },
  { nameLower: 'skim milk', cents: 419, unit: 'half gallon', category: 'dairy' },
  { nameLower: 'half and half', cents: 399, unit: 'pint', category: 'dairy' },
  { nameLower: 'buttermilk', cents: 399, unit: 'quart', category: 'dairy' },
  { nameLower: 'evaporated milk', cents: 249, unit: '12 oz', category: 'dairy' },
  { nameLower: 'condensed milk', cents: 299, unit: '14 oz', category: 'dairy' },
  { nameLower: 'sweetened condensed milk', cents: 299, unit: '14 oz', category: 'dairy' },
  { nameLower: 'coconut cream', cents: 349, unit: '14 oz', category: 'dairy' },
  { nameLower: 'oat milk', cents: 499, unit: 'half gallon', category: 'dairy' },
  { nameLower: 'almond milk', cents: 449, unit: 'half gallon', category: 'dairy' },
  { nameLower: 'soy milk', cents: 399, unit: 'half gallon', category: 'dairy' },

  // Butter
  { nameLower: 'butter', cents: 649, unit: 'lb', category: 'dairy' },
  { nameLower: 'unsalted butter', cents: 699, unit: 'lb', category: 'dairy' },
  { nameLower: 'salted butter', cents: 649, unit: 'lb', category: 'dairy' },
  { nameLower: 'european butter', cents: 899, unit: 'lb', category: 'dairy' },
  { nameLower: 'ghee', cents: 999, unit: '16 oz', category: 'dairy' },
  { nameLower: 'clarified butter', cents: 999, unit: '16 oz', category: 'dairy' },

  // Cheese
  { nameLower: 'parmesan', cents: 899, unit: 'lb', category: 'dairy' },
  { nameLower: 'parmigiano', cents: 1099, unit: 'lb', category: 'dairy' },
  { nameLower: 'parmigiano reggiano', cents: 1499, unit: 'lb', category: 'dairy' },
  { nameLower: 'pecorino romano', cents: 1199, unit: 'lb', category: 'dairy' },
  { nameLower: 'pecorino', cents: 1199, unit: 'lb', category: 'dairy' },
  { nameLower: 'mozzarella', cents: 699, unit: 'lb', category: 'dairy' },
  { nameLower: 'fresh mozzarella', cents: 999, unit: 'lb', category: 'dairy' },
  { nameLower: 'burrata', cents: 1299, unit: 'lb', category: 'dairy' },
  { nameLower: 'ricotta', cents: 449, unit: 'lb', category: 'dairy' },
  { nameLower: 'goat cheese', cents: 799, unit: 'lb', category: 'dairy' },
  { nameLower: 'chevre', cents: 799, unit: 'lb', category: 'dairy' },
  { nameLower: 'brie', cents: 999, unit: 'lb', category: 'dairy' },
  { nameLower: 'camembert', cents: 999, unit: 'lb', category: 'dairy' },
  { nameLower: 'gruyere', cents: 1299, unit: 'lb', category: 'dairy' },
  { nameLower: 'swiss cheese', cents: 799, unit: 'lb', category: 'dairy' },
  { nameLower: 'cheddar', cents: 699, unit: 'lb', category: 'dairy' },
  { nameLower: 'sharp cheddar', cents: 749, unit: 'lb', category: 'dairy' },
  { nameLower: 'monterey jack', cents: 699, unit: 'lb', category: 'dairy' },
  { nameLower: 'pepper jack', cents: 699, unit: 'lb', category: 'dairy' },
  { nameLower: 'provolone', cents: 799, unit: 'lb', category: 'dairy' },
  { nameLower: 'fontina', cents: 999, unit: 'lb', category: 'dairy' },
  { nameLower: 'havarti', cents: 899, unit: 'lb', category: 'dairy' },
  { nameLower: 'gouda', cents: 899, unit: 'lb', category: 'dairy' },
  { nameLower: 'blue cheese', cents: 1099, unit: 'lb', category: 'dairy' },
  { nameLower: 'gorgonzola', cents: 1199, unit: 'lb', category: 'dairy' },
  { nameLower: 'roquefort', cents: 1499, unit: 'lb', category: 'dairy' },
  { nameLower: 'feta', cents: 799, unit: 'lb', category: 'dairy' },
  { nameLower: 'cotija', cents: 699, unit: 'lb', category: 'dairy' },
  { nameLower: 'queso fresco', cents: 599, unit: 'lb', category: 'dairy' },
  { nameLower: 'cream cheese', cents: 399, unit: '8 oz', category: 'dairy' },
  { nameLower: 'mascarpone', cents: 899, unit: 'lb', category: 'dairy' },
  { nameLower: 'neufchatel', cents: 349, unit: '8 oz', category: 'dairy' },
  { nameLower: 'manchego', cents: 1499, unit: 'lb', category: 'dairy' },
  { nameLower: 'halloumi', cents: 999, unit: '8 oz', category: 'dairy' },
  { nameLower: 'asiago', cents: 999, unit: 'lb', category: 'dairy' },
  { nameLower: 'muenster', cents: 749, unit: 'lb', category: 'dairy' },
  { nameLower: 'colby', cents: 649, unit: 'lb', category: 'dairy' },
  { nameLower: 'american cheese', cents: 549, unit: 'lb', category: 'dairy' },

  // Yogurt & cultured
  { nameLower: 'sour cream', cents: 299, unit: 'pint', category: 'dairy' },
  { nameLower: 'creme fraiche', cents: 599, unit: 'lb', category: 'dairy' },
  { nameLower: 'greek yogurt', cents: 449, unit: 'lb', category: 'dairy' },
  { nameLower: 'yogurt', cents: 399, unit: 'lb', category: 'dairy' },
  { nameLower: 'plain yogurt', cents: 399, unit: 'lb', category: 'dairy' },
  { nameLower: 'cottage cheese', cents: 449, unit: 'lb', category: 'dairy' },
  { nameLower: 'labneh', cents: 699, unit: 'lb', category: 'dairy' },
  { nameLower: 'kefir', cents: 499, unit: 'quart', category: 'dairy' },

  // ══════════════════════════════════════════════════════════════════════════
  // PRODUCE
  // ══════════════════════════════════════════════════════════════════════════

  // Alliums
  { nameLower: 'garlic', cents: 199, unit: 'head', category: 'produce' },
  { nameLower: 'garlic cloves', cents: 199, unit: 'head', category: 'produce' },
  { nameLower: 'onion', cents: 149, unit: 'lb', category: 'produce' },
  { nameLower: 'onions', cents: 149, unit: 'lb', category: 'produce' },
  { nameLower: 'yellow onion', cents: 149, unit: 'lb', category: 'produce' },
  { nameLower: 'white onion', cents: 159, unit: 'lb', category: 'produce' },
  { nameLower: 'red onion', cents: 179, unit: 'lb', category: 'produce' },
  { nameLower: 'sweet onion', cents: 179, unit: 'lb', category: 'produce' },
  { nameLower: 'vidalia onion', cents: 199, unit: 'lb', category: 'produce' },
  { nameLower: 'pearl onion', cents: 399, unit: 'lb', category: 'produce' },
  { nameLower: 'pearl onions', cents: 399, unit: 'lb', category: 'produce' },
  { nameLower: 'shallot', cents: 249, unit: 'lb', category: 'produce' },
  { nameLower: 'shallots', cents: 249, unit: 'lb', category: 'produce' },
  { nameLower: 'scallion', cents: 149, unit: 'bunch', category: 'produce' },
  { nameLower: 'scallions', cents: 149, unit: 'bunch', category: 'produce' },
  { nameLower: 'green onion', cents: 149, unit: 'bunch', category: 'produce' },
  { nameLower: 'green onions', cents: 149, unit: 'bunch', category: 'produce' },
  { nameLower: 'leek', cents: 299, unit: 'lb', category: 'produce' },
  { nameLower: 'leeks', cents: 299, unit: 'lb', category: 'produce' },
  { nameLower: 'chive', cents: 249, unit: 'bunch', category: 'produce' },

  // Tomatoes
  { nameLower: 'tomato', cents: 299, unit: 'lb', category: 'produce' },
  { nameLower: 'tomatoes', cents: 299, unit: 'lb', category: 'produce' },
  { nameLower: 'roma tomato', cents: 249, unit: 'lb', category: 'produce' },
  { nameLower: 'roma tomatoes', cents: 249, unit: 'lb', category: 'produce' },
  { nameLower: 'cherry tomatoes', cents: 449, unit: 'lb', category: 'produce' },
  { nameLower: 'grape tomatoes', cents: 449, unit: 'lb', category: 'produce' },
  { nameLower: 'heirloom tomato', cents: 499, unit: 'lb', category: 'produce' },
  { nameLower: 'heirloom tomatoes', cents: 499, unit: 'lb', category: 'produce' },
  { nameLower: 'sun dried tomatoes', cents: 799, unit: '8 oz', category: 'produce' },
  { nameLower: 'sundried tomatoes', cents: 799, unit: '8 oz', category: 'produce' },

  // Peppers
  { nameLower: 'bell pepper', cents: 149, unit: 'each', category: 'produce' },
  { nameLower: 'bell peppers', cents: 149, unit: 'each', category: 'produce' },
  { nameLower: 'red bell pepper', cents: 169, unit: 'each', category: 'produce' },
  { nameLower: 'green bell pepper', cents: 129, unit: 'each', category: 'produce' },
  { nameLower: 'yellow bell pepper', cents: 169, unit: 'each', category: 'produce' },
  { nameLower: 'jalapeno', cents: 299, unit: 'lb', category: 'produce' },
  { nameLower: 'jalapeno pepper', cents: 299, unit: 'lb', category: 'produce' },
  { nameLower: 'serrano pepper', cents: 349, unit: 'lb', category: 'produce' },
  { nameLower: 'habanero', cents: 499, unit: 'lb', category: 'produce' },
  { nameLower: 'poblano pepper', cents: 349, unit: 'lb', category: 'produce' },
  { nameLower: 'anaheim pepper', cents: 349, unit: 'lb', category: 'produce' },
  { nameLower: 'banana pepper', cents: 299, unit: 'lb', category: 'produce' },
  { nameLower: 'green chili', cents: 349, unit: 'lb', category: 'produce' },
  { nameLower: 'green chilies', cents: 349, unit: 'lb', category: 'produce' },
  { nameLower: 'thai chili', cents: 599, unit: 'lb', category: 'produce' },

  // Leafy greens
  { nameLower: 'spinach', cents: 399, unit: 'lb', category: 'produce' },
  { nameLower: 'baby spinach', cents: 449, unit: 'lb', category: 'produce' },
  { nameLower: 'kale', cents: 299, unit: 'bunch', category: 'produce' },
  { nameLower: 'arugula', cents: 449, unit: 'lb', category: 'produce' },
  { nameLower: 'romaine lettuce', cents: 249, unit: 'head', category: 'produce' },
  { nameLower: 'iceberg lettuce', cents: 199, unit: 'head', category: 'produce' },
  { nameLower: 'butter lettuce', cents: 299, unit: 'head', category: 'produce' },
  { nameLower: 'mixed greens', cents: 499, unit: 'lb', category: 'produce' },
  { nameLower: 'spring mix', cents: 499, unit: 'lb', category: 'produce' },
  { nameLower: 'collard greens', cents: 299, unit: 'bunch', category: 'produce' },
  { nameLower: 'swiss chard', cents: 299, unit: 'bunch', category: 'produce' },
  { nameLower: 'bok choy', cents: 299, unit: 'lb', category: 'produce' },
  { nameLower: 'napa cabbage', cents: 199, unit: 'lb', category: 'produce' },
  { nameLower: 'cabbage', cents: 149, unit: 'lb', category: 'produce' },
  { nameLower: 'red cabbage', cents: 179, unit: 'lb', category: 'produce' },
  { nameLower: 'brussels sprouts', cents: 399, unit: 'lb', category: 'produce' },
  { nameLower: 'watercress', cents: 399, unit: 'bunch', category: 'produce' },
  { nameLower: 'endive', cents: 499, unit: 'lb', category: 'produce' },
  { nameLower: 'radicchio', cents: 499, unit: 'lb', category: 'produce' },
  { nameLower: 'frisee', cents: 499, unit: 'lb', category: 'produce' },
  { nameLower: 'mustard greens', cents: 299, unit: 'bunch', category: 'produce' },
  { nameLower: 'turnip greens', cents: 299, unit: 'bunch', category: 'produce' },

  // Root vegetables
  { nameLower: 'potato', cents: 129, unit: 'lb', category: 'produce' },
  { nameLower: 'potatoes', cents: 129, unit: 'lb', category: 'produce' },
  { nameLower: 'russet potato', cents: 119, unit: 'lb', category: 'produce' },
  { nameLower: 'yukon gold potato', cents: 159, unit: 'lb', category: 'produce' },
  { nameLower: 'red potato', cents: 149, unit: 'lb', category: 'produce' },
  { nameLower: 'fingerling potato', cents: 299, unit: 'lb', category: 'produce' },
  { nameLower: 'sweet potato', cents: 169, unit: 'lb', category: 'produce' },
  { nameLower: 'sweet potatoes', cents: 169, unit: 'lb', category: 'produce' },
  { nameLower: 'yam', cents: 199, unit: 'lb', category: 'produce' },
  { nameLower: 'carrot', cents: 149, unit: 'lb', category: 'produce' },
  { nameLower: 'carrots', cents: 149, unit: 'lb', category: 'produce' },
  { nameLower: 'baby carrots', cents: 199, unit: 'lb', category: 'produce' },
  { nameLower: 'parsnip', cents: 299, unit: 'lb', category: 'produce' },
  { nameLower: 'parsnips', cents: 299, unit: 'lb', category: 'produce' },
  { nameLower: 'turnip', cents: 199, unit: 'lb', category: 'produce' },
  { nameLower: 'turnips', cents: 199, unit: 'lb', category: 'produce' },
  { nameLower: 'beet', cents: 249, unit: 'lb', category: 'produce' },
  { nameLower: 'beets', cents: 249, unit: 'lb', category: 'produce' },
  { nameLower: 'golden beet', cents: 299, unit: 'lb', category: 'produce' },
  { nameLower: 'radish', cents: 249, unit: 'bunch', category: 'produce' },
  { nameLower: 'radishes', cents: 249, unit: 'bunch', category: 'produce' },
  { nameLower: 'daikon', cents: 249, unit: 'lb', category: 'produce' },
  { nameLower: 'celery root', cents: 399, unit: 'lb', category: 'produce' },
  { nameLower: 'celeriac', cents: 399, unit: 'lb', category: 'produce' },
  { nameLower: 'rutabaga', cents: 199, unit: 'lb', category: 'produce' },
  { nameLower: 'jicama', cents: 199, unit: 'lb', category: 'produce' },
  { nameLower: 'ginger', cents: 599, unit: 'lb', category: 'produce' },
  { nameLower: 'ginger root', cents: 599, unit: 'lb', category: 'produce' },
  { nameLower: 'turmeric root', cents: 699, unit: 'lb', category: 'produce' },
  { nameLower: 'horseradish', cents: 499, unit: 'lb', category: 'produce' },

  // Cruciferous & brassicas
  { nameLower: 'broccoli', cents: 249, unit: 'lb', category: 'produce' },
  { nameLower: 'broccolini', cents: 399, unit: 'lb', category: 'produce' },
  { nameLower: 'broccoli rabe', cents: 399, unit: 'bunch', category: 'produce' },
  { nameLower: 'cauliflower', cents: 349, unit: 'head', category: 'produce' },
  { nameLower: 'asparagus', cents: 499, unit: 'lb', category: 'produce' },
  { nameLower: 'artichoke', cents: 349, unit: 'each', category: 'produce' },
  { nameLower: 'artichokes', cents: 349, unit: 'each', category: 'produce' },
  { nameLower: 'artichoke hearts', cents: 499, unit: '14 oz', category: 'produce' },

  // Squash & gourds
  { nameLower: 'zucchini', cents: 229, unit: 'lb', category: 'produce' },
  { nameLower: 'yellow squash', cents: 229, unit: 'lb', category: 'produce' },
  { nameLower: 'summer squash', cents: 229, unit: 'lb', category: 'produce' },
  { nameLower: 'butternut squash', cents: 199, unit: 'lb', category: 'produce' },
  { nameLower: 'acorn squash', cents: 179, unit: 'lb', category: 'produce' },
  { nameLower: 'spaghetti squash', cents: 179, unit: 'lb', category: 'produce' },
  { nameLower: 'delicata squash', cents: 249, unit: 'lb', category: 'produce' },
  { nameLower: 'kabocha squash', cents: 199, unit: 'lb', category: 'produce' },
  { nameLower: 'pumpkin', cents: 149, unit: 'lb', category: 'produce' },
  { nameLower: 'cucumber', cents: 129, unit: 'each', category: 'produce' },
  { nameLower: 'cucumbers', cents: 129, unit: 'each', category: 'produce' },
  { nameLower: 'english cucumber', cents: 199, unit: 'each', category: 'produce' },
  { nameLower: 'eggplant', cents: 249, unit: 'lb', category: 'produce' },

  // Other vegetables
  { nameLower: 'celery', cents: 199, unit: 'bunch', category: 'produce' },
  { nameLower: 'corn', cents: 99, unit: 'each', category: 'produce' },
  { nameLower: 'corn on the cob', cents: 99, unit: 'each', category: 'produce' },
  { nameLower: 'sweet corn', cents: 99, unit: 'each', category: 'produce' },
  { nameLower: 'fennel', cents: 349, unit: 'bulb', category: 'produce' },
  { nameLower: 'fennel bulb', cents: 349, unit: 'bulb', category: 'produce' },
  { nameLower: 'mushroom', cents: 499, unit: 'lb', category: 'produce' },
  { nameLower: 'mushrooms', cents: 499, unit: 'lb', category: 'produce' },
  { nameLower: 'white mushrooms', cents: 449, unit: 'lb', category: 'produce' },
  { nameLower: 'button mushrooms', cents: 449, unit: 'lb', category: 'produce' },
  { nameLower: 'cremini mushrooms', cents: 499, unit: 'lb', category: 'produce' },
  { nameLower: 'baby bella mushrooms', cents: 499, unit: 'lb', category: 'produce' },
  { nameLower: 'portobello mushrooms', cents: 599, unit: 'lb', category: 'produce' },
  { nameLower: 'portobello', cents: 599, unit: 'lb', category: 'produce' },
  { nameLower: 'shiitake mushrooms', cents: 799, unit: 'lb', category: 'produce' },
  { nameLower: 'oyster mushrooms', cents: 899, unit: 'lb', category: 'produce' },
  { nameLower: 'chanterelle mushrooms', cents: 1999, unit: 'lb', category: 'produce' },
  { nameLower: 'porcini mushrooms', cents: 2499, unit: 'lb', category: 'produce' },
  { nameLower: 'morel mushrooms', cents: 2999, unit: 'lb', category: 'produce' },
  { nameLower: 'enoki mushrooms', cents: 499, unit: '7 oz', category: 'produce' },
  { nameLower: 'maitake mushrooms', cents: 1299, unit: 'lb', category: 'produce' },
  { nameLower: 'green beans', cents: 299, unit: 'lb', category: 'produce' },
  { nameLower: 'string beans', cents: 299, unit: 'lb', category: 'produce' },
  { nameLower: 'snap peas', cents: 449, unit: 'lb', category: 'produce' },
  { nameLower: 'snow peas', cents: 449, unit: 'lb', category: 'produce' },
  { nameLower: 'peas', cents: 349, unit: 'lb', category: 'produce' },
  { nameLower: 'english peas', cents: 399, unit: 'lb', category: 'produce' },
  { nameLower: 'okra', cents: 399, unit: 'lb', category: 'produce' },
  { nameLower: 'rhubarb', cents: 499, unit: 'lb', category: 'produce' },
  { nameLower: 'tomatillo', cents: 249, unit: 'lb', category: 'produce' },
  { nameLower: 'tomatillos', cents: 249, unit: 'lb', category: 'produce' },
  { nameLower: 'plantain', cents: 99, unit: 'each', category: 'produce' },
  { nameLower: 'plantains', cents: 99, unit: 'each', category: 'produce' },
  { nameLower: 'jackfruit', cents: 399, unit: 'lb', category: 'produce' },
  { nameLower: 'hearts of palm', cents: 399, unit: '14 oz', category: 'produce' },
  { nameLower: 'bamboo shoots', cents: 249, unit: '8 oz', category: 'produce' },
  { nameLower: 'water chestnuts', cents: 249, unit: '8 oz', category: 'produce' },
  { nameLower: 'bean sprouts', cents: 199, unit: 'lb', category: 'produce' },

  // Fruits
  { nameLower: 'lemon', cents: 99, unit: 'each', category: 'produce' },
  { nameLower: 'lemons', cents: 99, unit: 'each', category: 'produce' },
  { nameLower: 'lime', cents: 79, unit: 'each', category: 'produce' },
  { nameLower: 'limes', cents: 79, unit: 'each', category: 'produce' },
  { nameLower: 'orange', cents: 129, unit: 'each', category: 'produce' },
  { nameLower: 'oranges', cents: 129, unit: 'each', category: 'produce' },
  { nameLower: 'grapefruit', cents: 149, unit: 'each', category: 'produce' },
  { nameLower: 'tangerine', cents: 99, unit: 'each', category: 'produce' },
  { nameLower: 'clementine', cents: 79, unit: 'each', category: 'produce' },
  { nameLower: 'apple', cents: 199, unit: 'lb', category: 'produce' },
  { nameLower: 'apples', cents: 199, unit: 'lb', category: 'produce' },
  { nameLower: 'granny smith apple', cents: 199, unit: 'lb', category: 'produce' },
  { nameLower: 'banana', cents: 69, unit: 'lb', category: 'produce' },
  { nameLower: 'bananas', cents: 69, unit: 'lb', category: 'produce' },
  { nameLower: 'avocado', cents: 199, unit: 'each', category: 'produce' },
  { nameLower: 'avocados', cents: 199, unit: 'each', category: 'produce' },
  { nameLower: 'pear', cents: 249, unit: 'lb', category: 'produce' },
  { nameLower: 'pears', cents: 249, unit: 'lb', category: 'produce' },
  { nameLower: 'peach', cents: 299, unit: 'lb', category: 'produce' },
  { nameLower: 'peaches', cents: 299, unit: 'lb', category: 'produce' },
  { nameLower: 'plum', cents: 299, unit: 'lb', category: 'produce' },
  { nameLower: 'plums', cents: 299, unit: 'lb', category: 'produce' },
  { nameLower: 'nectarine', cents: 299, unit: 'lb', category: 'produce' },
  { nameLower: 'apricot', cents: 399, unit: 'lb', category: 'produce' },
  { nameLower: 'cherry', cents: 499, unit: 'lb', category: 'produce' },
  { nameLower: 'cherries', cents: 499, unit: 'lb', category: 'produce' },
  { nameLower: 'strawberry', cents: 399, unit: 'lb', category: 'produce' },
  { nameLower: 'strawberries', cents: 399, unit: 'lb', category: 'produce' },
  { nameLower: 'blueberry', cents: 449, unit: 'pint', category: 'produce' },
  { nameLower: 'blueberries', cents: 449, unit: 'pint', category: 'produce' },
  { nameLower: 'raspberry', cents: 499, unit: '6 oz', category: 'produce' },
  { nameLower: 'raspberries', cents: 499, unit: '6 oz', category: 'produce' },
  { nameLower: 'blackberry', cents: 499, unit: '6 oz', category: 'produce' },
  { nameLower: 'blackberries', cents: 499, unit: '6 oz', category: 'produce' },
  { nameLower: 'cranberries', cents: 399, unit: '12 oz', category: 'produce' },
  { nameLower: 'grapes', cents: 299, unit: 'lb', category: 'produce' },
  { nameLower: 'red grapes', cents: 299, unit: 'lb', category: 'produce' },
  { nameLower: 'watermelon', cents: 49, unit: 'lb', category: 'produce' },
  { nameLower: 'cantaloupe', cents: 79, unit: 'lb', category: 'produce' },
  { nameLower: 'honeydew', cents: 79, unit: 'lb', category: 'produce' },
  { nameLower: 'pineapple', cents: 399, unit: 'each', category: 'produce' },
  { nameLower: 'mango', cents: 199, unit: 'each', category: 'produce' },
  { nameLower: 'mangoes', cents: 199, unit: 'each', category: 'produce' },
  { nameLower: 'papaya', cents: 299, unit: 'each', category: 'produce' },
  { nameLower: 'kiwi', cents: 79, unit: 'each', category: 'produce' },
  { nameLower: 'pomegranate', cents: 299, unit: 'each', category: 'produce' },
  { nameLower: 'coconut', cents: 249, unit: 'each', category: 'produce' },
  { nameLower: 'fig', cents: 699, unit: 'lb', category: 'produce' },
  { nameLower: 'figs', cents: 699, unit: 'lb', category: 'produce' },
  { nameLower: 'passion fruit', cents: 199, unit: 'each', category: 'produce' },
  { nameLower: 'dragon fruit', cents: 599, unit: 'each', category: 'produce' },
  { nameLower: 'persimmon', cents: 199, unit: 'each', category: 'produce' },
  { nameLower: 'lychee', cents: 899, unit: 'lb', category: 'produce' },
  { nameLower: 'guava', cents: 499, unit: 'lb', category: 'produce' },
  { nameLower: 'star fruit', cents: 499, unit: 'lb', category: 'produce' },

  // Dried fruits
  { nameLower: 'raisins', cents: 399, unit: 'lb', category: 'produce' },
  { nameLower: 'golden raisins', cents: 449, unit: 'lb', category: 'produce' },
  { nameLower: 'dried cranberries', cents: 499, unit: 'lb', category: 'produce' },
  { nameLower: 'dried apricots', cents: 599, unit: 'lb', category: 'produce' },
  { nameLower: 'dried figs', cents: 699, unit: 'lb', category: 'produce' },
  { nameLower: 'dates', cents: 599, unit: 'lb', category: 'produce' },
  { nameLower: 'medjool dates', cents: 999, unit: 'lb', category: 'produce' },
  { nameLower: 'prunes', cents: 449, unit: 'lb', category: 'produce' },
  { nameLower: 'dried mango', cents: 599, unit: 'lb', category: 'produce' },
  { nameLower: 'dried coconut', cents: 499, unit: 'lb', category: 'produce' },
  { nameLower: 'shredded coconut', cents: 449, unit: 'lb', category: 'produce' },
  { nameLower: 'currants', cents: 599, unit: 'lb', category: 'produce' },

  // ══════════════════════════════════════════════════════════════════════════
  // OILS & FATS
  // ══════════════════════════════════════════════════════════════════════════
  { nameLower: 'olive oil', cents: 1299, unit: '16 oz', category: 'oil' },
  { nameLower: 'extra virgin olive oil', cents: 1499, unit: '16 oz', category: 'oil' },
  { nameLower: 'vegetable oil', cents: 499, unit: '32 oz', category: 'oil' },
  { nameLower: 'canola oil', cents: 499, unit: '32 oz', category: 'oil' },
  { nameLower: 'sesame oil', cents: 699, unit: '8 oz', category: 'oil' },
  { nameLower: 'toasted sesame oil', cents: 749, unit: '8 oz', category: 'oil' },
  { nameLower: 'coconut oil', cents: 899, unit: '14 oz', category: 'oil' },
  { nameLower: 'avocado oil', cents: 999, unit: '16 oz', category: 'oil' },
  { nameLower: 'peanut oil', cents: 699, unit: '32 oz', category: 'oil' },
  { nameLower: 'grapeseed oil', cents: 799, unit: '16 oz', category: 'oil' },
  { nameLower: 'walnut oil', cents: 999, unit: '8 oz', category: 'oil' },
  { nameLower: 'truffle oil', cents: 1499, unit: '8 oz', category: 'oil' },
  { nameLower: 'chili oil', cents: 599, unit: '8 oz', category: 'oil' },
  { nameLower: 'corn oil', cents: 499, unit: '32 oz', category: 'oil' },
  { nameLower: 'lard', cents: 399, unit: 'lb', category: 'oil' },
  { nameLower: 'shortening', cents: 449, unit: 'lb', category: 'oil' },
  { nameLower: 'cooking spray', cents: 349, unit: '6 oz', category: 'oil' },

  // ══════════════════════════════════════════════════════════════════════════
  // BAKING
  // ══════════════════════════════════════════════════════════════════════════
  { nameLower: 'flour', cents: 449, unit: '5 lb', category: 'baking' },
  { nameLower: 'all-purpose flour', cents: 449, unit: '5 lb', category: 'baking' },
  { nameLower: 'all purpose flour', cents: 449, unit: '5 lb', category: 'baking' },
  { nameLower: 'bread flour', cents: 549, unit: '5 lb', category: 'baking' },
  { nameLower: 'cake flour', cents: 449, unit: '2 lb', category: 'baking' },
  { nameLower: 'pastry flour', cents: 499, unit: '5 lb', category: 'baking' },
  { nameLower: 'whole wheat flour', cents: 499, unit: '5 lb', category: 'baking' },
  { nameLower: 'rye flour', cents: 599, unit: '5 lb', category: 'baking' },
  { nameLower: 'almond flour', cents: 899, unit: 'lb', category: 'baking' },
  { nameLower: 'coconut flour', cents: 699, unit: 'lb', category: 'baking' },
  { nameLower: 'semolina flour', cents: 399, unit: 'lb', category: 'baking' },
  { nameLower: 'semolina', cents: 399, unit: 'lb', category: 'baking' },
  { nameLower: 'cornmeal', cents: 299, unit: '2 lb', category: 'baking' },
  { nameLower: 'polenta', cents: 399, unit: 'lb', category: 'baking' },
  { nameLower: 'cornstarch', cents: 249, unit: '16 oz', category: 'baking' },
  { nameLower: 'corn starch', cents: 249, unit: '16 oz', category: 'baking' },
  { nameLower: 'tapioca starch', cents: 399, unit: 'lb', category: 'baking' },
  { nameLower: 'potato starch', cents: 399, unit: 'lb', category: 'baking' },
  { nameLower: 'arrowroot', cents: 499, unit: 'lb', category: 'baking' },
  { nameLower: 'sugar', cents: 399, unit: '4 lb', category: 'baking' },
  { nameLower: 'granulated sugar', cents: 399, unit: '4 lb', category: 'baking' },
  { nameLower: 'brown sugar', cents: 349, unit: '2 lb', category: 'baking' },
  { nameLower: 'light brown sugar', cents: 349, unit: '2 lb', category: 'baking' },
  { nameLower: 'dark brown sugar', cents: 349, unit: '2 lb', category: 'baking' },
  { nameLower: 'powdered sugar', cents: 299, unit: '2 lb', category: 'baking' },
  { nameLower: 'confectioners sugar', cents: 299, unit: '2 lb', category: 'baking' },
  { nameLower: 'turbinado sugar', cents: 449, unit: '2 lb', category: 'baking' },
  { nameLower: 'coconut sugar', cents: 599, unit: 'lb', category: 'baking' },
  { nameLower: 'baking soda', cents: 149, unit: '16 oz', category: 'baking' },
  { nameLower: 'baking powder', cents: 199, unit: '8 oz', category: 'baking' },
  { nameLower: 'cream of tartar', cents: 399, unit: '4 oz', category: 'baking' },
  { nameLower: 'yeast', cents: 199, unit: '0.75 oz', category: 'baking' },
  { nameLower: 'active dry yeast', cents: 199, unit: '0.75 oz', category: 'baking' },
  { nameLower: 'instant yeast', cents: 199, unit: '0.75 oz', category: 'baking' },
  { nameLower: 'cocoa powder', cents: 449, unit: '8 oz', category: 'baking' },
  { nameLower: 'dutch process cocoa', cents: 549, unit: '8 oz', category: 'baking' },
  { nameLower: 'vanilla extract', cents: 699, unit: '4 oz', category: 'baking' },
  { nameLower: 'vanilla bean', cents: 499, unit: 'each', category: 'baking' },
  { nameLower: 'vanilla bean paste', cents: 999, unit: '4 oz', category: 'baking' },
  { nameLower: 'almond extract', cents: 399, unit: '4 oz', category: 'baking' },
  { nameLower: 'peppermint extract', cents: 399, unit: '4 oz', category: 'baking' },
  { nameLower: 'chocolate chips', cents: 499, unit: '12 oz', category: 'baking' },
  { nameLower: 'dark chocolate', cents: 699, unit: '12 oz', category: 'baking' },
  { nameLower: 'milk chocolate', cents: 599, unit: '12 oz', category: 'baking' },
  { nameLower: 'white chocolate', cents: 599, unit: '12 oz', category: 'baking' },
  { nameLower: 'baking chocolate', cents: 499, unit: '4 oz', category: 'baking' },
  { nameLower: 'gelatin', cents: 399, unit: '1 oz', category: 'baking' },
  { nameLower: 'gelatin sheets', cents: 599, unit: '1 oz', category: 'baking' },
  { nameLower: 'pectin', cents: 499, unit: '1.75 oz', category: 'baking' },
  { nameLower: 'food coloring', cents: 349, unit: '1 oz', category: 'baking' },
  { nameLower: 'sprinkles', cents: 399, unit: '4 oz', category: 'baking' },
  { nameLower: 'meringue powder', cents: 799, unit: '4 oz', category: 'baking' },
  { nameLower: 'pie crust', cents: 399, unit: 'each', category: 'baking' },
  { nameLower: 'puff pastry', cents: 599, unit: '17.3 oz', category: 'baking' },
  { nameLower: 'phyllo dough', cents: 499, unit: '16 oz', category: 'baking' },

  // ══════════════════════════════════════════════════════════════════════════
  // PANTRY
  // ══════════════════════════════════════════════════════════════════════════

  // Pasta & noodles
  { nameLower: 'pasta', cents: 199, unit: 'lb', category: 'pantry' },
  { nameLower: 'spaghetti', cents: 199, unit: 'lb', category: 'pantry' },
  { nameLower: 'penne', cents: 199, unit: 'lb', category: 'pantry' },
  { nameLower: 'rigatoni', cents: 199, unit: 'lb', category: 'pantry' },
  { nameLower: 'fusilli', cents: 199, unit: 'lb', category: 'pantry' },
  { nameLower: 'farfalle', cents: 199, unit: 'lb', category: 'pantry' },
  { nameLower: 'linguine', cents: 199, unit: 'lb', category: 'pantry' },
  { nameLower: 'fettuccine', cents: 249, unit: 'lb', category: 'pantry' },
  { nameLower: 'angel hair', cents: 199, unit: 'lb', category: 'pantry' },
  { nameLower: 'lasagna noodles', cents: 249, unit: 'lb', category: 'pantry' },
  { nameLower: 'macaroni', cents: 149, unit: 'lb', category: 'pantry' },
  { nameLower: 'orzo', cents: 249, unit: 'lb', category: 'pantry' },
  { nameLower: 'egg noodles', cents: 249, unit: 'lb', category: 'pantry' },
  { nameLower: 'ramen noodles', cents: 299, unit: 'lb', category: 'pantry' },
  { nameLower: 'rice noodles', cents: 349, unit: 'lb', category: 'pantry' },
  { nameLower: 'udon noodles', cents: 349, unit: 'lb', category: 'pantry' },
  { nameLower: 'soba noodles', cents: 399, unit: 'lb', category: 'pantry' },
  { nameLower: 'glass noodles', cents: 349, unit: '8 oz', category: 'pantry' },
  { nameLower: 'vermicelli', cents: 249, unit: 'lb', category: 'pantry' },
  { nameLower: 'gnocchi', cents: 399, unit: 'lb', category: 'pantry' },
  { nameLower: 'couscous', cents: 349, unit: 'lb', category: 'pantry' },

  // Rice & grains
  { nameLower: 'rice', cents: 249, unit: 'lb', category: 'pantry' },
  { nameLower: 'white rice', cents: 199, unit: 'lb', category: 'pantry' },
  { nameLower: 'brown rice', cents: 249, unit: 'lb', category: 'pantry' },
  { nameLower: 'basmati rice', cents: 299, unit: 'lb', category: 'pantry' },
  { nameLower: 'jasmine rice', cents: 279, unit: 'lb', category: 'pantry' },
  { nameLower: 'arborio rice', cents: 449, unit: 'lb', category: 'pantry' },
  { nameLower: 'sushi rice', cents: 349, unit: 'lb', category: 'pantry' },
  { nameLower: 'wild rice', cents: 799, unit: 'lb', category: 'pantry' },
  { nameLower: 'quinoa', cents: 599, unit: 'lb', category: 'pantry' },
  { nameLower: 'bulgur', cents: 349, unit: 'lb', category: 'pantry' },
  { nameLower: 'barley', cents: 249, unit: 'lb', category: 'pantry' },
  { nameLower: 'pearl barley', cents: 249, unit: 'lb', category: 'pantry' },
  { nameLower: 'farro', cents: 499, unit: 'lb', category: 'pantry' },
  { nameLower: 'freekeh', cents: 599, unit: 'lb', category: 'pantry' },
  { nameLower: 'millet', cents: 349, unit: 'lb', category: 'pantry' },
  { nameLower: 'buckwheat', cents: 399, unit: 'lb', category: 'pantry' },
  { nameLower: 'oats', cents: 299, unit: 'lb', category: 'pantry' },
  { nameLower: 'rolled oats', cents: 299, unit: 'lb', category: 'pantry' },
  { nameLower: 'steel cut oats', cents: 399, unit: 'lb', category: 'pantry' },
  { nameLower: 'grits', cents: 249, unit: 'lb', category: 'pantry' },

  // Beans & legumes
  { nameLower: 'lentils', cents: 249, unit: 'lb', category: 'pantry' },
  { nameLower: 'red lentils', cents: 299, unit: 'lb', category: 'pantry' },
  { nameLower: 'green lentils', cents: 299, unit: 'lb', category: 'pantry' },
  { nameLower: 'black lentils', cents: 349, unit: 'lb', category: 'pantry' },
  { nameLower: 'dried beans', cents: 249, unit: 'lb', category: 'pantry' },
  { nameLower: 'black beans', cents: 199, unit: '15 oz', category: 'pantry' },
  { nameLower: 'kidney beans', cents: 199, unit: '15 oz', category: 'pantry' },
  { nameLower: 'pinto beans', cents: 199, unit: '15 oz', category: 'pantry' },
  { nameLower: 'navy beans', cents: 199, unit: '15 oz', category: 'pantry' },
  { nameLower: 'great northern beans', cents: 199, unit: '15 oz', category: 'pantry' },
  { nameLower: 'cannellini beans', cents: 229, unit: '15 oz', category: 'pantry' },
  { nameLower: 'white beans', cents: 229, unit: '15 oz', category: 'pantry' },
  { nameLower: 'garbanzo beans', cents: 199, unit: '15 oz', category: 'pantry' },
  { nameLower: 'chickpeas', cents: 199, unit: '15 oz', category: 'pantry' },
  { nameLower: 'split peas', cents: 249, unit: 'lb', category: 'pantry' },
  { nameLower: 'lima beans', cents: 249, unit: '15 oz', category: 'pantry' },
  { nameLower: 'fava beans', cents: 349, unit: 'lb', category: 'pantry' },
  { nameLower: 'refried beans', cents: 199, unit: '15 oz', category: 'pantry' },
  { nameLower: 'baked beans', cents: 249, unit: '15 oz', category: 'pantry' },
  { nameLower: 'hummus', cents: 449, unit: '10 oz', category: 'pantry' },
  { nameLower: 'tahini', cents: 699, unit: '16 oz', category: 'pantry' },

  // Stocks & broths
  { nameLower: 'chicken stock', cents: 399, unit: 'qt', category: 'pantry' },
  { nameLower: 'chicken broth', cents: 399, unit: 'qt', category: 'pantry' },
  { nameLower: 'vegetable stock', cents: 349, unit: 'qt', category: 'pantry' },
  { nameLower: 'vegetable broth', cents: 349, unit: 'qt', category: 'pantry' },
  { nameLower: 'beef stock', cents: 449, unit: 'qt', category: 'pantry' },
  { nameLower: 'beef broth', cents: 449, unit: 'qt', category: 'pantry' },
  { nameLower: 'bone broth', cents: 599, unit: 'qt', category: 'pantry' },
  { nameLower: 'fish stock', cents: 499, unit: 'qt', category: 'pantry' },
  { nameLower: 'dashi', cents: 499, unit: 'qt', category: 'pantry' },
  { nameLower: 'bouillon cube', cents: 199, unit: '6 ct', category: 'pantry' },
  { nameLower: 'bouillon cubes', cents: 199, unit: '6 ct', category: 'pantry' },
  { nameLower: 'better than bouillon', cents: 599, unit: '8 oz', category: 'pantry' },

  // Breadcrumbs & coatings
  { nameLower: 'panko', cents: 299, unit: 'lb', category: 'pantry' },
  { nameLower: 'bread crumbs', cents: 249, unit: 'lb', category: 'pantry' },
  { nameLower: 'breadcrumbs', cents: 249, unit: 'lb', category: 'pantry' },
  { nameLower: 'croutons', cents: 299, unit: '5 oz', category: 'pantry' },

  // ══════════════════════════════════════════════════════════════════════════
  // CANNED GOODS
  // ══════════════════════════════════════════════════════════════════════════
  { nameLower: 'canned tomatoes', cents: 199, unit: '28 oz', category: 'canned' },
  { nameLower: 'crushed tomatoes', cents: 199, unit: '28 oz', category: 'canned' },
  { nameLower: 'diced tomatoes', cents: 179, unit: '14.5 oz', category: 'canned' },
  { nameLower: 'whole peeled tomatoes', cents: 249, unit: '28 oz', category: 'canned' },
  { nameLower: 'san marzano tomatoes', cents: 449, unit: '28 oz', category: 'canned' },
  { nameLower: 'tomato paste', cents: 149, unit: '6 oz', category: 'canned' },
  { nameLower: 'tomato sauce', cents: 149, unit: '15 oz', category: 'canned' },
  { nameLower: 'marinara sauce', cents: 399, unit: '24 oz', category: 'canned' },
  { nameLower: 'coconut milk', cents: 249, unit: '14 oz', category: 'canned' },
  { nameLower: 'canned pumpkin', cents: 299, unit: '15 oz', category: 'canned' },
  { nameLower: 'pumpkin puree', cents: 299, unit: '15 oz', category: 'canned' },
  { nameLower: 'canned corn', cents: 149, unit: '15 oz', category: 'canned' },
  { nameLower: 'canned tuna', cents: 249, unit: '5 oz', category: 'canned' },
  { nameLower: 'canned salmon', cents: 399, unit: '6 oz', category: 'canned' },
  { nameLower: 'canned crab', cents: 599, unit: '6 oz', category: 'canned' },
  { nameLower: 'roasted red peppers', cents: 349, unit: '12 oz', category: 'canned' },
  { nameLower: 'chipotles in adobo', cents: 299, unit: '7 oz', category: 'canned' },
  { nameLower: 'chipotle peppers', cents: 299, unit: '7 oz', category: 'canned' },
  { nameLower: 'green chilies', cents: 149, unit: '4 oz', category: 'canned' },
  { nameLower: 'olives', cents: 399, unit: '6 oz', category: 'canned' },
  { nameLower: 'black olives', cents: 299, unit: '6 oz', category: 'canned' },
  { nameLower: 'kalamata olives', cents: 499, unit: '6 oz', category: 'canned' },
  { nameLower: 'green olives', cents: 399, unit: '6 oz', category: 'canned' },
  { nameLower: 'sun dried tomatoes in oil', cents: 599, unit: '8 oz', category: 'canned' },
  { nameLower: 'pesto', cents: 499, unit: '6 oz', category: 'canned' },

  // ══════════════════════════════════════════════════════════════════════════
  // CONDIMENTS & SAUCES
  // ══════════════════════════════════════════════════════════════════════════
  { nameLower: 'soy sauce', cents: 349, unit: '10 oz', category: 'condiment' },
  { nameLower: 'tamari', cents: 499, unit: '10 oz', category: 'condiment' },
  { nameLower: 'fish sauce', cents: 399, unit: '12 oz', category: 'condiment' },
  { nameLower: 'oyster sauce', cents: 349, unit: '9 oz', category: 'condiment' },
  { nameLower: 'hoisin sauce', cents: 399, unit: '8 oz', category: 'condiment' },
  { nameLower: 'worcestershire sauce', cents: 299, unit: '10 oz', category: 'condiment' },
  { nameLower: 'hot sauce', cents: 349, unit: '12 oz', category: 'condiment' },
  { nameLower: 'sriracha', cents: 399, unit: '17 oz', category: 'condiment' },
  { nameLower: 'tabasco', cents: 299, unit: '5 oz', category: 'condiment' },
  { nameLower: 'sambal oelek', cents: 399, unit: '8 oz', category: 'condiment' },
  { nameLower: 'gochujang', cents: 599, unit: '8 oz', category: 'condiment' },
  { nameLower: 'miso paste', cents: 499, unit: '8 oz', category: 'condiment' },
  { nameLower: 'white miso', cents: 499, unit: '8 oz', category: 'condiment' },
  { nameLower: 'red miso', cents: 499, unit: '8 oz', category: 'condiment' },
  { nameLower: 'curry paste', cents: 399, unit: '4 oz', category: 'condiment' },
  { nameLower: 'red curry paste', cents: 399, unit: '4 oz', category: 'condiment' },
  { nameLower: 'green curry paste', cents: 399, unit: '4 oz', category: 'condiment' },
  { nameLower: 'harissa', cents: 499, unit: '4 oz', category: 'condiment' },
  { nameLower: 'dijon mustard', cents: 399, unit: '8 oz', category: 'condiment' },
  { nameLower: 'whole grain mustard', cents: 449, unit: '8 oz', category: 'condiment' },
  { nameLower: 'yellow mustard', cents: 199, unit: '14 oz', category: 'condiment' },
  { nameLower: 'ketchup', cents: 299, unit: '20 oz', category: 'condiment' },
  { nameLower: 'mayonnaise', cents: 499, unit: '30 oz', category: 'condiment' },
  { nameLower: 'mayo', cents: 499, unit: '30 oz', category: 'condiment' },
  { nameLower: 'relish', cents: 299, unit: '10 oz', category: 'condiment' },
  { nameLower: 'honey', cents: 699, unit: 'lb', category: 'condiment' },
  { nameLower: 'maple syrup', cents: 1299, unit: '12 oz', category: 'condiment' },
  { nameLower: 'molasses', cents: 499, unit: '12 oz', category: 'condiment' },
  { nameLower: 'corn syrup', cents: 399, unit: '16 oz', category: 'condiment' },
  { nameLower: 'agave nectar', cents: 599, unit: '11 oz', category: 'condiment' },
  { nameLower: 'balsamic vinegar', cents: 599, unit: '16 oz', category: 'condiment' },
  { nameLower: 'balsamic glaze', cents: 599, unit: '8 oz', category: 'condiment' },
  { nameLower: 'red wine vinegar', cents: 349, unit: '16 oz', category: 'condiment' },
  { nameLower: 'white wine vinegar', cents: 349, unit: '16 oz', category: 'condiment' },
  { nameLower: 'apple cider vinegar', cents: 349, unit: '16 oz', category: 'condiment' },
  { nameLower: 'rice vinegar', cents: 349, unit: '12 oz', category: 'condiment' },
  { nameLower: 'sherry vinegar', cents: 599, unit: '12 oz', category: 'condiment' },
  { nameLower: 'malt vinegar', cents: 349, unit: '12 oz', category: 'condiment' },
  { nameLower: 'white vinegar', cents: 199, unit: '16 oz', category: 'condiment' },
  { nameLower: 'capers', cents: 349, unit: '4 oz', category: 'condiment' },
  { nameLower: 'anchovy paste', cents: 399, unit: '2 oz', category: 'condiment' },
  { nameLower: 'bbq sauce', cents: 349, unit: '18 oz', category: 'condiment' },
  { nameLower: 'teriyaki sauce', cents: 399, unit: '10 oz', category: 'condiment' },
  { nameLower: 'ponzu', cents: 499, unit: '10 oz', category: 'condiment' },
  { nameLower: 'mirin', cents: 499, unit: '10 oz', category: 'condiment' },
  { nameLower: 'rice wine', cents: 399, unit: '10 oz', category: 'condiment' },
  { nameLower: 'cooking sherry', cents: 499, unit: '16 oz', category: 'condiment' },
  { nameLower: 'marsala wine', cents: 699, unit: '16 oz', category: 'condiment' },
  { nameLower: 'chutney', cents: 499, unit: '8 oz', category: 'condiment' },
  { nameLower: 'mango chutney', cents: 499, unit: '8 oz', category: 'condiment' },
  { nameLower: 'pickled ginger', cents: 399, unit: '6 oz', category: 'condiment' },
  { nameLower: 'wasabi', cents: 399, unit: '2 oz', category: 'condiment' },
  { nameLower: 'tamarind paste', cents: 399, unit: '8 oz', category: 'condiment' },
  { nameLower: 'pomegranate molasses', cents: 699, unit: '10 oz', category: 'condiment' },

  // ══════════════════════════════════════════════════════════════════════════
  // NUTS & SEEDS
  // ══════════════════════════════════════════════════════════════════════════
  { nameLower: 'almonds', cents: 799, unit: 'lb', category: 'nuts_seeds' },
  { nameLower: 'sliced almonds', cents: 899, unit: 'lb', category: 'nuts_seeds' },
  { nameLower: 'slivered almonds', cents: 899, unit: 'lb', category: 'nuts_seeds' },
  { nameLower: 'walnuts', cents: 899, unit: 'lb', category: 'nuts_seeds' },
  { nameLower: 'pecans', cents: 1099, unit: 'lb', category: 'nuts_seeds' },
  { nameLower: 'cashews', cents: 999, unit: 'lb', category: 'nuts_seeds' },
  { nameLower: 'peanuts', cents: 399, unit: 'lb', category: 'nuts_seeds' },
  { nameLower: 'pine nuts', cents: 1999, unit: 'lb', category: 'nuts_seeds' },
  { nameLower: 'pistachios', cents: 1299, unit: 'lb', category: 'nuts_seeds' },
  { nameLower: 'macadamia nuts', cents: 1999, unit: 'lb', category: 'nuts_seeds' },
  { nameLower: 'hazelnuts', cents: 1299, unit: 'lb', category: 'nuts_seeds' },
  { nameLower: 'brazil nuts', cents: 999, unit: 'lb', category: 'nuts_seeds' },
  { nameLower: 'chestnuts', cents: 899, unit: 'lb', category: 'nuts_seeds' },
  { nameLower: 'mixed nuts', cents: 899, unit: 'lb', category: 'nuts_seeds' },
  { nameLower: 'peanut butter', cents: 499, unit: '16 oz', category: 'nuts_seeds' },
  { nameLower: 'almond butter', cents: 999, unit: '16 oz', category: 'nuts_seeds' },
  { nameLower: 'cashew butter', cents: 1099, unit: '16 oz', category: 'nuts_seeds' },
  { nameLower: 'sunflower seeds', cents: 399, unit: 'lb', category: 'nuts_seeds' },
  { nameLower: 'pumpkin seeds', cents: 499, unit: 'lb', category: 'nuts_seeds' },
  { nameLower: 'pepitas', cents: 499, unit: 'lb', category: 'nuts_seeds' },
  { nameLower: 'sesame seeds', cents: 499, unit: 'lb', category: 'nuts_seeds' },
  { nameLower: 'black sesame seeds', cents: 699, unit: 'lb', category: 'nuts_seeds' },
  { nameLower: 'chia seeds', cents: 699, unit: 'lb', category: 'nuts_seeds' },
  { nameLower: 'flax seeds', cents: 399, unit: 'lb', category: 'nuts_seeds' },
  { nameLower: 'flaxseed', cents: 399, unit: 'lb', category: 'nuts_seeds' },
  { nameLower: 'hemp seeds', cents: 999, unit: 'lb', category: 'nuts_seeds' },
  { nameLower: 'poppy seeds', cents: 599, unit: 'lb', category: 'nuts_seeds' },

  // ══════════════════════════════════════════════════════════════════════════
  // SPICES
  // ══════════════════════════════════════════════════════════════════════════
  { nameLower: 'black pepper', cents: 399, unit: '4 oz', category: 'spice' },
  { nameLower: 'black peppercorns', cents: 499, unit: '4 oz', category: 'spice' },
  { nameLower: 'white pepper', cents: 499, unit: '4 oz', category: 'spice' },
  { nameLower: 'kosher salt', cents: 299, unit: '3 lb', category: 'spice' },
  { nameLower: 'sea salt', cents: 449, unit: 'lb', category: 'spice' },
  { nameLower: 'flaky salt', cents: 799, unit: '4 oz', category: 'spice' },
  { nameLower: 'maldon salt', cents: 899, unit: '4 oz', category: 'spice' },
  { nameLower: 'pink himalayan salt', cents: 499, unit: 'lb', category: 'spice' },
  { nameLower: 'table salt', cents: 149, unit: '26 oz', category: 'spice' },
  { nameLower: 'cumin', cents: 349, unit: '4 oz', category: 'spice' },
  { nameLower: 'ground cumin', cents: 349, unit: '4 oz', category: 'spice' },
  { nameLower: 'cumin seeds', cents: 399, unit: '4 oz', category: 'spice' },
  { nameLower: 'coriander', cents: 349, unit: '4 oz', category: 'spice' },
  { nameLower: 'ground coriander', cents: 349, unit: '4 oz', category: 'spice' },
  { nameLower: 'coriander seeds', cents: 399, unit: '4 oz', category: 'spice' },
  { nameLower: 'paprika', cents: 349, unit: '4 oz', category: 'spice' },
  { nameLower: 'smoked paprika', cents: 449, unit: '4 oz', category: 'spice' },
  { nameLower: 'hungarian paprika', cents: 499, unit: '4 oz', category: 'spice' },
  { nameLower: 'cinnamon', cents: 349, unit: '4 oz', category: 'spice' },
  { nameLower: 'ground cinnamon', cents: 349, unit: '4 oz', category: 'spice' },
  { nameLower: 'cinnamon sticks', cents: 499, unit: '1 oz', category: 'spice' },
  { nameLower: 'nutmeg', cents: 499, unit: '2 oz', category: 'spice' },
  { nameLower: 'ground nutmeg', cents: 499, unit: '2 oz', category: 'spice' },
  { nameLower: 'whole nutmeg', cents: 599, unit: '2 oz', category: 'spice' },
  { nameLower: 'cloves', cents: 499, unit: '2 oz', category: 'spice' },
  { nameLower: 'ground cloves', cents: 499, unit: '2 oz', category: 'spice' },
  { nameLower: 'allspice', cents: 449, unit: '2 oz', category: 'spice' },
  { nameLower: 'ground allspice', cents: 449, unit: '2 oz', category: 'spice' },
  { nameLower: 'cardamom', cents: 799, unit: '2 oz', category: 'spice' },
  { nameLower: 'ground cardamom', cents: 799, unit: '2 oz', category: 'spice' },
  { nameLower: 'cardamom pods', cents: 899, unit: '2 oz', category: 'spice' },
  { nameLower: 'star anise', cents: 499, unit: '1 oz', category: 'spice' },
  { nameLower: 'anise seed', cents: 399, unit: '2 oz', category: 'spice' },
  { nameLower: 'fennel seeds', cents: 399, unit: '2 oz', category: 'spice' },
  { nameLower: 'mustard seeds', cents: 349, unit: '2 oz', category: 'spice' },
  { nameLower: 'celery seed', cents: 349, unit: '2 oz', category: 'spice' },
  { nameLower: 'caraway seeds', cents: 449, unit: '2 oz', category: 'spice' },
  { nameLower: 'red pepper flakes', cents: 349, unit: '4 oz', category: 'spice' },
  { nameLower: 'crushed red pepper', cents: 349, unit: '4 oz', category: 'spice' },
  { nameLower: 'cayenne pepper', cents: 399, unit: '4 oz', category: 'spice' },
  { nameLower: 'cayenne', cents: 399, unit: '4 oz', category: 'spice' },
  { nameLower: 'chili powder', cents: 349, unit: '4 oz', category: 'spice' },
  { nameLower: 'ancho chili powder', cents: 499, unit: '4 oz', category: 'spice' },
  { nameLower: 'chipotle powder', cents: 499, unit: '4 oz', category: 'spice' },
  { nameLower: 'turmeric', cents: 399, unit: '4 oz', category: 'spice' },
  { nameLower: 'ground turmeric', cents: 399, unit: '4 oz', category: 'spice' },
  { nameLower: 'ginger powder', cents: 399, unit: '4 oz', category: 'spice' },
  { nameLower: 'ground ginger', cents: 399, unit: '4 oz', category: 'spice' },
  { nameLower: 'garlic powder', cents: 349, unit: '4 oz', category: 'spice' },
  { nameLower: 'onion powder', cents: 349, unit: '4 oz', category: 'spice' },
  { nameLower: 'curry powder', cents: 449, unit: '4 oz', category: 'spice' },
  { nameLower: 'garam masala', cents: 599, unit: '4 oz', category: 'spice' },
  { nameLower: 'five spice', cents: 499, unit: '2 oz', category: 'spice' },
  { nameLower: 'five spice powder', cents: 499, unit: '2 oz', category: 'spice' },
  { nameLower: 'ras el hanout', cents: 699, unit: '2 oz', category: 'spice' },
  { nameLower: "za'atar", cents: 599, unit: '2 oz', category: 'spice' },
  { nameLower: 'zaatar', cents: 599, unit: '2 oz', category: 'spice' },
  { nameLower: 'sumac', cents: 599, unit: '2 oz', category: 'spice' },
  { nameLower: 'saffron', cents: 999, unit: '0.5 g', category: 'spice' },
  { nameLower: 'saffron threads', cents: 999, unit: '0.5 g', category: 'spice' },
  { nameLower: 'vanilla powder', cents: 1299, unit: '1 oz', category: 'spice' },
  { nameLower: 'fenugreek', cents: 399, unit: '2 oz', category: 'spice' },
  { nameLower: 'fenugreek seeds', cents: 399, unit: '2 oz', category: 'spice' },
  { nameLower: 'asafoetida', cents: 499, unit: '2 oz', category: 'spice' },
  { nameLower: 'hing', cents: 499, unit: '2 oz', category: 'spice' },
  { nameLower: 'nigella seeds', cents: 499, unit: '2 oz', category: 'spice' },
  { nameLower: 'achiote', cents: 399, unit: '2 oz', category: 'spice' },
  { nameLower: 'annatto', cents: 399, unit: '2 oz', category: 'spice' },
  { nameLower: 'bay leaves', cents: 349, unit: '0.5 oz', category: 'spice' },
  { nameLower: 'bay leaf', cents: 349, unit: '0.5 oz', category: 'spice' },
  { nameLower: 'juniper berries', cents: 599, unit: '1 oz', category: 'spice' },
  { nameLower: 'szechuan peppercorns', cents: 699, unit: '2 oz', category: 'spice' },
  { nameLower: 'msg', cents: 299, unit: '4 oz', category: 'spice' },
  { nameLower: 'tajin', cents: 399, unit: '5 oz', category: 'spice' },
  { nameLower: 'everything bagel seasoning', cents: 399, unit: '3 oz', category: 'spice' },
  { nameLower: 'italian seasoning', cents: 349, unit: '2 oz', category: 'spice' },
  { nameLower: 'herbs de provence', cents: 499, unit: '2 oz', category: 'spice' },
  { nameLower: 'old bay seasoning', cents: 399, unit: '2 oz', category: 'spice' },
  { nameLower: 'taco seasoning', cents: 149, unit: '1 oz', category: 'spice' },
  { nameLower: 'jerk seasoning', cents: 499, unit: '4 oz', category: 'spice' },
  { nameLower: 'berbere', cents: 699, unit: '2 oz', category: 'spice' },
  { nameLower: 'dried chile', cents: 499, unit: '3 oz', category: 'spice' },
  { nameLower: 'dried chilies', cents: 499, unit: '3 oz', category: 'spice' },
  { nameLower: 'guajillo chile', cents: 499, unit: '3 oz', category: 'spice' },
  { nameLower: 'ancho chile', cents: 499, unit: '3 oz', category: 'spice' },
  { nameLower: 'chipotle chile', cents: 499, unit: '3 oz', category: 'spice' },
  { nameLower: 'pasilla chile', cents: 499, unit: '3 oz', category: 'spice' },
  { nameLower: 'dried porcini', cents: 1499, unit: '1 oz', category: 'spice' },
  { nameLower: 'dried mushrooms', cents: 999, unit: '1 oz', category: 'spice' },

  // ══════════════════════════════════════════════════════════════════════════
  // HERBS (DRIED)
  // ══════════════════════════════════════════════════════════════════════════
  { nameLower: 'dried oregano', cents: 299, unit: '4 oz', category: 'dry_herb' },
  { nameLower: 'dried thyme', cents: 299, unit: '4 oz', category: 'dry_herb' },
  { nameLower: 'dried basil', cents: 299, unit: '4 oz', category: 'dry_herb' },
  { nameLower: 'dried rosemary', cents: 299, unit: '4 oz', category: 'dry_herb' },
  { nameLower: 'dried parsley', cents: 249, unit: '4 oz', category: 'dry_herb' },
  { nameLower: 'dried dill', cents: 299, unit: '2 oz', category: 'dry_herb' },
  { nameLower: 'dried tarragon', cents: 399, unit: '2 oz', category: 'dry_herb' },
  { nameLower: 'dried sage', cents: 299, unit: '2 oz', category: 'dry_herb' },
  { nameLower: 'dried marjoram', cents: 299, unit: '2 oz', category: 'dry_herb' },
  { nameLower: 'dried lavender', cents: 599, unit: '2 oz', category: 'dry_herb' },
  { nameLower: 'dried mint', cents: 349, unit: '2 oz', category: 'dry_herb' },
  { nameLower: 'curry leaves', cents: 399, unit: '1 oz', category: 'dry_herb' },
  { nameLower: 'kaffir lime leaves', cents: 499, unit: '1 oz', category: 'dry_herb' },
  { nameLower: 'lemongrass', cents: 299, unit: 'each', category: 'dry_herb' },

  // ══════════════════════════════════════════════════════════════════════════
  // HERBS (FRESH)
  // ══════════════════════════════════════════════════════════════════════════
  { nameLower: 'basil', cents: 299, unit: 'bunch', category: 'fresh_herb' },
  { nameLower: 'fresh basil', cents: 299, unit: 'bunch', category: 'fresh_herb' },
  { nameLower: 'thai basil', cents: 349, unit: 'bunch', category: 'fresh_herb' },
  { nameLower: 'parsley', cents: 199, unit: 'bunch', category: 'fresh_herb' },
  { nameLower: 'flat-leaf parsley', cents: 199, unit: 'bunch', category: 'fresh_herb' },
  { nameLower: 'italian parsley', cents: 199, unit: 'bunch', category: 'fresh_herb' },
  { nameLower: 'curly parsley', cents: 199, unit: 'bunch', category: 'fresh_herb' },
  { nameLower: 'thyme', cents: 249, unit: 'bunch', category: 'fresh_herb' },
  { nameLower: 'fresh thyme', cents: 249, unit: 'bunch', category: 'fresh_herb' },
  { nameLower: 'rosemary', cents: 249, unit: 'bunch', category: 'fresh_herb' },
  { nameLower: 'fresh rosemary', cents: 249, unit: 'bunch', category: 'fresh_herb' },
  { nameLower: 'cilantro', cents: 199, unit: 'bunch', category: 'fresh_herb' },
  { nameLower: 'chives', cents: 249, unit: 'bunch', category: 'fresh_herb' },
  { nameLower: 'tarragon', cents: 299, unit: 'bunch', category: 'fresh_herb' },
  { nameLower: 'fresh tarragon', cents: 299, unit: 'bunch', category: 'fresh_herb' },
  { nameLower: 'mint', cents: 249, unit: 'bunch', category: 'fresh_herb' },
  { nameLower: 'fresh mint', cents: 249, unit: 'bunch', category: 'fresh_herb' },
  { nameLower: 'sage', cents: 249, unit: 'bunch', category: 'fresh_herb' },
  { nameLower: 'fresh sage', cents: 249, unit: 'bunch', category: 'fresh_herb' },
  { nameLower: 'dill', cents: 249, unit: 'bunch', category: 'fresh_herb' },
  { nameLower: 'fresh dill', cents: 249, unit: 'bunch', category: 'fresh_herb' },
  { nameLower: 'oregano', cents: 249, unit: 'bunch', category: 'fresh_herb' },
  { nameLower: 'fresh oregano', cents: 249, unit: 'bunch', category: 'fresh_herb' },
  { nameLower: 'marjoram', cents: 299, unit: 'bunch', category: 'fresh_herb' },
  { nameLower: 'lavender', cents: 399, unit: 'bunch', category: 'fresh_herb' },
  { nameLower: 'lemon thyme', cents: 299, unit: 'bunch', category: 'fresh_herb' },
  { nameLower: 'bay leaves', cents: 349, unit: '0.5 oz', category: 'fresh_herb' },
  { nameLower: 'microgreens', cents: 499, unit: '2 oz', category: 'fresh_herb' },
  { nameLower: 'edible flowers', cents: 399, unit: 'package', category: 'fresh_herb' },

  // ══════════════════════════════════════════════════════════════════════════
  // ALCOHOL (COOKING)
  // ══════════════════════════════════════════════════════════════════════════
  { nameLower: 'white wine', cents: 999, unit: '750ml', category: 'alcohol' },
  { nameLower: 'red wine', cents: 1099, unit: '750ml', category: 'alcohol' },
  { nameLower: 'dry white wine', cents: 999, unit: '750ml', category: 'alcohol' },
  { nameLower: 'dry red wine', cents: 1099, unit: '750ml', category: 'alcohol' },
  { nameLower: 'sake', cents: 999, unit: '750ml', category: 'alcohol' },
  { nameLower: 'beer', cents: 199, unit: '12 oz', category: 'alcohol' },
  { nameLower: 'stout', cents: 299, unit: '12 oz', category: 'alcohol' },
  { nameLower: 'bourbon', cents: 2499, unit: '750ml', category: 'alcohol' },
  { nameLower: 'brandy', cents: 1999, unit: '750ml', category: 'alcohol' },
  { nameLower: 'cognac', cents: 3999, unit: '750ml', category: 'alcohol' },
  { nameLower: 'rum', cents: 1799, unit: '750ml', category: 'alcohol' },
  { nameLower: 'dark rum', cents: 1999, unit: '750ml', category: 'alcohol' },
  { nameLower: 'vodka', cents: 1499, unit: '750ml', category: 'alcohol' },
  { nameLower: 'tequila', cents: 2499, unit: '750ml', category: 'alcohol' },
  { nameLower: 'gin', cents: 1999, unit: '750ml', category: 'alcohol' },
  { nameLower: 'amaretto', cents: 1999, unit: '750ml', category: 'alcohol' },
  { nameLower: 'kahlua', cents: 2499, unit: '750ml', category: 'alcohol' },
  { nameLower: 'grand marnier', cents: 3499, unit: '750ml', category: 'alcohol' },
  { nameLower: 'cointreau', cents: 2999, unit: '750ml', category: 'alcohol' },
  { nameLower: 'triple sec', cents: 999, unit: '750ml', category: 'alcohol' },
  { nameLower: 'port wine', cents: 1499, unit: '750ml', category: 'alcohol' },
  { nameLower: 'sherry', cents: 1299, unit: '750ml', category: 'alcohol' },
  { nameLower: 'madeira', cents: 1499, unit: '750ml', category: 'alcohol' },
  { nameLower: 'vermouth', cents: 999, unit: '750ml', category: 'alcohol' },
  { nameLower: 'champagne', cents: 1999, unit: '750ml', category: 'alcohol' },
  { nameLower: 'prosecco', cents: 1299, unit: '750ml', category: 'alcohol' },

  // ══════════════════════════════════════════════════════════════════════════
  // ASIAN / INTERNATIONAL PANTRY
  // ══════════════════════════════════════════════════════════════════════════
  { nameLower: 'nori', cents: 399, unit: '10 sheets', category: 'pantry' },
  { nameLower: 'seaweed', cents: 399, unit: '1 oz', category: 'pantry' },
  { nameLower: 'kombu', cents: 499, unit: '1 oz', category: 'pantry' },
  { nameLower: 'wakame', cents: 399, unit: '1 oz', category: 'pantry' },
  { nameLower: 'bonito flakes', cents: 599, unit: '1 oz', category: 'pantry' },
  { nameLower: 'wonton wrappers', cents: 349, unit: '12 oz', category: 'pantry' },
  { nameLower: 'egg roll wrappers', cents: 349, unit: '14 oz', category: 'pantry' },
  { nameLower: 'dumpling wrappers', cents: 349, unit: '12 oz', category: 'pantry' },
  { nameLower: 'spring roll wrappers', cents: 299, unit: '12 oz', category: 'pantry' },
  { nameLower: 'rice paper', cents: 399, unit: '12 oz', category: 'pantry' },
  { nameLower: 'tortillas', cents: 349, unit: '10 ct', category: 'pantry' },
  { nameLower: 'flour tortillas', cents: 349, unit: '10 ct', category: 'pantry' },
  { nameLower: 'corn tortillas', cents: 299, unit: '30 ct', category: 'pantry' },
  { nameLower: 'pita bread', cents: 349, unit: '6 ct', category: 'pantry' },
  { nameLower: 'naan', cents: 399, unit: '4 ct', category: 'pantry' },
  { nameLower: 'lavash', cents: 349, unit: '4 ct', category: 'pantry' },
  { nameLower: 'panko breadcrumbs', cents: 349, unit: '8 oz', category: 'pantry' },
  { nameLower: 'mochi', cents: 499, unit: '10 oz', category: 'pantry' },
  { nameLower: 'toasted coconut', cents: 499, unit: '8 oz', category: 'pantry' },
  { nameLower: 'rose water', cents: 399, unit: '10 oz', category: 'pantry' },
  { nameLower: 'orange blossom water', cents: 499, unit: '10 oz', category: 'pantry' },
  { nameLower: 'papad', cents: 399, unit: '7 oz', category: 'pantry' },
  { nameLower: 'papadum', cents: 399, unit: '7 oz', category: 'pantry' },
  { nameLower: 'ghee', cents: 999, unit: '16 oz', category: 'pantry' },
  { nameLower: 'milk powder', cents: 499, unit: 'lb', category: 'pantry' },
  { nameLower: 'powdered milk', cents: 499, unit: 'lb', category: 'pantry' },
  { nameLower: 'matcha', cents: 999, unit: '1 oz', category: 'pantry' },
  { nameLower: 'matcha powder', cents: 999, unit: '1 oz', category: 'pantry' },
]

// Fuzzy match: returns best price entry for an ingredient name, or null.
// Priority: exact match > input contains lookup key > lookup key contains input.
export function lookupUsdaPrice(ingredientName: string): UsdaPriceEntry | null {
  const lower = ingredientName.toLowerCase().trim()
  const exact = USDA_NE_PRICES.find((e) => e.nameLower === lower)
  if (exact) return exact
  const containedBy = USDA_NE_PRICES.find((e) => lower.includes(e.nameLower))
  if (containedBy) return containedBy
  const contains = USDA_NE_PRICES.find((e) => e.nameLower.includes(lower) && lower.length > 3)
  return contains ?? null
}
