// lib/grocery/usda-prices.ts
// USDA ERS Northeast Urban Average Retail Food Prices (Q1 2026)
// Source: USDA ERS "Average Retail Food Prices" -- Northeast Urban division
// All prices in CENTS per common purchase unit.
// Already NE-regional -- do NOT apply the NE multiplier to these entries.

export type UsdaPriceEntry = {
  nameLower: string  // lowercase match key
  cents: number      // price in cents for `unit`
  unit: string       // purchase unit (lb, oz, each, pint, etc.)
  category: string   // ingredient_category value
}

export const USDA_NE_PRICES: UsdaPriceEntry[] = [
  // Proteins
  { nameLower: 'chicken breast',        cents: 799,  unit: 'lb',          category: 'protein' },
  { nameLower: 'chicken thigh',         cents: 599,  unit: 'lb',          category: 'protein' },
  { nameLower: 'chicken thighs',        cents: 599,  unit: 'lb',          category: 'protein' },
  { nameLower: 'ground beef',           cents: 749,  unit: 'lb',          category: 'protein' },
  { nameLower: 'ground turkey',         cents: 649,  unit: 'lb',          category: 'protein' },
  { nameLower: 'salmon',                cents: 1299, unit: 'lb',          category: 'protein' },
  { nameLower: 'salmon fillet',         cents: 1299, unit: 'lb',          category: 'protein' },
  { nameLower: 'shrimp',                cents: 999,  unit: 'lb',          category: 'protein' },
  { nameLower: 'scallops',              cents: 2499, unit: 'lb',          category: 'protein' },
  { nameLower: 'sea scallops',          cents: 2499, unit: 'lb',          category: 'protein' },
  { nameLower: 'pork tenderloin',       cents: 649,  unit: 'lb',          category: 'protein' },
  { nameLower: 'pork chop',             cents: 549,  unit: 'lb',          category: 'protein' },
  { nameLower: 'pork chops',            cents: 549,  unit: 'lb',          category: 'protein' },
  { nameLower: 'bacon',                 cents: 799,  unit: 'lb',          category: 'protein' },
  { nameLower: 'pancetta',              cents: 1299, unit: 'lb',          category: 'protein' },
  { nameLower: 'duck breast',           cents: 1799, unit: 'lb',          category: 'protein' },
  { nameLower: 'lamb chop',             cents: 1999, unit: 'lb',          category: 'protein' },
  { nameLower: 'lamb chops',            cents: 1999, unit: 'lb',          category: 'protein' },
  { nameLower: 'tuna',                  cents: 1499, unit: 'lb',          category: 'protein' },
  { nameLower: 'cod',                   cents: 1099, unit: 'lb',          category: 'protein' },
  { nameLower: 'halibut',               cents: 2299, unit: 'lb',          category: 'protein' },
  { nameLower: 'lobster',               cents: 2999, unit: 'lb',          category: 'protein' },
  { nameLower: 'eggs',                  cents: 499,  unit: 'dozen',       category: 'protein' },
  { nameLower: 'egg',                   cents: 499,  unit: 'dozen',       category: 'protein' },
  { nameLower: 'prosciutto',            cents: 2499, unit: 'lb',          category: 'protein' },
  // Dairy
  { nameLower: 'heavy cream',           cents: 499,  unit: 'pint',        category: 'dairy' },
  { nameLower: 'heavy whipping cream',  cents: 499,  unit: 'pint',        category: 'dairy' },
  { nameLower: 'butter',                cents: 649,  unit: 'lb',          category: 'dairy' },
  { nameLower: 'unsalted butter',       cents: 699,  unit: 'lb',          category: 'dairy' },
  { nameLower: 'whole milk',            cents: 449,  unit: 'half gallon', category: 'dairy' },
  { nameLower: 'milk',                  cents: 449,  unit: 'half gallon', category: 'dairy' },
  { nameLower: 'half and half',         cents: 399,  unit: 'pint',        category: 'dairy' },
  { nameLower: 'parmesan',              cents: 899,  unit: 'lb',          category: 'dairy' },
  { nameLower: 'parmigiano',            cents: 1099, unit: 'lb',          category: 'dairy' },
  { nameLower: 'mozzarella',            cents: 699,  unit: 'lb',          category: 'dairy' },
  { nameLower: 'fresh mozzarella',      cents: 999,  unit: 'lb',          category: 'dairy' },
  { nameLower: 'burrata',               cents: 1299, unit: 'lb',          category: 'dairy' },
  { nameLower: 'ricotta',               cents: 449,  unit: 'lb',          category: 'dairy' },
  { nameLower: 'goat cheese',           cents: 799,  unit: 'lb',          category: 'dairy' },
  { nameLower: 'brie',                  cents: 999,  unit: 'lb',          category: 'dairy' },
  { nameLower: 'gruyere',               cents: 1299, unit: 'lb',          category: 'dairy' },
  { nameLower: 'cream cheese',          cents: 399,  unit: '8 oz',        category: 'dairy' },
  { nameLower: 'sour cream',            cents: 299,  unit: 'pint',        category: 'dairy' },
  { nameLower: 'creme fraiche',         cents: 599,  unit: 'lb',          category: 'dairy' },
  { nameLower: 'mascarpone',            cents: 899,  unit: 'lb',          category: 'dairy' },
  { nameLower: 'greek yogurt',          cents: 449,  unit: 'lb',          category: 'dairy' },
  // Produce
  { nameLower: 'garlic',                cents: 199,  unit: 'head',        category: 'produce' },
  { nameLower: 'garlic cloves',         cents: 199,  unit: 'head',        category: 'produce' },
  { nameLower: 'onion',                 cents: 149,  unit: 'lb',          category: 'produce' },
  { nameLower: 'onions',                cents: 149,  unit: 'lb',          category: 'produce' },
  { nameLower: 'yellow onion',          cents: 149,  unit: 'lb',          category: 'produce' },
  { nameLower: 'red onion',             cents: 179,  unit: 'lb',          category: 'produce' },
  { nameLower: 'shallot',               cents: 249,  unit: 'lb',          category: 'produce' },
  { nameLower: 'shallots',              cents: 249,  unit: 'lb',          category: 'produce' },
  { nameLower: 'tomato',                cents: 299,  unit: 'lb',          category: 'produce' },
  { nameLower: 'tomatoes',              cents: 299,  unit: 'lb',          category: 'produce' },
  { nameLower: 'cherry tomatoes',       cents: 449,  unit: 'lb',          category: 'produce' },
  { nameLower: 'grape tomatoes',        cents: 449,  unit: 'lb',          category: 'produce' },
  { nameLower: 'lemon',                 cents: 99,   unit: 'each',        category: 'produce' },
  { nameLower: 'lemons',                cents: 99,   unit: 'each',        category: 'produce' },
  { nameLower: 'lime',                  cents: 79,   unit: 'each',        category: 'produce' },
  { nameLower: 'limes',                 cents: 79,   unit: 'each',        category: 'produce' },
  { nameLower: 'orange',                cents: 129,  unit: 'each',        category: 'produce' },
  { nameLower: 'spinach',               cents: 399,  unit: 'lb',          category: 'produce' },
  { nameLower: 'baby spinach',          cents: 449,  unit: 'lb',          category: 'produce' },
  { nameLower: 'kale',                  cents: 299,  unit: 'bunch',       category: 'produce' },
  { nameLower: 'arugula',               cents: 449,  unit: 'lb',          category: 'produce' },
  { nameLower: 'asparagus',             cents: 499,  unit: 'lb',          category: 'produce' },
  { nameLower: 'broccoli',              cents: 249,  unit: 'lb',          category: 'produce' },
  { nameLower: 'broccolini',            cents: 399,  unit: 'lb',          category: 'produce' },
  { nameLower: 'potato',                cents: 129,  unit: 'lb',          category: 'produce' },
  { nameLower: 'potatoes',              cents: 129,  unit: 'lb',          category: 'produce' },
  { nameLower: 'yukon gold potato',     cents: 159,  unit: 'lb',          category: 'produce' },
  { nameLower: 'sweet potato',          cents: 169,  unit: 'lb',          category: 'produce' },
  { nameLower: 'sweet potatoes',        cents: 169,  unit: 'lb',          category: 'produce' },
  { nameLower: 'mushroom',              cents: 499,  unit: 'lb',          category: 'produce' },
  { nameLower: 'mushrooms',             cents: 499,  unit: 'lb',          category: 'produce' },
  { nameLower: 'cremini mushrooms',     cents: 499,  unit: 'lb',          category: 'produce' },
  { nameLower: 'shiitake mushrooms',    cents: 799,  unit: 'lb',          category: 'produce' },
  { nameLower: 'bell pepper',           cents: 149,  unit: 'each',        category: 'produce' },
  { nameLower: 'bell peppers',          cents: 149,  unit: 'each',        category: 'produce' },
  { nameLower: 'zucchini',              cents: 229,  unit: 'lb',          category: 'produce' },
  { nameLower: 'eggplant',              cents: 249,  unit: 'lb',          category: 'produce' },
  { nameLower: 'cauliflower',           cents: 349,  unit: 'head',        category: 'produce' },
  { nameLower: 'celery',                cents: 199,  unit: 'bunch',       category: 'produce' },
  { nameLower: 'carrot',                cents: 149,  unit: 'lb',          category: 'produce' },
  { nameLower: 'carrots',               cents: 149,  unit: 'lb',          category: 'produce' },
  { nameLower: 'fennel',                cents: 349,  unit: 'bulb',        category: 'produce' },
  { nameLower: 'leek',                  cents: 299,  unit: 'lb',          category: 'produce' },
  { nameLower: 'leeks',                 cents: 299,  unit: 'lb',          category: 'produce' },
  { nameLower: 'corn',                  cents: 99,   unit: 'each',        category: 'produce' },
  { nameLower: 'avocado',               cents: 199,  unit: 'each',        category: 'produce' },
  { nameLower: 'avocados',              cents: 199,  unit: 'each',        category: 'produce' },
  // Oils
  { nameLower: 'olive oil',             cents: 1299, unit: '16 oz',       category: 'oil' },
  { nameLower: 'extra virgin olive oil',cents: 1499, unit: '16 oz',       category: 'oil' },
  { nameLower: 'vegetable oil',         cents: 499,  unit: '32 oz',       category: 'oil' },
  { nameLower: 'canola oil',            cents: 499,  unit: '32 oz',       category: 'oil' },
  { nameLower: 'sesame oil',            cents: 699,  unit: '8 oz',        category: 'oil' },
  { nameLower: 'coconut oil',           cents: 899,  unit: '14 oz',       category: 'oil' },
  // Baking
  { nameLower: 'flour',                 cents: 449,  unit: '5 lb',        category: 'baking' },
  { nameLower: 'all-purpose flour',     cents: 449,  unit: '5 lb',        category: 'baking' },
  { nameLower: 'bread flour',           cents: 549,  unit: '5 lb',        category: 'baking' },
  { nameLower: 'sugar',                 cents: 399,  unit: '4 lb',        category: 'baking' },
  { nameLower: 'granulated sugar',      cents: 399,  unit: '4 lb',        category: 'baking' },
  { nameLower: 'brown sugar',           cents: 349,  unit: '2 lb',        category: 'baking' },
  { nameLower: 'powdered sugar',        cents: 299,  unit: '2 lb',        category: 'baking' },
  { nameLower: 'baking soda',           cents: 149,  unit: '16 oz',       category: 'baking' },
  { nameLower: 'baking powder',         cents: 199,  unit: '8 oz',        category: 'baking' },
  { nameLower: 'cocoa powder',          cents: 449,  unit: '8 oz',        category: 'baking' },
  { nameLower: 'vanilla extract',       cents: 699,  unit: '4 oz',        category: 'baking' },
  { nameLower: 'chocolate chips',       cents: 499,  unit: '12 oz',       category: 'baking' },
  { nameLower: 'dark chocolate',        cents: 699,  unit: '12 oz',       category: 'baking' },
  // Pantry
  { nameLower: 'pasta',                 cents: 199,  unit: 'lb',          category: 'pantry' },
  { nameLower: 'spaghetti',             cents: 199,  unit: 'lb',          category: 'pantry' },
  { nameLower: 'penne',                 cents: 199,  unit: 'lb',          category: 'pantry' },
  { nameLower: 'fettuccine',            cents: 249,  unit: 'lb',          category: 'pantry' },
  { nameLower: 'rice',                  cents: 249,  unit: 'lb',          category: 'pantry' },
  { nameLower: 'arborio rice',          cents: 449,  unit: 'lb',          category: 'pantry' },
  { nameLower: 'chicken stock',         cents: 399,  unit: 'qt',          category: 'pantry' },
  { nameLower: 'chicken broth',         cents: 399,  unit: 'qt',          category: 'pantry' },
  { nameLower: 'vegetable stock',       cents: 349,  unit: 'qt',          category: 'pantry' },
  { nameLower: 'beef stock',            cents: 449,  unit: 'qt',          category: 'pantry' },
  { nameLower: 'panko',                 cents: 299,  unit: 'lb',          category: 'pantry' },
  { nameLower: 'bread crumbs',          cents: 249,  unit: 'lb',          category: 'pantry' },
  { nameLower: 'quinoa',                cents: 599,  unit: 'lb',          category: 'pantry' },
  { nameLower: 'lentils',               cents: 249,  unit: 'lb',          category: 'pantry' },
  // Alcohol
  { nameLower: 'white wine',            cents: 999,  unit: '750ml',       category: 'alcohol' },
  { nameLower: 'red wine',              cents: 1099, unit: '750ml',       category: 'alcohol' },
  // Canned
  { nameLower: 'canned tomatoes',       cents: 199,  unit: '28 oz',       category: 'canned' },
  { nameLower: 'crushed tomatoes',      cents: 199,  unit: '28 oz',       category: 'canned' },
  { nameLower: 'tomato paste',          cents: 149,  unit: '6 oz',        category: 'canned' },
  { nameLower: 'coconut milk',          cents: 249,  unit: '14 oz',       category: 'canned' },
  // Condiments
  { nameLower: 'dijon mustard',         cents: 399,  unit: '8 oz',        category: 'condiment' },
  { nameLower: 'whole grain mustard',   cents: 449,  unit: '8 oz',        category: 'condiment' },
  { nameLower: 'soy sauce',             cents: 349,  unit: '10 oz',       category: 'condiment' },
  { nameLower: 'worcestershire sauce',  cents: 299,  unit: '10 oz',       category: 'condiment' },
  { nameLower: 'hot sauce',             cents: 349,  unit: '12 oz',       category: 'condiment' },
  { nameLower: 'fish sauce',            cents: 399,  unit: '12 oz',       category: 'condiment' },
  { nameLower: 'honey',                 cents: 699,  unit: 'lb',          category: 'condiment' },
  { nameLower: 'maple syrup',           cents: 1299, unit: '12 oz',       category: 'condiment' },
  { nameLower: 'balsamic vinegar',      cents: 599,  unit: '16 oz',       category: 'condiment' },
  { nameLower: 'red wine vinegar',      cents: 349,  unit: '16 oz',       category: 'condiment' },
  { nameLower: 'white wine vinegar',    cents: 349,  unit: '16 oz',       category: 'condiment' },
  { nameLower: 'apple cider vinegar',   cents: 349,  unit: '16 oz',       category: 'condiment' },
  { nameLower: 'capers',                cents: 349,  unit: '4 oz',        category: 'condiment' },
  { nameLower: 'anchovies',             cents: 399,  unit: '2 oz',        category: 'condiment' },
  // Spices
  { nameLower: 'black pepper',          cents: 399,  unit: '4 oz',        category: 'spice' },
  { nameLower: 'kosher salt',           cents: 299,  unit: '3 lb',        category: 'spice' },
  { nameLower: 'sea salt',              cents: 449,  unit: 'lb',          category: 'spice' },
  { nameLower: 'cumin',                 cents: 349,  unit: '4 oz',        category: 'spice' },
  { nameLower: 'paprika',               cents: 349,  unit: '4 oz',        category: 'spice' },
  { nameLower: 'smoked paprika',        cents: 449,  unit: '4 oz',        category: 'spice' },
  { nameLower: 'cinnamon',              cents: 349,  unit: '4 oz',        category: 'spice' },
  { nameLower: 'red pepper flakes',     cents: 349,  unit: '4 oz',        category: 'spice' },
  { nameLower: 'turmeric',              cents: 399,  unit: '4 oz',        category: 'spice' },
  // Dry herbs
  { nameLower: 'dried oregano',         cents: 299,  unit: '4 oz',        category: 'dry_herb' },
  { nameLower: 'dried thyme',           cents: 299,  unit: '4 oz',        category: 'dry_herb' },
  { nameLower: 'bay leaves',            cents: 349,  unit: '0.5 oz',      category: 'dry_herb' },
  { nameLower: 'bay leaf',              cents: 349,  unit: '0.5 oz',      category: 'dry_herb' },
  // Fresh herbs
  { nameLower: 'basil',                 cents: 299,  unit: 'bunch',       category: 'fresh_herb' },
  { nameLower: 'fresh basil',           cents: 299,  unit: 'bunch',       category: 'fresh_herb' },
  { nameLower: 'parsley',               cents: 199,  unit: 'bunch',       category: 'fresh_herb' },
  { nameLower: 'flat-leaf parsley',     cents: 199,  unit: 'bunch',       category: 'fresh_herb' },
  { nameLower: 'thyme',                 cents: 249,  unit: 'bunch',       category: 'fresh_herb' },
  { nameLower: 'fresh thyme',           cents: 249,  unit: 'bunch',       category: 'fresh_herb' },
  { nameLower: 'rosemary',              cents: 249,  unit: 'bunch',       category: 'fresh_herb' },
  { nameLower: 'fresh rosemary',        cents: 249,  unit: 'bunch',       category: 'fresh_herb' },
  { nameLower: 'cilantro',              cents: 199,  unit: 'bunch',       category: 'fresh_herb' },
  { nameLower: 'chives',                cents: 249,  unit: 'bunch',       category: 'fresh_herb' },
  { nameLower: 'tarragon',              cents: 299,  unit: 'bunch',       category: 'fresh_herb' },
  { nameLower: 'mint',                  cents: 249,  unit: 'bunch',       category: 'fresh_herb' },
  { nameLower: 'sage',                  cents: 249,  unit: 'bunch',       category: 'fresh_herb' },
  { nameLower: 'dill',                  cents: 249,  unit: 'bunch',       category: 'fresh_herb' },
]

// Fuzzy match: returns best price entry for an ingredient name, or null.
// Priority: exact match > input contains lookup key > lookup key contains input.
export function lookupUsdaPrice(ingredientName: string): UsdaPriceEntry | null {
  const lower = ingredientName.toLowerCase().trim()
  const exact = USDA_NE_PRICES.find(e => e.nameLower === lower)
  if (exact) return exact
  const containedBy = USDA_NE_PRICES.find(e => lower.includes(e.nameLower))
  if (containedBy) return containedBy
  const contains = USDA_NE_PRICES.find(e => e.nameLower.includes(lower) && lower.length > 3)
  return contains ?? null
}
