// Pre-built ingredient database seed data
// Compact format to minimize file size. Expanded during seeding.
// Cup/tbsp weights from USDA FoodData Central where available.
// Allergen tags use Big 9: milk, egg, fish, shellfish, tree_nuts, peanuts, wheat, soy, sesame

type SeedIngredient = {
  n: string // name
  c: string // category (maps to ingredient_category enum)
  sc?: string // subcategory
  ut?: string // unit_type: weight|volume|each|bunch (default: weight)
  su?: string // standard_unit: g|oz|ml|fl_oz|each|bunch (default: g)
  cw?: number // cup_weight_grams
  tw?: number // tbsp_weight_grams
  ac?: number // avg_cost_cents (per standard unit, rough estimate)
  at?: string[] // allergen_tags
  pa?: Array<{ a: string; y: number }> // prep_actions [{action, yield_pct}]
}

// ============================================================================
// PROTEINS (~80)
// ============================================================================
const proteins: SeedIngredient[] = [
  // Poultry
  {
    n: 'Chicken breast, boneless skinless',
    c: 'protein',
    sc: 'poultry',
    cw: 140,
    pa: [
      { a: 'dice', y: 95 },
      { a: 'butterfly', y: 100 },
      { a: 'pound thin', y: 100 },
    ],
  },
  {
    n: 'Chicken thigh, boneless skinless',
    c: 'protein',
    sc: 'poultry',
    cw: 140,
    pa: [
      { a: 'dice', y: 95 },
      { a: 'trim', y: 90 },
    ],
  },
  {
    n: 'Chicken thigh, bone-in skin-on',
    c: 'protein',
    sc: 'poultry',
    pa: [
      { a: 'debone', y: 65 },
      { a: 'trim', y: 90 },
    ],
  },
  {
    n: 'Chicken drumstick',
    c: 'protein',
    sc: 'poultry',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'score', y: 100 }],
  },
  {
    n: 'Chicken wing',
    c: 'protein',
    sc: 'poultry',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'separate joints', y: 90 }],
  },
  {
    n: 'Whole chicken',
    c: 'protein',
    sc: 'poultry',
    ut: 'each',
    su: 'each',
    pa: [
      { a: 'spatchcock', y: 95 },
      { a: 'butcher', y: 70 },
    ],
  },
  { n: 'Ground chicken', c: 'protein', sc: 'poultry' },
  {
    n: 'Turkey breast',
    c: 'protein',
    sc: 'poultry',
    pa: [
      { a: 'slice', y: 95 },
      { a: 'pound thin', y: 100 },
    ],
  },
  { n: 'Ground turkey', c: 'protein', sc: 'poultry' },
  {
    n: 'Duck breast',
    c: 'protein',
    sc: 'poultry',
    pa: [
      { a: 'score skin', y: 100 },
      { a: 'trim', y: 90 },
    ],
  },
  { n: 'Duck leg confit', c: 'protein', sc: 'poultry', ut: 'each', su: 'each' },
  {
    n: 'Cornish hen',
    c: 'protein',
    sc: 'poultry',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'spatchcock', y: 95 }],
  },
  // Beef
  {
    n: 'Beef tenderloin',
    c: 'protein',
    sc: 'beef',
    pa: [
      { a: 'trim silver skin', y: 85 },
      { a: 'portion', y: 95 },
    ],
  },
  {
    n: 'Beef ribeye steak',
    c: 'protein',
    sc: 'beef',
    pa: [
      { a: 'trim', y: 90 },
      { a: 'slice', y: 95 },
    ],
  },
  { n: 'Beef strip steak (NY strip)', c: 'protein', sc: 'beef', pa: [{ a: 'trim', y: 92 }] },
  {
    n: 'Beef sirloin',
    c: 'protein',
    sc: 'beef',
    pa: [
      { a: 'cube', y: 90 },
      { a: 'slice', y: 95 },
    ],
  },
  {
    n: 'Beef chuck roast',
    c: 'protein',
    sc: 'beef',
    pa: [
      { a: 'cube', y: 85 },
      { a: 'trim', y: 80 },
    ],
  },
  { n: 'Beef short ribs', c: 'protein', sc: 'beef', pa: [{ a: 'trim', y: 75 }] },
  { n: 'Ground beef (80/20)', c: 'protein', sc: 'beef' },
  { n: 'Ground beef (90/10)', c: 'protein', sc: 'beef' },
  {
    n: 'Beef brisket',
    c: 'protein',
    sc: 'beef',
    pa: [
      { a: 'trim', y: 80 },
      { a: 'slice', y: 95 },
    ],
  },
  { n: 'Flank steak', c: 'protein', sc: 'beef', pa: [{ a: 'slice against grain', y: 95 }] },
  { n: 'Skirt steak', c: 'protein', sc: 'beef', pa: [{ a: 'trim membrane', y: 90 }] },
  { n: 'Beef oxtail', c: 'protein', sc: 'beef' },
  { n: 'Veal cutlet', c: 'protein', sc: 'beef', pa: [{ a: 'pound thin', y: 100 }] },
  // Pork
  {
    n: 'Pork tenderloin',
    c: 'protein',
    sc: 'pork',
    pa: [
      { a: 'trim silver skin', y: 88 },
      { a: 'medallion', y: 95 },
    ],
  },
  { n: 'Pork chop, bone-in', c: 'protein', sc: 'pork', pa: [{ a: 'french', y: 85 }] },
  {
    n: 'Pork shoulder (butt)',
    c: 'protein',
    sc: 'pork',
    pa: [
      { a: 'cube', y: 80 },
      { a: 'trim', y: 75 },
    ],
  },
  {
    n: 'Pork belly',
    c: 'protein',
    sc: 'pork',
    pa: [
      { a: 'score skin', y: 100 },
      { a: 'cube', y: 95 },
    ],
  },
  { n: 'Ground pork', c: 'protein', sc: 'pork' },
  { n: 'Pork ribs (baby back)', c: 'protein', sc: 'pork', pa: [{ a: 'remove membrane', y: 95 }] },
  { n: 'Bacon', c: 'protein', sc: 'pork', pa: [{ a: 'dice (lardons)', y: 95 }] },
  { n: 'Pancetta', c: 'protein', sc: 'pork', pa: [{ a: 'dice', y: 95 }] },
  { n: 'Prosciutto', c: 'protein', sc: 'pork' },
  { n: 'Italian sausage', c: 'protein', sc: 'pork', pa: [{ a: 'remove casing', y: 85 }] },
  { n: 'Chorizo', c: 'protein', sc: 'pork', pa: [{ a: 'remove casing', y: 85 }] },
  // Lamb
  {
    n: 'Lamb rack',
    c: 'protein',
    sc: 'lamb',
    pa: [
      { a: 'french', y: 75 },
      { a: 'trim', y: 80 },
    ],
  },
  {
    n: 'Lamb leg, boneless',
    c: 'protein',
    sc: 'lamb',
    pa: [
      { a: 'butterfly', y: 90 },
      { a: 'cube', y: 85 },
    ],
  },
  { n: 'Lamb shank', c: 'protein', sc: 'lamb', ut: 'each', su: 'each' },
  { n: 'Ground lamb', c: 'protein', sc: 'lamb' },
  { n: 'Lamb loin chop', c: 'protein', sc: 'lamb', pa: [{ a: 'french', y: 80 }] },
  // Seafood
  {
    n: 'Salmon fillet',
    c: 'protein',
    sc: 'seafood',
    at: ['fish'],
    pa: [
      { a: 'portion', y: 95 },
      { a: 'skin', y: 85 },
      { a: 'pin bone', y: 98 },
    ],
  },
  {
    n: 'Tuna steak (ahi)',
    c: 'protein',
    sc: 'seafood',
    at: ['fish'],
    pa: [{ a: 'portion', y: 95 }],
  },
  { n: 'Halibut fillet', c: 'protein', sc: 'seafood', at: ['fish'], pa: [{ a: 'portion', y: 90 }] },
  { n: 'Cod fillet', c: 'protein', sc: 'seafood', at: ['fish'], pa: [{ a: 'portion', y: 90 }] },
  {
    n: 'Sea bass fillet',
    c: 'protein',
    sc: 'seafood',
    at: ['fish'],
    pa: [
      { a: 'portion', y: 85 },
      { a: 'score skin', y: 100 },
    ],
  },
  { n: 'Snapper fillet', c: 'protein', sc: 'seafood', at: ['fish'], pa: [{ a: 'portion', y: 85 }] },
  { n: 'Swordfish steak', c: 'protein', sc: 'seafood', at: ['fish'] },
  { n: 'Mahi mahi fillet', c: 'protein', sc: 'seafood', at: ['fish'] },
  {
    n: 'Trout, whole',
    c: 'protein',
    sc: 'seafood',
    at: ['fish'],
    pa: [
      { a: 'fillet', y: 45 },
      { a: 'debone', y: 60 },
    ],
  },
  {
    n: 'Shrimp, raw (shell-on)',
    c: 'protein',
    sc: 'seafood',
    at: ['shellfish'],
    pa: [{ a: 'peel and devein', y: 55 }],
  },
  { n: 'Shrimp, peeled deveined', c: 'protein', sc: 'seafood', at: ['shellfish'] },
  {
    n: 'Lobster tail',
    c: 'protein',
    sc: 'seafood',
    at: ['shellfish'],
    ut: 'each',
    su: 'each',
    pa: [{ a: 'butterfly', y: 90 }],
  },
  { n: 'Scallops, dry-packed (U-10)', c: 'protein', sc: 'seafood', at: ['shellfish'] },
  { n: 'Crab meat, lump', c: 'protein', sc: 'seafood', at: ['shellfish'] },
  {
    n: 'Mussels',
    c: 'protein',
    sc: 'seafood',
    at: ['shellfish'],
    pa: [{ a: 'debeard and scrub', y: 85 }],
  },
  {
    n: 'Clams, littleneck',
    c: 'protein',
    sc: 'seafood',
    at: ['shellfish'],
    pa: [{ a: 'purge', y: 100 }],
  },
  {
    n: 'Oysters',
    c: 'protein',
    sc: 'seafood',
    at: ['shellfish'],
    ut: 'each',
    su: 'each',
    pa: [{ a: 'shuck', y: 40 }],
  },
  {
    n: 'Octopus',
    c: 'protein',
    sc: 'seafood',
    pa: [
      { a: 'clean', y: 60 },
      { a: 'tenderize', y: 100 },
    ],
  },
  { n: 'Calamari (squid)', c: 'protein', sc: 'seafood', pa: [{ a: 'clean and ring', y: 55 }] },
  { n: 'Anchovies, oil-packed', c: 'protein', sc: 'seafood', at: ['fish'] },
  { n: 'Smoked salmon', c: 'protein', sc: 'seafood', at: ['fish'] },
  // Plant-based
  {
    n: 'Tofu, firm',
    c: 'protein',
    sc: 'plant-based',
    at: ['soy'],
    cw: 252,
    pa: [{ a: 'press and cube', y: 90 }],
  },
  { n: 'Tofu, silken', c: 'protein', sc: 'plant-based', at: ['soy'] },
  {
    n: 'Tempeh',
    c: 'protein',
    sc: 'plant-based',
    at: ['soy'],
    pa: [
      { a: 'crumble', y: 95 },
      { a: 'slice', y: 95 },
    ],
  },
  { n: 'Seitan', c: 'protein', sc: 'plant-based', at: ['wheat'] },
  { n: 'Beyond Meat ground', c: 'protein', sc: 'plant-based' },
  { n: 'Impossible Burger', c: 'protein', sc: 'plant-based' },
  // Game
  { n: 'Venison loin', c: 'protein', sc: 'game', pa: [{ a: 'trim', y: 85 }] },
  { n: 'Bison steak', c: 'protein', sc: 'game' },
  { n: 'Ground bison', c: 'protein', sc: 'game' },
  {
    n: 'Quail',
    c: 'protein',
    sc: 'game',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'spatchcock', y: 95 }],
  },
  { n: 'Rabbit', c: 'protein', sc: 'game', pa: [{ a: 'butcher', y: 65 }] },
]

// ============================================================================
// VEGETABLES (~100)
// ============================================================================
const vegetables: SeedIngredient[] = [
  // Alliums
  {
    n: 'Yellow onion',
    c: 'produce',
    sc: 'allium',
    ut: 'each',
    su: 'each',
    cw: 160,
    pa: [
      { a: 'dice', y: 90 },
      { a: 'slice', y: 90 },
      { a: 'mince', y: 88 },
    ],
  },
  {
    n: 'Red onion',
    c: 'produce',
    sc: 'allium',
    ut: 'each',
    su: 'each',
    cw: 160,
    pa: [
      { a: 'dice', y: 90 },
      { a: 'slice', y: 90 },
    ],
  },
  {
    n: 'White onion',
    c: 'produce',
    sc: 'allium',
    ut: 'each',
    su: 'each',
    cw: 160,
    pa: [{ a: 'dice', y: 90 }],
  },
  { n: 'Shallot', c: 'produce', sc: 'allium', ut: 'each', su: 'each', pa: [{ a: 'mince', y: 88 }] },
  {
    n: 'Leek',
    c: 'produce',
    sc: 'allium',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'clean and slice', y: 55 }],
  },
  {
    n: 'Scallion (green onion)',
    c: 'produce',
    sc: 'allium',
    ut: 'bunch',
    su: 'bunch',
    pa: [{ a: 'slice', y: 85 }],
  },
  {
    n: 'Garlic',
    c: 'produce',
    sc: 'allium',
    ut: 'each',
    su: 'each',
    tw: 9,
    pa: [
      { a: 'mince', y: 88 },
      { a: 'slice', y: 90 },
    ],
  },
  // Root vegetables
  {
    n: 'Carrot',
    c: 'produce',
    sc: 'root',
    cw: 128,
    pa: [
      { a: 'peel', y: 85 },
      { a: 'dice', y: 80 },
      { a: 'julienne', y: 78 },
    ],
  },
  {
    n: 'Celery',
    c: 'produce',
    sc: 'stalk',
    cw: 101,
    pa: [
      { a: 'dice', y: 90 },
      { a: 'slice', y: 92 },
    ],
  },
  {
    n: 'Potato, russet',
    c: 'produce',
    sc: 'root',
    ut: 'each',
    su: 'each',
    cw: 150,
    pa: [
      { a: 'peel', y: 80 },
      { a: 'dice', y: 78 },
      { a: 'slice', y: 80 },
    ],
  },
  {
    n: 'Potato, Yukon Gold',
    c: 'produce',
    sc: 'root',
    ut: 'each',
    su: 'each',
    cw: 150,
    pa: [
      { a: 'dice', y: 90 },
      { a: 'slice', y: 92 },
    ],
  },
  {
    n: 'Sweet potato',
    c: 'produce',
    sc: 'root',
    ut: 'each',
    su: 'each',
    cw: 133,
    pa: [
      { a: 'peel', y: 80 },
      { a: 'dice', y: 78 },
    ],
  },
  {
    n: 'Beet',
    c: 'produce',
    sc: 'root',
    ut: 'each',
    su: 'each',
    pa: [
      { a: 'peel', y: 82 },
      { a: 'dice', y: 80 },
    ],
  },
  {
    n: 'Turnip',
    c: 'produce',
    sc: 'root',
    ut: 'each',
    su: 'each',
    pa: [
      { a: 'peel', y: 80 },
      { a: 'dice', y: 78 },
    ],
  },
  {
    n: 'Parsnip',
    c: 'produce',
    sc: 'root',
    pa: [
      { a: 'peel', y: 82 },
      { a: 'dice', y: 80 },
    ],
  },
  { n: 'Radish', c: 'produce', sc: 'root', cw: 116, pa: [{ a: 'slice', y: 92 }] },
  {
    n: 'Daikon radish',
    c: 'produce',
    sc: 'root',
    pa: [
      { a: 'peel', y: 85 },
      { a: 'grate', y: 80 },
    ],
  },
  {
    n: 'Celery root (celeriac)',
    c: 'produce',
    sc: 'root',
    pa: [
      { a: 'peel', y: 70 },
      { a: 'dice', y: 68 },
    ],
  },
  {
    n: 'Ginger root',
    c: 'produce',
    sc: 'root',
    tw: 6,
    pa: [
      { a: 'peel', y: 85 },
      { a: 'mince', y: 82 },
      { a: 'grate', y: 80 },
    ],
  },
  // Cruciferous
  {
    n: 'Broccoli',
    c: 'produce',
    sc: 'cruciferous',
    cw: 91,
    pa: [
      { a: 'floret', y: 60 },
      { a: 'trim', y: 65 },
    ],
  },
  {
    n: 'Cauliflower',
    c: 'produce',
    sc: 'cruciferous',
    cw: 107,
    pa: [
      { a: 'floret', y: 55 },
      { a: 'rice', y: 52 },
    ],
  },
  {
    n: 'Brussels sprouts',
    c: 'produce',
    sc: 'cruciferous',
    cw: 88,
    pa: [{ a: 'trim and halve', y: 85 }],
  },
  { n: 'Cabbage, green', c: 'produce', sc: 'cruciferous', cw: 89, pa: [{ a: 'shred', y: 80 }] },
  { n: 'Cabbage, red', c: 'produce', sc: 'cruciferous', cw: 89, pa: [{ a: 'shred', y: 80 }] },
  { n: 'Cabbage, napa', c: 'produce', sc: 'cruciferous', cw: 76, pa: [{ a: 'shred', y: 85 }] },
  {
    n: 'Kale',
    c: 'produce',
    sc: 'cruciferous',
    ut: 'bunch',
    su: 'bunch',
    cw: 67,
    pa: [{ a: 'de-stem and chop', y: 60 }],
  },
  { n: 'Bok choy', c: 'produce', sc: 'cruciferous', pa: [{ a: 'trim and halve', y: 85 }] },
  // Nightshades
  {
    n: 'Tomato, Roma',
    c: 'produce',
    sc: 'nightshade',
    ut: 'each',
    su: 'each',
    cw: 180,
    pa: [
      { a: 'dice', y: 90 },
      { a: 'concasse', y: 70 },
    ],
  },
  {
    n: 'Tomato, beefsteak',
    c: 'produce',
    sc: 'nightshade',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'slice', y: 92 }],
  },
  { n: 'Cherry tomatoes', c: 'produce', sc: 'nightshade', cw: 149, pa: [{ a: 'halve', y: 95 }] },
  {
    n: 'Bell pepper, red',
    c: 'produce',
    sc: 'nightshade',
    ut: 'each',
    su: 'each',
    cw: 149,
    pa: [
      { a: 'dice', y: 82 },
      { a: 'julienne', y: 80 },
    ],
  },
  {
    n: 'Bell pepper, green',
    c: 'produce',
    sc: 'nightshade',
    ut: 'each',
    su: 'each',
    cw: 149,
    pa: [{ a: 'dice', y: 82 }],
  },
  { n: 'Bell pepper, yellow', c: 'produce', sc: 'nightshade', ut: 'each', su: 'each', cw: 149 },
  {
    n: 'Jalapeno pepper',
    c: 'produce',
    sc: 'nightshade',
    ut: 'each',
    su: 'each',
    pa: [
      { a: 'mince', y: 75 },
      { a: 'seed', y: 70 },
    ],
  },
  { n: 'Serrano pepper', c: 'produce', sc: 'nightshade', ut: 'each', su: 'each' },
  { n: 'Habanero pepper', c: 'produce', sc: 'nightshade', ut: 'each', su: 'each' },
  {
    n: 'Poblano pepper',
    c: 'produce',
    sc: 'nightshade',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'roast and peel', y: 65 }],
  },
  {
    n: 'Eggplant',
    c: 'produce',
    sc: 'nightshade',
    ut: 'each',
    su: 'each',
    cw: 82,
    pa: [
      { a: 'dice', y: 85 },
      { a: 'slice', y: 90 },
    ],
  },
  // Squash
  {
    n: 'Zucchini',
    c: 'produce',
    sc: 'squash',
    ut: 'each',
    su: 'each',
    cw: 124,
    pa: [
      { a: 'dice', y: 90 },
      { a: 'spiralize', y: 85 },
    ],
  },
  {
    n: 'Yellow squash',
    c: 'produce',
    sc: 'squash',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'slice', y: 90 }],
  },
  {
    n: 'Butternut squash',
    c: 'produce',
    sc: 'squash',
    ut: 'each',
    su: 'each',
    cw: 140,
    pa: [{ a: 'peel and dice', y: 65 }],
  },
  {
    n: 'Acorn squash',
    c: 'produce',
    sc: 'squash',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'halve and seed', y: 80 }],
  },
  {
    n: 'Delicata squash',
    c: 'produce',
    sc: 'squash',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'slice', y: 85 }],
  },
  { n: 'Spaghetti squash', c: 'produce', sc: 'squash', ut: 'each', su: 'each' },
  {
    n: 'Pumpkin',
    c: 'produce',
    sc: 'squash',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'peel and dice', y: 55 }],
  },
  // Greens
  { n: 'Spinach, baby', c: 'produce', sc: 'greens', cw: 30, pa: [{ a: 'wash', y: 95 }] },
  {
    n: 'Spinach, mature',
    c: 'produce',
    sc: 'greens',
    ut: 'bunch',
    su: 'bunch',
    cw: 30,
    pa: [{ a: 'de-stem and wash', y: 70 }],
  },
  { n: 'Arugula', c: 'produce', sc: 'greens', cw: 20, pa: [{ a: 'wash', y: 95 }] },
  {
    n: 'Romaine lettuce',
    c: 'produce',
    sc: 'greens',
    ut: 'each',
    su: 'each',
    cw: 47,
    pa: [{ a: 'chop', y: 75 }],
  },
  {
    n: 'Butter lettuce',
    c: 'produce',
    sc: 'greens',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'separate leaves', y: 70 }],
  },
  { n: 'Mixed greens', c: 'produce', sc: 'greens', cw: 30 },
  {
    n: 'Swiss chard',
    c: 'produce',
    sc: 'greens',
    ut: 'bunch',
    su: 'bunch',
    pa: [{ a: 'de-stem and chop', y: 60 }],
  },
  {
    n: 'Collard greens',
    c: 'produce',
    sc: 'greens',
    ut: 'bunch',
    su: 'bunch',
    pa: [{ a: 'de-stem and chop', y: 55 }],
  },
  {
    n: 'Watercress',
    c: 'produce',
    sc: 'greens',
    ut: 'bunch',
    su: 'bunch',
    pa: [{ a: 'trim stems', y: 80 }],
  },
  {
    n: 'Endive',
    c: 'produce',
    sc: 'greens',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'separate leaves', y: 85 }],
  },
  {
    n: 'Radicchio',
    c: 'produce',
    sc: 'greens',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'shred', y: 80 }],
  },
  { n: 'Frisee', c: 'produce', sc: 'greens', ut: 'each', su: 'each', pa: [{ a: 'trim', y: 70 }] },
  // Other vegetables
  {
    n: 'Corn on the cob',
    c: 'produce',
    sc: 'vegetable',
    ut: 'each',
    su: 'each',
    pa: [
      { a: 'shuck', y: 65 },
      { a: 'cut kernels', y: 50 },
    ],
  },
  { n: 'Corn kernels (frozen)', c: 'frozen', sc: 'vegetable', cw: 154 },
  { n: 'Green beans', c: 'produce', sc: 'vegetable', cw: 110, pa: [{ a: 'trim', y: 90 }] },
  { n: 'Snow peas', c: 'produce', sc: 'vegetable', cw: 63, pa: [{ a: 'de-string', y: 92 }] },
  { n: 'Sugar snap peas', c: 'produce', sc: 'vegetable', cw: 63, pa: [{ a: 'de-string', y: 92 }] },
  { n: 'English peas (shelled)', c: 'produce', sc: 'vegetable', cw: 145 },
  {
    n: 'Asparagus',
    c: 'produce',
    sc: 'vegetable',
    ut: 'bunch',
    su: 'bunch',
    pa: [
      { a: 'trim woody ends', y: 65 },
      { a: 'peel stalks', y: 60 },
    ],
  },
  {
    n: 'Artichoke',
    c: 'produce',
    sc: 'vegetable',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'trim to heart', y: 30 }],
  },
  {
    n: 'Fennel bulb',
    c: 'produce',
    sc: 'vegetable',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'trim and slice', y: 70 }],
  },
  {
    n: 'Cucumber',
    c: 'produce',
    sc: 'vegetable',
    ut: 'each',
    su: 'each',
    cw: 133,
    pa: [
      { a: 'peel and seed', y: 70 },
      { a: 'slice', y: 92 },
    ],
  },
  {
    n: 'English cucumber',
    c: 'produce',
    sc: 'vegetable',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'slice', y: 95 }],
  },
  {
    n: 'Mushroom, cremini',
    c: 'produce',
    sc: 'mushroom',
    cw: 72,
    pa: [
      { a: 'slice', y: 92 },
      { a: 'quarter', y: 92 },
    ],
  },
  {
    n: 'Mushroom, shiitake',
    c: 'produce',
    sc: 'mushroom',
    pa: [{ a: 'de-stem and slice', y: 75 }],
  },
  { n: 'Mushroom, oyster', c: 'produce', sc: 'mushroom', pa: [{ a: 'tear', y: 90 }] },
  {
    n: 'Mushroom, portobello',
    c: 'produce',
    sc: 'mushroom',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'remove gills', y: 85 }],
  },
  {
    n: 'Mushroom, chanterelle',
    c: 'produce',
    sc: 'mushroom',
    pa: [{ a: 'clean and tear', y: 85 }],
  },
  { n: 'Mushroom, porcini (dried)', c: 'produce', sc: 'mushroom' },
  { n: 'Mushroom, king trumpet', c: 'produce', sc: 'mushroom', pa: [{ a: 'slice', y: 95 }] },
  {
    n: 'Avocado',
    c: 'produce',
    sc: 'fruit-veg',
    ut: 'each',
    su: 'each',
    cw: 150,
    pa: [{ a: 'pit and scoop', y: 65 }],
  },
  { n: 'Edamame (shelled)', c: 'produce', sc: 'legume', at: ['soy'], cw: 155 },
  { n: 'Bean sprouts', c: 'produce', sc: 'sprout', cw: 104 },
  { n: 'Hearts of palm', c: 'canned', sc: 'vegetable' },
  { n: 'Water chestnuts', c: 'canned', sc: 'vegetable' },
  { n: 'Bamboo shoots', c: 'canned', sc: 'vegetable' },
]

// ============================================================================
// FRUITS (~40)
// ============================================================================
const fruits: SeedIngredient[] = [
  {
    n: 'Lemon',
    c: 'produce',
    sc: 'citrus',
    ut: 'each',
    su: 'each',
    pa: [
      { a: 'juice', y: 35 },
      { a: 'zest', y: 5 },
      { a: 'supreme', y: 40 },
    ],
  },
  {
    n: 'Lime',
    c: 'produce',
    sc: 'citrus',
    ut: 'each',
    su: 'each',
    pa: [
      { a: 'juice', y: 30 },
      { a: 'zest', y: 5 },
    ],
  },
  {
    n: 'Orange',
    c: 'produce',
    sc: 'citrus',
    ut: 'each',
    su: 'each',
    pa: [
      { a: 'juice', y: 45 },
      { a: 'supreme', y: 50 },
      { a: 'zest', y: 5 },
    ],
  },
  {
    n: 'Grapefruit',
    c: 'produce',
    sc: 'citrus',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'supreme', y: 50 }],
  },
  { n: 'Blood orange', c: 'produce', sc: 'citrus', ut: 'each', su: 'each' },
  { n: 'Meyer lemon', c: 'produce', sc: 'citrus', ut: 'each', su: 'each' },
  {
    n: 'Apple, Granny Smith',
    c: 'produce',
    sc: 'pome',
    ut: 'each',
    su: 'each',
    cw: 125,
    pa: [{ a: 'peel and dice', y: 75 }],
  },
  { n: 'Apple, Honeycrisp', c: 'produce', sc: 'pome', ut: 'each', su: 'each' },
  {
    n: 'Pear, Bartlett',
    c: 'produce',
    sc: 'pome',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'peel and dice', y: 75 }],
  },
  { n: 'Pear, Bosc', c: 'produce', sc: 'pome', ut: 'each', su: 'each' },
  {
    n: 'Banana',
    c: 'produce',
    sc: 'tropical',
    ut: 'each',
    su: 'each',
    cw: 225,
    pa: [{ a: 'peel', y: 65 }],
  },
  {
    n: 'Mango',
    c: 'produce',
    sc: 'tropical',
    ut: 'each',
    su: 'each',
    cw: 165,
    pa: [{ a: 'peel and dice', y: 60 }],
  },
  {
    n: 'Pineapple',
    c: 'produce',
    sc: 'tropical',
    ut: 'each',
    su: 'each',
    cw: 165,
    pa: [{ a: 'peel and core', y: 50 }],
  },
  {
    n: 'Papaya',
    c: 'produce',
    sc: 'tropical',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'peel and seed', y: 55 }],
  },
  {
    n: 'Passion fruit',
    c: 'produce',
    sc: 'tropical',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'scoop', y: 50 }],
  },
  { n: 'Coconut, fresh', c: 'produce', sc: 'tropical', at: ['tree_nuts'], ut: 'each', su: 'each' },
  { n: 'Strawberries', c: 'produce', sc: 'berry', cw: 152, pa: [{ a: 'hull and slice', y: 88 }] },
  { n: 'Blueberries', c: 'produce', sc: 'berry', cw: 148 },
  { n: 'Raspberries', c: 'produce', sc: 'berry', cw: 123 },
  { n: 'Blackberries', c: 'produce', sc: 'berry', cw: 144 },
  { n: 'Cranberries, fresh', c: 'produce', sc: 'berry', cw: 100 },
  { n: 'Grapes, red', c: 'produce', sc: 'berry', cw: 151, pa: [{ a: 'halve', y: 95 }] },
  { n: 'Grapes, green', c: 'produce', sc: 'berry', cw: 151 },
  { n: 'Cherries', c: 'produce', sc: 'stone', cw: 138, pa: [{ a: 'pit', y: 82 }] },
  {
    n: 'Peach',
    c: 'produce',
    sc: 'stone',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'peel and slice', y: 75 }],
  },
  { n: 'Nectarine', c: 'produce', sc: 'stone', ut: 'each', su: 'each' },
  {
    n: 'Plum',
    c: 'produce',
    sc: 'stone',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'pit and slice', y: 85 }],
  },
  { n: 'Apricot', c: 'produce', sc: 'stone', ut: 'each', su: 'each' },
  {
    n: 'Fig, fresh',
    c: 'produce',
    sc: 'stone',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'quarter', y: 95 }],
  },
  {
    n: 'Pomegranate',
    c: 'produce',
    sc: 'other',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'seed', y: 40 }],
  },
  {
    n: 'Melon, cantaloupe',
    c: 'produce',
    sc: 'melon',
    ut: 'each',
    su: 'each',
    cw: 160,
    pa: [{ a: 'peel and dice', y: 50 }],
  },
  {
    n: 'Melon, honeydew',
    c: 'produce',
    sc: 'melon',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'peel and dice', y: 50 }],
  },
  {
    n: 'Watermelon',
    c: 'produce',
    sc: 'melon',
    ut: 'each',
    su: 'each',
    cw: 152,
    pa: [{ a: 'rind and dice', y: 55 }],
  },
  { n: 'Dates, Medjool', c: 'produce', sc: 'dried', cw: 147, pa: [{ a: 'pit', y: 88 }] },
  { n: 'Raisins', c: 'produce', sc: 'dried', cw: 145 },
  { n: 'Dried cranberries', c: 'produce', sc: 'dried', cw: 120 },
  { n: 'Dried apricots', c: 'produce', sc: 'dried', cw: 130 },
  { n: 'Prunes', c: 'produce', sc: 'dried', cw: 174, pa: [{ a: 'chop', y: 90 }] },
  {
    n: 'Plantain',
    c: 'produce',
    sc: 'tropical',
    ut: 'each',
    su: 'each',
    pa: [
      { a: 'peel', y: 70 },
      { a: 'slice', y: 68 },
    ],
  },
  {
    n: 'Star fruit',
    c: 'produce',
    sc: 'tropical',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'slice', y: 90 }],
  },
]

// ============================================================================
// FRESH HERBS (~25)
// ============================================================================
const freshHerbs: SeedIngredient[] = [
  {
    n: 'Basil, fresh',
    c: 'fresh_herb',
    ut: 'bunch',
    su: 'bunch',
    cw: 24,
    tw: 2.6,
    pa: [{ a: 'chiffonade', y: 75 }],
  },
  {
    n: 'Cilantro',
    c: 'fresh_herb',
    ut: 'bunch',
    su: 'bunch',
    cw: 16,
    tw: 1,
    pa: [{ a: 'chop', y: 70 }],
  },
  {
    n: 'Parsley, flat-leaf',
    c: 'fresh_herb',
    ut: 'bunch',
    su: 'bunch',
    cw: 60,
    tw: 3.8,
    pa: [{ a: 'chop', y: 65 }],
  },
  { n: 'Parsley, curly', c: 'fresh_herb', ut: 'bunch', su: 'bunch', cw: 60, tw: 3.8 },
  {
    n: 'Dill, fresh',
    c: 'fresh_herb',
    ut: 'bunch',
    su: 'bunch',
    cw: 8.9,
    pa: [{ a: 'pick fronds', y: 50 }],
  },
  {
    n: 'Mint, fresh',
    c: 'fresh_herb',
    ut: 'bunch',
    su: 'bunch',
    cw: 11,
    pa: [{ a: 'chiffonade', y: 65 }],
  },
  {
    n: 'Thyme, fresh',
    c: 'fresh_herb',
    ut: 'bunch',
    su: 'bunch',
    tw: 0.8,
    pa: [{ a: 'strip leaves', y: 40 }],
  },
  {
    n: 'Rosemary, fresh',
    c: 'fresh_herb',
    ut: 'bunch',
    su: 'bunch',
    tw: 1.7,
    pa: [{ a: 'strip and mince', y: 45 }],
  },
  {
    n: 'Sage, fresh',
    c: 'fresh_herb',
    ut: 'bunch',
    su: 'bunch',
    tw: 2,
    pa: [{ a: 'chiffonade', y: 80 }],
  },
  {
    n: 'Oregano, fresh',
    c: 'fresh_herb',
    ut: 'bunch',
    su: 'bunch',
    tw: 1.5,
    pa: [{ a: 'strip leaves', y: 45 }],
  },
  {
    n: 'Tarragon, fresh',
    c: 'fresh_herb',
    ut: 'bunch',
    su: 'bunch',
    tw: 1.4,
    pa: [{ a: 'strip leaves', y: 50 }],
  },
  {
    n: 'Chives, fresh',
    c: 'fresh_herb',
    ut: 'bunch',
    su: 'bunch',
    tw: 3,
    pa: [{ a: 'mince', y: 90 }],
  },
  { n: 'Bay leaf, fresh', c: 'fresh_herb', ut: 'each', su: 'each' },
  {
    n: 'Lemongrass',
    c: 'fresh_herb',
    ut: 'each',
    su: 'each',
    pa: [{ a: 'trim and smash', y: 35 }],
  },
  { n: 'Thai basil', c: 'fresh_herb', ut: 'bunch', su: 'bunch' },
  {
    n: 'Marjoram, fresh',
    c: 'fresh_herb',
    ut: 'bunch',
    su: 'bunch',
    pa: [{ a: 'strip leaves', y: 45 }],
  },
  { n: 'Lavender, fresh', c: 'fresh_herb', ut: 'bunch', su: 'bunch' },
  { n: 'Epazote', c: 'fresh_herb', ut: 'bunch', su: 'bunch' },
  { n: 'Culantro', c: 'fresh_herb', ut: 'bunch', su: 'bunch' },
  { n: 'Shiso', c: 'fresh_herb', ut: 'bunch', su: 'bunch' },
  { n: 'Curry leaves', c: 'fresh_herb', ut: 'bunch', su: 'bunch' },
  { n: 'Kaffir lime leaves', c: 'fresh_herb', ut: 'each', su: 'each' },
  { n: 'Microgreens', c: 'fresh_herb', cw: 15 },
  { n: 'Chervil', c: 'fresh_herb', ut: 'bunch', su: 'bunch', pa: [{ a: 'pick', y: 55 }] },
  { n: 'Sorrel', c: 'fresh_herb', ut: 'bunch', su: 'bunch', pa: [{ a: 'chiffonade', y: 80 }] },
]

// ============================================================================
// SPICES & DRIED HERBS (~40)
// ============================================================================
const spices: SeedIngredient[] = [
  { n: 'Black pepper, ground', c: 'spice', tw: 6.9 },
  { n: 'Black peppercorns, whole', c: 'spice', tw: 6.4 },
  { n: 'White pepper', c: 'spice', tw: 7 },
  { n: 'Kosher salt', c: 'spice', tw: 18, cw: 288 },
  { n: 'Sea salt, flaky (Maldon)', c: 'spice', tw: 12 },
  { n: 'Cumin, ground', c: 'spice', tw: 6, pa: [{ a: 'toast', y: 100 }] },
  { n: 'Cumin seeds', c: 'spice', tw: 6 },
  { n: 'Coriander, ground', c: 'spice', tw: 5 },
  { n: 'Coriander seeds', c: 'spice', tw: 5 },
  { n: 'Paprika, sweet', c: 'spice', tw: 6.8 },
  { n: 'Paprika, smoked (pimenton)', c: 'spice', tw: 6.8 },
  { n: 'Cayenne pepper', c: 'spice', tw: 5.3 },
  { n: 'Red pepper flakes', c: 'spice', tw: 4.8 },
  { n: 'Chili powder', c: 'spice', tw: 7.5 },
  { n: 'Turmeric, ground', c: 'spice', tw: 7 },
  { n: 'Cinnamon, ground', c: 'spice', tw: 7.8 },
  { n: 'Cinnamon sticks', c: 'spice', ut: 'each', su: 'each' },
  { n: 'Nutmeg, whole', c: 'spice', ut: 'each', su: 'each' },
  { n: 'Nutmeg, ground', c: 'spice', tw: 7 },
  { n: 'Cloves, whole', c: 'spice', tw: 6.6 },
  { n: 'Cloves, ground', c: 'spice', tw: 7 },
  { n: 'Cardamom pods', c: 'spice', tw: 5.8 },
  { n: 'Cardamom, ground', c: 'spice', tw: 5.8 },
  { n: 'Star anise', c: 'spice', ut: 'each', su: 'each' },
  { n: 'Fennel seeds', c: 'spice', tw: 6.7 },
  { n: 'Mustard seeds', c: 'spice', tw: 10.2 },
  { n: 'Mustard, dry', c: 'spice', tw: 6.3 },
  { n: 'Oregano, dried', c: 'dry_herb', tw: 1.8 },
  { n: 'Thyme, dried', c: 'dry_herb', tw: 1.4 },
  { n: 'Rosemary, dried', c: 'dry_herb', tw: 1.2 },
  { n: 'Bay leaves, dried', c: 'dry_herb', ut: 'each', su: 'each' },
  { n: 'Sage, dried', c: 'dry_herb', tw: 0.7 },
  { n: 'Herbes de Provence', c: 'dry_herb', tw: 1.3 },
  { n: 'Italian seasoning', c: 'dry_herb', tw: 1.5 },
  { n: 'Garam masala', c: 'spice', tw: 5.8 },
  { n: 'Curry powder', c: 'spice', tw: 6.3 },
  { n: "Za'atar", c: 'spice', tw: 3.5 },
  { n: 'Sumac', c: 'spice', tw: 4 },
  { n: 'Saffron threads', c: 'spice' },
  { n: 'Vanilla extract', c: 'spice', ut: 'volume', su: 'ml', tw: 13 },
  { n: 'Vanilla bean', c: 'spice', ut: 'each', su: 'each', pa: [{ a: 'split and scrape', y: 20 }] },
  { n: 'Allspice, ground', c: 'spice', tw: 6.1 },
  { n: 'Juniper berries', c: 'spice' },
  { n: 'Szechuan peppercorns', c: 'spice' },
  { n: 'Onion powder', c: 'spice', tw: 7 },
  { n: 'Garlic powder', c: 'spice', tw: 8.7 },
]

// ============================================================================
// DAIRY & EGGS (~30)
// ============================================================================
const dairy: SeedIngredient[] = [
  {
    n: 'Butter, unsalted',
    c: 'dairy',
    at: ['milk'],
    cw: 227,
    tw: 14.2,
    pa: [{ a: 'clarify', y: 75 }],
  },
  { n: 'Butter, salted', c: 'dairy', at: ['milk'], cw: 227, tw: 14.2 },
  { n: 'Heavy cream', c: 'dairy', at: ['milk'], ut: 'volume', su: 'ml', cw: 238, tw: 15 },
  { n: 'Half-and-half', c: 'dairy', at: ['milk'], ut: 'volume', su: 'ml', cw: 242, tw: 15 },
  { n: 'Whole milk', c: 'dairy', at: ['milk'], ut: 'volume', su: 'ml', cw: 244, tw: 15.3 },
  { n: 'Buttermilk', c: 'dairy', at: ['milk'], ut: 'volume', su: 'ml', cw: 245, tw: 15.3 },
  { n: 'Sour cream', c: 'dairy', at: ['milk'], cw: 230, tw: 14.4 },
  { n: 'Creme fraiche', c: 'dairy', at: ['milk'], cw: 232, tw: 14.5 },
  { n: 'Greek yogurt', c: 'dairy', at: ['milk'], cw: 245 },
  { n: 'Cream cheese', c: 'dairy', at: ['milk'], cw: 232, tw: 14.5 },
  { n: 'Mascarpone', c: 'dairy', at: ['milk'], cw: 227 },
  { n: 'Ricotta', c: 'dairy', at: ['milk'], cw: 246 },
  {
    n: 'Parmesan (Parmigiano-Reggiano)',
    c: 'dairy',
    at: ['milk'],
    cw: 100,
    tw: 5,
    pa: [
      { a: 'grate', y: 95 },
      { a: 'shave', y: 90 },
    ],
  },
  { n: 'Pecorino Romano', c: 'dairy', at: ['milk'], cw: 100, tw: 5, pa: [{ a: 'grate', y: 95 }] },
  { n: 'Gruyere', c: 'dairy', at: ['milk'], cw: 108, pa: [{ a: 'grate', y: 95 }] },
  { n: 'Cheddar, sharp', c: 'dairy', at: ['milk'], cw: 113, pa: [{ a: 'grate', y: 95 }] },
  {
    n: 'Mozzarella, fresh',
    c: 'dairy',
    at: ['milk'],
    pa: [
      { a: 'slice', y: 95 },
      { a: 'tear', y: 95 },
    ],
  },
  { n: 'Mozzarella, low-moisture', c: 'dairy', at: ['milk'], cw: 112, pa: [{ a: 'grate', y: 95 }] },
  { n: 'Goat cheese (chevre)', c: 'dairy', at: ['milk'] },
  { n: 'Blue cheese', c: 'dairy', at: ['milk'] },
  { n: 'Feta', c: 'dairy', at: ['milk'], cw: 150 },
  { n: 'Brie', c: 'dairy', at: ['milk'] },
  { n: 'Burrata', c: 'dairy', at: ['milk'] },
  { n: 'Manchego', c: 'dairy', at: ['milk'] },
  {
    n: 'Egg, large',
    c: 'dairy',
    sc: 'egg',
    at: ['egg'],
    ut: 'each',
    su: 'each',
    pa: [{ a: 'separate', y: 100 }],
  },
  { n: 'Egg yolk', c: 'dairy', sc: 'egg', at: ['egg'], ut: 'each', su: 'each' },
  { n: 'Egg white', c: 'dairy', sc: 'egg', at: ['egg'], ut: 'each', su: 'each' },
  { n: 'Quail egg', c: 'dairy', sc: 'egg', at: ['egg'], ut: 'each', su: 'each' },
  { n: 'Condensed milk, sweetened', c: 'dairy', at: ['milk'], ut: 'volume', su: 'ml' },
  { n: 'Evaporated milk', c: 'dairy', at: ['milk'], ut: 'volume', su: 'ml' },
]

// ============================================================================
// OILS & FATS (~15)
// ============================================================================
const oils: SeedIngredient[] = [
  { n: 'Olive oil, extra virgin', c: 'oil', ut: 'volume', su: 'ml', tw: 13.5 },
  { n: 'Olive oil, light/pure', c: 'oil', ut: 'volume', su: 'ml', tw: 13.5 },
  { n: 'Vegetable oil', c: 'oil', ut: 'volume', su: 'ml', tw: 13.6 },
  { n: 'Canola oil', c: 'oil', ut: 'volume', su: 'ml', tw: 13.6 },
  { n: 'Avocado oil', c: 'oil', ut: 'volume', su: 'ml', tw: 14 },
  { n: 'Coconut oil', c: 'oil', at: ['tree_nuts'], cw: 218, tw: 13.6 },
  { n: 'Sesame oil', c: 'oil', at: ['sesame'], ut: 'volume', su: 'ml', tw: 13.6 },
  { n: 'Toasted sesame oil', c: 'oil', at: ['sesame'], ut: 'volume', su: 'ml', tw: 13.6 },
  { n: 'Grapeseed oil', c: 'oil', ut: 'volume', su: 'ml', tw: 13.6 },
  { n: 'Walnut oil', c: 'oil', at: ['tree_nuts'], ut: 'volume', su: 'ml', tw: 13.6 },
  { n: 'Truffle oil', c: 'oil', ut: 'volume', su: 'ml' },
  { n: 'Ghee', c: 'oil', at: ['milk'], cw: 205, tw: 13 },
  { n: 'Lard', c: 'oil', cw: 205, tw: 12.8 },
  { n: 'Duck fat', c: 'oil', cw: 205, tw: 12.8 },
  { n: 'Cooking spray', c: 'oil', ut: 'each', su: 'each' },
]

// ============================================================================
// GRAINS & PASTA (~30)
// ============================================================================
const grains: SeedIngredient[] = [
  { n: 'All-purpose flour', c: 'pantry', sc: 'flour', at: ['wheat'], cw: 125, tw: 7.8 },
  { n: 'Bread flour', c: 'pantry', sc: 'flour', at: ['wheat'], cw: 127, tw: 7.9 },
  { n: 'Cake flour', c: 'pantry', sc: 'flour', at: ['wheat'], cw: 114, tw: 7.1 },
  { n: 'Whole wheat flour', c: 'pantry', sc: 'flour', at: ['wheat'], cw: 120, tw: 7.5 },
  { n: 'Semolina flour', c: 'pantry', sc: 'flour', at: ['wheat'], cw: 167 },
  { n: 'Almond flour', c: 'pantry', sc: 'flour', at: ['tree_nuts'], cw: 96, tw: 6 },
  { n: 'Coconut flour', c: 'pantry', sc: 'flour', at: ['tree_nuts'], cw: 112, tw: 7 },
  { n: 'Rice flour', c: 'pantry', sc: 'flour', cw: 158 },
  { n: 'White rice, long-grain', c: 'pantry', sc: 'grain', cw: 185 },
  { n: 'White rice, jasmine', c: 'pantry', sc: 'grain', cw: 185 },
  { n: 'White rice, basmati', c: 'pantry', sc: 'grain', cw: 185 },
  { n: 'Brown rice', c: 'pantry', sc: 'grain', cw: 185 },
  { n: 'Arborio rice (risotto)', c: 'pantry', sc: 'grain', cw: 185 },
  { n: 'Sushi rice', c: 'pantry', sc: 'grain', cw: 185 },
  { n: 'Wild rice', c: 'pantry', sc: 'grain', cw: 160 },
  { n: 'Quinoa', c: 'pantry', sc: 'grain', cw: 170 },
  { n: 'Couscous', c: 'pantry', sc: 'grain', at: ['wheat'], cw: 173 },
  { n: 'Israeli couscous (pearl)', c: 'pantry', sc: 'grain', at: ['wheat'], cw: 173 },
  { n: 'Farro', c: 'pantry', sc: 'grain', at: ['wheat'], cw: 180 },
  { n: 'Barley, pearl', c: 'pantry', sc: 'grain', at: ['wheat'], cw: 184 },
  { n: 'Bulgur wheat', c: 'pantry', sc: 'grain', at: ['wheat'], cw: 140 },
  { n: 'Polenta (cornmeal)', c: 'pantry', sc: 'grain', cw: 157 },
  { n: 'Oats, rolled', c: 'pantry', sc: 'grain', cw: 81 },
  { n: 'Spaghetti', c: 'pantry', sc: 'pasta', at: ['wheat'] },
  { n: 'Penne', c: 'pantry', sc: 'pasta', at: ['wheat'] },
  { n: 'Rigatoni', c: 'pantry', sc: 'pasta', at: ['wheat'] },
  { n: 'Linguine', c: 'pantry', sc: 'pasta', at: ['wheat'] },
  { n: 'Fettuccine', c: 'pantry', sc: 'pasta', at: ['wheat'] },
  { n: 'Orzo', c: 'pantry', sc: 'pasta', at: ['wheat'] },
  { n: 'Egg noodles', c: 'pantry', sc: 'pasta', at: ['wheat', 'egg'] },
  { n: 'Rice noodles', c: 'pantry', sc: 'pasta' },
  { n: 'Soba noodles', c: 'pantry', sc: 'pasta', at: ['wheat'] },
  { n: 'Udon noodles', c: 'pantry', sc: 'pasta', at: ['wheat'] },
]

// ============================================================================
// LEGUMES & NUTS (~25)
// ============================================================================
const legumesNuts: SeedIngredient[] = [
  { n: 'Chickpeas, canned', c: 'canned', sc: 'legume', cw: 164 },
  { n: 'Chickpeas, dried', c: 'pantry', sc: 'legume', cw: 200 },
  { n: 'Black beans, canned', c: 'canned', sc: 'legume', cw: 172 },
  { n: 'Kidney beans, canned', c: 'canned', sc: 'legume', cw: 177 },
  { n: 'Cannellini beans, canned', c: 'canned', sc: 'legume', cw: 179 },
  { n: 'Navy beans, dried', c: 'pantry', sc: 'legume', cw: 182 },
  { n: 'Lentils, green/brown', c: 'pantry', sc: 'legume', cw: 192 },
  { n: 'Lentils, red', c: 'pantry', sc: 'legume', cw: 192 },
  { n: 'Lentils, French (du Puy)', c: 'pantry', sc: 'legume', cw: 192 },
  { n: 'Split peas', c: 'pantry', sc: 'legume', cw: 195 },
  { n: 'Peanuts, roasted', c: 'pantry', sc: 'nut', at: ['peanuts'], cw: 146 },
  { n: 'Peanut butter', c: 'pantry', sc: 'nut', at: ['peanuts'], cw: 258, tw: 16 },
  {
    n: 'Almonds, whole',
    c: 'pantry',
    sc: 'nut',
    at: ['tree_nuts'],
    cw: 143,
    pa: [
      { a: 'sliver', y: 95 },
      { a: 'blanch', y: 90 },
    ],
  },
  { n: 'Almonds, sliced', c: 'pantry', sc: 'nut', at: ['tree_nuts'], cw: 92 },
  { n: 'Almond butter', c: 'pantry', sc: 'nut', at: ['tree_nuts'], cw: 258, tw: 16 },
  {
    n: 'Walnuts',
    c: 'pantry',
    sc: 'nut',
    at: ['tree_nuts'],
    cw: 117,
    pa: [
      { a: 'chop', y: 95 },
      { a: 'toast', y: 95 },
    ],
  },
  {
    n: 'Pecans',
    c: 'pantry',
    sc: 'nut',
    at: ['tree_nuts'],
    cw: 109,
    pa: [
      { a: 'chop', y: 95 },
      { a: 'toast', y: 95 },
    ],
  },
  {
    n: 'Pine nuts',
    c: 'pantry',
    sc: 'nut',
    at: ['tree_nuts'],
    cw: 135,
    pa: [{ a: 'toast', y: 95 }],
  },
  { n: 'Cashews', c: 'pantry', sc: 'nut', at: ['tree_nuts'], cw: 137 },
  {
    n: 'Pistachios, shelled',
    c: 'pantry',
    sc: 'nut',
    at: ['tree_nuts'],
    cw: 123,
    pa: [{ a: 'chop', y: 95 }],
  },
  { n: 'Macadamia nuts', c: 'pantry', sc: 'nut', at: ['tree_nuts'], cw: 134 },
  {
    n: 'Hazelnuts',
    c: 'pantry',
    sc: 'nut',
    at: ['tree_nuts'],
    cw: 135,
    pa: [
      { a: 'skin', y: 88 },
      { a: 'chop', y: 95 },
    ],
  },
  { n: 'Tahini', c: 'pantry', sc: 'nut', at: ['sesame'], cw: 236, tw: 15 },
  { n: 'Sunflower seeds', c: 'pantry', sc: 'seed', cw: 140 },
  { n: 'Pumpkin seeds (pepitas)', c: 'pantry', sc: 'seed', cw: 129 },
  { n: 'Sesame seeds', c: 'pantry', sc: 'seed', at: ['sesame'], cw: 144, tw: 9 },
  { n: 'Chia seeds', c: 'pantry', sc: 'seed', cw: 170, tw: 12 },
  { n: 'Flax seeds', c: 'pantry', sc: 'seed', cw: 150, tw: 7 },
]

// ============================================================================
// CONDIMENTS & SAUCES (~30)
// ============================================================================
const condiments: SeedIngredient[] = [
  { n: 'Soy sauce', c: 'condiment', at: ['soy', 'wheat'], ut: 'volume', su: 'ml', tw: 16 },
  { n: 'Tamari (gluten-free soy)', c: 'condiment', at: ['soy'], ut: 'volume', su: 'ml', tw: 16 },
  { n: 'Fish sauce', c: 'condiment', at: ['fish'], ut: 'volume', su: 'ml', tw: 18 },
  { n: 'Oyster sauce', c: 'condiment', at: ['shellfish'], ut: 'volume', su: 'ml', tw: 18 },
  { n: 'Hoisin sauce', c: 'condiment', at: ['soy'], ut: 'volume', su: 'ml', tw: 16 },
  { n: 'Worcestershire sauce', c: 'condiment', at: ['fish'], ut: 'volume', su: 'ml', tw: 17 },
  { n: "Hot sauce (Tabasco/Frank's)", c: 'condiment', ut: 'volume', su: 'ml', tw: 15 },
  { n: 'Sriracha', c: 'condiment', ut: 'volume', su: 'ml', tw: 17 },
  { n: 'Sambal oelek', c: 'condiment', tw: 16 },
  { n: 'Gochujang', c: 'condiment', tw: 17 },
  { n: 'Harissa paste', c: 'condiment', tw: 15 },
  { n: 'Miso paste, white', c: 'condiment', at: ['soy'], tw: 17 },
  { n: 'Miso paste, red', c: 'condiment', at: ['soy'], tw: 17 },
  { n: 'Dijon mustard', c: 'condiment', tw: 15 },
  { n: 'Whole grain mustard', c: 'condiment', tw: 16 },
  { n: 'Yellow mustard', c: 'condiment', tw: 15 },
  { n: 'Ketchup', c: 'condiment', ut: 'volume', su: 'ml', tw: 17 },
  { n: 'Mayonnaise', c: 'condiment', at: ['egg'], cw: 220, tw: 13.8 },
  { n: 'Tomato paste', c: 'condiment', cw: 262, tw: 16.4 },
  { n: 'Tomato sauce', c: 'canned', ut: 'volume', su: 'ml' },
  { n: 'Crushed tomatoes, canned', c: 'canned' },
  { n: 'Whole peeled tomatoes, canned', c: 'canned' },
  { n: 'Sun-dried tomatoes', c: 'condiment', cw: 110 },
  { n: 'Capers', c: 'condiment', tw: 8.6 },
  { n: 'Olives, Kalamata', c: 'condiment', cw: 134, pa: [{ a: 'pit and chop', y: 75 }] },
  { n: 'Olives, Castelvetrano', c: 'condiment', pa: [{ a: 'pit', y: 80 }] },
  { n: 'Pickles, dill', c: 'condiment', pa: [{ a: 'dice', y: 92 }] },
  { n: 'Kimchi', c: 'condiment' },
  { n: 'Coconut aminos', c: 'condiment', ut: 'volume', su: 'ml', tw: 15 },
  { n: 'Pomegranate molasses', c: 'condiment', ut: 'volume', su: 'ml', tw: 20 },
]

// ============================================================================
// BAKING (~25)
// ============================================================================
const baking: SeedIngredient[] = [
  { n: 'Granulated sugar', c: 'baking', cw: 200, tw: 12.5 },
  { n: 'Brown sugar, light', c: 'baking', cw: 220, tw: 13.8 },
  { n: 'Brown sugar, dark', c: 'baking', cw: 220, tw: 13.8 },
  { n: 'Powdered sugar (confectioners)', c: 'baking', cw: 120, tw: 7.5 },
  { n: 'Honey', c: 'baking', cw: 340, tw: 21 },
  { n: 'Maple syrup', c: 'baking', cw: 312, tw: 20 },
  { n: 'Agave nectar', c: 'baking', cw: 336, tw: 21 },
  { n: 'Molasses', c: 'baking', cw: 328, tw: 20 },
  { n: 'Corn syrup, light', c: 'baking', cw: 328, tw: 20 },
  { n: 'Baking powder', c: 'baking', tw: 4.6 },
  { n: 'Baking soda', c: 'baking', tw: 13.8 },
  { n: 'Active dry yeast', c: 'baking', tw: 8.5 },
  { n: 'Instant yeast', c: 'baking', tw: 8 },
  { n: 'Cream of tartar', c: 'baking', tw: 3 },
  { n: 'Cornstarch', c: 'baking', cw: 128, tw: 8 },
  { n: 'Gelatin, unflavored', c: 'baking', tw: 9.3 },
  { n: 'Agar-agar', c: 'baking' },
  { n: 'Cocoa powder, unsweetened', c: 'baking', cw: 86, tw: 5.4 },
  { n: 'Chocolate chips, semisweet', c: 'baking', at: ['milk'], cw: 170 },
  { n: 'Chocolate, dark (70%)', c: 'baking', pa: [{ a: 'chop', y: 95 }] },
  { n: 'Chocolate, white', c: 'baking', at: ['milk'] },
  { n: 'Almond extract', c: 'baking', at: ['tree_nuts'], ut: 'volume', su: 'ml' },
  { n: 'Rose water', c: 'baking', ut: 'volume', su: 'ml' },
  { n: 'Orange blossom water', c: 'baking', ut: 'volume', su: 'ml' },
  { n: 'Food coloring, gel', c: 'baking' },
]

// ============================================================================
// VINEGARS & ACIDS (~10 - part of condiments/pantry)
// ============================================================================
const vinegars: SeedIngredient[] = [
  { n: 'Red wine vinegar', c: 'condiment', sc: 'vinegar', ut: 'volume', su: 'ml', tw: 15 },
  { n: 'White wine vinegar', c: 'condiment', sc: 'vinegar', ut: 'volume', su: 'ml', tw: 15 },
  { n: 'Balsamic vinegar', c: 'condiment', sc: 'vinegar', ut: 'volume', su: 'ml', tw: 16 },
  { n: 'Apple cider vinegar', c: 'condiment', sc: 'vinegar', ut: 'volume', su: 'ml', tw: 15 },
  { n: 'Rice vinegar', c: 'condiment', sc: 'vinegar', ut: 'volume', su: 'ml', tw: 15 },
  { n: 'Sherry vinegar', c: 'condiment', sc: 'vinegar', ut: 'volume', su: 'ml', tw: 15 },
  { n: 'Champagne vinegar', c: 'condiment', sc: 'vinegar', ut: 'volume', su: 'ml', tw: 15 },
  { n: 'Distilled white vinegar', c: 'condiment', sc: 'vinegar', ut: 'volume', su: 'ml', tw: 15 },
  { n: 'Mirin', c: 'condiment', sc: 'vinegar', ut: 'volume', su: 'ml', tw: 15 },
  { n: 'Rice wine (Shaoxing)', c: 'condiment', sc: 'vinegar', ut: 'volume', su: 'ml' },
]

// ============================================================================
// STOCKS & BROTHS (~10)
// ============================================================================
const stocks: SeedIngredient[] = [
  { n: 'Chicken stock', c: 'pantry', sc: 'stock', ut: 'volume', su: 'ml' },
  { n: 'Beef stock', c: 'pantry', sc: 'stock', ut: 'volume', su: 'ml' },
  { n: 'Vegetable stock', c: 'pantry', sc: 'stock', ut: 'volume', su: 'ml' },
  { n: 'Fish stock', c: 'pantry', sc: 'stock', at: ['fish'], ut: 'volume', su: 'ml' },
  { n: 'Seafood stock', c: 'pantry', sc: 'stock', at: ['shellfish'], ut: 'volume', su: 'ml' },
  { n: 'Dashi stock', c: 'pantry', sc: 'stock', at: ['fish'], ut: 'volume', su: 'ml' },
  { n: 'Bone broth', c: 'pantry', sc: 'stock', ut: 'volume', su: 'ml' },
  { n: 'Better Than Bouillon (chicken)', c: 'pantry', sc: 'stock', tw: 6 },
  { n: 'Better Than Bouillon (beef)', c: 'pantry', sc: 'stock', tw: 6 },
  { n: 'Bouillon cube', c: 'pantry', sc: 'stock', ut: 'each', su: 'each' },
]

// ============================================================================
// MISCELLANEOUS (~30)
// ============================================================================
const misc: SeedIngredient[] = [
  { n: 'Breadcrumbs, plain', c: 'pantry', sc: 'breadcrumb', at: ['wheat'], cw: 108, tw: 6.8 },
  { n: 'Breadcrumbs, Italian seasoned', c: 'pantry', sc: 'breadcrumb', at: ['wheat'], cw: 108 },
  { n: 'Panko breadcrumbs', c: 'pantry', sc: 'breadcrumb', at: ['wheat'], cw: 60 },
  { n: 'Coconut milk, canned (full-fat)', c: 'pantry', at: ['tree_nuts'], ut: 'volume', su: 'ml' },
  { n: 'Coconut milk, lite', c: 'pantry', at: ['tree_nuts'], ut: 'volume', su: 'ml' },
  { n: 'Coconut cream', c: 'pantry', at: ['tree_nuts'], cw: 228 },
  { n: 'Shredded coconut, unsweetened', c: 'pantry', at: ['tree_nuts'], cw: 93 },
  { n: 'Toasted coconut flakes', c: 'pantry', at: ['tree_nuts'], cw: 85 },
  { n: 'Tortillas, flour (10-inch)', c: 'pantry', at: ['wheat'], ut: 'each', su: 'each' },
  { n: 'Tortillas, corn', c: 'pantry', ut: 'each', su: 'each' },
  { n: 'Pita bread', c: 'pantry', at: ['wheat'], ut: 'each', su: 'each' },
  { n: 'Naan bread', c: 'pantry', at: ['wheat', 'milk'], ut: 'each', su: 'each' },
  { n: 'Phyllo dough', c: 'frozen', at: ['wheat'] },
  { n: 'Puff pastry', c: 'frozen', at: ['wheat', 'milk'] },
  { n: 'Wonton wrappers', c: 'pantry', at: ['wheat', 'egg'] },
  { n: 'Spring roll wrappers', c: 'pantry', at: ['wheat'] },
  { n: 'Anchovy paste', c: 'condiment', at: ['fish'], tw: 15 },
  { n: 'Chipotle peppers in adobo', c: 'canned' },
  { n: 'Roasted red peppers, jarred', c: 'canned' },
  { n: 'Artichoke hearts, canned', c: 'canned' },
  { n: 'Pumpkin puree, canned', c: 'canned', cw: 245 },
  { n: 'Coconut water', c: 'beverage', at: ['tree_nuts'], ut: 'volume', su: 'ml' },
  { n: 'Orange juice', c: 'beverage', ut: 'volume', su: 'ml' },
  { n: 'Lemon juice, bottled', c: 'condiment', ut: 'volume', su: 'ml', tw: 15 },
  { n: 'Lime juice, bottled', c: 'condiment', ut: 'volume', su: 'ml', tw: 15 },
  { n: 'White wine (cooking)', c: 'alcohol', ut: 'volume', su: 'ml' },
  { n: 'Red wine (cooking)', c: 'alcohol', ut: 'volume', su: 'ml' },
  { n: 'Marsala wine', c: 'alcohol', ut: 'volume', su: 'ml' },
  { n: 'Dry vermouth', c: 'alcohol', ut: 'volume', su: 'ml' },
  { n: 'Beer (for cooking)', c: 'alcohol', at: ['wheat'], ut: 'volume', su: 'ml' },
  { n: 'Brandy/Cognac', c: 'alcohol', ut: 'volume', su: 'ml' },
  { n: 'Kahlua', c: 'alcohol', ut: 'volume', su: 'ml' },
  { n: 'Grand Marnier', c: 'alcohol', ut: 'volume', su: 'ml' },
]

// ============================================================================
// EXPORT
// ============================================================================
export const SEED_INGREDIENTS: SeedIngredient[] = [
  ...proteins,
  ...vegetables,
  ...freshHerbs,
  ...spices,
  ...dairy,
  ...oils,
  ...grains,
  ...legumesNuts,
  ...condiments,
  ...baking,
  ...vinegars,
  ...stocks,
  ...misc,
  ...fruits,
]

// Map compact category code to ingredient_category enum values
const UNIT_TYPE_MAP: Record<string, string> = {
  weight: 'weight',
  volume: 'volume',
  each: 'each',
  bunch: 'bunch',
}
const UNIT_MAP: Record<string, string> = {
  g: 'g',
  oz: 'oz',
  ml: 'ml',
  fl_oz: 'fl_oz',
  each: 'each',
  bunch: 'bunch',
}

/**
 * Expand compact seed format into full DB row shape
 */
export function expandSeedIngredient(s: SeedIngredient) {
  return {
    name: s.n,
    category: s.c,
    subcategory: s.sc ?? '',
    unit_type: UNIT_TYPE_MAP[s.ut ?? 'weight'] ?? 'weight',
    standard_unit: UNIT_MAP[s.su ?? 'g'] ?? 'g',
    cup_weight_grams: s.cw ?? null,
    tbsp_weight_grams: s.tw ?? null,
    cost_per_unit_cents: s.ac ?? 0,
    allergen_tags: s.at ?? [],
    common_prep_actions: (s.pa ?? []).map((p) => ({ action: p.a, yield_pct: p.y })),
    is_active: true,
  }
}

export type ExpandedSeedIngredient = ReturnType<typeof expandSeedIngredient>
