-- ============================================================
-- Pending migrations from Codex period (April 22-23, 2026)
-- Generated by stabilization agent. NOT YET APPLIED.
-- Developer must review and approve before application.
-- ============================================================

-- SECTION 1: New enum types
-- communication_delivery_status (used by communication_events + conversation_threads)

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'communication_delivery_status') THEN
    CREATE TYPE communication_delivery_status AS ENUM ('pending', 'sent', 'delivered', 'read', 'failed');
  END IF;
END $$;

-- statement-breakpoint

-- ============================================================
-- SECTION 2: New tables
-- ============================================================

-- 2A: planning_runs
CREATE TABLE IF NOT EXISTS planning_runs (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY NOT NULL,
  tenant_id uuid NOT NULL,
  run_type text NOT NULL,
  run_source text DEFAULT 'interactive' NOT NULL,
  status text DEFAULT 'running' NOT NULL,
  scope_key text DEFAULT 'default' NOT NULL,
  as_of_date date NOT NULL,
  horizon_months integer NOT NULL,
  generator_version text NOT NULL,
  request_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
  summary_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
  error_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
  started_at timestamptz DEFAULT now() NOT NULL,
  completed_at timestamptz,

  CONSTRAINT planning_runs_tenant_id_fkey
    FOREIGN KEY (tenant_id) REFERENCES chefs(id) ON DELETE CASCADE,

  CONSTRAINT planning_runs_run_source_check
    CHECK (run_source = ANY (ARRAY['interactive'::text, 'scheduled'::text, 'manual'::text, 'repair'::text])),

  CONSTRAINT planning_runs_status_check
    CHECK (status = ANY (ARRAY['running'::text, 'completed'::text, 'failed'::text])),

  CONSTRAINT planning_runs_horizon_months_check
    CHECK (horizon_months > 0),

  CONSTRAINT planning_runs_scope_key_check
    CHECK (length(scope_key) > 0),

  CONSTRAINT planning_runs_run_type_check
    CHECK (length(run_type) > 0)
);

-- statement-breakpoint

CREATE INDEX IF NOT EXISTS idx_planning_runs_tenant_type_completed
  ON planning_runs USING btree (
    tenant_id ASC NULLS LAST,
    run_type ASC NULLS LAST,
    completed_at DESC NULLS FIRST,
    started_at DESC NULLS FIRST
  );

-- statement-breakpoint

CREATE INDEX IF NOT EXISTS idx_planning_runs_scope_horizon
  ON planning_runs USING btree (
    tenant_id ASC NULLS LAST,
    scope_key ASC NULLS LAST,
    horizon_months ASC NULLS LAST,
    as_of_date DESC NULLS FIRST
  );

-- statement-breakpoint

-- 2B: planning_run_artifacts
CREATE TABLE IF NOT EXISTS planning_run_artifacts (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY NOT NULL,
  tenant_id uuid NOT NULL,
  run_id uuid NOT NULL,
  artifact_key text NOT NULL,
  artifact_version text NOT NULL,
  payload jsonb DEFAULT '{}'::jsonb NOT NULL,
  provenance jsonb DEFAULT '{}'::jsonb NOT NULL,
  data_quality jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,

  CONSTRAINT planning_run_artifacts_run_id_fkey
    FOREIGN KEY (run_id) REFERENCES planning_runs(id) ON DELETE CASCADE,

  CONSTRAINT planning_run_artifacts_tenant_id_fkey
    FOREIGN KEY (tenant_id) REFERENCES chefs(id) ON DELETE CASCADE,

  CONSTRAINT planning_run_artifacts_run_id_artifact_key_key
    UNIQUE (run_id, artifact_key),

  CONSTRAINT planning_run_artifacts_artifact_key_check
    CHECK (length(artifact_key) > 0),

  CONSTRAINT planning_run_artifacts_artifact_version_check
    CHECK (length(artifact_version) > 0)
);

-- statement-breakpoint

CREATE INDEX IF NOT EXISTS idx_planning_run_artifacts_tenant_created
  ON planning_run_artifacts USING btree (
    tenant_id ASC NULLS LAST,
    created_at DESC NULLS FIRST
  );

-- statement-breakpoint

-- 2C: directory_listing_favorites
CREATE TABLE IF NOT EXISTS directory_listing_favorites (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY NOT NULL,
  client_id uuid NOT NULL,
  listing_id uuid NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,

  CONSTRAINT directory_listing_favorites_client_id_fkey
    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,

  CONSTRAINT directory_listing_favorites_listing_id_fkey
    FOREIGN KEY (listing_id) REFERENCES directory_listings(id) ON DELETE CASCADE,

  CONSTRAINT directory_listing_favorites_client_id_listing_id_key
    UNIQUE (client_id, listing_id)
);

-- statement-breakpoint

CREATE INDEX IF NOT EXISTS idx_directory_listing_favorites_client_created
  ON directory_listing_favorites USING btree (
    client_id ASC NULLS LAST,
    created_at DESC NULLS FIRST
  );

-- statement-breakpoint

CREATE INDEX IF NOT EXISTS idx_directory_listing_favorites_listing
  ON directory_listing_favorites USING btree (
    listing_id ASC NULLS LAST
  );

-- statement-breakpoint

-- ============================================================
-- SECTION 3: Altered tables (new columns on existing tables)
-- ============================================================

-- 3A: communication_events (12 new columns)

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'communication_events' AND column_name = 'external_thread_key'
  ) THEN
    ALTER TABLE communication_events ADD COLUMN external_thread_key text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'communication_events' AND column_name = 'provider_name'
  ) THEN
    ALTER TABLE communication_events ADD COLUMN provider_name text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'communication_events' AND column_name = 'managed_channel_address'
  ) THEN
    ALTER TABLE communication_events ADD COLUMN managed_channel_address text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'communication_events' AND column_name = 'recipient_address'
  ) THEN
    ALTER TABLE communication_events ADD COLUMN recipient_address text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'communication_events' AND column_name = 'provider_delivery_status'
  ) THEN
    ALTER TABLE communication_events ADD COLUMN provider_delivery_status communication_delivery_status;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'communication_events' AND column_name = 'provider_status'
  ) THEN
    ALTER TABLE communication_events ADD COLUMN provider_status text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'communication_events' AND column_name = 'provider_status_updated_at'
  ) THEN
    ALTER TABLE communication_events ADD COLUMN provider_status_updated_at timestamptz;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'communication_events' AND column_name = 'provider_delivered_at'
  ) THEN
    ALTER TABLE communication_events ADD COLUMN provider_delivered_at timestamptz;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'communication_events' AND column_name = 'provider_read_at'
  ) THEN
    ALTER TABLE communication_events ADD COLUMN provider_read_at timestamptz;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'communication_events' AND column_name = 'provider_failed_at'
  ) THEN
    ALTER TABLE communication_events ADD COLUMN provider_failed_at timestamptz;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'communication_events' AND column_name = 'provider_error_code'
  ) THEN
    ALTER TABLE communication_events ADD COLUMN provider_error_code text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'communication_events' AND column_name = 'provider_error_message'
  ) THEN
    ALTER TABLE communication_events ADD COLUMN provider_error_message text;
  END IF;
END $$;

-- statement-breakpoint

-- 3B: conversation_threads (8 new columns)

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'conversation_threads' AND column_name = 'external_thread_key'
  ) THEN
    ALTER TABLE conversation_threads ADD COLUMN external_thread_key text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'conversation_threads' AND column_name = 'latest_outbound_event_id'
  ) THEN
    ALTER TABLE conversation_threads ADD COLUMN latest_outbound_event_id uuid;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'conversation_threads' AND column_name = 'latest_outbound_attempted_at'
  ) THEN
    ALTER TABLE conversation_threads ADD COLUMN latest_outbound_attempted_at timestamptz;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'conversation_threads' AND column_name = 'latest_outbound_delivery_status'
  ) THEN
    ALTER TABLE conversation_threads ADD COLUMN latest_outbound_delivery_status communication_delivery_status;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'conversation_threads' AND column_name = 'latest_outbound_provider_status'
  ) THEN
    ALTER TABLE conversation_threads ADD COLUMN latest_outbound_provider_status text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'conversation_threads' AND column_name = 'latest_outbound_status_updated_at'
  ) THEN
    ALTER TABLE conversation_threads ADD COLUMN latest_outbound_status_updated_at timestamptz;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'conversation_threads' AND column_name = 'latest_outbound_error_code'
  ) THEN
    ALTER TABLE conversation_threads ADD COLUMN latest_outbound_error_code text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'conversation_threads' AND column_name = 'latest_outbound_error_message'
  ) THEN
    ALTER TABLE conversation_threads ADD COLUMN latest_outbound_error_message text;
  END IF;
END $$;

-- statement-breakpoint

-- 3C: guest_count_changes (4 new columns + FK + CHECK)

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'guest_count_changes' AND column_name = 'status'
  ) THEN
    ALTER TABLE guest_count_changes ADD COLUMN status text DEFAULT 'pending' NOT NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'guest_count_changes' AND column_name = 'reviewed_by'
  ) THEN
    ALTER TABLE guest_count_changes ADD COLUMN reviewed_by uuid;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'guest_count_changes' AND column_name = 'reviewed_at'
  ) THEN
    ALTER TABLE guest_count_changes ADD COLUMN reviewed_at timestamptz;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'guest_count_changes' AND column_name = 'review_notes'
  ) THEN
    ALTER TABLE guest_count_changes ADD COLUMN review_notes text;
  END IF;
END $$;

-- statement-breakpoint

-- guest_count_changes FK: reviewed_by -> users(id) ON DELETE SET NULL
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'guest_count_changes_reviewed_by_fkey'
    AND table_name = 'guest_count_changes'
  ) THEN
    ALTER TABLE guest_count_changes
      ADD CONSTRAINT guest_count_changes_reviewed_by_fkey
      FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL;
  END IF;
END $$;

-- statement-breakpoint

-- guest_count_changes CHECK: status in ('pending', 'approved', 'rejected')
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'guest_count_changes_status_check'
    AND table_name = 'guest_count_changes'
  ) THEN
    ALTER TABLE guest_count_changes
      ADD CONSTRAINT guest_count_changes_status_check
      CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text]));
  END IF;
END $$;

-- statement-breakpoint

-- ============================================================
-- SECTION 4: New indexes on altered tables
-- ============================================================

-- communication_events indexes (partial, conditional)
CREATE INDEX IF NOT EXISTS idx_comm_events_delivery_status
  ON communication_events USING btree (
    tenant_id ASC NULLS LAST,
    provider_delivery_status ASC NULLS LAST,
    provider_status_updated_at DESC NULLS FIRST
  )
  WHERE provider_delivery_status IS NOT NULL;

-- statement-breakpoint

CREATE INDEX IF NOT EXISTS idx_comm_events_external_thread
  ON communication_events USING btree (
    tenant_id ASC NULLS LAST,
    source ASC NULLS LAST,
    external_thread_key ASC NULLS LAST
  )
  WHERE external_thread_key IS NOT NULL;

-- statement-breakpoint

CREATE INDEX IF NOT EXISTS idx_comm_events_provider
  ON communication_events USING btree (
    tenant_id ASC NULLS LAST,
    provider_name ASC NULLS LAST,
    "timestamp" DESC NULLS FIRST
  )
  WHERE provider_name IS NOT NULL;

-- statement-breakpoint

-- conversation_threads indexes
CREATE INDEX IF NOT EXISTS idx_threads_latest_outbound_delivery
  ON conversation_threads USING btree (
    tenant_id ASC NULLS LAST,
    latest_outbound_delivery_status ASC NULLS LAST,
    latest_outbound_status_updated_at DESC NULLS FIRST
  )
  WHERE latest_outbound_delivery_status IS NOT NULL;

-- statement-breakpoint

CREATE UNIQUE INDEX IF NOT EXISTS uq_threads_external_key
  ON conversation_threads USING btree (
    tenant_id ASC NULLS LAST,
    external_thread_key ASC NULLS LAST
  )
  WHERE external_thread_key IS NOT NULL;

-- statement-breakpoint

-- guest_count_changes index
CREATE INDEX IF NOT EXISTS idx_guest_count_changes_event_status
  ON guest_count_changes USING btree (
    event_id ASC NULLS LAST,
    status ASC NULLS LAST,
    created_at DESC NULLS FIRST
  );

-- ============================================================
-- END OF PENDING MIGRATIONS
-- ============================================================
