// Public Partner Contribution Report
// Read-only, no auth required.
// Shows a chef's service history at a partner's location(s).
// URL generated by the chef via "Share with Partner" on the partner detail page.

import { headers } from 'next/headers'
import { checkRateLimit } from '@/lib/rateLimit'
import { getPartnerContributionReport } from '@/lib/partners/actions'
import { TokenExpiredPage } from '@/components/ui/token-expired-page'
import { PartnerContributionReport } from '@/components/partners/partner-contribution-report'

export default async function PublicPartnerReportPage({ params }: { params: { token: string } }) {
  const headersList = await headers()
  const ip = headersList.get('x-forwarded-for')?.split(',')[0] || 'unknown'

  try {
    await checkRateLimit(`partner-report:${ip}`, 30, 15 * 60 * 1000)
  } catch {
    return (
      <div className="min-h-screen flex items-center justify-center text-stone-400">
        Too many requests. Please try again later.
      </div>
    )
  }

  const data = await getPartnerContributionReport(params.token)

  if (!data) {
    return <TokenExpiredPage reason="expired" noun="report" />
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-stone-50 to-white">
      <div className="max-w-3xl mx-auto px-4 py-10 sm:py-14">
        <PartnerContributionReport
          partner={data.partner}
          chef={data.chef}
          stats={data.stats}
          events={data.events}
          location_map={data.location_map}
          by_location={data.by_location}
        />
      </div>
    </div>
  )
}
