// Public Partner Contribution Report
// Read-only, no auth required.
// Shows a chef's service history at a partner's location(s).
// URL generated by the chef via "Share with Partner" on the partner detail page.

import { notFound } from 'next/navigation'
import { getPartnerContributionReport } from '@/lib/partners/actions'
import { PartnerContributionReport } from '@/components/partners/partner-contribution-report'

export default async function PublicPartnerReportPage({
  params,
}: {
  params: { token: string }
}) {
  const data = await getPartnerContributionReport(params.token)

  if (!data) {
    notFound()
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-stone-50 to-white">
      <div className="max-w-3xl mx-auto px-4 py-10 sm:py-14">
        <PartnerContributionReport
          partner={data.partner}
          chef={data.chef}
          stats={data.stats}
          events={data.events}
          location_map={data.location_map}
          by_location={data.by_location}
        />
      </div>
    </div>
  )
}
