#!/bin/bash
# Hermes Job 10: Weekly Trend Digest
# Runs every Sunday at 6:00 AM. Compiles weekly trends from all job data.
# Output: docs/hermes/weekly-digest.md

CHEFFLOW="/mnt/c/Users/david/Documents/CFv1"
HERMES_DIR="$CHEFFLOW/docs/hermes"
OUTPUT="$HERMES_DIR/weekly-digest.md"
WEEK_START=$(date -d "7 days ago" +"%Y-%m-%d")
WEEK_END=$(date +"%Y-%m-%d")
NOW=$(date +"%Y-%m-%d %H:%M")

mkdir -p "$HERMES_DIR"
cd "$CHEFFLOW" || exit 1

# ── Git Velocity ──────────────────────────────────────────────
TOTAL_COMMITS=$(git log --oneline --since="7 days ago" 2>/dev/null | wc -l | tr -d ' ')
FEAT_COMMITS=$(git log --oneline --since="7 days ago" 2>/dev/null | grep -c "^[a-f0-9]* feat" || echo "0")
FIX_COMMITS=$(git log --oneline --since="7 days ago" 2>/dev/null | grep -c "^[a-f0-9]* fix" || echo "0")

# Commits per day
DAILY_AVG=$((TOTAL_COMMITS / 7))

# Top domains
TOP_DOMAINS=$(git log --oneline --since="7 days ago" 2>/dev/null | grep -oP '(?<=\()[^)]+(?=\))' | sort | uniq -c | sort -rn | head -10)

# Most changed files
WEEK_HASH=$(git log --oneline --since="7 days ago" --format="%H" 2>/dev/null | tail -1)
MOST_CHANGED=""
if [ -n "$WEEK_HASH" ]; then
  MOST_CHANGED=$(git diff --stat "$WEEK_HASH" HEAD 2>/dev/null | grep -v "files changed" | sort -t'|' -k2 -rn | head -15)
fi

# ── Health Trends ─────────────────────────────────────────────
HEALTH_FILE="$HERMES_DIR/health-pulse.jsonl"
HEALTH_TOTAL=0
HEALTH_OK=0
HEALTH_FAIL=0
SERVER_DOWN=0
if [ -f "$HEALTH_FILE" ]; then
  HEALTH_TOTAL=$(wc -l < "$HEALTH_FILE" | tr -d ' ')
  HEALTH_OK=$(grep -c '"all_ok":true' "$HEALTH_FILE" 2>/dev/null || echo "0")
  HEALTH_FAIL=$((HEALTH_TOTAL - HEALTH_OK))
  SERVER_DOWN=$(grep -c '"server_running":false' "$HEALTH_FILE" 2>/dev/null || echo "0")
fi
UPTIME_PCT=0
if [ "$HEALTH_TOTAL" -gt 0 ]; then
  UPTIME_PCT=$(( (HEALTH_OK * 100) / HEALTH_TOTAL ))
fi

# ── Alert Summary ─────────────────────────────────────────────
ALERT_FILE="$HERMES_DIR/ALERTS.md"
TOTAL_ALERTS=0
CRITICAL_ALERTS=0
WARN_ALERTS=0
ERROR_ALERTS=0
if [ -f "$ALERT_FILE" ]; then
  TOTAL_ALERTS=$(wc -l < "$ALERT_FILE" | tr -d ' ')
  CRITICAL_ALERTS=$(grep -c "\[CRITICAL\]" "$ALERT_FILE" 2>/dev/null || echo "0")
  ERROR_ALERTS=$(grep -c "\[ERROR\]" "$ALERT_FILE" 2>/dev/null || echo "0")
  WARN_ALERTS=$(grep -c "\[WARN\]" "$ALERT_FILE" 2>/dev/null || echo "0")
fi

# ── DB Trends ─────────────────────────────────────────────────
DB_FILE="$HERMES_DIR/db-health.jsonl"
DB_SUMMARY="No database health data this week."
if [ -f "$DB_FILE" ] && [ -s "$DB_FILE" ]; then
  LATEST_DB=$(tail -1 "$DB_FILE")
  if echo "$LATEST_DB" | jq . >/dev/null 2>&1; then
    DB_SIZE=$(echo "$LATEST_DB" | jq -r '.db_size // "?"')
    DB_TABLES=$(echo "$LATEST_DB" | jq -r '.tables // 0')
    DB_EVENTS=$(echo "$LATEST_DB" | jq -r '.rows.events // 0')
    DB_USERS=$(echo "$LATEST_DB" | jq -r '.rows.users // 0')
    DB_SUMMARY="Size: $DB_SIZE | Tables: $DB_TABLES | Events: $DB_EVENTS | Users: $DB_USERS"
  fi
fi

# ── Write Digest ──────────────────────────────────────────────
cat > "$OUTPUT" << EOF
# Hermes Weekly Digest: $WEEK_START to $WEEK_END

**Compiled:** $NOW

## Development Velocity
- **Total commits:** $TOTAL_COMMITS ($DAILY_AVG/day avg)
- **Features:** $FEAT_COMMITS | **Fixes:** $FIX_COMMITS
- **Top domains:**
$TOP_DOMAINS

## Most Changed Files
\`\`\`
$MOST_CHANGED
\`\`\`

## App Health
- **Uptime:** ${UPTIME_PCT}% ($HEALTH_OK/$HEALTH_TOTAL checks OK)
- **Server down events:** $SERVER_DOWN
- **Route failures:** $HEALTH_FAIL

## Alerts This Week
- **Total:** $TOTAL_ALERTS (Critical: $CRITICAL_ALERTS, Error: $ERROR_ALERTS, Warn: $WARN_ALERTS)

## Database
$DB_SUMMARY

---
*Generated by Hermes Night Shift weekly digest.*
EOF

echo "[$(date)] Weekly digest written to $OUTPUT"

# Clear old alerts (archive then truncate)
if [ -f "$ALERT_FILE" ] && [ "$TOTAL_ALERTS" -gt 0 ]; then
  cp "$ALERT_FILE" "$HERMES_DIR/alerts-archive-${WEEK_END}.md"
  echo "# Alerts (cleared $WEEK_END after weekly digest)" > "$ALERT_FILE"
fi
