// Dashboard "This Week" Section - composite server component that groups
// schedule, saturation, pipeline, financial, calendar, client, and pricing widgets.
// Moved from page.tsx during decomposition.

import { Suspense } from 'react'
import { requireChef } from '@/lib/auth/get-user'
import { getCachedIsPrivileged } from '@/lib/chef/layout-data-cache'
import { getTenantDataPresence } from '@/lib/progressive-disclosure/tenant-data-presence'
import { isBrandNewChef } from '@/lib/progressive-disclosure/nav-visibility'
import { getWorkspaceDensity } from '@/lib/chef/preferences-actions'
import { WidgetErrorBoundary } from '@/components/ui/widget-error-boundary'
import { WidgetCardSkeleton } from '@/components/dashboard/widget-cards/widget-card-shell'
import { SectionShell } from '@/components/dashboard/section-shell'
import { CompletionSummaryWidgetServer } from '@/components/completion/completion-summary-server'
import { RecipeGapCard } from '@/components/dashboard/recipe-gap-card'
import { SeasonalCalendarWidget } from '@/components/dashboard/seasonal-calendar-widget'
import { MarginFeedbackCard } from '@/components/dashboard/margin-feedback-card'
import { ScheduleCards } from './schedule-cards'
import { LoadHeatmapCard } from './load-heatmap-card'
import { SaturationCards } from './saturation-cards'
import { PipelineSnapshot, PipelineSnapshotSkeleton } from './pipeline-snapshot'
import { FinancialPulse, FinancialPulseSkeleton } from './financial-pulse'
import { PulseSummary } from './pulse-summary'
import { ClientAttentionSection } from './client-attention-data'
import {
  AutoGeneratedDraftsSection,
  DormantClientsSection,
  ClientBirthdaysSection,
  QuickAvailabilitySection,
  QuickExpenseSection,
  PriorityQueueSection,
  ClientContributionDecisionsSection,
  TouchpointsSection,
} from './widget-sections'
import { PriceGlanceSection } from './pricing-sections'
import {
  ScheduleCardsSkeleton,
  SaturationCardsSkeleton,
  TouchpointsSkeleton,
  PriorityQueueSkeleton,
} from './section-skeletons'
import type { PriorityQueue } from '@/lib/queue/types'

async function safe<T>(label: string, fn: () => Promise<T>, fallback: T): Promise<T> {
  try {
    return await fn()
  } catch (err) {
    console.error(`[Dashboard/ThisWeek] ${label} failed:`, err)
    return fallback
  }
}

export interface ThisWeekSectionProps {
  queuePromise: Promise<PriorityQueue>
}

export async function ThisWeekSection({ queuePromise }: ThisWeekSectionProps) {
  const user = await requireChef()
  const [presence, userIsPrivileged, workspaceDensity] = await Promise.all([
    safe('presence', () => getTenantDataPresence(user.tenantId!), null),
    safe('privilegedAccess', () => getCachedIsPrivileged(user.id), false),
    safe('workspaceDensity', getWorkspaceDensity, 'standard' as const),
  ])

  const isMinimalDensity = workspaceDensity === 'minimal'
  const bypassProgressiveDisclosure = userIsPrivileged || process.env.DEMO_MODE_ENABLED === 'true'

  // Smart mode: whisper when chef has no events and no clients (empty week)
  const hasContent = !presence || presence.hasEvents || presence.hasClients
  const mode = hasContent ? ('expanded' as const) : ('whisper' as const)
  const whisperText = !hasContent ? 'This Week: clear schedule' : null

  return (
    <SectionShell sectionId="this-week" mode={mode} label="This Week" whisperText={whisperText}>
      <div className="space-y-4">
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">
          <WidgetErrorBoundary name="Schedule" compact>
            <Suspense fallback={<ScheduleCardsSkeleton />}>
              <ScheduleCards />
            </Suspense>
          </WidgetErrorBoundary>
          <WidgetErrorBoundary name="Auto-Generated Drafts" compact>
            <Suspense fallback={null}>
              <AutoGeneratedDraftsSection />
            </Suspense>
          </WidgetErrorBoundary>
          <Suspense fallback={null}>
            <WidgetErrorBoundary name="Weekly Load">
              <div className="col-span-full sm:col-span-2">
                <LoadHeatmapCard />
              </div>
            </WidgetErrorBoundary>
          </Suspense>
          <WidgetErrorBoundary name="Saturation" compact>
            <Suspense fallback={<SaturationCardsSkeleton />}>
              <SaturationCards />
            </Suspense>
          </WidgetErrorBoundary>
        </div>

        {/* Pipeline + Financial Pulse */}
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
          <WidgetErrorBoundary name="Pipeline Snapshot" compact>
            <Suspense fallback={<PipelineSnapshotSkeleton />}>
              <PipelineSnapshot />
            </Suspense>
          </WidgetErrorBoundary>
          <WidgetErrorBoundary name="Financial Pulse" compact>
            <Suspense fallback={<FinancialPulseSkeleton />}>
              <FinancialPulse />
            </Suspense>
          </WidgetErrorBoundary>
        </div>

        {/* Seasonal Calendar */}
        <WidgetErrorBoundary name="Seasonal Calendar" compact>
          <Suspense fallback={<WidgetCardSkeleton size="lg" />}>
            <SeasonalCalendarWidget />
          </Suspense>
        </WidgetErrorBoundary>

        {/* Client Pulse + Client details */}
        {!isMinimalDensity && (
          <>
            <WidgetErrorBoundary name="Client Pulse" compact>
              <Suspense fallback={null}>
                <PulseSummary />
              </Suspense>
            </WidgetErrorBoundary>

            <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">
              <WidgetErrorBoundary name="Dormant Clients" compact>
                <Suspense fallback={<WidgetCardSkeleton size="sm" />}>
                  <DormantClientsSection />
                </Suspense>
              </WidgetErrorBoundary>
              <WidgetErrorBoundary name="Client Milestones" compact>
                <Suspense fallback={<WidgetCardSkeleton size="sm" />}>
                  <ClientBirthdaysSection />
                </Suspense>
              </WidgetErrorBoundary>
              <WidgetErrorBoundary name="Availability Check" compact>
                <Suspense fallback={<WidgetCardSkeleton size="sm" />}>
                  <QuickAvailabilitySection />
                </Suspense>
              </WidgetErrorBoundary>
              <WidgetErrorBoundary name="Quick Expense" compact>
                <Suspense fallback={<WidgetCardSkeleton size="sm" />}>
                  <QuickExpenseSection />
                </Suspense>
              </WidgetErrorBoundary>
            </div>

            {/* Price Glance */}
            <WidgetErrorBoundary name="Price Glance" compact>
              <Suspense fallback={null}>
                <PriceGlanceSection />
              </Suspense>
            </WidgetErrorBoundary>

            {/* Priority Queue + Touchpoints */}
            <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">
              <WidgetErrorBoundary name="Contribution Decisions" compact>
                <Suspense fallback={<WidgetCardSkeleton size="sm" />}>
                  <ClientContributionDecisionsSection />
                </Suspense>
              </WidgetErrorBoundary>
              <WidgetErrorBoundary name="Priority Queue" compact>
                <Suspense fallback={<PriorityQueueSkeleton />}>
                  <PriorityQueueSection queuePromise={queuePromise} />
                </Suspense>
              </WidgetErrorBoundary>
              <WidgetErrorBoundary name="Upcoming Touchpoints" compact>
                <Suspense fallback={<TouchpointsSkeleton />}>
                  <TouchpointsSection />
                </Suspense>
              </WidgetErrorBoundary>
            </div>
          </>
        )}

        {/* Client Attention */}
        <WidgetErrorBoundary name="Client Attention" compact>
          <Suspense fallback={null}>
            <ClientAttentionSection />
          </Suspense>
        </WidgetErrorBoundary>

        {/* Event Readiness */}
        {!isMinimalDensity && (bypassProgressiveDisclosure || !presence || presence.hasEvents) && (
          <WidgetErrorBoundary name="Event Readiness" compact>
            <Suspense fallback={null}>
              <CompletionSummaryWidgetServer />
            </Suspense>
          </WidgetErrorBoundary>
        )}

        {/* Recipe Gaps */}
        {!isMinimalDensity && (bypassProgressiveDisclosure || !presence || presence.hasEvents) && (
          <WidgetErrorBoundary name="Recipe Gaps" compact>
            <Suspense fallback={null}>
              <RecipeGapCard />
            </Suspense>
          </WidgetErrorBoundary>
        )}
      </div>
    </SectionShell>
  )
}
