// Dashboard Widget Sections - small self-contained async server components
// for individual widgets (messages, quotes, payments, shopping, availability,
// expenses, hours, recipe capture, schedule, staff, revenue goal, etc.)
// Moved from page.tsx during decomposition.

import { QuickNotesSection } from '@/components/dashboard/quick-notes-section'
import { getQuickNotes } from '@/lib/quick-notes/actions'
import { UnreadHubMessagesWidget } from '@/components/dashboard/unread-hub-messages-widget'
import { ExpiringQuotesWidget } from '@/components/dashboard/expiring-quotes-widget'
import { OverduePaymentsWidget } from '@/components/dashboard/overdue-payments-widget'
import { DormantClientsWidget } from '@/components/dashboard/dormant-clients-widget'
import { ClientBirthdaysWidget } from '@/components/dashboard/client-birthdays-widget'
import { ShoppingWindowWidget } from '@/components/dashboard/shopping-window-widget'
import { QuickAvailabilityWidget } from '@/components/dashboard/quick-availability-widget'
import { QuickExpenseWidget } from '@/components/dashboard/quick-expense-widget'
import { HoursLogWidget } from '@/components/dashboard/hours-log-widget'
import { RecipeCaptureWidget } from '@/components/dashboard/recipe-capture-widget'
import { TodaysScheduleWidget } from '@/components/dashboard/todays-schedule-widget'
import { StaffTodayWidget } from '@/components/dashboard/staff-today-widget'
import { RevenueGoalWidget } from '@/components/dashboard/revenue-goal-widget'
import {
  getUnreadHubMessages,
  getExpiringQuotes,
  getUpcomingBirthdays,
  getShoppingWindowItems,
  getBookedDates,
  getRecentExpenses,
  getUpcomingEventsForExpense,
} from '@/lib/dashboard/widget-actions'
import { getOverdueDeposits } from '@/lib/finance/deposit-actions'
import { getDormantClients } from '@/lib/clients/dormancy'
import { getDashboardHoursSnapshot } from '@/lib/dashboard/actions'
import { getRecipeDebt } from '@/lib/recipes/actions'
import { getTodaysScheduleEnriched } from '@/lib/scheduling/actions'
import { getStaffToday } from '@/lib/staff/dashboard-actions'
import { getRevenueGoalSnapshot } from '@/lib/revenue-goals/actions'
import { AutoGeneratedDraftsCard } from '@/components/dashboard/auto-generated-drafts-card'
import { getUnacknowledgedAutoGeneratedEvents } from '@/lib/scheduling/recurring-actions'
import UpcomingTouchpoints from '@/components/clients/upcoming-touchpoints'
import { getUpcomingTouchpoints } from '@/lib/clients/touchpoint-actions'
import { ListCard, type ListCardItem } from '@/components/dashboard/widget-cards/list-card'
import type { PriorityQueue } from '@/lib/queue/types'
import { DashboardPriorityActions } from '@/components/dashboard/dashboard-priority-actions'
import { ResolveNextCard } from '@/components/dashboard/resolve-next-card'
import { DecisionQueueWidget } from '@/components/dashboard/decision-queue-widget'
import { resolveDashboardNextTask } from '@/lib/dashboard/view-types'
import type { DecisionQueueResult } from '@/lib/decision-queue/actions'
import type { getOnboardingProgress } from '@/lib/onboarding/progress-actions'
import { ChefTipsWidget } from '@/components/dashboard/cheftips-widget'
import {
  getTodaysTips,
  getCachedTipStats,
  getRandomPastTip,
} from '@/lib/chef/knowledge/tip-actions'
import { getReviewQueueCount } from '@/lib/knowledge/review-actions'
import { requireChef } from '@/lib/auth/get-user'
import { getClientContributionPortfolio } from '@/lib/client-contribution/actions'
import { buildContributionOpportunityPlan } from '@/lib/client-contribution/strategy'
import { HealthDashboardWidget } from '@/components/intelligence/health-dashboard-widget'
import { fetchBusinessHealthSummaryOnly } from '@/lib/intelligence/business-health-actions'
import { getPortfolioLTVSummary } from '@/lib/analytics/client-ltv-actions'
import { getHealthScoreDistribution } from '@/lib/clients/health-score'
import { formatCurrency } from '@/lib/utils/currency'

async function safe<T>(label: string, fn: () => Promise<T>, fallback: T): Promise<T> {
  try {
    return await fn()
  } catch (err) {
    console.error(`[Dashboard/Widgets] ${label} failed:`, err)
    return fallback
  }
}

const UNRESOLVED_TEMPLATE_TOKEN = /\{[a-zA-Z0-9_]+\}/

function hasUnresolvedTemplateText(value: string | null | undefined): boolean {
  return typeof value === 'string' && UNRESOLVED_TEMPLATE_TOKEN.test(value)
}

export async function QuickNotesLoader() {
  const notes = await safe('quickNotes', () => getQuickNotes({ limit: 20 }), [])
  return <QuickNotesSection initialNotes={notes} />
}

export async function UnreadMessagesSection() {
  const groups = await safe('unreadHub', getUnreadHubMessages, [])
  if (groups.length === 0) return null
  return <UnreadHubMessagesWidget groups={groups} />
}

export async function ExpiringQuotesSection() {
  const quotes = await safe('expiringQuotes', getExpiringQuotes, [])
  if (quotes.length === 0) return null
  return <ExpiringQuotesWidget quotes={quotes} />
}

export async function OverduePaymentsSection() {
  const overdueEvents = await safe('overdueDeposits', getOverdueDeposits, [])
  if (overdueEvents.length === 0) return null
  return <OverduePaymentsWidget overdueEvents={overdueEvents} />
}

export async function DormantClientsSection() {
  const clients = await safe('dormantClients', getDormantClients, [])
  if (clients.length === 0) return null
  return <DormantClientsWidget clients={clients} />
}

export async function ClientBirthdaysSection() {
  const birthdays = await safe('birthdays', getUpcomingBirthdays, [])
  if (birthdays.length === 0) return null
  return <ClientBirthdaysWidget birthdays={birthdays} />
}

export async function ShoppingWindowSection() {
  const items = await safe('shoppingWindow', getShoppingWindowItems, [])
  if (items.length === 0) return null
  return <ShoppingWindowWidget items={items} />
}

export async function QuickAvailabilitySection() {
  const dates = await safe('bookedDates', getBookedDates, { booked: [], tentative: [] })
  return <QuickAvailabilityWidget bookedDates={dates.booked} tentativeDates={dates.tentative} />
}

export async function QuickExpenseSection() {
  const [upcomingEvents, recentExpenses] = await Promise.all([
    safe('expenseEvents', getUpcomingEventsForExpense, []),
    safe('recentExpenses', getRecentExpenses, []),
  ])
  return <QuickExpenseWidget upcomingEvents={upcomingEvents} recentExpenses={recentExpenses} />
}

export async function HoursLogSection() {
  const snapshot = await safe('hoursSnapshot', getDashboardHoursSnapshot, null)
  if (!snapshot) return null
  return (
    <HoursLogWidget
      todayMinutes={snapshot.todayMinutes}
      weekMinutes={snapshot.weekMinutes}
      allTimeMinutes={snapshot.allTimeMinutes}
      topActivity={snapshot.topActivity}
      recentEntries={snapshot.recentEntries}
      trackingStreak={snapshot.trackingStreak}
      todayLogged={snapshot.todayLogged}
      weekCategoryBreakdown={snapshot.weekCategoryBreakdown}
    />
  )
}

export async function RecipeCaptureSection() {
  const debt = await safe('recipeDebt', getRecipeDebt, {
    total: 0,
    last7Days: 0,
    last30Days: 0,
    older: 0,
    totalRecipes: 0,
  })
  return <RecipeCaptureWidget recipeDebt={debt.total} />
}

export async function TodaysScheduleSection() {
  const schedule = await safe('todaysScheduleEnriched', () => getTodaysScheduleEnriched(), null)
  if (!schedule) return null
  return <TodaysScheduleWidget schedule={schedule} />
}

export async function StaffTodaySection() {
  const data = await safe('staffToday', getStaffToday, null)
  if (!data) return null
  return <StaffTodayWidget data={data} />
}

export async function RevenueGoalSection() {
  const snapshot = await safe('revenueGoalSnapshot', getRevenueGoalSnapshot, null)
  if (!snapshot || !snapshot.enabled) return null
  return <RevenueGoalWidget snapshot={snapshot} />
}

export async function AutoGeneratedDraftsSection() {
  const drafts = await getUnacknowledgedAutoGeneratedEvents().catch(() => [])
  if (drafts.length === 0) return null
  return (
    <div className="col-span-full">
      <AutoGeneratedDraftsCard drafts={drafts} />
    </div>
  )
}

export async function TouchpointsSection() {
  const touchpoints = await safe('touchpoints', getUpcomingTouchpoints, [])
  if (touchpoints.length === 0) return null
  return (
    <div className="col-span-1 sm:col-span-2">
      <UpcomingTouchpoints initialTouchpoints={touchpoints} />
    </div>
  )
}

export async function PriorityQueueSection({
  queuePromise,
}: {
  queuePromise: Promise<PriorityQueue>
}) {
  const queue = await queuePromise
  const remainingItems = queue.items.slice(1, 6)

  if (queue.summary.totalItems <= 1 || remainingItems.length === 0) return null

  const queueItems: ListCardItem[] = remainingItems.map((item) => ({
    id: item.id,
    label: item.title,
    sublabel:
      item.context.primaryLabel +
      (item.context.secondaryLabel ? ` - ${item.context.secondaryLabel}` : ''),
    href: item.href,
    status:
      item.urgency === 'critical'
        ? ('red' as const)
        : item.urgency === 'high'
          ? ('amber' as const)
          : item.urgency === 'normal'
            ? ('brand' as const)
            : ('stone' as const),
  }))

  return (
    <ListCard
      widgetId="priority_queue"
      title="After This"
      count={queue.summary.totalItems - 1}
      items={queueItems}
      href="/queue"
      emptyMessage="Nothing else queued."
    />
  )
}

export async function ClientContributionDecisionsSection() {
  const portfolio = await safe('clientContributionPortfolio', getClientContributionPortfolio, null)
  if (!portfolio) return null

  const opportunities = buildContributionOpportunityPlan(portfolio, { limit: 4 })
  if (opportunities.length === 0) return null

  const items: ListCardItem[] = opportunities.map((item) => ({
    id: item.id,
    label: `${item.actionLabel}: ${item.clientName}`,
    sublabel: `${item.window}-day plan - ${item.reason}`,
    href: item.href,
    status: item.urgency === 'high' ? ('amber' as const) : ('brand' as const),
  }))

  return (
    <ListCard
      widgetId="client_contribution_decisions"
      title="Contribution Decisions"
      count={opportunities.length}
      items={items}
      href="/clients/contribution"
      emptyMessage="No contribution decisions need attention."
    />
  )
}

export async function PriorityActionsSection({
  queuePromise,
}: {
  queuePromise: Promise<PriorityQueue>
}) {
  const queue = await queuePromise
  return <DashboardPriorityActions queue={queue} />
}

export async function ResolveNextSection({
  queuePromise,
  onboardingProgress,
  profileGated,
}: {
  queuePromise: Promise<PriorityQueue>
  onboardingProgress: Awaited<ReturnType<typeof getOnboardingProgress>> | null
  profileGated: boolean
}) {
  const queue = await queuePromise
  const task = resolveDashboardNextTask({
    priorityQueue: queue,
    onboardingProgress,
    profileGated,
  })

  return <ResolveNextCard task={task} />
}

export async function DecisionQueueSection({
  decisionQueuePromise,
}: {
  decisionQueuePromise: Promise<DecisionQueueResult>
}) {
  const decisionQueueData = await decisionQueuePromise
  return <DecisionQueueWidget data={decisionQueueData} />
}

export async function ChefTipsSection() {
  const user = await requireChef()
  const [todaysTips, stats, pastTip, reviewCount] = await Promise.all([
    getTodaysTips(),
    getCachedTipStats(user.entityId),
    getRandomPastTip(),
    getReviewQueueCount(),
  ])

  return (
    <ChefTipsWidget
      todaysTips={todaysTips}
      totalCount={stats.total}
      streak={stats.streak}
      pastTip={pastTip}
      reviewCount={reviewCount}
    />
  )
}

export async function BusinessHealthSection() {
  const healthSummary = await safe('healthSummary', fetchBusinessHealthSummaryOnly, null)
  if (!healthSummary) return null

  const score = healthSummary.scores.overall
  const recentScore = healthSummary.scores.revenue
  const trend: 'improving' | 'stable' | 'declining' =
    score >= 60 && recentScore >= 60 ? 'improving' : score < 40 ? 'declining' : 'stable'

  return <HealthDashboardWidget score={score} trend={trend} />
}

export async function PortfolioSummarySection() {
  const [portfolio, healthDist] = await Promise.all([
    safe('portfolioLTV', getPortfolioLTVSummary, null),
    safe('healthDist', getHealthScoreDistribution, null),
  ])
  if (!portfolio || portfolio.clientCount === 0) return null

  const stats: { label: string; value: string }[] = [
    { label: 'Portfolio Value', value: formatCurrency(portfolio.totalPortfolioValueCents) },
    { label: 'Clients', value: String(portfolio.clientCount) },
  ]
  if (healthDist && healthDist.totalClients > 0) {
    stats.push({ label: 'Healthy', value: `${healthDist.percentHealthy}%` })
  }
  if (portfolio.atRiskRevenueCents > 0) {
    stats.push({ label: 'At-Risk Revenue', value: formatCurrency(portfolio.atRiskRevenueCents) })
  }

  return (
    <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
      {stats.map((s) => (
        <div key={s.label} className="rounded-xl border border-stone-800 bg-stone-900/50 p-4">
          <div className="text-xs text-stone-500 uppercase tracking-wide">{s.label}</div>
          <div className="mt-1 text-lg font-semibold text-stone-100">{s.value}</div>
        </div>
      ))}
    </div>
  )
}

export async function TieredRailSection({
  queuePromise,
}: {
  queuePromise: Promise<PriorityQueue>
}) {
  const user = await requireChef()
  const { TieredRail } = await import('@/components/rail/tiered-rail')
  const { assembleRailForPage } = await import('@/lib/discovery/universal-rail-assembly')
  let universalItems: import('@/lib/discovery/universal-rail-types').UniversalRailItem[] = []
  try {
    const universalResult = await assembleRailForPage(
      'chef',
      'dashboard',
      user.id,
      user.tenantId ?? undefined
    )
    universalItems = universalResult.items.filter(
      (item) =>
        !hasUnresolvedTemplateText(item.label) &&
        !hasUnresolvedTemplateText(item.sublabel) &&
        !hasUnresolvedTemplateText(item.href)
    )
  } catch {
    // Universal rail data is non-critical; proceed without it
  }
  try {
    const { injectRailLifecycleItems } = await import('@/lib/discovery/rail-lifecycle-bridge')
    universalItems = await injectRailLifecycleItems(
      universalItems,
      'chef',
      user.id,
      user.tenantId ?? undefined
    )
    universalItems = universalItems.filter(
      (item) =>
        !hasUnresolvedTemplateText(item.label) &&
        !hasUnresolvedTemplateText(item.sublabel) &&
        !hasUnresolvedTemplateText(item.href)
    )
  } catch {
    // Lifecycle bridge is non-critical
  }
  return <TieredRail queuePromise={queuePromise} universalItems={universalItems} />
}
