-- Migration: Add portal access token to clients table
-- Enables magic-link / token-based client portal access without requiring a client account.
-- Additive only.

ALTER TABLE clients
  ADD COLUMN IF NOT EXISTS portal_access_token TEXT UNIQUE,
  ADD COLUMN IF NOT EXISTS portal_token_created_at TIMESTAMPTZ;

-- Index for fast token lookups
CREATE INDEX IF NOT EXISTS idx_clients_portal_access_token
  ON clients (portal_access_token)
  WHERE portal_access_token IS NOT NULL;

COMMENT ON COLUMN clients.portal_access_token IS
  'Opaque token used for magic-link client portal access. Generated by the chef and shared with the client.';
COMMENT ON COLUMN clients.portal_token_created_at IS
  'Timestamp when the portal token was last generated/rotated.';
