// Inquiry Response Composer
// AI-powered draft generation + chef review + Gmail send
// This component handles the full correspondence workflow for an inquiry.

'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Alert } from '@/components/ui/alert'
import { draftResponseForInquiry } from '@/lib/ai/correspondence'
import {
  createDraftMessage,
  approveAndSendMessage,
  updateDraftMessage,
  deleteDraftMessage,
} from '@/lib/gmail/actions'
import { getDinnerCircleInvitation } from '@/lib/lifecycle/dinner-circle-templates'
import type { EmailSnapshotResult } from '@/lib/lifecycle/email-snapshot'
import { buildPresetA, buildPresetB } from '@/lib/inquiries/soft-close-message-presets'

interface InquiryResponseComposerProps {
  inquiryId: string
  clientId: string | null
  clientEmail: string | null
  gmailConnected: boolean
  circleToken?: string | null
  chefName?: string | null
  /** Contact name used for soft-close preset subject/greeting */
  contactName?: string | null
  isFirstResponse?: boolean
  snapshotData?: EmailSnapshotResult | null
  /** When true: defaults to A mode (no circle link, no snapshot), shows A/B preset loaders */
  softCloseMode?: boolean
  /** Pre-generated draft from the reactive pipeline - shown immediately on load */
  pendingDraft?: { id: string; subject: string; body: string } | null
}

interface DraftState {
  draft: string
  subject: string
  flags: string[]
  lifecycleState: string
  emailStage: string
  missingBlocking: string[]
  pricingAllowed: boolean
  confidence: string
  conversationDepth: number
}

export function InquiryResponseComposer({
  inquiryId,
  clientId,
  clientEmail,
  gmailConnected,
  circleToken,
  chefName,
  contactName,
  isFirstResponse,
  snapshotData,
  softCloseMode = false,
  pendingDraft = null,
}: InquiryResponseComposerProps) {
  const router = useRouter()
  const [generating, setGenerating] = useState(false)
  const [sending, setSending] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [success, setSuccess] = useState<string | null>(null)
  // If a pre-generated draft exists, show it immediately
  const [draftState, setDraftState] = useState<DraftState | null>(
    pendingDraft
      ? {
          draft: pendingDraft.body,
          subject: pendingDraft.subject,
          flags: [],
          lifecycleState: 'inquiry',
          emailStage: 'first_response',
          missingBlocking: [],
          pricingAllowed: false,
          confidence: 'high',
          conversationDepth: 0,
        }
      : null
  )
  const [editedBody, setEditedBody] = useState(pendingDraft?.body ?? '')
  const [editedSubject, setEditedSubject] = useState(pendingDraft?.subject ?? '')
  const [isEditing, setIsEditing] = useState(false)
  const [savedMessageId, setSavedMessageId] = useState<string | null>(pendingDraft?.id ?? null)
  // Tracks whether the visible draft is the auto-generated one (shows badge). Goes false on Regenerate/Discard.
  const [isAutoGenerated, setIsAutoGenerated] = useState(!!pendingDraft)
  // Soft-close mode: default A (no circle, no snapshot). Normal mode: default B when token exists.
  const [includeCircleLink, setIncludeCircleLink] = useState(softCloseMode ? false : !!circleToken)
  const [includeSnapshot, setIncludeSnapshot] = useState(softCloseMode ? false : !!snapshotData)

  // ── Generate AI Draft ──────────────────────────────────────────────────────

  const handleGenerateDraft = async () => {
    setGenerating(true)
    setError(null)
    setSuccess(null)
    setDraftState(null)
    setSavedMessageId(null)
    setIsAutoGenerated(false)

    try {
      const result = await draftResponseForInquiry(inquiryId)

      // Parse subject from draft (format: "Subject: ...\n\n...")
      let subject = ''
      let body = result.draft
      const subjectMatch = result.draft.match(/^Subject:\s*(.+?)(?:\n\n|\r\n\r\n)/)
      if (subjectMatch) {
        subject = subjectMatch[1].trim()
        body = result.draft.slice(subjectMatch[0].length).trim()
      }

      // Auto-append based on Version A/B strategy
      let finalBody = body
      const circleUrl = circleToken ? `https://app.cheflowhq.com/hub/g/${circleToken}` : null

      if (includeCircleLink && circleUrl && includeSnapshot && snapshotData?.formatted) {
        // Version B: snapshot with circle link woven in, menu teased
        const invitation = getDinnerCircleInvitation({
          chefName: chefName || 'Your chef',
          circleUrl,
        })
        finalBody = body + '\n\n' + invitation.paragraph + '\n\n' + snapshotData.formatted
        // Append "View full details" link at the end of the snapshot
        finalBody = finalBody + '\n\nView full details: ' + circleUrl
      } else if (includeCircleLink && circleUrl) {
        // Circle link without snapshot
        const invitation = getDinnerCircleInvitation({
          chefName: chefName || 'Your chef',
          circleUrl,
        })
        finalBody = body + '\n\n' + invitation.paragraph
      } else if (includeSnapshot && snapshotData?.formatted) {
        // Version A: full snapshot inlined, no portal link
        finalBody = finalBody + '\n\n' + snapshotData.formatted
      }

      setDraftState({
        draft: finalBody,
        subject,
        flags: result.flags,
        lifecycleState: result.lifecycleState,
        emailStage: result.emailStage,
        missingBlocking: result.missingBlocking,
        pricingAllowed: result.pricingAllowed,
        confidence: result.confidence,
        conversationDepth: result.conversationDepth,
      })
      setEditedBody(finalBody)
      setEditedSubject(subject)
    } catch (err) {
      const e = err as Error
      setError(e.message)
    } finally {
      setGenerating(false)
    }
  }

  // ── Approve and Send ───────────────────────────────────────────────────────

  const handleSend = async () => {
    if (!clientId || !clientEmail) {
      setError('Cannot send: client has no email address')
      return
    }

    setSending(true)
    setError(null)
    setSuccess(null)

    try {
      // Create the message record as a draft first
      let messageId = savedMessageId
      if (!messageId) {
        const created = await createDraftMessage({
          inquiryId,
          clientId,
          subject: editedSubject || 'Your dinner inquiry',
          body: editedBody,
        })
        messageId = created.messageId
        setSavedMessageId(messageId)
      } else {
        // Update existing draft with any edits
        await updateDraftMessage(messageId, {
          subject: editedSubject,
          body: editedBody,
        })
      }

      // Approve and send via Gmail
      const result = await approveAndSendMessage(messageId)

      if (result.success) {
        setSuccess('Message sent successfully via Gmail')
        setDraftState(null)
        setSavedMessageId(null)
        router.refresh()
      }
    } catch (err) {
      const e = err as Error
      setError(e.message)
    } finally {
      setSending(false)
    }
  }

  // ── Discard Draft ──────────────────────────────────────────────────────────

  const handleDiscard = () => {
    // Update UI immediately so the button feels instant
    const idToDelete = savedMessageId
    setDraftState(null)
    setEditedBody('')
    setEditedSubject('')
    setSavedMessageId(null)
    setIsAutoGenerated(false)
    setError(null)
    setSuccess(null)
    // Delete the DB record in the background (non-blocking)
    if (idToDelete) {
      deleteDraftMessage(idToDelete).catch(() => {})
    }
  }

  // ── No Gmail / No Client Guards ────────────────────────────────────────────

  if (!gmailConnected) {
    return (
      <Card className="p-6">
        <h2 className="text-xl font-semibold mb-3">Response Draft</h2>
        <p className="text-sm text-stone-500">
          Connect your Gmail account in Settings to enable response drafting and sending.
        </p>
      </Card>
    )
  }

  if (!clientId || !clientEmail) {
    return (
      <Card className="p-6">
        <h2 className="text-xl font-semibold mb-3">Response Draft</h2>
        <p className="text-sm text-stone-500">
          This inquiry needs a linked client with an email address before you can send responses.
        </p>
        <Button
          variant="secondary"
          size="sm"
          className="mt-3"
          onClick={handleGenerateDraft}
          loading={generating}
        >
          Generate Draft (preview only)
        </Button>
        {draftState && (
          <div className="mt-4 bg-stone-800 rounded-lg p-4">
            <p className="text-xs text-stone-500 mb-2">
              Preview only - cannot send without client email
            </p>
            <p className="text-sm whitespace-pre-wrap">{draftState.draft}</p>
          </div>
        )}
      </Card>
    )
  }

  const circleUrl = circleToken ? `https://app.cheflowhq.com/hub/g/${circleToken}` : null

  const handleLoadPresetA = () => {
    const name = contactName ?? ''
    const chef = chefName ?? 'Your chef'
    const preset = buildPresetA(name, chef)
    setDraftState({
      draft: preset.body,
      subject: preset.subject,
      flags: [],
      lifecycleState: 'soft_close',
      emailStage: 'courtesy_closeout',
      missingBlocking: [],
      pricingAllowed: false,
      confidence: 'high',
      conversationDepth: 0,
    })
    setEditedBody(preset.body)
    setEditedSubject(preset.subject)
    setIncludeCircleLink(false)
    setIncludeSnapshot(false)
    setSavedMessageId(null)
    setError(null)
  }

  const handleLoadPresetB = () => {
    if (!circleUrl) return
    const name = contactName ?? ''
    const chef = chefName ?? 'Your chef'
    const preset = buildPresetB(name, chef, circleUrl)
    setDraftState({
      draft: preset.body,
      subject: preset.subject,
      flags: [],
      lifecycleState: 'soft_close',
      emailStage: 'courtesy_closeout',
      missingBlocking: [],
      pricingAllowed: false,
      confidence: 'high',
      conversationDepth: 0,
    })
    setEditedBody(preset.body)
    setEditedSubject(preset.subject)
    setIncludeCircleLink(true)
    setIncludeSnapshot(false)
    setSavedMessageId(null)
    setError(null)
  }

  return (
    <Card className="p-6">
      <div className="flex justify-between items-center mb-4">
        <div className="flex items-center gap-2">
          <h2 className="text-xl font-semibold">
            {softCloseMode ? 'Courtesy Closeout (optional)' : 'Response Draft'}
          </h2>
          {isAutoGenerated && draftState && (
            <span className="inline-flex items-center gap-1 rounded-full bg-emerald-900/50 border border-emerald-700/50 px-2 py-0.5 text-xs font-medium text-emerald-400">
              <span className="h-1.5 w-1.5 rounded-full bg-emerald-400" />
              Draft ready
            </span>
          )}
        </div>
        {!draftState && (
          <div className="flex items-center gap-2">
            {softCloseMode && (
              <>
                <Button variant="ghost" size="sm" onClick={handleLoadPresetA}>
                  Load A closeout
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleLoadPresetB}
                  disabled={!circleUrl}
                  title={!circleUrl ? 'No Dinner Circle token for this inquiry' : undefined}
                >
                  Load B closeout
                </Button>
              </>
            )}
            <Button variant="primary" size="sm" onClick={handleGenerateDraft} loading={generating}>
              {generating ? 'Generating...' : 'Generate Draft'}
            </Button>
          </div>
        )}
      </div>

      {error && (
        <Alert variant="error" className="mb-4">
          {error}
        </Alert>
      )}
      {success && (
        <Alert variant="success" className="mb-4">
          {success}
        </Alert>
      )}

      {draftState && (
        <div className="space-y-4">
          {/* Lifecycle Context */}
          <div className="flex flex-wrap gap-2">
            <Badge variant="default">{draftState.lifecycleState.replace(/_/g, ' ')}</Badge>
            <Badge variant="default">{draftState.emailStage} stage</Badge>
            <Badge
              variant={
                draftState.confidence === 'high'
                  ? 'success'
                  : draftState.confidence === 'medium'
                    ? 'warning'
                    : 'error'
              }
            >
              {draftState.confidence} confidence
            </Badge>
            {draftState.pricingAllowed && <Badge variant="success">pricing allowed</Badge>}
          </div>

          {/* Flags */}
          {draftState.flags.length > 0 && (
            <Alert variant="warning">
              <div className="text-sm">
                <p className="font-medium">Review flags:</p>
                <ul className="list-disc list-inside mt-1">
                  {draftState.flags.map((flag, i) => (
                    <li key={i}>{flag}</li>
                  ))}
                </ul>
              </div>
            </Alert>
          )}

          {/* Missing Data */}
          {draftState.missingBlocking.length > 0 && (
            <div className="bg-amber-950 border border-amber-200 rounded-lg p-3">
              <p className="text-xs font-medium text-amber-800">Missing blocking data:</p>
              <div className="flex gap-1.5 mt-1 flex-wrap">
                {draftState.missingBlocking.map((field) => (
                  <Badge key={field} variant="warning">
                    {field}
                  </Badge>
                ))}
              </div>
            </div>
          )}

          {/* Subject Line */}
          <div>
            <label className="text-xs font-medium text-stone-500 block mb-1">Subject</label>
            {isEditing ? (
              <input
                type="text"
                value={editedSubject}
                onChange={(e) => setEditedSubject(e.target.value)}
                aria-label="Email subject"
                className="w-full border border-stone-600 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-brand-500 focus:border-brand-500 outline-none"
              />
            ) : (
              <p className="text-sm text-stone-100 bg-stone-800 rounded-lg px-3 py-2">
                {editedSubject || '(no subject)'}
              </p>
            )}
          </div>

          {/* Draft Body */}
          <div>
            <label className="text-xs font-medium text-stone-500 block mb-1">
              Message to {clientEmail}
            </label>
            {isEditing ? (
              <textarea
                value={editedBody}
                onChange={(e) => setEditedBody(e.target.value)}
                rows={12}
                aria-label="Email body"
                className="w-full border border-stone-600 rounded-lg px-3 py-2 text-sm font-mono focus:ring-2 focus:ring-brand-500 focus:border-brand-500 outline-none resize-y"
              />
            ) : (
              <div className="bg-stone-800 rounded-lg p-4 text-sm whitespace-pre-wrap">
                {editedBody}
              </div>
            )}
          </div>

          {/* Email options */}
          <div className="flex flex-wrap gap-4">
            {/* Dinner Circle toggle */}
            {circleToken && (
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={includeCircleLink}
                  onChange={(e) => setIncludeCircleLink(e.target.checked)}
                  className="h-4 w-4 rounded border-stone-600 bg-stone-800 text-[#e88f47] focus:ring-[#e88f47]"
                />
                <span className="text-xs text-stone-400">Include Dinner Circle link</span>
              </label>
            )}

            {/* Snapshot footer toggle */}
            {snapshotData && (
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={includeSnapshot}
                  onChange={(e) => setIncludeSnapshot(e.target.checked)}
                  className="h-4 w-4 rounded border-stone-600 bg-stone-800 text-[#e88f47] focus:ring-[#e88f47]"
                />
                <span className="text-xs text-stone-400">Include dinner summary</span>
              </label>
            )}
          </div>

          {/* Action Buttons */}
          <div className="flex gap-2 pt-2">
            {isEditing ? (
              <Button variant="secondary" size="sm" onClick={() => setIsEditing(false)}>
                Done Editing
              </Button>
            ) : (
              <Button variant="secondary" size="sm" onClick={() => setIsEditing(true)}>
                Edit
              </Button>
            )}
            <Button
              variant="primary"
              size="sm"
              onClick={handleSend}
              loading={sending}
              disabled={!editedBody.trim()}
            >
              {sending ? 'Sending...' : 'Approve & Send'}
            </Button>
            <Button
              variant="secondary"
              size="sm"
              onClick={handleGenerateDraft}
              loading={generating}
            >
              Regenerate
            </Button>
            <Button variant="ghost" size="sm" onClick={handleDiscard}>
              Discard
            </Button>
          </div>
        </div>
      )}

      {/* Empty State */}
      {!draftState && !generating && !success && (
        <p className="text-sm text-stone-500">
          Generate a contextual response draft based on lifecycle state, client history, and brand
          voice.
        </p>
      )}
    </Card>
  )
}
