import { DEFAULT_GRAZING_COMPONENT_MIX } from './scaling-engine'
import type { GrazingComponent, GrazingTemplate } from './types'

export const DEFAULT_GRAZING_TEMPLATES: GrazingTemplate[] = [
  {
    id: 'seed-small-classic-cheese-board',
    name: 'Small Classic Cheese Board',
    format: 'small_board',
    serviceStyle: 'standard_grazing',
    aestheticTags: ['classic', 'neutral', 'wine-friendly'],
    defaultDensity: 'standard',
    layoutZones: [],
    componentMix: { ...DEFAULT_GRAZING_COMPONENT_MIX },
    active: true,
  },
  {
    id: 'seed-seasonal-brunch-board',
    name: 'Seasonal Brunch Board',
    format: 'mid_spread',
    serviceStyle: 'light_snack',
    aestheticTags: ['brunch', 'seasonal', 'bright'],
    defaultDensity: 'standard',
    layoutZones: [],
    componentMix: {
      cheese: 0.2,
      charcuterie: 0.12,
      fruit: 0.28,
      crackers_bread: 0.2,
      nuts: 0.05,
      dips_spreads: 0.1,
      garnish: 0.05,
    },
    active: true,
  },
  {
    id: 'seed-mid-size-cocktail-spread',
    name: 'Mid-Size Cocktail Spread',
    format: 'mid_spread',
    serviceStyle: 'standard_grazing',
    aestheticTags: ['cocktail', 'polished', 'savory'],
    defaultDensity: 'standard',
    layoutZones: [],
    componentMix: {
      cheese: 0.28,
      charcuterie: 0.24,
      fruit: 0.14,
      crackers_bread: 0.16,
      nuts: 0.06,
      dips_spreads: 0.07,
      garnish: 0.05,
    },
    active: true,
  },
  {
    id: 'seed-abundant-celebration-table',
    name: 'Abundant Celebration Table',
    format: 'large_table',
    serviceStyle: 'heavy_grazing',
    aestheticTags: ['abundant', 'celebration', 'layered'],
    defaultDensity: 'abundant',
    layoutZones: [],
    componentMix: {
      cheese: 0.27,
      charcuterie: 0.22,
      fruit: 0.18,
      crackers_bread: 0.15,
      nuts: 0.06,
      dips_spreads: 0.07,
      garnish: 0.05,
    },
    active: true,
  },
  {
    id: 'seed-large-grazing-table',
    name: 'Large Grazing Table',
    format: 'large_table',
    serviceStyle: 'standard_grazing',
    aestheticTags: ['large-format', 'flowing', 'event-ready'],
    defaultDensity: 'standard',
    layoutZones: [],
    componentMix: { ...DEFAULT_GRAZING_COMPONENT_MIX },
    active: true,
  },
]

export const DEFAULT_GRAZING_COMPONENTS: GrazingComponent[] = [
  {
    id: 'seed-aged-cheddar',
    name: 'Aged cheddar',
    category: 'cheese',
    aestheticTags: ['classic'],
    seasonTags: ['all-season'],
    dietaryTags: ['vegetarian'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 85,
    clientDescription: 'A familiar sharp cheese anchor.',
    prepNotes: 'Cut into varied blocks and batons.',
    storageNotes: 'Keep chilled and covered until setup.',
    active: true,
  },
  {
    id: 'seed-triple-cream-brie',
    name: 'Triple cream brie',
    category: 'cheese',
    aestheticTags: ['soft', 'classic'],
    seasonTags: ['all-season'],
    dietaryTags: ['vegetarian'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 115,
    clientDescription: 'Creamy soft cheese for spreading.',
    prepNotes: 'Serve as wedges or petite wheels.',
    storageNotes: 'Temper shortly before service.',
    active: true,
  },
  {
    id: 'seed-goat-cheese-log',
    name: 'Herbed goat cheese',
    category: 'cheese',
    aestheticTags: ['fresh', 'herbal'],
    seasonTags: ['spring', 'summer'],
    dietaryTags: ['vegetarian'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 100,
    clientDescription: 'Tangy fresh cheese with herbs.',
    prepNotes: 'Slice cold; garnish with oil and herbs.',
    storageNotes: 'Keep chilled.',
    active: true,
  },
  {
    id: 'seed-manchego',
    name: 'Manchego',
    category: 'cheese',
    aestheticTags: ['spanish', 'firm'],
    seasonTags: ['all-season'],
    dietaryTags: ['vegetarian'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 125,
    clientDescription: 'Firm sheep milk cheese with nutty depth.',
    prepNotes: 'Cut into triangles.',
    storageNotes: 'Keep wrapped and chilled.',
    active: true,
  },
  {
    id: 'seed-blue-cheese',
    name: 'Blue cheese',
    category: 'cheese',
    aestheticTags: ['bold'],
    seasonTags: ['fall', 'winter'],
    dietaryTags: ['vegetarian'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 130,
    clientDescription: 'Bold accent cheese.',
    prepNotes: 'Use smaller pieces to control intensity.',
    storageNotes: 'Wrap separately.',
    active: true,
  },
  {
    id: 'seed-havarti',
    name: 'Dill havarti',
    category: 'cheese',
    aestheticTags: ['mild', 'herbal'],
    seasonTags: ['all-season'],
    dietaryTags: ['vegetarian'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 90,
    clientDescription: 'Mild cheese with fresh dill notes.',
    prepNotes: 'Cube or baton cut.',
    storageNotes: 'Keep chilled.',
    active: true,
  },
  {
    id: 'seed-smoked-gouda',
    name: 'Smoked gouda',
    category: 'cheese',
    aestheticTags: ['smoky'],
    seasonTags: ['all-season'],
    dietaryTags: ['vegetarian'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 95,
    clientDescription: 'Smoky semi-firm cheese.',
    prepNotes: 'Slice thinly for easy pickup.',
    storageNotes: 'Keep wrapped.',
    active: true,
  },
  {
    id: 'seed-fresh-mozzarella',
    name: 'Fresh mozzarella pearls',
    category: 'cheese',
    aestheticTags: ['fresh', 'bright'],
    seasonTags: ['spring', 'summer'],
    dietaryTags: ['vegetarian'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 80,
    clientDescription: 'Fresh mozzarella accent.',
    prepNotes: 'Drain well before setting.',
    storageNotes: 'Keep in brine until prep.',
    active: true,
  },
  {
    id: 'seed-prosciutto',
    name: 'Prosciutto',
    category: 'charcuterie',
    aestheticTags: ['classic', 'delicate'],
    seasonTags: ['all-season'],
    dietaryTags: [],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 180,
    clientDescription: 'Thin sliced cured ham.',
    prepNotes: 'Fold into loose ribbons.',
    storageNotes: 'Keep chilled.',
    active: true,
  },
  {
    id: 'seed-soppressata',
    name: 'Soppressata',
    category: 'charcuterie',
    aestheticTags: ['savory'],
    seasonTags: ['all-season'],
    dietaryTags: [],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 150,
    clientDescription: 'Savory salami with gentle spice.',
    prepNotes: 'Fan slices near firm cheeses.',
    storageNotes: 'Keep chilled.',
    active: true,
  },
  {
    id: 'seed-genoa-salami',
    name: 'Genoa salami',
    category: 'charcuterie',
    aestheticTags: ['classic'],
    seasonTags: ['all-season'],
    dietaryTags: [],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 130,
    clientDescription: 'Classic salami.',
    prepNotes: 'Shingle or fold.',
    storageNotes: 'Keep chilled.',
    active: true,
  },
  {
    id: 'seed-bresaola',
    name: 'Bresaola',
    category: 'charcuterie',
    aestheticTags: ['premium'],
    seasonTags: ['all-season'],
    dietaryTags: [],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 210,
    clientDescription: 'Lean cured beef accent.',
    prepNotes: 'Use as a premium accent.',
    storageNotes: 'Keep chilled and covered.',
    active: true,
  },
  {
    id: 'seed-turkey-salami',
    name: 'Turkey salami',
    category: 'charcuterie',
    aestheticTags: ['lighter'],
    seasonTags: ['all-season'],
    dietaryTags: [],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 135,
    clientDescription: 'Lighter cured meat option.',
    prepNotes: 'Fan with crackers.',
    storageNotes: 'Keep chilled.',
    active: true,
  },
  {
    id: 'seed-grapes',
    name: 'Grapes',
    category: 'fruit',
    aestheticTags: ['classic'],
    seasonTags: ['all-season'],
    dietaryTags: ['vegan', 'gluten-free'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 24,
    clientDescription: 'Fresh grape clusters.',
    prepNotes: 'Cut into small clusters and dry well.',
    storageNotes: 'Wash and chill.',
    active: true,
  },
  {
    id: 'seed-berries',
    name: 'Mixed berries',
    category: 'fruit',
    aestheticTags: ['bright'],
    seasonTags: ['spring', 'summer'],
    dietaryTags: ['vegan', 'gluten-free'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 60,
    clientDescription: 'Bright seasonal berries.',
    prepNotes: 'Dry thoroughly to avoid bleeding.',
    storageNotes: 'Keep chilled and lined.',
    active: true,
  },
  {
    id: 'seed-figs',
    name: 'Figs',
    category: 'fruit',
    aestheticTags: ['seasonal', 'premium'],
    seasonTags: ['late-summer', 'fall'],
    dietaryTags: ['vegan', 'gluten-free'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 95,
    clientDescription: 'Seasonal figs when available.',
    prepNotes: 'Halve close to setup.',
    storageNotes: 'Handle gently.',
    active: true,
  },
  {
    id: 'seed-citrus',
    name: 'Citrus segments',
    category: 'fruit',
    aestheticTags: ['bright'],
    seasonTags: ['winter', 'spring'],
    dietaryTags: ['vegan', 'gluten-free'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 32,
    clientDescription: 'Bright citrus accents.',
    prepNotes: 'Segment and drain.',
    storageNotes: 'Keep chilled.',
    active: true,
  },
  {
    id: 'seed-apple-slices',
    name: 'Apple slices',
    category: 'fruit',
    aestheticTags: ['crisp'],
    seasonTags: ['fall', 'winter'],
    dietaryTags: ['vegan', 'gluten-free'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 22,
    clientDescription: 'Crisp apple slices.',
    prepNotes: 'Treat to prevent browning.',
    storageNotes: 'Prep close to service.',
    active: true,
  },
  {
    id: 'seed-pear-slices',
    name: 'Pear slices',
    category: 'fruit',
    aestheticTags: ['soft', 'seasonal'],
    seasonTags: ['fall', 'winter'],
    dietaryTags: ['vegan', 'gluten-free'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 30,
    clientDescription: 'Seasonal pear slices.',
    prepNotes: 'Slice close to service.',
    storageNotes: 'Keep chilled.',
    active: true,
  },
  {
    id: 'seed-dried-apricots',
    name: 'Dried apricots',
    category: 'fruit',
    aestheticTags: ['warm'],
    seasonTags: ['all-season'],
    dietaryTags: ['vegan', 'gluten-free'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 45,
    clientDescription: 'Dried fruit accent.',
    prepNotes: 'Group near nuts and firm cheese.',
    storageNotes: 'Shelf stable.',
    active: true,
  },
  {
    id: 'seed-melon',
    name: 'Melon',
    category: 'fruit',
    aestheticTags: ['fresh'],
    seasonTags: ['summer'],
    dietaryTags: ['vegan', 'gluten-free'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 26,
    clientDescription: 'Fresh melon pieces.',
    prepNotes: 'Drain well and keep away from crackers.',
    storageNotes: 'Keep chilled.',
    active: true,
  },
  {
    id: 'seed-water-crackers',
    name: 'Water crackers',
    category: 'cracker_bread',
    aestheticTags: ['classic'],
    seasonTags: ['all-season'],
    dietaryTags: ['vegetarian'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 28,
    clientDescription: 'Classic crisp cracker.',
    prepNotes: 'Stage refills separately.',
    storageNotes: 'Keep dry.',
    active: true,
  },
  {
    id: 'seed-crostini',
    name: 'Crostini',
    category: 'cracker_bread',
    aestheticTags: ['rustic'],
    seasonTags: ['all-season'],
    dietaryTags: ['vegetarian'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 32,
    clientDescription: 'Toasted bread slices.',
    prepNotes: 'Toast and cool fully before packing.',
    storageNotes: 'Keep dry.',
    active: true,
  },
  {
    id: 'seed-baguette',
    name: 'Sliced baguette',
    category: 'cracker_bread',
    aestheticTags: ['classic'],
    seasonTags: ['all-season'],
    dietaryTags: ['vegetarian'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 18,
    clientDescription: 'Fresh baguette slices.',
    prepNotes: 'Slice day-of when possible.',
    storageNotes: 'Bag loosely.',
    active: true,
  },
  {
    id: 'seed-seeded-crackers',
    name: 'Seeded crackers',
    category: 'cracker_bread',
    aestheticTags: ['textured'],
    seasonTags: ['all-season'],
    dietaryTags: ['vegetarian'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 38,
    clientDescription: 'Seeded cracker variety.',
    prepNotes: 'Mix with plain crackers.',
    storageNotes: 'Keep dry.',
    active: true,
  },
  {
    id: 'seed-gluten-free-crackers',
    name: 'Gluten-free crackers',
    category: 'cracker_bread',
    aestheticTags: ['dietary'],
    seasonTags: ['all-season'],
    dietaryTags: ['gluten-free', 'vegetarian'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 55,
    clientDescription: 'Gluten-free cracker option.',
    prepNotes: 'Keep separated from gluten items.',
    storageNotes: 'Keep dry and sealed.',
    active: true,
  },
  {
    id: 'seed-flatbread',
    name: 'Flatbread crisps',
    category: 'cracker_bread',
    aestheticTags: ['rustic'],
    seasonTags: ['all-season'],
    dietaryTags: ['vegetarian'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 34,
    clientDescription: 'Rustic crisp flatbread.',
    prepNotes: 'Break into serviceable pieces.',
    storageNotes: 'Keep dry.',
    active: true,
  },
  {
    id: 'seed-marcona-almonds',
    name: 'Marcona almonds',
    category: 'nut',
    aestheticTags: ['premium'],
    seasonTags: ['all-season'],
    dietaryTags: ['gluten-free'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 95,
    clientDescription: 'Buttery almonds.',
    prepNotes: 'Bowl separately for allergen clarity.',
    storageNotes: 'Keep sealed.',
    active: true,
  },
  {
    id: 'seed-candied-walnuts',
    name: 'Candied walnuts',
    category: 'nut',
    aestheticTags: ['sweet'],
    seasonTags: ['fall', 'winter'],
    dietaryTags: ['vegetarian', 'gluten-free'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 80,
    clientDescription: 'Sweet crunchy walnuts.',
    prepNotes: 'Bowl separately for allergen clarity.',
    storageNotes: 'Keep sealed.',
    active: true,
  },
  {
    id: 'seed-pistachios',
    name: 'Pistachios',
    category: 'nut',
    aestheticTags: ['green'],
    seasonTags: ['all-season'],
    dietaryTags: ['gluten-free'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 85,
    clientDescription: 'Green nut accent.',
    prepNotes: 'Use shelled for service ease.',
    storageNotes: 'Keep sealed.',
    active: true,
  },
  {
    id: 'seed-fig-jam',
    name: 'Fig jam',
    category: 'dip_spread',
    aestheticTags: ['sweet'],
    seasonTags: ['all-season'],
    dietaryTags: ['vegetarian', 'gluten-free'],
    defaultUnit: 'cup',
    defaultVendorId: null,
    costPerUnitCents: 400,
    clientDescription: 'Sweet jam for cheese pairing.',
    prepNotes: 'Portion into small bowls.',
    storageNotes: 'Keep chilled after opening.',
    active: true,
  },
  {
    id: 'seed-honeycomb',
    name: 'Honeycomb',
    category: 'dip_spread',
    aestheticTags: ['premium'],
    seasonTags: ['all-season'],
    dietaryTags: ['vegetarian', 'gluten-free'],
    defaultUnit: 'cup',
    defaultVendorId: null,
    costPerUnitCents: 650,
    clientDescription: 'Honeycomb accent.',
    prepNotes: 'Use in small controlled portions.',
    storageNotes: 'Room temperature.',
    active: true,
  },
  {
    id: 'seed-hummus',
    name: 'Hummus',
    category: 'dip_spread',
    aestheticTags: ['savory'],
    seasonTags: ['all-season'],
    dietaryTags: ['vegan', 'gluten-free'],
    defaultUnit: 'cup',
    defaultVendorId: null,
    costPerUnitCents: 250,
    clientDescription: 'Savory plant-based dip.',
    prepNotes: 'Bowl and garnish with oil.',
    storageNotes: 'Keep chilled.',
    active: true,
  },
  {
    id: 'seed-olive-medley',
    name: 'Olive medley',
    category: 'pickle_olive',
    aestheticTags: ['savory'],
    seasonTags: ['all-season'],
    dietaryTags: ['vegan', 'gluten-free'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 55,
    clientDescription: 'Briny olive mix.',
    prepNotes: 'Drain well before plating.',
    storageNotes: 'Keep chilled.',
    active: true,
  },
  {
    id: 'seed-cornichons',
    name: 'Cornichons',
    category: 'pickle_olive',
    aestheticTags: ['briny'],
    seasonTags: ['all-season'],
    dietaryTags: ['vegan', 'gluten-free'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 50,
    clientDescription: 'Small tart pickles.',
    prepNotes: 'Drain and bowl separately.',
    storageNotes: 'Keep chilled.',
    active: true,
  },
  {
    id: 'seed-dark-chocolate',
    name: 'Dark chocolate squares',
    category: 'sweet',
    aestheticTags: ['sweet'],
    seasonTags: ['all-season'],
    dietaryTags: ['vegetarian'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 70,
    clientDescription: 'Small sweet finish.',
    prepNotes: 'Place away from direct heat.',
    storageNotes: 'Keep cool.',
    active: true,
  },
  {
    id: 'seed-fresh-rosemary',
    name: 'Fresh rosemary',
    category: 'garnish',
    aestheticTags: ['herbal'],
    seasonTags: ['all-season'],
    dietaryTags: ['vegan', 'gluten-free'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 45,
    clientDescription: 'Aromatic herb garnish.',
    prepNotes: 'Use small clean sprigs.',
    storageNotes: 'Wrap lightly damp.',
    active: true,
  },
  {
    id: 'seed-edible-flowers',
    name: 'Edible flowers',
    category: 'garnish',
    aestheticTags: ['floral', 'premium'],
    seasonTags: ['spring', 'summer'],
    dietaryTags: ['vegan', 'gluten-free'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 180,
    clientDescription: 'Seasonal floral finish.',
    prepNotes: 'Add at final setup only.',
    storageNotes: 'Keep chilled and protected.',
    active: true,
  },
  {
    id: 'seed-citrus-leaves',
    name: 'Citrus leaves',
    category: 'garnish',
    aestheticTags: ['greenery'],
    seasonTags: ['all-season'],
    dietaryTags: ['vegan', 'gluten-free'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 35,
    clientDescription: 'Greenery for finish.',
    prepNotes: 'Use only food-safe leaves.',
    storageNotes: 'Keep lightly damp.',
    active: true,
  },
  {
    id: 'seed-microgreens',
    name: 'Microgreens',
    category: 'garnish',
    aestheticTags: ['fresh'],
    seasonTags: ['all-season'],
    dietaryTags: ['vegan', 'gluten-free'],
    defaultUnit: 'oz',
    defaultVendorId: null,
    costPerUnitCents: 120,
    clientDescription: 'Fresh green accent.',
    prepNotes: 'Add late to avoid wilting.',
    storageNotes: 'Keep chilled.',
    active: true,
  },
  {
    id: 'seed-small-bowls',
    name: 'Small service bowls',
    category: 'prop',
    aestheticTags: ['service'],
    seasonTags: ['all-season'],
    dietaryTags: [],
    defaultUnit: 'each',
    defaultVendorId: null,
    costPerUnitCents: 600,
    clientDescription: null,
    prepNotes: 'Pack extra for wet items and refills.',
    storageNotes: 'Clean and wrap.',
    active: true,
  },
  {
    id: 'seed-risers',
    name: 'Table risers',
    category: 'prop',
    aestheticTags: ['height'],
    seasonTags: ['all-season'],
    dietaryTags: [],
    defaultUnit: 'each',
    defaultVendorId: null,
    costPerUnitCents: 1200,
    clientDescription: null,
    prepNotes: 'Use for height on large tables.',
    storageNotes: 'Pack securely.',
    active: true,
  },
]
