import type { MetadataRoute } from 'next'
import { PUBLIC_SITE_URL } from '@/lib/site/public-site'

const BASE_URL = PUBLIC_SITE_URL

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/chef/',
          '/chefs',
          '/compare',
          '/compare/',
          '/faq',
          '/how-it-works',
          '/marketplace-chefs',
          '/services',
          '/trust',
          '/trust/',
          '/contact',
          '/privacy',
          '/terms',
          '/partner-signup',
          '/for-operators',
          '/about',
          '/nearby',
          '/nearby/',
          '/book',
          '/cannabis/public',
          '/pricing',
          '/eat',
        ],
        disallow: [
          '/api/',
          '/auth/',
          '/beta-survey/',
          '/event/',
          '/share/',
          '/g/',
          '/book/',
          '/embed/',
          '/customers',
          '/customers/',
          '/dashboard',
          '/events',
          '/clients',
          '/quotes',
          '/inquiries',
          '/inbox',
          '/finance',
          '/settings',
          '/recipes',
          '/menus',
          '/calendar',
          '/documents',
          '/staff',
          '/my-events',
          '/my-quotes',
          '/my-chat',
          '/my-profile',
          '/my-rewards',
          '/my-inquiries',
          '/cannabis-invite/',
          '/admin/',
          '/proposal/',
          '/tip/',
          '/worksheet/',
          '/feedback/',
          '/guest-feedback/',
          '/review/',
          '/view/',
          '/availability/',
          '/menu/',
          '/e/',
          '/onboarding/',
          '/partner-report/',
          '/hub/me/',
          '/hub/join/',
          '/hub/g/',
          '/survey/',
          // Chef-protected paths (defense-in-depth; middleware is primary guard)
          '/activity',
          '/analytics',
          '/autopilot',
          '/briefing',
          '/calls',
          '/cannabis/',
          '/capture',
          '/circles',
          '/commerce',
          '/community',
          '/contracts',
          '/culinary',
          '/daily',
          '/expenses',
          '/goals',
          '/intelligence',
          '/insights',
          '/inventory',
          '/kitchen',
          '/leads',
          '/locations',
          '/loyalty',
          '/marketing',
          '/network',
          '/notifications',
          '/nutrition',
          '/ops',
          '/partners',
          '/payments',
          '/pipeline',
          '/portfolio',
          '/production',
          '/proposals',
          '/remy',
          '/reports',
          '/reputation',
          '/reviews',
          '/safety',
          '/social',
          '/stations',
          '/tasks',
          '/team',
          '/travel',
          '/vendors',
          '/waitlist',
          '/welcome',
          // Client-protected paths
          '/book-now',
          '/browse-dates',
          '/my-',
          // Staff/partner/vendor
          '/staff-',
          '/partner',
          '/vendor',
        ],
      },
      // Block aggressive crawlers that waste bandwidth
      {
        userAgent: 'AhrefsBot',
        crawlDelay: 10,
      },
      {
        userAgent: 'SemrushBot',
        crawlDelay: 10,
      },
    ],
    sitemap: `${BASE_URL}/sitemap.xml`,
  }
}
