import type { RailProfile, RailProfileMatch } from './contextual-rail-types'

export const RAIL_PROFILES: RailProfile[] = [
  {
    id: 'event-detail',
    pattern: /^\/events\/([^/]+)$/,
    entityExtract: (m) => ({ type: 'event', id: m[1] }),
    categories: ['readiness', 'money', 'people', 'time', 'risk', 'intelligence', 'actions'],
    primaryCategory: 'readiness',
    resolverFilter: [
      'completion',
      'events',
      'payments',
      'prep-status',
      'packing-status',
      'shopping-lists',
      'menu-approvals',
      'contracts',
      'messages',
      'communication-feed',
      'staff-issues',
      'weather-alerts',
      'equipment-conflicts',
      'cil-signals',
      'intelligence-signals',
      'lifecycle-stages',
      'dish-fatigue',
    ],
    entityScoped: true,
    collapsedSummary: 'readiness-bar',
    collapsedMetrics: [
      { label: 'Ready', resolverKey: 'completion', format: 'percent' },
      { label: 'Critical', resolverKey: '_critical_count', format: 'number', severity: 'critical' },
      { label: 'Days', resolverKey: 'events', format: 'countdown' },
      { label: 'Margin', resolverKey: 'payments', format: 'percent' },
      { label: 'Messages', resolverKey: 'messages', format: 'number' },
    ],
    layout: 'columns',
    columnCount: 4,
    maxItems: 24,
    defaultExpanded: true,
    stickyOnScroll: false,
  },
  {
    id: 'client-detail',
    pattern: /^\/clients\/([^/]+)$/,
    entityExtract: (m) => ({ type: 'client', id: m[1] }),
    categories: ['people', 'money', 'communication', 'risk', 'intelligence'],
    primaryCategory: 'people',
    resolverFilter: [
      'events',
      'payments',
      'dormant-clients',
      'client-birthdays',
      'followups',
      'messages',
      'communication-feed',
      'cadence-due',
      'scheduled-messages',
      'revenue-opportunities',
      'cil-signals',
      'intelligence-signals',
      'review-requests',
    ],
    entityScoped: true,
    collapsedSummary: 'metric-row',
    collapsedMetrics: [
      { label: 'Lifetime', resolverKey: 'payments', format: 'currency' },
      { label: 'Last Contact', resolverKey: 'communication-feed', format: 'date' },
      { label: 'Outstanding', resolverKey: 'payments', format: 'currency' },
      { label: 'Events', resolverKey: 'events', format: 'number' },
    ],
    layout: 'columns',
    columnCount: 3,
    maxItems: 18,
    defaultExpanded: false,
    stickyOnScroll: false,
  },
  {
    id: 'menu-detail',
    pattern: /^\/menus\/([^/]+)$/,
    entityExtract: (m) => ({ type: 'menu', id: m[1] }),
    categories: ['readiness', 'money', 'people', 'intelligence', 'actions'],
    primaryCategory: 'readiness',
    resolverFilter: [
      'completion',
      'payments',
      'menu-approvals',
      'dish-fatigue',
      'quality-drift',
      'intelligence-signals',
      'cil-signals',
      'shopping-lists',
    ],
    entityScoped: true,
    collapsedSummary: 'readiness-bar',
    collapsedMetrics: [
      { label: 'Ready', resolverKey: 'completion', format: 'percent' },
      { label: 'Food Cost', resolverKey: 'payments', format: 'currency' },
      { label: 'Margin', resolverKey: 'payments', format: 'percent' },
      { label: 'Dishes', resolverKey: 'completion', format: 'number' },
      { label: 'Alerts', resolverKey: 'intelligence-signals', format: 'number' },
    ],
    layout: 'columns',
    columnCount: 4,
    maxItems: 20,
    defaultExpanded: true,
    stickyOnScroll: false,
  },
  {
    id: 'calendar',
    pattern: /^\/calendar$/,
    categories: ['time', 'risk', 'intelligence'],
    primaryCategory: 'time',
    resolverFilter: [
      'events',
      'contracts',
      'prep-status',
      'packing-status',
      'inquiries',
      'equipment-conflicts',
      'weather-alerts',
      'completion',
      'payments',
      'revenue-goals',
      'cil-signals',
      'intelligence-signals',
    ],
    entityScoped: false,
    collapsedSummary: 'countdown',
    collapsedMetrics: [
      { label: 'Next', resolverKey: 'events', format: 'countdown' },
      { label: 'This Week', resolverKey: 'events', format: 'number' },
      { label: 'Warnings', resolverKey: '_critical_count', format: 'number', severity: 'warn' },
      { label: 'Booked', resolverKey: 'revenue-goals', format: 'percent' },
    ],
    layout: 'columns',
    columnCount: 3,
    maxItems: 15,
    defaultExpanded: false,
    stickyOnScroll: false,
  },
  {
    id: 'inquiries',
    pattern: /^\/inquiries/,
    categories: ['communication', 'time', 'people', 'money', 'actions'],
    primaryCategory: 'communication',
    resolverFilter: [
      'inquiries',
      'messages',
      'communication-feed',
      'payments',
      'followups',
      'cadence-due',
      'intelligence-signals',
    ],
    entityScoped: false,
    collapsedSummary: 'metric-row',
    collapsedMetrics: [
      { label: 'New', resolverKey: 'inquiries', format: 'number' },
      { label: 'Oldest', resolverKey: 'inquiries', format: 'countdown' },
      { label: 'Pipeline', resolverKey: 'payments', format: 'currency' },
    ],
    layout: 'columns',
    columnCount: 3,
    maxItems: 15,
    defaultExpanded: true,
    stickyOnScroll: false,
  },
  {
    id: 'recipe-detail',
    pattern: /^\/recipes\/([^/]+)$/,
    entityExtract: (m) => ({ type: 'recipe', id: m[1] }),
    categories: ['readiness', 'intelligence', 'actions'],
    primaryCategory: 'readiness',
    resolverFilter: ['completion', 'dish-fatigue', 'quality-drift', 'intelligence-signals'],
    entityScoped: true,
    collapsedSummary: 'readiness-bar',
    collapsedMetrics: [
      { label: 'Complete', resolverKey: 'completion', format: 'percent' },
      { label: 'Quality', resolverKey: 'quality-drift', format: 'percent' },
    ],
    layout: 'columns',
    columnCount: 2,
    maxItems: 10,
    defaultExpanded: true,
    stickyOnScroll: false,
  },
  {
    id: 'finance',
    pattern: /^\/finance/,
    categories: ['money', 'risk', 'time'],
    primaryCategory: 'money',
    resolverFilter: [
      'payments',
      'revenue-goals',
      'recurring-invoices',
      'vendor-invoices',
      'receipt-capture',
      'revenue-opportunities',
    ],
    entityScoped: false,
    collapsedSummary: 'metric-row',
    collapsedMetrics: [
      { label: 'Outstanding', resolverKey: 'payments', format: 'currency' },
      { label: 'Overdue', resolverKey: 'payments', format: 'currency', severity: 'critical' },
      { label: 'Goal', resolverKey: 'revenue-goals', format: 'percent' },
    ],
    layout: 'columns',
    columnCount: 3,
    maxItems: 15,
    defaultExpanded: false,
    stickyOnScroll: false,
  },
  {
    id: 'prep-shopping',
    pattern: /^\/(prep|shopping)/,
    categories: ['readiness', 'time', 'actions'],
    primaryCategory: 'readiness',
    resolverFilter: ['prep-status', 'shopping-lists', 'packing-status', 'events', 'completion'],
    entityScoped: false,
    collapsedSummary: 'readiness-bar',
    collapsedMetrics: [
      { label: 'Items', resolverKey: 'shopping-lists', format: 'number' },
      { label: 'Sourced', resolverKey: 'shopping-lists', format: 'percent' },
      { label: 'Next Event', resolverKey: 'events', format: 'countdown' },
    ],
    layout: 'columns',
    columnCount: 2,
    maxItems: 12,
    defaultExpanded: true,
    stickyOnScroll: false,
  },
  {
    id: 'analytics',
    pattern: /^\/analytics/,
    categories: ['money', 'intelligence'],
    primaryCategory: 'intelligence',
    resolverFilter: [
      'revenue-goals',
      'payments',
      'cil-signals',
      'intelligence-signals',
      'revenue-opportunities',
    ],
    entityScoped: false,
    collapsedSummary: 'metric-row',
    collapsedMetrics: [
      { label: 'Revenue', resolverKey: 'revenue-goals', format: 'currency' },
      { label: 'Margin', resolverKey: 'payments', format: 'percent' },
    ],
    layout: 'columns',
    columnCount: 2,
    maxItems: 10,
    defaultExpanded: false,
    stickyOnScroll: false,
  },
  {
    id: 'fallback',
    pattern: /.*/,
    categories: ['actions', 'risk'],
    primaryCategory: 'actions',
    resolverFilter: [],
    entityScoped: false,
    collapsedSummary: 'status-ticker',
    collapsedMetrics: [
      { label: 'Critical', resolverKey: '_critical_count', format: 'number', severity: 'critical' },
    ],
    layout: 'stack',
    maxItems: 5,
    defaultExpanded: false,
    stickyOnScroll: false,
  },
]

export function matchRailProfile(pathname: string): RailProfileMatch {
  for (const profile of RAIL_PROFILES) {
    const match = pathname.match(profile.pattern)
    if (match) {
      const entityContext = extractEntityContext(profile, match)
      return { profile, entityContext }
    }
  }
  const fallback = RAIL_PROFILES[RAIL_PROFILES.length - 1]
  return { profile: fallback, entityContext: null }
}

export function extractEntityContext(
  profile: RailProfile,
  match: RegExpMatchArray
): RailProfileMatch['entityContext'] {
  return profile.entityExtract ? profile.entityExtract(match) : null
}
