// Phosphor Icons - mapped from former Lucide icon names for drop-in compatibility
// ChefFlow uses Phosphor (https://phosphoricons.com/) for a distinctive visual identity
// Import from '@/components/ui/icons' instead of 'lucide-react'

export type { Icon as LucideIcon, IconProps } from '@phosphor-icons/react/dist/lib/types'

// Re-export Phosphor icons under their Lucide-equivalent names
// This allows a single import path change across the entire codebase

export { Pulse as Activity } from '@phosphor-icons/react/dist/ssr/Pulse'
export { WarningCircle as AlertCircle } from '@phosphor-icons/react/dist/ssr/WarningCircle'
export { WarningCircle } from '@phosphor-icons/react/dist/ssr/WarningCircle'
export { WarningOctagon as AlertOctagon } from '@phosphor-icons/react/dist/ssr/WarningOctagon'
export { Warning as AlertTriangle } from '@phosphor-icons/react/dist/ssr/Warning'
export { AppleLogo as Apple } from '@phosphor-icons/react/dist/ssr/AppleLogo'
export { Archive } from '@phosphor-icons/react/dist/ssr/Archive'
export { ArrowDown } from '@phosphor-icons/react/dist/ssr/ArrowDown'
export { ArrowDownRight } from '@phosphor-icons/react/dist/ssr/ArrowDownRight'
export { ArrowLeft } from '@phosphor-icons/react/dist/ssr/ArrowLeft'
export { ArrowRight } from '@phosphor-icons/react/dist/ssr/ArrowRight'
export { ArrowUp } from '@phosphor-icons/react/dist/ssr/ArrowUp'
export { ArrowsDownUp as ArrowUpDown } from '@phosphor-icons/react/dist/ssr/ArrowsDownUp'
export { ArrowUpRight } from '@phosphor-icons/react/dist/ssr/ArrowUpRight'
export { Medal as Award } from '@phosphor-icons/react/dist/ssr/Medal'
export { Money as Banknote } from '@phosphor-icons/react/dist/ssr/Money'
export { BatteryFull as Battery } from '@phosphor-icons/react/dist/ssr/BatteryFull'
export { ChartBar as BarChart2 } from '@phosphor-icons/react/dist/ssr/ChartBar'
export { ChartBar as BarChart3 } from '@phosphor-icons/react/dist/ssr/ChartBar'
export { Bell } from '@phosphor-icons/react/dist/ssr/Bell'
export { BellSlash as BellOff } from '@phosphor-icons/react/dist/ssr/BellSlash'
export { BellRinging as BellRing } from '@phosphor-icons/react/dist/ssr/BellRinging'
export { TextB as Bold } from '@phosphor-icons/react/dist/ssr/TextB'
export { BookBookmark as BookMarked } from '@phosphor-icons/react/dist/ssr/BookBookmark'
export { BookOpen } from '@phosphor-icons/react/dist/ssr/BookOpen'
export { Notebook as BookTemplate } from '@phosphor-icons/react/dist/ssr/Notebook'
export { Bookmark } from '@phosphor-icons/react/dist/ssr/Bookmark'
export { Robot as Bot } from '@phosphor-icons/react/dist/ssr/Robot'
export { BracketsCurly as Braces } from '@phosphor-icons/react/dist/ssr/BracketsCurly'
export { Brain } from '@phosphor-icons/react/dist/ssr/Brain'
export { Buildings as Building2 } from '@phosphor-icons/react/dist/ssr/Buildings'
export { Calculator } from '@phosphor-icons/react/dist/ssr/Calculator'
export { Calendar } from '@phosphor-icons/react/dist/ssr/Calendar'
export { CalendarCheck } from '@phosphor-icons/react/dist/ssr/CalendarCheck'
export { CalendarDots as CalendarDays } from '@phosphor-icons/react/dist/ssr/CalendarDots'
export { CalendarPlus } from '@phosphor-icons/react/dist/ssr/CalendarPlus'
export { CalendarDots as CalendarRange } from '@phosphor-icons/react/dist/ssr/CalendarDots'
export { Camera } from '@phosphor-icons/react/dist/ssr/Camera'
export { Car } from '@phosphor-icons/react/dist/ssr/Car'
export { Check } from '@phosphor-icons/react/dist/ssr/Check'
export { Checks as CheckCheck } from '@phosphor-icons/react/dist/ssr/Checks'
export { CheckCircle } from '@phosphor-icons/react/dist/ssr/CheckCircle'
export { CheckCircle as CheckCircle2 } from '@phosphor-icons/react/dist/ssr/CheckCircle'
export { CheckSquare } from '@phosphor-icons/react/dist/ssr/CheckSquare'
export { ChefHat } from '@phosphor-icons/react/dist/ssr/ChefHat'
export { CaretDown as ChevronDown } from '@phosphor-icons/react/dist/ssr/CaretDown'
export { CaretLeft as ChevronLeft } from '@phosphor-icons/react/dist/ssr/CaretLeft'
export { CaretRight as ChevronRight } from '@phosphor-icons/react/dist/ssr/CaretRight'
export { CaretUp as ChevronUp } from '@phosphor-icons/react/dist/ssr/CaretUp'
export { CaretDoubleDown as ChevronsDownUp } from '@phosphor-icons/react/dist/ssr/CaretDoubleDown'
export { CaretUpDown as ChevronsUpDown } from '@phosphor-icons/react/dist/ssr/CaretUpDown'
export { GoogleChromeLogo as Chrome } from '@phosphor-icons/react/dist/ssr/GoogleChromeLogo'
export { Circle } from '@phosphor-icons/react/dist/ssr/Circle'
export { ClipboardText as ClipboardCheck } from '@phosphor-icons/react/dist/ssr/ClipboardText'
export { ClipboardText as ClipboardList } from '@phosphor-icons/react/dist/ssr/ClipboardText'
export { Clock } from '@phosphor-icons/react/dist/ssr/Clock'
export { Clock as Clock3 } from '@phosphor-icons/react/dist/ssr/Clock'
export { CloudArrowUp as CloudUpload } from '@phosphor-icons/react/dist/ssr/CloudArrowUp'
export { CodeBlock as Code2 } from '@phosphor-icons/react/dist/ssr/CodeBlock'
export { Compass } from '@phosphor-icons/react/dist/ssr/Compass'
export { AddressBook as Contact } from '@phosphor-icons/react/dist/ssr/AddressBook'
export { Copy } from '@phosphor-icons/react/dist/ssr/Copy'
export { Cpu } from '@phosphor-icons/react/dist/ssr/Cpu'
export { CreditCard } from '@phosphor-icons/react/dist/ssr/CreditCard'
export { Crosshair } from '@phosphor-icons/react/dist/ssr/Crosshair'
export { Crown } from '@phosphor-icons/react/dist/ssr/Crown'
export { CurrencyDollar as DollarSign } from '@phosphor-icons/react/dist/ssr/CurrencyDollar'
export { Download } from '@phosphor-icons/react/dist/ssr/Download'
export { PencilSimple as Edit2 } from '@phosphor-icons/react/dist/ssr/PencilSimple'
export { PencilLine as Edit3 } from '@phosphor-icons/react/dist/ssr/PencilLine'
export { ArrowSquareOut as ExternalLink } from '@phosphor-icons/react/dist/ssr/ArrowSquareOut'
export { Eye } from '@phosphor-icons/react/dist/ssr/Eye'
export { EyeSlash as EyeOff } from '@phosphor-icons/react/dist/ssr/EyeSlash'
export { File } from '@phosphor-icons/react/dist/ssr/File'
export { FileText as FileCheck } from '@phosphor-icons/react/dist/ssr/FileText'
export { FileXls as FileSpreadsheet } from '@phosphor-icons/react/dist/ssr/FileXls'
export { FileText } from '@phosphor-icons/react/dist/ssr/FileText'
export { FilmStrip as Film } from '@phosphor-icons/react/dist/ssr/FilmStrip'
export { Funnel as Filter } from '@phosphor-icons/react/dist/ssr/Funnel'
export { Fire as Flame } from '@phosphor-icons/react/dist/ssr/Fire'
export { Flask as FlaskConical } from '@phosphor-icons/react/dist/ssr/Flask'
export { CrosshairSimple as Focus } from '@phosphor-icons/react/dist/ssr/CrosshairSimple'
export { GameController as Gamepad2 } from '@phosphor-icons/react/dist/ssr/GameController'
export { Ghost } from '@phosphor-icons/react/dist/ssr/Ghost'
export { Gift } from '@phosphor-icons/react/dist/ssr/Gift'
export { GitBranch } from '@phosphor-icons/react/dist/ssr/GitBranch'
export { Globe } from '@phosphor-icons/react/dist/ssr/Globe'
export { GridNine as Grid3X3 } from '@phosphor-icons/react/dist/ssr/GridNine'
export { DotsSixVertical as GripVertical } from '@phosphor-icons/react/dist/ssr/DotsSixVertical'
export { Handshake } from '@phosphor-icons/react/dist/ssr/Handshake'
export { Hash } from '@phosphor-icons/react/dist/ssr/Hash'
export { Heart } from '@phosphor-icons/react/dist/ssr/Heart'
export { HandHeart as HeartHandshake } from '@phosphor-icons/react/dist/ssr/HandHeart'
export { ClockCounterClockwise as History } from '@phosphor-icons/react/dist/ssr/ClockCounterClockwise'
export { House as Home } from '@phosphor-icons/react/dist/ssr/House'
export { Image } from '@phosphor-icons/react/dist/ssr/Image'
export { CameraPlus as ImagePlus } from '@phosphor-icons/react/dist/ssr/CameraPlus'
export { Tray as Inbox } from '@phosphor-icons/react/dist/ssr/Tray'
export { Info } from '@phosphor-icons/react/dist/ssr/Info'
export { TextItalic as Italic } from '@phosphor-icons/react/dist/ssr/TextItalic'
export { Bank as Landmark } from '@phosphor-icons/react/dist/ssr/Bank'
export { Stack as Layers } from '@phosphor-icons/react/dist/ssr/Stack'
export { SquaresFour as LayoutDashboard } from '@phosphor-icons/react/dist/ssr/SquaresFour'
export { GridFour as LayoutGrid } from '@phosphor-icons/react/dist/ssr/GridFour'
export { Lightbulb } from '@phosphor-icons/react/dist/ssr/Lightbulb'
export { Link } from '@phosphor-icons/react/dist/ssr/Link'
export { LinkSimple as Link2 } from '@phosphor-icons/react/dist/ssr/LinkSimple'
export { List } from '@phosphor-icons/react/dist/ssr/List'
export { ListChecks } from '@phosphor-icons/react/dist/ssr/ListChecks'
export { ListNumbers as ListOrdered } from '@phosphor-icons/react/dist/ssr/ListNumbers'
export { SpinnerGap as Loader2 } from '@phosphor-icons/react/dist/ssr/SpinnerGap'
export { Lock } from '@phosphor-icons/react/dist/ssr/Lock'
export { SignOut as LogOut } from '@phosphor-icons/react/dist/ssr/SignOut'
export { Envelope as Mail } from '@phosphor-icons/react/dist/ssr/Envelope'
export { EnvelopeOpen as MailPlus } from '@phosphor-icons/react/dist/ssr/EnvelopeOpen'
export { MapPin } from '@phosphor-icons/react/dist/ssr/MapPin'
export { ArrowsOut as Maximize2 } from '@phosphor-icons/react/dist/ssr/ArrowsOut'
export { Megaphone } from '@phosphor-icons/react/dist/ssr/Megaphone'
export { List as Menu } from '@phosphor-icons/react/dist/ssr/List'
export { GitMerge as Merge } from '@phosphor-icons/react/dist/ssr/GitMerge'
export { ChatCircle as MessageCircle } from '@phosphor-icons/react/dist/ssr/ChatCircle'
export { Chat as MessageSquare } from '@phosphor-icons/react/dist/ssr/Chat'
export { ChatCenteredText as MessageSquareWarning } from '@phosphor-icons/react/dist/ssr/ChatCenteredText'
export { Chats as MessagesSquare } from '@phosphor-icons/react/dist/ssr/Chats'
export { ArrowsIn as Minimize2 } from '@phosphor-icons/react/dist/ssr/ArrowsIn'
export { Minus } from '@phosphor-icons/react/dist/ssr/Minus'
export { MinusCircle } from '@phosphor-icons/react/dist/ssr/MinusCircle'
export { Monitor } from '@phosphor-icons/react/dist/ssr/Monitor'
export { Moon } from '@phosphor-icons/react/dist/ssr/Moon'
export { Cursor as MousePointer } from '@phosphor-icons/react/dist/ssr/Cursor'
export { CursorClick as MousePointerClick } from '@phosphor-icons/react/dist/ssr/CursorClick'
export { ArrowsOutCardinal as Move } from '@phosphor-icons/react/dist/ssr/ArrowsOutCardinal'
export { Package } from '@phosphor-icons/react/dist/ssr/Package'
export { Palette } from '@phosphor-icons/react/dist/ssr/Palette'
export { Paperclip } from '@phosphor-icons/react/dist/ssr/Paperclip'
export { Pause } from '@phosphor-icons/react/dist/ssr/Pause'
export { Pencil } from '@phosphor-icons/react/dist/ssr/Pencil'
export { Pencil as Edit } from '@phosphor-icons/react/dist/ssr/Pencil'
export { Confetti as PartyPopper } from '@phosphor-icons/react/dist/ssr/Confetti'
export { Percent } from '@phosphor-icons/react/dist/ssr/Percent'
export { Phone } from '@phosphor-icons/react/dist/ssr/Phone'
export { PhoneCall } from '@phosphor-icons/react/dist/ssr/PhoneCall'
export { ChartPie as PieChart } from '@phosphor-icons/react/dist/ssr/ChartPie'
export { PiggyBank } from '@phosphor-icons/react/dist/ssr/PiggyBank'
export { PushPin as Pin } from '@phosphor-icons/react/dist/ssr/PushPin'
export { PushPinSlash as PinOff } from '@phosphor-icons/react/dist/ssr/PushPinSlash'
export { Play } from '@phosphor-icons/react/dist/ssr/Play'
export { Plus } from '@phosphor-icons/react/dist/ssr/Plus'
export { PlusCircle } from '@phosphor-icons/react/dist/ssr/PlusCircle'
export { Power } from '@phosphor-icons/react/dist/ssr/Power'
export { Presentation } from '@phosphor-icons/react/dist/ssr/Presentation'
export { Printer } from '@phosphor-icons/react/dist/ssr/Printer'
export { Quotes as Quote } from '@phosphor-icons/react/dist/ssr/Quotes'
export { Radio } from '@phosphor-icons/react/dist/ssr/Radio'
export { Receipt } from '@phosphor-icons/react/dist/ssr/Receipt'
export { Recycle } from '@phosphor-icons/react/dist/ssr/Recycle'
export { ArrowClockwise as RefreshCw } from '@phosphor-icons/react/dist/ssr/ArrowClockwise'
export { Repeat } from '@phosphor-icons/react/dist/ssr/Repeat'
export { ArrowCounterClockwise as RotateCcw } from '@phosphor-icons/react/dist/ssr/ArrowCounterClockwise'
export { FloppyDisk as Save } from '@phosphor-icons/react/dist/ssr/FloppyDisk'
export { Scroll as ScrollText } from '@phosphor-icons/react/dist/ssr/Scroll'
export { MagnifyingGlass as Search } from '@phosphor-icons/react/dist/ssr/MagnifyingGlass'
export { PaperPlaneTilt as Send } from '@phosphor-icons/react/dist/ssr/PaperPlaneTilt'
export { HardDrives as Server } from '@phosphor-icons/react/dist/ssr/HardDrives'
export { Gear as Settings } from '@phosphor-icons/react/dist/ssr/Gear'
export { GearSix as Settings2 } from '@phosphor-icons/react/dist/ssr/GearSix'
export { ShareNetwork as Share2 } from '@phosphor-icons/react/dist/ssr/ShareNetwork'
export { Shield } from '@phosphor-icons/react/dist/ssr/Shield'
export { ShieldWarning as ShieldAlert } from '@phosphor-icons/react/dist/ssr/ShieldWarning'
export { ShieldCheck } from '@phosphor-icons/react/dist/ssr/ShieldCheck'
export { ShieldSlash as ShieldX } from '@phosphor-icons/react/dist/ssr/ShieldSlash'
export { ShoppingCart } from '@phosphor-icons/react/dist/ssr/ShoppingCart'
export { SkipForward } from '@phosphor-icons/react/dist/ssr/SkipForward'
export { DeviceMobile as Smartphone } from '@phosphor-icons/react/dist/ssr/DeviceMobile'
export { Sparkle as Sparkles } from '@phosphor-icons/react/dist/ssr/Sparkle'
export { Square } from '@phosphor-icons/react/dist/ssr/Square'
export { Star } from '@phosphor-icons/react/dist/ssr/Star'
export { Stethoscope } from '@phosphor-icons/react/dist/ssr/Stethoscope'
export { Note as StickyNote } from '@phosphor-icons/react/dist/ssr/Note'
export { Storefront as Store } from '@phosphor-icons/react/dist/ssr/Storefront'
export { Sun } from '@phosphor-icons/react/dist/ssr/Sun'
export { DeviceTablet as Tablet } from '@phosphor-icons/react/dist/ssr/DeviceTablet'
export { Tag } from '@phosphor-icons/react/dist/ssr/Tag'
export { Ticket } from '@phosphor-icons/react/dist/ssr/Ticket'
export { Target } from '@phosphor-icons/react/dist/ssr/Target'
export { Thermometer } from '@phosphor-icons/react/dist/ssr/Thermometer'
export { ToggleLeft } from '@phosphor-icons/react/dist/ssr/ToggleLeft'
export { Trash as Trash2 } from '@phosphor-icons/react/dist/ssr/Trash'
export { TrendDown as TrendingDown } from '@phosphor-icons/react/dist/ssr/TrendDown'
export { TrendUp as TrendingUp } from '@phosphor-icons/react/dist/ssr/TrendUp'
export { Trophy } from '@phosphor-icons/react/dist/ssr/Trophy'
export { Truck } from '@phosphor-icons/react/dist/ssr/Truck'
export { LinkBreak as Unlink } from '@phosphor-icons/react/dist/ssr/LinkBreak'
export { LockOpen as Unlock } from '@phosphor-icons/react/dist/ssr/LockOpen'
export { Upload } from '@phosphor-icons/react/dist/ssr/Upload'
export { User } from '@phosphor-icons/react/dist/ssr/User'
export { UserCheck } from '@phosphor-icons/react/dist/ssr/UserCheck'
export { UserCircle } from '@phosphor-icons/react/dist/ssr/UserCircle'
export { UserMinus } from '@phosphor-icons/react/dist/ssr/UserMinus'
export { UserPlus } from '@phosphor-icons/react/dist/ssr/UserPlus'
export { Users } from '@phosphor-icons/react/dist/ssr/Users'
export { UsersThree as Users2 } from '@phosphor-icons/react/dist/ssr/UsersThree'
export { UsersThree as UsersRound } from '@phosphor-icons/react/dist/ssr/UsersThree'
export { ForkKnife as Utensils } from '@phosphor-icons/react/dist/ssr/ForkKnife'
export { ForkKnife as UtensilsCrossed } from '@phosphor-icons/react/dist/ssr/ForkKnife'
export { Wallet } from '@phosphor-icons/react/dist/ssr/Wallet'
export { Warehouse } from '@phosphor-icons/react/dist/ssr/Warehouse'
export { WifiHigh as Wifi } from '@phosphor-icons/react/dist/ssr/WifiHigh'
export { WifiSlash as WifiOff } from '@phosphor-icons/react/dist/ssr/WifiSlash'
export { Wine } from '@phosphor-icons/react/dist/ssr/Wine'
export { Wrench } from '@phosphor-icons/react/dist/ssr/Wrench'
export { X } from '@phosphor-icons/react/dist/ssr/X'
export { XCircle } from '@phosphor-icons/react/dist/ssr/XCircle'
export { Lightning as Zap } from '@phosphor-icons/react/dist/ssr/Lightning'

// Distinct icons for navigation differentiation (batch 3 - icon overhaul)
export { ChatTeardropText } from '@phosphor-icons/react/dist/ssr/ChatTeardropText' // Inquiries (not Tray/Inbox)
export { Funnel } from '@phosphor-icons/react/dist/ssr/Funnel' // Sales pipeline
export { IdentificationBadge } from '@phosphor-icons/react/dist/ssr/IdentificationBadge' // Staff
export { PenNib } from '@phosphor-icons/react/dist/ssr/PenNib' // Content creation
export { Notepad } from '@phosphor-icons/react/dist/ssr/Notepad' // Station clipboards
export { Toolbox } from '@phosphor-icons/react/dist/ssr/Toolbox' // Tools group
export { ChartLineUp } from '@phosphor-icons/react/dist/ssr/ChartLineUp' // Client insights / trends
export { Coins } from '@phosphor-icons/react/dist/ssr/Coins' // Expenses
export { Invoice } from '@phosphor-icons/react/dist/ssr/Invoice' // Invoices
export { Notebook as NotebookIcon } from '@phosphor-icons/react/dist/ssr/Notebook' // Ledger
export { CurrencyCircleDollar } from '@phosphor-icons/react/dist/ssr/CurrencyCircleDollar' // Payments
export { Scales } from '@phosphor-icons/react/dist/ssr/Scales' // Reconciliation
export { SlidersHorizontal as Sliders } from '@phosphor-icons/react/dist/ssr/SlidersHorizontal' // Preferences
export { Strategy } from '@phosphor-icons/react/dist/ssr/Strategy' // Priority queue
export { ClipboardText as ClipboardTextIcon } from '@phosphor-icons/react/dist/ssr/ClipboardText' // Inventory counts
export { MagnifyingGlassPlus } from '@phosphor-icons/react/dist/ssr/MagnifyingGlassPlus' // Audits
export { Exam } from '@phosphor-icons/react/dist/ssr/Exam' // Event reviews / AAR
export { WifiHigh } from '@phosphor-icons/react/dist/ssr/WifiHigh' // Live presence
export { Broadcast } from '@phosphor-icons/react/dist/ssr/Broadcast' // Command center
export { FlagBanner } from '@phosphor-icons/react/dist/ssr/FlagBanner' // Feature flags
export { ChatDots } from '@phosphor-icons/react/dist/ssr/ChatDots' // Admin conversations
export { Megaphone as MegaphoneIcon } from '@phosphor-icons/react/dist/ssr/Megaphone' // Marketing group (re-export)
export { Chalkboard } from '@phosphor-icons/react/dist/ssr/Chalkboard' // Culinary board
export { Flower } from '@phosphor-icons/react/dist/ssr/Flower' // Seasonal palettes
export { TreeStructure } from '@phosphor-icons/react/dist/ssr/TreeStructure' // Directory
export { HandArrowDown } from '@phosphor-icons/react/dist/ssr/HandArrowDown' // Procurement
export { SealCheck } from '@phosphor-icons/react/dist/ssr/SealCheck' // Certifications

// Additional icons used across the codebase (batch 2)
export { ArrowsLeftRight as ArrowRightLeft } from '@phosphor-icons/react/dist/ssr/ArrowsLeftRight'
export { ArrowCircleRight as ArrowRightCircle } from '@phosphor-icons/react/dist/ssr/ArrowCircleRight'
export { CurrencyDollar as BadgeDollarSign } from '@phosphor-icons/react/dist/ssr/CurrencyDollar'
export { BookmarkSimple as BookmarkCheck } from '@phosphor-icons/react/dist/ssr/BookmarkSimple'
export { Cake } from '@phosphor-icons/react/dist/ssr/Cake'
export { CalendarDots as CalendarClock } from '@phosphor-icons/react/dist/ssr/CalendarDots'
export { CaretDoubleLeft as ChevronsLeft } from '@phosphor-icons/react/dist/ssr/CaretDoubleLeft'
export { CaretDoubleRight as ChevronsRight } from '@phosphor-icons/react/dist/ssr/CaretDoubleRight'
export { RadioButton as CircleDot } from '@phosphor-icons/react/dist/ssr/RadioButton'
export { Code } from '@phosphor-icons/react/dist/ssr/Code'
export { Database } from '@phosphor-icons/react/dist/ssr/Database'
export { Barbell as Dumbbell } from '@phosphor-icons/react/dist/ssr/Barbell'
export { FacebookLogo as Facebook } from '@phosphor-icons/react/dist/ssr/FacebookLogo'
export { NotePencil as FileEdit } from '@phosphor-icons/react/dist/ssr/NotePencil'
export { FileCode as FileJson } from '@phosphor-icons/react/dist/ssr/FileCode'
export { FileX } from '@phosphor-icons/react/dist/ssr/FileX'
export { FolderPlus } from '@phosphor-icons/react/dist/ssr/FolderPlus'
export { Footprints } from '@phosphor-icons/react/dist/ssr/Footprints'
export { GraduationCap } from '@phosphor-icons/react/dist/ssr/GraduationCap'
export { HandCoins } from '@phosphor-icons/react/dist/ssr/HandCoins'
export { HandHeart } from '@phosphor-icons/react/dist/ssr/HandHeart'
export { HardDrive } from '@phosphor-icons/react/dist/ssr/HardDrive'
export { Headphones } from '@phosphor-icons/react/dist/ssr/Headphones'
export { Question as HelpCircle } from '@phosphor-icons/react/dist/ssr/Question'
export { InstagramLogo as Instagram } from '@phosphor-icons/react/dist/ssr/InstagramLogo'
export { Kanban } from '@phosphor-icons/react/dist/ssr/Kanban'
export { Keyboard } from '@phosphor-icons/react/dist/ssr/Keyboard'
export { Layout } from '@phosphor-icons/react/dist/ssr/Layout'
export { Leaf } from '@phosphor-icons/react/dist/ssr/Leaf'
export { Funnel as ListFilter } from '@phosphor-icons/react/dist/ssr/Funnel'
export { EnvelopeOpen as MailOpen } from '@phosphor-icons/react/dist/ssr/EnvelopeOpen'
export { ChatCircleDots as MessageSquareDashed } from '@phosphor-icons/react/dist/ssr/ChatCircleDots'
export { Microphone as Mic } from '@phosphor-icons/react/dist/ssr/Microphone'
export { MicrophoneSlash as MicOff } from '@phosphor-icons/react/dist/ssr/MicrophoneSlash'
export { DotsThree as MoreHorizontal } from '@phosphor-icons/react/dist/ssr/DotsThree'
export { MusicNote as Music } from '@phosphor-icons/react/dist/ssr/MusicNote'
export { Newspaper } from '@phosphor-icons/react/dist/ssr/Newspaper'
export { NotePencil as NotebookPen } from '@phosphor-icons/react/dist/ssr/NotePencil'
export { Package as PackageCheck } from '@phosphor-icons/react/dist/ssr/Package'
export { PencilLine as PenLine } from '@phosphor-icons/react/dist/ssr/PencilLine'
export { AirplaneTilt as Plane } from '@phosphor-icons/react/dist/ssr/AirplaneTilt'
export { Plug } from '@phosphor-icons/react/dist/ssr/Plug'
export { Repeat as Repeat2 } from '@phosphor-icons/react/dist/ssr/Repeat'
export { Rss } from '@phosphor-icons/react/dist/ssr/Rss'
export { Scales as Scale } from '@phosphor-icons/react/dist/ssr/Scales'
export { Barcode as ScanLine } from '@phosphor-icons/react/dist/ssr/Barcode'
export { ShieldSlash as ShieldOff } from '@phosphor-icons/react/dist/ssr/ShieldSlash'
export { Shuffle } from '@phosphor-icons/react/dist/ssr/Shuffle'
export { SlidersHorizontal } from '@phosphor-icons/react/dist/ssr/SlidersHorizontal'
export { BowlSteam as Soup } from '@phosphor-icons/react/dist/ssr/BowlSteam'
export { SunHorizon as Sunset } from '@phosphor-icons/react/dist/ssr/SunHorizon'
export { ThumbsDown } from '@phosphor-icons/react/dist/ssr/ThumbsDown'
export { ThumbsUp } from '@phosphor-icons/react/dist/ssr/ThumbsUp'
export { Timer } from '@phosphor-icons/react/dist/ssr/Timer'
export { ToggleRight } from '@phosphor-icons/react/dist/ssr/ToggleRight'
export { SpeakerHigh as Volume2 } from '@phosphor-icons/react/dist/ssr/SpeakerHigh'
export { SpeakerX as VolumeX } from '@phosphor-icons/react/dist/ssr/SpeakerX'

// Additional icons (batch 3 - lucide migration stragglers)
export { Bag as ShoppingBag } from '@phosphor-icons/react/dist/ssr/Bag'
export { MapTrifold as Map } from '@phosphor-icons/react/dist/ssr/MapTrifold'
export { Images } from '@phosphor-icons/react/dist/ssr/Images'
export { Suitcase as Briefcase } from '@phosphor-icons/react/dist/ssr/Suitcase'
export { BellSimpleRinging as ConciergeBell } from '@phosphor-icons/react/dist/ssr/BellSimpleRinging'
export { Bread as Croissant } from '@phosphor-icons/react/dist/ssr/Bread'
export { RocketLaunch as Rocket } from '@phosphor-icons/react/dist/ssr/RocketLaunch'
export { Flag } from '@phosphor-icons/react/dist/ssr/Flag'
export { GitMerge } from '@phosphor-icons/react/dist/ssr/GitMerge'

// Food discovery icons
export { Avocado } from '@phosphor-icons/react/dist/ssr/Avocado'
export { BowlFood } from '@phosphor-icons/react/dist/ssr/BowlFood'
export { Bread } from '@phosphor-icons/react/dist/ssr/Bread'
export { Campfire } from '@phosphor-icons/react/dist/ssr/Campfire'
export { Carrot } from '@phosphor-icons/react/dist/ssr/Carrot'
export { Champagne } from '@phosphor-icons/react/dist/ssr/Champagne'
export { Cheers } from '@phosphor-icons/react/dist/ssr/Cheers'
export { Coffee } from '@phosphor-icons/react/dist/ssr/Coffee'
export { Cookie } from '@phosphor-icons/react/dist/ssr/Cookie'
export { CookingPot } from '@phosphor-icons/react/dist/ssr/CookingPot'
export { Cow } from '@phosphor-icons/react/dist/ssr/Cow'
export { Egg } from '@phosphor-icons/react/dist/ssr/Egg'
export { EggCrack } from '@phosphor-icons/react/dist/ssr/EggCrack'
export { Fish } from '@phosphor-icons/react/dist/ssr/Fish'
export { FishSimple } from '@phosphor-icons/react/dist/ssr/FishSimple'
export { Grains } from '@phosphor-icons/react/dist/ssr/Grains'
export { Hamburger } from '@phosphor-icons/react/dist/ssr/Hamburger'
export { IceCream } from '@phosphor-icons/react/dist/ssr/IceCream'
export { Knife } from '@phosphor-icons/react/dist/ssr/Knife'
export { Pepper } from '@phosphor-icons/react/dist/ssr/Pepper'
export { Pizza } from '@phosphor-icons/react/dist/ssr/Pizza'
export { Plant } from '@phosphor-icons/react/dist/ssr/Plant'
export { Shrimp } from '@phosphor-icons/react/dist/ssr/Shrimp'
export { Stack } from '@phosphor-icons/react/dist/ssr/Stack'
export { UsersFour } from '@phosphor-icons/react/dist/ssr/UsersFour'

// Intelligence feature icons (direct Phosphor names)
export { TrendUp } from '@phosphor-icons/react/dist/ssr/TrendUp'
export { TrendDown } from '@phosphor-icons/react/dist/ssr/TrendDown'
export { CurrencyDollar } from '@phosphor-icons/react/dist/ssr/CurrencyDollar'
export { Pulse } from '@phosphor-icons/react/dist/ssr/Pulse'
export { ClipboardText } from '@phosphor-icons/react/dist/ssr/ClipboardText'
export { Envelope } from '@phosphor-icons/react/dist/ssr/Envelope'
export { ChatCircle } from '@phosphor-icons/react/dist/ssr/ChatCircle'
export { Note } from '@phosphor-icons/react/dist/ssr/Note'

// Prep timeline icons (not in SSR barrel export, imported directly)
export { Snowflake } from '@phosphor-icons/react/dist/ssr/Snowflake'
export { Key } from '@phosphor-icons/react/dist/ssr/Key'

// Event Intelligence Panel icons
export { CloudSun } from '@phosphor-icons/react/dist/ssr/CloudSun'
export { Train } from '@phosphor-icons/react/dist/ssr/Train'
export { Wind } from '@phosphor-icons/react/dist/ssr/Wind'
export { Bed } from '@phosphor-icons/react/dist/ssr/Bed'
