// Phosphor Icons - mapped from former Lucide icon names for drop-in compatibility
// ChefFlow uses Phosphor (https://phosphoricons.com/) for a distinctive visual identity
// Import from '@/components/ui/icons' instead of 'lucide-react'

export type { Icon as LucideIcon, IconProps } from '@phosphor-icons/react'

// Re-export Phosphor icons under their Lucide-equivalent names
// This allows a single import path change across the entire codebase

export { Pulse as Activity } from '@phosphor-icons/react/ssr'
export { WarningCircle as AlertCircle } from '@phosphor-icons/react/ssr'
export { WarningOctagon as AlertOctagon } from '@phosphor-icons/react/ssr'
export { Warning as AlertTriangle } from '@phosphor-icons/react/ssr'
export { AppleLogo as Apple } from '@phosphor-icons/react/ssr'
export { Archive } from '@phosphor-icons/react/ssr'
export { ArrowDown } from '@phosphor-icons/react/ssr'
export { ArrowDownRight } from '@phosphor-icons/react/ssr'
export { ArrowLeft } from '@phosphor-icons/react/ssr'
export { ArrowRight } from '@phosphor-icons/react/ssr'
export { ArrowUp } from '@phosphor-icons/react/ssr'
export { ArrowsDownUp as ArrowUpDown } from '@phosphor-icons/react/ssr'
export { ArrowUpRight } from '@phosphor-icons/react/ssr'
export { Medal as Award } from '@phosphor-icons/react/ssr'
export { Money as Banknote } from '@phosphor-icons/react/ssr'
export { ChartBar as BarChart2 } from '@phosphor-icons/react/ssr'
export { ChartBar as BarChart3 } from '@phosphor-icons/react/ssr'
export { Bell } from '@phosphor-icons/react/ssr'
export { BellSlash as BellOff } from '@phosphor-icons/react/ssr'
export { BellRinging as BellRing } from '@phosphor-icons/react/ssr'
export { TextB as Bold } from '@phosphor-icons/react/ssr'
export { BookBookmark as BookMarked } from '@phosphor-icons/react/ssr'
export { BookOpen } from '@phosphor-icons/react/ssr'
export { Notebook as BookTemplate } from '@phosphor-icons/react/ssr'
export { Bookmark } from '@phosphor-icons/react/ssr'
export { Robot as Bot } from '@phosphor-icons/react/ssr'
export { BracketsCurly as Braces } from '@phosphor-icons/react/ssr'
export { Brain } from '@phosphor-icons/react/ssr'
export { Buildings as Building2 } from '@phosphor-icons/react/ssr'
export { Calculator } from '@phosphor-icons/react/ssr'
export { Calendar } from '@phosphor-icons/react/ssr'
export { CalendarCheck } from '@phosphor-icons/react/ssr'
export { CalendarDots as CalendarDays } from '@phosphor-icons/react/ssr'
export { CalendarPlus } from '@phosphor-icons/react/ssr'
export { CalendarDots as CalendarRange } from '@phosphor-icons/react/ssr'
export { Camera } from '@phosphor-icons/react/ssr'
export { Car } from '@phosphor-icons/react/ssr'
export { Check } from '@phosphor-icons/react/ssr'
export { Checks as CheckCheck } from '@phosphor-icons/react/ssr'
export { CheckCircle } from '@phosphor-icons/react/ssr'
export { CheckCircle as CheckCircle2 } from '@phosphor-icons/react/ssr'
export { CheckSquare } from '@phosphor-icons/react/ssr'
export { ChefHat } from '@phosphor-icons/react/ssr'
export { CaretDown as ChevronDown } from '@phosphor-icons/react/ssr'
export { CaretLeft as ChevronLeft } from '@phosphor-icons/react/ssr'
export { CaretRight as ChevronRight } from '@phosphor-icons/react/ssr'
export { CaretUp as ChevronUp } from '@phosphor-icons/react/ssr'
export { CaretDoubleDown as ChevronsDownUp } from '@phosphor-icons/react/ssr'
export { CaretUpDown as ChevronsUpDown } from '@phosphor-icons/react/ssr'
export { GoogleChromeLogo as Chrome } from '@phosphor-icons/react/ssr'
export { Circle } from '@phosphor-icons/react/ssr'
export { ClipboardText as ClipboardCheck } from '@phosphor-icons/react/ssr'
export { ClipboardText as ClipboardList } from '@phosphor-icons/react/ssr'
export { Clock } from '@phosphor-icons/react/ssr'
export { Clock as Clock3 } from '@phosphor-icons/react/ssr'
export { CloudArrowUp as CloudUpload } from '@phosphor-icons/react/ssr'
export { CodeBlock as Code2 } from '@phosphor-icons/react/ssr'
export { Compass } from '@phosphor-icons/react/ssr'
export { AddressBook as Contact } from '@phosphor-icons/react/ssr'
export { Copy } from '@phosphor-icons/react/ssr'
export { Cpu } from '@phosphor-icons/react/ssr'
export { CreditCard } from '@phosphor-icons/react/ssr'
export { Crosshair } from '@phosphor-icons/react/ssr'
export { Crown } from '@phosphor-icons/react/ssr'
export { CurrencyDollar as DollarSign } from '@phosphor-icons/react/ssr'
export { Download } from '@phosphor-icons/react/ssr'
export { PencilSimple as Edit2 } from '@phosphor-icons/react/ssr'
export { PencilLine as Edit3 } from '@phosphor-icons/react/ssr'
export { ArrowSquareOut as ExternalLink } from '@phosphor-icons/react/ssr'
export { Eye } from '@phosphor-icons/react/ssr'
export { EyeSlash as EyeOff } from '@phosphor-icons/react/ssr'
export { File } from '@phosphor-icons/react/ssr'
export { FileText as FileCheck } from '@phosphor-icons/react/ssr'
export { FileXls as FileSpreadsheet } from '@phosphor-icons/react/ssr'
export { FileText } from '@phosphor-icons/react/ssr'
export { FilmStrip as Film } from '@phosphor-icons/react/ssr'
export { Funnel as Filter } from '@phosphor-icons/react/ssr'
export { Fire as Flame } from '@phosphor-icons/react/ssr'
export { Flask as FlaskConical } from '@phosphor-icons/react/ssr'
export { CrosshairSimple as Focus } from '@phosphor-icons/react/ssr'
export { GameController as Gamepad2 } from '@phosphor-icons/react/ssr'
export { Ghost } from '@phosphor-icons/react/ssr'
export { Gift } from '@phosphor-icons/react/ssr'
export { GitBranch } from '@phosphor-icons/react/ssr'
export { Globe } from '@phosphor-icons/react/ssr'
export { GridNine as Grid3X3 } from '@phosphor-icons/react/ssr'
export { DotsSixVertical as GripVertical } from '@phosphor-icons/react/ssr'
export { Handshake } from '@phosphor-icons/react/ssr'
export { Hash } from '@phosphor-icons/react/ssr'
export { Heart } from '@phosphor-icons/react/ssr'
export { HandHeart as HeartHandshake } from '@phosphor-icons/react/ssr'
export { ClockCounterClockwise as History } from '@phosphor-icons/react/ssr'
export { House as Home } from '@phosphor-icons/react/ssr'
export { Image } from '@phosphor-icons/react/ssr'
export { CameraPlus as ImagePlus } from '@phosphor-icons/react/ssr'
export { Tray as Inbox } from '@phosphor-icons/react/ssr'
export { Info } from '@phosphor-icons/react/ssr'
export { TextItalic as Italic } from '@phosphor-icons/react/ssr'
export { Bank as Landmark } from '@phosphor-icons/react/ssr'
export { Stack as Layers } from '@phosphor-icons/react/ssr'
export { SquaresFour as LayoutDashboard } from '@phosphor-icons/react/ssr'
export { GridFour as LayoutGrid } from '@phosphor-icons/react/ssr'
export { Lightbulb } from '@phosphor-icons/react/ssr'
export { Link } from '@phosphor-icons/react/ssr'
export { LinkSimple as Link2 } from '@phosphor-icons/react/ssr'
export { List } from '@phosphor-icons/react/ssr'
export { ListChecks } from '@phosphor-icons/react/ssr'
export { ListNumbers as ListOrdered } from '@phosphor-icons/react/ssr'
export { SpinnerGap as Loader2 } from '@phosphor-icons/react/ssr'
export { Lock } from '@phosphor-icons/react/ssr'
export { SignOut as LogOut } from '@phosphor-icons/react/ssr'
export { Envelope as Mail } from '@phosphor-icons/react/ssr'
export { EnvelopeOpen as MailPlus } from '@phosphor-icons/react/ssr'
export { MapPin } from '@phosphor-icons/react/ssr'
export { ArrowsOut as Maximize2 } from '@phosphor-icons/react/ssr'
export { Megaphone } from '@phosphor-icons/react/ssr'
export { List as Menu } from '@phosphor-icons/react/ssr'
export { GitMerge as Merge } from '@phosphor-icons/react/ssr'
export { ChatCircle as MessageCircle } from '@phosphor-icons/react/ssr'
export { Chat as MessageSquare } from '@phosphor-icons/react/ssr'
export { ChatCenteredText as MessageSquareWarning } from '@phosphor-icons/react/ssr'
export { Chats as MessagesSquare } from '@phosphor-icons/react/ssr'
export { ArrowsIn as Minimize2 } from '@phosphor-icons/react/ssr'
export { Minus } from '@phosphor-icons/react/ssr'
export { MinusCircle } from '@phosphor-icons/react/ssr'
export { Monitor } from '@phosphor-icons/react/ssr'
export { Moon } from '@phosphor-icons/react/ssr'
export { Cursor as MousePointer } from '@phosphor-icons/react/ssr'
export { CursorClick as MousePointerClick } from '@phosphor-icons/react/ssr'
export { ArrowsOutCardinal as Move } from '@phosphor-icons/react/ssr'
export { Package } from '@phosphor-icons/react/ssr'
export { Palette } from '@phosphor-icons/react/ssr'
export { Paperclip } from '@phosphor-icons/react/ssr'
export { Pause } from '@phosphor-icons/react/ssr'
export { Pencil } from '@phosphor-icons/react/ssr'
export { Percent } from '@phosphor-icons/react/ssr'
export { Phone } from '@phosphor-icons/react/ssr'
export { PhoneCall } from '@phosphor-icons/react/ssr'
export { ChartPie as PieChart } from '@phosphor-icons/react/ssr'
export { PiggyBank } from '@phosphor-icons/react/ssr'
export { PushPin as Pin } from '@phosphor-icons/react/ssr'
export { PushPinSlash as PinOff } from '@phosphor-icons/react/ssr'
export { Play } from '@phosphor-icons/react/ssr'
export { Plus } from '@phosphor-icons/react/ssr'
export { PlusCircle } from '@phosphor-icons/react/ssr'
export { Power } from '@phosphor-icons/react/ssr'
export { Presentation } from '@phosphor-icons/react/ssr'
export { Printer } from '@phosphor-icons/react/ssr'
export { Quotes as Quote } from '@phosphor-icons/react/ssr'
export { Radio } from '@phosphor-icons/react/ssr'
export { Receipt } from '@phosphor-icons/react/ssr'
export { Recycle } from '@phosphor-icons/react/ssr'
export { ArrowClockwise as RefreshCw } from '@phosphor-icons/react/ssr'
export { Repeat } from '@phosphor-icons/react/ssr'
export { ArrowCounterClockwise as RotateCcw } from '@phosphor-icons/react/ssr'
export { FloppyDisk as Save } from '@phosphor-icons/react/ssr'
export { Scroll as ScrollText } from '@phosphor-icons/react/ssr'
export { MagnifyingGlass as Search } from '@phosphor-icons/react/ssr'
export { PaperPlaneTilt as Send } from '@phosphor-icons/react/ssr'
export { HardDrives as Server } from '@phosphor-icons/react/ssr'
export { Gear as Settings } from '@phosphor-icons/react/ssr'
export { GearSix as Settings2 } from '@phosphor-icons/react/ssr'
export { ShareNetwork as Share2 } from '@phosphor-icons/react/ssr'
export { Shield } from '@phosphor-icons/react/ssr'
export { ShieldWarning as ShieldAlert } from '@phosphor-icons/react/ssr'
export { ShieldCheck } from '@phosphor-icons/react/ssr'
export { ShieldSlash as ShieldX } from '@phosphor-icons/react/ssr'
export { ShoppingCart } from '@phosphor-icons/react/ssr'
export { SkipForward } from '@phosphor-icons/react/ssr'
export { DeviceMobile as Smartphone } from '@phosphor-icons/react/ssr'
export { Sparkle as Sparkles } from '@phosphor-icons/react/ssr'
export { Square } from '@phosphor-icons/react/ssr'
export { Star } from '@phosphor-icons/react/ssr'
export { Stethoscope } from '@phosphor-icons/react/ssr'
export { Note as StickyNote } from '@phosphor-icons/react/ssr'
export { Storefront as Store } from '@phosphor-icons/react/ssr'
export { Sun } from '@phosphor-icons/react/ssr'
export { DeviceTablet as Tablet } from '@phosphor-icons/react/ssr'
export { Tag } from '@phosphor-icons/react/ssr'
export { Target } from '@phosphor-icons/react/ssr'
export { Thermometer } from '@phosphor-icons/react/ssr'
export { ToggleLeft } from '@phosphor-icons/react/ssr'
export { Trash as Trash2 } from '@phosphor-icons/react/ssr'
export { TrendDown as TrendingDown } from '@phosphor-icons/react/ssr'
export { TrendUp as TrendingUp } from '@phosphor-icons/react/ssr'
export { Trophy } from '@phosphor-icons/react/ssr'
export { Truck } from '@phosphor-icons/react/ssr'
export { LinkBreak as Unlink } from '@phosphor-icons/react/ssr'
export { LockOpen as Unlock } from '@phosphor-icons/react/ssr'
export { Upload } from '@phosphor-icons/react/ssr'
export { User } from '@phosphor-icons/react/ssr'
export { UserCheck } from '@phosphor-icons/react/ssr'
export { UserCircle } from '@phosphor-icons/react/ssr'
export { UserMinus } from '@phosphor-icons/react/ssr'
export { UserPlus } from '@phosphor-icons/react/ssr'
export { Users } from '@phosphor-icons/react/ssr'
export { UsersThree as Users2 } from '@phosphor-icons/react/ssr'
export { UsersThree as UsersRound } from '@phosphor-icons/react/ssr'
export { ForkKnife as Utensils } from '@phosphor-icons/react/ssr'
export { ForkKnife as UtensilsCrossed } from '@phosphor-icons/react/ssr'
export { Wallet } from '@phosphor-icons/react/ssr'
export { Warehouse } from '@phosphor-icons/react/ssr'
export { WifiHigh as Wifi } from '@phosphor-icons/react/ssr'
export { WifiSlash as WifiOff } from '@phosphor-icons/react/ssr'
export { Wine } from '@phosphor-icons/react/ssr'
export { Wrench } from '@phosphor-icons/react/ssr'
export { X } from '@phosphor-icons/react/ssr'
export { XCircle } from '@phosphor-icons/react/ssr'
export { Lightning as Zap } from '@phosphor-icons/react/ssr'

// Distinct icons for navigation differentiation (batch 3 - icon overhaul)
export { ChatTeardropText } from '@phosphor-icons/react/ssr' // Inquiries (not Tray/Inbox)
export { Funnel } from '@phosphor-icons/react/ssr' // Sales pipeline
export { IdentificationBadge } from '@phosphor-icons/react/ssr' // Staff
export { PenNib } from '@phosphor-icons/react/ssr' // Content creation
export { Notepad } from '@phosphor-icons/react/ssr' // Station clipboards
export { Toolbox } from '@phosphor-icons/react/ssr' // Tools group
export { ChartLineUp } from '@phosphor-icons/react/ssr' // Client insights / trends
export { Coins } from '@phosphor-icons/react/ssr' // Expenses
export { Invoice } from '@phosphor-icons/react/ssr' // Invoices
export { Notebook as NotebookIcon } from '@phosphor-icons/react/ssr' // Ledger
export { CurrencyCircleDollar } from '@phosphor-icons/react/ssr' // Payments
export { Scales } from '@phosphor-icons/react/ssr' // Reconciliation
export { SlidersHorizontal as Sliders } from '@phosphor-icons/react/ssr' // Preferences
export { Strategy } from '@phosphor-icons/react/ssr' // Priority queue
export { ClipboardText as ClipboardTextIcon } from '@phosphor-icons/react/ssr' // Inventory counts
export { MagnifyingGlassPlus } from '@phosphor-icons/react/ssr' // Audits
export { Exam } from '@phosphor-icons/react/ssr' // Event reviews / AAR
export { WifiHigh } from '@phosphor-icons/react/ssr' // Live presence
export { Broadcast } from '@phosphor-icons/react/ssr' // Command center
export { FlagBanner } from '@phosphor-icons/react/ssr' // Feature flags
export { ChatDots } from '@phosphor-icons/react/ssr' // Admin conversations
export { Megaphone as MegaphoneIcon } from '@phosphor-icons/react/ssr' // Marketing group (re-export)
export { Chalkboard } from '@phosphor-icons/react/ssr' // Culinary board
export { Flower } from '@phosphor-icons/react/ssr' // Seasonal palettes
export { TreeStructure } from '@phosphor-icons/react/ssr' // Directory
export { HandArrowDown } from '@phosphor-icons/react/ssr' // Procurement
export { SealCheck } from '@phosphor-icons/react/ssr' // Certifications

// Additional icons used across the codebase (batch 2)
export { ArrowsLeftRight as ArrowRightLeft } from '@phosphor-icons/react/ssr'
export { ArrowCircleRight as ArrowRightCircle } from '@phosphor-icons/react/ssr'
export { CurrencyDollar as BadgeDollarSign } from '@phosphor-icons/react/ssr'
export { BookmarkSimple as BookmarkCheck } from '@phosphor-icons/react/ssr'
export { Cake } from '@phosphor-icons/react/ssr'
export { CalendarDots as CalendarClock } from '@phosphor-icons/react/ssr'
export { CaretDoubleLeft as ChevronsLeft } from '@phosphor-icons/react/ssr'
export { CaretDoubleRight as ChevronsRight } from '@phosphor-icons/react/ssr'
export { RadioButton as CircleDot } from '@phosphor-icons/react/ssr'
export { Code } from '@phosphor-icons/react/ssr'
export { Database } from '@phosphor-icons/react/ssr'
export { Barbell as Dumbbell } from '@phosphor-icons/react/ssr'
export { FacebookLogo as Facebook } from '@phosphor-icons/react/ssr'
export { NotePencil as FileEdit } from '@phosphor-icons/react/ssr'
export { FileCode as FileJson } from '@phosphor-icons/react/ssr'
export { FileX } from '@phosphor-icons/react/ssr'
export { FolderPlus } from '@phosphor-icons/react/ssr'
export { Footprints } from '@phosphor-icons/react/ssr'
export { GraduationCap } from '@phosphor-icons/react/ssr'
export { HandCoins } from '@phosphor-icons/react/ssr'
export { HandHeart } from '@phosphor-icons/react/ssr'
export { HardDrive } from '@phosphor-icons/react/ssr'
export { Headphones } from '@phosphor-icons/react/ssr'
export { Question as HelpCircle } from '@phosphor-icons/react/ssr'
export { InstagramLogo as Instagram } from '@phosphor-icons/react/ssr'
export { Kanban } from '@phosphor-icons/react/ssr'
export { Keyboard } from '@phosphor-icons/react/ssr'
export { Layout } from '@phosphor-icons/react/ssr'
export { Leaf } from '@phosphor-icons/react/ssr'
export { Funnel as ListFilter } from '@phosphor-icons/react/ssr'
export { EnvelopeOpen as MailOpen } from '@phosphor-icons/react/ssr'
export { ChatCircleDots as MessageSquareDashed } from '@phosphor-icons/react/ssr'
export { Microphone as Mic } from '@phosphor-icons/react/ssr'
export { MicrophoneSlash as MicOff } from '@phosphor-icons/react/ssr'
export { DotsThree as MoreHorizontal } from '@phosphor-icons/react/ssr'
export { MusicNote as Music } from '@phosphor-icons/react/ssr'
export { Newspaper } from '@phosphor-icons/react/ssr'
export { NotePencil as NotebookPen } from '@phosphor-icons/react/ssr'
export { Package as PackageCheck } from '@phosphor-icons/react/ssr'
export { PencilLine as PenLine } from '@phosphor-icons/react/ssr'
export { AirplaneTilt as Plane } from '@phosphor-icons/react/ssr'
export { Plug } from '@phosphor-icons/react/ssr'
export { Repeat as Repeat2 } from '@phosphor-icons/react/ssr'
export { Rss } from '@phosphor-icons/react/ssr'
export { Scales as Scale } from '@phosphor-icons/react/ssr'
export { Barcode as ScanLine } from '@phosphor-icons/react/ssr'
export { ShieldSlash as ShieldOff } from '@phosphor-icons/react/ssr'
export { Shuffle } from '@phosphor-icons/react/ssr'
export { SlidersHorizontal } from '@phosphor-icons/react/ssr'
export { BowlSteam as Soup } from '@phosphor-icons/react/ssr'
export { SunHorizon as Sunset } from '@phosphor-icons/react/ssr'
export { ThumbsDown } from '@phosphor-icons/react/ssr'
export { ThumbsUp } from '@phosphor-icons/react/ssr'
export { Timer } from '@phosphor-icons/react/ssr'
export { ToggleRight } from '@phosphor-icons/react/ssr'
export { SpeakerHigh as Volume2 } from '@phosphor-icons/react/ssr'
export { SpeakerX as VolumeX } from '@phosphor-icons/react/ssr'
