import 'server-only'

import type { PlannedTask } from '@/lib/ai/command-types'
import {
  executeCancellationImpact,
  executeClientMilestones,
  executeContingencyPlanning,
  executeContractGeneration,
  executeDietaryCheck as executeIngredientDietaryCheck,
  executeEquipmentList,
  executeEquipmentMaintenance,
  executeFoodSafetyQuery,
  executeGoalsDashboard,
  executeGroceryConsolidation,
  executeIngredientSubstitution,
  executeMorningBriefing,
  executeMultiEventComparison,
  executePnLReport,
  executePostEventSequence,
  executePricingAnalysis,
  executeReEngagementScoring,
  executeRevenueForecast,
  executeSeasonalProduce,
  executeTaxSummary,
  executeUtilizationAnalysis,
  executeVendorsList,
  executeAcquisitionFunnel,
} from '@/lib/ai/remy-intelligence-actions'
import {
  executeBenchmarks,
  executeBusinessHealthScore,
  executeCapacityCheck,
  executeCashFlowForecast,
  executeCertificationStatus,
  executeClientBirthdays,
  executeClientChurnRisk,
  executeClientCooling,
  executeClientLTVTrajectory,
  executeClientMenuHistory,
  executeClientNDAStatus,
  executeClientNextBestActions,
  executeClientPaymentPlans,
  executeClientReferralHealth,
  executeClientSpending,
  executeCommerceSalesSummary,
  executeContractorSummary,
  executeCostTrends,
  executeDemandForecast,
  executeDisputes,
  executeDocumentSnapshots,
  executeEquipmentRentals,
  executeEventCountdown,
  executeEventDebrief,
  executeEventDietaryConflicts,
  executeGoalCheckIns,
  executeGoalHistory,
  executeGmailSenderReputation,
  executeGuestList,
  executeInquiryFollowUps,
  executeInquiryLikelihood,
  executeInventoryStatus,
  executeInvoiceLookup,
  executeLoyaltyGiftCards,
  executeLoyaltyRedemptions,
  executeMarketingCampaigns,
  executeMenuDishIndex,
  executeMenuFoodCost,
  executeMenuShowcase,
  executeMileageSummary,
  executeNewsletterStatus,
  executeNotificationPreferences,
  executePaymentPlanLookup,
  executePayrollSummary,
  executePipelineAnalytics,
  executePrepBlocks,
  executePricingSuggestions,
  executeProtectedTime,
  executePurchaseOrders,
  executeQuoteLossAnalysis,
  executeRecipeAllergens,
  executeRecipeNutrition,
  executeRecipeProductionLogs,
  executeRecurringInvoices,
  executeReferralAnalytics,
  executeResponseTimeMetrics,
  executeRevenueByServiceType,
  executeReviewsSummary,
  executeSchedulingGaps,
  executeStaffAvailability,
  executeStaffBriefing,
  executeStaffClockSummary,
  executeStaffLaborDashboard,
  executeStaffPerformance,
  executeTaxPackage,
  executeTipSummary,
  executeVendorInvoices,
  executeVendorPaymentAging,
  executeVendorPriceInsights,
  executeYearOverYear,
} from '@/lib/ai/remy-intelligence-actions-2'
import {
  executeAARForgottenItems,
  executeAARList,
  executeAARStats,
  executeActivityFeed,
  executeCircleEvents,
  executeCirclesList,
  executeCirclesUnread,
  executeCommerceDailyReport,
  executeCommerceInventoryLow,
  executeCommerceProductReport,
  executeCommerceProducts,
  executeCommerceRecentSales,
  executeDailyPlan,
  executeDailyPlanStats,
  executeEngagementStats,
  executeEventsWithoutAAR,
  executeOpsLog,
  executePartnerEvents,
  executePartnerPerformance,
  executePartnersList,
  executePriorityQueue,
  executeRateCard,
  executeStationDetail,
  executeStationsList,
  executeTasksByDate,
  executeTasksList,
  executeTasksOverdue,
  executeTestimonialsList,
  executeTestimonialsPending,
  executeTravelPlan,
  executeTravelUpcoming,
  executeWaitlistStatus,
  executeWasteLog,
} from '@/lib/ai/remy-intelligence-actions-3'

type ReadTaskContext = {
  tenantId: string
}

type ReadTaskExecutor = (task: PlannedTask, ctx: ReadTaskContext) => Promise<unknown>

const REMY_READ_TASK_EXECUTORS: Record<string, ReadTaskExecutor> = {
  'contract.generate': (task) => executeContractGeneration(task.inputs),
  'contingency.plan': (task) => executeContingencyPlanning(task.inputs),
  'seasonal.produce': () => executeSeasonalProduce(),
  'grocery.consolidate': (task) => executeGroceryConsolidation(task.inputs),
  'finance.forecast': (_task, ctx) => executeRevenueForecast(ctx.tenantId),
  'finance.pnl': (task, ctx) => executePnLReport(ctx.tenantId, task.inputs),
  'finance.tax_summary': (task, ctx) => executeTaxSummary(ctx.tenantId, task.inputs),
  'finance.pricing': (_task, ctx) => executePricingAnalysis(ctx.tenantId),
  'capacity.utilization': (task, ctx) => executeUtilizationAnalysis(ctx.tenantId, task.inputs),
  'relationship.milestones': (_task, ctx) => executeClientMilestones(ctx.tenantId),
  'relationship.reengagement': (_task, ctx) => executeReEngagementScoring(ctx.tenantId),
  'relationship.acquisition': (_task, ctx) => executeAcquisitionFunnel(ctx.tenantId),
  'goals.dashboard': () => executeGoalsDashboard(),
  'equipment.list': () => executeEquipmentList(),
  'equipment.maintenance': () => executeEquipmentMaintenance(),
  'vendors.list': (_task, ctx) => executeVendorsList(ctx.tenantId),
  'analytics.compare_events': (task, ctx) => executeMultiEventComparison(task.inputs, ctx.tenantId),
  'briefing.morning': (_task, ctx) => executeMorningBriefing(ctx.tenantId),
  'workflow.cancellation_impact': (task, ctx) =>
    executeCancellationImpact(task.inputs, ctx.tenantId),
  'workflow.post_event': (task) => executePostEventSequence(task.inputs),
  'ops.ingredient_sub': (task) => executeIngredientSubstitution(task.inputs),
  'food.safety': (task) => executeFoodSafetyQuery(task.inputs),
  'food.dietary_ingredients': (task) => executeIngredientDietaryCheck(task.inputs),

  'client.spending': () => executeClientSpending(),
  'client.churn_risk': () => executeClientChurnRisk(),
  'client.birthdays': () => executeClientBirthdays(),
  'client.next_best_action': () => executeClientNextBestActions(),
  'client.cooling': () => executeClientCooling(),
  'client.ltv_trajectory': (task) => executeClientLTVTrajectory(task.inputs),
  'client.menu_history': (task) => executeClientMenuHistory(task.inputs),
  'client.referral_health': () => executeClientReferralHealth(),
  'client.nda_status': () => executeClientNDAStatus(),
  'client.payment_plans': (task) => executeClientPaymentPlans(task.inputs),
  'event.dietary_conflicts': (task) => executeEventDietaryConflicts(task.inputs),
  'event.debrief': (task) => executeEventDebrief(task.inputs),
  'event.countdown': (task) => executeEventCountdown(task.inputs),
  'event.invoice': (task) => executeInvoiceLookup(task.inputs),
  'inquiry.follow_ups': () => executeInquiryFollowUps(),
  'inquiry.likelihood': () => executeInquiryLikelihood(),
  'menu.food_cost': () => executeMenuFoodCost(),
  'menu.dish_index': () => executeMenuDishIndex(),
  'menu.showcase': () => executeMenuShowcase(),
  'recipe.allergens': () => executeRecipeAllergens(),
  'recipe.nutrition': (task) => executeRecipeNutrition(task.inputs),
  'recipe.production_logs': () => executeRecipeProductionLogs(),
  'finance.cash_flow': () => executeCashFlowForecast(),
  'finance.mileage': () => executeMileageSummary(),
  'finance.tips': () => executeTipSummary(),
  'finance.contractors': () => executeContractorSummary(),
  'finance.disputes': () => executeDisputes(),
  'finance.payment_plan': (task) => executePaymentPlanLookup(task.inputs),
  'finance.recurring_invoices': () => executeRecurringInvoices(),
  'finance.tax_package': () => executeTaxPackage(),
  'finance.payroll': () => executePayrollSummary(),
  'vendor.invoices': (task) => executeVendorInvoices(task.inputs),
  'vendor.price_insights': () => executeVendorPriceInsights(),
  'vendor.payment_aging': () => executeVendorPaymentAging(),
  'equipment.rentals': (task) => executeEquipmentRentals(task.inputs),
  'staff.availability': (task) => executeStaffAvailability(task.inputs),
  'staff.briefing': (task) => executeStaffBriefing(task.inputs),
  'staff.clock_summary': (task) => executeStaffClockSummary(task.inputs),
  'staff.performance': () => executeStaffPerformance(),
  'staff.labor_dashboard': (task) => executeStaffLaborDashboard(task.inputs),
  'scheduling.capacity': (task) => executeCapacityCheck(task.inputs),
  'scheduling.prep_blocks': (task) => executePrepBlocks(task.inputs),
  'scheduling.protected_time': () => executeProtectedTime(),
  'scheduling.gaps': () => executeSchedulingGaps(),
  'analytics.pipeline': () => executePipelineAnalytics(),
  'analytics.yoy': () => executeYearOverYear(),
  'analytics.demand_forecast': () => executeDemandForecast(),
  'analytics.benchmarks': () => executeBenchmarks(),
  'analytics.pricing_suggestions': (task) => executePricingSuggestions(task.inputs),
  'analytics.response_time': () => executeResponseTimeMetrics(),
  'analytics.cost_trends': () => executeCostTrends(),
  'analytics.referrals': () => executeReferralAnalytics(),
  'analytics.quote_loss': () => executeQuoteLossAnalysis(),
  'analytics.service_mix': () => executeRevenueByServiceType(),
  'goals.history': (task) => executeGoalHistory(task.inputs),
  'goals.check_ins': (task) => executeGoalCheckIns(task.inputs),
  'protection.certifications': () => executeCertificationStatus(),
  'protection.business_health': () => executeBusinessHealthScore(),
  'loyalty.redemptions': () => executeLoyaltyRedemptions(),
  'loyalty.gift_cards': () => executeLoyaltyGiftCards(),
  'inventory.status': () => executeInventoryStatus(),
  'inventory.purchase_orders': () => executePurchaseOrders(),
  'commerce.sales_summary': () => executeCommerceSalesSummary(),
  'guest.list': (task) => executeGuestList(task.inputs),
  'marketing.campaigns': () => executeMarketingCampaigns(),
  'marketing.newsletters': () => executeNewsletterStatus(),
  'reviews.summary': () => executeReviewsSummary(),
  'gmail.sender_reputation': () => executeGmailSenderReputation(),
  'notifications.preferences': () => executeNotificationPreferences(),
  'document.snapshots': (task) => executeDocumentSnapshots(task.inputs),

  'circles.list': () => executeCirclesList(),
  'circles.unread': () => executeCirclesUnread(),
  'circles.events': (task) => executeCircleEvents(task.inputs),
  'circles.discover': async () => ({
    route: '/hub/circles',
    navigated: true,
    message:
      'Opening community circles discovery page. You can browse, search, and join public circles.',
  }),
  'rate_card.summary': () => executeRateCard(),
  'tasks.list': (task) => executeTasksList(task.inputs),
  'tasks.by_date': (task) => executeTasksByDate(task.inputs),
  'tasks.overdue': () => executeTasksOverdue(),
  'travel.plan': (task) => executeTravelPlan(task.inputs),
  'travel.upcoming': () => executeTravelUpcoming(),
  'commerce.products': () => executeCommerceProducts(),
  'commerce.recent_sales': () => executeCommerceRecentSales(),
  'commerce.daily_report': () => executeCommerceDailyReport(),
  'commerce.product_report': () => executeCommerceProductReport(),
  'commerce.inventory_low': () => executeCommerceInventoryLow(),
  'daily.plan': () => executeDailyPlan(),
  'daily.stats': () => executeDailyPlanStats(),
  'queue.status': () => executePriorityQueue(),
  'stations.list': () => executeStationsList(),
  'stations.detail': (task) => executeStationDetail(task.inputs),
  'stations.ops_log': (task) => executeOpsLog(task.inputs),
  'stations.waste_log': () => executeWasteLog(),
  'testimonials.list': () => executeTestimonialsList(),
  'testimonials.pending': () => executeTestimonialsPending(),
  'partners.list': () => executePartnersList(),
  'partners.events': (task) => executePartnerEvents(task.inputs),
  'partners.performance': () => executePartnerPerformance(),
  'activity.feed': () => executeActivityFeed(),
  'activity.engagement': () => executeEngagementStats(),
  'aar.list': () => executeAARList(),
  'aar.stats': () => executeAARStats(),
  'aar.events_without': () => executeEventsWithoutAAR(),
  'aar.forgotten_items': () => executeAARForgottenItems(),
  'waitlist.status': () => executeWaitlistStatus(),
}

export async function executeRegisteredRemyReadTask(
  task: PlannedTask,
  ctx: ReadTaskContext
): Promise<{ handled: true; data: unknown } | { handled: false }> {
  const executor = REMY_READ_TASK_EXECUTORS[task.taskType]
  if (!executor) return { handled: false }
  return { handled: true, data: await executor(task, ctx) }
}
