import {
  pgTable,
  pgSchema,
  uuid,
  varchar,
  timestamp,
  jsonb,
  boolean,
  smallint,
  text,
} from 'drizzle-orm/pg-core'

// Supabase stores users in the 'auth' schema, not 'public'
const authSchema = pgSchema('auth')

export const authUsers = authSchema.table('users', {
  instanceId: uuid('instance_id'),
  id: uuid('id').primaryKey().notNull(),
  aud: varchar('aud', { length: 255 }),
  role: varchar('role', { length: 255 }),
  email: varchar('email', { length: 255 }),
  encryptedPassword: varchar('encrypted_password', { length: 255 }),
  emailConfirmedAt: timestamp('email_confirmed_at', { withTimezone: true }),
  invitedAt: timestamp('invited_at', { withTimezone: true }),
  confirmationToken: varchar('confirmation_token', { length: 255 }),
  confirmationSentAt: timestamp('confirmation_sent_at', { withTimezone: true }),
  recoveryToken: varchar('recovery_token', { length: 255 }),
  recoverySentAt: timestamp('recovery_sent_at', { withTimezone: true }),
  emailChangeTokenNew: varchar('email_change_token_new', { length: 255 }),
  emailChange: varchar('email_change', { length: 255 }),
  emailChangeSentAt: timestamp('email_change_sent_at', { withTimezone: true }),
  lastSignInAt: timestamp('last_sign_in_at', { withTimezone: true }),
  rawAppMetaData: jsonb('raw_app_meta_data'),
  rawUserMetaData: jsonb('raw_user_meta_data'),
  isSuperAdmin: boolean('is_super_admin'),
  createdAt: timestamp('created_at', { withTimezone: true }),
  updatedAt: timestamp('updated_at', { withTimezone: true }),
  phone: text('phone'),
  phoneConfirmedAt: timestamp('phone_confirmed_at', { withTimezone: true }),
  phoneChange: text('phone_change'),
  phoneChangeToken: varchar('phone_change_token', { length: 255 }),
  phoneChangeSentAt: timestamp('phone_change_sent_at', { withTimezone: true }),
  emailChangeTokenCurrent: varchar('email_change_token_current', { length: 255 }),
  emailChangeConfirmStatus: smallint('email_change_confirm_status'),
  bannedUntil: timestamp('banned_until', { withTimezone: true }),
  reauthenticationToken: varchar('reauthentication_token', { length: 255 }),
  reauthenticationSentAt: timestamp('reauthentication_sent_at', { withTimezone: true }),
  isSsoUser: boolean('is_sso_user').notNull().default(false),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
  isAnonymous: boolean('is_anonymous').notNull().default(false),
})
