-- Remy Proactive Alerts Table
-- Stores deterministic alerts generated by the rule engine (remy-proactive-alerts.ts).
-- Alerts are deduped (24h window), dismissable, and actionable.

CREATE TABLE IF NOT EXISTS remy_alerts (
  id            UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  tenant_id     UUID        NOT NULL REFERENCES chefs(id) ON DELETE CASCADE,
  alert_type    TEXT        NOT NULL,
  entity_type   TEXT,
  entity_id     UUID,
  title         TEXT        NOT NULL,
  body          TEXT        NOT NULL,
  priority      TEXT        NOT NULL DEFAULT 'normal'
                            CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
  dismissed_at  TIMESTAMPTZ,
  acted_on_at   TIMESTAMPTZ,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_remy_alerts_tenant_active
  ON remy_alerts (tenant_id, created_at DESC)
  WHERE dismissed_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_remy_alerts_tenant_type
  ON remy_alerts (tenant_id, alert_type, created_at DESC);
