-- Seed system_ingredients with 500+ common ingredients
-- Density data sourced from USDA and common culinary references
-- cup_weight_grams = density * 236.588, tbsp_weight_grams = density * 14.787

INSERT INTO system_ingredients (name, category, subcategory, unit_type, standard_unit, weight_to_volume_ratio, cup_weight_grams, tbsp_weight_grams, allergen_tags, common_prep_actions) VALUES

-- ============================================================
-- PROTEIN (85 items)
-- ============================================================

-- Poultry
('Chicken Breast (Boneless, Skinless)', 'protein', 'poultry', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 95}]'),
('Chicken Thigh (Boneless, Skinless)', 'protein', 'poultry', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 90}]'),
('Chicken Thigh (Bone-In, Skin-On)', 'protein', 'poultry', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 70}]'),
('Chicken Drumstick', 'protein', 'poultry', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 65}]'),
('Chicken Wing', 'protein', 'poultry', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "separate", "yield_pct": 90}]'),
('Whole Chicken', 'protein', 'poultry', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "butcher", "yield_pct": 65}]'),
('Chicken Tender', 'protein', 'poultry', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 98}]'),
('Ground Chicken', 'protein', 'poultry', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Turkey Breast', 'protein', 'poultry', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 90}]'),
('Ground Turkey', 'protein', 'poultry', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Whole Turkey', 'protein', 'poultry', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "butcher", "yield_pct": 60}]'),
('Duck Breast', 'protein', 'poultry', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "score_skin", "yield_pct": 85}]'),
('Whole Duck', 'protein', 'poultry', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "butcher", "yield_pct": 55}]'),
('Cornish Hen', 'protein', 'poultry', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "spatchcock", "yield_pct": 75}]'),
('Quail', 'protein', 'poultry', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "spatchcock", "yield_pct": 70}]'),

-- Beef
('Beef Tenderloin (Filet Mignon)', 'protein', 'beef', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 80}]'),
('Beef Ribeye Steak', 'protein', 'beef', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 90}]'),
('Beef New York Strip', 'protein', 'beef', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 90}]'),
('Beef Sirloin', 'protein', 'beef', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 88}]'),
('Beef Chuck Roast', 'protein', 'beef', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 80}]'),
('Beef Short Ribs', 'protein', 'beef', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 60}]'),
('Beef Brisket', 'protein', 'beef', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 70}]'),
('Ground Beef (80/20)', 'protein', 'beef', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Ground Beef (90/10)', 'protein', 'beef', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Beef Flank Steak', 'protein', 'beef', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 92}]'),
('Beef Skirt Steak', 'protein', 'beef', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 90}]'),
('Beef Stew Meat', 'protein', 'beef', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Beef Shank (Osso Buco)', 'protein', 'beef', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 55}]'),
('Veal Chop', 'protein', 'beef', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 80}]'),
('Veal Shank', 'protein', 'beef', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 55}]'),

-- Pork
('Pork Tenderloin', 'protein', 'pork', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim_silverskin", "yield_pct": 88}]'),
('Pork Chop (Bone-In)', 'protein', 'pork', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 80}]'),
('Pork Chop (Boneless)', 'protein', 'pork', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 95}]'),
('Pork Shoulder (Boston Butt)', 'protein', 'pork', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 70}]'),
('Pork Belly', 'protein', 'pork', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "score_skin", "yield_pct": 85}]'),
('Pork Loin Roast', 'protein', 'pork', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 85}]'),
('Baby Back Ribs', 'protein', 'pork', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "remove_membrane", "yield_pct": 70}]'),
('Spare Ribs', 'protein', 'pork', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "remove_membrane", "yield_pct": 65}]'),
('Ground Pork', 'protein', 'pork', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Bacon', 'protein', 'pork', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Pancetta', 'protein', 'pork', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "dice", "yield_pct": 100}]'),
('Prosciutto', 'protein', 'pork', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Italian Sausage', 'protein', 'pork', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Chorizo', 'protein', 'pork', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Ham', 'protein', 'pork', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "slice", "yield_pct": 95}]'),

-- Lamb
('Lamb Rack', 'protein', 'lamb', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "french", "yield_pct": 75}]'),
('Lamb Chop', 'protein', 'lamb', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 80}]'),
('Lamb Shank', 'protein', 'lamb', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 55}]'),
('Lamb Leg', 'protein', 'lamb', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 75}]'),
('Ground Lamb', 'protein', 'lamb', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Lamb Shoulder', 'protein', 'lamb', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 70}]'),

-- Seafood
('Salmon Fillet', 'protein', 'seafood', 'weight', 'g', NULL, NULL, NULL, '{"fish"}', '[{"action": "pin_bone", "yield_pct": 95}]'),
('Salmon (Whole Side)', 'protein', 'seafood', 'weight', 'g', NULL, NULL, NULL, '{"fish"}', '[{"action": "fillet", "yield_pct": 60}]'),
('Tuna Steak (Ahi)', 'protein', 'seafood', 'weight', 'g', NULL, NULL, NULL, '{"fish"}', '[{"action": "trim", "yield_pct": 95}]'),
('Cod Fillet', 'protein', 'seafood', 'weight', 'g', NULL, NULL, NULL, '{"fish"}', '[{"action": "pin_bone", "yield_pct": 95}]'),
('Halibut Fillet', 'protein', 'seafood', 'weight', 'g', NULL, NULL, NULL, '{"fish"}', '[{"action": "pin_bone", "yield_pct": 95}]'),
('Sea Bass Fillet', 'protein', 'seafood', 'weight', 'g', NULL, NULL, NULL, '{"fish"}', '[{"action": "pin_bone", "yield_pct": 95}]'),
('Swordfish Steak', 'protein', 'seafood', 'weight', 'g', NULL, NULL, NULL, '{"fish"}', '[{"action": "trim", "yield_pct": 92}]'),
('Mahi Mahi Fillet', 'protein', 'seafood', 'weight', 'g', NULL, NULL, NULL, '{"fish"}', '[{"action": "trim", "yield_pct": 95}]'),
('Snapper Fillet', 'protein', 'seafood', 'weight', 'g', NULL, NULL, NULL, '{"fish"}', '[{"action": "pin_bone", "yield_pct": 92}]'),
('Trout Fillet', 'protein', 'seafood', 'weight', 'g', NULL, NULL, NULL, '{"fish"}', '[{"action": "pin_bone", "yield_pct": 90}]'),
('Shrimp (Raw, Shell-On)', 'protein', 'seafood', 'weight', 'g', NULL, NULL, NULL, '{"shellfish"}', '[{"action": "peel_devein", "yield_pct": 55}]'),
('Shrimp (Peeled, Deveined)', 'protein', 'seafood', 'weight', 'g', NULL, NULL, NULL, '{"shellfish"}', '[]'),
('Lobster Tail', 'protein', 'seafood', 'weight', 'g', NULL, NULL, NULL, '{"shellfish"}', '[{"action": "shell", "yield_pct": 50}]'),
('Whole Lobster', 'protein', 'seafood', 'weight', 'g', NULL, NULL, NULL, '{"shellfish"}', '[{"action": "shell", "yield_pct": 30}]'),
('Scallops (Dry-Pack)', 'protein', 'seafood', 'weight', 'g', NULL, NULL, NULL, '{"shellfish"}', '[{"action": "pat_dry", "yield_pct": 100}]'),
('Crab Meat (Lump)', 'protein', 'seafood', 'weight', 'g', NULL, NULL, NULL, '{"shellfish"}', '[{"action": "pick_shells", "yield_pct": 95}]'),
('Mussels', 'protein', 'seafood', 'weight', 'g', NULL, NULL, NULL, '{"shellfish"}', '[{"action": "debeard_scrub", "yield_pct": 40}]'),
('Clams (Littleneck)', 'protein', 'seafood', 'weight', 'g', NULL, NULL, NULL, '{"shellfish"}', '[{"action": "scrub_purge", "yield_pct": 35}]'),
('Calamari (Squid)', 'protein', 'seafood', 'weight', 'g', NULL, NULL, NULL, '{"shellfish"}', '[{"action": "clean_slice", "yield_pct": 60}]'),
('Octopus', 'protein', 'seafood', 'weight', 'g', NULL, NULL, NULL, '{"shellfish"}', '[{"action": "clean", "yield_pct": 55}]'),
('Sardines', 'protein', 'seafood', 'weight', 'g', NULL, NULL, NULL, '{"fish"}', '[{"action": "gut_fillet", "yield_pct": 50}]'),
('Anchovies (Fresh)', 'protein', 'seafood', 'weight', 'g', NULL, NULL, NULL, '{"fish"}', '[{"action": "fillet", "yield_pct": 45}]'),

-- Other Protein
('Eggs (Large)', 'protein', 'eggs', 'each', 'each', NULL, NULL, NULL, '{"eggs"}', '[]'),
('Egg Whites', 'protein', 'eggs', 'volume', 'ml', NULL, NULL, NULL, '{"eggs"}', '[]'),
('Egg Yolks', 'protein', 'eggs', 'each', 'each', NULL, NULL, NULL, '{"eggs"}', '[]'),
('Tofu (Firm)', 'protein', 'plant_based', 'weight', 'g', NULL, NULL, NULL, '{"soybeans"}', '[{"action": "press_drain", "yield_pct": 90}]'),
('Tofu (Silken)', 'protein', 'plant_based', 'weight', 'g', NULL, NULL, NULL, '{"soybeans"}', '[]'),
('Tempeh', 'protein', 'plant_based', 'weight', 'g', NULL, NULL, NULL, '{"soybeans"}', '[]'),
('Seitan', 'protein', 'plant_based', 'weight', 'g', NULL, NULL, NULL, '{"wheat"}', '[]'),

-- ============================================================
-- PRODUCE (105 items)
-- ============================================================

-- Leafy Greens
('Romaine Lettuce', 'produce', 'leafy_green', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "wash_chop", "yield_pct": 75}]'),
('Mixed Greens (Mesclun)', 'produce', 'leafy_green', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "wash", "yield_pct": 95}]'),
('Baby Spinach', 'produce', 'leafy_green', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "wash", "yield_pct": 95}]'),
('Mature Spinach', 'produce', 'leafy_green', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "wash_stem", "yield_pct": 70}]'),
('Kale', 'produce', 'leafy_green', 'bunch', 'bunch', NULL, NULL, NULL, '{}', '[{"action": "stem_wash", "yield_pct": 65}]'),
('Swiss Chard', 'produce', 'leafy_green', 'bunch', 'bunch', NULL, NULL, NULL, '{}', '[{"action": "stem_wash", "yield_pct": 70}]'),
('Arugula', 'produce', 'leafy_green', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "wash", "yield_pct": 95}]'),
('Iceberg Lettuce', 'produce', 'leafy_green', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "core_wash", "yield_pct": 75}]'),
('Butter Lettuce', 'produce', 'leafy_green', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "wash_separate", "yield_pct": 80}]'),
('Watercress', 'produce', 'leafy_green', 'bunch', 'bunch', NULL, NULL, NULL, '{}', '[{"action": "wash_trim", "yield_pct": 85}]'),
('Endive', 'produce', 'leafy_green', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "wash_separate", "yield_pct": 90}]'),
('Radicchio', 'produce', 'leafy_green', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "wash_core", "yield_pct": 80}]'),
('Collard Greens', 'produce', 'leafy_green', 'bunch', 'bunch', NULL, NULL, NULL, '{}', '[{"action": "stem_wash", "yield_pct": 60}]'),
('Mustard Greens', 'produce', 'leafy_green', 'bunch', 'bunch', NULL, NULL, NULL, '{}', '[{"action": "wash_trim", "yield_pct": 70}]'),
('Bok Choy', 'produce', 'leafy_green', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "wash_trim", "yield_pct": 85}]'),
('Napa Cabbage', 'produce', 'leafy_green', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "wash_core", "yield_pct": 80}]'),

-- Root Vegetables
('Yellow Onion', 'produce', 'root_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "peel_dice", "yield_pct": 88}]'),
('Red Onion', 'produce', 'root_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "peel_dice", "yield_pct": 88}]'),
('White Onion', 'produce', 'root_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "peel_dice", "yield_pct": 88}]'),
('Shallot', 'produce', 'root_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "peel_mince", "yield_pct": 85}]'),
('Garlic', 'produce', 'root_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "peel_mince", "yield_pct": 88}]'),
('Carrot', 'produce', 'root_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "peel", "yield_pct": 82}]'),
('Celery', 'produce', 'root_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "wash_trim", "yield_pct": 75}]'),
('Potato (Russet)', 'produce', 'root_vegetable', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "peel", "yield_pct": 81}]'),
('Potato (Yukon Gold)', 'produce', 'root_vegetable', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "peel", "yield_pct": 85}]'),
('Sweet Potato', 'produce', 'root_vegetable', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "peel", "yield_pct": 80}]'),
('Red Potato', 'produce', 'root_vegetable', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Fingerling Potato', 'produce', 'root_vegetable', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Beet', 'produce', 'root_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "peel", "yield_pct": 75}]'),
('Turnip', 'produce', 'root_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "peel", "yield_pct": 80}]'),
('Parsnip', 'produce', 'root_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "peel", "yield_pct": 80}]'),
('Rutabaga', 'produce', 'root_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "peel", "yield_pct": 78}]'),
('Radish', 'produce', 'root_vegetable', 'bunch', 'bunch', NULL, NULL, NULL, '{}', '[{"action": "trim_wash", "yield_pct": 90}]'),
('Ginger Root', 'produce', 'root_vegetable', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "peel", "yield_pct": 85}]'),
('Turmeric Root', 'produce', 'root_vegetable', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "peel", "yield_pct": 85}]'),
('Celery Root (Celeriac)', 'produce', 'root_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "peel", "yield_pct": 70}]'),
('Fennel Bulb', 'produce', 'root_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "trim_core", "yield_pct": 75}]'),
('Leek', 'produce', 'root_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "trim_wash", "yield_pct": 55}]'),

-- Citrus
('Lemon', 'produce', 'citrus', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "juice", "yield_pct": 35}]'),
('Lime', 'produce', 'citrus', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "juice", "yield_pct": 30}]'),
('Orange', 'produce', 'citrus', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "peel_segment", "yield_pct": 65}]'),
('Grapefruit', 'produce', 'citrus', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "peel_segment", "yield_pct": 55}]'),
('Blood Orange', 'produce', 'citrus', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "peel_segment", "yield_pct": 65}]'),
('Meyer Lemon', 'produce', 'citrus', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "juice", "yield_pct": 35}]'),
('Tangerine', 'produce', 'citrus', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "peel_segment", "yield_pct": 70}]'),
('Kumquat', 'produce', 'citrus', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),

-- Fruiting Vegetables
('Tomato (Beefsteak)', 'produce', 'fruiting_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "core_slice", "yield_pct": 90}]'),
('Tomato (Roma)', 'produce', 'fruiting_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "core", "yield_pct": 92}]'),
('Cherry Tomato', 'produce', 'fruiting_vegetable', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "wash_halve", "yield_pct": 95}]'),
('Grape Tomato', 'produce', 'fruiting_vegetable', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "wash", "yield_pct": 98}]'),
('Heirloom Tomato', 'produce', 'fruiting_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "core_slice", "yield_pct": 90}]'),
('Bell Pepper (Red)', 'produce', 'fruiting_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "core_seed", "yield_pct": 82}]'),
('Bell Pepper (Green)', 'produce', 'fruiting_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "core_seed", "yield_pct": 82}]'),
('Bell Pepper (Yellow)', 'produce', 'fruiting_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "core_seed", "yield_pct": 82}]'),
('Jalapeno Pepper', 'produce', 'fruiting_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "seed_mince", "yield_pct": 80}]'),
('Serrano Pepper', 'produce', 'fruiting_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "seed_mince", "yield_pct": 80}]'),
('Habanero Pepper', 'produce', 'fruiting_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "seed_mince", "yield_pct": 75}]'),
('Poblano Pepper', 'produce', 'fruiting_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "roast_peel_seed", "yield_pct": 65}]'),
('Cucumber', 'produce', 'fruiting_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "peel_seed", "yield_pct": 75}]'),
('English Cucumber', 'produce', 'fruiting_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "slice", "yield_pct": 95}]'),
('Zucchini', 'produce', 'fruiting_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 95}]'),
('Yellow Squash', 'produce', 'fruiting_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 95}]'),
('Eggplant', 'produce', 'fruiting_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "peel_cube", "yield_pct": 81}]'),
('Avocado', 'produce', 'fruiting_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "pit_scoop", "yield_pct": 65}]'),
('Corn on the Cob', 'produce', 'fruiting_vegetable', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "husk_silk", "yield_pct": 55}]'),

-- Cruciferous
('Broccoli', 'produce', 'cruciferous', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "trim_floret", "yield_pct": 60}]'),
('Cauliflower', 'produce', 'cruciferous', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "trim_floret", "yield_pct": 55}]'),
('Brussels Sprouts', 'produce', 'cruciferous', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim_halve", "yield_pct": 85}]'),
('Green Cabbage', 'produce', 'cruciferous', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "core_shred", "yield_pct": 80}]'),
('Red Cabbage', 'produce', 'cruciferous', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "core_shred", "yield_pct": 80}]'),
('Broccolini', 'produce', 'cruciferous', 'bunch', 'bunch', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 90}]'),

-- Mushrooms
('White Button Mushroom', 'produce', 'mushroom', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "wipe_slice", "yield_pct": 92}]'),
('Cremini Mushroom', 'produce', 'mushroom', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "wipe_slice", "yield_pct": 92}]'),
('Portobello Mushroom', 'produce', 'mushroom', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "stem_scrape_gills", "yield_pct": 80}]'),
('Shiitake Mushroom', 'produce', 'mushroom', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "stem_slice", "yield_pct": 75}]'),
('Oyster Mushroom', 'produce', 'mushroom', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim_tear", "yield_pct": 90}]'),
('King Trumpet Mushroom', 'produce', 'mushroom', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "slice", "yield_pct": 95}]'),
('Chanterelle Mushroom', 'produce', 'mushroom', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "brush_trim", "yield_pct": 85}]'),
('Morel Mushroom', 'produce', 'mushroom', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "soak_rinse", "yield_pct": 80}]'),

-- Fruit
('Strawberry', 'produce', 'fruit', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "hull_wash", "yield_pct": 88}]'),
('Blueberry', 'produce', 'fruit', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "wash_sort", "yield_pct": 95}]'),
('Raspberry', 'produce', 'fruit', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "wash", "yield_pct": 95}]'),
('Blackberry', 'produce', 'fruit', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "wash", "yield_pct": 95}]'),
('Apple (Granny Smith)', 'produce', 'fruit', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "peel_core", "yield_pct": 75}]'),
('Apple (Honeycrisp)', 'produce', 'fruit', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "peel_core", "yield_pct": 75}]'),
('Pear (Bartlett)', 'produce', 'fruit', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "peel_core", "yield_pct": 78}]'),
('Banana', 'produce', 'fruit', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "peel", "yield_pct": 64}]'),
('Mango', 'produce', 'fruit', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "peel_pit", "yield_pct": 60}]'),
('Pineapple', 'produce', 'fruit', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "peel_core", "yield_pct": 50}]'),
('Peach', 'produce', 'fruit', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "peel_pit", "yield_pct": 76}]'),
('Plum', 'produce', 'fruit', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "pit", "yield_pct": 90}]'),
('Fig', 'produce', 'fruit', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 95}]'),
('Pomegranate', 'produce', 'fruit', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "seed", "yield_pct": 45}]'),
('Watermelon', 'produce', 'fruit', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "rind_seed", "yield_pct": 52}]'),
('Cantaloupe', 'produce', 'fruit', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "peel_seed", "yield_pct": 52}]'),
('Honeydew', 'produce', 'fruit', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "peel_seed", "yield_pct": 52}]'),
('Grape (Red)', 'produce', 'fruit', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "wash_stem", "yield_pct": 95}]'),
('Grape (Green)', 'produce', 'fruit', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "wash_stem", "yield_pct": 95}]'),

-- Other Produce
('Green Bean', 'produce', 'legume', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim", "yield_pct": 88}]'),
('Snow Pea', 'produce', 'legume', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim_string", "yield_pct": 90}]'),
('Sugar Snap Pea', 'produce', 'legume', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "trim_string", "yield_pct": 90}]'),
('Edamame (In Shell)', 'produce', 'legume', 'weight', 'g', NULL, NULL, NULL, '{"soybeans"}', '[{"action": "shell", "yield_pct": 50}]'),
('Artichoke', 'produce', 'other', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "trim_choke", "yield_pct": 35}]'),
('Asparagus', 'produce', 'other', 'bunch', 'bunch', NULL, NULL, NULL, '{}', '[{"action": "trim_snap", "yield_pct": 65}]'),

-- ============================================================
-- DAIRY (42 items)
-- ============================================================

('Whole Milk', 'dairy', 'milk', 'volume', 'ml', 1.0300, 243.69, 15.23, '{"milk"}', '[]'),
('2% Milk', 'dairy', 'milk', 'volume', 'ml', 1.0300, 243.69, 15.23, '{"milk"}', '[]'),
('Skim Milk', 'dairy', 'milk', 'volume', 'ml', 1.0300, 243.69, 15.23, '{"milk"}', '[]'),
('Heavy Cream', 'dairy', 'cream', 'volume', 'ml', 1.0100, 238.95, 14.93, '{"milk"}', '[]'),
('Half and Half', 'dairy', 'cream', 'volume', 'ml', 1.0200, 241.32, 15.08, '{"milk"}', '[]'),
('Whipping Cream', 'dairy', 'cream', 'volume', 'ml', 1.0100, 238.95, 14.93, '{"milk"}', '[]'),
('Sour Cream', 'dairy', 'cream', 'volume', 'ml', 1.0100, 238.95, 14.93, '{"milk"}', '[]'),
('Creme Fraiche', 'dairy', 'cream', 'volume', 'ml', 1.0100, 238.95, 14.93, '{"milk"}', '[]'),
('Cream Cheese', 'dairy', 'cheese', 'weight', 'g', 1.0200, 241.32, 15.08, '{"milk"}', '[]'),
('Butter (Unsalted)', 'dairy', 'butter', 'weight', 'g', 0.9100, 215.30, 13.46, '{"milk"}', '[]'),
('Butter (Salted)', 'dairy', 'butter', 'weight', 'g', 0.9100, 215.30, 13.46, '{"milk"}', '[]'),
('Clarified Butter (Ghee)', 'dairy', 'butter', 'weight', 'g', 0.9100, 215.30, 13.46, '{"milk"}', '[]'),
('Yogurt (Plain, Whole)', 'dairy', 'yogurt', 'volume', 'ml', 1.0400, 246.05, 15.38, '{"milk"}', '[]'),
('Yogurt (Greek, Whole)', 'dairy', 'yogurt', 'volume', 'ml', 1.0400, 246.05, 15.38, '{"milk"}', '[]'),
('Yogurt (Greek, Nonfat)', 'dairy', 'yogurt', 'volume', 'ml', 1.0400, 246.05, 15.38, '{"milk"}', '[]'),
('Buttermilk', 'dairy', 'milk', 'volume', 'ml', 1.0300, 243.69, 15.23, '{"milk"}', '[]'),
('Evaporated Milk', 'dairy', 'milk', 'volume', 'ml', 1.0700, 253.15, 15.82, '{"milk"}', '[]'),
('Sweetened Condensed Milk', 'dairy', 'milk', 'volume', 'ml', 1.3300, 314.66, 19.67, '{"milk"}', '[]'),
('Parmesan Cheese (Wedge)', 'dairy', 'cheese', 'weight', 'g', NULL, NULL, NULL, '{"milk"}', '[{"action": "grate", "yield_pct": 95}]'),
('Parmesan Cheese (Grated)', 'dairy', 'cheese', 'weight', 'g', NULL, NULL, NULL, '{"milk"}', '[]'),
('Mozzarella (Fresh)', 'dairy', 'cheese', 'weight', 'g', NULL, NULL, NULL, '{"milk"}', '[{"action": "slice_drain", "yield_pct": 95}]'),
('Mozzarella (Low-Moisture, Shredded)', 'dairy', 'cheese', 'weight', 'g', NULL, NULL, NULL, '{"milk"}', '[]'),
('Cheddar Cheese', 'dairy', 'cheese', 'weight', 'g', NULL, NULL, NULL, '{"milk"}', '[{"action": "shred", "yield_pct": 100}]'),
('Gruyere Cheese', 'dairy', 'cheese', 'weight', 'g', NULL, NULL, NULL, '{"milk"}', '[{"action": "shred", "yield_pct": 100}]'),
('Swiss Cheese', 'dairy', 'cheese', 'weight', 'g', NULL, NULL, NULL, '{"milk"}', '[]'),
('Gouda Cheese', 'dairy', 'cheese', 'weight', 'g', NULL, NULL, NULL, '{"milk"}', '[]'),
('Blue Cheese', 'dairy', 'cheese', 'weight', 'g', NULL, NULL, NULL, '{"milk"}', '[]'),
('Goat Cheese (Chevre)', 'dairy', 'cheese', 'weight', 'g', NULL, NULL, NULL, '{"milk"}', '[]'),
('Ricotta Cheese', 'dairy', 'cheese', 'weight', 'g', NULL, NULL, NULL, '{"milk"}', '[]'),
('Mascarpone', 'dairy', 'cheese', 'weight', 'g', NULL, NULL, NULL, '{"milk"}', '[]'),
('Feta Cheese', 'dairy', 'cheese', 'weight', 'g', NULL, NULL, NULL, '{"milk"}', '[]'),
('Brie Cheese', 'dairy', 'cheese', 'weight', 'g', NULL, NULL, NULL, '{"milk"}', '[]'),
('Pecorino Romano', 'dairy', 'cheese', 'weight', 'g', NULL, NULL, NULL, '{"milk"}', '[{"action": "grate", "yield_pct": 95}]'),
('Provolone Cheese', 'dairy', 'cheese', 'weight', 'g', NULL, NULL, NULL, '{"milk"}', '[]'),
('Monterey Jack Cheese', 'dairy', 'cheese', 'weight', 'g', NULL, NULL, NULL, '{"milk"}', '[]'),
('Fontina Cheese', 'dairy', 'cheese', 'weight', 'g', NULL, NULL, NULL, '{"milk"}', '[]'),
('Cotija Cheese', 'dairy', 'cheese', 'weight', 'g', NULL, NULL, NULL, '{"milk"}', '[]'),
('Burrata', 'dairy', 'cheese', 'each', 'each', NULL, NULL, NULL, '{"milk"}', '[]'),
('Queso Fresco', 'dairy', 'cheese', 'weight', 'g', NULL, NULL, NULL, '{"milk"}', '[]'),
('Havarti Cheese', 'dairy', 'cheese', 'weight', 'g', NULL, NULL, NULL, '{"milk"}', '[]'),
('Manchego Cheese', 'dairy', 'cheese', 'weight', 'g', NULL, NULL, NULL, '{"milk"}', '[]'),
('Halloumi Cheese', 'dairy', 'cheese', 'weight', 'g', NULL, NULL, NULL, '{"milk"}', '[]'),

-- ============================================================
-- PANTRY (55 items)
-- ============================================================

-- Flour
('All-Purpose Flour', 'pantry', 'flour', 'weight', 'g', 0.5300, 125.39, 7.84, '{"wheat"}', '[{"action": "sift", "yield_pct": 100}]'),
('Bread Flour', 'pantry', 'flour', 'weight', 'g', 0.5500, 130.12, 8.13, '{"wheat"}', '[{"action": "sift", "yield_pct": 100}]'),
('Cake Flour', 'pantry', 'flour', 'weight', 'g', 0.4900, 115.93, 7.25, '{"wheat"}', '[{"action": "sift", "yield_pct": 100}]'),
('Whole Wheat Flour', 'pantry', 'flour', 'weight', 'g', 0.5100, 120.66, 7.54, '{"wheat"}', '[]'),
('Semolina Flour', 'pantry', 'flour', 'weight', 'g', 0.5500, 130.12, 8.13, '{"wheat"}', '[]'),
('Almond Flour', 'pantry', 'flour', 'weight', 'g', 0.6000, 141.95, 8.87, '{"tree_nuts"}', '[]'),
('Coconut Flour', 'pantry', 'flour', 'weight', 'g', 0.5000, 118.29, 7.39, '{}', '[]'),
('Cornmeal', 'pantry', 'flour', 'weight', 'g', 0.6500, 153.78, 9.61, '{}', '[]'),
('Cornstarch', 'pantry', 'flour', 'weight', 'g', 0.5100, 120.66, 7.54, '{}', '[]'),

-- Sugar
('Granulated Sugar', 'pantry', 'sugar', 'weight', 'g', 0.8500, 201.10, 12.57, '{}', '[]'),
('Light Brown Sugar', 'pantry', 'sugar', 'weight', 'g', 0.8300, 196.37, 12.27, '{}', '[]'),
('Dark Brown Sugar', 'pantry', 'sugar', 'weight', 'g', 0.8300, 196.37, 12.27, '{}', '[]'),
('Powdered Sugar (Confectioners)', 'pantry', 'sugar', 'weight', 'g', 0.5600, 132.49, 8.28, '{}', '[{"action": "sift", "yield_pct": 100}]'),
('Turbinado Sugar', 'pantry', 'sugar', 'weight', 'g', 0.8800, 208.20, 13.01, '{}', '[]'),
('Honey', 'pantry', 'sweetener', 'volume', 'ml', 1.4200, 335.95, 21.00, '{}', '[]'),
('Maple Syrup', 'pantry', 'sweetener', 'volume', 'ml', 1.3300, 314.66, 19.67, '{}', '[]'),
('Molasses', 'pantry', 'sweetener', 'volume', 'ml', 1.4200, 335.95, 21.00, '{}', '[]'),
('Agave Nectar', 'pantry', 'sweetener', 'volume', 'ml', 1.3500, 319.39, 19.96, '{}', '[]'),
('Corn Syrup (Light)', 'pantry', 'sweetener', 'volume', 'ml', 1.3800, 326.49, 20.41, '{}', '[]'),

-- Grains and Pasta
('Long Grain White Rice', 'pantry', 'grain', 'weight', 'g', 0.7900, 186.90, 11.68, '{}', '[]'),
('Basmati Rice', 'pantry', 'grain', 'weight', 'g', 0.7900, 186.90, 11.68, '{}', '[]'),
('Jasmine Rice', 'pantry', 'grain', 'weight', 'g', 0.7900, 186.90, 11.68, '{}', '[]'),
('Arborio Rice', 'pantry', 'grain', 'weight', 'g', 0.8000, 189.27, 11.83, '{}', '[]'),
('Brown Rice', 'pantry', 'grain', 'weight', 'g', 0.7900, 186.90, 11.68, '{}', '[]'),
('Wild Rice', 'pantry', 'grain', 'weight', 'g', 0.6600, 156.15, 9.76, '{}', '[]'),
('Quinoa', 'pantry', 'grain', 'weight', 'g', 0.7200, 170.34, 10.65, '{}', '[]'),
('Couscous', 'pantry', 'grain', 'weight', 'g', 0.6300, 149.05, 9.32, '{"wheat"}', '[]'),
('Bulgur Wheat', 'pantry', 'grain', 'weight', 'g', 0.6500, 153.78, 9.61, '{"wheat"}', '[]'),
('Farro', 'pantry', 'grain', 'weight', 'g', 0.6500, 153.78, 9.61, '{"wheat"}', '[]'),
('Rolled Oats', 'pantry', 'grain', 'weight', 'g', 0.3500, 82.81, 5.18, '{}', '[]'),
('Steel Cut Oats', 'pantry', 'grain', 'weight', 'g', 0.5500, 130.12, 8.13, '{}', '[]'),
('Polenta (Dry)', 'pantry', 'grain', 'weight', 'g', 0.6500, 153.78, 9.61, '{}', '[]'),
('Spaghetti (Dry)', 'pantry', 'pasta', 'weight', 'g', NULL, NULL, NULL, '{"wheat"}', '[]'),
('Penne (Dry)', 'pantry', 'pasta', 'weight', 'g', NULL, NULL, NULL, '{"wheat"}', '[]'),
('Rigatoni (Dry)', 'pantry', 'pasta', 'weight', 'g', NULL, NULL, NULL, '{"wheat"}', '[]'),
('Linguine (Dry)', 'pantry', 'pasta', 'weight', 'g', NULL, NULL, NULL, '{"wheat"}', '[]'),
('Fettuccine (Dry)', 'pantry', 'pasta', 'weight', 'g', NULL, NULL, NULL, '{"wheat"}', '[]'),
('Orzo (Dry)', 'pantry', 'pasta', 'weight', 'g', NULL, NULL, NULL, '{"wheat"}', '[]'),
('Egg Noodles (Dry)', 'pantry', 'pasta', 'weight', 'g', NULL, NULL, NULL, '{"wheat","eggs"}', '[]'),
('Rice Noodles (Dry)', 'pantry', 'pasta', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Lasagna Sheets (Dry)', 'pantry', 'pasta', 'weight', 'g', NULL, NULL, NULL, '{"wheat"}', '[]'),

-- Legumes
('Black Beans (Dried)', 'pantry', 'legume', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "soak", "yield_pct": 100}]'),
('Kidney Beans (Dried)', 'pantry', 'legume', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "soak", "yield_pct": 100}]'),
('Chickpeas (Dried)', 'pantry', 'legume', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "soak", "yield_pct": 100}]'),
('Lentils (Green)', 'pantry', 'legume', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Lentils (Red)', 'pantry', 'legume', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('White Beans (Dried)', 'pantry', 'legume', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "soak", "yield_pct": 100}]'),
('Split Peas (Green)', 'pantry', 'legume', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),

-- Nuts and Seeds
('Almonds (Whole)', 'pantry', 'nut', 'weight', 'g', 0.6000, 141.95, 8.87, '{"tree_nuts"}', '[]'),
('Almonds (Sliced)', 'pantry', 'nut', 'weight', 'g', 0.5000, 118.29, 7.39, '{"tree_nuts"}', '[]'),
('Walnuts (Halves)', 'pantry', 'nut', 'weight', 'g', 0.4600, 108.83, 6.80, '{"tree_nuts"}', '[]'),
('Pecans (Halves)', 'pantry', 'nut', 'weight', 'g', 0.4200, 99.37, 6.21, '{"tree_nuts"}', '[]'),
('Pine Nuts', 'pantry', 'nut', 'weight', 'g', 0.5600, 132.49, 8.28, '{"tree_nuts"}', '[]'),
('Cashews', 'pantry', 'nut', 'weight', 'g', 0.5700, 134.86, 8.43, '{"tree_nuts"}', '[]'),
('Pistachios (Shelled)', 'pantry', 'nut', 'weight', 'g', 0.5500, 130.12, 8.13, '{"tree_nuts"}', '[]'),
('Peanuts', 'pantry', 'nut', 'weight', 'g', 0.5800, 137.22, 8.58, '{"peanuts"}', '[]'),
('Peanut Butter', 'pantry', 'nut_butter', 'weight', 'g', 1.0800, 255.51, 15.97, '{"peanuts"}', '[]'),
('Almond Butter', 'pantry', 'nut_butter', 'weight', 'g', 1.0600, 250.78, 15.67, '{"tree_nuts"}', '[]'),
('Tahini', 'pantry', 'nut_butter', 'weight', 'g', 1.0500, 248.42, 15.53, '{"sesame"}', '[]'),
('Sesame Seeds', 'pantry', 'seed', 'weight', 'g', 0.5800, 137.22, 8.58, '{"sesame"}', '[]'),
('Sunflower Seeds', 'pantry', 'seed', 'weight', 'g', 0.5500, 130.12, 8.13, '{}', '[]'),
('Pumpkin Seeds (Pepitas)', 'pantry', 'seed', 'weight', 'g', 0.5600, 132.49, 8.28, '{}', '[]'),
('Flax Seeds', 'pantry', 'seed', 'weight', 'g', 0.5200, 123.03, 7.69, '{}', '[]'),
('Chia Seeds', 'pantry', 'seed', 'weight', 'g', 0.5300, 125.39, 7.84, '{}', '[]'),
('Coconut (Shredded, Unsweetened)', 'pantry', 'nut', 'weight', 'g', 0.3400, 80.44, 5.03, '{"tree_nuts"}', '[]'),
('Coconut (Shredded, Sweetened)', 'pantry', 'nut', 'weight', 'g', 0.3700, 87.54, 5.47, '{"tree_nuts"}', '[]'),

-- ============================================================
-- SPICE (65 items)
-- ============================================================

('Black Pepper (Ground)', 'spice', 'ground_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Black Pepper (Whole)', 'spice', 'whole_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('White Pepper (Ground)', 'spice', 'ground_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Cayenne Pepper', 'spice', 'ground_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Crushed Red Pepper Flakes', 'spice', 'ground_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Paprika (Sweet)', 'spice', 'ground_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Paprika (Smoked)', 'spice', 'ground_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Paprika (Hot)', 'spice', 'ground_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Chili Powder', 'spice', 'ground_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Ancho Chili Powder', 'spice', 'ground_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Chipotle Powder', 'spice', 'ground_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Cumin (Ground)', 'spice', 'ground_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Cumin Seeds', 'spice', 'whole_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Coriander (Ground)', 'spice', 'ground_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Coriander Seeds', 'spice', 'whole_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Turmeric (Ground)', 'spice', 'ground_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Cinnamon (Ground)', 'spice', 'ground_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Cinnamon Sticks', 'spice', 'whole_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Nutmeg (Ground)', 'spice', 'ground_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Nutmeg (Whole)', 'spice', 'whole_spice', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "grate", "yield_pct": 95}]'),
('Cloves (Ground)', 'spice', 'ground_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Cloves (Whole)', 'spice', 'whole_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Allspice (Ground)', 'spice', 'ground_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Allspice (Whole)', 'spice', 'whole_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Ginger (Ground)', 'spice', 'ground_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Cardamom (Ground)', 'spice', 'ground_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Cardamom Pods (Green)', 'spice', 'whole_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Mustard Powder', 'spice', 'ground_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Mustard Seeds (Yellow)', 'spice', 'whole_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Mustard Seeds (Black)', 'spice', 'whole_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Fennel Seeds', 'spice', 'whole_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Caraway Seeds', 'spice', 'whole_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Star Anise', 'spice', 'whole_spice', 'each', 'each', NULL, NULL, NULL, '{}', '[]'),
('Saffron', 'spice', 'whole_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Vanilla Bean', 'spice', 'whole_spice', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "split_scrape", "yield_pct": 90}]'),
('Vanilla Extract', 'spice', 'extract', 'volume', 'ml', NULL, NULL, NULL, '{}', '[]'),
('Almond Extract', 'spice', 'extract', 'volume', 'ml', NULL, NULL, NULL, '{"tree_nuts"}', '[]'),
('Peppermint Extract', 'spice', 'extract', 'volume', 'ml', NULL, NULL, NULL, '{}', '[]'),
('Bay Leaf (Dried)', 'spice', 'whole_spice', 'each', 'each', NULL, NULL, NULL, '{}', '[]'),
('Fenugreek Seeds', 'spice', 'whole_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Sumac', 'spice', 'ground_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Za''atar Blend', 'spice', 'blend', 'weight', 'g', NULL, NULL, NULL, '{"sesame"}', '[]'),
('Garam Masala', 'spice', 'blend', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Curry Powder', 'spice', 'blend', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Chinese Five Spice', 'spice', 'blend', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Italian Seasoning', 'spice', 'blend', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Herbs de Provence', 'spice', 'blend', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Old Bay Seasoning', 'spice', 'blend', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Taco Seasoning', 'spice', 'blend', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Jerk Seasoning', 'spice', 'blend', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Ras el Hanout', 'spice', 'blend', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Achiote (Annatto) Powder', 'spice', 'ground_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Onion Powder', 'spice', 'ground_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Garlic Powder', 'spice', 'ground_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Celery Seed', 'spice', 'whole_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Poppy Seeds', 'spice', 'whole_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Juniper Berries', 'spice', 'whole_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Szechuan Peppercorn', 'spice', 'whole_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Mace (Ground)', 'spice', 'ground_spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Berbere Spice Blend', 'spice', 'blend', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Dukkah', 'spice', 'blend', 'weight', 'g', NULL, NULL, NULL, '{"tree_nuts","sesame"}', '[]'),
('Everything Bagel Seasoning', 'spice', 'blend', 'weight', 'g', NULL, NULL, NULL, '{"sesame"}', '[]'),
('Tajin Seasoning', 'spice', 'blend', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Togarashi (Shichimi)', 'spice', 'blend', 'weight', 'g', NULL, NULL, NULL, '{"sesame"}', '[]'),
('Furikake', 'spice', 'blend', 'weight', 'g', NULL, NULL, NULL, '{"sesame","fish"}', '[]'),

-- ============================================================
-- OIL (22 items)
-- ============================================================

('Extra Virgin Olive Oil', 'oil', 'cooking_oil', 'volume', 'ml', 0.9200, 217.66, 13.60, '{}', '[]'),
('Light Olive Oil', 'oil', 'cooking_oil', 'volume', 'ml', 0.9200, 217.66, 13.60, '{}', '[]'),
('Vegetable Oil', 'oil', 'cooking_oil', 'volume', 'ml', 0.9200, 217.66, 13.60, '{}', '[]'),
('Canola Oil', 'oil', 'cooking_oil', 'volume', 'ml', 0.9200, 217.66, 13.60, '{}', '[]'),
('Avocado Oil', 'oil', 'cooking_oil', 'volume', 'ml', 0.9200, 217.66, 13.60, '{}', '[]'),
('Coconut Oil', 'oil', 'cooking_oil', 'volume', 'ml', 0.9200, 217.66, 13.60, '{}', '[]'),
('Grapeseed Oil', 'oil', 'cooking_oil', 'volume', 'ml', 0.9200, 217.66, 13.60, '{}', '[]'),
('Peanut Oil', 'oil', 'cooking_oil', 'volume', 'ml', 0.9200, 217.66, 13.60, '{"peanuts"}', '[]'),
('Sesame Oil (Toasted)', 'oil', 'finishing_oil', 'volume', 'ml', 0.9200, 217.66, 13.60, '{"sesame"}', '[]'),
('Sesame Oil (Light)', 'oil', 'cooking_oil', 'volume', 'ml', 0.9200, 217.66, 13.60, '{"sesame"}', '[]'),
('Walnut Oil', 'oil', 'finishing_oil', 'volume', 'ml', 0.9200, 217.66, 13.60, '{"tree_nuts"}', '[]'),
('Truffle Oil', 'oil', 'finishing_oil', 'volume', 'ml', 0.9200, 217.66, 13.60, '{}', '[]'),
('Chili Oil', 'oil', 'finishing_oil', 'volume', 'ml', 0.9200, 217.66, 13.60, '{}', '[]'),
('Cooking Spray (Nonstick)', 'oil', 'cooking_oil', 'each', 'each', NULL, NULL, NULL, '{}', '[]'),
('Lard', 'oil', 'animal_fat', 'weight', 'g', 0.9200, 217.66, 13.60, '{}', '[]'),
('Duck Fat', 'oil', 'animal_fat', 'weight', 'g', 0.9200, 217.66, 13.60, '{}', '[]'),
('Schmaltz (Chicken Fat)', 'oil', 'animal_fat', 'weight', 'g', 0.9200, 217.66, 13.60, '{}', '[]'),
('Shortening', 'oil', 'cooking_oil', 'weight', 'g', 0.9100, 215.30, 13.46, '{}', '[]'),
('Tallow (Beef Fat)', 'oil', 'animal_fat', 'weight', 'g', 0.9200, 217.66, 13.60, '{}', '[]'),
('MCT Oil', 'oil', 'finishing_oil', 'volume', 'ml', 0.9200, 217.66, 13.60, '{}', '[]'),
('Flaxseed Oil', 'oil', 'finishing_oil', 'volume', 'ml', 0.9200, 217.66, 13.60, '{}', '[]'),
('Hemp Seed Oil', 'oil', 'finishing_oil', 'volume', 'ml', 0.9200, 217.66, 13.60, '{}', '[]'),

-- ============================================================
-- BAKING (32 items)
-- ============================================================

('Baking Powder', 'baking', 'leavener', 'weight', 'g', 0.9200, 217.66, 13.60, '{}', '[]'),
('Baking Soda', 'baking', 'leavener', 'weight', 'g', 0.9500, 224.76, 14.05, '{}', '[]'),
('Active Dry Yeast', 'baking', 'leavener', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Instant Yeast', 'baking', 'leavener', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Cream of Tartar', 'baking', 'leavener', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Cocoa Powder (Unsweetened)', 'baking', 'chocolate', 'weight', 'g', 0.4200, 99.37, 6.21, '{}', '[]'),
('Cocoa Powder (Dutch Process)', 'baking', 'chocolate', 'weight', 'g', 0.4200, 99.37, 6.21, '{}', '[]'),
('Chocolate Chips (Semi-Sweet)', 'baking', 'chocolate', 'weight', 'g', NULL, NULL, NULL, '{"milk"}', '[]'),
('Chocolate Chips (Dark)', 'baking', 'chocolate', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Chocolate Chips (White)', 'baking', 'chocolate', 'weight', 'g', NULL, NULL, NULL, '{"milk"}', '[]'),
('Baking Chocolate (Unsweetened)', 'baking', 'chocolate', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Baking Chocolate (Bittersweet)', 'baking', 'chocolate', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Gelatin (Unflavored, Powder)', 'baking', 'thickener', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Gelatin Sheets', 'baking', 'thickener', 'each', 'each', NULL, NULL, NULL, '{}', '[]'),
('Agar Agar Powder', 'baking', 'thickener', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Pectin', 'baking', 'thickener', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Xanthan Gum', 'baking', 'thickener', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Tapioca Starch', 'baking', 'thickener', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Arrowroot Powder', 'baking', 'thickener', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Meringue Powder', 'baking', 'specialty', 'weight', 'g', NULL, NULL, NULL, '{"eggs"}', '[]'),
('Food Coloring (Red)', 'baking', 'decoration', 'volume', 'ml', NULL, NULL, NULL, '{}', '[]'),
('Food Coloring (Blue)', 'baking', 'decoration', 'volume', 'ml', NULL, NULL, NULL, '{}', '[]'),
('Food Coloring (Yellow)', 'baking', 'decoration', 'volume', 'ml', NULL, NULL, NULL, '{}', '[]'),
('Food Coloring (Green)', 'baking', 'decoration', 'volume', 'ml', NULL, NULL, NULL, '{}', '[]'),
('Sprinkles', 'baking', 'decoration', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Kosher Salt', 'baking', 'salt', 'weight', 'g', 0.6400, 151.42, 9.46, '{}', '[]'),
('Sea Salt (Fine)', 'baking', 'salt', 'weight', 'g', 1.2200, 288.64, 18.04, '{}', '[]'),
('Sea Salt (Flaky, Finishing)', 'baking', 'salt', 'weight', 'g', 0.5500, 130.12, 8.13, '{}', '[]'),
('Table Salt', 'baking', 'salt', 'weight', 'g', 1.2200, 288.64, 18.04, '{}', '[]'),
('Pink Himalayan Salt', 'baking', 'salt', 'weight', 'g', 1.1500, 272.08, 17.01, '{}', '[]'),
('Maldon Salt', 'baking', 'salt', 'weight', 'g', 0.5500, 130.12, 8.13, '{}', '[]'),
('Black Salt (Kala Namak)', 'baking', 'salt', 'weight', 'g', 1.1500, 272.08, 17.01, '{}', '[]'),

-- ============================================================
-- FROZEN (18 items)
-- ============================================================

('Frozen Peas', 'frozen', 'vegetable', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Frozen Corn', 'frozen', 'vegetable', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Frozen Spinach', 'frozen', 'vegetable', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "thaw_squeeze", "yield_pct": 60}]'),
('Frozen Broccoli', 'frozen', 'vegetable', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Frozen Mixed Vegetables', 'frozen', 'vegetable', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Frozen Edamame (Shelled)', 'frozen', 'vegetable', 'weight', 'g', NULL, NULL, NULL, '{"soybeans"}', '[]'),
('Frozen Lima Beans', 'frozen', 'vegetable', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Frozen Strawberries', 'frozen', 'fruit', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Frozen Blueberries', 'frozen', 'fruit', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Frozen Raspberries', 'frozen', 'fruit', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Frozen Mango Chunks', 'frozen', 'fruit', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Frozen Peach Slices', 'frozen', 'fruit', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Frozen Puff Pastry', 'frozen', 'dough', 'each', 'each', NULL, NULL, NULL, '{"wheat","milk"}', '[{"action": "thaw", "yield_pct": 100}]'),
('Frozen Phyllo Dough', 'frozen', 'dough', 'each', 'each', NULL, NULL, NULL, '{"wheat"}', '[{"action": "thaw", "yield_pct": 100}]'),
('Frozen Pie Crust', 'frozen', 'dough', 'each', 'each', NULL, NULL, NULL, '{"wheat","milk"}', '[{"action": "thaw", "yield_pct": 100}]'),
('Frozen Shrimp (Raw, Peeled)', 'frozen', 'seafood', 'weight', 'g', NULL, NULL, NULL, '{"shellfish"}', '[{"action": "thaw", "yield_pct": 100}]'),
('Frozen Fish Fillets (White)', 'frozen', 'seafood', 'weight', 'g', NULL, NULL, NULL, '{"fish"}', '[{"action": "thaw", "yield_pct": 100}]'),
('Ice Cream (Vanilla)', 'frozen', 'dessert', 'volume', 'ml', NULL, NULL, NULL, '{"milk","eggs"}', '[]'),

-- ============================================================
-- CANNED (22 items)
-- ============================================================

('Canned Diced Tomatoes', 'canned', 'tomato', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Canned Crushed Tomatoes', 'canned', 'tomato', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Canned Whole Peeled Tomatoes', 'canned', 'tomato', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Tomato Paste', 'canned', 'tomato', 'weight', 'g', 1.1000, 260.25, 16.27, '{}', '[]'),
('Tomato Sauce', 'canned', 'tomato', 'volume', 'ml', 1.0500, 248.42, 15.53, '{}', '[]'),
('Canned Black Beans', 'canned', 'bean', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "drain_rinse", "yield_pct": 65}]'),
('Canned Kidney Beans', 'canned', 'bean', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "drain_rinse", "yield_pct": 65}]'),
('Canned Chickpeas', 'canned', 'bean', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "drain_rinse", "yield_pct": 65}]'),
('Canned White Beans (Cannellini)', 'canned', 'bean', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "drain_rinse", "yield_pct": 65}]'),
('Canned Pinto Beans', 'canned', 'bean', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "drain_rinse", "yield_pct": 65}]'),
('Canned Coconut Milk', 'canned', 'coconut', 'volume', 'ml', NULL, NULL, NULL, '{}', '[]'),
('Canned Coconut Cream', 'canned', 'coconut', 'volume', 'ml', NULL, NULL, NULL, '{}', '[]'),
('Canned Corn', 'canned', 'vegetable', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "drain", "yield_pct": 70}]'),
('Canned Artichoke Hearts', 'canned', 'vegetable', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "drain", "yield_pct": 60}]'),
('Canned Roasted Red Peppers', 'canned', 'vegetable', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "drain", "yield_pct": 70}]'),
('Canned Chipotle in Adobo', 'canned', 'sauce', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Canned Tuna (In Water)', 'canned', 'seafood', 'weight', 'g', NULL, NULL, NULL, '{"fish"}', '[{"action": "drain", "yield_pct": 70}]'),
('Canned Tuna (In Oil)', 'canned', 'seafood', 'weight', 'g', NULL, NULL, NULL, '{"fish"}', '[{"action": "drain", "yield_pct": 75}]'),
('Canned Anchovies (In Oil)', 'canned', 'seafood', 'weight', 'g', NULL, NULL, NULL, '{"fish"}', '[]'),
('Canned Sardines', 'canned', 'seafood', 'weight', 'g', NULL, NULL, NULL, '{"fish"}', '[]'),
('Canned Pumpkin Puree', 'canned', 'vegetable', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Canned Jackfruit', 'canned', 'vegetable', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "drain_shred", "yield_pct": 65}]'),

-- ============================================================
-- FRESH HERB (22 items)
-- ============================================================

('Fresh Basil', 'fresh_herb', 'herb', 'bunch', 'bunch', NULL, NULL, NULL, '{}', '[{"action": "wash_pick", "yield_pct": 60}]'),
('Fresh Parsley (Italian Flat-Leaf)', 'fresh_herb', 'herb', 'bunch', 'bunch', NULL, NULL, NULL, '{}', '[{"action": "wash_pick_chop", "yield_pct": 55}]'),
('Fresh Parsley (Curly)', 'fresh_herb', 'herb', 'bunch', 'bunch', NULL, NULL, NULL, '{}', '[{"action": "wash_pick_chop", "yield_pct": 55}]'),
('Fresh Cilantro', 'fresh_herb', 'herb', 'bunch', 'bunch', NULL, NULL, NULL, '{}', '[{"action": "wash_pick_chop", "yield_pct": 55}]'),
('Fresh Dill', 'fresh_herb', 'herb', 'bunch', 'bunch', NULL, NULL, NULL, '{}', '[{"action": "wash_pick", "yield_pct": 50}]'),
('Fresh Mint', 'fresh_herb', 'herb', 'bunch', 'bunch', NULL, NULL, NULL, '{}', '[{"action": "wash_pick", "yield_pct": 55}]'),
('Fresh Thyme', 'fresh_herb', 'herb', 'bunch', 'bunch', NULL, NULL, NULL, '{}', '[{"action": "strip_stem", "yield_pct": 40}]'),
('Fresh Rosemary', 'fresh_herb', 'herb', 'bunch', 'bunch', NULL, NULL, NULL, '{}', '[{"action": "strip_stem_chop", "yield_pct": 45}]'),
('Fresh Oregano', 'fresh_herb', 'herb', 'bunch', 'bunch', NULL, NULL, NULL, '{}', '[{"action": "strip_stem", "yield_pct": 45}]'),
('Fresh Sage', 'fresh_herb', 'herb', 'bunch', 'bunch', NULL, NULL, NULL, '{}', '[{"action": "wash_pick", "yield_pct": 60}]'),
('Fresh Chives', 'fresh_herb', 'herb', 'bunch', 'bunch', NULL, NULL, NULL, '{}', '[{"action": "wash_snip", "yield_pct": 90}]'),
('Fresh Tarragon', 'fresh_herb', 'herb', 'bunch', 'bunch', NULL, NULL, NULL, '{}', '[{"action": "strip_stem", "yield_pct": 45}]'),
('Fresh Bay Leaf', 'fresh_herb', 'herb', 'each', 'each', NULL, NULL, NULL, '{}', '[]'),
('Fresh Lemongrass', 'fresh_herb', 'herb', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "trim_bruise", "yield_pct": 30}]'),
('Fresh Thai Basil', 'fresh_herb', 'herb', 'bunch', 'bunch', NULL, NULL, NULL, '{}', '[{"action": "wash_pick", "yield_pct": 60}]'),
('Fresh Lavender', 'fresh_herb', 'herb', 'bunch', 'bunch', NULL, NULL, NULL, '{}', '[{"action": "strip_stem", "yield_pct": 30}]'),
('Fresh Marjoram', 'fresh_herb', 'herb', 'bunch', 'bunch', NULL, NULL, NULL, '{}', '[{"action": "strip_stem", "yield_pct": 45}]'),
('Fresh Sorrel', 'fresh_herb', 'herb', 'bunch', 'bunch', NULL, NULL, NULL, '{}', '[{"action": "wash_stem", "yield_pct": 70}]'),
('Microgreens', 'fresh_herb', 'herb', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Fresh Shiso', 'fresh_herb', 'herb', 'bunch', 'bunch', NULL, NULL, NULL, '{}', '[{"action": "wash_pick", "yield_pct": 65}]'),
('Edible Flowers', 'fresh_herb', 'garnish', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Fresh Epazote', 'fresh_herb', 'herb', 'bunch', 'bunch', NULL, NULL, NULL, '{}', '[{"action": "wash_pick", "yield_pct": 55}]'),

-- ============================================================
-- DRY HERB (20 items)
-- ============================================================

('Dried Basil', 'dry_herb', 'herb', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Dried Oregano', 'dry_herb', 'herb', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Dried Thyme', 'dry_herb', 'herb', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Dried Rosemary', 'dry_herb', 'herb', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Dried Parsley', 'dry_herb', 'herb', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Dried Dill', 'dry_herb', 'herb', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Dried Sage', 'dry_herb', 'herb', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Dried Tarragon', 'dry_herb', 'herb', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Dried Marjoram', 'dry_herb', 'herb', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Dried Chives', 'dry_herb', 'herb', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Dried Mint', 'dry_herb', 'herb', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Dried Lavender', 'dry_herb', 'herb', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Dried Lemon Peel', 'dry_herb', 'herb', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Dried Orange Peel', 'dry_herb', 'herb', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Dried Chipotle Pepper (Whole)', 'dry_herb', 'dried_pepper', 'each', 'each', NULL, NULL, NULL, '{}', '[]'),
('Dried Ancho Pepper (Whole)', 'dry_herb', 'dried_pepper', 'each', 'each', NULL, NULL, NULL, '{}', '[]'),
('Dried Guajillo Pepper (Whole)', 'dry_herb', 'dried_pepper', 'each', 'each', NULL, NULL, NULL, '{}', '[]'),
('Dried Arbol Pepper (Whole)', 'dry_herb', 'dried_pepper', 'each', 'each', NULL, NULL, NULL, '{}', '[]'),
('Sun-Dried Tomato', 'dry_herb', 'dried_vegetable', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "rehydrate", "yield_pct": 200}]'),
('Dried Porcini Mushroom', 'dry_herb', 'dried_vegetable', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "rehydrate", "yield_pct": 250}]'),

-- ============================================================
-- CONDIMENT (32 items)
-- ============================================================

('Soy Sauce', 'condiment', 'asian_sauce', 'volume', 'ml', 1.1500, 272.08, 17.01, '{"soybeans","wheat"}', '[]'),
('Tamari (Gluten-Free Soy Sauce)', 'condiment', 'asian_sauce', 'volume', 'ml', 1.1500, 272.08, 17.01, '{"soybeans"}', '[]'),
('Fish Sauce', 'condiment', 'asian_sauce', 'volume', 'ml', 1.1500, 272.08, 17.01, '{"fish"}', '[]'),
('Oyster Sauce', 'condiment', 'asian_sauce', 'volume', 'ml', 1.2000, 283.91, 17.74, '{"shellfish","soybeans"}', '[]'),
('Hoisin Sauce', 'condiment', 'asian_sauce', 'volume', 'ml', 1.1500, 272.08, 17.01, '{"soybeans","wheat"}', '[]'),
('Sriracha', 'condiment', 'hot_sauce', 'volume', 'ml', 1.1000, 260.25, 16.27, '{}', '[]'),
('Hot Sauce (Louisiana Style)', 'condiment', 'hot_sauce', 'volume', 'ml', 1.0000, 236.59, 14.79, '{}', '[]'),
('Sambal Oelek', 'condiment', 'hot_sauce', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Gochujang', 'condiment', 'asian_sauce', 'weight', 'g', NULL, NULL, NULL, '{"soybeans","wheat"}', '[]'),
('Miso Paste (White)', 'condiment', 'asian_sauce', 'weight', 'g', NULL, NULL, NULL, '{"soybeans"}', '[]'),
('Miso Paste (Red)', 'condiment', 'asian_sauce', 'weight', 'g', NULL, NULL, NULL, '{"soybeans"}', '[]'),
('Worcestershire Sauce', 'condiment', 'western_sauce', 'volume', 'ml', 1.1000, 260.25, 16.27, '{"fish"}', '[]'),
('Dijon Mustard', 'condiment', 'mustard', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Whole Grain Mustard', 'condiment', 'mustard', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Yellow Mustard', 'condiment', 'mustard', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Ketchup', 'condiment', 'western_sauce', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Mayonnaise', 'condiment', 'western_sauce', 'weight', 'g', NULL, NULL, NULL, '{"eggs"}', '[]'),
('Red Wine Vinegar', 'condiment', 'vinegar', 'volume', 'ml', 1.0100, 238.95, 14.93, '{}', '[]'),
('White Wine Vinegar', 'condiment', 'vinegar', 'volume', 'ml', 1.0100, 238.95, 14.93, '{}', '[]'),
('Balsamic Vinegar', 'condiment', 'vinegar', 'volume', 'ml', 1.0400, 246.05, 15.38, '{}', '[]'),
('Apple Cider Vinegar', 'condiment', 'vinegar', 'volume', 'ml', 1.0100, 238.95, 14.93, '{}', '[]'),
('Rice Vinegar', 'condiment', 'vinegar', 'volume', 'ml', 1.0100, 238.95, 14.93, '{}', '[]'),
('Sherry Vinegar', 'condiment', 'vinegar', 'volume', 'ml', 1.0100, 238.95, 14.93, '{}', '[]'),
('Distilled White Vinegar', 'condiment', 'vinegar', 'volume', 'ml', 1.0100, 238.95, 14.93, '{}', '[]'),
('Capers', 'condiment', 'pickle', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "drain_rinse", "yield_pct": 90}]'),
('Cornichons', 'condiment', 'pickle', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Olives (Kalamata)', 'condiment', 'pickle', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "pit", "yield_pct": 80}]'),
('Olives (Green, Castelvetrano)', 'condiment', 'pickle', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "pit", "yield_pct": 80}]'),
('Pickled Jalapeno', 'condiment', 'pickle', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Harissa Paste', 'condiment', 'hot_sauce', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Tahini Sauce', 'condiment', 'dressing', 'volume', 'ml', 1.0500, 248.42, 15.53, '{"sesame"}', '[]'),
('Coconut Aminos', 'condiment', 'asian_sauce', 'volume', 'ml', 1.1000, 260.25, 16.27, '{}', '[]'),

-- ============================================================
-- BEVERAGE (16 items)
-- ============================================================

('Water', 'beverage', 'water', 'volume', 'ml', 1.0000, 236.59, 14.79, '{}', '[]'),
('Chicken Stock', 'beverage', 'stock', 'volume', 'ml', 1.0100, 238.95, 14.93, '{}', '[]'),
('Beef Stock', 'beverage', 'stock', 'volume', 'ml', 1.0100, 238.95, 14.93, '{}', '[]'),
('Vegetable Stock', 'beverage', 'stock', 'volume', 'ml', 1.0100, 238.95, 14.93, '{}', '[]'),
('Seafood Stock', 'beverage', 'stock', 'volume', 'ml', 1.0100, 238.95, 14.93, '{"fish","shellfish"}', '[]'),
('Bone Broth', 'beverage', 'stock', 'volume', 'ml', 1.0100, 238.95, 14.93, '{}', '[]'),
('Dashi Stock', 'beverage', 'stock', 'volume', 'ml', 1.0000, 236.59, 14.79, '{"fish"}', '[]'),
('White Wine (Dry, Cooking)', 'beverage', 'wine', 'volume', 'ml', 0.9900, 234.22, 14.64, '{}', '[]'),
('Red Wine (Dry, Cooking)', 'beverage', 'wine', 'volume', 'ml', 0.9900, 234.22, 14.64, '{}', '[]'),
('Marsala Wine', 'beverage', 'wine', 'volume', 'ml', 0.9900, 234.22, 14.64, '{}', '[]'),
('Sherry (Dry, Cooking)', 'beverage', 'wine', 'volume', 'ml', 0.9900, 234.22, 14.64, '{}', '[]'),
('Mirin', 'beverage', 'wine', 'volume', 'ml', 1.1000, 260.25, 16.27, '{}', '[]'),
('Sake (Cooking)', 'beverage', 'wine', 'volume', 'ml', 0.9900, 234.22, 14.64, '{}', '[]'),
('Beer (Lager, Cooking)', 'beverage', 'beer', 'volume', 'ml', 1.0000, 236.59, 14.79, '{"wheat"}', '[]'),
('Coffee (Brewed)', 'beverage', 'coffee', 'volume', 'ml', 1.0000, 236.59, 14.79, '{}', '[]'),
('Espresso', 'beverage', 'coffee', 'volume', 'ml', 1.0000, 236.59, 14.79, '{}', '[]'),

-- ============================================================
-- SPECIALTY (22 items)
-- ============================================================

('Truffle (Black, Fresh)', 'specialty', 'truffle', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "brush_shave", "yield_pct": 90}]'),
('Truffle (White, Fresh)', 'specialty', 'truffle', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "brush_shave", "yield_pct": 90}]'),
('Caviar', 'specialty', 'garnish', 'weight', 'g', NULL, NULL, NULL, '{"fish"}', '[]'),
('Foie Gras', 'specialty', 'protein', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "devein", "yield_pct": 85}]'),
('Wagyu Beef (A5)', 'specialty', 'protein', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "temper_slice", "yield_pct": 95}]'),
('Saffron Threads', 'specialty', 'spice', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "steep", "yield_pct": 100}]'),
('Dried Porcini Powder', 'specialty', 'mushroom', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Bonito Flakes (Katsuobushi)', 'specialty', 'japanese', 'weight', 'g', NULL, NULL, NULL, '{"fish"}', '[]'),
('Kombu (Dried Kelp)', 'specialty', 'japanese', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Nori Sheets', 'specialty', 'japanese', 'each', 'each', NULL, NULL, NULL, '{}', '[]'),
('Wakame (Dried Seaweed)', 'specialty', 'japanese', 'weight', 'g', NULL, NULL, NULL, '{}', '[{"action": "rehydrate", "yield_pct": 300}]'),
('Mirin (Premium)', 'specialty', 'japanese', 'volume', 'ml', 1.1000, 260.25, 16.27, '{}', '[]'),
('Preserved Lemon', 'specialty', 'fermented', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "rinse_mince", "yield_pct": 80}]'),
('Tamarind Paste', 'specialty', 'paste', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Rose Water', 'specialty', 'flavoring', 'volume', 'ml', 1.0000, 236.59, 14.79, '{}', '[]'),
('Orange Blossom Water', 'specialty', 'flavoring', 'volume', 'ml', 1.0000, 236.59, 14.79, '{}', '[]'),
('Matcha Powder', 'specialty', 'tea', 'weight', 'g', NULL, NULL, NULL, '{}', '[]'),
('Pomegranate Molasses', 'specialty', 'sweetener', 'volume', 'ml', 1.3500, 319.39, 19.96, '{}', '[]'),
('Yuzu Juice', 'specialty', 'citrus', 'volume', 'ml', 1.0000, 236.59, 14.79, '{}', '[]'),
('Miso (Shiro/White)', 'specialty', 'fermented', 'weight', 'g', NULL, NULL, NULL, '{"soybeans"}', '[]'),
('Kimchi', 'specialty', 'fermented', 'weight', 'g', NULL, NULL, NULL, '{"shellfish"}', '[]'),
('Umeboshi (Pickled Plum)', 'specialty', 'fermented', 'each', 'each', NULL, NULL, NULL, '{}', '[{"action": "pit_chop", "yield_pct": 80}]')

ON CONFLICT DO NOTHING;
