-- Tasting Menu Bridge: connect tasting menus to the main menu intelligence engine
-- Adds event linking and materialization tracking so tasting menus participate in
-- cost breakdown, margin alerts, allergen checks, repeat detection, dish indexing,
-- menu engineering, the what-if simulator, and the approval workflow.
-- Additive only. No drops, no destructive changes.

-- 1. Add event and materialized menu link to tasting_menus
ALTER TABLE tasting_menus
  ADD COLUMN IF NOT EXISTS event_id UUID REFERENCES events(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS materialized_menu_id UUID REFERENCES menus(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_tasting_menus_event_id
  ON tasting_menus(event_id) WHERE event_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_tasting_menus_materialized_menu_id
  ON tasting_menus(materialized_menu_id) WHERE materialized_menu_id IS NOT NULL;

COMMENT ON COLUMN tasting_menus.event_id IS
  'Links this tasting menu to an event for intelligence features';
COMMENT ON COLUMN tasting_menus.materialized_menu_id IS
  'Points to the shadow menus row generated by the sync bridge';

-- 2. Add source tracking to dishes (which tasting course generated this dish)
ALTER TABLE dishes
  ADD COLUMN IF NOT EXISTS source_tasting_course_id UUID
    REFERENCES tasting_menu_courses(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_dishes_source_tasting_course_id
  ON dishes(source_tasting_course_id) WHERE source_tasting_course_id IS NOT NULL;

COMMENT ON COLUMN dishes.source_tasting_course_id IS
  'If materialized from a tasting menu course, tracks the source for sync';

-- 3. Add source tracking to components
ALTER TABLE components
  ADD COLUMN IF NOT EXISTS source_tasting_course_id UUID
    REFERENCES tasting_menu_courses(id) ON DELETE SET NULL;

COMMENT ON COLUMN components.source_tasting_course_id IS
  'If auto-created from a tasting course recipe, tracks the source for sync';
