// PATCH /api/prospecting/[id]/draft-email
// Save a personalized email draft (generated by Ollama via n8n) to a prospect.
// Accepts: { subject?: string, body: string }

import { NextRequest, NextResponse } from 'next/server'
import { validateProspectingAuth } from '@/lib/prospecting/api-auth'
import { createServerClient } from '@/lib/supabase/server'

export async function PATCH(request: NextRequest, { params }: { params: { id: string } }) {
  const auth = await validateProspectingAuth(request)
  if (!auth) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  let body: { subject?: string; body: string }
  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 })
  }

  if (!body.body?.trim()) {
    return NextResponse.json({ error: 'body required' }, { status: 400 })
  }

  const supabase = createServerClient({ admin: true })

  // Build the draft_email field (subject + body combined)
  const draftEmail = body.subject ? `Subject: ${body.subject}\n\n${body.body}` : body.body

  const { data, error } = await supabase
    .from('prospects' as any)
    .update({ draft_email: draftEmail })
    .eq('id', params.id)
    .eq('chef_id', auth.tenantId)
    .select('id, name, draft_email')
    .single()

  if (error) {
    console.error('[prospecting/draft-email] Update error:', error)
    return NextResponse.json({ error: 'Update failed' }, { status: 500 })
  }

  if (!data) {
    return NextResponse.json({ error: 'Prospect not found' }, { status: 404 })
  }

  return NextResponse.json({ success: true, prospect: data })
}
