import type { UniversalRailItemDefinition } from '../universal-rail-types'
import { PUBLIC_RAIL_REGISTRY } from './public-rail-registry'

// Guest role: includes all public items + 37 guest-specific items
// Guest-specific items include persistence (abandoned drafts, browse patterns),
// conversion nudges, and cross-sell items

export const GUEST_SPECIFIC_ITEMS: readonly UniversalRailItemDefinition[] = [
  // ──────────────────────────────────────────────
  // Guest Persistence (14 items)
  // ──────────────────────────────────────────────

  {
    id: 'guest.abandoned_inquiry_draft',
    role: 'guest',
    label: 'Finish your request to Chef {chefName}',
    labelTemplate: 'Finish your request to Chef {chefName}',
    category: 'guest_persistence',
    baseUrgency: 62,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['draft_state', 'saved_chefs', 'browse_history'],
    freshnessWindow: '14d',
    pageAffinity: '/,/chef/{slug},/eat,/chefs,/book',
    pageAffinityBoost: 30,
    href: '/chef/{slug}/inquire?draft=1',
    hrefTemplate: '/chef/{slug}/inquire?draft=1',
    dataSources: ['discovery_interactions', 'draft_store'],
    privacy: 'account_private',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 6,
    cooldownMinutes: 1440,
    renderHints: { presentation: 'card', icon: 'chef' },
    scoringNotes:
      '+20 if draft has date/party size/menu notes. -30 if guest saved a different chef. Suppress if submitted. Expires 14 days after last draft update.',
  },

  {
    id: 'guest.browse_pattern',
    role: 'guest',
    label: 'More {patternLabel}',
    labelTemplate: 'More {patternLabel}',
    category: 'guest_persistence',
    baseUrgency: 44,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['browse_history', 'cuisine_affinity', 'dwell_time'],
    freshnessWindow: '21d',
    pageAffinity: '/,/eat,/chefs,/cuisines/{slug},/ingredients',
    pageAffinityBoost: 18,
    href: '/eat?{dominantFacet}={slug}',
    hrefTemplate: '/eat?{dominantFacet}={slug}',
    dataSources: ['discovery_interactions', 'discovery_profile_items'],
    privacy: 'account_private',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'toggle_filter',
    maxImpressions: 12,
    cooldownMinutes: 720,
    renderHints: { presentation: 'pill', icon: 'spark' },
    scoringNotes:
      '+5 per repeated interaction capped at +25. Requires at least 3 related events. Feeds preference_evolution.',
  },

  {
    id: 'guest.budget_memory',
    role: 'guest',
    label: '{budgetLabel} fits your recent searches',
    labelTemplate: '{budgetLabel} fits your recent searches',
    category: 'guest_persistence',
    baseUrgency: 39,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['browse_history', 'price_filters'],
    freshnessWindow: '30d',
    pageAffinity: '/eat,/chefs,/chef/{slug},/book',
    pageAffinityBoost: 18,
    href: '/eat?budget={budgetSlug}',
    hrefTemplate: '/eat?budget={budgetSlug}',
    dataSources: ['discovery_interactions', 'discovery_profile_items', 'chef_marketplace_profiles'],
    privacy: 'account_private',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'toggle_filter',
    maxImpressions: 10,
    cooldownMinutes: 720,
    renderHints: { presentation: 'badge', icon: 'stack' },
    scoringNotes:
      '+15 if same budget used twice. +10 if saved chefs share price tier. -20 if user dismisses price guidance.',
  },

  {
    id: 'guest.comparison_history',
    role: 'guest',
    label: 'You compared {count} {label} chefs',
    labelTemplate: 'You compared {count} {label} chefs',
    category: 'guest_persistence',
    baseUrgency: 57,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['compare_state', 'saved_chefs', 'browse_history'],
    freshnessWindow: '30d',
    pageAffinity: '/,/compare,/eat,/chefs',
    pageAffinityBoost: 32,
    href: '/eat?mode=compare&cmp={shareSafeIds}',
    hrefTemplate: '/eat?mode=compare&cmp={shareSafeIds}',
    dataSources: ['discovery_interactions', 'consumer_saved_chefs'],
    privacy: 'account_private',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 8,
    cooldownMinutes: 1440,
    renderHints: { presentation: 'card', icon: 'search' },
    scoringNotes:
      '+20 for 2+ compared chefs. +10 if any are saved. +12 if viewed one candidate again. Suppresses generic compare_tool.',
  },

  {
    id: 'guest.preference_evolution',
    role: 'guest',
    label: 'You seem to love {preferenceLabel}',
    labelTemplate: 'You seem to love {preferenceLabel}',
    category: 'guest_persistence',
    baseUrgency: 47,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['browse_history', 'saved_chefs', 'dwell_time'],
    freshnessWindow: '30d',
    pageAffinity: '/,/eat,/chefs,/ingredients',
    pageAffinityBoost: 20,
    href: '/account/preferences?review={signalId}',
    hrefTemplate: '/account/preferences?review={signalId}',
    dataSources: ['discovery_interactions', 'discovery_profile_items'],
    privacy: 'account_private',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: 8,
    cooldownMinutes: 2880,
    renderHints: { presentation: 'badge', icon: 'spark' },
    scoringNotes:
      'Requires repeated behavior confidence. +20 if pattern spans saves and long dwell. Converts browse_pattern into explicit preference.',
  },

  {
    id: 'guest.recent_search',
    role: 'guest',
    label: 'Search again: {queryLabel}',
    labelTemplate: 'Search again: {queryLabel}',
    category: 'guest_persistence',
    baseUrgency: 45,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['browse_history', 'dwell_time'],
    freshnessWindow: '30d',
    pageAffinity: '/,/eat,/chefs,/nearby,/ingredients',
    pageAffinityBoost: 24,
    href: '{searchHref}',
    hrefTemplate: '{searchHref}',
    dataSources: ['discovery_interactions', 'discovery_profile_items'],
    privacy: 'account_private',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 12,
    cooldownMinutes: 720,
    renderHints: { presentation: 'pill', icon: 'search' },
    scoringNotes:
      '+18 if repeated. +12 if search had long dwell. -15 after quick back. Feeds browse_pattern and budget_memory.',
  },

  {
    id: 'guest.saved',
    role: 'guest',
    label: 'Saved: {itemLabel}',
    labelTemplate: 'Saved: {itemLabel}',
    category: 'guest_persistence',
    baseUrgency: 48,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['saved_items', 'browse_history'],
    freshnessWindow: '45d',
    pageAffinity: '/,/eat,/chefs,/ingredients,/nearby',
    pageAffinityBoost: 24,
    href: '{savedHref}',
    hrefTemplate: '{savedHref}',
    dataSources: ['discovery_profile_items', 'consumer_saved_chefs'],
    privacy: 'account_private',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 20,
    cooldownMinutes: 720,
    renderHints: { presentation: 'pill', icon: 'heart' },
    scoringNotes:
      '+25 pinned/saved. +12 recent revisit. Yields to more specific saved_chef_* and saved_location items.',
  },

  {
    id: 'guest.saved_chef_availability',
    role: 'guest',
    label: '{chefName} has openings {window}',
    labelTemplate: '{chefName} has openings {window}',
    category: 'guest_persistence',
    baseUrgency: 68,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['saved_chefs', 'time_of_day', 'seasonal_context'],
    freshnessWindow: '7d',
    pageAffinity: '/,/chef/{slug},/eat,/chefs',
    pageAffinityBoost: 35,
    href: '/chef/{slug}?dateWindow={window}#availability',
    hrefTemplate: '/chef/{slug}?dateWindow={window}#availability',
    dataSources: ['consumer_saved_chefs', 'chef_marketplace_profiles'],
    privacy: 'account_private',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 5,
    cooldownMinutes: 1440,
    renderHints: { presentation: 'card', icon: 'calendar' },
    scoringNotes:
      '+30 saved chef. +20 near weekend/holiday. +10 if viewed recently. Highest saved-chef item. Suppresses generic availability_pulse for same chef.',
  },

  {
    id: 'guest.saved_chef_resurface',
    role: 'guest',
    label: 'You saved Chef {name} {relativeTime}',
    labelTemplate: 'You saved Chef {name} {relativeTime}',
    category: 'guest_persistence',
    baseUrgency: 56,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['saved_chefs', 'browse_history', 'cuisine_affinity'],
    freshnessWindow: '45d',
    pageAffinity: '/,/eat,/chefs,/chef/{slug}',
    pageAffinityBoost: 28,
    href: '/chef/{slug}?source=saved_chef',
    hrefTemplate: '/chef/{slug}?source=saved_chef',
    dataSources: ['consumer_saved_chefs', 'chef_profiles', 'chef_marketplace_profiles'],
    privacy: 'account_private',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 10,
    cooldownMinutes: 1440,
    renderHints: { presentation: 'card', icon: 'heart' },
    scoringNotes:
      '+30 recent save. +15 matching current filters. +10 saved chef viewed again. Default saved-chef memory item.',
  },

  {
    id: 'guest.saved_chef_update',
    role: 'guest',
    label: 'Chef {name} added {updateLabel}',
    labelTemplate: 'Chef {name} added {updateLabel}',
    category: 'guest_persistence',
    baseUrgency: 61,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['saved_chefs', 'cuisine_affinity'],
    freshnessWindow: '14d',
    pageAffinity: '/,/chef/{slug},/eat,/chefs',
    pageAffinityBoost: 30,
    href: '/chef/{slug}?source=saved_update#updates',
    hrefTemplate: '/chef/{slug}?source=saved_update#updates',
    dataSources: ['consumer_saved_chefs', 'chef_profiles', 'chef_marketplace_profiles'],
    privacy: 'account_private',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 5,
    cooldownMinutes: 2880,
    renderHints: { presentation: 'card', icon: 'spark' },
    scoringNotes:
      '+30 saved chef. +20 new menu/service. +10 preference match. Outranks saved_chef_resurface for same chef.',
  },

  {
    id: 'guest.saved_location',
    role: 'guest',
    label: 'Your {placeLabel} picks',
    labelTemplate: 'Your {placeLabel} picks',
    category: 'guest_persistence',
    baseUrgency: 50,
    urgencyDecayFn: 'none',
    relevanceSignals: ['saved_location', 'browse_history'],
    freshnessWindow: '30d',
    pageAffinity: '/,/eat,/chefs,/nearby',
    pageAffinityBoost: 30,
    href: '/eat?location={encodedPlace}',
    hrefTemplate: '/eat?location={encodedPlace}',
    dataSources: ['discovery_profile_items', 'chef_marketplace_profiles'],
    privacy: 'account_private',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'toggle_filter',
    maxImpressions: 30,
    cooldownMinutes: 360,
    renderHints: { presentation: 'badge', icon: 'location' },
    scoringNotes:
      '+25 default location. +10 local results clicked. Powers local social proof, events, availability, and featured chefs.',
  },

  // ──────────────────────────────────────────────
  // Guest Capabilities (2 items)
  // ──────────────────────────────────────────────

  {
    id: 'guest.compare_tool',
    role: 'guest',
    label: 'Compare chefs side by side',
    labelTemplate: 'Compare chefs side by side',
    category: 'guest_capability',
    baseUrgency: 34,
    urgencyDecayFn: 'none',
    relevanceSignals: ['browse_history', 'saved_chefs'],
    freshnessWindow: '1h',
    pageAffinity: '/eat,/chefs,/chef/{slug},/compare',
    pageAffinityBoost: 25,
    href: '/eat?mode=compare',
    hrefTemplate: '/eat?mode=compare',
    dataSources: ['chef_marketplace_profiles', 'consumer_saved_chefs'],
    privacy: 'account_private',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: 12,
    cooldownMinutes: 720,
    renderHints: { presentation: 'pill', icon: 'search' },
    scoringNotes:
      '+15 on chef listings. +10 after second chef profile view. -20 if no comparable cards. Yields to comparison_history.',
  },

  // ──────────────────────────────────────────────
  // Conversion Nudges (8 items)
  // ──────────────────────────────────────────────

  {
    id: 'guest.chef_facing_content_nudge',
    role: 'guest',
    label: 'Are you a chef? Create your profile',
    labelTemplate: 'Are you a chef? Create your profile',
    category: 'conversion_nudge',
    baseUrgency: 36,
    urgencyDecayFn: 'none',
    relevanceSignals: ['route_history', 'browse_history'],
    freshnessWindow: '30d',
    pageAffinity: '/for-operators,/partner-signup,/nearby/submit,/chef/{slug}/partner-signup',
    pageAffinityBoost: 35,
    href: '/partner-signup?source=guest_rail',
    hrefTemplate: '/partner-signup?source=guest_rail',
    dataSources: ['discovery_interactions'],
    privacy: 'account_private',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 5,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'badge', icon: 'chef' },
    scoringNotes:
      '+25 after chef-facing route visits. +10 after operator comparison content. -40 after client-intent searches. Only one role-choice nudge per rail pass.',
  },

  {
    id: 'guest.dietary_setup_nudge',
    role: 'guest',
    label: 'Set your dietary needs',
    labelTemplate: 'Set your dietary needs',
    category: 'conversion_nudge',
    baseUrgency: 46,
    urgencyDecayFn: 'none',
    relevanceSignals: ['dietary_filters', 'browse_history'],
    freshnessWindow: '30d',
    pageAffinity: '/eat,/chefs,/ingredients,/chef/{slug}',
    pageAffinityBoost: 24,
    href: '/account/preferences?section=dietary',
    hrefTemplate: '/account/preferences?section=dietary',
    dataSources: ['discovery_interactions', 'discovery_profile_items'],
    privacy: 'account_private',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: 6,
    cooldownMinutes: 4320,
    renderHints: { presentation: 'badge', icon: 'leaf' },
    scoringNotes:
      '+20 after dietary filter used twice. +15 after safe-for-me clicks. Do not infer allergies without confirmation. Converts repeated dietary usage into saved preference.',
  },

  {
    id: 'guest.dinner_circle_nudge',
    role: 'guest',
    label: 'Join a dinner circle',
    labelTemplate: 'Join a dinner circle',
    category: 'conversion_nudge',
    baseUrgency: 37,
    urgencyDecayFn: 'none',
    relevanceSignals: ['browse_history', 'group_size_filters'],
    freshnessWindow: '30d',
    pageAffinity: '/hub,/hub/circles,/eat',
    pageAffinityBoost: 24,
    href: '/hub/circles?source=guest_rail',
    hrefTemplate: '/hub/circles?source=guest_rail',
    dataSources: ['discovery_interactions'],
    privacy: 'account_private',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 5,
    cooldownMinutes: 4320,
    renderHints: { presentation: 'card', icon: 'family' },
    scoringNotes:
      '+20 after group size 5+. +10 after party/occasion searches. -10 if solo/date-night intent. Suppresses generic circle in same rail slice.',
  },

  {
    id: 'guest.first_booking_nudge',
    role: 'guest',
    label: 'Book your first dinner',
    labelTemplate: 'Book your first dinner',
    category: 'conversion_nudge',
    baseUrgency: 43,
    urgencyDecayFn: 'none',
    relevanceSignals: ['saved_chefs', 'browse_history', 'compare_state'],
    freshnessWindow: '30d',
    pageAffinity: '/,/chef/{slug},/chefs,/eat,/book',
    pageAffinityBoost: 24,
    href: '/book?source=guest_rail',
    hrefTemplate: '/book?source=guest_rail',
    dataSources: ['discovery_interactions', 'consumer_saved_chefs'],
    privacy: 'account_private',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 4,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'badge', icon: 'spark' },
    scoringNotes:
      'Activates after 3+ chef profile views, 2+ saves, or compare session. Never before meaningful intent. Suppressed by abandoned_inquiry_draft.',
  },

  {
    id: 'guest.location_save_nudge',
    role: 'guest',
    label: 'Save {place} for faster discovery',
    labelTemplate: 'Save {place} for faster discovery',
    category: 'conversion_nudge',
    baseUrgency: 41,
    urgencyDecayFn: 'none',
    relevanceSignals: ['browse_history', 'location_searches'],
    freshnessWindow: '30d',
    pageAffinity: '/eat,/chefs,/nearby,/',
    pageAffinityBoost: 26,
    href: '/account/preferences?section=location',
    hrefTemplate: '/account/preferences?section=location',
    dataSources: ['discovery_interactions', 'discovery_profile_items'],
    privacy: 'account_private',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: 5,
    cooldownMinutes: 4320,
    renderHints: { presentation: 'badge', icon: 'location' },
    scoringNotes:
      'Activates after 2+ location searches or one long dwell on local results. Converts ephemeral location into durable context.',
  },

  {
    id: 'guest.personalized_recs_nudge',
    role: 'guest',
    label: 'Get personalized recommendations',
    labelTemplate: 'Get personalized recommendations',
    category: 'conversion_nudge',
    baseUrgency: 44,
    urgencyDecayFn: 'none',
    relevanceSignals: ['browse_history', 'session_depth'],
    freshnessWindow: '30d',
    pageAffinity: '/,/eat,/chefs',
    pageAffinityBoost: 18,
    href: '/account/preferences?source=guest_rail',
    hrefTemplate: '/account/preferences?source=guest_rail',
    dataSources: ['discovery_interactions', 'discovery_profile_items'],
    privacy: 'account_private',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 5,
    cooldownMinutes: 4320,
    renderHints: { presentation: 'card', icon: 'spark' },
    scoringNotes:
      'Activates after 10+ interactions without accepted preferences. Suppressed by taste_profile_completion when profile started.',
  },

  {
    id: 'guest.profile_progress',
    role: 'guest',
    label: 'Your taste profile: {percent}%',
    labelTemplate: 'Your taste profile: {percent}%',
    category: 'conversion_nudge',
    baseUrgency: 49,
    urgencyDecayFn: 'none',
    relevanceSignals: ['profile_completeness', 'saved_chefs'],
    freshnessWindow: '30d',
    pageAffinity: '/,/eat,/chefs,/account/preferences',
    pageAffinityBoost: 20,
    href: '/account/preferences',
    hrefTemplate: '/account/preferences',
    dataSources: ['discovery_profile_items', 'consumer_saved_chefs'],
    privacy: 'account_private',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: 10,
    cooldownMinutes: 1440,
    renderHints: { presentation: 'progress', icon: 'progress' },
    scoringNotes:
      '+15 when any profile section started. +10 after saves. Avoid before first meaningful signal. Suppresses personalized_recs_nudge.',
  },

  {
    id: 'guest.taste_profile_completion',
    role: 'guest',
    label: 'Complete your taste profile',
    labelTemplate: 'Complete your taste profile',
    category: 'conversion_nudge',
    baseUrgency: 50,
    urgencyDecayFn: 'none',
    relevanceSignals: ['profile_completeness', 'browse_history', 'saved_chefs'],
    freshnessWindow: '30d',
    pageAffinity: '/,/eat,/chefs,/account/preferences',
    pageAffinityBoost: 22,
    href: '/account/preferences?source=guest_rail',
    hrefTemplate: '/account/preferences?source=guest_rail',
    dataSources: ['discovery_profile_items', 'consumer_saved_chefs', 'discovery_interactions'],
    privacy: 'account_private',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: 6,
    cooldownMinutes: 4320,
    renderHints: { presentation: 'progress', icon: 'progress' },
    scoringNotes:
      'Activates after 5+ interactions or one saved chef. +20 if profile partially started. Suppresses personalized_recs_nudge. Feeds all personalized scoring.',
  },

  // ──────────────────────────────────────────────
  // Seasonal and Timely (4 items)
  // ──────────────────────────────────────────────

  {
    id: 'guest.holiday_plan',
    role: 'guest',
    label: 'Plan your {holidayName} dinner',
    labelTemplate: 'Plan your {holidayName} dinner',
    category: 'seasonal_timely',
    baseUrgency: 72,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['seasonal_context', 'saved_chefs', 'browse_history'],
    freshnessWindow: '7d',
    pageAffinity: '/,/eat,/chefs,/cuisines/{slug}',
    pageAffinityBoost: 40,
    href: '/eat?intent=holiday_party&dateWindow={holidayWindow}',
    hrefTemplate: '/eat?intent=holiday_party&dateWindow={holidayWindow}',
    dataSources: [
      'seasonal_calendar',
      'editorial_slots',
      'chef_marketplace_profiles',
      'consumer_saved_chefs',
    ],
    privacy: 'public',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 8,
    cooldownMinutes: 1440,
    renderHints: { presentation: 'card', icon: 'confetti' },
    scoringNotes:
      '+20 near deadline. +15 if group/occasion browsing. +10 if saved chef fits holiday menus. Starts 60 days before major holiday.',
  },

  {
    id: 'guest.local_event',
    role: 'guest',
    label: '{eventName} near you',
    labelTemplate: '{eventName} near you',
    category: 'seasonal_timely',
    baseUrgency: 48,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['saved_location', 'cuisine_affinity', 'seasonal_context'],
    freshnessWindow: '7d',
    pageAffinity: '/,/nearby,/eat,/chefs',
    pageAffinityBoost: 26,
    href: '/nearby?event={eventSlug}&location={location}',
    hrefTemplate: '/nearby?event={eventSlug}&location={location}',
    dataSources: ['editorial_slots', 'seasonal_calendar', 'chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 6,
    cooldownMinutes: 1440,
    renderHints: { presentation: 'card', icon: 'market' },
    scoringNotes:
      'Requires saved or searched location. +15 if event matches cuisine preferences. Expires when event ends.',
  },

  {
    id: 'guest.seasonal_ingredient',
    role: 'guest',
    label: 'Peak: {ingredient}',
    labelTemplate: 'Peak: {ingredient}',
    category: 'seasonal_timely',
    baseUrgency: 54,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['seasonal_context', 'cuisine_affinity', 'saved_location'],
    freshnessWindow: '14d',
    pageAffinity: '/,/ingredients,/ingredient/{id},/eat',
    pageAffinityBoost: 30,
    href: '/ingredient/{id}?source=guest_rail',
    hrefTemplate: '/ingredient/{id}?source=guest_rail',
    dataSources: ['ingredient_taxonomy', 'seasonal_calendar', 'chef_culinary_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 10,
    cooldownMinutes: 1440,
    renderHints: { presentation: 'card', icon: 'market' },
    scoringNotes:
      '+20 seasonal peak. +15 saved/clicked cuisine match. +10 local event/farm market match. Avoids allergens.',
  },

  {
    id: 'guest.weekend_availability',
    role: 'guest',
    label: "This weekend's availability",
    labelTemplate: "This weekend's availability",
    category: 'seasonal_timely',
    baseUrgency: 66,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['saved_location', 'saved_chefs', 'time_of_day'],
    freshnessWindow: '24h',
    pageAffinity: '/,/eat,/chefs,/nearby',
    pageAffinityBoost: 34,
    href: '/eat?dateWindow=this_weekend&location={place}',
    hrefTemplate: '/eat?dateWindow=this_weekend&location={place}',
    dataSources: ['chef_marketplace_profiles', 'consumer_saved_chefs'],
    privacy: 'account_private',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 8,
    cooldownMinutes: 720,
    renderHints: { presentation: 'card', icon: 'calendar' },
    scoringNotes:
      '+20 Wednesday-Friday. +20 saved location. +15 saved chef availability. Starts Monday, expires Sunday night. Suppresses generic time when active.',
  },

  // ──────────────────────────────────────────────
  // Social Proof (4 items)
  // ──────────────────────────────────────────────

  {
    id: 'guest.most_saved_chef',
    role: 'guest',
    label: 'Most saved chef near {place}',
    labelTemplate: 'Most saved chef near {place}',
    category: 'social_proof',
    baseUrgency: 46,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['saved_location', 'cuisine_affinity'],
    freshnessWindow: '7d',
    pageAffinity: '/,/chefs,/nearby,/eat',
    pageAffinityBoost: 22,
    href: '/chef/{slug}?source=most_saved',
    hrefTemplate: '/chef/{slug}?source=most_saved',
    dataSources: ['consumer_saved_chefs', 'chef_profiles', 'chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 8,
    cooldownMinutes: 1440,
    renderHints: { presentation: 'card', icon: 'heart' },
    scoringNotes:
      'Requires k-anonymous aggregate threshold. +15 if cuisine matches guest. Recompute daily. Can become saved_chef_resurface if guest saves.',
  },

  {
    id: 'guest.review_highlight',
    role: 'guest',
    label: '{quoteSnippet}',
    labelTemplate: '{quoteSnippet}',
    category: 'social_proof',
    baseUrgency: 35,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['cuisine_affinity', 'saved_chefs'],
    freshnessWindow: '30d',
    pageAffinity: '/,/chef/{slug},/chefs,/eat',
    pageAffinityBoost: 16,
    href: '/chef/{slug}#reviews',
    hrefTemplate: '/chef/{slug}#reviews',
    dataSources: ['chef_profiles', 'chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 6,
    cooldownMinutes: 1440,
    renderHints: { presentation: 'story', icon: 'star' },
    scoringNotes:
      '+12 if review cuisine/occasion matches guest. +8 if chef is saved or viewed. Rotates after 30 days.',
  },

  {
    id: 'guest.social_booking_count',
    role: 'guest',
    label: '{count} people booked {targetLabel} this month',
    labelTemplate: '{count} people booked {targetLabel} this month',
    category: 'social_proof',
    baseUrgency: 42,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['browse_history', 'cuisine_affinity'],
    freshnessWindow: '24h',
    pageAffinity: '/,/chef/{slug},/chefs,/eat',
    pageAffinityBoost: 18,
    href: '{proofHref}',
    hrefTemplate: '{proofHref}',
    dataSources: ['discovery_interactions', 'chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 6,
    cooldownMinutes: 1440,
    renderHints: { presentation: 'badge', icon: 'users' },
    scoringNotes:
      'Must pass aggregate threshold. +12 if target matches guest preferences. Never stacks more than two social proof items.',
  },

  {
    id: 'guest.trending_cuisine_nearby',
    role: 'guest',
    label: '{cuisineName} is trending near {place}',
    labelTemplate: '{cuisineName} is trending near {place}',
    category: 'social_proof',
    baseUrgency: 48,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['saved_location', 'cuisine_affinity', 'browse_history'],
    freshnessWindow: '7d',
    pageAffinity: '/,/eat,/chefs,/nearby,/cuisines/{slug}',
    pageAffinityBoost: 24,
    href: '/eat?cuisine={slug}&location={place}',
    hrefTemplate: '/eat?cuisine={slug}&location={place}',
    dataSources: ['discovery_interactions', 'chef_marketplace_profiles', 'consumer_saved_chefs'],
    privacy: 'public',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'toggle_filter',
    maxImpressions: 8,
    cooldownMinutes: 1440,
    renderHints: { presentation: 'badge', icon: 'flame' },
    scoringNotes:
      '+18 saved location. +15 cuisine preference. +10 local event overlap. Suppress if user hid cuisine.',
  },

  // ──────────────────────────────────────────────
  // Recovery (2 items)
  // ──────────────────────────────────────────────

  {
    id: 'guest.recovery_empty_results',
    role: 'guest',
    label: 'No perfect matches yet',
    labelTemplate: 'No perfect matches yet',
    category: 'recovery',
    baseUrgency: 76,
    urgencyDecayFn: 'none',
    relevanceSignals: ['route_context', 'active_filters'],
    freshnessWindow: '0',
    pageAffinity: '/eat,/chefs,/nearby',
    pageAffinityBoost: 45,
    href: '/eat?{broadenedParams}',
    hrefTemplate: '/eat?{broadenedParams}',
    dataSources: ['chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'search' },
    scoringNotes:
      'Highest priority only in empty/sparse result context. Temporarily suppresses most discovery items. Can show abandoned_inquiry_draft alongside.',
  },

  {
    id: 'guest.recovery_not_found',
    role: 'guest',
    label: 'That page moved',
    labelTemplate: 'That page moved',
    category: 'recovery',
    baseUrgency: 70,
    urgencyDecayFn: 'none',
    relevanceSignals: ['route_context'],
    freshnessWindow: '0',
    pageAffinity: '/404',
    pageAffinityBoost: 45,
    href: '/eat?source=recovery&from={routeKind}',
    hrefTemplate: '/eat?source=recovery&from={routeKind}',
    dataSources: ['chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'search' },
    scoringNotes:
      'Route-context priority only. If chef slug known, show similar chefs. Suppresses conversion nudges.',
  },

  // ──────────────────────────────────────────────
  // Cross-Sell (2 items)
  // ──────────────────────────────────────────────

  {
    id: 'guest.cross_sell_gift_card',
    role: 'guest',
    label: 'Give the gift of a private chef',
    labelTemplate: 'Give the gift of a private chef',
    category: 'cross_sell',
    baseUrgency: 21,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['seasonal_context', 'saved_chefs'],
    freshnessWindow: '30d',
    pageAffinity: '/gift-cards,/chef/{slug},/,/eat',
    pageAffinityBoost: 18,
    href: '/gift-cards?source=guest_rail',
    hrefTemplate: '/gift-cards?source=guest_rail',
    dataSources: ['editorial_slots', 'consumer_saved_chefs'],
    privacy: 'public',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 4,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'card', icon: 'gift' },
    scoringNotes:
      '+18 near holidays. +10 if viewing chef gift card page. Low baseline to avoid pushiness. Never appears next to first_booking_nudge.',
  },

  {
    id: 'guest.cross_sell_referral',
    role: 'guest',
    label: 'Invite friends, get rewards',
    labelTemplate: 'Invite friends, get rewards',
    category: 'cross_sell',
    baseUrgency: 18,
    urgencyDecayFn: 'none',
    relevanceSignals: ['saved_chefs', 'compare_state'],
    freshnessWindow: '30d',
    pageAffinity: '/,/eat,/chefs,/hub',
    pageAffinityBoost: 8,
    href: '/account/referrals?source=guest_rail',
    hrefTemplate: '/account/referrals?source=guest_rail',
    dataSources: [],
    privacy: 'account_private',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: 4,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'badge', icon: 'share' },
    scoringNotes:
      '+10 after 2+ saves or compare session. -20 before any meaningful interaction. Lower priority than discovery and persistence.',
  },
] as const

// Full guest registry: public items (remapped to guest role) + guest-specific
export const GUEST_RAIL_REGISTRY: readonly UniversalRailItemDefinition[] = [
  ...PUBLIC_RAIL_REGISTRY.map((item) => ({
    ...item,
    role: 'guest' as const,
    id: item.id.replace('public.', 'guest.'),
  })),
  ...GUEST_SPECIFIC_ITEMS,
] as const
