import type { UniversalRailItemDefinition } from '../universal-rail-types'

// Partner role: 76 items. Scoped to own referrals/events. NEVER sees other partners.

// ============================================================================
// Referral Tracking (11 items)
// ============================================================================

const REFERRAL_TRACKING: UniversalRailItemDefinition[] = [
  {
    id: 'partner.referral_converted',
    role: 'partner',
    label: 'Referral Converted',
    labelTemplate: 'Your referral {clientFirstName} booked a chef!',
    category: 'Referral Tracking',
    baseUrgency: 78,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['first_conversion', 'event_proximity', 'view_count'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 30,
    href: '/partner/events',
    hrefTemplate: '/partner/events?referral={referralId}',
    dataSources: ['events', 'inquiries', 'referral_attributions'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 8,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'story', icon: 'Handshake', priority: 'high' },
    scoringNotes: '+15 if first converted referral; +10 if event is soon; -20 after viewed twice',
  },
  {
    id: 'partner.referral_pending',
    role: 'partner',
    label: 'Referral Pending',
    labelTemplate: '{clientFirstName} signed up from your link',
    category: 'Referral Tracking',
    baseUrgency: 48,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['activity_recency', 'high_intent_inquiry'],
    freshnessWindow: '45d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 20,
    href: '/partner/dashboard',
    hrefTemplate: '/partner/dashboard?rail=referrals&referral={referralId}',
    dataSources: ['referral_attributions', 'clients', 'inquiries'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 12,
    cooldownMinutes: 4320,
    renderHints: { presentation: 'pill', icon: 'UserPlus', priority: 'normal' },
    scoringNotes:
      '+10 if activity in last 7 days; +8 if high-intent inquiry; decays after 14 inactive days',
  },
  {
    id: 'partner.referral_link_performance',
    role: 'partner',
    label: 'Link Performance',
    labelTemplate: 'Your link got {clickCount} clicks this week',
    category: 'Referral Tracking',
    baseUrgency: 34,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['click_trend', 'conversion_change', 'active_campaign'],
    freshnessWindow: '7d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 15,
    href: '/partner/dashboard',
    hrefTemplate: '/partner/dashboard?rail=link-performance',
    dataSources: ['partner_referral_clicks', 'analytics_events'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 10,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'card', icon: 'MousePointerClick', priority: 'low' },
    scoringNotes: '+10 if clicks up >25%; +15 if conversion changed materially',
  },
  {
    id: 'partner.referral_earning_created',
    role: 'partner',
    label: 'Earning Created',
    labelTemplate: "You earned {amount} from {clientFirstName}'s booking",
    category: 'Referral Tracking',
    baseUrgency: 70,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['first_earning', 'amount_vs_average'],
    freshnessWindow: '45d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 25,
    href: '/partner/dashboard',
    hrefTemplate: '/partner/dashboard?rail=earnings&earning={earningId}',
    dataSources: ['partner_commissions', 'events'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 8,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'card', icon: 'CircleDollarSign', priority: 'high' },
    scoringNotes: '+10 for first earning; +8 when amount exceeds partner average',
  },
  {
    id: 'partner.referral_payout_ready',
    role: 'partner',
    label: 'Payout Ready',
    labelTemplate: '{amount} ready for payout',
    category: 'Referral Tracking',
    baseUrgency: 82,
    urgencyDecayFn: 'none',
    relevanceSignals: ['payout_method_missing', 'balance_vs_average'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 35,
    href: '/partner/profile',
    hrefTemplate: '/partner/profile?payout=ready',
    dataSources: ['partner_payouts', 'partner_commissions'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'WalletCards', priority: 'high' },
    scoringNotes: '+20 if payout method missing; +10 if balance > historical average',
  },
  {
    id: 'partner.referral_payout_processed',
    role: 'partner',
    label: 'Payout Processed',
    labelTemplate: '{amount} sent to your account',
    category: 'Referral Tracking',
    baseUrgency: 42,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['payout_value', 'view_count'],
    freshnessWindow: '21d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 12,
    href: '/partner/dashboard',
    hrefTemplate: '/partner/dashboard?rail=payouts&payout={payoutId}',
    dataSources: ['partner_payouts'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 5,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'badge', icon: 'BadgeCheck', priority: 'low' },
    scoringNotes: '+10 on high-value payout; -15 after viewed',
  },
  {
    id: 'partner.referral_code_expiring',
    role: 'partner',
    label: 'Code Expiring',
    labelTemplate: '{campaignName} code expires {date}',
    category: 'Referral Tracking',
    baseUrgency: 68,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['expiry_proximity', 'unused_value', 'copy_state'],
    freshnessWindow: '14d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 20,
    href: '/partner/profile',
    hrefTemplate: '/partner/profile?campaign={campaignId}',
    dataSources: ['partner_campaigns', 'referral_codes'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: -1,
    cooldownMinutes: 1440,
    renderHints: { presentation: 'alert', icon: 'TimerReset', priority: 'normal' },
    scoringNotes: '+25 inside 72h; +10 if code has unused value; -20 after copied',
  },
  {
    id: 'partner.top_referral_channel',
    role: 'partner',
    label: 'Top Channel',
    labelTemplate: '{channelName} is your top channel',
    category: 'Referral Tracking',
    baseUrgency: 30,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['channel_performance', 'marketing_asset_launch'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 15,
    href: '/partner/dashboard',
    hrefTemplate: '/partner/dashboard?rail=channels',
    dataSources: ['analytics_events', 'referral_attributions'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 8,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'card', icon: 'TrendingUp', priority: 'low' },
    scoringNotes: '+10 when channel beats baseline; +5 after new marketing asset launch',
  },
  {
    id: 'partner.monthly_referral_summary',
    role: 'partner',
    label: 'Monthly Summary',
    labelTemplate: '{monthName}: {bookings} bookings from your referrals',
    category: 'Referral Tracking',
    baseUrgency: 38,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['new_best_month', 'quarter_close'],
    freshnessWindow: '60d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 18,
    href: '/partner/dashboard',
    hrefTemplate: '/partner/dashboard?rail=monthly-summary&month={yyyyMm}',
    dataSources: ['referral_attributions', 'partner_commissions'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 6,
    cooldownMinutes: 20160,
    renderHints: { presentation: 'story', icon: 'BarChart3', priority: 'low' },
    scoringNotes: '+12 on new best month; +8 at quarter close',
  },
  {
    id: 'partner.referral_milestone',
    role: 'partner',
    label: 'Referral Milestone',
    labelTemplate: "You've referred {milestoneCount} clients!",
    category: 'Referral Tracking',
    baseUrgency: 52,
    urgencyDecayFn: 'none',
    relevanceSignals: ['milestone_significance', 'reward_unlock'],
    freshnessWindow: '90d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 20,
    href: '/partner/dashboard',
    hrefTemplate: '/partner/dashboard?rail=milestone',
    dataSources: ['referral_attributions', 'partner_tiers'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: 10,
    cooldownMinutes: 20160,
    renderHints: { presentation: 'story', icon: 'Trophy', priority: 'normal' },
    scoringNotes: '+20 for first, tenth, fiftieth referrals; +10 if reward unlocks',
  },
  {
    id: 'partner.inactive_referral_period',
    role: 'partner',
    label: 'Inactive Referrals',
    labelTemplate: 'No new referrals in {daysInactive} days',
    category: 'Referral Tracking',
    baseUrgency: 44,
    urgencyDecayFn: 'none',
    relevanceSignals: ['inactivity_duration', 'link_copy_recency'],
    freshnessWindow: '90d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 20,
    href: '/partner/profile',
    hrefTemplate: '/partner/profile?share=referral-link',
    dataSources: ['referral_attributions', 'partner_referral_clicks'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: 8,
    cooldownMinutes: 4320,
    renderHints: { presentation: 'pill', icon: 'Share2', priority: 'normal' },
    scoringNotes: '+12 after 30 days; +20 after 60 days; -10 if partner recently copied link',
  },
]

// ============================================================================
// Co-hosting and Venue (16 items)
// ============================================================================

const COHOSTING_AND_VENUE: UniversalRailItemDefinition[] = [
  {
    id: 'partner.cohost_event_upcoming',
    role: 'partner',
    label: 'Upcoming Co-hosted Event',
    labelTemplate: '{eventName} {eventDate}',
    category: 'Co-hosting and Venue',
    baseUrgency: 72,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['event_proximity', 'tasks_incomplete', 'outdoor_venue'],
    freshnessWindow: '7d',
    pageAffinity: '/partner/events',
    pageAffinityBoost: 35,
    href: '/partner/events',
    hrefTemplate: '/partner/events?event={eventId}',
    dataSources: ['events', 'partner_locations'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'card', icon: 'CalendarDays', priority: 'high' },
    scoringNotes: '+20 inside 72h; +10 if tasks incomplete; +15 if outdoor venue',
  },
  {
    id: 'partner.cohost_event_readiness',
    role: 'partner',
    label: 'Event Readiness',
    labelTemplate: '{eventName}: {readyPercent}% ready',
    category: 'Co-hosting and Venue',
    baseUrgency: 76,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['readiness_pct', 'overdue_tasks', 'event_proximity'],
    freshnessWindow: '7d',
    pageAffinity: '/partner/events',
    pageAffinityBoost: 35,
    href: '/partner/events',
    hrefTemplate: '/partner/events?event={eventId}&tab=readiness',
    dataSources: ['events', 'event_tasks', 'collaboration_tasks'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'progress', icon: 'ListChecks', priority: 'high' },
    scoringNotes: '+25 if <70% within 72h; +15 if partner-owned task overdue',
  },
  {
    id: 'partner.venue_availability_request',
    role: 'partner',
    label: 'Venue Request',
    labelTemplate: 'Chef {chefFirstName} wants {locationName}',
    category: 'Co-hosting and Venue',
    baseUrgency: 84,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['response_deadline', 'location_demand', 'view_state'],
    freshnessWindow: '7d',
    pageAffinity: '/partner/locations',
    pageAffinityBoost: 40,
    href: '/partner/locations',
    hrefTemplate: '/partner/locations/{locationId}?request={requestId}',
    dataSources: ['partner_location_requests', 'events', 'partner_locations'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'MapPinned', priority: 'high' },
    scoringNotes:
      '+25 inside 48h; +10 if location is high-demand; -20 if viewed and pending response',
  },
  {
    id: 'partner.venue_booking_confirmed',
    role: 'partner',
    label: 'Venue Booked',
    labelTemplate: '{locationName} is booked for {eventDate}',
    category: 'Co-hosting and Venue',
    baseUrgency: 58,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['first_booking', 'revenue_split'],
    freshnessWindow: '14d',
    pageAffinity: '/partner/locations',
    pageAffinityBoost: 25,
    href: '/partner/events',
    hrefTemplate: '/partner/events?event={eventId}',
    dataSources: ['events', 'partner_locations'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 8,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'card', icon: 'BadgeCheck', priority: 'normal' },
    scoringNotes: '+10 for first booking at location; +8 if revenue split exists',
  },
  {
    id: 'partner.venue_booking_canceled',
    role: 'partner',
    label: 'Venue Booking Canceled',
    labelTemplate: '{eventName} was canceled',
    category: 'Co-hosting and Venue',
    baseUrgency: 70,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['cancellation_recency', 'settlement_affected'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/events',
    pageAffinityBoost: 30,
    href: '/partner/events',
    hrefTemplate: '/partner/events?event={eventId}',
    dataSources: ['events'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 12,
    cooldownMinutes: 4320,
    renderHints: { presentation: 'alert', icon: 'CalendarX', priority: 'high' },
    scoringNotes: '+15 if within 7 days; +10 if partner settlement affected',
  },
  {
    id: 'partner.cohost_task_assigned',
    role: 'partner',
    label: 'Co-host Task',
    labelTemplate: '{taskTitle}',
    category: 'Co-hosting and Venue',
    baseUrgency: 80,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['overdue_state', 'due_proximity', 'blocks_chef'],
    freshnessWindow: '7d',
    pageAffinity: '/partner/events',
    pageAffinityBoost: 40,
    href: '/partner/events',
    hrefTemplate: '/partner/events?event={eventId}&task={taskId}',
    dataSources: ['event_tasks', 'collaboration_tasks'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'ClipboardList', priority: 'high' },
    scoringNotes: '+25 if overdue; +15 within 24h; +10 if blocks chef',
  },
  {
    id: 'partner.cohost_ingredient_list_shared',
    role: 'partner',
    label: 'Ingredient List Shared',
    labelTemplate: 'Chef shared the ingredient list',
    category: 'Co-hosting and Venue',
    baseUrgency: 50,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['partner_must_provide', 'allergen_venue_prep'],
    freshnessWindow: '14d',
    pageAffinity: '/partner/events',
    pageAffinityBoost: 20,
    href: '/partner/events',
    hrefTemplate: '/partner/events?event={eventId}&tab=ingredients',
    dataSources: ['menus', 'recipe_ingredients'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: 8,
    cooldownMinutes: 4320,
    renderHints: { presentation: 'pill', icon: 'Carrot', priority: 'normal' },
    scoringNotes: '+15 if partner must provide items; +10 if allergens require venue prep',
  },
  {
    id: 'partner.cohost_ticket_sales_progress',
    role: 'partner',
    label: 'Ticket Sales Progress',
    labelTemplate: '{soldCount} of {capacity} tickets sold',
    category: 'Co-hosting and Venue',
    baseUrgency: 55,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['sell_through_rate', 'partner_channel_contribution'],
    freshnessWindow: '7d',
    pageAffinity: '/partner/events',
    pageAffinityBoost: 25,
    href: '/partner/events',
    hrefTemplate: '/partner/events?event={eventId}&tab=tickets',
    dataSources: ['event_tickets', 'event_ticket_types', 'event_distribution'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 12,
    cooldownMinutes: 4320,
    renderHints: { presentation: 'progress', icon: 'Ticket', priority: 'normal' },
    scoringNotes: '+15 if sell-through >75%; +10 if partner channel contributed sales',
  },
  {
    id: 'partner.cohost_ticket_sales_stalled',
    role: 'partner',
    label: 'Ticket Sales Stalled',
    labelTemplate: 'Only {soldCount} tickets sold',
    category: 'Co-hosting and Venue',
    baseUrgency: 82,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['pace_vs_target', 'partner_channel_strength'],
    freshnessWindow: '7d',
    pageAffinity: '/partner/events',
    pageAffinityBoost: 40,
    href: '/partner/events',
    hrefTemplate: '/partner/events?event={eventId}&tab=tickets&action=promote',
    dataSources: ['event_tickets', 'event_distribution'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: -1,
    cooldownMinutes: 720,
    renderHints: { presentation: 'alert', icon: 'BadgeAlert', priority: 'high' },
    scoringNotes: '+30 inside 5 days under 50% sold; +15 if partner has strong channel',
  },
  {
    id: 'partner.cohost_revenue_split_preview',
    role: 'partner',
    label: 'Revenue Split Preview',
    labelTemplate: 'Estimated share: {amount}',
    category: 'Co-hosting and Venue',
    baseUrgency: 46,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['estimate_change', 'sell_out'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/events',
    pageAffinityBoost: 18,
    href: '/partner/events',
    hrefTemplate: '/partner/events?event={eventId}&tab=settlement',
    dataSources: ['event_revenue_splits', 'event_tickets'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 10,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'card', icon: 'Scale', priority: 'normal' },
    scoringNotes: '+12 as estimate changes >10%; +10 after sell-out',
  },
  {
    id: 'partner.cohost_settlement_processed',
    role: 'partner',
    label: 'Settlement Processed',
    labelTemplate: '{amount} deposited',
    category: 'Co-hosting and Venue',
    baseUrgency: 48,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['settlement_value', 'view_count'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 18,
    href: '/partner/events',
    hrefTemplate: '/partner/events?event={eventId}&tab=settlement',
    dataSources: ['partner_settlements'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 6,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'badge', icon: 'Landmark', priority: 'normal' },
    scoringNotes: '+10 for high-value event; -15 after viewed',
  },
  {
    id: 'partner.guest_dietary_needs_for_venue',
    role: 'partner',
    label: 'Dietary Venue Prep',
    labelTemplate: '{count} guests need venue prep',
    category: 'Co-hosting and Venue',
    baseUrgency: 88,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['allergen_severity', 'event_proximity'],
    freshnessWindow: '7d',
    pageAffinity: '/partner/events',
    pageAffinityBoost: 45,
    href: '/partner/events',
    hrefTemplate: '/partner/events?event={eventId}&tab=dietary',
    dataSources: ['event_guests', 'dietary_restrictions'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'ShieldAlert', priority: 'high' },
    scoringNotes: '+25 for severe allergens; +15 if event within 72h',
  },
  {
    id: 'partner.weather_alert_for_venue_event',
    role: 'partner',
    label: 'Weather Alert',
    labelTemplate: '{weatherRisk} for {eventName}',
    category: 'Co-hosting and Venue',
    baseUrgency: 86,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['forecast_severity', 'outdoor_event', 'backup_plan_state'],
    freshnessWindow: '3d',
    pageAffinity: '/partner/events',
    pageAffinityBoost: 45,
    href: '/partner/events',
    hrefTemplate: '/partner/events?event={eventId}&tab=venue-plan',
    dataSources: ['weather_api', 'event_location_metadata'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: -1,
    cooldownMinutes: 360,
    renderHints: { presentation: 'alert', icon: 'CloudSun', priority: 'high' },
    scoringNotes: '+30 inside 72h; +15 for outdoor event; +10 if no backup plan',
  },
  {
    id: 'partner.venue_capacity_update_needed',
    role: 'partner',
    label: 'Capacity Update Needed',
    labelTemplate: 'Update capacity for {locationName}',
    category: 'Co-hosting and Venue',
    baseUrgency: 62,
    urgencyDecayFn: 'none',
    relevanceSignals: ['request_blocked', 'capacity_missing'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/locations',
    pageAffinityBoost: 25,
    href: '/partner/locations',
    hrefTemplate: '/partner/locations/{locationId}?edit=capacity',
    dataSources: ['partner_locations'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 10,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'pill', icon: 'UsersRound', priority: 'normal' },
    scoringNotes: '+15 if request blocked; +10 if capacity missing',
  },
  {
    id: 'partner.venue_photos_requested',
    role: 'partner',
    label: 'Photos Requested',
    labelTemplate: 'Chef requested photos of {locationName}',
    category: 'Co-hosting and Venue',
    baseUrgency: 58,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['listing_has_no_photos', 'seasonal_campaign'],
    freshnessWindow: '14d',
    pageAffinity: '/partner/locations',
    pageAffinityBoost: 25,
    href: '/partner/locations',
    hrefTemplate: '/partner/locations/{locationId}?photos=requested',
    dataSources: ['partner_images', 'partner_locations'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 12,
    cooldownMinutes: 4320,
    renderHints: { presentation: 'pill', icon: 'Images', priority: 'normal' },
    scoringNotes: '+15 if public listing has no photos; +10 before seasonal campaign',
  },
  {
    id: 'partner.cohost_circle_activity',
    role: 'partner',
    label: 'Planning Circle Activity',
    labelTemplate: '{actorName} updated the planning circle',
    category: 'Co-hosting and Venue',
    baseUrgency: 54,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['partner_mentioned', 'attachment_added'],
    freshnessWindow: '14d',
    pageAffinity: '/partner/events',
    pageAffinityBoost: 25,
    href: '/partner/events',
    hrefTemplate: '/partner/events?event={eventId}&thread={threadId}',
    dataSources: ['hub_circle_activity', 'collaboration_threads'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 20,
    cooldownMinutes: 720,
    renderHints: { presentation: 'pill', icon: 'MessagesSquare', priority: 'normal' },
    scoringNotes: '+20 if partner mentioned; +10 if attachment/task added',
  },
]

// ============================================================================
// Shared Events (5 items)
// ============================================================================

const SHARED_EVENTS: UniversalRailItemDefinition[] = [
  {
    id: 'partner.shared_event_approaching',
    role: 'partner',
    label: 'Event Approaching',
    labelTemplate: '{eventName} is {timeUntil}',
    category: 'Shared Events',
    baseUrgency: 74,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['event_proximity', 'partner_action_open'],
    freshnessWindow: '3d',
    pageAffinity: '/partner/events',
    pageAffinityBoost: 30,
    href: '/partner/events',
    hrefTemplate: '/partner/events?event={eventId}',
    dataSources: ['events', 'partner_locations'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'Clock', priority: 'high' },
    scoringNotes: '+25 inside 24h; +15 if partner action open',
  },
  {
    id: 'partner.shared_event_completed',
    role: 'partner',
    label: 'Event Completed',
    labelTemplate: '{eventName} completed',
    category: 'Shared Events',
    baseUrgency: 40,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['settlement_exists', 'photos_available'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/events',
    pageAffinityBoost: 15,
    href: '/partner/events',
    hrefTemplate: '/partner/events?event={eventId}&tab=recap',
    dataSources: ['events'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 8,
    cooldownMinutes: 4320,
    renderHints: { presentation: 'badge', icon: 'CheckCircle2', priority: 'low' },
    scoringNotes: '+12 if partner settlement or review exists; +8 if photos available',
  },
  {
    id: 'partner.event_feedback_relevant_to_partner',
    role: 'partner',
    label: 'Event Feedback',
    labelTemplate: '{ratingLabel} feedback from {eventName}',
    category: 'Shared Events',
    baseUrgency: 56,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['rating_value', 'partner_related_issue'],
    freshnessWindow: '90d',
    pageAffinity: '/partner/events',
    pageAffinityBoost: 22,
    href: '/partner/events',
    hrefTemplate: '/partner/events?event={eventId}&tab=feedback',
    dataSources: ['event_reviews', 'guest_feedback'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 10,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'card', icon: 'Star', priority: 'normal' },
    scoringNotes: '+20 for 5-star review; +25 if negative partner-related issue',
  },
  {
    id: 'partner.event_photos_shared',
    role: 'partner',
    label: 'Event Photos',
    labelTemplate: 'Photos shared from {eventName}',
    category: 'Shared Events',
    baseUrgency: 42,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['listing_improvement', 'partner_featured'],
    freshnessWindow: '60d',
    pageAffinity: '/partner/events',
    pageAffinityBoost: 22,
    href: '/partner/events',
    hrefTemplate: '/partner/events?event={eventId}&tab=photos',
    dataSources: ['event_media', 'partner_image_approvals'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 12,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'card', icon: 'Image', priority: 'low' },
    scoringNotes: '+15 if photos improve listing; +10 if partner is featured',
  },
  {
    id: 'partner.referred_client_satisfaction',
    role: 'partner',
    label: 'Client Satisfaction',
    labelTemplate: '{clientFirstName} rated their booking {rating}/5',
    category: 'Shared Events',
    baseUrgency: 45,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['rating_value', 'follow_up_needed'],
    freshnessWindow: '60d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 18,
    href: '/partner/events',
    hrefTemplate: '/partner/events?event={eventId}&referral={referralId}',
    dataSources: ['event_reviews', 'referral_attributions'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 8,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'badge', icon: 'Smile', priority: 'normal' },
    scoringNotes: '+15 if high rating; +25 if low rating requires partner follow-up',
  },
]

// ============================================================================
// Communication (4 items)
// ============================================================================

const COMMUNICATION: UniversalRailItemDefinition[] = [
  {
    id: 'partner.message_from_chef_partner',
    role: 'partner',
    label: 'Chef Message',
    labelTemplate: 'Message from Chef {chefFirstName}',
    category: 'Communication',
    baseUrgency: 76,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['unread_state', 'event_proximity'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 35,
    href: '/partner/dashboard',
    hrefTemplate: '/partner/dashboard?message={messageId}',
    dataSources: ['partner_messages', 'hub_circle_threads'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'MessageCircle', priority: 'high' },
    scoringNotes: '+20 if unread; +15 if mentions event within 72h',
  },
  {
    id: 'partner.message_from_chefflow_admin',
    role: 'partner',
    label: 'Admin Update',
    labelTemplate: 'ChefFlow sent you an update',
    category: 'Communication',
    baseUrgency: 64,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['action_required', 'compliance_related'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 30,
    href: '/partner/profile',
    hrefTemplate: '/partner/profile?message={messageId}',
    dataSources: ['admin_announcements', 'partner_messages'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'pill', icon: 'Megaphone', priority: 'normal' },
    scoringNotes: '+20 if action required; +10 for compliance/account message',
  },
  {
    id: 'partner.cohost_planning_thread_update',
    role: 'partner',
    label: 'Planning Thread Update',
    labelTemplate: '{eventName} planning update',
    category: 'Communication',
    baseUrgency: 58,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['partner_mentioned', 'attachment_added'],
    freshnessWindow: '14d',
    pageAffinity: '/partner/events',
    pageAffinityBoost: 28,
    href: '/partner/events',
    hrefTemplate: '/partner/events?event={eventId}&thread={threadId}',
    dataSources: ['collaboration_threads'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 20,
    cooldownMinutes: 720,
    renderHints: { presentation: 'pill', icon: 'PanelTopOpen', priority: 'normal' },
    scoringNotes: '+20 if partner mentioned; +12 if attachment/task added',
  },
  {
    id: 'partner.inquiry_routed_through_partner',
    role: 'partner',
    label: 'Inquiry Routed',
    labelTemplate: 'New inquiry through your partnership',
    category: 'Communication',
    baseUrgency: 60,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['chef_accepted', 'venue_requested'],
    freshnessWindow: '45d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 25,
    href: '/partner/dashboard',
    hrefTemplate: '/partner/dashboard?rail=inquiries&inquiry={inquiryId}',
    dataSources: ['inquiries'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 10,
    cooldownMinutes: 4320,
    renderHints: { presentation: 'card', icon: 'Route', priority: 'normal' },
    scoringNotes: '+15 if chef accepted; +10 if venue requested',
  },
]

// ============================================================================
// Business Intelligence (6 items)
// ============================================================================

const BUSINESS_INTELLIGENCE: UniversalRailItemDefinition[] = [
  {
    id: 'partner.demand_in_partner_area',
    role: 'partner',
    label: 'Area Demand',
    labelTemplate: '{searchCount} chef searches near {areaName}',
    category: 'Business Intelligence',
    baseUrgency: 36,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['demand_trend', 'location_match'],
    freshnessWindow: '14d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 18,
    href: '/partner/dashboard',
    hrefTemplate: '/partner/dashboard?rail=area-demand',
    dataSources: ['search_analytics', 'partner_locations'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 8,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'card', icon: 'Map', priority: 'low' },
    scoringNotes: '+15 if demand up >25%; +10 if partner location matches search profile',
  },
  {
    id: 'partner.popular_cuisines_for_partner_audience',
    role: 'partner',
    label: 'Trending Cuisine',
    labelTemplate: '{cuisineName} is trending with your audience',
    category: 'Business Intelligence',
    baseUrgency: 28,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['cuisine_venue_match', 'new_chef_nearby'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 12,
    href: '/partner/dashboard',
    hrefTemplate: '/partner/dashboard?rail=cuisines&cuisine={slug}',
    dataSources: ['search_analytics', 'event_analytics'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'toggle_filter',
    maxImpressions: 8,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'pill', icon: 'Utensils', priority: 'low' },
    scoringNotes: '+10 when cuisine matches venue positioning; +8 if new chef nearby serves it',
  },
  {
    id: 'partner.seasonal_opportunity',
    role: 'partner',
    label: 'Seasonal Opportunity',
    labelTemplate: '{seasonName}: share with {audienceName}',
    category: 'Business Intelligence',
    baseUrgency: 44,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['peak_period', 'inactive_referrals', 'audience_match'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 18,
    href: '/partner/profile',
    hrefTemplate: '/partner/profile?campaign={campaignId}',
    dataSources: ['campaign_calendar', 'partner_type', 'referral_attributions'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: 10,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'story', icon: 'Sparkles', priority: 'normal' },
    scoringNotes:
      '+20 during peak period; +10 if inactive referrals; +8 if partner audience matches',
  },
  {
    id: 'partner.new_chefs_in_partner_area',
    role: 'partner',
    label: 'New Chefs Nearby',
    labelTemplate: '{chefCount} new chefs near {locationName}',
    category: 'Business Intelligence',
    baseUrgency: 32,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['unmet_cuisine_demand', 'chef_venue_match'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/locations',
    pageAffinityBoost: 15,
    href: '/partner/locations',
    hrefTemplate: '/partner/locations/{locationId}?rail=new-chefs',
    dataSources: ['chef_profiles', 'partner_locations'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 8,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'card', icon: 'ChefHat', priority: 'low' },
    scoringNotes: '+10 if partner had unmet cuisine demand; +8 if chef matches venue',
  },
  {
    id: 'partner.event_trend_partner_can_capitalize',
    role: 'partner',
    label: 'Event Trend',
    labelTemplate: '{eventType} events are up {percentChange}%',
    category: 'Business Intelligence',
    baseUrgency: 34,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['trend_partner_match', 'peak_season'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 15,
    href: '/partner/dashboard',
    hrefTemplate: '/partner/dashboard?rail=event-trends&type={eventType}',
    dataSources: ['event_analytics', 'search_analytics'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: 8,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'card', icon: 'LineChart', priority: 'low' },
    scoringNotes: '+12 when trend matches partner type; +10 near local peak season',
  },
  {
    id: 'partner.partner_tier_status',
    role: 'partner',
    label: 'Tier Status',
    labelTemplate: '{tierName} partner: {bonusPercent}% bonus',
    category: 'Business Intelligence',
    baseUrgency: 40,
    urgencyDecayFn: 'none',
    relevanceSignals: ['tier_upgrade_proximity', 'status_change'],
    freshnessWindow: '90d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 20,
    href: '/partner/profile',
    hrefTemplate: '/partner/profile?tab=tier',
    dataSources: ['partner_tiers', 'referral_attributions'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 12,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'progress', icon: 'Award', priority: 'normal' },
    scoringNotes: '+20 on upgrade; +10 near next tier; -10 after acknowledged',
  },
]

// ============================================================================
// Profile and Settings (5 items)
// ============================================================================

const PROFILE_AND_SETTINGS: UniversalRailItemDefinition[] = [
  {
    id: 'partner.partner_profile_completeness',
    role: 'partner',
    label: 'Profile Completeness',
    labelTemplate: 'Profile is {completePercent}% complete',
    category: 'Profile and Settings',
    baseUrgency: 52,
    urgencyDecayFn: 'none',
    relevanceSignals: ['completeness_pct', 'public_showcase'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/profile',
    pageAffinityBoost: 30,
    href: '/partner/profile',
    hrefTemplate: '/partner/profile?checklist=profile',
    dataSources: ['referral_partners'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 15,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'progress', icon: 'UserRoundCog', priority: 'normal' },
    scoringNotes: '+15 below 60%; +10 if public showcase visible',
  },
  {
    id: 'partner.venue_listing_completeness',
    role: 'partner',
    label: 'Venue Listing',
    labelTemplate: '{locationName} listing is {completePercent}% complete',
    category: 'Profile and Settings',
    baseUrgency: 58,
    urgencyDecayFn: 'none',
    relevanceSignals: ['no_photos', 'no_capacity', 'receives_requests'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/locations',
    pageAffinityBoost: 35,
    href: '/partner/locations',
    hrefTemplate: '/partner/locations/{locationId}?checklist=listing',
    dataSources: ['partner_locations', 'partner_images'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 15,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'progress', icon: 'MapPinHouse', priority: 'normal' },
    scoringNotes: '+20 if no photos/capacity; +10 if location receives requests',
  },
  {
    id: 'partner.payout_method_setup_needed',
    role: 'partner',
    label: 'Payout Method Needed',
    labelTemplate: 'Set up payout method',
    category: 'Profile and Settings',
    baseUrgency: 90,
    urgencyDecayFn: 'none',
    relevanceSignals: ['balance_ready', 'first_earning'],
    freshnessWindow: '90d',
    pageAffinity: '/partner/profile',
    pageAffinityBoost: 45,
    href: '/partner/profile',
    hrefTemplate: '/partner/profile?payout=setup',
    dataSources: ['partner_payout_accounts'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'CreditCard', priority: 'high' },
    scoringNotes: '+20 if balance is ready; +10 if first earning created',
  },
  {
    id: 'partner.tax_document_needed',
    role: 'partner',
    label: 'Tax Document Needed',
    labelTemplate: 'Tax document needed',
    category: 'Profile and Settings',
    baseUrgency: 88,
    urgencyDecayFn: 'none',
    relevanceSignals: ['payout_blocked', 'year_end'],
    freshnessWindow: '90d',
    pageAffinity: '/partner/profile',
    pageAffinityBoost: 40,
    href: '/partner/profile',
    hrefTemplate: '/partner/profile?tax=required',
    dataSources: ['partner_tax_documents'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'FileText', priority: 'high' },
    scoringNotes: '+25 if payout blocked; +15 near year end',
  },
  {
    id: 'partner.agreement_terms_renewal',
    role: 'partner',
    label: 'Terms Renewal',
    labelTemplate: 'Review updated partner terms',
    category: 'Profile and Settings',
    baseUrgency: 82,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['deadline_proximity', 'blocks_activity'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/profile',
    pageAffinityBoost: 40,
    href: '/partner/profile',
    hrefTemplate: '/partner/profile?agreement={agreementId}',
    dataSources: ['partner_agreements'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'ScrollText', priority: 'high' },
    scoringNotes: '+30 inside 7 days; +20 if blocks new referrals/bookings',
  },
]

// ============================================================================
// Marketing Support (5 items)
// ============================================================================

const MARKETING_SUPPORT: UniversalRailItemDefinition[] = [
  {
    id: 'partner.marketing_materials_available',
    role: 'partner',
    label: 'Marketing Materials',
    labelTemplate: 'New referral materials available',
    category: 'Marketing Support',
    baseUrgency: 38,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['campaign_active', 'partner_inactive'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/profile',
    pageAffinityBoost: 18,
    href: '/partner/profile',
    hrefTemplate: '/partner/profile?assets={campaignId}',
    dataSources: ['marketing_asset_cms', 'partner_campaigns'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 10,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'card', icon: 'Download', priority: 'low' },
    scoringNotes: '+12 if campaign active; +10 if partner inactive',
  },
  {
    id: 'partner.cobranded_content_ready',
    role: 'partner',
    label: 'Co-branded Content',
    labelTemplate: 'Co-branded content is ready',
    category: 'Marketing Support',
    baseUrgency: 46,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['awaiting_approval', 'event_launch'],
    freshnessWindow: '60d',
    pageAffinity: '/partner/profile',
    pageAffinityBoost: 22,
    href: '/partner/profile',
    hrefTemplate: '/partner/profile?assets=cobranded&asset={assetId}',
    dataSources: ['cobranded_asset_service', 'media_library'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 10,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'card', icon: 'Layers', priority: 'normal' },
    scoringNotes: '+15 when awaiting approval; +10 before event launch',
  },
  {
    id: 'partner.social_assets_available',
    role: 'partner',
    label: 'Social Assets',
    labelTemplate: 'Social posts ready to share',
    category: 'Marketing Support',
    baseUrgency: 40,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['ticket_sales_stalled', 'seasonal_campaign'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 18,
    href: '/partner/profile',
    hrefTemplate: '/partner/profile?assets=social&campaign={campaignId}',
    dataSources: ['marketing_cms', 'partner_campaigns'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: 12,
    cooldownMinutes: 4320,
    renderHints: { presentation: 'pill', icon: 'Share2', priority: 'low' },
    scoringNotes: '+15 if ticket sales stalled; +10 during seasonal campaign',
  },
  {
    id: 'partner.seasonal_campaign_launched',
    role: 'partner',
    label: 'Campaign Launched',
    labelTemplate: '{campaignName} campaign launched',
    category: 'Marketing Support',
    baseUrgency: 50,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['first_week', 'audience_match', 'inactive_referrals'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 24,
    href: '/partner/profile',
    hrefTemplate: '/partner/profile?campaign={campaignId}',
    dataSources: ['partner_campaigns', 'referral_codes'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: 10,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'story', icon: 'PartyPopper', priority: 'normal' },
    scoringNotes: '+20 first week; +10 if audience match; +15 if inactive referrals',
  },
  {
    id: 'partner.success_story_featuring_partner',
    role: 'partner',
    label: 'Success Story',
    labelTemplate: 'Success story featuring {partnerName}',
    category: 'Marketing Support',
    baseUrgency: 44,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['approval_needed', 'milestone_event'],
    freshnessWindow: '90d',
    pageAffinity: '/partner/preview',
    pageAffinityBoost: 20,
    href: '/partner/preview',
    hrefTemplate: '/partner/preview?story={storyId}',
    dataSources: ['content_cms', 'event_recaps'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 10,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'story', icon: 'Newspaper', priority: 'normal' },
    scoringNotes: '+15 when approval needed; +10 after milestone/high-rating event',
  },
]

// ============================================================================
// Onboarding (6 items)
// ============================================================================

const ONBOARDING: UniversalRailItemDefinition[] = [
  {
    id: 'partner.onboarding_welcome_setup',
    role: 'partner',
    label: 'Welcome Setup',
    labelTemplate: 'Welcome to ChefFlow Partners',
    category: 'Onboarding',
    baseUrgency: 65,
    urgencyDecayFn: 'none',
    relevanceSignals: ['first_visit', 'setup_progress'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 35,
    href: '/partner/dashboard',
    hrefTemplate: '/partner/dashboard?onboarding=setup',
    dataSources: ['referral_partners'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'story', icon: 'Sparkle', priority: 'high' },
    scoringNotes: '+20 until first visit complete; decays after key steps complete',
  },
  {
    id: 'partner.onboarding_referral_link_creation',
    role: 'partner',
    label: 'Create Referral Link',
    labelTemplate: 'Create your referral link',
    category: 'Onboarding',
    baseUrgency: 78,
    urgencyDecayFn: 'none',
    relevanceSignals: ['referral_partner_type', 'no_tracked_source'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 40,
    href: '/partner/profile',
    hrefTemplate: '/partner/profile?onboarding=referral-link',
    dataSources: ['partner_referral_links'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'Link', priority: 'high' },
    scoringNotes: '+20 if referral partner type; +10 if no tracked source',
  },
  {
    id: 'partner.onboarding_venue_profile_setup',
    role: 'partner',
    label: 'Venue Profile Setup',
    labelTemplate: 'Set up your venue profile',
    category: 'Onboarding',
    baseUrgency: 76,
    urgencyDecayFn: 'none',
    relevanceSignals: ['venue_partner_type', 'no_active_location'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/locations',
    pageAffinityBoost: 40,
    href: '/partner/locations',
    hrefTemplate: '/partner/locations?onboarding=venue',
    dataSources: ['partner_locations', 'partner_images'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'progress', icon: 'MapPin', priority: 'high' },
    scoringNotes: '+25 for venue/farm/estate partners; +15 if no active location',
  },
  {
    id: 'partner.onboarding_payout_setup',
    role: 'partner',
    label: 'Payout Setup',
    labelTemplate: 'Set up payouts',
    category: 'Onboarding',
    baseUrgency: 80,
    urgencyDecayFn: 'none',
    relevanceSignals: ['commissions_enabled', 'earnings_pending'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/profile',
    pageAffinityBoost: 40,
    href: '/partner/profile',
    hrefTemplate: '/partner/profile?payout=setup',
    dataSources: ['partner_payout_accounts'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'Wallet', priority: 'high' },
    scoringNotes: '+20 if commissions enabled; +20 if earnings pending',
  },
  {
    id: 'partner.onboarding_first_referral_guide',
    role: 'partner',
    label: 'First Referral Guide',
    labelTemplate: 'Make your first referral',
    category: 'Onboarding',
    baseUrgency: 42,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['no_referrals_after_7d', 'marketing_materials_exist'],
    freshnessWindow: '45d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 20,
    href: '/partner/dashboard',
    hrefTemplate: '/partner/dashboard?onboarding=first-referral',
    dataSources: ['referral_attributions'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: 8,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'card', icon: 'Send', priority: 'normal' },
    scoringNotes: '+15 if no referrals after 7 days; +10 if marketing materials exist',
  },
  {
    id: 'partner.onboarding_dashboard_tour',
    role: 'partner',
    label: 'Dashboard Tour',
    labelTemplate: 'Take the partner dashboard tour',
    category: 'Onboarding',
    baseUrgency: 32,
    urgencyDecayFn: 'none',
    relevanceSignals: ['first_login', 'visit_count'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 18,
    href: '/partner/dashboard',
    hrefTemplate: '/partner/dashboard?tour=partner',
    dataSources: ['onboarding_events', 'product_analytics'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: 6,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'pill', icon: 'Compass', priority: 'low' },
    scoringNotes: '+10 on first login; -10 after multiple visits',
  },
]

// ============================================================================
// Compliance and Admin (5 items)
// ============================================================================

const COMPLIANCE_AND_ADMIN: UniversalRailItemDefinition[] = [
  {
    id: 'partner.partnership_agreement_expiring',
    role: 'partner',
    label: 'Agreement Expiring',
    labelTemplate: 'Partnership agreement expires {date}',
    category: 'Compliance and Admin',
    baseUrgency: 86,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['expiry_proximity', 'active_events_rely_on'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/profile',
    pageAffinityBoost: 45,
    href: '/partner/profile',
    hrefTemplate: '/partner/profile?agreement={agreementId}',
    dataSources: ['partner_agreements'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'FileWarning', priority: 'high' },
    scoringNotes: '+30 inside 14 days; +20 if active events/referrals rely on agreement',
  },
  {
    id: 'partner.insurance_certificate_needed',
    role: 'partner',
    label: 'Insurance Certificate',
    labelTemplate: 'Insurance certificate needed',
    category: 'Compliance and Admin',
    baseUrgency: 90,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['event_within_14d', 'expired'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/locations',
    pageAffinityBoost: 45,
    href: '/partner/locations',
    hrefTemplate: '/partner/locations/{locationId}?compliance=insurance',
    dataSources: ['partner_compliance_documents'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'ShieldCheck', priority: 'high' },
    scoringNotes: '+30 if event within 14 days; +20 if expired',
  },
  {
    id: 'partner.liability_waiver_update',
    role: 'partner',
    label: 'Liability Waiver',
    labelTemplate: 'Liability waiver update required',
    category: 'Compliance and Admin',
    baseUrgency: 82,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['deadline_proximity', 'event_blocked'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/profile',
    pageAffinityBoost: 40,
    href: '/partner/profile',
    hrefTemplate: '/partner/profile?waiver={waiverId}',
    dataSources: ['waiver_records', 'partner_compliance'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'Signature', priority: 'high' },
    scoringNotes: '+25 inside 7 days; +15 if active event blocked',
  },
  {
    id: 'partner.health_inspection_due',
    role: 'partner',
    label: 'Health Inspection Due',
    labelTemplate: 'Health inspection due {date}',
    category: 'Compliance and Admin',
    baseUrgency: 88,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['due_proximity', 'event_after_expiry'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/locations',
    pageAffinityBoost: 45,
    href: '/partner/locations',
    hrefTemplate: '/partner/locations/{locationId}?compliance=health',
    dataSources: ['partner_compliance_documents'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'ClipboardCheck', priority: 'high' },
    scoringNotes: '+30 inside 30 days; +20 if event scheduled after expiry',
  },
  {
    id: 'partner.permit_renewal_reminder',
    role: 'partner',
    label: 'Permit Renewal',
    labelTemplate: '{permitName} renews {date}',
    category: 'Compliance and Admin',
    baseUrgency: 84,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['renewal_proximity', 'event_after_expiry'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/locations',
    pageAffinityBoost: 42,
    href: '/partner/locations',
    hrefTemplate: '/partner/locations/{locationId}?compliance=permit',
    dataSources: ['partner_permits', 'partner_compliance_documents'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'BadgeAlert', priority: 'high' },
    scoringNotes: '+25 inside 30 days; +20 if event after expiry',
  },
]

// ============================================================================
// Vendor and Supplier Collaboration (5 items)
// ============================================================================

const VENDOR_AND_SUPPLIER: UniversalRailItemDefinition[] = [
  {
    id: 'partner.supplier_order_request',
    role: 'partner',
    label: 'Order Request',
    labelTemplate: 'Order request for {eventName}',
    category: 'Vendor and Supplier Collaboration',
    baseUrgency: 78,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['response_deadline', 'event_proximity'],
    freshnessWindow: '7d',
    pageAffinity: '/partner/events',
    pageAffinityBoost: 35,
    href: '/partner/events',
    hrefTemplate: '/partner/events?event={eventId}&supplierRequest={requestId}',
    dataSources: ['supplier_requests', 'shared_ingredient_list'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'PackagePlus', priority: 'high' },
    scoringNotes: '+25 inside 48h; +15 if event within 7 days',
  },
  {
    id: 'partner.supplier_delivery_window',
    role: 'partner',
    label: 'Delivery Window',
    labelTemplate: 'Delivery window {windowStart}-{windowEnd}',
    category: 'Vendor and Supplier Collaboration',
    baseUrgency: 74,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['delivery_day', 'allergen_sensitive'],
    freshnessWindow: '3d',
    pageAffinity: '/partner/events',
    pageAffinityBoost: 35,
    href: '/partner/events',
    hrefTemplate: '/partner/events?event={eventId}&delivery={deliveryId}',
    dataSources: ['delivery_schedule', 'supplier_orders'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'Truck', priority: 'high' },
    scoringNotes: '+25 on delivery day; +15 for cold/allergen-sensitive items',
  },
  {
    id: 'partner.equipment_rental_request',
    role: 'partner',
    label: 'Equipment Request',
    labelTemplate: '{equipmentName} requested',
    category: 'Vendor and Supplier Collaboration',
    baseUrgency: 76,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['event_proximity', 'no_backup'],
    freshnessWindow: '7d',
    pageAffinity: '/partner/events',
    pageAffinityBoost: 35,
    href: '/partner/events',
    hrefTemplate: '/partner/events?event={eventId}&equipment={requestId}',
    dataSources: ['equipment_request_records'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'Wrench', priority: 'high' },
    scoringNotes: '+20 if event within 7 days; +15 if no backup equipment',
  },
  {
    id: 'partner.supplier_invoice_ready',
    role: 'partner',
    label: 'Invoice Ready',
    labelTemplate: 'Invoice {invoiceNumber} ready',
    category: 'Vendor and Supplier Collaboration',
    baseUrgency: 50,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['payment_overdue', 'amount_changed'],
    freshnessWindow: '60d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 20,
    href: '/partner/profile',
    hrefTemplate: '/partner/profile?invoice={invoiceId}',
    dataSources: ['vendor_invoice_records'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 8,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'badge', icon: 'ReceiptText', priority: 'normal' },
    scoringNotes: '+20 if payment overdue; +10 if amount changed',
  },
  {
    id: 'partner.supplier_shortage_alert',
    role: 'partner',
    label: 'Shortage Alert',
    labelTemplate: '{itemName} shortage affects {eventName}',
    category: 'Vendor and Supplier Collaboration',
    baseUrgency: 90,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['deadline_proximity', 'critical_ingredient'],
    freshnessWindow: '7d',
    pageAffinity: '/partner/events',
    pageAffinityBoost: 45,
    href: '/partner/events',
    hrefTemplate: '/partner/events?event={eventId}&shortage={shortageId}',
    dataSources: ['supplier_inventory_signals', 'event_prep_data'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'TriangleAlert', priority: 'high' },
    scoringNotes: '+30 inside 48h; +20 for critical ingredient/equipment',
  },
]

// ============================================================================
// Event Planner Collaboration (4 items)
// ============================================================================

const EVENT_PLANNER: UniversalRailItemDefinition[] = [
  {
    id: 'partner.planner_timeline_review_needed',
    role: 'partner',
    label: 'Timeline Review',
    labelTemplate: 'Timeline needs your review',
    category: 'Event Planner Collaboration',
    baseUrgency: 80,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['event_proximity', 'vendor_dependencies'],
    freshnessWindow: '7d',
    pageAffinity: '/partner/events',
    pageAffinityBoost: 40,
    href: '/partner/events',
    hrefTemplate: '/partner/events?event={eventId}&timeline=review',
    dataSources: ['event_timeline', 'collaboration_approvals'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'CalendarClock', priority: 'high' },
    scoringNotes: '+25 inside 72h; +15 if vendor/venue dependencies exist',
  },
  {
    id: 'partner.planner_guest_count_change',
    role: 'partner',
    label: 'Guest Count Changed',
    labelTemplate: 'Guest count changed to {guestCount}',
    category: 'Event Planner Collaboration',
    baseUrgency: 74,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['over_capacity', 'event_proximity'],
    freshnessWindow: '7d',
    pageAffinity: '/partner/events',
    pageAffinityBoost: 35,
    href: '/partner/events',
    hrefTemplate: '/partner/events?event={eventId}&change=guest-count',
    dataSources: ['events', 'event_tickets'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'Users', priority: 'high' },
    scoringNotes: '+20 if over venue capacity; +15 inside 7 days',
  },
  {
    id: 'partner.planner_client_handoff_needed',
    role: 'partner',
    label: 'Client Handoff',
    labelTemplate: 'Client handoff needed',
    category: 'Event Planner Collaboration',
    baseUrgency: 66,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['due_today', 'blocks_chef'],
    freshnessWindow: '7d',
    pageAffinity: '/partner/events',
    pageAffinityBoost: 28,
    href: '/partner/events',
    hrefTemplate: '/partner/events?event={eventId}&handoff={handoffId}',
    dataSources: ['collaboration_tasks'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'pill', icon: 'Handshake', priority: 'normal' },
    scoringNotes: '+20 if due today; +15 if blocks chef/admin',
  },
  {
    id: 'partner.planner_vendor_coordination_due',
    role: 'partner',
    label: 'Vendor Coordination',
    labelTemplate: 'Vendor coordination due',
    category: 'Event Planner Collaboration',
    baseUrgency: 78,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['event_proximity', 'venue_access_depends'],
    freshnessWindow: '7d',
    pageAffinity: '/partner/events',
    pageAffinityBoost: 35,
    href: '/partner/events',
    hrefTemplate: '/partner/events?event={eventId}&vendors=coordination',
    dataSources: ['vendor_coordination_records', 'event_tasks'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'Network', priority: 'high' },
    scoringNotes: '+25 inside 72h; +15 if venue access depends on it',
  },
]

// ============================================================================
// Relationship Health and System (4 items)
// ============================================================================

const RELATIONSHIP_HEALTH: UniversalRailItemDefinition[] = [
  {
    id: 'partner.partner_relationship_health',
    role: 'partner',
    label: 'Partnership Health',
    labelTemplate: 'Partnership health: {healthLabel}',
    category: 'Relationship Health and System',
    baseUrgency: 36,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['health_drop', 'tier_upgrade_proximity'],
    freshnessWindow: '7d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 18,
    href: '/partner/dashboard',
    hrefTemplate: '/partner/dashboard?rail=relationship-health',
    dataSources: ['partner_health_service'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 8,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'progress', icon: 'Activity', priority: 'normal' },
    scoringNotes: '+20 if health drops; +10 if near tier upgrade',
  },
  {
    id: 'partner.partner_next_best_action',
    role: 'partner',
    label: 'Next Best Action',
    labelTemplate: 'Next best action: {actionTitle}',
    category: 'Relationship Health and System',
    baseUrgency: 46,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['action_unlocks_payout', 'partner_inactive'],
    freshnessWindow: '7d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 22,
    href: '/partner/dashboard',
    hrefTemplate: '/partner/dashboard?rail=next-best-action&action={actionId}',
    dataSources: ['partner_recommendation_engine'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: 8,
    cooldownMinutes: 4320,
    renderHints: { presentation: 'pill', icon: 'ArrowRightCircle', priority: 'normal' },
    scoringNotes: '+15 if action unlocks payout/booking; +10 if partner is inactive',
  },
  {
    id: 'partner.partner_reactivation_offer',
    role: 'partner',
    label: 'Reactivation Offer',
    labelTemplate: 'Reactivate your partnership',
    category: 'Relationship Health and System',
    baseUrgency: 58,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['inactivity_duration', 'seasonal_demand'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/dashboard',
    pageAffinityBoost: 25,
    href: '/partner/profile',
    hrefTemplate: '/partner/profile?reactivation={offerId}',
    dataSources: ['partner_lifecycle_service', 'partner_campaigns'],
    privacy: 'role_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: 6,
    cooldownMinutes: 20160,
    renderHints: { presentation: 'story', icon: 'RefreshCcw', priority: 'normal' },
    scoringNotes: '+20 after 60 inactive days; +10 if seasonal demand is high',
  },
  {
    id: 'partner.partner_security_prompt',
    role: 'partner',
    label: 'Security Prompt',
    labelTemplate: 'Secure your partner account',
    category: 'Relationship Health and System',
    baseUrgency: 72,
    urgencyDecayFn: 'none',
    relevanceSignals: ['new_device', 'payout_enabled'],
    freshnessWindow: '30d',
    pageAffinity: '/partner/profile',
    pageAffinityBoost: 35,
    href: '/partner/profile',
    hrefTemplate: '/partner/profile?security=checkup',
    dataSources: ['auth_security_events'],
    privacy: 'role_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'Shield', priority: 'high' },
    scoringNotes: '+20 for new device/risky session; +10 if payout enabled',
  },
]

// ============================================================================
// Export: 76 items total
// ============================================================================

export const PARTNER_RAIL_REGISTRY: readonly UniversalRailItemDefinition[] = [
  ...REFERRAL_TRACKING,
  ...COHOSTING_AND_VENUE,
  ...SHARED_EVENTS,
  ...COMMUNICATION,
  ...BUSINESS_INTELLIGENCE,
  ...PROFILE_AND_SETTINGS,
  ...MARKETING_SUPPORT,
  ...ONBOARDING,
  ...COMPLIANCE_AND_ADMIN,
  ...VENDOR_AND_SUPPLIER,
  ...EVENT_PLANNER,
  ...RELATIONSHIP_HEALTH,
] as const
