import type { UniversalRailItemDefinition } from '../universal-rail-types'

// Public role: 53 item types across 4 lanes (taste, occasion, chefflow_picks, engagement)
// Anonymous users, no auth required
export const PUBLIC_RAIL_REGISTRY: readonly UniversalRailItemDefinition[] = [
  // ──────────────────────────────────────────────
  // TASTE Lane (17 items)
  // ──────────────────────────────────────────────

  {
    id: 'public.cuisine',
    role: 'public',
    label: '{cuisineName}',
    labelTemplate: '{cuisineName}',
    category: 'taste',
    baseUrgency: 40,
    urgencyDecayFn: 'none',
    relevanceSignals: ['user_location', 'browse_history', 'chef_density'],
    freshnessWindow: '7d',
    pageAffinity: '/chefs,/eat,/nearby',
    pageAffinityBoost: 15,
    href: '/eat?cuisine={slug}',
    hrefTemplate: '/eat?cuisine={slug}',
    dataSources: ['chef_culinary_profiles', 'chef_profiles', 'chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'toggle_filter',
    maxImpressions: -1,
    cooldownMinutes: 60,
    renderHints: { presentation: 'pill', icon: 'taco' },
    scoringNotes:
      'Diversity fill boosts unseen cuisines. Location match boosts when chefs of this cuisine exist nearby.',
  },

  {
    id: 'public.food_type',
    role: 'public',
    label: '{dishName}',
    labelTemplate: '{dishName}',
    category: 'taste',
    baseUrgency: 35,
    urgencyDecayFn: 'none',
    relevanceSignals: ['browse_history', 'cuisine_affinity'],
    freshnessWindow: '7d',
    pageAffinity: '/eat,/chefs',
    pageAffinityBoost: 10,
    href: '/eat?craving={slug}',
    hrefTemplate: '/eat?craving={slug}',
    dataSources: ['chef_marketplace_profiles', 'chef_culinary_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'toggle_filter',
    maxImpressions: -1,
    cooldownMinutes: 60,
    renderHints: { presentation: 'pill', icon: 'dining' },
    scoringNotes: 'Boosted by related cuisine selection. Price range context from chef listings.',
  },

  {
    id: 'public.craving',
    role: 'public',
    label: '{cravingText}',
    labelTemplate: '{cravingText}',
    category: 'taste',
    baseUrgency: 45,
    urgencyDecayFn: 'none',
    relevanceSignals: ['time_of_day', 'browse_history', 'seasonal_context'],
    freshnessWindow: '24h',
    pageAffinity: '/eat,/',
    pageAffinityBoost: 20,
    href: '/eat?craving={slug}',
    hrefTemplate: '/eat?craving={slug}',
    dataSources: ['chef_marketplace_profiles', 'chef_culinary_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'toggle_filter',
    maxImpressions: 50,
    cooldownMinutes: 30,
    renderHints: { presentation: 'pill', icon: 'flame' },
    scoringNotes:
      'Time-of-day and seasonal context boost. Rotate stale labels after 30 impressions.',
  },

  {
    id: 'public.dietary',
    role: 'public',
    label: '{dietaryLabel}',
    labelTemplate: '{dietaryLabel}',
    category: 'taste',
    baseUrgency: 50,
    urgencyDecayFn: 'none',
    relevanceSignals: ['dietary_filters', 'browse_history'],
    freshnessWindow: '30d',
    pageAffinity: '/chefs,/eat',
    pageAffinityBoost: 20,
    href: '/eat?dietary={slug}',
    hrefTemplate: '/eat?dietary={slug}',
    dataSources: ['chef_marketplace_profiles', 'chef_culinary_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'toggle_filter',
    maxImpressions: -1,
    cooldownMinutes: 120,
    renderHints: { presentation: 'badge', icon: 'leaf' },
    scoringNotes: 'Hard constraints persist. Repeated dietary filter use boosts urgency.',
  },

  {
    id: 'public.mood',
    role: 'public',
    label: '{moodLabel}',
    labelTemplate: '{moodLabel}',
    category: 'taste',
    baseUrgency: 30,
    urgencyDecayFn: 'none',
    relevanceSignals: ['time_of_day', 'browse_history'],
    freshnessWindow: '7d',
    pageAffinity: '/eat',
    pageAffinityBoost: 10,
    href: '/eat?eventStyle={slug}',
    hrefTemplate: '/eat?eventStyle={slug}',
    dataSources: ['chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'toggle_filter',
    maxImpressions: 40,
    cooldownMinutes: 60,
    renderHints: { presentation: 'pill', icon: 'spark' },
    scoringNotes: 'Session mood fades after 7 days. Lower confidence than explicit preferences.',
  },

  {
    id: 'public.seasonal',
    role: 'public',
    label: '{seasonalItem}',
    labelTemplate: '{seasonalItem}',
    category: 'taste',
    baseUrgency: 55,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['seasonal_context', 'user_location'],
    freshnessWindow: '30d',
    pageAffinity: '/,/eat',
    pageAffinityBoost: 25,
    href: '/eat?seasonal={slug}',
    hrefTemplate: '/eat?seasonal={slug}',
    dataSources: ['editorial_slots', 'seasonal_calendar', 'chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 30,
    cooldownMinutes: 120,
    renderHints: { presentation: 'card', icon: 'market' },
    scoringNotes: 'Peaks during active season window. Expires at season end or campaign end date.',
  },

  {
    id: 'public.culinary_signal',
    role: 'public',
    label: '{signalLabel}',
    labelTemplate: '{signalLabel}',
    category: 'taste',
    baseUrgency: 35,
    urgencyDecayFn: 'none',
    relevanceSignals: ['taste_profile', 'browse_history', 'seasonal_context'],
    freshnessWindow: '30d',
    pageAffinity: '/eat,/ingredients',
    pageAffinityBoost: 15,
    href: '/eat?signal={signalSlug}',
    hrefTemplate: '/eat?signal={signalSlug}',
    dataSources: ['chef_culinary_profiles', 'ingredient_taxonomy'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'toggle_filter',
    maxImpressions: 40,
    cooldownMinutes: 60,
    renderHints: { presentation: 'pill', icon: 'knife' },
    scoringNotes:
      'Bridges ingredient, technique, food_type, and preference signals. Can collapse into combo.',
  },

  {
    id: 'public.technique',
    role: 'public',
    label: '{techniqueName}',
    labelTemplate: '{techniqueName}',
    category: 'taste',
    baseUrgency: 30,
    urgencyDecayFn: 'none',
    relevanceSignals: ['browse_history', 'cuisine_affinity'],
    freshnessWindow: '7d',
    pageAffinity: '/eat,/chefs',
    pageAffinityBoost: 10,
    href: '/eat?technique={slug}',
    hrefTemplate: '/eat?technique={slug}',
    dataSources: ['chef_culinary_profiles', 'chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'toggle_filter',
    maxImpressions: -1,
    cooldownMinutes: 60,
    renderHints: { presentation: 'pill', icon: 'flame' },
    scoringNotes: 'Boosted by related ingredient/dish clicks. Adds craft-oriented discovery layer.',
  },

  {
    id: 'public.ingredient',
    role: 'public',
    label: '{ingredientName}',
    labelTemplate: '{ingredientName}',
    category: 'taste',
    baseUrgency: 30,
    urgencyDecayFn: 'none',
    relevanceSignals: ['browse_history', 'seasonal_context'],
    freshnessWindow: '30d',
    pageAffinity: '/eat,/ingredients',
    pageAffinityBoost: 15,
    href: '/eat?ingredient={slug}',
    hrefTemplate: '/eat?ingredient={slug}',
    dataSources: ['ingredient_taxonomy', 'chef_culinary_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'toggle_filter',
    maxImpressions: 40,
    cooldownMinutes: 60,
    renderHints: { presentation: 'pill', icon: 'carrot' },
    scoringNotes:
      'Seasonal ingredients get deadline decay boost. Safety constraints demote allergens.',
  },

  {
    id: 'public.vibe',
    role: 'public',
    label: '{vibeName}',
    labelTemplate: '{vibeName}',
    category: 'taste',
    baseUrgency: 30,
    urgencyDecayFn: 'none',
    relevanceSignals: ['browse_history', 'occasion_affinity'],
    freshnessWindow: '7d',
    pageAffinity: '/eat',
    pageAffinityBoost: 10,
    href: '/eat?eventStyle={slug}',
    hrefTemplate: '/eat?eventStyle={slug}',
    dataSources: ['chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'toggle_filter',
    maxImpressions: 40,
    cooldownMinutes: 60,
    renderHints: { presentation: 'pill', icon: 'champagne' },
    scoringNotes: 'Pairs with mood, occasion, special_dining, and combo.',
  },

  {
    id: 'public.ingredient_hero',
    role: 'public',
    label: 'Peak: {ingredient}',
    labelTemplate: 'Peak: {ingredient}',
    category: 'taste',
    baseUrgency: 60,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['seasonal_context', 'user_location'],
    freshnessWindow: '14d',
    pageAffinity: '/,/eat',
    pageAffinityBoost: 30,
    href: '/ingredient/{id}?source=rail',
    hrefTemplate: '/ingredient/{id}?source=rail',
    dataSources: ['ingredient_taxonomy', 'seasonal_calendar', 'chef_culinary_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 20,
    cooldownMinutes: 180,
    renderHints: { presentation: 'card', icon: 'avocado' },
    scoringNotes: 'Peaks during local seasonal window. Expires when ingredient goes out of season.',
  },

  {
    id: 'public.cuisine_fusion',
    role: 'public',
    label: '{cuisine1} x {cuisine2}',
    labelTemplate: '{cuisine1} x {cuisine2}',
    category: 'taste',
    baseUrgency: 35,
    urgencyDecayFn: 'none',
    relevanceSignals: ['cuisine_affinity', 'browse_history'],
    freshnessWindow: '7d',
    pageAffinity: '/chefs,/eat',
    pageAffinityBoost: 10,
    href: '/eat?cuisine={slug1}&cuisine2={slug2}',
    hrefTemplate: '/eat?cuisine={slug1}&cuisine2={slug2}',
    dataSources: ['chef_culinary_profiles', 'chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'toggle_filter',
    maxImpressions: 30,
    cooldownMinutes: 120,
    renderHints: { presentation: 'pill', icon: 'utensils' },
    scoringNotes:
      'Boundary-crossing flavors. Boosted when user has viewed both component cuisines.',
  },

  {
    id: 'public.prep_style',
    role: 'public',
    label: '{prepStyle}',
    labelTemplate: '{prepStyle}',
    category: 'taste',
    baseUrgency: 25,
    urgencyDecayFn: 'none',
    relevanceSignals: ['browse_history'],
    freshnessWindow: '7d',
    pageAffinity: '/eat',
    pageAffinityBoost: 10,
    href: '/eat?prep={slug}',
    hrefTemplate: '/eat?prep={slug}',
    dataSources: ['chef_culinary_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'toggle_filter',
    maxImpressions: -1,
    cooldownMinutes: 60,
    renderHints: { presentation: 'badge', icon: 'knife' },
    scoringNotes: 'Low baseline urgency. Provides nuance for experienced food browsers.',
  },

  {
    id: 'public.meal_moment',
    role: 'public',
    label: '{momentName}',
    labelTemplate: '{momentName}',
    category: 'taste',
    baseUrgency: 40,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['time_of_day', 'browse_history'],
    freshnessWindow: '12h',
    pageAffinity: '/,/eat',
    pageAffinityBoost: 20,
    href: '/eat?moment={slug}',
    hrefTemplate: '/eat?moment={slug}',
    dataSources: ['chef_marketplace_profiles', 'editorial_slots'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'toggle_filter',
    maxImpressions: 30,
    cooldownMinutes: 30,
    renderHints: { presentation: 'pill', icon: 'coffee' },
    scoringNotes: 'Right meal, right time. Time-of-day strongly influences which moments surface.',
  },

  {
    id: 'public.region',
    role: 'public',
    label: '{regionName} cuisine',
    labelTemplate: '{regionName} cuisine',
    category: 'taste',
    baseUrgency: 30,
    urgencyDecayFn: 'none',
    relevanceSignals: ['cuisine_affinity', 'browse_history'],
    freshnessWindow: '7d',
    pageAffinity: '/chefs,/eat',
    pageAffinityBoost: 10,
    href: '/eat?region={slug}',
    hrefTemplate: '/eat?region={slug}',
    dataSources: ['chef_culinary_profiles', 'chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'toggle_filter',
    maxImpressions: -1,
    cooldownMinutes: 60,
    renderHints: { presentation: 'pill', icon: 'location' },
    scoringNotes: 'Regional specialties drill deeper than cuisine. Expands to sub-cuisines.',
  },

  {
    id: 'public.farm_fresh',
    role: 'public',
    label: 'Farm-fresh {item}',
    labelTemplate: 'Farm-fresh {item}',
    category: 'taste',
    baseUrgency: 50,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['seasonal_context', 'user_location'],
    freshnessWindow: '14d',
    pageAffinity: '/,/eat',
    pageAffinityBoost: 25,
    href: '/eat?farm={slug}',
    hrefTemplate: '/eat?farm={slug}',
    dataSources: ['seasonal_calendar', 'ingredient_taxonomy', 'chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 25,
    cooldownMinutes: 180,
    renderHints: { presentation: 'card', icon: 'plant' },
    scoringNotes:
      'Local harvest window drives deadline decay. Pairs with seasonal and ingredient_hero.',
  },

  {
    id: 'public.allergen_safe',
    role: 'public',
    label: '{allergen}-free dining',
    labelTemplate: '{allergen}-free dining',
    category: 'taste',
    baseUrgency: 55,
    urgencyDecayFn: 'none',
    relevanceSignals: ['dietary_filters', 'browse_history'],
    freshnessWindow: '30d',
    pageAffinity: '/chefs,/eat',
    pageAffinityBoost: 25,
    href: '/eat?allergenFree={slug}',
    hrefTemplate: '/eat?allergenFree={slug}',
    dataSources: ['chef_marketplace_profiles', 'chef_culinary_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'toggle_filter',
    maxImpressions: -1,
    cooldownMinutes: 120,
    renderHints: { presentation: 'badge', icon: 'leaf' },
    scoringNotes:
      'Safety-critical. Safe for your table. Never suppress allergen-safe items for users who need them.',
  },

  // ──────────────────────────────────────────────
  // OCCASION Lane (15 items)
  // ──────────────────────────────────────────────

  {
    id: 'public.service',
    role: 'public',
    label: '{serviceFormat}',
    labelTemplate: '{serviceFormat}',
    category: 'occasion',
    baseUrgency: 45,
    urgencyDecayFn: 'none',
    relevanceSignals: ['browse_history', 'occasion_affinity'],
    freshnessWindow: '7d',
    pageAffinity: '/eat,/chefs',
    pageAffinityBoost: 15,
    href: '/eat?fulfillment={serviceSlug}',
    hrefTemplate: '/eat?fulfillment={serviceSlug}',
    dataSources: ['chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'toggle_filter',
    maxImpressions: -1,
    cooldownMinutes: 60,
    renderHints: { presentation: 'pill', icon: 'chef' },
    scoringNotes:
      'Service format choice changes entire result mix. Boosts occasion and price items.',
  },

  {
    id: 'public.occasion',
    role: 'public',
    label: '{occasionName}',
    labelTemplate: '{occasionName}',
    category: 'occasion',
    baseUrgency: 50,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['seasonal_context', 'browse_history'],
    freshnessWindow: '14d',
    pageAffinity: '/eat',
    pageAffinityBoost: 20,
    href: '/eat?intent={occasionSlug}',
    hrefTemplate: '/eat?intent={occasionSlug}',
    dataSources: ['editorial_slots', 'chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: -1,
    cooldownMinutes: 60,
    renderHints: { presentation: 'pill', icon: 'confetti' },
    scoringNotes:
      'Event-like occasions persist; seasonal occasions expire after the moment passes.',
  },

  {
    id: 'public.special_dining',
    role: 'public',
    label: '{diningFormat}',
    labelTemplate: '{diningFormat}',
    category: 'occasion',
    baseUrgency: 45,
    urgencyDecayFn: 'none',
    relevanceSignals: ['browse_history', 'occasion_affinity'],
    freshnessWindow: '7d',
    pageAffinity: '/eat,/chefs',
    pageAffinityBoost: 15,
    href: '/eat?intent={formatSlug}&fulfillment=private_chef',
    hrefTemplate: '/eat?intent={formatSlug}&fulfillment=private_chef',
    dataSources: ['chef_marketplace_profiles', 'editorial_slots'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 30,
    cooldownMinutes: 120,
    renderHints: { presentation: 'card', icon: 'crown' },
    scoringNotes: 'Premium experiences. Should be gentle for budget-sensitive users.',
  },

  {
    id: 'public.circle',
    role: 'public',
    label: 'Dinner with friends',
    labelTemplate: 'Dinner with friends',
    category: 'occasion',
    baseUrgency: 35,
    urgencyDecayFn: 'none',
    relevanceSignals: ['browse_history'],
    freshnessWindow: '7d',
    pageAffinity: '/eat',
    pageAffinityBoost: 10,
    href: '/hub/circles?source=rail',
    hrefTemplate: '/hub/circles?source=rail',
    dataSources: ['chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 30,
    cooldownMinutes: 120,
    renderHints: { presentation: 'pill', icon: 'family' },
    scoringNotes: 'Group planning entry point. Boosted after party size 5+ interactions.',
  },

  {
    id: 'public.location',
    role: 'public',
    label: 'Chefs near {place}',
    labelTemplate: 'Chefs near {place}',
    category: 'occasion',
    baseUrgency: 60,
    urgencyDecayFn: 'none',
    relevanceSignals: ['user_location', 'browse_history'],
    freshnessWindow: '24h',
    pageAffinity: '/chefs,/eat,/',
    pageAffinityBoost: 30,
    href: '/eat?location={encodedPlace}',
    hrefTemplate: '/eat?location={encodedPlace}',
    dataSources: ['chef_marketplace_profiles', 'chef_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'toggle_filter',
    maxImpressions: -1,
    cooldownMinutes: 30,
    renderHints: { presentation: 'badge', icon: 'location' },
    scoringNotes:
      'Core navigation item. Location match drives chef density and availability signals.',
  },

  {
    id: 'public.price',
    role: 'public',
    label: '{budgetLabel}',
    labelTemplate: '{budgetLabel}',
    category: 'occasion',
    baseUrgency: 40,
    urgencyDecayFn: 'none',
    relevanceSignals: ['browse_history'],
    freshnessWindow: '30d',
    pageAffinity: '/eat,/chefs',
    pageAffinityBoost: 15,
    href: '/eat?budget={slug}',
    hrefTemplate: '/eat?budget={slug}',
    dataSources: ['chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'toggle_filter',
    maxImpressions: -1,
    cooldownMinutes: 60,
    renderHints: { presentation: 'badge', icon: 'stack' },
    scoringNotes: 'Affects featured_chef ranking, not visibility. Do not shame high/low budgets.',
  },

  {
    id: 'public.time',
    role: 'public',
    label: '{timeWindow}',
    labelTemplate: '{timeWindow}',
    category: 'occasion',
    baseUrgency: 50,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['time_of_day', 'browse_history'],
    freshnessWindow: '12h',
    pageAffinity: '/eat',
    pageAffinityBoost: 20,
    href: '/eat?dateWindow={window}',
    hrefTemplate: '/eat?dateWindow={window}',
    dataSources: ['chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'toggle_filter',
    maxImpressions: 30,
    cooldownMinutes: 30,
    renderHints: { presentation: 'pill', icon: 'search' },
    scoringNotes: 'Urgent windows get +20 boost. Expires at end of selected window.',
  },

  {
    id: 'public.group_size',
    role: 'public',
    label: '{sizeLabel}',
    labelTemplate: '{sizeLabel}',
    category: 'occasion',
    baseUrgency: 35,
    urgencyDecayFn: 'none',
    relevanceSignals: ['browse_history'],
    freshnessWindow: '30d',
    pageAffinity: '/eat',
    pageAffinityBoost: 15,
    href: '/eat?partySize={count}',
    hrefTemplate: '/eat?partySize={count}',
    dataSources: ['chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'toggle_filter',
    maxImpressions: -1,
    cooldownMinutes: 60,
    renderHints: { presentation: 'badge', icon: 'family' },
    scoringNotes: 'How many at the table. Boosts circle, occasion, and price items when selected.',
  },

  {
    id: 'public.hosting_format',
    role: 'public',
    label: '{formatName}',
    labelTemplate: '{formatName}',
    category: 'occasion',
    baseUrgency: 35,
    urgencyDecayFn: 'none',
    relevanceSignals: ['browse_history', 'occasion_affinity'],
    freshnessWindow: '7d',
    pageAffinity: '/eat',
    pageAffinityBoost: 15,
    href: '/eat?hosting={slug}',
    hrefTemplate: '/eat?hosting={slug}',
    dataSources: ['chef_marketplace_profiles', 'editorial_slots'],
    privacy: 'public',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'toggle_filter',
    maxImpressions: 40,
    cooldownMinutes: 60,
    renderHints: { presentation: 'pill', icon: 'dining' },
    scoringNotes: 'Your hosting style. Expands to matching occasions.',
  },

  {
    id: 'public.budget_range',
    role: 'public',
    label: '{min}-{max}/person',
    labelTemplate: '{min}-{max}/person',
    category: 'occasion',
    baseUrgency: 40,
    urgencyDecayFn: 'none',
    relevanceSignals: ['browse_history'],
    freshnessWindow: '30d',
    pageAffinity: '/eat,/chefs',
    pageAffinityBoost: 20,
    href: '/eat?budgetMin={min}&budgetMax={max}',
    hrefTemplate: '/eat?budgetMin={min}&budgetMax={max}',
    dataSources: ['chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'toggle_filter',
    maxImpressions: -1,
    cooldownMinutes: 60,
    renderHints: { presentation: 'badge', icon: 'stack' },
    scoringNotes: 'Set your budget. Explicit range complements the price tier pill.',
  },

  {
    id: 'public.party_tier',
    role: 'public',
    label: '{tierName}',
    labelTemplate: '{tierName}',
    category: 'occasion',
    baseUrgency: 30,
    urgencyDecayFn: 'none',
    relevanceSignals: ['browse_history'],
    freshnessWindow: '30d',
    pageAffinity: '/eat',
    pageAffinityBoost: 10,
    href: '/eat?partyTier={slug}',
    hrefTemplate: '/eat?partyTier={slug}',
    dataSources: ['chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'toggle_filter',
    maxImpressions: -1,
    cooldownMinutes: 60,
    renderHints: { presentation: 'pill', icon: 'family' },
    scoringNotes: 'Party tier descriptor. Low urgency, supplementary to group_size.',
  },

  {
    id: 'public.calendar_hook',
    role: 'public',
    label: '{eventName} is {daysAway}',
    labelTemplate: '{eventName} is {daysAway}',
    category: 'occasion',
    baseUrgency: 70,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['seasonal_context', 'browse_history'],
    freshnessWindow: '7d',
    pageAffinity: '/,/eat',
    pageAffinityBoost: 35,
    href: '/eat?intent={occasionSlug}&dateWindow={window}',
    hrefTemplate: '/eat?intent={occasionSlug}&dateWindow={window}',
    dataSources: ['seasonal_calendar', 'editorial_slots', 'chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 15,
    cooldownMinutes: 1440,
    renderHints: { presentation: 'card', icon: 'confetti' },
    scoringNotes: 'Start planning now. Peaks 7-21 days before event. Expires next day after event.',
  },

  {
    id: 'public.holiday',
    role: 'public',
    label: '{holidayName} dining',
    labelTemplate: '{holidayName} dining',
    category: 'occasion',
    baseUrgency: 75,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['seasonal_context', 'user_location'],
    freshnessWindow: '7d',
    pageAffinity: '/,/eat,/chefs',
    pageAffinityBoost: 40,
    href: '/eat?intent=holiday_party&dateWindow={holidayWindow}',
    hrefTemplate: '/eat?intent=holiday_party&dateWindow={holidayWindow}',
    dataSources: ['seasonal_calendar', 'editorial_slots', 'chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 20,
    cooldownMinutes: 1440,
    renderHints: { presentation: 'card', icon: 'confetti' },
    scoringNotes:
      'Highest occasion urgency. Starts 60 days before major holidays. Expires day after.',
  },

  {
    id: 'public.availability_pulse',
    role: 'public',
    label: '{count} chefs available {window}',
    labelTemplate: '{count} chefs available {window}',
    category: 'occasion',
    baseUrgency: 65,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['user_location', 'time_of_day'],
    freshnessWindow: '6h',
    pageAffinity: '/chefs,/eat,/',
    pageAffinityBoost: 30,
    href: '/eat?dateWindow={window}&location={location}',
    hrefTemplate: '/eat?dateWindow={window}&location={location}',
    dataSources: ['chef_marketplace_profiles', 'chef_profiles'],
    privacy: 'public',
    dismissable: false,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 20,
    cooldownMinutes: 60,
    renderHints: { presentation: 'badge', icon: 'chef' },
    scoringNotes:
      'Book now signal. Expires at end of availability window. Not dismissable to preserve urgency.',
  },

  {
    id: 'public.local_market',
    role: 'public',
    label: '{marketName}',
    labelTemplate: '{marketName}',
    category: 'occasion',
    baseUrgency: 35,
    urgencyDecayFn: 'none',
    relevanceSignals: ['user_location'],
    freshnessWindow: '7d',
    pageAffinity: '/,/eat',
    pageAffinityBoost: 15,
    href: '/eat?market={slug}',
    hrefTemplate: '/eat?market={slug}',
    dataSources: ['editorial_slots', 'chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 30,
    cooldownMinutes: 180,
    renderHints: { presentation: 'card', icon: 'market' },
    scoringNotes: 'Local food scene. Requires location context to be relevant.',
  },

  // ──────────────────────────────────────────────
  // CHEFFLOW PICKS Lane (11 items)
  // ──────────────────────────────────────────────

  {
    id: 'public.featured_chef',
    role: 'public',
    label: 'Chef {name}',
    labelTemplate: 'Chef {name}',
    category: 'chefflow_picks',
    baseUrgency: 55,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['user_location', 'cuisine_affinity', 'browse_history'],
    freshnessWindow: '14d',
    pageAffinity: '/chefs,/',
    pageAffinityBoost: 25,
    href: '/chef/{slug}',
    hrefTemplate: '/chef/{slug}',
    dataSources: ['chef_profiles', 'chef_marketplace_profiles', 'chef_culinary_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 15,
    cooldownMinutes: 360,
    renderHints: { presentation: 'card', icon: 'chef' },
    scoringNotes:
      '+25 taste score, +15 saved location, +12 social proof, +10 new/featured. Diversity fill rotates chefs.',
  },

  {
    id: 'public.chef_pick',
    role: 'public',
    label: '{pickLabel}',
    labelTemplate: '{pickLabel}',
    category: 'chefflow_picks',
    baseUrgency: 50,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['browse_history', 'user_location'],
    freshnessWindow: '30d',
    pageAffinity: '/,/eat,/chefs',
    pageAffinityBoost: 20,
    href: '{editorialHref}',
    hrefTemplate: '{editorialHref}',
    dataSources: ['editorial_slots', 'chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 20,
    cooldownMinutes: 180,
    renderHints: { presentation: 'card', icon: 'crown' },
    scoringNotes:
      'ChefFlow recommends. Fills when personalized data is sparse. Yields to saved chef updates.',
  },

  {
    id: 'public.combo',
    role: 'public',
    label: '{comboLabel}',
    labelTemplate: '{comboLabel}',
    category: 'chefflow_picks',
    baseUrgency: 40,
    urgencyDecayFn: 'none',
    relevanceSignals: ['browse_history', 'cuisine_affinity'],
    freshnessWindow: '7d',
    pageAffinity: '/eat',
    pageAffinityBoost: 15,
    href: '/eat?cuisine={cuisine}&intent={intent}&budget={budget}',
    hrefTemplate: '/eat?cuisine={cuisine}&intent={intent}&budget={budget}',
    dataSources: ['chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 30,
    cooldownMinutes: 120,
    renderHints: { presentation: 'pill', icon: 'utensils' },
    scoringNotes: 'Multi-signal combined filter. +10 per user-backed facet, capped at +35.',
  },

  {
    id: 'public.story',
    role: 'public',
    label: '{storyTitle}',
    labelTemplate: '{storyTitle}',
    category: 'chefflow_picks',
    baseUrgency: 35,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['browse_history', 'seasonal_context'],
    freshnessWindow: '45d',
    pageAffinity: '/,/eat',
    pageAffinityBoost: 15,
    href: '{storyHref}',
    hrefTemplate: '{storyHref}',
    dataSources: ['editorial_slots'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 10,
    cooldownMinutes: 720,
    renderHints: { presentation: 'story', icon: 'spark' },
    scoringNotes:
      'ChefFlow editorial. Delight/education. Yields to persistence and recovery items.',
  },

  {
    id: 'public.surprise',
    role: 'public',
    label: 'Surprise me',
    labelTemplate: 'Surprise me',
    category: 'chefflow_picks',
    baseUrgency: 25,
    urgencyDecayFn: 'none',
    relevanceSignals: ['session_repetition'],
    freshnessWindow: '1h',
    pageAffinity: '/eat,/',
    pageAffinityBoost: 10,
    href: '/eat?mode=surprise',
    hrefTemplate: '/eat?mode=surprise',
    dataSources: ['chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'pill', icon: 'spark' },
    scoringNotes:
      'Injects novelty when session is repetitive. Cannot override safety/dietary exclusions.',
  },

  {
    id: 'public.saved',
    role: 'public',
    label: '{savedLabel}',
    labelTemplate: '{savedLabel}',
    category: 'chefflow_picks',
    baseUrgency: 45,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['browse_history'],
    freshnessWindow: '30d',
    pageAffinity: '/,/eat',
    pageAffinityBoost: 20,
    href: '{savedHref}',
    hrefTemplate: '{savedHref}',
    dataSources: ['discovery_profile_items'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 20,
    cooldownMinutes: 60,
    renderHints: { presentation: 'pill', icon: 'search' },
    scoringNotes: 'Pick up where you left off. localStorage-based for public users.',
  },

  {
    id: 'public.editorial_collection',
    role: 'public',
    label: '{collectionTitle}',
    labelTemplate: '{collectionTitle}',
    category: 'chefflow_picks',
    baseUrgency: 45,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['browse_history', 'seasonal_context'],
    freshnessWindow: '30d',
    pageAffinity: '/,/eat,/chefs',
    pageAffinityBoost: 20,
    href: '/eat?collection={slug}',
    hrefTemplate: '/eat?collection={slug}',
    dataSources: ['editorial_slots', 'chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 15,
    cooldownMinutes: 360,
    renderHints: { presentation: 'card', icon: 'crown' },
    scoringNotes: 'Curated collections. Provides fallback when personalized data is sparse.',
  },

  {
    id: 'public.chef_spotlight_story',
    role: 'public',
    label: 'Meet Chef {name}',
    labelTemplate: 'Meet Chef {name}',
    category: 'chefflow_picks',
    baseUrgency: 50,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['cuisine_affinity', 'user_location'],
    freshnessWindow: '14d',
    pageAffinity: '/,/chefs',
    pageAffinityBoost: 25,
    href: '/chef/{slug}?source=spotlight',
    hrefTemplate: '/chef/{slug}?source=spotlight',
    dataSources: ['chef_profiles', 'chef_marketplace_profiles', 'editorial_slots'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 10,
    cooldownMinutes: 720,
    renderHints: { presentation: 'story', icon: 'chef' },
    scoringNotes: 'Long-form chef story. Specialty and area match boost relevance.',
  },

  {
    id: 'public.chef_video',
    role: 'public',
    label: 'Watch: {title}',
    labelTemplate: 'Watch: {title}',
    category: 'chefflow_picks',
    baseUrgency: 45,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['browse_history', 'cuisine_affinity'],
    freshnessWindow: '14d',
    pageAffinity: '/,/chefs',
    pageAffinityBoost: 20,
    href: '/chef/{slug}?source=video',
    hrefTemplate: '/chef/{slug}?source=video',
    dataSources: ['chef_profiles', 'chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: 10,
    cooldownMinutes: 720,
    renderHints: { presentation: 'card', icon: 'chef' },
    scoringNotes: 'Chef in action video. Expand inline to play. High engagement potential.',
  },

  {
    id: 'public.dish_visual',
    role: 'public',
    label: '{dishName}',
    labelTemplate: '{dishName}',
    category: 'chefflow_picks',
    baseUrgency: 40,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['cuisine_affinity', 'browse_history'],
    freshnessWindow: '14d',
    pageAffinity: '/,/eat',
    pageAffinityBoost: 20,
    href: '/chef/{slug}?dish={dishSlug}',
    hrefTemplate: '/chef/{slug}?dish={dishSlug}',
    dataSources: ['chef_marketplace_profiles', 'chef_culinary_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 15,
    cooldownMinutes: 360,
    renderHints: { presentation: 'card', icon: 'dining' },
    scoringNotes: 'Visual dish card by chef. Cuisine match and browse history boost.',
  },

  {
    id: 'public.quick_compare',
    role: 'public',
    label: 'Compare {count} chefs',
    labelTemplate: 'Compare {count} chefs',
    category: 'chefflow_picks',
    baseUrgency: 35,
    urgencyDecayFn: 'none',
    relevanceSignals: ['browse_history'],
    freshnessWindow: '1h',
    pageAffinity: '/chefs',
    pageAffinityBoost: 25,
    href: '/eat?mode=compare',
    hrefTemplate: '/eat?mode=compare',
    dataSources: ['chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: false,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'pill', icon: 'search' },
    scoringNotes: 'Side by side comparison prompt. Always available on chef listings.',
  },

  // ──────────────────────────────────────────────
  // ENGAGEMENT Lane (10 items)
  // ──────────────────────────────────────────────

  {
    id: 'public.trending',
    role: 'public',
    label: 'Trending: {label}',
    labelTemplate: 'Trending: {label}',
    category: 'engagement',
    baseUrgency: 50,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['browse_history', 'user_location'],
    freshnessWindow: '24h',
    pageAffinity: '/,/eat,/chefs',
    pageAffinityBoost: 20,
    href: '/eat?trend={slug}',
    hrefTemplate: '/eat?trend={slug}',
    dataSources: ['discovery_interactions', 'chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'toggle_filter',
    maxImpressions: 25,
    cooldownMinutes: 120,
    renderHints: { presentation: 'badge', icon: 'flame' },
    scoringNotes: 'Trend window usually 24-72 hours. Minimum aggregate threshold required.',
  },

  {
    id: 'public.new_on_chefflow',
    role: 'public',
    label: 'New: {label}',
    labelTemplate: 'New: {label}',
    category: 'engagement',
    baseUrgency: 55,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['user_location', 'cuisine_affinity'],
    freshnessWindow: '21d',
    pageAffinity: '/,/chefs',
    pageAffinityBoost: 20,
    href: '/chef/{slug}?source=new_on_chefflow',
    hrefTemplate: '/chef/{slug}?source=new_on_chefflow',
    dataSources: ['chef_profiles', 'chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 15,
    cooldownMinutes: 360,
    renderHints: { presentation: 'badge', icon: 'spark' },
    scoringNotes: 'Freshness decays linearly over 21 days. Provides novelty to avoid overfitting.',
  },

  {
    id: 'public.social_proof',
    role: 'public',
    label: '{count} people {action}',
    labelTemplate: '{count} people {action}',
    category: 'engagement',
    baseUrgency: 45,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['user_location', 'browse_history'],
    freshnessWindow: '24h',
    pageAffinity: '/,/eat',
    pageAffinityBoost: 15,
    href: '{proofHref}',
    hrefTemplate: '{proofHref}',
    dataSources: ['discovery_interactions', 'chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 20,
    cooldownMinutes: 180,
    renderHints: { presentation: 'badge', icon: 'cheers' },
    scoringNotes:
      'Aggregate social proof. Must pass k-anonymous threshold. Never stacks more than two.',
  },

  {
    id: 'public.comparison_prompt',
    role: 'public',
    label: "Can't decide?",
    labelTemplate: "Can't decide?",
    category: 'engagement',
    baseUrgency: 30,
    urgencyDecayFn: 'none',
    relevanceSignals: ['browse_history'],
    freshnessWindow: '1h',
    pageAffinity: '/chefs,/eat',
    pageAffinityBoost: 20,
    href: '/eat?mode=compare',
    hrefTemplate: '/eat?mode=compare',
    dataSources: ['chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 10,
    cooldownMinutes: 720,
    renderHints: { presentation: 'pill', icon: 'search' },
    scoringNotes: 'Compare chefs side by side. Shows after multiple chef profile views.',
  },

  {
    id: 'public.guided_flow',
    role: 'public',
    label: '{flowTitle}',
    labelTemplate: '{flowTitle}',
    category: 'engagement',
    baseUrgency: 55,
    urgencyDecayFn: 'none',
    relevanceSignals: ['browse_history'],
    freshnessWindow: '7d',
    pageAffinity: '/,/eat',
    pageAffinityBoost: 30,
    href: '/eat?flow={slug}',
    hrefTemplate: '/eat?flow={slug}',
    dataSources: ['editorial_slots', 'chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 8,
    cooldownMinutes: 1440,
    renderHints: { presentation: 'card', icon: 'concierge' },
    scoringNotes: 'Step-by-step planning flow. High engagement, low frequency to avoid fatigue.',
  },

  {
    id: 'public.signup_nudge',
    role: 'public',
    label: '{nudgeText}',
    labelTemplate: '{nudgeText}',
    category: 'engagement',
    baseUrgency: 20,
    urgencyDecayFn: 'none',
    relevanceSignals: ['browse_history', 'session_depth'],
    freshnessWindow: '7d',
    pageAffinity: '/chefs,/eat,/',
    pageAffinityBoost: 10,
    href: '/sign-up?source=rail',
    hrefTemplate: '/sign-up?source=rail',
    dataSources: [],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 5,
    cooldownMinutes: 2880,
    renderHints: { presentation: 'badge', icon: 'spark' },
    scoringNotes:
      'Unlock more features. Low urgency, earned by engagement depth. Never first-screen noise.',
  },

  {
    id: 'public.recovery',
    role: 'public',
    label: '{recoveryText}',
    labelTemplate: '{recoveryText}',
    category: 'engagement',
    baseUrgency: 70,
    urgencyDecayFn: 'none',
    relevanceSignals: ['route_context'],
    freshnessWindow: '0',
    pageAffinity: '/404',
    pageAffinityBoost: 40,
    href: '/eat?source=recovery',
    hrefTemplate: '/eat?source=recovery&from={routeKind}',
    dataSources: ['chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'pill', icon: 'search' },
    scoringNotes:
      'Try something different. Context-only priority for 404 and empty results. Suppresses conversion nudges.',
  },

  {
    id: 'public.cross_sell',
    role: 'public',
    label: '{offerLabel}',
    labelTemplate: '{offerLabel}',
    category: 'engagement',
    baseUrgency: 15,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['browse_history', 'seasonal_context'],
    freshnessWindow: '30d',
    pageAffinity: '/,/eat',
    pageAffinityBoost: 5,
    href: '/gift-cards?source=rail',
    hrefTemplate: '/gift-cards?source=rail',
    dataSources: ['editorial_slots'],
    privacy: 'public',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 5,
    cooldownMinutes: 4320,
    renderHints: { presentation: 'card', icon: 'crown' },
    scoringNotes:
      'Lowest urgency. Seasonal boost near gift-giving holidays. Never outranks discovery.',
  },

  {
    id: 'public.ask_chefflow',
    role: 'public',
    label: 'Ask ChefFlow',
    labelTemplate: 'Ask ChefFlow',
    category: 'engagement',
    baseUrgency: 40,
    urgencyDecayFn: 'none',
    relevanceSignals: ['session_depth', 'browse_history'],
    freshnessWindow: '1h',
    pageAffinity: '/,/eat,/chefs',
    pageAffinityBoost: 15,
    href: '/eat?ask=1',
    hrefTemplate: '/eat?ask=1',
    dataSources: ['chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'pill', icon: 'concierge' },
    scoringNotes:
      'Describe what you want. Natural language discovery entry point. Always available.',
  },

  {
    id: 'public.world_food_day',
    role: 'public',
    label: '{eventName}',
    labelTemplate: '{eventName}',
    category: 'engagement',
    baseUrgency: 65,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['seasonal_context'],
    freshnessWindow: '7d',
    pageAffinity: '/,/eat',
    pageAffinityBoost: 35,
    href: '/eat?event={slug}',
    hrefTemplate: '/eat?event={slug}',
    dataSources: ['seasonal_calendar', 'editorial_slots', 'chef_marketplace_profiles'],
    privacy: 'public',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 10,
    cooldownMinutes: 1440,
    renderHints: { presentation: 'card', icon: 'confetti' },
    scoringNotes:
      'Celebrate with food. World food days and cultural food events. Deadline decay around event date.',
  },
] as const
