import type { UniversalRailItemDefinition } from '../universal-rail-types'

// Staff role: 57 items. Tenant-scoped. NEVER sees client financials or business metrics.

// ============================================================================
// Shift and Schedule (10 items)
// ============================================================================

const SHIFT_AND_SCHEDULE: UniversalRailItemDefinition[] = [
  {
    id: 'staff.availability_conflict',
    role: 'staff',
    label: 'Availability Conflict',
    labelTemplate: 'Conflict: {day} marked unavailable',
    category: 'Shift and Schedule',
    baseUrgency: 88,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['conflict_date', 'assigned_shift', 'event_linked'],
    freshnessWindow: '24h',
    pageAffinity: '/staff-schedule',
    pageAffinityBoost: 35,
    href: '/staff-schedule',
    hrefTemplate: '/staff-schedule?date={date}&conflict={conflictId}',
    dataSources: ['staff_availability', 'staff_assignments', 'events'],
    privacy: 'tenant_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'AlertTriangle', priority: 'high' },
    scoringNotes: 'Safety/coverage risk; boost inside 24h and if event-linked',
  },
  {
    id: 'staff.clock_in_reminder',
    role: 'staff',
    label: 'Clock In Reminder',
    labelTemplate: 'Shift starts in {minutes} minutes',
    category: 'Shift and Schedule',
    baseUrgency: 82,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['shift_start_time', 'clock_state', 'station_assignment'],
    freshnessWindow: '30m',
    pageAffinity: '/staff-time',
    pageAffinityBoost: 40,
    href: '/staff-time',
    hrefTemplate: '/staff-time?shift={shiftId}',
    dataSources: ['staff_assignments', 'staff_shifts', 'staff_clock_entries'],
    privacy: 'tenant_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'LogIn', priority: 'high' },
    scoringNotes: 'Highest in 30m before start; reduce if already clocked in',
  },
  {
    id: 'staff.clock_out_reminder',
    role: 'staff',
    label: 'Clock Out Reminder',
    labelTemplate: 'You have been clocked in for {hours} hours',
    category: 'Shift and Schedule',
    baseUrgency: 86,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['active_clock_entry', 'scheduled_end', 'duration_threshold'],
    freshnessWindow: '1h',
    pageAffinity: '/staff-time',
    pageAffinityBoost: 40,
    href: '/staff-time',
    hrefTemplate: '/staff-time?entry={clockEntryId}',
    dataSources: ['staff_clock_entries', 'staff_assignments'],
    privacy: 'tenant_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'LogOut', priority: 'high' },
    scoringNotes: 'Boost after scheduled end, critical after 10h',
  },
  {
    id: 'staff.no_shifts_next_week',
    role: 'staff',
    label: 'No Shifts Warning',
    labelTemplate: 'No shifts scheduled next week',
    category: 'Shift and Schedule',
    baseUrgency: 38,
    urgencyDecayFn: 'none',
    relevanceSignals: ['schedule_gap', 'recurring_shifts'],
    freshnessWindow: '7d',
    pageAffinity: '/staff-schedule',
    pageAffinityBoost: 20,
    href: '/staff-schedule',
    hrefTemplate: '/staff-schedule?week={weekStart}',
    dataSources: ['staff_assignments', 'staff_shifts'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 3,
    cooldownMinutes: 1440,
    renderHints: { presentation: 'badge', icon: 'CalendarX', priority: 'low' },
    scoringNotes: 'Low unless staff usually has recurring shifts',
  },
  {
    id: 'staff.overtime_warning',
    role: 'staff',
    label: 'Overtime Warning',
    labelTemplate: 'Overtime warning: {hours} hours this week',
    category: 'Shift and Schedule',
    baseUrgency: 75,
    urgencyDecayFn: 'none',
    relevanceSignals: ['weekly_hours', 'overtime_threshold', 'scheduled_remaining'],
    freshnessWindow: '7d',
    pageAffinity: '/staff-time',
    pageAffinityBoost: 35,
    href: '/staff-time',
    hrefTemplate: '/staff-time?week={weekStart}&focus=overtime',
    dataSources: ['staff_clock_entries', 'staff_assignments'],
    privacy: 'tenant_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'Gauge', priority: 'high' },
    scoringNotes: 'Boost at 38h, critical at 40h or tenant-config threshold',
  },
  {
    id: 'staff.schedule_change_alert',
    role: 'staff',
    label: 'Schedule Change',
    labelTemplate: 'Schedule changed: {oldDayTime} -> {newDayTime}',
    category: 'Shift and Schedule',
    baseUrgency: 84,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['change_window', 'affected_shift', 'event_linked'],
    freshnessWindow: '48h',
    pageAffinity: '/staff-schedule',
    pageAffinityBoost: 40,
    href: '/staff-schedule',
    hrefTemplate: '/staff-schedule?change={changeId}',
    dataSources: ['staff_schedule_changes', 'staff_assignments', 'notifications'],
    privacy: 'tenant_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'CalendarSync', priority: 'high' },
    scoringNotes: 'Boost if change affects next 48h',
  },
  {
    id: 'staff.shift_coverage_request',
    role: 'staff',
    label: 'Coverage Request',
    labelTemplate: 'Coverage needed: {day} {time}',
    category: 'Shift and Schedule',
    baseUrgency: 70,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['role_match', 'shift_start_time', 'availability'],
    freshnessWindow: '48h',
    pageAffinity: '/staff-schedule',
    pageAffinityBoost: 30,
    href: '/staff-schedule',
    hrefTemplate: '/staff-schedule?coverage={requestId}',
    dataSources: ['staff_coverage_requests', 'staff_assignments', 'staff_availability'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: 5,
    cooldownMinutes: 240,
    renderHints: { presentation: 'alert', icon: 'UsersRound', priority: 'normal' },
    scoringNotes: 'Higher if role matches staff and shift starts soon',
  },
  {
    id: 'staff.shift_swap_request',
    role: 'staff',
    label: 'Shift Swap Request',
    labelTemplate: '{staffName} wants to swap {shiftLabel}',
    category: 'Shift and Schedule',
    baseUrgency: 64,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['response_deadline', 'shift_compatibility', 'availability'],
    freshnessWindow: '48h',
    pageAffinity: '/staff-schedule',
    pageAffinityBoost: 30,
    href: '/staff-schedule',
    hrefTemplate: '/staff-schedule?swap={swapId}',
    dataSources: ['shift_swap_requests', 'staff_assignments', 'staff_availability'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: -1,
    cooldownMinutes: 120,
    renderHints: { presentation: 'pill', icon: 'ArrowLeftRight', priority: 'normal' },
    scoringNotes: 'Boost if response deadline within 24h',
  },
  {
    id: 'staff.todays_shift',
    role: 'staff',
    label: "Today's Shift",
    labelTemplate: 'You are on {startTime}-{endTime} today',
    category: 'Shift and Schedule',
    baseUrgency: 78,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['shift_active', 'clock_state', 'station_assignment'],
    freshnessWindow: '24h',
    pageAffinity: '/staff-dashboard',
    pageAffinityBoost: 40,
    href: '/staff-schedule',
    hrefTemplate: '/staff-schedule?shift={shiftId}',
    dataSources: ['staff_assignments', 'staff_shifts', 'events', 'staff_clock_entries'],
    privacy: 'tenant_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'card', icon: 'Calendar', priority: 'high' },
    scoringNotes: 'Higher before and during shift; lower after clock-out',
  },
  {
    id: 'staff.upcoming_shifts_week',
    role: 'staff',
    label: 'Upcoming Shifts',
    labelTemplate: '{count} shifts this week',
    category: 'Shift and Schedule',
    baseUrgency: 52,
    urgencyDecayFn: 'none',
    relevanceSignals: ['shift_count', 'schedule_changes'],
    freshnessWindow: '7d',
    pageAffinity: '/staff-schedule',
    pageAffinityBoost: 25,
    href: '/staff-schedule',
    hrefTemplate: '/staff-schedule?week={weekStart}',
    dataSources: ['staff_assignments', 'staff_shifts'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 5,
    cooldownMinutes: 720,
    renderHints: { presentation: 'pill', icon: 'CalendarDays', priority: 'normal' },
    scoringNotes: 'Lower if todays shift is active; boost after schedule changes',
  },
]

// ============================================================================
// Tasks and Delegation (10 items)
// ============================================================================

const TASKS_AND_DELEGATION: UniversalRailItemDefinition[] = [
  {
    id: 'staff.bulk_task_list',
    role: 'staff',
    label: 'Bulk Task List',
    labelTemplate: '{count} tasks for {eventOrToday}',
    category: 'Tasks and Delegation',
    baseUrgency: 72,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['task_count', 'overdue_count', 'event_linked'],
    freshnessWindow: '24h',
    pageAffinity: '/staff-tasks',
    pageAffinityBoost: 30,
    href: '/staff-tasks',
    hrefTemplate: '/staff-tasks?event={eventId}&date={date}',
    dataSources: ['tasks', 'events', 'stations'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: -1,
    cooldownMinutes: 30,
    renderHints: { presentation: 'progress', icon: 'ListChecks', priority: 'high' },
    scoringNotes: 'Higher when count includes overdue/urgent tasks',
  },
  {
    id: 'staff.new_task_assigned',
    role: 'staff',
    label: 'New Task',
    labelTemplate: 'New task: {taskTitle}',
    category: 'Tasks and Delegation',
    baseUrgency: 78,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['task_priority', 'due_time', 'chef_message'],
    freshnessWindow: '24h',
    pageAffinity: '/staff-tasks',
    pageAffinityBoost: 35,
    href: '/staff-tasks',
    hrefTemplate: '/staff-tasks?task={taskId}',
    dataSources: ['tasks', 'notifications', 'staff_activity'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: -1,
    cooldownMinutes: 30,
    renderHints: { presentation: 'alert', icon: 'ClipboardPlus', priority: 'high' },
    scoringNotes: 'Boost if urgent, due today, or from chef message',
  },
  {
    id: 'staff.task_completed_confirmation',
    role: 'staff',
    label: 'Task Completed',
    labelTemplate: 'Completed: {taskTitle}',
    category: 'Tasks and Delegation',
    baseUrgency: 24,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['completion_time', 'next_dependency'],
    freshnessWindow: '30m',
    pageAffinity: '/staff-tasks',
    pageAffinityBoost: 10,
    href: '/staff-tasks',
    hrefTemplate: '/staff-tasks?task={taskId}',
    dataSources: ['tasks', 'staff_activity', 'notifications'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: 2,
    cooldownMinutes: 1440,
    renderHints: { presentation: 'badge', icon: 'CheckCircle2', priority: 'low' },
    scoringNotes: 'Confirmation only; never displace active work',
  },
  {
    id: 'staff.task_dependency',
    role: 'staff',
    label: 'Task Blocked',
    labelTemplate: 'Blocked: {taskTitle}',
    category: 'Tasks and Delegation',
    baseUrgency: 64,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['blocker_status', 'task_due_time', 'dependency_owner'],
    freshnessWindow: '24h',
    pageAffinity: '/staff-tasks',
    pageAffinityBoost: 30,
    href: '/staff-tasks',
    hrefTemplate: '/staff-tasks?task={taskId}&blocked=true',
    dataSources: ['task_dependencies', 'tasks', 'staff_activity'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: -1,
    cooldownMinutes: 120,
    renderHints: { presentation: 'alert', icon: 'GitBranch', priority: 'normal' },
    scoringNotes: 'Boost if task due soon but blocked',
  },
  {
    id: 'staff.task_due_soon',
    role: 'staff',
    label: 'Task Due Soon',
    labelTemplate: 'Due soon: {taskTitle}',
    category: 'Tasks and Delegation',
    baseUrgency: 82,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['due_time', 'task_priority', 'station_assignment'],
    freshnessWindow: '2h',
    pageAffinity: '/staff-tasks',
    pageAffinityBoost: 35,
    href: '/staff-tasks',
    hrefTemplate: '/staff-tasks?task={taskId}',
    dataSources: ['tasks', 'events', 'stations'],
    privacy: 'tenant_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'AlarmClock', priority: 'high' },
    scoringNotes: 'Boost under 60m and if urgent/high',
  },
  {
    id: 'staff.task_notes_from_chef',
    role: 'staff',
    label: 'Chef Note on Task',
    labelTemplate: 'Chef note: {noteExcerpt}',
    category: 'Tasks and Delegation',
    baseUrgency: 62,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['note_recency', 'task_viewed_state', 'event_linked'],
    freshnessWindow: '24h',
    pageAffinity: '/staff-tasks',
    pageAffinityBoost: 25,
    href: '/staff-tasks',
    hrefTemplate: '/staff-tasks?task={taskId}&note={noteId}',
    dataSources: ['task_comments', 'tasks', 'notifications'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: -1,
    cooldownMinutes: 60,
    renderHints: { presentation: 'pill', icon: 'StickyNote', priority: 'normal' },
    scoringNotes: 'Boost if note added after staff viewed task',
  },
  {
    id: 'staff.task_overdue',
    role: 'staff',
    label: 'Task Overdue',
    labelTemplate: 'Overdue: {taskTitle}',
    category: 'Tasks and Delegation',
    baseUrgency: 94,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['overdue_duration', 'task_priority', 'service_risk'],
    freshnessWindow: '24h',
    pageAffinity: '/staff-tasks',
    pageAffinityBoost: 45,
    href: '/staff-tasks',
    hrefTemplate: '/staff-tasks?task={taskId}&status=overdue',
    dataSources: ['tasks'],
    privacy: 'tenant_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'Siren', priority: 'high' },
    scoringNotes: 'Top-ranked non-safety item; critical if service at risk',
  },
  {
    id: 'staff.task_priority_change',
    role: 'staff',
    label: 'Priority Changed',
    labelTemplate: 'Priority changed: {taskTitle} is {priority}',
    category: 'Tasks and Delegation',
    baseUrgency: 70,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['priority_delta', 'task_due_time', 'chef_note'],
    freshnessWindow: '24h',
    pageAffinity: '/staff-tasks',
    pageAffinityBoost: 25,
    href: '/staff-tasks',
    hrefTemplate: '/staff-tasks?task={taskId}',
    dataSources: ['task_audit', 'tasks', 'notifications'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: -1,
    cooldownMinutes: 60,
    renderHints: { presentation: 'alert', icon: 'SignalHigh', priority: 'normal' },
    scoringNotes: 'Boost if bumped to urgent/high',
  },
  {
    id: 'staff.task_reassigned',
    role: 'staff',
    label: 'Task Reassigned',
    labelTemplate: 'Reassigned: {taskTitle}',
    category: 'Tasks and Delegation',
    baseUrgency: 42,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['reassignment_reason', 'remaining_tasks'],
    freshnessWindow: '24h',
    pageAffinity: '/staff-tasks',
    pageAffinityBoost: 15,
    href: '/staff-tasks',
    hrefTemplate: '/staff-tasks?task={taskId}',
    dataSources: ['task_audit', 'tasks', 'notifications'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: 3,
    cooldownMinutes: 720,
    renderHints: { presentation: 'badge', icon: 'UserRoundCog', priority: 'low' },
    scoringNotes: 'Low unless staff has dependent follow-up work',
  },
  {
    id: 'staff.recurring_task_due',
    role: 'staff',
    label: 'Recurring Task',
    labelTemplate: 'Recurring: {taskTitle}',
    category: 'Tasks and Delegation',
    baseUrgency: 56,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['recurrence_cadence', 'current_due_date'],
    freshnessWindow: '24h',
    pageAffinity: '/staff-tasks',
    pageAffinityBoost: 25,
    href: '/staff-tasks',
    hrefTemplate: '/staff-tasks?task={taskId}',
    dataSources: ['tasks', 'task_recurrences', 'notifications'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: -1,
    cooldownMinutes: 120,
    renderHints: { presentation: 'pill', icon: 'Repeat', priority: 'normal' },
    scoringNotes: 'Lower than event-critical tasks unless overdue',
  },
]

// ============================================================================
// Station Assignments (5 items)
// ============================================================================

const STATION_ASSIGNMENTS: UniversalRailItemDefinition[] = [
  {
    id: 'staff.current_station',
    role: 'staff',
    label: 'Current Station',
    labelTemplate: 'You are on {stationName} today',
    category: 'Station Assignments',
    baseUrgency: 76,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['station_active', 'shift_today', 'clocked_in'],
    freshnessWindow: '24h',
    pageAffinity: '/staff-station',
    pageAffinityBoost: 40,
    href: '/staff-station',
    hrefTemplate: '/staff-station?station={stationId}&date={date}',
    dataSources: ['staff_assignments', 'stations', 'tasks', 'events'],
    privacy: 'tenant_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'card', icon: 'ChefHat', priority: 'high' },
    scoringNotes: 'Boost if shift is today or staff is clocked in',
  },
  {
    id: 'staff.station_change',
    role: 'staff',
    label: 'Station Change',
    labelTemplate: 'Station changed: {oldStation} -> {newStation}',
    category: 'Station Assignments',
    baseUrgency: 82,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['change_timing', 'readiness_gaps', 'clocked_in'],
    freshnessWindow: '24h',
    pageAffinity: '/staff-station',
    pageAffinityBoost: 40,
    href: '/staff-station',
    hrefTemplate: '/staff-station?station={stationId}&changed={changeId}',
    dataSources: ['station_assignments', 'staff_assignments', 'notifications'],
    privacy: 'tenant_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'Shuffle', priority: 'high' },
    scoringNotes: 'Boost if same-day or after clock-in',
  },
  {
    id: 'staff.station_equipment_check',
    role: 'staff',
    label: 'Equipment Check',
    labelTemplate: 'Check {stationName} equipment',
    category: 'Station Assignments',
    baseUrgency: 60,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['checklist_incomplete', 'service_approaching'],
    freshnessWindow: '4h',
    pageAffinity: '/staff-station',
    pageAffinityBoost: 30,
    href: '/staff-station',
    hrefTemplate: '/staff-station?station={stationId}&panel=equipment',
    dataSources: ['station_equipment_checks', 'station_checklists', 'tasks'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: -1,
    cooldownMinutes: 120,
    renderHints: { presentation: 'pill', icon: 'Wrench', priority: 'normal' },
    scoringNotes: 'Higher before service; lower once completed recently',
  },
  {
    id: 'staff.station_handoff',
    role: 'staff',
    label: 'Station Handoff',
    labelTemplate: 'Handoff: take over from {staffName} at {time}',
    category: 'Station Assignments',
    baseUrgency: 74,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['handoff_time', 'clocked_in', 'unresolved_notes'],
    freshnessWindow: '2h',
    pageAffinity: '/staff-station',
    pageAffinityBoost: 35,
    href: '/staff-station',
    hrefTemplate: '/staff-station?handoff={handoffId}',
    dataSources: ['station_handoffs', 'staff_assignments', 'tasks'],
    privacy: 'tenant_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'Handshake', priority: 'high' },
    scoringNotes: 'Boost in 30m before handoff and while clocked in',
  },
  {
    id: 'staff.station_prep_checklist',
    role: 'staff',
    label: 'Station Prep',
    labelTemplate: '{stationName}: {remaining} items to prep',
    category: 'Station Assignments',
    baseUrgency: 78,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['checklist_progress', 'service_approaching', 'blockers'],
    freshnessWindow: '4h',
    pageAffinity: '/staff-station',
    pageAffinityBoost: 40,
    href: '/staff-station',
    hrefTemplate: '/staff-station?station={stationId}&panel=prep',
    dataSources: ['station_checklists', 'tasks', 'recipes', 'events'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: -1,
    cooldownMinutes: 60,
    renderHints: { presentation: 'progress', icon: 'ClipboardCheck', priority: 'high' },
    scoringNotes: 'Higher for active station and approaching service',
  },
]

// ============================================================================
// Event Context (7 items)
// ============================================================================

const EVENT_CONTEXT: UniversalRailItemDefinition[] = [
  {
    id: 'staff.event_dietary_alerts',
    role: 'staff',
    label: 'Dietary Alert',
    labelTemplate: 'Dietary alert: {alertSummary}',
    category: 'Event Context',
    baseUrgency: 96,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['allergen_severity', 'event_window', 'station_assignment'],
    freshnessWindow: '24h',
    pageAffinity: '/staff-dashboard',
    pageAffinityBoost: 45,
    href: '/staff-station',
    hrefTemplate: '/staff-station?event={eventId}&panel=dietary',
    dataSources: ['event_guests', 'dietary_restrictions', 'menus'],
    privacy: 'tenant_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'ShieldAlert', priority: 'high' },
    scoringNotes: 'Safety item; almost always top-ranked during event window',
  },
  {
    id: 'staff.event_menu',
    role: 'staff',
    label: 'Event Menu',
    labelTemplate: 'Menu: {courseCount} courses for {eventLabel}',
    category: 'Event Context',
    baseUrgency: 64,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['assigned_courses', 'recipe_opened_state', 'event_window'],
    freshnessWindow: '24h',
    pageAffinity: '/staff-dashboard',
    pageAffinityBoost: 30,
    href: '/staff-recipes',
    hrefTemplate: '/staff-recipes?event={eventId}',
    dataSources: ['events', 'menus', 'dishes', 'components', 'staff_assignments'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: 5,
    cooldownMinutes: 240,
    renderHints: { presentation: 'card', icon: 'Utensils', priority: 'normal' },
    scoringNotes: 'Boost if recipes not yet opened or station owns multiple dishes',
  },
  {
    id: 'staff.event_special_instructions',
    role: 'staff',
    label: 'Special Instruction',
    labelTemplate: 'Special instruction: {shortInstruction}',
    category: 'Event Context',
    baseUrgency: 74,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['instruction_timing', 'safety_critical', 'station_linked'],
    freshnessWindow: '24h',
    pageAffinity: '/staff-dashboard',
    pageAffinityBoost: 30,
    href: '/staff-tasks',
    hrefTemplate: '/staff-tasks?event={eventId}&instruction={instructionId}',
    dataSources: ['event_notes', 'staff_briefings', 'tasks', 'notifications'],
    privacy: 'tenant_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'Sparkles', priority: 'high' },
    scoringNotes: 'High if time-bound or safety/service-critical',
  },
  {
    id: 'staff.event_timeline',
    role: 'staff',
    label: 'Event Timeline',
    labelTemplate: '{nextMilestone} at {time}',
    category: 'Event Context',
    baseUrgency: 78,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['next_milestone', 'staff_owns_step', 'event_window'],
    freshnessWindow: '24h',
    pageAffinity: '/staff-dashboard',
    pageAffinityBoost: 35,
    href: '/staff-dashboard',
    hrefTemplate: '/staff-dashboard?event={eventId}&panel=timeline',
    dataSources: ['events', 'event_timeline', 'tasks'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: -1,
    cooldownMinutes: 60,
    renderHints: { presentation: 'progress', icon: 'CalendarClock', priority: 'high' },
    scoringNotes: 'Boost near next milestone; higher if staff owns it',
  },
  {
    id: 'staff.post_event_cleanup',
    role: 'staff',
    label: 'Post-Event Cleanup',
    labelTemplate: 'Cleanup: {count} tasks after {eventLabel}',
    category: 'Event Context',
    baseUrgency: 70,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['cleanup_remaining', 'venue_close_time', 'station_assigned'],
    freshnessWindow: '4h',
    pageAffinity: '/staff-tasks',
    pageAffinityBoost: 30,
    href: '/staff-tasks',
    hrefTemplate: '/staff-tasks?event={eventId}&phase=cleanup',
    dataSources: ['tasks', 'event_timeline', 'stations'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: -1,
    cooldownMinutes: 60,
    renderHints: { presentation: 'progress', icon: 'SprayCan', priority: 'normal' },
    scoringNotes: 'Boost after service milestone; overdue if venue close time near',
  },
  {
    id: 'staff.today_event_summary',
    role: 'staff',
    label: "Today's Event",
    labelTemplate: 'Today: {eventType}, {guestCount} guests, {menuTheme}',
    category: 'Event Context',
    baseUrgency: 74,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['event_today', 'staff_assigned', 'safety_flags'],
    freshnessWindow: '24h',
    pageAffinity: '/staff-dashboard',
    pageAffinityBoost: 35,
    href: '/staff-dashboard',
    hrefTemplate: '/staff-dashboard?event={eventId}',
    dataSources: ['events', 'staff_assignments', 'menus', 'tasks'],
    privacy: 'tenant_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'card', icon: 'CalendarCheck', priority: 'high' },
    scoringNotes: 'Boost while shift is today and staff assigned',
  },
  {
    id: 'staff.upcoming_event_preview',
    role: 'staff',
    label: 'Upcoming Event',
    labelTemplate: '{day}: {eventType}, {guestCount} guests',
    category: 'Event Context',
    baseUrgency: 54,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['event_proximity', 'assignment_state'],
    freshnessWindow: '72h',
    pageAffinity: '/staff-schedule',
    pageAffinityBoost: 25,
    href: '/staff-schedule',
    hrefTemplate: '/staff-schedule?event={eventId}',
    dataSources: ['events', 'staff_assignments'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 4,
    cooldownMinutes: 720,
    renderHints: { presentation: 'pill', icon: 'CalendarRange', priority: 'normal' },
    scoringNotes: 'Higher within 72h; demote if todays event exists',
  },
]

// ============================================================================
// Recipes (5 items)
// ============================================================================

const RECIPES: UniversalRailItemDefinition[] = [
  {
    id: 'staff.recipe_allergen_flag',
    role: 'staff',
    label: 'Recipe Allergen',
    labelTemplate: 'Contains: {allergens}',
    category: 'Recipes',
    baseUrgency: 84,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['allergen_severity', 'event_dietary_match', 'recipe_assigned'],
    freshnessWindow: '24h',
    pageAffinity: '/staff-recipes',
    pageAffinityBoost: 40,
    href: '/staff-recipes',
    hrefTemplate: '/staff-recipes?recipe={recipeId}&panel=allergens',
    dataSources: ['recipes', 'recipe_ingredients', 'ingredients', 'event_guests'],
    privacy: 'tenant_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'CircleAlert', priority: 'high' },
    scoringNotes: 'Safety item; boosted when event has matching dietary alert',
  },
  {
    id: 'staff.recipe_technique_reminder',
    role: 'staff',
    label: 'Technique Reminder',
    labelTemplate: 'Technique: {techniqueName}',
    category: 'Recipes',
    baseUrgency: 44,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['staff_experience', 'technique_difficulty', 'recipe_assigned'],
    freshnessWindow: '24h',
    pageAffinity: '/staff-recipes',
    pageAffinityBoost: 25,
    href: '/staff-recipes',
    hrefTemplate: '/staff-recipes?recipe={recipeId}&technique={techniqueId}',
    dataSources: ['recipe_training_assets', 'recipes', 'staff_recipe_acknowledgments'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: 4,
    cooldownMinutes: 1440,
    renderHints: { presentation: 'card', icon: 'Video', priority: 'low' },
    scoringNotes: 'Boost for new staff or high-risk technique',
  },
  {
    id: 'staff.recipe_to_prep',
    role: 'staff',
    label: 'Recipe to Prep',
    labelTemplate: 'Prep: {recipeName}',
    category: 'Recipes',
    baseUrgency: 72,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['prep_due_time', 'recipe_read_state', 'task_linked'],
    freshnessWindow: '24h',
    pageAffinity: '/staff-recipes',
    pageAffinityBoost: 35,
    href: '/staff-recipes',
    hrefTemplate: '/staff-recipes?recipe={recipeId}&task={taskId}',
    dataSources: ['tasks', 'recipes', 'menus', 'components'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: -1,
    cooldownMinutes: 60,
    renderHints: { presentation: 'card', icon: 'BookMarked', priority: 'high' },
    scoringNotes: 'Higher if prep due soon or recipe unread',
  },
  {
    id: 'staff.recipe_update',
    role: 'staff',
    label: 'Recipe Updated',
    labelTemplate: 'Recipe updated: {recipeName}',
    category: 'Recipes',
    baseUrgency: 66,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['recipe_assigned_today', 'change_significance'],
    freshnessWindow: '24h',
    pageAffinity: '/staff-recipes',
    pageAffinityBoost: 30,
    href: '/staff-recipes',
    hrefTemplate: '/staff-recipes?recipe={recipeId}&updated={versionId}',
    dataSources: ['recipe_versions', 'recipes', 'tasks', 'notifications'],
    privacy: 'tenant_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'RefreshCw', priority: 'normal' },
    scoringNotes: 'Boost if recipe is assigned today',
  },
  {
    id: 'staff.recipe_yield_needed',
    role: 'staff',
    label: 'Yield Needed',
    labelTemplate: 'Scale {recipeName} to {servings} servings',
    category: 'Recipes',
    baseUrgency: 68,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['recipe_opened_state', 'event_linked', 'prep_task_linked'],
    freshnessWindow: '24h',
    pageAffinity: '/staff-recipes',
    pageAffinityBoost: 30,
    href: '/staff-recipes',
    hrefTemplate: '/staff-recipes?recipe={recipeId}&scale={servings}',
    dataSources: ['recipes', 'recipe_scaling', 'menus', 'events', 'tasks'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: -1,
    cooldownMinutes: 60,
    renderHints: { presentation: 'pill', icon: 'Scale', priority: 'normal' },
    scoringNotes: 'Boost if staff opened base recipe but not scaled version',
  },
]

// ============================================================================
// Communication (4 items)
// ============================================================================

const COMMUNICATION: UniversalRailItemDefinition[] = [
  {
    id: 'staff.chef_feedback',
    role: 'staff',
    label: 'Chef Feedback',
    labelTemplate: 'Chef feedback: {shortFeedback}',
    category: 'Communication',
    baseUrgency: 45,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['feedback_recency', 'task_linked'],
    freshnessWindow: '72h',
    pageAffinity: '/staff-dashboard',
    pageAffinityBoost: 15,
    href: '/staff-tasks',
    hrefTemplate: '/staff-tasks?task={taskId}',
    dataSources: ['task_comments', 'staff_feedback', 'notifications'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: 3,
    cooldownMinutes: 1440,
    renderHints: { presentation: 'badge', icon: 'MessageCircleHeart', priority: 'low' },
    scoringNotes: 'Positive feedback should not outrank current work',
  },
  {
    id: 'staff.message_from_chef',
    role: 'staff',
    label: 'Chef Message',
    labelTemplate: 'Chef: {messageExcerpt}',
    category: 'Communication',
    baseUrgency: 80,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['unread_state', 'task_linked', 'event_proximity'],
    freshnessWindow: '24h',
    pageAffinity: '/staff-dashboard',
    pageAffinityBoost: 25,
    href: '/staff-dashboard',
    hrefTemplate: '/staff-dashboard?message={messageId}',
    dataSources: ['notifications', 'chat_messages', 'staff_briefings'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: -1,
    cooldownMinutes: 30,
    renderHints: { presentation: 'alert', icon: 'MessageSquare', priority: 'high' },
    scoringNotes: 'Unread chef messages outrank non-safety routine cards',
  },
  {
    id: 'staff.message_from_staff',
    role: 'staff',
    label: 'Staff Message',
    labelTemplate: '{staffName}: {messageExcerpt}',
    category: 'Communication',
    baseUrgency: 52,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['same_station', 'task_blocker', 'unread_state'],
    freshnessWindow: '48h',
    pageAffinity: '/staff-dashboard',
    pageAffinityBoost: 15,
    href: '/staff-dashboard',
    hrefTemplate: '/staff-dashboard?message={messageId}',
    dataSources: ['chat_messages', 'notifications', 'tasks'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: 5,
    cooldownMinutes: 60,
    renderHints: { presentation: 'pill', icon: 'MessagesSquare', priority: 'normal' },
    scoringNotes: 'Higher if from same station or blocks own task',
  },
  {
    id: 'staff.team_announcement',
    role: 'staff',
    label: 'Team Announcement',
    labelTemplate: 'Team: {announcementTitle}',
    category: 'Communication',
    baseUrgency: 50,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['required_acknowledgment', 'schedule_linked'],
    freshnessWindow: '72h',
    pageAffinity: '/staff-dashboard',
    pageAffinityBoost: 15,
    href: '/staff-dashboard',
    hrefTemplate: '/staff-dashboard?announcement={announcementId}',
    dataSources: ['team_announcements', 'notifications'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: 5,
    cooldownMinutes: 720,
    renderHints: { presentation: 'card', icon: 'Megaphone', priority: 'normal' },
    scoringNotes: 'Higher if marked required acknowledgment',
  },
]

// ============================================================================
// Inventory and Supplies (4 items)
// ============================================================================

const INVENTORY_AND_SUPPLIES: UniversalRailItemDefinition[] = [
  {
    id: 'staff.delivery_arriving',
    role: 'staff',
    label: 'Delivery Arriving',
    labelTemplate: '{vendorOrCategory} delivery at {time}',
    category: 'Inventory and Supplies',
    baseUrgency: 58,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['receiving_assigned', 'delivery_eta', 'station_impact'],
    freshnessWindow: '4h',
    pageAffinity: '/staff-dashboard',
    pageAffinityBoost: 15,
    href: '/staff-tasks',
    hrefTemplate: '/staff-tasks?delivery={deliveryId}',
    dataSources: ['purchase_orders', 'vendor_deliveries', 'tasks'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: 4,
    cooldownMinutes: 120,
    renderHints: { presentation: 'pill', icon: 'Truck', priority: 'normal' },
    scoringNotes: 'Higher if staff assigned receiving task',
  },
  {
    id: 'staff.inventory_count_due',
    role: 'staff',
    label: 'Inventory Count Due',
    labelTemplate: '{countName} count due {dueText}',
    category: 'Inventory and Supplies',
    baseUrgency: 62,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['due_time', 'assigned_to_staff'],
    freshnessWindow: '24h',
    pageAffinity: '/staff-tasks',
    pageAffinityBoost: 25,
    href: '/staff-tasks',
    hrefTemplate: '/staff-tasks?task={taskId}&type=inventory-count',
    dataSources: ['inventory_audits', 'inventory_audit_items', 'tasks'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: -1,
    cooldownMinutes: 120,
    renderHints: { presentation: 'pill', icon: 'ClipboardList', priority: 'normal' },
    scoringNotes: 'Higher if due today; lower if not assigned to this staff member',
  },
  {
    id: 'staff.item_substitution',
    role: 'staff',
    label: 'Item Substitution',
    labelTemplate: 'Substitution: {missingItem} -> {replacementItem}',
    category: 'Inventory and Supplies',
    baseUrgency: 76,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['active_station', 'allergen_impact', 'recipe_linked'],
    freshnessWindow: '24h',
    pageAffinity: '/staff-recipes',
    pageAffinityBoost: 35,
    href: '/staff-recipes',
    hrefTemplate: '/staff-recipes?recipe={recipeId}&substitution={substitutionId}',
    dataSources: ['inventory_substitutions', 'recipe_overrides', 'tasks'],
    privacy: 'tenant_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'Replace', priority: 'high' },
    scoringNotes: 'Boost if affects active station or allergen status',
  },
  {
    id: 'staff.low_stock_alert',
    role: 'staff',
    label: 'Low Stock',
    labelTemplate: 'Low stock: {itemName}',
    category: 'Inventory and Supplies',
    baseUrgency: 68,
    urgencyDecayFn: 'none',
    relevanceSignals: ['station_impact', 'active_recipe', 'event_today'],
    freshnessWindow: '24h',
    pageAffinity: '/staff-station',
    pageAffinityBoost: 20,
    href: '/staff-station',
    hrefTemplate: '/staff-station?inventory={ingredientId}',
    dataSources: ['inventory_current_stock', 'inventory_counts', 'tasks'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: 5,
    cooldownMinutes: 180,
    renderHints: { presentation: 'alert', icon: 'PackageMinus', priority: 'normal' },
    scoringNotes: 'Higher if tied to active recipe or event today',
  },
]

// ============================================================================
// Time Tracking (4 items)
// ============================================================================

const TIME_TRACKING: UniversalRailItemDefinition[] = [
  {
    id: 'staff.clock_status',
    role: 'staff',
    label: 'Clock Status',
    labelTemplate: '{clockState}: {durationOrNextShift}',
    category: 'Time Tracking',
    baseUrgency: 65,
    urgencyDecayFn: 'none',
    relevanceSignals: ['clock_state', 'shift_today'],
    freshnessWindow: '24h',
    pageAffinity: '/staff-time',
    pageAffinityBoost: 35,
    href: '/staff-time',
    hrefTemplate: '/staff-time',
    dataSources: ['staff_clock_entries', 'staff_assignments'],
    privacy: 'tenant_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'pill', icon: 'Timer', priority: 'normal' },
    scoringNotes: 'Always visible on time page; lower if no shift today',
  },
  {
    id: 'staff.hours_week_summary',
    role: 'staff',
    label: 'Hours This Week',
    labelTemplate: '{hours} hours logged this week',
    category: 'Time Tracking',
    baseUrgency: 48,
    urgencyDecayFn: 'none',
    relevanceSignals: ['overtime_proximity', 'missing_entries'],
    freshnessWindow: '7d',
    pageAffinity: '/staff-time',
    pageAffinityBoost: 25,
    href: '/staff-time',
    hrefTemplate: '/staff-time?week={weekStart}',
    dataSources: ['staff_clock_entries', 'staff_assignments'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 5,
    cooldownMinutes: 720,
    renderHints: { presentation: 'progress', icon: 'Clock3', priority: 'normal' },
    scoringNotes: 'Boost near overtime threshold; never show labor cost',
  },
  {
    id: 'staff.pay_period_ending',
    role: 'staff',
    label: 'Pay Period Ending',
    labelTemplate: 'Pay period ends {date}',
    category: 'Time Tracking',
    baseUrgency: 50,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['missing_clock_outs', 'correction_pending', 'cutoff_proximity'],
    freshnessWindow: '7d',
    pageAffinity: '/staff-time',
    pageAffinityBoost: 25,
    href: '/staff-time',
    hrefTemplate: '/staff-time?period={periodId}',
    dataSources: ['pay_periods', 'staff_clock_entries'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 4,
    cooldownMinutes: 720,
    renderHints: { presentation: 'pill', icon: 'CalendarDays', priority: 'normal' },
    scoringNotes: 'Higher if missing clock-out or correction pending',
  },
  {
    id: 'staff.timesheet_approval_pending',
    role: 'staff',
    label: 'Timesheet Pending',
    labelTemplate: 'Timesheet pending approval',
    category: 'Time Tracking',
    baseUrgency: 40,
    urgencyDecayFn: 'none',
    relevanceSignals: ['approval_status', 'correction_needed'],
    freshnessWindow: '14d',
    pageAffinity: '/staff-time',
    pageAffinityBoost: 20,
    href: '/staff-time',
    hrefTemplate: '/staff-time?period={periodId}&status=pending',
    dataSources: ['timesheets', 'staff_clock_entries'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 4,
    cooldownMinutes: 1440,
    renderHints: { presentation: 'badge', icon: 'FileClock', priority: 'low' },
    scoringNotes: 'Lower than active clock reminders; boost if rejected/correction needed',
  },
]

// ============================================================================
// Onboarding (5 items)
// ============================================================================

const ONBOARDING: UniversalRailItemDefinition[] = [
  {
    id: 'staff.key_recipes_review',
    role: 'staff',
    label: 'Key Recipes',
    labelTemplate: 'Review {count} key recipes',
    category: 'Onboarding',
    baseUrgency: 42,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['new_staff', 'recipe_read_state', 'station_relevance'],
    freshnessWindow: '14d',
    pageAffinity: '/staff-recipes',
    pageAffinityBoost: 25,
    href: '/staff-recipes',
    hrefTemplate: '/staff-recipes?filter=onboarding',
    dataSources: ['staff_onboarding', 'recipes', 'staff_recipe_acknowledgments'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 8,
    cooldownMinutes: 1440,
    renderHints: { presentation: 'progress', icon: 'BookOpen', priority: 'low' },
    scoringNotes: 'Boost for new staff in first 14 days',
  },
  {
    id: 'staff.onboarding_station_familiarization',
    role: 'staff',
    label: 'Station Familiarization',
    labelTemplate: 'Learn {stationName} station',
    category: 'Onboarding',
    baseUrgency: 46,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['station_assigned_soon', 'checklist_progress'],
    freshnessWindow: '14d',
    pageAffinity: '/staff-station',
    pageAffinityBoost: 30,
    href: '/staff-station',
    hrefTemplate: '/staff-station?onboarding=station&station={stationId}',
    dataSources: ['staff_onboarding', 'stations', 'station_checklists'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 8,
    cooldownMinutes: 1440,
    renderHints: { presentation: 'progress', icon: 'MapPinned', priority: 'low' },
    scoringNotes: 'Boost if station assigned within next 7d',
  },
  {
    id: 'staff.safety_protocol_ack',
    role: 'staff',
    label: 'Safety Protocol',
    labelTemplate: 'Acknowledge {protocolName}',
    category: 'Onboarding',
    baseUrgency: 82,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['shift_today', 'station_requires', 'compliance_blocking'],
    freshnessWindow: '7d',
    pageAffinity: '/staff-dashboard',
    pageAffinityBoost: 30,
    href: '/staff-dashboard',
    hrefTemplate: '/staff-dashboard?onboarding=safety&protocol={protocolId}',
    dataSources: ['staff_onboarding', 'safety_protocols', 'staff_acknowledgments'],
    privacy: 'tenant_scoped',
    dismissable: false,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: -1,
    cooldownMinutes: 0,
    renderHints: { presentation: 'alert', icon: 'ShieldCheck', priority: 'high' },
    scoringNotes: 'High if required before todays shift',
  },
  {
    id: 'staff.team_introduction',
    role: 'staff',
    label: 'Team Introduction',
    labelTemplate: 'Meet the team',
    category: 'Onboarding',
    baseUrgency: 30,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['onboarding_phase', 'rail_capacity'],
    freshnessWindow: '14d',
    pageAffinity: '/staff-dashboard',
    pageAffinityBoost: 10,
    href: '/staff-dashboard',
    hrefTemplate: '/staff-dashboard?onboarding=team',
    dataSources: ['staff_members', 'staff_onboarding', 'staff_assignments'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: 5,
    cooldownMinutes: 2880,
    renderHints: { presentation: 'story', icon: 'Users', priority: 'low' },
    scoringNotes: 'Low; only when rail has spare capacity',
  },
  {
    id: 'staff.welcome_setup_steps',
    role: 'staff',
    label: 'Welcome Setup',
    labelTemplate: 'Welcome, {staffName}',
    category: 'Onboarding',
    baseUrgency: 48,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['first_login', 'setup_progress', 'days_since_join'],
    freshnessWindow: '30d',
    pageAffinity: '/staff-dashboard',
    pageAffinityBoost: 25,
    href: '/staff-dashboard',
    hrefTemplate: '/staff-dashboard?onboarding=setup',
    dataSources: ['staff_onboarding', 'staff_members'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 8,
    cooldownMinutes: 1440,
    renderHints: { presentation: 'progress', icon: 'PartyPopper', priority: 'normal' },
    scoringNotes: 'Boost for first 7 days; demote during active shift emergencies',
  },
]

// ============================================================================
// Personal (3 items)
// ============================================================================

const PERSONAL: UniversalRailItemDefinition[] = [
  {
    id: 'staff.certification_expiring',
    role: 'staff',
    label: 'Certification Expiring',
    labelTemplate: '{certName} expires in {days} days',
    category: 'Personal',
    baseUrgency: 70,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['expiry_proximity', 'compliance_blocking'],
    freshnessWindow: '30d',
    pageAffinity: '/staff-dashboard',
    pageAffinityBoost: 15,
    href: '/staff-dashboard',
    hrefTemplate: '/staff-dashboard?panel=certifications&cert={certId}',
    dataSources: ['staff_certifications'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'navigate',
    maxImpressions: 6,
    cooldownMinutes: 1440,
    renderHints: { presentation: 'alert', icon: 'BadgeCheck', priority: 'normal' },
    scoringNotes: 'Boost under 14d; critical under 7d',
  },
  {
    id: 'staff.performance_milestone',
    role: 'staff',
    label: 'Performance Milestone',
    labelTemplate: '{milestoneText}',
    category: 'Personal',
    baseUrgency: 32,
    urgencyDecayFn: 'linear',
    relevanceSignals: ['milestone_type', 'rail_capacity'],
    freshnessWindow: '7d',
    pageAffinity: '/staff-dashboard',
    pageAffinityBoost: 10,
    href: '/staff-dashboard',
    hrefTemplate: '/staff-dashboard?milestone={milestoneId}',
    dataSources: ['tasks', 'staff_activity'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: false,
    hoverAction: 'preview',
    clickAction: 'expand_inline',
    maxImpressions: 2,
    cooldownMinutes: 10080,
    renderHints: { presentation: 'badge', icon: 'Trophy', priority: 'low' },
    scoringNotes: 'Never outrank operational work',
  },
  {
    id: 'staff.training_opportunity',
    role: 'staff',
    label: 'Training Opportunity',
    labelTemplate: 'Training: {trainingTitle}',
    category: 'Personal',
    baseUrgency: 36,
    urgencyDecayFn: 'deadline',
    relevanceSignals: ['training_required', 'station_relevance', 'rsvp_state'],
    freshnessWindow: '14d',
    pageAffinity: '/staff-dashboard',
    pageAffinityBoost: 15,
    href: '/staff-dashboard',
    hrefTemplate: '/staff-dashboard?training={trainingId}',
    dataSources: ['training_sessions', 'staff_training_assignments'],
    privacy: 'tenant_scoped',
    dismissable: true,
    expandable: true,
    hoverAction: 'preview',
    clickAction: 'quick_action',
    maxImpressions: 4,
    cooldownMinutes: 2880,
    renderHints: { presentation: 'card', icon: 'GraduationCap', priority: 'low' },
    scoringNotes: 'Boost if required for upcoming station',
  },
]

// ============================================================================
// Export: 57 items total
// ============================================================================

export const STAFF_RAIL_REGISTRY: readonly UniversalRailItemDefinition[] = [
  ...SHIFT_AND_SCHEDULE,
  ...TASKS_AND_DELEGATION,
  ...STATION_ASSIGNMENTS,
  ...EVENT_CONTEXT,
  ...RECIPES,
  ...COMMUNICATION,
  ...INVENTORY_AND_SUPPLIES,
  ...TIME_TRACKING,
  ...ONBOARDING,
  ...PERSONAL,
] as const
