import type { ExitLinkDefinition } from '@/types/exit-links'

/**
 * Complete registry of all 91 exit-link definitions.
 * Each entry describes where a chef leaves ChefFlow to accomplish
 * something the app cannot (yet) do internally.
 *
 * Entries with urlTemplate: null and inApp: true are handled
 * inside the app; the registry tracks them for completeness.
 */
export const EXIT_LINK_REGISTRY: ExitLinkDefinition[] = [
  // ──────────────────────────────────────────────
  // 1-10  DATA GAPS
  // ──────────────────────────────────────────────
  {
    id: 1,
    category: 'data-gaps',
    label: 'Search {ingredient} on Instacart',
    urlTemplate: 'https://www.instacart.com/store/search/{ingredient}',
    contextKeys: ['ingredient'],
    icon: 'ShoppingCart',
    newTab: true,
    subLinks: [
      {
        label: 'Search on Amazon Fresh',
        urlTemplate: 'https://www.amazon.com/s?k={ingredient}&i=amazonfresh',
        contextKeys: ['ingredient'],
        icon: 'ShoppingCart',
        newTab: true,
      },
      {
        label: 'Search on Google Shopping',
        urlTemplate: 'https://www.google.com/search?tbm=shop&q={ingredient}',
        contextKeys: ['ingredient'],
        icon: 'Search',
        newTab: true,
      },
    ],
  },
  {
    id: 2,
    category: 'data-gaps',
    label: 'Check current price for {ingredient}',
    urlTemplate: 'https://www.instacart.com/store/search/{ingredient}',
    contextKeys: ['ingredient'],
    icon: 'DollarSign',
    newTab: true,
  },
  {
    id: 3,
    category: 'data-gaps',
    label: 'Find local price for {ingredient}',
    urlTemplate: 'https://www.instacart.com/store/search/{ingredient}?zipCode={zip}',
    contextKeys: ['ingredient', 'zip'],
    icon: 'MapPin',
    newTab: true,
  },
  {
    id: 4,
    category: 'data-gaps',
    label: 'Check wholesale price',
    urlTemplate: 'https://www.usfoods.com/search.html?q={ingredient}',
    contextKeys: ['ingredient'],
    icon: 'Package',
    newTab: true,
    subLinks: [
      {
        label: 'Check on Sysco',
        urlTemplate: 'https://www.sysco.com/search?q={ingredient}',
        contextKeys: ['ingredient'],
        icon: 'Package',
        newTab: true,
      },
      {
        label: 'Check on Restaurant Depot',
        urlTemplate: 'https://www.restaurantdepot.com/search?q={ingredient}',
        contextKeys: ['ingredient'],
        icon: 'Package',
        newTab: true,
      },
    ],
  },
  {
    id: 5,
    category: 'data-gaps',
    label: 'Check seasonal availability',
    urlTemplate: 'https://snaped.fns.usda.gov/seasonal-produce-guide',
    contextKeys: [],
    icon: 'Calendar',
    newTab: true,
    subLinks: [
      {
        label: 'Local farms near you',
        urlTemplate: 'https://www.localharvest.org/search.jsp?jmp&lat={lat}&lon={lon}',
        contextKeys: ['lat', 'lon'],
        icon: 'MapPin',
        newTab: true,
      },
    ],
  },
  {
    id: 6,
    category: 'data-gaps',
    label: 'Search specialty vendors for {ingredient}',
    urlTemplate: 'https://www.google.com/search?q={ingredient}+buy+online+specialty',
    contextKeys: ['ingredient'],
    icon: 'Search',
    newTab: true,
  },
  {
    id: 7,
    category: 'data-gaps',
    label: 'USDA Nutrition Lookup for {ingredient}',
    urlTemplate: 'https://fdc.nal.usda.gov/search?query={ingredient}',
    contextKeys: ['ingredient'],
    icon: 'Apple',
    newTab: true,
  },
  {
    id: 8,
    category: 'data-gaps',
    label: 'FDA Safe Cooking Temperatures',
    urlTemplate:
      'https://www.fda.gov/food/buy-store-serve-safe-food/safe-minimum-cooking-temperatures-chart',
    contextKeys: [],
    icon: 'Thermometer',
    newTab: true,
  },
  {
    id: 9,
    category: 'data-gaps',
    label: 'Find substitution for {ingredient}',
    urlTemplate: 'https://www.google.com/search?q={ingredient}+substitute+for+{allergy}',
    contextKeys: ['ingredient', 'allergy'],
    icon: 'RefreshCw',
    newTab: true,
  },
  {
    id: 10,
    category: 'data-gaps',
    label: 'Research market rates',
    urlTemplate: 'https://www.thumbtack.com/k/personal-chefs/near-me/',
    contextKeys: [],
    icon: 'TrendingUp',
    newTab: true,
    subLinks: [
      {
        label: 'Check on Bark',
        urlTemplate: 'https://www.bark.com/en/us/personal-chef/',
        contextKeys: [],
        icon: 'TrendingUp',
        newTab: true,
      },
    ],
  },

  // ──────────────────────────────────────────────
  // 11-29  MISSING FEATURES
  // ──────────────────────────────────────────────
  {
    id: 11,
    category: 'missing-features',
    label: 'In-app: contract generation',
    urlTemplate: null,
    contextKeys: [],
    icon: 'FileText',
    newTab: false,
    inApp: true,
  },
  {
    id: 12,
    category: 'missing-features',
    label: 'In-app: invoice generation',
    urlTemplate: null,
    contextKeys: [],
    icon: 'FileText',
    newTab: false,
    inApp: true,
  },
  {
    id: 13,
    category: 'missing-features',
    label: 'In-app: client portal sharing',
    urlTemplate: null,
    contextKeys: [],
    icon: 'Share2',
    newTab: false,
    inApp: true,
  },
  {
    id: 14,
    category: 'missing-features',
    label: 'Add to Google Calendar',
    urlTemplate:
      'https://calendar.google.com/calendar/render?action=TEMPLATE&text={eventName}&dates={startDate}/{endDate}&location={venueAddress}',
    contextKeys: ['eventName', 'startDate', 'endDate', 'venueAddress'],
    icon: 'Calendar',
    newTab: true,
  },
  {
    id: 15,
    category: 'missing-features',
    label: 'Calculate driving distance',
    urlTemplate: 'https://www.google.com/maps/dir/{homeAddress}/{venueAddress}',
    contextKeys: ['homeAddress', 'venueAddress'],
    icon: 'Navigation',
    newTab: true,
  },
  {
    id: 16,
    category: 'missing-features',
    label: 'In-app: prep timeline',
    urlTemplate: null,
    contextKeys: [],
    icon: 'Clock',
    newTab: false,
    inApp: true,
  },
  {
    id: 17,
    category: 'missing-features',
    label: 'In-app: equipment checklist',
    urlTemplate: null,
    contextKeys: [],
    icon: 'CheckSquare',
    newTab: false,
    inApp: true,
  },
  {
    id: 18,
    category: 'missing-features',
    label: 'In-app: dietary restriction tracking',
    urlTemplate: null,
    contextKeys: [],
    icon: 'AlertTriangle',
    newTab: false,
    inApp: true,
  },
  {
    id: 19,
    category: 'missing-features',
    label: 'In-app: expense tracking',
    urlTemplate: null,
    contextKeys: [],
    icon: 'Receipt',
    newTab: false,
    inApp: true,
  },
  {
    id: 20,
    category: 'missing-features',
    label: 'In-app: mileage tracking',
    urlTemplate: null,
    contextKeys: [],
    icon: 'Car',
    newTab: false,
    inApp: true,
  },
  {
    id: 21,
    category: 'missing-features',
    label: 'In-app: menu builder',
    urlTemplate: null,
    contextKeys: [],
    icon: 'BookOpen',
    newTab: false,
    inApp: true,
  },
  {
    id: 22,
    category: 'missing-features',
    label: 'In-app: client feedback collection',
    urlTemplate: null,
    contextKeys: [],
    icon: 'MessageSquare',
    newTab: false,
    inApp: true,
  },
  {
    id: 23,
    category: 'missing-features',
    label: 'Pay {staffName} via Venmo',
    urlTemplate:
      'https://venmo.com/?txn=pay&recipients={staffPhone}&amount={amount}&note=Event+{eventName}',
    contextKeys: ['staffName', 'staffPhone', 'amount', 'eventName'],
    icon: 'DollarSign',
    newTab: true,
  },
  {
    id: 24,
    category: 'missing-features',
    label: 'In-app: staff scheduling',
    urlTemplate: null,
    contextKeys: [],
    icon: 'Users',
    newTab: false,
    inApp: true,
  },
  {
    id: 25,
    category: 'missing-features',
    label: 'View venue on Maps',
    urlTemplate: 'https://www.google.com/maps/search/?api=1&query={venueAddress}',
    contextKeys: ['venueAddress'],
    icon: 'Map',
    newTab: true,
  },
  {
    id: 26,
    category: 'missing-features',
    label: 'Full weather forecast',
    urlTemplate: 'https://forecast.weather.gov/MapClick.php?lat={lat}&lon={lon}',
    contextKeys: ['lat', 'lon'],
    icon: 'Cloud',
    newTab: true,
    subLinks: [
      {
        label: 'Weather.com forecast',
        urlTemplate: 'https://weather.com/weather/tenday/l/{venueZip}',
        contextKeys: ['venueZip'],
        icon: 'Cloud',
        newTab: true,
      },
    ],
  },
  {
    id: 27,
    category: 'missing-features',
    label: 'Get directions',
    urlTemplate: 'https://www.google.com/maps/dir/{stop1}/{stop2}/{stop3}',
    contextKeys: ['stop1', 'stop2', 'stop3'],
    icon: 'Navigation',
    newTab: true,
  },
  {
    id: 28,
    category: 'missing-features',
    label: 'In-app: route optimization',
    urlTemplate: null,
    contextKeys: [],
    icon: 'Navigation',
    newTab: false,
    inApp: true,
  },
  {
    id: 29,
    category: 'missing-features',
    label: 'View in Stripe',
    urlTemplate: 'https://dashboard.stripe.com/payments/{paymentId}',
    contextKeys: ['paymentId'],
    icon: 'CreditCard',
    newTab: true,
  },

  // ──────────────────────────────────────────────
  // 30-38  CHANNEL LOCK-IN
  // ──────────────────────────────────────────────
  {
    id: 30,
    category: 'channel-lock-in',
    label: 'Text {clientName}',
    urlTemplate: 'sms:{phoneNumber}?body={message}',
    contextKeys: ['clientName', 'phoneNumber', 'message'],
    icon: 'MessageSquare',
    newTab: true,
  },
  {
    id: 31,
    category: 'channel-lock-in',
    label: 'WhatsApp {clientName}',
    urlTemplate: 'https://wa.me/{phoneNumber}?text={message}',
    contextKeys: ['clientName', 'phoneNumber', 'message'],
    icon: 'MessageCircle',
    newTab: true,
  },
  {
    id: 32,
    category: 'channel-lock-in',
    label: 'Call {clientName}',
    urlTemplate: 'tel:{phoneNumber}',
    contextKeys: ['clientName', 'phoneNumber'],
    icon: 'Phone',
    newTab: true,
  },
  {
    id: 33,
    category: 'channel-lock-in',
    label: 'Reply on Thumbtack',
    urlTemplate: 'https://www.thumbtack.com/messages',
    contextKeys: [],
    icon: 'MessageSquare',
    newTab: true,
    subLinks: [
      {
        label: 'Reply on Bark',
        urlTemplate: 'https://www.bark.com/en/us/dashboard/',
        contextKeys: [],
        icon: 'MessageSquare',
        newTab: true,
      },
    ],
  },
  {
    id: 34,
    category: 'channel-lock-in',
    label: 'Open Gmail for {clientName}',
    urlTemplate: 'https://mail.google.com/mail/u/0/#search/from:{clientEmail}',
    contextKeys: ['clientName', 'clientEmail'],
    icon: 'Mail',
    newTab: true,
  },
  {
    id: 35,
    category: 'channel-lock-in',
    label: 'Email {vendorName}',
    urlTemplate: 'mailto:{vendorEmail}?subject=Order+for+{eventDate}&body={itemList}',
    contextKeys: ['vendorName', 'vendorEmail', 'eventDate', 'itemList'],
    icon: 'Mail',
    newTab: true,
  },
  {
    id: 36,
    category: 'channel-lock-in',
    label: 'Email all vendors',
    urlTemplate: 'mailto:{vendorEmails}?subject=Event+Brief+-+{eventDate}&body={eventBrief}',
    contextKeys: ['vendorEmails', 'eventDate', 'eventBrief'],
    icon: 'Mail',
    newTab: true,
  },
  {
    id: 37,
    category: 'channel-lock-in',
    label: 'Contact {contactName}',
    urlTemplate: 'tel:{contactPhone}',
    contextKeys: ['contactName', 'contactPhone'],
    icon: 'Phone',
    newTab: true,
  },
  {
    id: 38,
    category: 'channel-lock-in',
    label: 'Text crew',
    urlTemplate: 'sms:{crewPhones}?body={dayOfBrief}',
    contextKeys: ['crewPhones', 'dayOfBrief'],
    icon: 'MessageSquare',
    newTab: true,
  },

  // ──────────────────────────────────────────────
  // 39-47  TRANSACTION ELSEWHERE
  // ──────────────────────────────────────────────
  {
    id: 39,
    category: 'transaction',
    label: 'Order from {vendorName}',
    urlTemplate: '{vendorPortalUrl}',
    contextKeys: ['vendorName', 'vendorPortalUrl'],
    icon: 'ShoppingBag',
    newTab: true,
  },
  {
    id: 40,
    category: 'transaction',
    label: 'Shop on Instacart',
    urlTemplate: 'https://www.instacart.com/store/search/{firstItem}',
    contextKeys: ['firstItem'],
    icon: 'ShoppingCart',
    newTab: true,
    subLinks: [
      {
        label: 'Shop on Amazon Fresh',
        urlTemplate: 'https://www.amazon.com/s?k={firstItem}&i=amazonfresh',
        contextKeys: ['firstItem'],
        icon: 'ShoppingCart',
        newTab: true,
      },
    ],
  },
  {
    id: 41,
    category: 'transaction',
    label: 'Buy on Amazon',
    urlTemplate: 'https://www.amazon.com/s?k={equipmentItem}',
    contextKeys: ['equipmentItem'],
    icon: 'ShoppingBag',
    newTab: true,
    subLinks: [
      {
        label: 'Buy on WebstaurantStore',
        urlTemplate: 'https://www.webstaurantstore.com/search/{equipmentItem}.html',
        contextKeys: ['equipmentItem'],
        icon: 'ShoppingBag',
        newTab: true,
      },
    ],
  },
  {
    id: 42,
    category: 'transaction',
    label: 'Request rental quote',
    urlTemplate: 'mailto:{rentalEmail}?subject=Equipment+Rental+{eventDate}&body={equipmentList}',
    contextKeys: ['rentalEmail', 'eventDate', 'equipmentList'],
    icon: 'Mail',
    newTab: true,
  },
  {
    id: 43,
    category: 'transaction',
    label: 'Search flights',
    urlTemplate: 'https://www.google.com/travel/flights?q=Flights+to+{venueCity}+on+{eventDate}',
    contextKeys: ['venueCity', 'eventDate'],
    icon: 'Plane',
    newTab: true,
    subLinks: [
      {
        label: 'Search hotels',
        urlTemplate: 'https://www.google.com/travel/hotels/{venueCity}?dates={checkIn},{checkOut}',
        contextKeys: ['venueCity', 'checkIn', 'checkOut'],
        icon: 'Building',
        newTab: true,
      },
    ],
  },
  {
    id: 44,
    category: 'transaction',
    label: 'Send Venmo request',
    urlTemplate:
      'https://venmo.com/?txn=charge&recipients={clientPhone}&amount={amount}&note={eventName}',
    contextKeys: ['clientPhone', 'amount', 'eventName'],
    icon: 'DollarSign',
    newTab: true,
  },
  {
    id: 45,
    category: 'transaction',
    label: 'Book commissary time',
    urlTemplate: '{commissaryUrl}',
    contextKeys: ['commissaryUrl'],
    icon: 'Building',
    newTab: true,
  },
  {
    id: 46,
    category: 'transaction',
    label: 'Hire photographer',
    urlTemplate: 'mailto:{photographerEmail}?subject=Photography+{eventDate}&body={eventBrief}',
    contextKeys: ['photographerEmail', 'eventDate', 'eventBrief'],
    icon: 'Camera',
    newTab: true,
  },
  {
    id: 47,
    category: 'transaction',
    label: 'Send flowers',
    urlTemplate: 'https://www.google.com/search?q=flower+delivery+near+{clientZip}',
    contextKeys: ['clientZip'],
    icon: 'Gift',
    newTab: true,
    subLinks: [
      {
        label: 'Send gift on Amazon',
        urlTemplate: 'https://www.amazon.com/s?k={giftIdea}',
        contextKeys: ['giftIdea'],
        icon: 'Gift',
        newTab: true,
      },
    ],
  },

  // ──────────────────────────────────────────────
  // 48-60  EXTERNAL PLATFORM
  // ──────────────────────────────────────────────
  {
    id: 48,
    category: 'external-platform',
    label: 'View on Instagram',
    urlTemplate: 'https://instagram.com/{handle}',
    contextKeys: ['handle'],
    icon: 'Instagram',
    newTab: true,
    subLinks: [
      {
        label: 'View on Facebook',
        urlTemplate: 'https://facebook.com/{handle}',
        contextKeys: ['handle'],
        icon: 'Facebook',
        newTab: true,
      },
      {
        label: 'View on LinkedIn',
        urlTemplate: 'https://linkedin.com/in/{handle}',
        contextKeys: ['handle'],
        icon: 'Linkedin',
        newTab: true,
      },
    ],
  },
  {
    id: 49,
    category: 'external-platform',
    label: 'View company website',
    urlTemplate: '{companyUrl}',
    contextKeys: ['companyUrl'],
    icon: 'Globe',
    newTab: true,
    subLinks: [
      {
        label: 'Search company',
        urlTemplate: 'https://www.google.com/search?q={companyName}',
        contextKeys: ['companyName'],
        icon: 'Search',
        newTab: true,
      },
    ],
  },
  {
    id: 50,
    category: 'external-platform',
    label: 'Email venue about kitchen',
    urlTemplate:
      'mailto:{venueEmail}?subject=Kitchen+Details+for+{eventDate}&body={kitchenQuestionnaire}',
    contextKeys: ['venueEmail', 'eventDate', 'kitchenQuestionnaire'],
    icon: 'Mail',
    newTab: true,
  },
  {
    id: 51,
    category: 'external-platform',
    label: 'Browse {vendorName} catalog',
    urlTemplate: '{vendorWebsite}',
    contextKeys: ['vendorName', 'vendorWebsite'],
    icon: 'ShoppingBag',
    newTab: true,
  },
  {
    id: 52,
    category: 'external-platform',
    label: 'Track shipment',
    urlTemplate: 'https://www.google.com/search?q={trackingNumber}',
    contextKeys: ['trackingNumber'],
    icon: 'Truck',
    newTab: true,
  },
  {
    id: 53,
    category: 'external-platform',
    label: 'View competitor',
    urlTemplate: '{competitorUrl}',
    contextKeys: ['competitorUrl'],
    icon: 'Eye',
    newTab: true,
  },
  {
    id: 54,
    category: 'external-platform',
    label: 'Read on Eater',
    urlTemplate: 'https://www.eater.com',
    contextKeys: [],
    icon: 'Newspaper',
    newTab: true,
    subLinks: [
      {
        label: 'Read Bon Appetit',
        urlTemplate: 'https://www.bonappetit.com',
        contextKeys: [],
        icon: 'Newspaper',
        newTab: true,
      },
      {
        label: 'Read Food & Wine',
        urlTemplate: 'https://www.foodandwine.com',
        contextKeys: [],
        icon: 'Newspaper',
        newTab: true,
      },
    ],
  },
  {
    id: 55,
    category: 'external-platform',
    label: 'Navigate to venue',
    urlTemplate:
      'https://www.google.com/maps/dir/?api=1&origin={homeAddress}&destination={venueAddress}&travelmode=driving',
    contextKeys: ['homeAddress', 'venueAddress'],
    icon: 'Navigation',
    newTab: true,
    subLinks: [
      {
        label: 'Navigate (Waze)',
        urlTemplate: 'https://waze.com/ul?ll={venueLat},{venueLon}&navigate=yes',
        contextKeys: ['venueLat', 'venueLon'],
        icon: 'Navigation',
        newTab: true,
      },
    ],
  },
  {
    id: 56,
    category: 'external-platform',
    label: 'Full weather forecast',
    urlTemplate: 'https://weather.com/weather/tenday/l/{venueZip}',
    contextKeys: ['venueZip'],
    icon: 'Cloud',
    newTab: true,
  },
  {
    id: 57,
    category: 'external-platform',
    label: 'Grocery stores near venue',
    urlTemplate: 'https://www.google.com/maps/search/grocery+store/@{venueLat},{venueLon},14z',
    contextKeys: ['venueLat', 'venueLon'],
    icon: 'MapPin',
    newTab: true,
    subLinks: [
      {
        label: 'Specialty stores near venue',
        urlTemplate:
          'https://www.google.com/maps/search/specialty+food+store/@{venueLat},{venueLon},14z',
        contextKeys: ['venueLat', 'venueLon'],
        icon: 'MapPin',
        newTab: true,
      },
    ],
  },
  {
    id: 58,
    category: 'external-platform',
    label: 'Farmers markets nearby',
    urlTemplate: 'https://www.localharvest.org/search.jsp?jmp&lat={venueLat}&lon={venueLon}',
    contextKeys: ['venueLat', 'venueLon'],
    icon: 'Leaf',
    newTab: true,
  },
  {
    id: 59,
    category: 'external-platform',
    label: 'Search wine pairings for {dishName}',
    urlTemplate: 'https://www.vivino.com/search/wines?q={dishName}+pairing',
    contextKeys: ['dishName'],
    icon: 'Wine',
    newTab: true,
    subLinks: [
      {
        label: 'Google wine pairing',
        urlTemplate: 'https://www.google.com/search?q=wine+pairing+{dishName}',
        contextKeys: ['dishName'],
        icon: 'Search',
        newTab: true,
      },
    ],
  },
  {
    id: 60,
    category: 'external-platform',
    label: 'Street View of venue',
    urlTemplate:
      'https://www.google.com/maps/@?api=1&map_action=pano&viewpoint={venueLat},{venueLon}',
    contextKeys: ['venueLat', 'venueLon'],
    icon: 'Eye',
    newTab: true,
  },

  // ──────────────────────────────────────────────
  // 61-67  GOVERNMENT
  // ──────────────────────────────────────────────
  {
    id: 61,
    category: 'government',
    label: "Renew food handler's license",
    urlTemplate: 'https://www.google.com/search?q={state}+food+handler+license+renewal',
    contextKeys: ['state'],
    icon: 'FileText',
    newTab: true,
  },
  {
    id: 62,
    category: 'government',
    label: 'View cottage food laws',
    urlTemplate: 'https://foodpreneurs.com/cottage-food-laws/{state}/',
    contextKeys: ['state'],
    icon: 'Scale',
    newTab: true,
  },
  {
    id: 63,
    category: 'government',
    label: 'Apply for business license',
    urlTemplate: 'https://www.google.com/search?q={city}+{state}+business+license+food+service',
    contextKeys: ['city', 'state'],
    icon: 'FileText',
    newTab: true,
  },
  {
    id: 64,
    category: 'government',
    label: 'Get insurance quote',
    urlTemplate: 'https://www.google.com/search?q=food+service+liability+insurance+{state}',
    contextKeys: ['state'],
    icon: 'Shield',
    newTab: true,
  },
  {
    id: 65,
    category: 'government',
    label: 'Schedule health inspection',
    urlTemplate:
      'https://www.google.com/search?q={county}+{state}+health+department+food+inspection',
    contextKeys: ['county', 'state'],
    icon: 'ClipboardCheck',
    newTab: true,
  },
  {
    id: 66,
    category: 'government',
    label: 'Manage insurance policy',
    urlTemplate: '{insurancePortalUrl}',
    contextKeys: ['insurancePortalUrl'],
    icon: 'Shield',
    newTab: true,
  },
  {
    id: 67,
    category: 'government',
    label: 'Contact lawyer',
    urlTemplate: 'tel:{lawyerPhone}',
    contextKeys: ['lawyerPhone'],
    icon: 'Phone',
    newTab: true,
    subLinks: [
      {
        label: 'Email lawyer',
        urlTemplate: 'mailto:{lawyerEmail}',
        contextKeys: ['lawyerEmail'],
        icon: 'Mail',
        newTab: true,
      },
    ],
  },

  // ──────────────────────────────────────────────
  // 68-71  TAX / FINANCIAL
  // ──────────────────────────────────────────────
  {
    id: 68,
    category: 'tax-financial',
    label: 'Open bank portal',
    urlTemplate: '{bankUrl}',
    contextKeys: ['bankUrl'],
    icon: 'Building',
    newTab: true,
  },
  {
    id: 69,
    category: 'tax-financial',
    label: 'Email tax package to accountant',
    urlTemplate: 'mailto:{accountantEmail}?subject=Tax+Documents+{year}',
    contextKeys: ['accountantEmail', 'year'],
    icon: 'Mail',
    newTab: true,
  },
  {
    id: 70,
    category: 'tax-financial',
    label: 'Email accountant',
    urlTemplate: 'mailto:{accountantEmail}?subject=Monthly+Update+-+{month}+{year}',
    contextKeys: ['accountantEmail', 'month', 'year'],
    icon: 'Mail',
    newTab: true,
  },
  {
    id: 71,
    category: 'tax-financial',
    label: 'In-app: financial reports',
    urlTemplate: null,
    contextKeys: [],
    icon: 'BarChart',
    newTab: false,
    inApp: true,
  },

  // ──────────────────────────────────────────────
  // 72-76  CREATIVE
  // ──────────────────────────────────────────────
  {
    id: 72,
    category: 'creative',
    label: 'Watch {technique} on YouTube',
    urlTemplate: 'https://www.youtube.com/results?search_query={technique}+cooking+technique',
    contextKeys: ['technique'],
    icon: 'Play',
    newTab: true,
    subLinks: [
      {
        label: 'Read on Serious Eats',
        urlTemplate: 'https://www.seriouseats.com/search?q={technique}',
        contextKeys: ['technique'],
        icon: 'BookOpen',
        newTab: true,
      },
    ],
  },
  {
    id: 73,
    category: 'creative',
    label: 'Search inspiration on Pinterest',
    urlTemplate: 'https://www.pinterest.com/search/pins/?q={cuisine}+{eventType}+dinner',
    contextKeys: ['cuisine', 'eventType'],
    icon: 'Image',
    newTab: true,
  },
  {
    id: 74,
    category: 'creative',
    label: 'Research {cuisine} cuisine',
    urlTemplate: 'https://www.youtube.com/results?search_query={cuisine}+cooking+basics',
    contextKeys: ['cuisine'],
    icon: 'Play',
    newTab: true,
    subLinks: [
      {
        label: 'Read on Serious Eats',
        urlTemplate: 'https://www.seriouseats.com/search?q={cuisine}',
        contextKeys: ['cuisine'],
        icon: 'BookOpen',
        newTab: true,
      },
    ],
  },
  {
    id: 75,
    category: 'creative',
    label: 'Layout ideas on Pinterest',
    urlTemplate: 'https://www.pinterest.com/search/pins/?q={eventType}+dinner+table+layout',
    contextKeys: ['eventType'],
    icon: 'Layout',
    newTab: true,
  },
  {
    id: 76,
    category: 'creative',
    label: 'Edit photos on Canva',
    urlTemplate: 'https://www.canva.com/photo-editor/',
    contextKeys: [],
    icon: 'Image',
    newTab: true,
  },

  // ──────────────────────────────────────────────
  // 77-83  MARKETING
  // ──────────────────────────────────────────────
  {
    id: 77,
    category: 'marketing',
    label: 'Post to Instagram',
    urlTemplate: 'https://www.instagram.com/',
    contextKeys: [],
    icon: 'Instagram',
    newTab: true,
    subLinks: [
      {
        label: 'Post to Facebook',
        urlTemplate: 'https://www.facebook.com/',
        contextKeys: [],
        icon: 'Facebook',
        newTab: true,
      },
      {
        label: 'Post to TikTok',
        urlTemplate: 'https://www.tiktok.com/upload',
        contextKeys: [],
        icon: 'Video',
        newTab: true,
      },
    ],
  },
  {
    id: 78,
    category: 'marketing',
    label: 'Schedule on Buffer',
    urlTemplate: 'https://publish.buffer.com/',
    contextKeys: [],
    icon: 'Clock',
    newTab: true,
  },
  {
    id: 79,
    category: 'marketing',
    label: 'Update Google Business',
    urlTemplate: 'https://business.google.com/',
    contextKeys: [],
    icon: 'Globe',
    newTab: true,
    subLinks: [
      {
        label: 'Add photos to Google',
        urlTemplate: 'https://business.google.com/photos',
        contextKeys: [],
        icon: 'Image',
        newTab: true,
      },
    ],
  },
  {
    id: 80,
    category: 'marketing',
    label: 'Reply on Yelp',
    urlTemplate: 'https://biz.yelp.com/',
    contextKeys: [],
    icon: 'Star',
    newTab: true,
    subLinks: [
      {
        label: 'Reply on Google Reviews',
        urlTemplate: 'https://business.google.com/reviews',
        contextKeys: [],
        icon: 'Star',
        newTab: true,
      },
    ],
  },
  {
    id: 81,
    category: 'marketing',
    label: 'Update website',
    urlTemplate: '{websiteAdminUrl}',
    contextKeys: ['websiteAdminUrl'],
    icon: 'Globe',
    newTab: true,
  },
  {
    id: 82,
    category: 'marketing',
    label: 'Create design on Canva',
    urlTemplate: 'https://www.canva.com/design/create',
    contextKeys: [],
    icon: 'Palette',
    newTab: true,
  },
  {
    id: 83,
    category: 'marketing',
    label: 'Create Facebook Ad',
    urlTemplate: 'https://www.facebook.com/adsmanager/create',
    contextKeys: [],
    icon: 'Megaphone',
    newTab: true,
    subLinks: [
      {
        label: 'Create Google Ad',
        urlTemplate: 'https://ads.google.com/aw/campaigns/new',
        contextKeys: [],
        icon: 'Megaphone',
        newTab: true,
      },
    ],
  },

  // ──────────────────────────────────────────────
  // 84-87  PROFESSIONAL GROWTH
  // ──────────────────────────────────────────────
  {
    id: 84,
    category: 'professional-growth',
    label: 'Renew ServSafe',
    urlTemplate: 'https://www.servsafe.com/ServSafe-Manager/Get-Certified',
    contextKeys: [],
    icon: 'Award',
    newTab: true,
    subLinks: [
      {
        label: 'Find courses',
        urlTemplate: 'https://www.google.com/search?q={specialty}+cooking+certification+course',
        contextKeys: ['specialty'],
        icon: 'Search',
        newTab: true,
      },
    ],
  },
  {
    id: 85,
    category: 'professional-growth',
    label: 'Read industry news',
    urlTemplate: 'https://www.eater.com',
    contextKeys: [],
    icon: 'Newspaper',
    newTab: true,
  },
  {
    id: 86,
    category: 'professional-growth',
    label: 'Message {chefName} on Instagram',
    urlTemplate: 'https://instagram.com/{chefHandle}',
    contextKeys: ['chefName', 'chefHandle'],
    icon: 'MessageCircle',
    newTab: true,
  },
  {
    id: 87,
    category: 'professional-growth',
    label: 'Contact {assistantName}',
    urlTemplate: 'tel:{assistantPhone}',
    contextKeys: ['assistantName', 'assistantPhone'],
    icon: 'Phone',
    newTab: true,
    subLinks: [
      {
        label: 'Text {assistantName}',
        urlTemplate: 'sms:{assistantPhone}?body=Available+for+{eventDate}?',
        contextKeys: ['assistantName', 'assistantPhone', 'eventDate'],
        icon: 'MessageSquare',
        newTab: true,
      },
    ],
  },

  // ──────────────────────────────────────────────
  // 88-91  KITCHEN BOUNDARY
  // ──────────────────────────────────────────────
  {
    id: 88,
    category: 'kitchen-boundary',
    label: 'Set timer (Siri)',
    urlTemplate: 'shortcuts://run-shortcut?name=Timer&input={minutes}',
    contextKeys: ['minutes'],
    icon: 'Clock',
    newTab: true,
  },
  {
    id: 89,
    category: 'kitchen-boundary',
    label: 'In-app: kitchen display mode',
    urlTemplate: null,
    contextKeys: [],
    icon: 'Monitor',
    newTab: false,
    inApp: true,
  },
  {
    id: 90,
    category: 'kitchen-boundary',
    label: 'Open Spotify',
    urlTemplate: 'https://open.spotify.com/search/{ambianceNote}',
    contextKeys: ['ambianceNote'],
    icon: 'Music',
    newTab: true,
  },
  {
    id: 91,
    category: 'kitchen-boundary',
    label: 'In-app: voice commands',
    urlTemplate: null,
    contextKeys: [],
    icon: 'Mic',
    newTab: false,
    inApp: true,
  },
]

/** Quick lookup by id (O(1) after init). */
const registryById = new Map<number, ExitLinkDefinition>()
for (const link of EXIT_LINK_REGISTRY) {
  registryById.set(link.id, link)
}

export function getExitDefinition(id: number): ExitLinkDefinition | undefined {
  return registryById.get(id)
}

export function getExitDefinitionsByCategory(
  category: ExitLinkDefinition['category']
): ExitLinkDefinition[] {
  return EXIT_LINK_REGISTRY.filter((l) => l.category === category)
}
