/**
 * Route Protection Matrix
 *
 * Declarative, pattern-based mapping of route groups to protection levels.
 * Single source of truth for "what level of auth does this route group need?"
 *
 * Patterns use simple glob syntax:
 *   "/admin/*"  matches /admin and all sub-paths
 *   "/login"    matches exactly /login
 *
 * Order matters: first match wins. Place more specific patterns before general ones.
 */

import type { RouteProtectionEntry } from './route-protection-types'

export const routeProtectionMatrix: RouteProtectionEntry[] = [
  // -- PUBLIC: no auth required -----------------------------------
  { pattern: '/', level: 'public', description: 'Landing page' },
  { pattern: '/about', level: 'public', description: 'About page' },
  { pattern: '/pricing', level: 'public', description: 'Pricing page' },
  { pattern: '/contact', level: 'public', description: 'Contact page' },
  { pattern: '/faq', level: 'public', description: 'FAQ page' },
  { pattern: '/how-it-works', level: 'public', description: 'How it works page' },
  { pattern: '/terms', level: 'public', description: 'Terms of service' },
  { pattern: '/privacy', level: 'public', description: 'Privacy policy (short)' },
  { pattern: '/privacy-policy', level: 'public', description: 'Privacy policy (full)' },
  { pattern: '/cookie-policy', level: 'public', description: 'Cookie policy' },
  { pattern: '/acceptable-use', level: 'public', description: 'Acceptable use policy' },
  { pattern: '/dmca', level: 'public', description: 'DMCA policy' },
  {
    pattern: '/refund-cancellation',
    level: 'public',
    description: 'Refund and cancellation policy',
  },
  { pattern: '/trust', level: 'public', description: 'Trust center' },
  { pattern: '/client-terms', level: 'public', description: 'Client terms' },
  { pattern: '/guest-terms', level: 'public', description: 'Guest terms' },
  { pattern: '/staff-terms', level: 'public', description: 'Staff terms' },
  { pattern: '/partner-terms', level: 'public', description: 'Partner terms' },
  { pattern: '/vendor-agreement', level: 'public', description: 'Vendor agreement' },
  { pattern: '/chef-agreement', level: 'public', description: 'Chef agreement' },
  { pattern: '/data-request', level: 'public', description: 'Data request form' },
  { pattern: '/unsubscribe', level: 'public', description: 'Email unsubscribe' },
  { pattern: '/reactivate-account', level: 'public', description: 'Account reactivation' },
  { pattern: '/unauthorized', level: 'public', description: 'Unauthorized access page' },
  { pattern: '/staff-login', level: 'public', description: 'Staff login page' },
  { pattern: '/for-operators/*', level: 'public', description: 'Operator marketing pages' },
  { pattern: '/services/*', level: 'public', description: 'Public service listings' },
  { pattern: '/chefs', level: 'public', description: 'Chef directory' },
  {
    pattern: '/chef/[slug]/*',
    level: 'public',
    description: 'Public chef profiles and storefronts',
  },
  { pattern: '/cuisines/*', level: 'public', description: 'Cuisine browsing' },
  { pattern: '/customers/*', level: 'public', description: 'Customer stories' },
  { pattern: '/discover/*', level: 'public', description: 'Discovery pages' },
  { pattern: '/nearby/*', level: 'public', description: 'Nearby directory' },
  { pattern: '/ingredients/*', level: 'public', description: 'Public ingredient pages' },
  { pattern: '/ingredient/*', level: 'public', description: 'Single ingredient detail' },
  { pattern: '/compare/*', level: 'public', description: 'Chef comparison' },
  { pattern: '/eat', level: 'public', description: 'Eat landing page' },
  { pattern: '/marketplace-chefs', level: 'public', description: 'Marketplace chef listings' },
  { pattern: '/hub/*', level: 'public', description: 'Public hub pages' },
  { pattern: '/gift-cards', level: 'public', description: 'Gift cards landing' },
  { pattern: '/beta/*', level: 'public', description: 'Beta signup pages' },
  { pattern: '/beta-survey/*', level: 'public', description: 'Beta survey pages' },
  { pattern: '/cannabis/public', level: 'public', description: 'Cannabis public info' },
  { pattern: '/cannabis-invite/*', level: 'public', description: 'Cannabis event invites' },
  { pattern: '/guest-feedback/*', level: 'public', description: 'Guest feedback via token' },
  { pattern: '/book/*', level: 'public', description: 'Booking flow and status' },
  { pattern: '/menu/*', level: 'public', description: 'Menu view via token' },
  { pattern: '/menu-pick/*', level: 'public', description: 'Menu selection via token' },
  { pattern: '/catalog-pick/*', level: 'public', description: 'Catalog pick via token' },
  { pattern: '/proposal/*', level: 'public', description: 'Proposal view via token' },
  { pattern: '/review/*', level: 'public', description: 'Review submission via token' },
  { pattern: '/feedback/*', level: 'public', description: 'Feedback via token' },
  { pattern: '/survey/*', level: 'public', description: 'Survey via token' },
  { pattern: '/share/*', level: 'public', description: 'Shared content via token' },
  { pattern: '/split/*', level: 'public', description: 'Bill splitting via token' },
  { pattern: '/tip/*', level: 'public', description: 'Tipping via token' },
  { pattern: '/view/*', level: 'public', description: 'View content via token' },
  { pattern: '/availability/*', level: 'public', description: 'Availability view via token' },
  { pattern: '/join/*', level: 'public', description: 'Join invitation via token' },
  { pattern: '/e/*', level: 'public', description: 'Event share via token' },
  { pattern: '/g/*', level: 'public', description: 'Group invite via code' },
  { pattern: '/event/*', level: 'public', description: 'Guest event view via token' },
  { pattern: '/partner-report/*', level: 'public', description: 'Partner report via token' },
  { pattern: '/partner-signup', level: 'public', description: 'Partner signup' },
  { pattern: '/worksheet/*', level: 'public', description: 'Worksheet via token' },
  { pattern: '/dietary-confirm/*', level: 'public', description: 'Dietary confirmation' },
  { pattern: '/client/*', level: 'public', description: 'Client portal token pages' },
  { pattern: '/embed/*', level: 'public', description: 'Embeddable widgets' },
  { pattern: '/intake/*', level: 'public', description: 'Intake form via token' },
  { pattern: '/web-research-health', level: 'public', description: 'Web research health check' },
  { pattern: '/staff-portal/*', level: 'public', description: 'Staff portal public access' },
  {
    pattern: '/auth/*',
    level: 'public',
    description: 'Authentication pages (signin, signup, reset)',
  },
  { pattern: '/api/e2e/*', level: 'public', description: 'End-to-end testing endpoints' },
  { pattern: '/feed.xml', level: 'public', description: 'RSS feed' },

  // -- AUTHENTICATED: sign-in required, any role -----------------
  {
    pattern: '/account-security',
    level: 'authenticated',
    description: 'Account security settings',
  },
  { pattern: '/nearby/join', level: 'authenticated', description: 'Join nearby directory' },
  { pattern: '/print/*', level: 'authenticated', description: 'Print views (menu, dosing packet)' },

  // -- CHEF: requires chef role -----------------------------------
  { pattern: '/dashboard', level: 'chef', description: 'Chef dashboard' },
  { pattern: '/daily', level: 'chef', description: 'Daily briefing' },
  { pattern: '/briefing', level: 'chef', description: 'Morning briefing' },
  { pattern: '/calendar/*', level: 'chef', description: 'Calendar views' },
  { pattern: '/events/*', level: 'chef', description: 'Event management' },
  { pattern: '/clients/*', level: 'chef', description: 'Client management' },
  { pattern: '/menus/*', level: 'chef', description: 'Menu management' },
  { pattern: '/recipes/*', level: 'chef', description: 'Recipe management' },
  { pattern: '/culinary/*', level: 'chef', description: 'Culinary workspace' },
  { pattern: '/culinary-board', level: 'chef', description: 'Culinary board overview' },
  { pattern: '/settings/*', level: 'chef', description: 'Chef settings' },
  { pattern: '/finance/*', level: 'chef', description: 'Financial management' },
  { pattern: '/analytics/*', level: 'chef', description: 'Analytics and reporting' },
  { pattern: '/inquiries/*', level: 'chef', description: 'Inquiry pipeline' },
  { pattern: '/quotes/*', level: 'chef', description: 'Quote management' },
  { pattern: '/proposals/*', level: 'chef', description: 'Proposal builder' },
  { pattern: '/contracts/*', level: 'chef', description: 'Contract management' },
  { pattern: '/payments/*', level: 'chef', description: 'Payment management' },
  { pattern: '/expenses/*', level: 'chef', description: 'Expense tracking' },
  { pattern: '/inventory/*', level: 'chef', description: 'Inventory management' },
  { pattern: '/shopping/*', level: 'chef', description: 'Shopping lists' },
  { pattern: '/prices/*', level: 'chef', description: 'Price catalog' },
  { pattern: '/food-cost/*', level: 'chef', description: 'Food cost analysis' },
  { pattern: '/guests/*', level: 'chef', description: 'Guest management' },
  { pattern: '/guest-leads', level: 'chef', description: 'Guest lead tracking' },
  { pattern: '/guest-analytics', level: 'chef', description: 'Guest analytics' },
  { pattern: '/leads/*', level: 'chef', description: 'Lead pipeline' },
  { pattern: '/staff/*', level: 'chef', description: 'Staff management (chef view)' },
  { pattern: '/team', level: 'chef', description: 'Team overview' },
  { pattern: '/stations/*', level: 'chef', description: 'Station management' },
  { pattern: '/vendors/*', level: 'chef', description: 'Vendor management (chef view)' },
  { pattern: '/partners/*', level: 'chef', description: 'Partner management' },
  { pattern: '/circles/*', level: 'chef', description: 'Dinner circles' },
  { pattern: '/chat/*', level: 'chef', description: 'Chef messaging' },
  { pattern: '/inbox/*', level: 'chef', description: 'Chef inbox' },
  { pattern: '/notifications', level: 'chef', description: 'Notifications center' },
  { pattern: '/remy/*', level: 'chef', description: 'Remy AI assistant' },
  { pattern: '/commerce/*', level: 'chef', description: 'Commerce and POS' },
  { pattern: '/marketing/*', level: 'chef', description: 'Marketing tools' },
  { pattern: '/social/*', level: 'chef', description: 'Social media management' },
  { pattern: '/cannabis/*', level: 'chef', description: 'Cannabis service management' },
  { pattern: '/community/*', level: 'chef', description: 'Chef community' },
  { pattern: '/network/*', level: 'chef', description: 'Chef network' },
  { pattern: '/documents', level: 'chef', description: 'Document vault' },
  { pattern: '/tasks/*', level: 'chef', description: 'Task management' },
  { pattern: '/safety/*', level: 'chef', description: 'Safety and compliance' },
  { pattern: '/travel', level: 'chef', description: 'Travel management' },
  { pattern: '/locations/*', level: 'chef', description: 'Location management' },
  { pattern: '/ops/*', level: 'chef', description: 'Operations dashboard' },
  { pattern: '/production', level: 'chef', description: 'Production planning' },
  { pattern: '/prep/*', level: 'chef', description: 'Prep consolidation' },
  { pattern: '/kitchen', level: 'chef', description: 'Kitchen view' },
  { pattern: '/explore/*', level: 'chef', description: 'Chef explore/discover' },
  { pattern: '/pipeline', level: 'chef', description: 'Sales pipeline' },
  { pattern: '/pulse', level: 'chef', description: 'Business pulse' },
  { pattern: '/queue', level: 'chef', description: 'Priority queue' },
  { pattern: '/insights/*', level: 'chef', description: 'Business insights' },
  { pattern: '/loyalty/*', level: 'chef', description: 'Loyalty program management' },
  { pattern: '/reputation/*', level: 'chef', description: 'Reputation management' },
  { pattern: '/reviews', level: 'chef', description: 'Review management' },
  { pattern: '/surveys', level: 'chef', description: 'Survey management' },
  { pattern: '/receipts', level: 'chef', description: 'Receipt tracking' },
  { pattern: '/rate-card', level: 'chef', description: 'Rate card' },
  { pattern: '/portfolio', level: 'chef', description: 'Chef portfolio' },
  { pattern: '/capture', level: 'chef', description: 'Quick capture' },
  { pattern: '/quick-log', level: 'chef', description: 'Quick log entry' },
  { pattern: '/help/*', level: 'chef', description: 'Chef help center' },
  { pattern: '/onboarding/*', level: 'chef', description: 'Chef onboarding flow' },
  { pattern: '/welcome', level: 'chef', description: 'Welcome page' },
  { pattern: '/features', level: 'chef', description: 'Feature discovery' },
  { pattern: '/charity/*', level: 'chef', description: 'Charity event tracking' },
  { pattern: '/content/*', level: 'chef', description: 'Content management' },
  { pattern: '/consulting', level: 'chef', description: 'Consulting services' },
  { pattern: '/marketplace/*', level: 'chef', description: 'Marketplace management' },
  { pattern: '/meal-prep/*', level: 'chef', description: 'Meal prep programs' },
  { pattern: '/nutrition/*', level: 'chef', description: 'Nutrition analysis' },
  { pattern: '/prospecting/*', level: 'chef', description: 'Lead prospecting' },
  { pattern: '/waitlist', level: 'chef', description: 'Waitlist management' },
  { pattern: '/wix-submissions/*', level: 'chef', description: 'Wix form submissions' },
  { pattern: '/import/*', level: 'chef', description: 'Data import tools' },
  { pattern: '/imports/*', level: 'chef', description: 'Import history' },
  { pattern: '/activity/*', level: 'chef', description: 'Activity feed' },
  { pattern: '/aar', level: 'chef', description: 'After action review' },
  { pattern: '/autopilot', level: 'chef', description: 'Autopilot settings' },
  { pattern: '/calls/*', level: 'chef', description: 'Call management' },
  { pattern: '/communication/*', level: 'chef', description: 'Communication center' },
  { pattern: '/dev/*', level: 'chef', description: 'Developer tools' },
  { pattern: '/pie-cart', level: 'chef', description: 'PIE price cart' },
  { pattern: '/reminders', level: 'chef', description: 'Reminder management' },

  // -- CLIENT: requires client role -------------------------------
  { pattern: '/my-bookings', level: 'client', description: 'Client bookings' },
  { pattern: '/my-calendar', level: 'client', description: 'Client calendar' },
  { pattern: '/my-cannabis/*', level: 'client', description: 'Client cannabis orders' },
  { pattern: '/my-chat/*', level: 'client', description: 'Client messaging' },
  { pattern: '/my-dietary', level: 'client', description: 'Dietary preferences' },
  { pattern: '/my-documents', level: 'client', description: 'Client documents' },
  { pattern: '/my-events/*', level: 'client', description: 'Client event views' },
  { pattern: '/my-gift-cards', level: 'client', description: 'Client gift cards' },
  { pattern: '/my-help', level: 'client', description: 'Client help' },
  { pattern: '/my-household', level: 'client', description: 'Household management' },
  { pattern: '/my-hub/*', level: 'client', description: 'Client hub and groups' },
  { pattern: '/my-inquiries/*', level: 'client', description: 'Client inquiries' },
  { pattern: '/my-meals', level: 'client', description: 'Client meal history' },
  { pattern: '/my-notifications', level: 'client', description: 'Client notifications' },
  { pattern: '/my-passport', level: 'client', description: 'Client food passport' },
  { pattern: '/my-preferences/*', level: 'client', description: 'Client preferences' },
  { pattern: '/my-profile/*', level: 'client', description: 'Client profile' },
  { pattern: '/my-quotes/*', level: 'client', description: 'Client quotes' },
  { pattern: '/my-receipts/*', level: 'client', description: 'Client receipts' },
  { pattern: '/my-recipes', level: 'client', description: 'Client saved recipes' },
  { pattern: '/my-recurring', level: 'client', description: 'Recurring services' },
  { pattern: '/my-referrals', level: 'client', description: 'Client referrals' },
  { pattern: '/my-reviews', level: 'client', description: 'Client reviews' },
  { pattern: '/my-rewards/*', level: 'client', description: 'Client rewards' },
  { pattern: '/my-spending/*', level: 'client', description: 'Client spending history' },
  { pattern: '/my-timeline', level: 'client', description: 'Client event timeline' },
  { pattern: '/book-now', level: 'client', description: 'Book now (signed-in client)' },
  { pattern: '/browse-dates', level: 'client', description: 'Browse available dates' },

  // -- ADMIN: requires admin/founder role -------------------------
  { pattern: '/admin/*', level: 'admin', description: 'Admin panel (all sub-routes)' },

  // -- STAFF: requires staff role ---------------------------------
  { pattern: '/staff-dashboard', level: 'staff', description: 'Staff dashboard' },
  { pattern: '/staff-recipes', level: 'staff', description: 'Staff recipe access' },
  { pattern: '/staff-schedule', level: 'staff', description: 'Staff schedule' },
  { pattern: '/staff-station', level: 'staff', description: 'Staff station assignment' },
  { pattern: '/staff-tasks', level: 'staff', description: 'Staff tasks' },
  { pattern: '/staff-time', level: 'staff', description: 'Staff time tracking' },

  // -- PARTNER: requires partner role -----------------------------
  { pattern: '/partner/*', level: 'partner', description: 'Partner portal' },

  // -- VENDOR: requires vendor role -------------------------------
  { pattern: '/vendor/*', level: 'vendor', description: 'Vendor portal' },

  // -- DEMO: demo mode --------------------------------------------
  { pattern: '/demo', level: 'demo', description: 'Demo mode' },

  // -- MOBILE: token-based mobile access --------------------------
  { pattern: '/chef/[slug]/dashboard', level: 'mobile', description: 'Mobile chef dashboard' },
  { pattern: '/client/[token]/events', level: 'mobile', description: 'Mobile client events' },

  // -- KIOSK: device-paired kiosk mode ----------------------------
  { pattern: '/kiosk/*', level: 'kiosk', description: 'Kiosk mode pages' },
]
