// Location Alert Server Actions
// Create, acknowledge, resolve, and query operational alerts per location.
// Includes automatic alert generation based on thresholds.

'use server'

import { z } from 'zod'
import { revalidatePath } from 'next/cache'
import { requireChef } from '@/lib/auth/get-user'
import { createServerClient } from '@/lib/db/server'

// ─── Types ───────────────────────────────────────────────────────

export type AlertType =
  | 'low_inventory'
  | 'high_food_cost'
  | 'high_labor_cost'
  | 'low_covers'
  | 'high_waste'
  | 'staff_shortage'
  | 'equipment_issue'
  | 'compliance_due'
  | 'revenue_drop'
  | 'portion_drift'
  | 'recipe_deviation'
  | 'speed_degradation'
  | 'custom'

export type AlertSeverity = 'low' | 'medium' | 'high' | 'critical'

export type LocationAlert = {
  id: string
  tenantId: string
  locationId: string
  alertType: AlertType
  severity: AlertSeverity
  title: string
  description: string | null
  metricValue: number | null
  thresholdValue: number | null
  metadata: Record<string, unknown>
  acknowledgedAt: string | null
  acknowledgedBy: string | null
  resolvedAt: string | null
  resolvedBy: string | null
  autoGenerated: boolean
  createdAt: string
}

// ─── Schemas ─────────────────────────────────────────────────────

const CreateAlertSchema = z.object({
  locationId: z.string().uuid(),
  alertType: z.enum([
    'low_inventory',
    'high_food_cost',
    'high_labor_cost',
    'low_covers',
    'high_waste',
    'staff_shortage',
    'equipment_issue',
    'compliance_due',
    'revenue_drop',
    'portion_drift',
    'recipe_deviation',
    'speed_degradation',
    'custom',
  ]),
  severity: z.enum(['low', 'medium', 'high', 'critical']).default('medium'),
  title: z.string().min(1),
  description: z.string().optional(),
  metricValue: z.number().optional(),
  thresholdValue: z.number().optional(),
  metadata: z.record(z.string(), z.unknown()).optional(),
})

// ─── Helpers ─────────────────────────────────────────────────────

function mapAlert(row: any): LocationAlert {
  return {
    id: row.id,
    tenantId: row.tenant_id,
    locationId: row.location_id,
    alertType: row.alert_type,
    severity: row.severity,
    title: row.title,
    description: row.description,
    metricValue: row.metric_value ? Number(row.metric_value) : null,
    thresholdValue: row.threshold_value ? Number(row.threshold_value) : null,
    metadata: row.metadata ?? {},
    acknowledgedAt: row.acknowledged_at,
    acknowledgedBy: row.acknowledged_by,
    resolvedAt: row.resolved_at,
    resolvedBy: row.resolved_by,
    autoGenerated: row.auto_generated,
    createdAt: row.created_at,
  }
}

// ─── Actions ─────────────────────────────────────────────────────

export async function getActiveAlerts(locationId?: string): Promise<LocationAlert[]> {
  const user = await requireChef()
  const db: any = createServerClient()

  let query = db
    .from('location_alerts')
    .select('*')
    .eq('tenant_id', user.tenantId!)
    .is('resolved_at', null)
    .order('created_at', { ascending: false })

  if (locationId) {
    query = query.eq('location_id', locationId)
  }

  const { data, error } = await query
  if (error) throw new Error(`Failed to get alerts: ${error.message}`)
  return (data ?? []).map(mapAlert)
}

export async function getAlertHistory(
  locationId: string,
  limit: number = 50
): Promise<LocationAlert[]> {
  const user = await requireChef()
  const db: any = createServerClient()

  const { data, error } = await db
    .from('location_alerts')
    .select('*')
    .eq('tenant_id', user.tenantId!)
    .eq('location_id', locationId)
    .order('created_at', { ascending: false })
    .limit(limit)

  if (error) throw new Error(`Failed to get alert history: ${error.message}`)
  return (data ?? []).map(mapAlert)
}

export async function createAlert(
  input: z.infer<typeof CreateAlertSchema>
): Promise<{ success: boolean; error?: string }> {
  const user = await requireChef()
  const parsed = CreateAlertSchema.parse(input)
  const db: any = createServerClient()

  const { error } = await db.from('location_alerts').insert({
    tenant_id: user.tenantId!,
    location_id: parsed.locationId,
    alert_type: parsed.alertType,
    severity: parsed.severity,
    title: parsed.title,
    description: parsed.description ?? null,
    metric_value: parsed.metricValue ?? null,
    threshold_value: parsed.thresholdValue ?? null,
    metadata: parsed.metadata ?? {},
    auto_generated: false,
  })

  if (error) return { success: false, error: error.message }

  revalidatePath('/locations')
  return { success: true }
}

export async function acknowledgeAlert(
  alertId: string
): Promise<{ success: boolean; error?: string }> {
  const user = await requireChef()
  const db: any = createServerClient()

  const { error } = await db
    .from('location_alerts')
    .update({
      acknowledged_at: new Date().toISOString(),
      acknowledged_by: user.id,
    })
    .eq('id', alertId)
    .eq('tenant_id', user.tenantId!)

  if (error) return { success: false, error: error.message }

  revalidatePath('/locations')
  return { success: true }
}

export async function resolveAlert(alertId: string): Promise<{ success: boolean; error?: string }> {
  const user = await requireChef()
  const db: any = createServerClient()

  const { error } = await db
    .from('location_alerts')
    .update({
      resolved_at: new Date().toISOString(),
      resolved_by: user.id,
    })
    .eq('id', alertId)
    .eq('tenant_id', user.tenantId!)

  if (error) return { success: false, error: error.message }

  revalidatePath('/locations')
  return { success: true }
}

// ─── Automatic Alert Generation ──────────────────────────────────

export async function generateAlertsForLocation(locationId: string): Promise<number> {
  const user = await requireChef()
  const db: any = createServerClient()
  const today = new Date().toISOString().split('T')[0]
  let alertsGenerated = 0

  // Get location with targets
  const { data: location } = await db
    .from('business_locations')
    .select('*')
    .eq('id', locationId)
    .eq('tenant_id', user.tenantId!)
    .single()

  if (!location) return 0

  // Get today's metrics
  const { data: metrics } = await db
    .from('location_daily_metrics')
    .select('*')
    .eq('location_id', locationId)
    .eq('date', today)
    .single()

  if (!metrics) return 0

  const alerts: Array<z.infer<typeof CreateAlertSchema>> = []

  // High food cost alert
  if (location.food_cost_target_pct && metrics.food_cost_pct) {
    const threshold = Number(location.food_cost_target_pct)
    const actual = Number(metrics.food_cost_pct)
    if (actual > threshold * 1.1) {
      alerts.push({
        locationId,
        alertType: 'high_food_cost',
        severity: actual > threshold * 1.25 ? 'critical' : 'high',
        title: `Food cost ${actual.toFixed(1)}% exceeds target ${threshold.toFixed(1)}%`,
        metricValue: actual,
        thresholdValue: threshold,
      })
    }
  }

  // High labor cost alert
  if (location.labor_cost_target_pct && metrics.labor_cost_pct) {
    const threshold = Number(location.labor_cost_target_pct)
    const actual = Number(metrics.labor_cost_pct)
    if (actual > threshold * 1.1) {
      alerts.push({
        locationId,
        alertType: 'high_labor_cost',
        severity: actual > threshold * 1.25 ? 'critical' : 'high',
        title: `Labor cost ${actual.toFixed(1)}% exceeds target ${threshold.toFixed(1)}%`,
        metricValue: actual,
        thresholdValue: threshold,
      })
    }
  }

  // Low covers alert (below 70% of target)
  if (location.daily_cover_target && metrics.covers_served !== undefined) {
    const target = location.daily_cover_target
    const actual = metrics.covers_served
    if (actual < target * 0.7) {
      alerts.push({
        locationId,
        alertType: 'low_covers',
        severity: actual < target * 0.5 ? 'critical' : 'medium',
        title: `Only ${actual} covers (target: ${target})`,
        metricValue: actual,
        thresholdValue: target,
      })
    }
  }

  // Revenue drop alert (below 70% of target)
  if (location.daily_revenue_target_cents && metrics.revenue_cents !== undefined) {
    const target = Number(location.daily_revenue_target_cents)
    const actual = Number(metrics.revenue_cents)
    if (actual < target * 0.7) {
      alerts.push({
        locationId,
        alertType: 'revenue_drop',
        severity: actual < target * 0.5 ? 'critical' : 'medium',
        title: `Revenue $${(actual / 100).toFixed(0)} below target $${(target / 100).toFixed(0)}`,
        metricValue: actual,
        thresholdValue: target,
      })
    }
  }

  // High waste alert (waste > 5% of revenue)
  if (metrics.revenue_cents > 0 && metrics.waste_cents > 0) {
    const wastePct = (metrics.waste_cents / metrics.revenue_cents) * 100
    if (wastePct > 5) {
      alerts.push({
        locationId,
        alertType: 'high_waste',
        severity: wastePct > 10 ? 'critical' : 'high',
        title: `Waste at ${wastePct.toFixed(1)}% of revenue`,
        metricValue: wastePct,
        thresholdValue: 5,
      })
    }
  }

  // Insert alerts (skip duplicates by checking existing active alerts)
  for (const alert of alerts) {
    const { count } = await db
      .from('location_alerts')
      .select('id', { count: 'exact', head: true })
      .eq('location_id', locationId)
      .eq('alert_type', alert.alertType)
      .is('resolved_at', null)
      .gte('created_at', `${today}T00:00:00Z`)

    if ((count ?? 0) === 0) {
      await db.from('location_alerts').insert({
        tenant_id: user.tenantId!,
        location_id: alert.locationId,
        alert_type: alert.alertType,
        severity: alert.severity,
        title: alert.title,
        description: alert.description ?? null,
        metric_value: alert.metricValue ?? null,
        threshold_value: alert.thresholdValue ?? null,
        metadata: alert.metadata ?? {},
        auto_generated: true,
      })
      alertsGenerated++
    }
  }

  if (alertsGenerated > 0) revalidatePath('/locations')
  return alertsGenerated
}
