'use server'

import { requireChef } from '@/lib/auth/get-user'
import { createServerClient } from '@/lib/db/server'
import { revalidatePath } from 'next/cache'

// ─── Types ───────────────────────────────────────────────────────────────────

export type PrintPreferences = {
  show_attribution: boolean
  attribution_name: string | null
  default_print_mode: 'standard' | 'thermal-80' | 'thermal-58'
  custom_footer: string | null
}

const DEFAULT_PRINT_PREFS: PrintPreferences = {
  show_attribution: true,
  attribution_name: null,
  default_print_mode: 'standard',
  custom_footer: null,
}

// ─── Fetch ───────────────────────────────────────────────────────────────────

export async function getPrintPreferences(): Promise<PrintPreferences> {
  const user = await requireChef()
  const db: any = createServerClient()

  const { data } = await db
    .from('chef_preferences')
    .select('print_preferences')
    .eq('tenant_id', user.tenantId!)
    .single()

  if (!data?.print_preferences) return DEFAULT_PRINT_PREFS

  return { ...DEFAULT_PRINT_PREFS, ...data.print_preferences }
}

/**
 * Resolve the "Generated by" name for documents.
 * Returns null if attribution is disabled.
 * Uses: attribution_name override → business_name → email fallback.
 */
export async function getDocumentAttribution(): Promise<string | null> {
  const user = await requireChef()
  const db: any = createServerClient()

  const { data } = await db
    .from('chef_preferences')
    .select('print_preferences')
    .eq('tenant_id', user.tenantId!)
    .single()

  const prefs: PrintPreferences = { ...DEFAULT_PRINT_PREFS, ...(data?.print_preferences ?? {}) }

  if (!prefs.show_attribution) return null

  // If custom attribution name is set, use it
  if (prefs.attribution_name) return prefs.attribution_name

  // Otherwise fall back to business name
  const { data: chef } = await db
    .from('chefs')
    .select('business_name')
    .eq('id', user.tenantId!)
    .single()

  return chef?.business_name || user.email
}

/**
 * Fetch all document rendering context in a single call - attribution, print mode, custom footer.
 * Used by browser print pages and the PDF API route to avoid multiple DB round-trips.
 */
export async function getDocumentContext(): Promise<{
  generatedBy: string | undefined
  printMode: PrintPreferences['default_print_mode']
  customFooter: string | null
}> {
  const user = await requireChef()
  const db: any = createServerClient()

  const { data } = await db
    .from('chef_preferences')
    .select('print_preferences')
    .eq('tenant_id', user.tenantId!)
    .single()

  const prefs: PrintPreferences = { ...DEFAULT_PRINT_PREFS, ...(data?.print_preferences ?? {}) }

  let generatedBy: string | undefined = undefined
  if (prefs.show_attribution) {
    if (prefs.attribution_name) {
      generatedBy = prefs.attribution_name
    } else {
      const { data: chef } = await db
        .from('chefs')
        .select('business_name')
        .eq('id', user.tenantId!)
        .single()
      generatedBy = chef?.business_name || user.email
    }
  }

  return {
    generatedBy,
    printMode: prefs.default_print_mode,
    customFooter: prefs.custom_footer,
  }
}

// ─── Update ──────────────────────────────────────────────────────────────────

export async function updatePrintPreferences(
  updates: Partial<PrintPreferences>
): Promise<{ success: boolean; error?: string }> {
  const user = await requireChef()
  const db: any = createServerClient()

  // Merge with existing
  const current = await getPrintPreferences()
  const merged = { ...current, ...updates }

  const { error } = await db
    .from('chef_preferences')
    .update({ print_preferences: merged })
    .eq('tenant_id', user.tenantId!)

  if (error) {
    console.error('[print/actions] Update failed:', error)
    return { success: false, error: error.message }
  }

  revalidatePath('/settings')
  return { success: true }
}
