#!/usr/bin/env bash
# ============================================================================
# ChefFlow Regression -> Codex Spec Generator
# ============================================================================
# Reads regression reports and generates focused, single-task Codex-compatible
# repair specs in docs/specs/auto-repair/.
#
# Sources:
#   .regression-report.md         - missing routes, files, exports
#   .regression-semantic-report.md - missing auth gates, no-ops, empty handlers
#   .regression-fragile-report.md  - CRIT/HIGH fragile files
#
# Usage:
#   bash scripts/regression-codex-specs.sh           # generate specs
#   bash scripts/regression-codex-specs.sh --clean    # remove all auto-repair specs
#   bash scripts/regression-codex-specs.sh --list     # list current auto-repair specs
#
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SPEC_DIR="$PROJECT_ROOT/docs/specs/auto-repair"

# Report paths
REGRESSION_REPORT="$PROJECT_ROOT/.regression-report.md"
SEMANTIC_REPORT="$PROJECT_ROOT/.regression-semantic-report.md"
FRAGILE_REPORT="$PROJECT_ROOT/.regression-fragile-report.md"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'
BOLD='\033[1m'
DIM='\033[2m'

TODAY=$(date -u +'%Y-%m-%d')
GENERATED=0
SKIPPED=0
ERRORS=0

# --------------------------------------------------------------------------
# Mode dispatch
# --------------------------------------------------------------------------

case "${1:-}" in
  --clean)
    if [[ -d "$SPEC_DIR" ]]; then
      count=$(find "$SPEC_DIR" -name '*.md' -type f 2>/dev/null | wc -l | tr -d ' ')
      rm -rf "$SPEC_DIR"
      echo -e "${GREEN}Cleaned${NC} $count auto-repair spec(s) from docs/specs/auto-repair/"
    else
      echo -e "${DIM}No auto-repair specs to clean.${NC}"
    fi
    exit 0
    ;;
  --list)
    if [[ -d "$SPEC_DIR" ]] && [[ -n "$(ls -A "$SPEC_DIR" 2>/dev/null)" ]]; then
      echo -e "${BOLD}Auto-Repair Specs${NC}"
      echo ""
      for f in "$SPEC_DIR"/*.md; do
        [[ -f "$f" ]] || continue
        basename_f=$(basename "$f" .md)
        # Extract the title line
        title=$(head -1 "$f" | sed 's/^# //')
        echo -e "  ${CYAN}$basename_f${NC}"
        echo -e "    $title"
      done
      echo ""
      count=$(find "$SPEC_DIR" -name '*.md' -type f 2>/dev/null | wc -l | tr -d ' ')
      echo -e "${DIM}$count spec(s) total${NC}"
    else
      echo -e "${DIM}No auto-repair specs found.${NC}"
    fi
    exit 0
    ;;
  "")
    # Default: generate
    ;;
  *)
    echo -e "${RED}Unknown flag: $1${NC}"
    echo "Usage: $0 [--clean | --list]"
    exit 1
    ;;
esac

# --------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------

mkdir -p "$SPEC_DIR"

# Slugify a string for use as a filename
slugify() {
  echo "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed 's/[^a-z0-9.]/-/g' \
    | sed 's/--*/-/g' \
    | sed 's/^-//;s/-$//' \
    | cut -c1-80
}

# Check if a spec for this issue already exists (by matching the slug)
spec_exists() {
  local slug="$1"
  [[ -f "$SPEC_DIR/${slug}.md" ]]
}

# Write a spec file
write_spec() {
  local slug="$1"
  local description="$2"
  local problem="$3"
  local fix="$4"
  local verification="$5"
  local source_report="$6"

  if spec_exists "$slug"; then
    SKIPPED=$((SKIPPED + 1))
    return
  fi

  cat > "$SPEC_DIR/${slug}.md" << SPECEOF
# Auto-Repair: $description

## Source
Generated by regression detection system on $TODAY
Report: $source_report

## Problem
$problem

## Fix
$fix

## Verification
$verification

## Constraints
- Do not delete or remove existing functionality
- Do not modify unrelated code
- Run \`bash scripts/regression-check.sh --quick\` after fix to verify no new regressions
SPECEOF

  GENERATED=$((GENERATED + 1))
  echo -e "  ${GREEN}+${NC} $slug"
}

# --------------------------------------------------------------------------
# 1. Process .regression-report.md (missing routes, files, exports)
# --------------------------------------------------------------------------

process_regression_report() {
  [[ -f "$REGRESSION_REPORT" ]] || return 0

  echo -e "${BOLD}${CYAN}[REGRESSION REPORT]${NC} $REGRESSION_REPORT"

  while IFS= read -r line; do
    # Lines look like: - `app/(chef)/some/page.tsx (chef_routes)`
    # or: - `lib/events/actions.ts::createEvent()`
    # or: - `lib/events/actions.ts (FILE MISSING)`
    # or: - `schema::events (table not in schema)`
    # or: - `semantic regression checks (...)`

    # Strip markdown bullet and backticks
    item=$(echo "$line" | sed 's/^- `//;s/`$//')

    # Skip meta-entries
    if [[ "$item" == *"semantic regression"* ]]; then
      continue
    fi

    # Missing export: file::function()
    if [[ "$item" == *"::"* ]] && [[ "$item" != *"schema::"* ]]; then
      file=$(echo "$item" | sed 's/::.*//')
      func=$(echo "$item" | sed 's/.*:://;s/()//')

      slug="missing-export-$(slugify "$file-$func")"
      write_spec "$slug" \
        "Missing export: $func in $file" \
        "The function \`$func\` is expected to be exported from \`$file\` but was not found. It may have been renamed, moved to another file, or accidentally removed." \
        "1. Open \`$file\` and check if \`$func\` exists under a different name
2. Search the codebase for \`$func\` to see if it was moved: \`grep -r '$func' lib/ app/\`
3. If renamed: restore the original export name or update the regression registry (\`scripts/regression-registry.json\`)
4. If deleted: determine if it is still needed by checking callers, then restore or remove from registry" \
        "1. Run \`bash scripts/regression-check.sh --quick\` and confirm \`$file::$func\` no longer appears as missing
2. Verify \`npx tsc --noEmit --skipLibCheck\` passes (no import errors from callers)" \
        ".regression-report.md"
      continue
    fi

    # Missing schema table: schema::tablename
    if [[ "$item" == "schema::"* ]]; then
      table=$(echo "$item" | sed 's/schema:://;s/ .*//')

      slug="missing-schema-table-$(slugify "$table")"
      write_spec "$slug" \
        "Missing schema table: $table" \
        "The table \`$table\` is expected in \`lib/db/schema/schema.ts\` but was not found. It may have been removed or the migration was never applied." \
        "1. Check if the table exists in the database: query \`SELECT tablename FROM pg_tables WHERE tablename = '$table'\`
2. Check \`database/migrations/\` for the migration that creates this table
3. If the table should exist, ensure the schema file reflects it
4. If the table was intentionally removed, update \`scripts/regression-registry.json\` to remove it" \
        "Run \`bash scripts/regression-check.sh\` and confirm \`schema::$table\` no longer appears as missing" \
        ".regression-report.md"
      continue
    fi

    # Missing file/route: path (group)
    if [[ "$item" == *"("* ]]; then
      file=$(echo "$item" | sed 's/ (.*//')
      group=$(echo "$item" | sed 's/.*(\(.*\))/\1/')

      # Determine if it is a route, API route, or critical file
      local file_type="file"
      if [[ "$file" == *"/page.tsx" ]]; then
        file_type="route"
      elif [[ "$file" == *"/route.ts" ]]; then
        file_type="API route"
      fi

      slug="missing-$(slugify "$file_type")-$(slugify "$file")"
      write_spec "$slug" \
        "Missing $file_type: $file" \
        "The $file_type \`$file\` (group: $group) is registered in the regression registry but does not exist on disk. It may have been accidentally deleted, moved, or renamed." \
        "1. Check git history for the file: \`git log --all --follow -- '$file'\`
2. If moved/renamed: update \`scripts/regression-registry.json\` to point to the new path
3. If accidentally deleted: restore from git: \`git checkout HEAD~1 -- '$file'\` (adjust commit as needed)
4. If intentionally removed: remove from regression registry" \
        "1. Verify \`$file\` exists on disk or has been removed from the registry
2. Run \`bash scripts/regression-check.sh --quick\` and confirm no regression for this file" \
        ".regression-report.md"
      continue
    fi

  done < <(grep '^- ' "$REGRESSION_REPORT" 2>/dev/null || true)
}

# --------------------------------------------------------------------------
# 2. Process .regression-semantic-report.md
# --------------------------------------------------------------------------

process_semantic_report() {
  [[ -f "$SEMANTIC_REPORT" ]] || return 0

  echo -e "${BOLD}${CYAN}[SEMANTIC REPORT]${NC} $SEMANTIC_REPORT"

  # -- Auth gate failures --
  # Group auth gate failures by directory to avoid 100+ individual specs
  local auth_files=()

  while IFS= read -r line; do
    item=$(echo "$line" | sed 's/^- `//;s/`$//')

    # Missing auth gate
    if [[ "$item" == "Missing auth gate: "* ]]; then
      file=$(echo "$item" | sed 's/Missing auth gate: //')
      auth_files+=("$file")
      continue
    fi

    # No-op return { success: true }
    if [[ "$item" == "No-op return"* ]]; then
      file=$(echo "$item" | sed 's/No-op return { success: true } in //;s/ at L.*//')
      lines=$(echo "$item" | sed 's/.* at //')

      slug="noop-return-$(slugify "$file")"
      write_spec "$slug" \
        "No-op return in $file" \
        "The file \`$file\` contains \`return { success: true }\` at line(s) $lines with no meaningful logic preceding the return. This is a Zero Hallucination violation: the function reports success without doing any work." \
        "1. Open \`$file\` and examine the function(s) at line(s) $lines
2. For each no-op return, determine:
   a. If the function is a stub awaiting implementation: add a TODO comment and change to \`return { success: false, error: 'Not yet implemented' }\`
   b. If the function was implemented elsewhere: remove the dead function or redirect to the real implementation
   c. If the function is intentionally a no-op (e.g., feature flag off): add a comment explaining why
3. Never return \`{ success: true }\` without performing the operation the caller expects" \
        "1. Verify the function(s) either perform real work or honestly report they do not
2. Run \`bash scripts/regression-semantic.sh --quiet\` and confirm \`$file\` no longer appears in no-op detection" \
        ".regression-semantic-report.md"
      continue
    fi

    # Empty event handler
    if [[ "$item" == "Empty event handler"* ]]; then
      file=$(echo "$item" | sed 's/Empty event handler in //;s/ at L.*//')
      lines=$(echo "$item" | sed 's/.* at //')

      slug="empty-handler-$(slugify "$file")"
      write_spec "$slug" \
        "Empty event handler in $file" \
        "The file \`$file\` contains empty event handler(s) (e.g., \`onClick={() => {}}\`) at line(s) $lines. This is a Zero Hallucination violation: a clickable/interactive element that does nothing appears functional to the user." \
        "1. Open \`$file\` and examine line(s) $lines
2. For each empty handler, determine:
   a. If the handler should do something: implement it
   b. If the element should not be interactive: remove the handler and any interactive styling (e.g., cursor-pointer)
   c. If the feature is WIP: add a TODO comment and either hide the element or show a 'coming soon' indicator
3. Never render a clickable element that does nothing" \
        "1. Run \`bash scripts/regression-semantic.sh --quiet\` and confirm \`$file\` no longer appears in empty handler detection
2. Visually verify the affected component behaves correctly" \
        ".regression-semantic-report.md"
      continue
    fi

  done < <(grep '^- ' "$SEMANTIC_REPORT" 2>/dev/null | grep -v '^- `Suspicious' || true)

  # -- Generate grouped auth gate specs by top-level directory --
  if [[ ${#auth_files[@]} -gt 0 ]]; then
    # Group by lib/X directory
    declare -A auth_groups
    for file in "${auth_files[@]}"; do
      # Extract grouping key: lib/ai, lib/hub, lib/events, etc.
      group_key=$(echo "$file" | sed 's|/[^/]*$||')
      if [[ -z "${auth_groups[$group_key]+_}" ]]; then
        auth_groups[$group_key]="$file"
      else
        auth_groups[$group_key]="${auth_groups[$group_key]}"$'\n'"$file"
      fi
    done

    for group_key in "${!auth_groups[@]}"; do
      file_list="${auth_groups[$group_key]}"
      file_count=$(echo "$file_list" | wc -l | tr -d ' ')

      slug="missing-auth-gate-$(slugify "$group_key")"

      # Build the file list for the spec
      formatted_files=""
      while IFS= read -r f; do
        formatted_files="${formatted_files}
- \`$f\`"
      done <<< "$file_list"

      write_spec "$slug" \
        "Missing auth gates in $group_key/ ($file_count files)" \
        "The following $file_count server action file(s) in \`$group_key/\` contain \`'use server'\` and export async functions but do not call any auth gate function (\`requireChef\`, \`requireAuth\`, \`requireAdmin\`, etc.):
$formatted_files

Without auth gates, these server actions can be invoked by unauthenticated or unauthorized users." \
        "For each file listed above:
1. Determine if the file should be public (no auth needed) or protected
2. If protected: add the appropriate auth gate at the top of each exported async function:
   - Chef-only actions: \`const user = await requireChef()\`
   - Any authenticated user: \`const user = await requireAuth()\`
   - Admin-only: \`await requireAdmin()\`
3. If intentionally public: add the file to the whitelist in \`scripts/regression-semantic.sh\` (the \`AUTH_WHITELIST\` array)
4. Use the tenant ID from the session, never from request input" \
        "1. Run \`bash scripts/regression-semantic.sh --quiet\` and confirm none of the listed files appear as missing auth gates
2. Run \`npx tsc --noEmit --skipLibCheck\` to verify no type errors from the added imports" \
        ".regression-semantic-report.md"
    done
  fi
}

# --------------------------------------------------------------------------
# 3. Process .regression-fragile-report.md (CRIT and HIGH only)
# --------------------------------------------------------------------------

process_fragile_report() {
  [[ -f "$FRAGILE_REPORT" ]] || return 0

  echo -e "${BOLD}${CYAN}[FRAGILE REPORT]${NC} $FRAGILE_REPORT"

  # Parse the markdown table for CRIT and HIGH rows from the "Top Fragile Files" section
  # Format: | CRIT | `file` | commits | sessions | ... |
  while IFS= read -r line; do
    # Extract risk level and file from table row
    risk=$(echo "$line" | sed 's/^| *//;s/ *|.*//')
    file=$(echo "$line" | sed 's/^|[^|]*| *`//;s/` *|.*//')
    commits=$(echo "$line" | sed 's/^|[^|]*|[^|]*| *//;s/ *|.*//')

    # Skip rows without backtick-wrapped file paths (summary table, headers)
    if [[ "$line" != *'`'* ]]; then
      continue
    fi

    # Only process CRIT and HIGH, skip docs/config files
    if [[ "$risk" != "CRIT" && "$risk" != "HIGH" ]]; then
      continue
    fi

    # Skip non-code files (docs, config, etc.)
    if [[ "$file" == docs/* ]] || [[ "$file" == CLAUDE.md ]] || [[ "$file" == .gitignore ]] || [[ "$file" == package.json ]]; then
      continue
    fi

    slug="fragile-$(slugify "$risk")-$(slugify "$file")"
    local risk_lower=$(echo "$risk" | tr '[:upper:]' '[:lower:]')

    write_spec "$slug" \
      "Fragile file ($risk): $file" \
      "The file \`$file\` has been flagged as **$risk** risk in the fragile file analysis. It has $commits commits in the last 30 days, indicating high churn and instability. Frequently modified files are more likely to accumulate bugs, merge conflicts, and architectural drift." \
      "1. Review \`$file\` for:
   - Functions that are too long (>50 lines): extract into smaller, testable functions
   - Mixed concerns (UI + business logic, data fetching + rendering): separate into distinct modules
   - Missing or inadequate error handling
   - Dead code or commented-out blocks that should be removed
2. If the file lacks tests: add unit tests for the core exported functions
3. If the file has grown too large (>500 lines): consider splitting into focused modules
4. Document any non-obvious patterns with inline comments" \
      "1. Verify \`npx tsc --noEmit --skipLibCheck\` passes after changes
2. If tests were added, verify they pass: \`npx jest $file --passWithNoTests\`
3. Run \`bash scripts/regression-check.sh --quick\` to confirm no new regressions" \
      ".regression-fragile-report.md"

  done < <(grep -E '^\| (CRIT|HIGH) ' "$FRAGILE_REPORT" 2>/dev/null || true)
}

# --------------------------------------------------------------------------
# Run all processors
# --------------------------------------------------------------------------

echo -e "${BOLD}ChefFlow Regression -> Codex Spec Generator${NC}"
echo "================================================"
echo ""

# Check if any reports exist
report_count=0
[[ -f "$REGRESSION_REPORT" ]] && report_count=$((report_count + 1))
[[ -f "$SEMANTIC_REPORT" ]] && report_count=$((report_count + 1))
[[ -f "$FRAGILE_REPORT" ]] && report_count=$((report_count + 1))

if [[ "$report_count" -eq 0 ]]; then
  echo -e "${YELLOW}No regression reports found.${NC}"
  echo "Run these first:"
  echo "  bash scripts/regression-check.sh"
  echo "  bash scripts/regression-semantic.sh"
  echo "  bash scripts/regression-fragile.sh"
  exit 0
fi

echo -e "${DIM}Found $report_count regression report(s)${NC}"
echo ""

process_regression_report
process_semantic_report
process_fragile_report

# --------------------------------------------------------------------------
# Summary
# --------------------------------------------------------------------------

echo ""
echo "================================================"
TOTAL=$((GENERATED + SKIPPED))

if [[ "$GENERATED" -gt 0 ]]; then
  echo -e "${GREEN}${BOLD}Generated $GENERATED spec(s)${NC} ($SKIPPED skipped as duplicates)"
  echo -e "${DIM}Specs written to docs/specs/auto-repair/${NC}"
elif [[ "$SKIPPED" -gt 0 ]]; then
  echo -e "${YELLOW}No new specs${NC} ($SKIPPED already exist)"
else
  echo -e "${GREEN}No actionable findings to generate specs for.${NC}"
fi

if [[ "$GENERATED" -gt 0 ]]; then
  echo ""
  echo -e "${BOLD}Next steps:${NC}"
  echo "  1. Review specs:  bash $0 --list"
  echo "  2. Feed to Codex or overnight loop"
  echo "  3. After fixes:   bash $0 --clean"
fi
