// Interaction Layer — Partners Deep Tests
// Tests the full partners sub-tree beyond the basic hub.
//
// Routes covered:
//   /partners                    — partners hub (tested in file 26, extended here)
//   /partners/active             — active partners list
//   /partners/inactive           — inactive partners
//   /partners/events-generated   — events generated by partners
//   /partners/referral-performance — referral performance metrics
//   /partners/[id]               — individual partner detail
//   /partners/[id]/edit          — edit partner
//   /partners/[id]/report        — partner-specific report
//
// Uses chef storageState (interactions-chef project).

import { test, expect } from '../helpers/fixtures'

// ─── Partners Status Views ────────────────────────────────────────────────────

test.describe('Partners — Status Views', () => {
  const partnerStatusRoutes = [
    '/partners/active',
    '/partners/inactive',
    '/partners/events-generated',
    '/partners/referral-performance',
  ]

  for (const route of partnerStatusRoutes) {
    test(`${route} — loads without 500`, async ({ page }) => {
      const resp = await page.goto(route)
      await page.waitForLoadState('networkidle')
      expect(resp?.status()).not.toBe(500)
    })
  }

  test('/partners/active — shows active partners or empty state', async ({ page }) => {
    await page.goto('/partners/active')
    await page.waitForLoadState('networkidle')
    const bodyText = await page.locator('body').innerText()
    expect(bodyText.trim().length).toBeGreaterThan(20)
  })

  test('/partners/referral-performance — shows metrics or empty state', async ({ page }) => {
    await page.goto('/partners/referral-performance')
    await page.waitForLoadState('networkidle')
    const bodyText = await page.locator('body').innerText()
    expect(bodyText.trim().length).toBeGreaterThan(20)
  })

  test('/partners/active — no JS errors', async ({ page }) => {
    const errors: string[] = []
    page.on('pageerror', (err) => errors.push(err.message))
    await page.goto('/partners/active')
    await page.waitForLoadState('networkidle')
    expect(errors).toHaveLength(0)
  })

  test('/partners/events-generated — no JS errors', async ({ page }) => {
    const errors: string[] = []
    page.on('pageerror', (err) => errors.push(err.message))
    await page.goto('/partners/events-generated')
    await page.waitForLoadState('networkidle')
    expect(errors).toHaveLength(0)
  })

  test('Partner status views are tenant-scoped', async ({ page, seedIds }) => {
    await page.goto('/partners/active')
    await page.waitForLoadState('networkidle')
    const bodyText = await page.locator('body').innerText()
    expect(bodyText).not.toContain(seedIds.chefBId)
  })
})

// ─── Partner Detail ───────────────────────────────────────────────────────────

test.describe('Partners — Detail (via list click)', () => {
  test('Clicking first partner navigates to partner detail', async ({ page }) => {
    const errors: string[] = []
    page.on('pageerror', (err) => errors.push(err.message))

    await page.goto('/partners')
    await page.waitForLoadState('networkidle')

    const firstPartnerLink = page.locator('a[href*="/partners/"]').first()
    if (await firstPartnerLink.isVisible()) {
      await firstPartnerLink.click()
      await page.waitForLoadState('networkidle')
      expect(page.url()).toMatch(/\/partners\//)
    }

    expect(errors).toHaveLength(0)
  })

  test('Partner detail page does not 500 with seeded partner ID', async ({ page, seedIds }) => {
    // If there are no partners seeded, this gracefully falls through
    await page.goto('/partners')
    await page.waitForLoadState('networkidle')

    const firstLink = page
      .locator('a[href*="/partners/"]')
      .filter({
        hasNot: page.locator(
          '[href="/partners/active"], [href="/partners/inactive"], [href="/partners/new"]'
        ),
      })
      .first()

    if (await firstLink.isVisible()) {
      const href = await firstLink.getAttribute('href')
      if (href) {
        const resp = await page.goto(href)
        await page.waitForLoadState('networkidle')
        expect(resp?.status()).not.toBe(500)
      }
    }
  })
})

// ─── Partner Add / Edit ───────────────────────────────────────────────────────

test.describe('Partners — Create & Edit', () => {
  test('/partners/new — loads and shows form', async ({ page }) => {
    const resp = await page.goto('/partners/new')
    await page.waitForLoadState('networkidle')
    expect(resp?.status()).not.toBe(500)
    const bodyText = await page.locator('body').innerText()
    expect(bodyText.trim().length).toBeGreaterThan(20)
  })

  test('/partners/new — has name/company field', async ({ page }) => {
    await page.goto('/partners/new')
    await page.waitForLoadState('networkidle')
    const nameField = page
      .getByLabel(/name|company|partner/i)
      .first()
      .or(page.locator('input[type="text"]').first())
    const isVisible = await nameField.isVisible().catch(() => false)
    // Informational
    const _ = isVisible
  })

  test('/partners/new — no JS errors', async ({ page }) => {
    const errors: string[] = []
    page.on('pageerror', (err) => errors.push(err.message))
    await page.goto('/partners/new')
    await page.waitForLoadState('networkidle')
    expect(errors).toHaveLength(0)
  })

  test('/partners/new — empty submit shows validation', async ({ page }) => {
    await page.goto('/partners/new')
    await page.waitForLoadState('networkidle')
    const saveBtn = page.getByRole('button', { name: /save|create|add/i }).first()
    if (await saveBtn.isVisible()) {
      await saveBtn.click()
      await page.waitForTimeout(800)
    }
    // Should stay on /partners/new or show error — not create blank partner
    const url = page.url()
    expect(url).not.toMatch(/\/partners\/[0-9a-f-]{36}$/)
  })
})

// ─── Partner Report ───────────────────────────────────────────────────────────

test.describe('Partners — Reports', () => {
  test('Partner report page is accessible from partner detail', async ({ page }) => {
    const errors: string[] = []
    page.on('pageerror', (err) => errors.push(err.message))

    await page.goto('/partners')
    await page.waitForLoadState('networkidle')

    // Try to find a link to a partner report page
    const reportLink = page.locator('a[href*="/partners/"][href*="/report"]').first()

    if (await reportLink.isVisible()) {
      await reportLink.click()
      await page.waitForLoadState('networkidle')
      expect(page.url()).toMatch(/\/partners\/.*\/report/)
    }

    expect(errors).toHaveLength(0)
  })

  test('Referral performance page shows metrics or empty state', async ({ page }) => {
    await page.goto('/partners/referral-performance')
    await page.waitForLoadState('networkidle')
    const hasContent = await page
      .getByText(/referral|performance|commission|event|revenue|partner/i)
      .first()
      .isVisible()
      .catch(() => false)
    const bodyText = await page.locator('body').innerText()
    expect(bodyText.trim().length).toBeGreaterThan(20)
    const _ = hasContent
  })
})

// ─── Partners — Cross Navigation ──────────────────────────────────────────────

test.describe('Partners — Cross Navigation', () => {
  test('All partner status routes load without 500', async ({ page }) => {
    const routes = [
      '/partners',
      '/partners/active',
      '/partners/inactive',
      '/partners/events-generated',
      '/partners/referral-performance',
      '/partners/new',
    ]
    for (const route of routes) {
      const resp = await page.goto(route)
      await page.waitForLoadState('networkidle')
      expect(resp?.status(), `${route} should not 500`).not.toBe(500)
    }
  })

  test('Navigating through partner pages produces no JS errors', async ({ page }) => {
    const errors: string[] = []
    page.on('pageerror', (err) => errors.push(err.message))

    for (const route of ['/partners', '/partners/active', '/partners/referral-performance']) {
      await page.goto(route)
      await page.waitForLoadState('networkidle')
    }

    expect(errors).toHaveLength(0)
  })
})
