'use client'

import { useState, useTransition } from 'react'
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { updatePrintPreferences, type PrintPreferences } from '@/lib/print/actions'
import { toast } from 'sonner'

type Props = {
  initialPrefs: PrintPreferences
}

export function PrintSettingsForm({ initialPrefs }: Props) {
  const [prefs, setPrefs] = useState<PrintPreferences>(initialPrefs)
  const [isPending, startTransition] = useTransition()

  function handleSave() {
    const previous = { ...prefs }
    startTransition(async () => {
      try {
        const result = await updatePrintPreferences(prefs)
        if (!result.success) {
          setPrefs(previous)
          toast.error(result.error ?? 'Failed to save print preferences')
        } else {
          toast.success('Print preferences saved')
        }
      } catch {
        setPrefs(previous)
        toast.error('Failed to save print preferences')
      }
    })
  }

  return (
    <div className="space-y-6">
      {/* Attribution */}
      <Card className="p-6 space-y-4">
        <div>
          <h2 className="text-lg font-semibold">Document Attribution</h2>
          <p className="text-stone-400 text-sm mt-1">
            A subtle &ldquo;Generated by&rdquo; line at the bottom of every document. Shows who
            printed it and when — useful for tracking in kitchens with multiple staff.
          </p>
        </div>

        <label className="flex items-center gap-3 cursor-pointer">
          <input
            type="checkbox"
            checked={prefs.show_attribution}
            onChange={(e) => setPrefs({ ...prefs, show_attribution: e.target.checked })}
            className="h-4 w-4 rounded border-stone-600 bg-stone-800 text-brand-500 focus:ring-brand-500"
          />
          <span className="text-sm">Show &ldquo;Generated by&rdquo; on documents</span>
        </label>

        {prefs.show_attribution && (
          <div>
            <label className="block text-sm font-medium text-stone-300 mb-1">
              Attribution name
            </label>
            <input
              type="text"
              value={prefs.attribution_name ?? ''}
              onChange={(e) => setPrefs({ ...prefs, attribution_name: e.target.value || null })}
              placeholder="Leave blank to use your business name"
              className="w-full px-3 py-2 bg-stone-800 border border-stone-700 rounded-lg text-sm text-stone-100 placeholder:text-stone-500 focus:outline-none focus:ring-1 focus:ring-brand-500"
            />
            <p className="text-xs text-stone-500 mt-1">
              Example: &ldquo;Generated by Chef David&rsquo;s Kitchen · Feb 28, 2026, 3:45 PM&rdquo;
            </p>
          </div>
        )}
      </Card>

      {/* Default Print Mode */}
      <Card className="p-6 space-y-4">
        <div>
          <h2 className="text-lg font-semibold">Default Print Mode</h2>
          <p className="text-stone-400 text-sm mt-1">
            Sets the default paper format for browser print pages. You can always override per-page
            with the <code className="text-stone-300">?mode=thermal</code> URL parameter.
          </p>
        </div>

        <div className="space-y-2">
          {(
            [
              {
                value: 'standard',
                label: 'Standard paper',
                desc: 'Letter / A4 — inkjet, laser printers',
              },
              {
                value: 'thermal-80',
                label: '80mm thermal',
                desc: '3 1/8" receipt paper — Epson, Star, Bixolon',
              },
              {
                value: 'thermal-58',
                label: '58mm thermal',
                desc: '2 1/4" mobile/budget receipt printers',
              },
            ] as const
          ).map((opt) => (
            <label
              key={opt.value}
              className="flex items-start gap-3 cursor-pointer p-2 rounded-lg hover:bg-stone-800/50"
            >
              <input
                type="radio"
                name="print-mode"
                checked={prefs.default_print_mode === opt.value}
                onChange={() => setPrefs({ ...prefs, default_print_mode: opt.value })}
                className="mt-0.5 h-4 w-4 border-stone-600 bg-stone-800 text-brand-500 focus:ring-brand-500"
              />
              <div>
                <span className="text-sm font-medium">{opt.label}</span>
                <p className="text-xs text-stone-500">{opt.desc}</p>
              </div>
            </label>
          ))}
        </div>
      </Card>

      {/* Custom Footer */}
      <Card className="p-6 space-y-4">
        <div>
          <h2 className="text-lg font-semibold">Custom Footer</h2>
          <p className="text-stone-400 text-sm mt-1">
            Replace the default &ldquo;ChefFlow — Printed [date]&rdquo; footer with your own text.
            Great for branding or adding a tagline to printed documents.
          </p>
        </div>

        <div>
          <input
            type="text"
            value={prefs.custom_footer ?? ''}
            onChange={(e) => setPrefs({ ...prefs, custom_footer: e.target.value || null })}
            placeholder="Leave blank for default footer"
            className="w-full px-3 py-2 bg-stone-800 border border-stone-700 rounded-lg text-sm text-stone-100 placeholder:text-stone-500 focus:outline-none focus:ring-1 focus:ring-brand-500"
          />
          <p className="text-xs text-stone-500 mt-1">
            Example: &ldquo;David&rsquo;s Artisan Kitchen — Ops for Artists&rdquo;
          </p>
        </div>
      </Card>

      {/* Save */}
      <div className="flex justify-end">
        <Button variant="primary" onClick={handleSave} disabled={isPending}>
          {isPending ? 'Saving...' : 'Save Preferences'}
        </Button>
      </div>
    </div>
  )
}
