export type Feature = {
  id: string
  name: string
  description: string
  category: 'pipeline' | 'culinary' | 'clients' | 'finance' | 'operations'
  classification:
    | 'chef_standard'
    | 'chef_privileged'
    | 'internal_admin'
    | 'developer_tool'
    | 'internal_only'
  entryPoint?: {
    type: 'route' | 'component' | 'service' | 'none'
    value?: string
  }
  visibility: 'visible' | 'hidden' | 'gated' | 'internal'
  status: 'complete' | 'partial' | 'stub'
}

export const FEATURE_REGISTRY: Feature[] = [
  // Pipeline
  {
    id: 'event-workspace',
    name: 'Event Workspace',
    description: 'Primary event list and detail workspace with operational tabs and status slices.',
    category: 'pipeline',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/events' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'event-intake-builders',
    name: 'Event Intake Builders',
    description: 'Structured event creation flows including manual, text-parsed, and wizard entry.',
    category: 'pipeline',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/events/new' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'event-run-of-show',
    name: 'Event Run Of Show',
    description:
      'Event execution views for schedules, DOP mobile, guest cards, KDS, and service-time coordination.',
    category: 'pipeline',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/events/[id]/schedule' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'event-closeout',
    name: 'Event Closeout',
    description:
      'Post-service wrap-up covering AAR, debrief, invoice, receipts, financial review, and split billing.',
    category: 'pipeline',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/events/[id]/close-out' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'inquiry-pipeline',
    name: 'Inquiry Pipeline',
    description:
      'Inbound inquiry management with lifecycle states, detail views, and conversion paths.',
    category: 'pipeline',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/inquiries' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'quote-workbench',
    name: 'Quote Workbench',
    description: 'Quote creation, editing, state filters, and client send/view tracking.',
    category: 'pipeline',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/quotes' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'rate-card',
    name: 'Rate Card',
    description:
      'Base pricing and package modeling surface for offer design and quoting consistency.',
    category: 'pipeline',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/rate-card' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'calls-consultations',
    name: 'Calls And Consultations',
    description:
      'Call scheduling, prep, agenda capture, and outcome logging for sales conversations.',
    category: 'pipeline',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/calls' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'website-leads',
    name: 'Website Leads',
    description:
      'Captured website leads with claim, dismiss, and pipeline follow-through behaviors.',
    category: 'pipeline',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/leads' },
    visibility: 'hidden',
    status: 'complete',
  },
  {
    id: 'guest-lead-pipeline',
    name: 'Guest Lead Pipeline',
    description: 'Guest-originated lead tracking with conversion and archive flows.',
    category: 'pipeline',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/guest-leads' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'prospecting-engine',
    name: 'Prospecting Engine',
    description:
      'Outbound prospecting system with queue, scripts, AI scrub, clusters, and conversion tools.',
    category: 'pipeline',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/prospecting' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'proposals-addons',
    name: 'Proposals And Add Ons',
    description: 'Proposal builder, add-on packaging, and reusable proposal template management.',
    category: 'pipeline',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/proposals' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'contracts-approvals',
    name: 'Contracts And Approvals',
    description:
      'Contract records, template linkage, and client-side approval or acceptance touchpoints.',
    category: 'pipeline',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/contracts' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'referral-partner-management',
    name: 'Referral Partner Management',
    description: 'Partner directory with activity, reports, and referral-generated event tracking.',
    category: 'pipeline',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/partners' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'marketplace-command-center',
    name: 'Marketplace Command Center',
    description:
      'Multi-platform marketplace lead management, rebooking ROI, and booking follow-up control.',
    category: 'pipeline',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/marketplace' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'marketplace-capture-ingestion',
    name: 'Marketplace Capture And Ingestion',
    description:
      'Live capture and ingestion utilities for marketplace opportunities and external listing data.',
    category: 'pipeline',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/marketplace/capture' },
    visibility: 'hidden',
    status: 'partial',
  },
  {
    id: 'public-booking-funnels',
    name: 'Public Booking Funnels',
    description:
      'Public booking pages, thank-you states, and campaign-specific booking entry points.',
    category: 'pipeline',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/book' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'embed-inquiry-widget',
    name: 'Embed Inquiry Widget',
    description: 'Embeddable inquiry form experience for external chef websites and landing pages.',
    category: 'pipeline',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/embed/inquiry/[chefId]' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'waitlist-management',
    name: 'Waitlist Management',
    description: 'Date-based waitlist handling for clients who want newly opened availability.',
    category: 'pipeline',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/waitlist' },
    visibility: 'hidden',
    status: 'complete',
  },

  // Culinary
  {
    id: 'culinary-home',
    name: 'Culinary Home',
    description:
      'Chef culinary hub that anchors menus, recipes, ingredients, prep, and costing workflows.',
    category: 'culinary',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/culinary' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'culinary-ideation-board',
    name: 'Culinary Ideation Board',
    description:
      'Creative culinary composition board for ingredient words, inspiration, and dish ideation.',
    category: 'culinary',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/culinary-board' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'menu-management',
    name: 'Menu Management',
    description: 'Menu library, drafts, approvals, editor, upload flow, and tasting menu surfaces.',
    category: 'culinary',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/menus' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'menu-engineering',
    name: 'Menu Engineering',
    description:
      'Dish indexing, menu engineering, scaling, and substitution planning for menu performance.',
    category: 'culinary',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/culinary/dish-index' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'recipe-library',
    name: 'Recipe Library',
    description:
      'Recipe catalog with detail pages, edits, tags, drafts, and dietary or seasonal organization.',
    category: 'culinary',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/recipes' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'recipe-capture-import',
    name: 'Recipe Capture And Import',
    description: 'Recipe sprinting, brain-dump capture, photo logging, and import workflows.',
    category: 'culinary',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/recipes/sprint' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'ingredient-catalog',
    name: 'Ingredient Catalog',
    description:
      'Ingredient database with vendor notes, seasonal availability, and receipt-scan support.',
    category: 'culinary',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/culinary/ingredients' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'ingredient-price-engine',
    name: 'Ingredient Price Engine',
    description:
      'Chef-facing store price engine for tracked products, coverage, freshness, and store-specific pricing.',
    category: 'culinary',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/prices' },
    visibility: 'visible',
    status: 'partial',
  },
  {
    id: 'costing-suite',
    name: 'Costing Suite',
    description:
      'Recipe, menu, and food-cost calculators for pricing dishes and menus against current inputs.',
    category: 'culinary',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/culinary/costing' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'culinary-components',
    name: 'Culinary Components',
    description:
      'Sub-recipe and component system for stocks, sauces, garnishes, ferments, and substitutions.',
    category: 'culinary',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/culinary/components' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'prep-planning',
    name: 'Prep Planning',
    description: 'Prep boards, shopping lists, and timeline planning for event and menu execution.',
    category: 'culinary',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/culinary/prep' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'vendor-management',
    name: 'Vendor Management',
    description: 'Vendor records, vendor invoices, and cross-vendor price comparison workflows.',
    category: 'culinary',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/vendors' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'inventory-procurement',
    name: 'Inventory And Procurement',
    description:
      'Inventory, counts, audits, locations, transactions, procurement, and purchase-order control.',
    category: 'culinary',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/inventory' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'food-cost-operations',
    name: 'Food Cost Operations',
    description:
      'Food-cost operational views for waste, demand, expiry, staff meals, and vendor invoice monitoring.',
    category: 'culinary',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/food-cost' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'kitchen-stations-kds',
    name: 'Kitchen Stations And KDS',
    description:
      'Kitchen execution tools including kitchen mode, stations, clipboards, order sheets, and KDS.',
    category: 'culinary',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/kitchen' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'meal-prep-operations',
    name: 'Meal Prep Operations',
    description:
      'Recurring meal prep program management with deliveries, containers, and client programs.',
    category: 'culinary',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/meal-prep' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'nutrition-analysis',
    name: 'Nutrition Analysis',
    description: 'Menu-level nutrition analysis with chef overrides and proposal display controls.',
    category: 'culinary',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/nutrition/[menuId]' },
    visibility: 'gated',
    status: 'complete',
  },
  {
    id: 'guest-crm',
    name: 'Guest CRM',
    description: 'Guest directory, guest details, reservations, comp tracking, and guest tagging.',
    category: 'culinary',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/guests' },
    visibility: 'hidden',
    status: 'complete',
  },

  // Clients
  {
    id: 'client-crm',
    name: 'Client CRM',
    description:
      'Client directory, detail views, and status slices for active, inactive, VIP, and duplicate records.',
    category: 'clients',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/clients' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'client-preferences-intake',
    name: 'Client Preferences And Intake',
    description:
      'Preference tracking for allergies, dietary needs, favorites, and shared intake forms.',
    category: 'clients',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/clients/preferences' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'client-communications',
    name: 'Client Communications',
    description:
      'Client notes, follow-ups, touchpoints, inbox links, and chat-connected relationship management.',
    category: 'clients',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/clients/communication' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'client-insights',
    name: 'Client Insights',
    description:
      'Top-client, frequency, at-risk, and lifetime-value-oriented client intelligence surfaces.',
    category: 'clients',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/clients/insights' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'recurring-service-programs',
    name: 'Recurring Service Programs',
    description:
      'Recurring service management for repeat clients and repeat billing or booking patterns.',
    category: 'clients',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/clients/recurring' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'gift-cards-vouchers',
    name: 'Gift Cards And Vouchers',
    description:
      'Gift-card issuance, client-side purchase flows, voucher sending, and redemption tracking.',
    category: 'clients',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/clients/gift-cards' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'cooking-classes',
    name: 'Cooking Classes',
    description:
      'Class program management with class definitions, registrations, and chef-side teaching offers.',
    category: 'clients',
    classification: 'chef_standard',
    entryPoint: { type: 'component', value: 'components/classes/class-list.tsx' },
    visibility: 'hidden',
    status: 'partial',
  },
  {
    id: 'client-portal-events',
    name: 'Client Portal Events',
    description:
      'Client-side event workspace for proposals, payments, invoices, contracts, menu choices, and summaries.',
    category: 'clients',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/my-events' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'client-portal-account',
    name: 'Client Portal Account',
    description: 'Client-facing profile, quotes, inquiries, chat, and spending surfaces.',
    category: 'clients',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/my-profile' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'dinner-circles-social-hub',
    name: 'Dinner Circles Social Hub',
    description:
      'Group and social hub system spanning chef circles, client my-hub pages, and guest-facing join pages.',
    category: 'clients',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/circles' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'loyalty-rewards',
    name: 'Loyalty Rewards',
    description: 'Points, referrals, reward catalog, redemption, and client reward history.',
    category: 'clients',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/loyalty' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'monthly-raffle',
    name: 'Monthly Raffle',
    description:
      'Monthly raffle program for client participation and chef-side reward gamification.',
    category: 'clients',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/loyalty/raffle' },
    visibility: 'gated',
    status: 'complete',
  },
  {
    id: 'feedback-surveys',
    name: 'Feedback And Surveys',
    description:
      'Post-event survey dispatch, feedback dashboards, and public token-based survey collection.',
    category: 'clients',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/feedback' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'reviews-testimonials-reputation',
    name: 'Reviews Testimonials And Reputation',
    description:
      'Internal and external review aggregation, testimonial moderation, and brand-mention monitoring.',
    category: 'clients',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/reviews' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'public-chef-marketplace',
    name: 'Public Chef Marketplace',
    description:
      'Public chef discovery, chef profiles, public inquiry flows, and chef-specific gift-card pages.',
    category: 'clients',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/chefs' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'public-food-discovery-directory',
    name: 'Public Food Discovery Directory',
    description:
      'Public business discovery directory for operators, restaurants, trucks, bakeries, and local food listings.',
    category: 'clients',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/discover' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'public-brand-marketing-site',
    name: 'Public Brand Marketing Site',
    description:
      'Public marketing pages for the platform, including homepage, operators page, compare, trust, and legal surfaces.',
    category: 'clients',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'network-community',
    name: 'Network And Community',
    description:
      'Chef community feed, channels, collaborations, bridges, notifications, and saved content.',
    category: 'clients',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/network' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'community-template-exchange',
    name: 'Community Template Exchange',
    description: 'Community publishing and import of shared templates across chefs.',
    category: 'clients',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/community/templates' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'mentorship-exchange',
    name: 'Mentorship Exchange',
    description:
      'Mentor discovery, mentorship profiles, and connection management for peer learning inside the community layer.',
    category: 'clients',
    classification: 'chef_standard',
    entryPoint: { type: 'component', value: 'components/community/mentorship-dashboard.tsx' },
    visibility: 'hidden',
    status: 'partial',
  },
  {
    id: 'marketing-campaigns',
    name: 'Marketing Campaigns',
    description: 'Push dinners, sequences, templates, and email-oriented campaign management.',
    category: 'clients',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/marketing' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'social-publishing',
    name: 'Social Publishing',
    description:
      'Social planner, media vault, platform connections, social templates, and event-post composition.',
    category: 'clients',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/social' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'content-pipeline',
    name: 'Content Pipeline',
    description:
      'Structured content workflow for drafts, review queues, scheduling, and published items.',
    category: 'clients',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/content' },
    visibility: 'visible',
    status: 'partial',
  },
  {
    id: 'portfolio-public-assets',
    name: 'Portfolio And Public Assets',
    description:
      'Portfolio, public profile, highlights, and showcase assets used for external presentation.',
    category: 'clients',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/portfolio' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'favorite-chef-curation',
    name: 'Favorite Chef Curation',
    description:
      'Chef-curated roster of culinary inspirations used for profile storytelling, Remy context, and social sharing.',
    category: 'clients',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/settings/favorite-chefs' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'guest-analytics',
    name: 'Guest Analytics',
    description:
      'Repeat-guest, dinner-group, and guest-conversion analytics derived from attendance history.',
    category: 'clients',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/guest-analytics' },
    visibility: 'hidden',
    status: 'complete',
  },
  {
    id: 'charity-programs',
    name: 'Charity Programs',
    description:
      'Charity aggregation and volunteer-hour tracking tied to chef goodwill and community contribution.',
    category: 'clients',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/charity' },
    visibility: 'visible',
    status: 'partial',
  },
  {
    id: 'cannabis-vertical',
    name: 'Cannabis Vertical',
    description:
      'Cannabis tiering, guest invites, ledgering, compliance, handbook, RSVPs, and control-packet tooling.',
    category: 'clients',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/cannabis' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'public-beta-program',
    name: 'Public Beta Program',
    description: 'Public beta signup and beta survey collection surfaces for early users.',
    category: 'clients',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/beta' },
    visibility: 'visible',
    status: 'complete',
  },

  // Finance
  {
    id: 'finance-home',
    name: 'Finance Home',
    description: 'Finance landing surfaces and overview cards for the business financial state.',
    category: 'finance',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/financials' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'expense-management',
    name: 'Expense Management',
    description:
      'Expense capture, quick expense entry, receipt scanning, and expense detail management.',
    category: 'finance',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/expenses' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'invoicing-billing',
    name: 'Invoicing And Billing',
    description: 'Invoice management, recurring invoices, retainers, and billing-status tracking.',
    category: 'finance',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/finance/invoices' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'payments-collections',
    name: 'Payments And Collections',
    description:
      'Deposits, installments, refunds, failed payments, disputes, and split-payment collection workflows.',
    category: 'finance',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/finance/payments' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'payouts-reconciliation',
    name: 'Payouts And Reconciliation',
    description: 'Chef payouts, manual payouts, bank-feed views, and reconciliation tooling.',
    category: 'finance',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/finance/payouts' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'ledger-accounting',
    name: 'Ledger And Accounting',
    description: 'Ledger views, transaction logs, adjustments, and owner-draw accounting support.',
    category: 'finance',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/finance/ledger' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'finance-reporting',
    name: 'Finance Reporting',
    description:
      'Revenue, profit, expense, and year-to-date reporting plus forecast and cash-flow surfaces.',
    category: 'finance',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/finance/reporting' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'tax-compliance',
    name: 'Tax Compliance',
    description:
      'Sales-tax, quarterly, year-end, 1099, depreciation, retirement, and related tax workflows.',
    category: 'finance',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/finance/tax' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'payroll-contractors',
    name: 'Payroll And Contractors',
    description: 'Payroll runs, employee records, contractor support, and payroll filing surfaces.',
    category: 'finance',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/finance/payroll' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'goals-planning',
    name: 'Goals And Planning',
    description: 'Financial and growth goals, history, revenue path, and break-even planning.',
    category: 'finance',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/goals' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'consulting-toolkit',
    name: 'Consulting Toolkit',
    description:
      'Pricing and offer-building playbook with consulting calculators and package framing support.',
    category: 'finance',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/consulting' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'commerce-register',
    name: 'Commerce Register',
    description: 'POS register, checkout, cash drawer handling, and active selling workflows.',
    category: 'finance',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/commerce/register' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'commerce-catalog',
    name: 'Commerce Catalog',
    description:
      'Product catalog, promotions, parity checks, and virtual-terminal selling support.',
    category: 'finance',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/commerce/products' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'commerce-service-modes',
    name: 'Commerce Service Modes',
    description:
      'Orders, schedules, table service, and order-ahead or service-mode commerce flows.',
    category: 'finance',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/commerce/orders' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'commerce-reporting-settlements',
    name: 'Commerce Reporting And Settlements',
    description:
      'Sales detail, shift reporting, observability, reconciliation, and settlement tracking.',
    category: 'finance',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/commerce/reports' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'food-operator-retail-ops',
    name: 'Food Operator Retail Ops',
    description:
      'Schema-backed operator workflows for bakery production, truck schedules, wholesale orders, display cases, and order-ahead retail programs.',
    category: 'operations',
    classification: 'chef_privileged',
    entryPoint: { type: 'none' },
    visibility: 'hidden',
    status: 'stub',
  },

  // Operations
  {
    id: 'dashboard-command-center',
    name: 'Dashboard Command Center',
    description:
      'Primary dashboard shell, widget system, and command-center overview of the chef business.',
    category: 'operations',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/dashboard' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'activity-queue',
    name: 'Activity And Queue',
    description:
      'Activity log, retrace views, and priority queue with snoozing and urgency segmentation.',
    category: 'operations',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/queue' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'daily-ops-planner',
    name: 'Daily Ops Planner',
    description: 'Daily swim-lane planner for admin, prep, creative, and relationship work.',
    category: 'operations',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/daily' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'morning-briefing',
    name: 'Morning Briefing',
    description:
      'Owner-oriented morning overview, shift handoff notes, and pre-service prep coordination.',
    category: 'operations',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/briefing' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'calendar-schedule',
    name: 'Calendar And Schedule',
    description:
      'Calendar day, week, year, share, and schedule-planning surfaces for service timing.',
    category: 'operations',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/calendar' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'availability-broadcaster',
    name: 'Availability Broadcaster',
    description:
      'Marketplace-blocking checklist and availability sharing workflow for confirmed bookings.',
    category: 'operations',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/availability' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'travel-production',
    name: 'Travel And Production',
    description: 'Travel route planning and production calendar surfaces for operational movement.',
    category: 'operations',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/travel' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'operations-equipment',
    name: 'Operations And Equipment',
    description: 'Operations hub, equipment inventory, maintenance, and kitchen-rental tracking.',
    category: 'operations',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/operations' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'staff-management',
    name: 'Staff Management',
    description:
      'Staff directory, availability, schedules, labor views, clocking, and live activity monitoring.',
    category: 'operations',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/staff' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'team-collaboration',
    name: 'Team Collaboration',
    description:
      'Multi-chef team membership, permissions, and tenant-level collaborator access control.',
    category: 'operations',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/team' },
    visibility: 'hidden',
    status: 'complete',
  },
  {
    id: 'tasks-stations',
    name: 'Tasks And Stations',
    description: 'Task board, templates, Gantt views, VA tasks, and station-level operating tools.',
    category: 'operations',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/tasks' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'notifications-center',
    name: 'Notifications Center',
    description:
      'Notification history, read-state management, and notification preference support.',
    category: 'operations',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/notifications' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'inbox-and-chat',
    name: 'Inbox And Chat',
    description:
      'Unified inbox, history scan, triage surfaces, and chat conversations across business workflows.',
    category: 'operations',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/inbox' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'documents-workspace',
    name: 'Documents Workspace',
    description:
      'Chef-facing document workspace with event phases, search, and document pack access.',
    category: 'operations',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/documents' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'pdf-document-services',
    name: 'PDF Document Services',
    description:
      'Server-side document generation for quotes, invoices, receipts, grocery packs, FOH, and commerce receipts.',
    category: 'operations',
    classification: 'internal_only',
    entryPoint: { type: 'service', value: 'app/api/documents/*' },
    visibility: 'internal',
    status: 'complete',
  },
  {
    id: 'document-intelligence',
    name: 'Document Intelligence',
    description:
      'Document parsing, intelligence jobs, comments, and snapshot processing for uploaded materials.',
    category: 'operations',
    classification: 'internal_only',
    entryPoint: { type: 'service', value: 'document_intelligence_*' },
    visibility: 'internal',
    status: 'partial',
  },
  {
    id: 'analytics-hub',
    name: 'Analytics Hub',
    description: 'Business analytics, funnel analysis, benchmarks, demand, and referral reporting.',
    category: 'operations',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/analytics' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'custom-reports',
    name: 'Custom Reports',
    description:
      'Pro-gated custom reporting surface for saved and ad hoc analytical reporting workflows.',
    category: 'operations',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/reports' },
    visibility: 'gated',
    status: 'complete',
  },
  {
    id: 'insights-suite',
    name: 'Insights Suite',
    description: 'Clientele insights, daily report surfaces, and deeper business-pattern analysis.',
    category: 'operations',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/insights' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'intelligence-hub',
    name: 'Intelligence Hub',
    description:
      'Deterministic intelligence engines for forecasting, anomaly detection, and guided operator decisions.',
    category: 'operations',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/intelligence' },
    visibility: 'gated',
    status: 'complete',
  },
  {
    id: 'remy-ai-platform',
    name: 'Remy AI Platform',
    description: 'Chef, client, and public Remy chat surfaces plus streaming and warmup APIs.',
    category: 'operations',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/remy' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'founder-command-hub',
    name: 'Founder Command Hub',
    description: 'Founder-only Remy control surface exposed through the hidden commands page.',
    category: 'operations',
    classification: 'developer_tool',
    entryPoint: { type: 'route', value: '/commands' },
    visibility: 'gated',
    status: 'complete',
  },
  {
    id: 'settings-control-plane',
    name: 'Settings Control Plane',
    description:
      'Chef settings shell for profile, pricing, templates, devices, professional, protection, and system preferences.',
    category: 'operations',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/settings' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'growth-hub',
    name: 'Growth Hub',
    description:
      'Cross-feature hub that organizes growth-oriented tools across marketing, analytics, goals, portfolio, and community.',
    category: 'operations',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/growth' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'module-gating-and-focus-mode',
    name: 'Module Gating And Focus Mode',
    description: 'Per-chef module visibility, focus mode, and navigation personalization controls.',
    category: 'operations',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/settings/modules' },
    visibility: 'hidden',
    status: 'complete',
  },
  {
    id: 'automations-touchpoints',
    name: 'Automations And Touchpoints',
    description:
      'Built-in and custom automations, execution logs, and touchpoint rule configuration.',
    category: 'operations',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/settings/automations' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'integrations-webhooks',
    name: 'Integrations And Webhooks',
    description:
      'Connection management for Gmail, Stripe, social providers, webhooks, API keys, and platform integrations.',
    category: 'operations',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/settings/integrations' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'safety-protection',
    name: 'Safety And Protection',
    description:
      'Incident logs, claims, certifications, HACCP, insurance, backup-chef coverage, and business protection workflows for operational resilience.',
    category: 'operations',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/safety/incidents' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'auth-and-onboarding',
    name: 'Auth And Onboarding',
    description:
      'Sign-in, role selection, password recovery, client signup, and chef onboarding flows.',
    category: 'operations',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/auth/signin' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'help-guidance',
    name: 'Help And Guidance',
    description: 'Help center, contextual page-help overlays, and guided support content.',
    category: 'operations',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/help' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'import-pipelines',
    name: 'Import Pipelines',
    description:
      'CSV, recipe, menu, and history import workflows for getting legacy data into the platform.',
    category: 'operations',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/import' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'wix-processing',
    name: 'Wix Processing',
    description: 'Wix submission ingestion, status review, and follow-on inquiry creation support.',
    category: 'operations',
    classification: 'internal_only',
    entryPoint: { type: 'route', value: '/wix-submissions' },
    visibility: 'internal',
    status: 'complete',
  },
  {
    id: 'tokenized-service-pages',
    name: 'Tokenized Service Pages',
    description:
      'Token-gated proposal, review, tip, worksheet, event-guest, intake, availability, and share pages.',
    category: 'operations',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/proposal/[token]' },
    visibility: 'gated',
    status: 'complete',
  },
  {
    id: 'mobile-portal-surfaces',
    name: 'Mobile Portal Surfaces',
    description:
      'Slim mobile chef and client portal views for lightweight dashboard and event access.',
    category: 'operations',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/mobile/chef/[slug]/dashboard' },
    visibility: 'hidden',
    status: 'partial',
  },
  {
    id: 'partner-portal',
    name: 'Partner Portal',
    description:
      'Partner-facing dashboard, profile, preview, event, and location management surfaces.',
    category: 'operations',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/partner/dashboard' },
    visibility: 'gated',
    status: 'complete',
  },
  {
    id: 'kiosk-device-fleet',
    name: 'Kiosk Device Fleet',
    description:
      'Device pairing, staff PIN sessions, inquiry kiosk, order kiosk, and heartbeat-driven device control.',
    category: 'operations',
    classification: 'chef_privileged',
    entryPoint: { type: 'route', value: '/kiosk' },
    visibility: 'visible',
    status: 'complete',
  },
  {
    id: 'public-staff-experience',
    name: 'Public Staff Experience',
    description: 'Staff login, public staff portal entry, and staff-specific dashboard surfaces.',
    category: 'operations',
    classification: 'chef_standard',
    entryPoint: { type: 'route', value: '/staff-login' },
    visibility: 'gated',
    status: 'complete',
  },
  {
    id: 'public-demo-mode',
    name: 'Public Demo Mode',
    description:
      'Demo account switcher, demo data controls, and demo-tier toggling for walkthrough environments.',
    category: 'operations',
    classification: 'developer_tool',
    entryPoint: { type: 'route', value: '/demo' },
    visibility: 'gated',
    status: 'complete',
  },
  {
    id: 'mission-control-launcher',
    name: 'Mission Control Launcher',
    description:
      'Standalone desktop launcher with Gustav AI, quick-login automation, and local control panels.',
    category: 'operations',
    classification: 'developer_tool',
    entryPoint: { type: 'service', value: 'scripts/launcher/index.html' },
    visibility: 'internal',
    status: 'complete',
  },
  {
    id: 'admin-platform-overview',
    name: 'Admin Platform Overview',
    description: 'Platform-admin overview and pulse surfaces for broad operational control.',
    category: 'operations',
    classification: 'internal_admin',
    entryPoint: { type: 'route', value: '/admin' },
    visibility: 'internal',
    status: 'complete',
  },
  {
    id: 'admin-user-event-ops',
    name: 'Admin User And Event Ops',
    description:
      'Platform-admin control over chefs, clients, events, inquiries, and cannabis oversight.',
    category: 'operations',
    classification: 'internal_admin',
    entryPoint: { type: 'route', value: '/admin/users' },
    visibility: 'internal',
    status: 'complete',
  },
  {
    id: 'admin-directory-moderation',
    name: 'Admin Directory Moderation',
    description:
      'Admin management of directory records, listings, referral partners, and related enrichment flows.',
    category: 'operations',
    classification: 'internal_admin',
    entryPoint: { type: 'route', value: '/admin/directory' },
    visibility: 'internal',
    status: 'complete',
  },
  {
    id: 'admin-communications-social',
    name: 'Admin Communications And Social',
    description:
      'Admin-side communications, conversations, group moderation, social oversight, and feedback review.',
    category: 'operations',
    classification: 'internal_admin',
    entryPoint: { type: 'route', value: '/admin/communications' },
    visibility: 'internal',
    status: 'complete',
  },
  {
    id: 'admin-financial-health-ops',
    name: 'Admin Financial And Health Ops',
    description:
      'Admin financials, reconciliation, system health, presence, notifications, and silent-failure review.',
    category: 'operations',
    classification: 'internal_admin',
    entryPoint: { type: 'route', value: '/admin/financials' },
    visibility: 'internal',
    status: 'complete',
  },
  {
    id: 'admin-feature-flags',
    name: 'Admin Feature Flags',
    description: 'Platform-admin controls for per-chef feature flags and gated rollouts.',
    category: 'operations',
    classification: 'internal_admin',
    entryPoint: { type: 'route', value: '/admin/flags' },
    visibility: 'internal',
    status: 'complete',
  },
  {
    id: 'admin-beta-research',
    name: 'Admin Beta Research',
    description: 'Admin review of beta signups, pulse metrics, and beta-survey responses.',
    category: 'operations',
    classification: 'internal_admin',
    entryPoint: { type: 'route', value: '/admin/beta' },
    visibility: 'internal',
    status: 'complete',
  },
  {
    id: 'developer-simulation-lab',
    name: 'Developer Simulation Lab',
    description:
      'Simulation tooling for AI or workflow validation, including scheduled simulation checks.',
    category: 'operations',
    classification: 'developer_tool',
    entryPoint: { type: 'route', value: '/dev/simulate' },
    visibility: 'gated',
    status: 'complete',
  },
  {
    id: 'platform-health-monitoring',
    name: 'Platform Health Monitoring',
    description:
      'Monitoring, readiness, sentinel, and system-healing endpoints for infrastructure oversight.',
    category: 'operations',
    classification: 'internal_only',
    entryPoint: { type: 'service', value: 'app/api/health/*' },
    visibility: 'internal',
    status: 'complete',
  },
  {
    id: 'background-job-orchestrator',
    name: 'Background Job Orchestrator',
    description:
      'Scheduled jobs, cron tasks, Inngest handlers, and automation execution infrastructure.',
    category: 'operations',
    classification: 'internal_only',
    entryPoint: { type: 'service', value: 'app/api/scheduled/*' },
    visibility: 'internal',
    status: 'complete',
  },
  {
    id: 'realtime-push-fabric',
    name: 'Realtime Push Fabric',
    description:
      'Realtime channel, presence, typing, push subscription, and device heartbeat services.',
    category: 'operations',
    classification: 'internal_only',
    entryPoint: { type: 'service', value: 'app/api/realtime/*' },
    visibility: 'internal',
    status: 'complete',
  },
  {
    id: 'api-service-layer',
    name: 'API Service Layer',
    description:
      'Versioned business APIs covering CRUD, conversions, loyalty, commerce, settings, and search.',
    category: 'operations',
    classification: 'internal_only',
    entryPoint: { type: 'service', value: 'app/api/v2/*' },
    visibility: 'internal',
    status: 'complete',
  },
  {
    id: 'feature-flag-and-tier-system',
    name: 'Feature Flag And Tier System',
    description:
      'Pro gating, upgrade gates, tier-aware surfaces, and chef-level feature-flag enablement.',
    category: 'operations',
    classification: 'internal_only',
    entryPoint: { type: 'service', value: 'lib/billing/pro-features.ts' },
    visibility: 'internal',
    status: 'complete',
  },
  {
    id: 'price-sync-local-mirror',
    name: 'Price Sync Local Mirror',
    description:
      'OpenClaw-backed price refresh, local mirror status, and sync scheduling for grocery pricing data.',
    category: 'operations',
    classification: 'internal_only',
    entryPoint: { type: 'service', value: 'app/api/cron/price-sync/route.ts' },
    visibility: 'internal',
    status: 'partial',
  },
  {
    id: 'admin-price-catalog-ops',
    name: 'Admin Price Catalog Ops',
    description:
      'Admin-facing pricing oversight for catalog coverage and price-intelligence controls.',
    category: 'operations',
    classification: 'internal_admin',
    entryPoint: { type: 'route', value: '/admin/price-catalog' },
    visibility: 'internal',
    status: 'complete',
  },
]
