-- Print Preferences — adds configurable print/document settings per chef
-- Controls: attribution line (generated by), default print mode, custom footer text
-- Stored as JSONB for flexibility — new options can be added without migrations

ALTER TABLE chef_preferences
  ADD COLUMN IF NOT EXISTS print_preferences jsonb
    NOT NULL DEFAULT '{
      "show_attribution": true,
      "attribution_name": null,
      "default_print_mode": "standard",
      "custom_footer": null
    }'::jsonb;

COMMENT ON COLUMN chef_preferences.print_preferences IS
  'Print/document preferences. Keys: show_attribution (bool), attribution_name (string|null, defaults to business_name), default_print_mode (standard|thermal-80|thermal-58), custom_footer (string|null)';
