-- Daily Ops System
-- Tables for the daily plan: auto-drafted communications and item dismissals.
-- Part of the "Open App → Approve → Go Cook" workflow.

-- ============================================
-- 1. Daily Plan Drafts
-- Auto-generated by Remy, reviewed/approved by chef.
-- ============================================

CREATE TABLE daily_plan_drafts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  chef_id UUID NOT NULL REFERENCES chefs(id) ON DELETE CASCADE,
  plan_date DATE NOT NULL DEFAULT CURRENT_DATE,
  draft_type TEXT NOT NULL,                 -- 'follow_up', 'confirmation', 'birthday', 'reminder'
  source_entity_type TEXT,                  -- 'event', 'client', 'inquiry'
  source_entity_id UUID,
  recipient_client_id UUID REFERENCES clients(id) ON DELETE SET NULL,
  subject TEXT,
  body TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending_review',  -- pending_review, approved, dismissed
  approved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_daily_plan_drafts_chef_date ON daily_plan_drafts(chef_id, plan_date);
CREATE INDEX idx_daily_plan_drafts_status ON daily_plan_drafts(chef_id, status) WHERE status = 'pending_review';

-- ============================================
-- 2. Daily Plan Dismissals
-- Tracks items the chef skipped/snoozed for a given day.
-- ============================================

CREATE TABLE daily_plan_dismissals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  chef_id UUID NOT NULL REFERENCES chefs(id) ON DELETE CASCADE,
  item_key TEXT NOT NULL,                   -- deterministic key from source system
  dismissed_date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(chef_id, item_key, dismissed_date)
);

CREATE INDEX idx_daily_plan_dismissals_chef_date ON daily_plan_dismissals(chef_id, dismissed_date);

-- ============================================
-- 3. RLS Policies
-- ============================================

ALTER TABLE daily_plan_drafts ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_plan_dismissals ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Chef manages own drafts" ON daily_plan_drafts;
CREATE POLICY "Chef manages own drafts" ON daily_plan_drafts
  FOR ALL USING (
    chef_id IN (
      SELECT entity_id FROM user_roles WHERE auth_user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Chef manages own dismissals" ON daily_plan_dismissals;
CREATE POLICY "Chef manages own dismissals" ON daily_plan_dismissals
  FOR ALL USING (
    chef_id IN (
      SELECT entity_id FROM user_roles WHERE auth_user_id = auth.uid()
    )
  );
