-- Contracts & Legal System
-- Enables chefs to create reusable contract templates, generate event-specific
-- contracts with merge fields, and collect client e-signatures with an IP/UA audit trail.
-- Replaces the informal "cancellation policy field" with a full legal workflow.

-- ============================================
-- ENUM: Contract status lifecycle
-- ============================================

CREATE TYPE contract_status AS ENUM (
  'draft',    -- Generated by chef, not yet sent to client
  'sent',     -- Emailed to client, awaiting review
  'viewed',   -- Client opened the signing page
  'signed',   -- Client signed
  'voided'    -- Voided by chef (superseded or cancelled)
);

-- ============================================
-- TABLE 1: CONTRACT TEMPLATES
-- Reusable templates per chef with Markdown body.
-- Supports merge fields: {{client_name}}, {{event_date}},
-- {{quoted_price}}, {{deposit_amount}}, {{cancellation_policy}}
-- ============================================

CREATE TABLE contract_templates (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  chef_id        UUID NOT NULL REFERENCES chefs(id) ON DELETE CASCADE,
  name           TEXT NOT NULL,
  body_markdown  TEXT NOT NULL,
  is_default     BOOLEAN NOT NULL DEFAULT false,
  version        INTEGER NOT NULL DEFAULT 1,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_contract_templates_chef ON contract_templates(chef_id);

COMMENT ON TABLE contract_templates IS 'Chef-owned reusable contract templates. Body uses Markdown with {{merge_field}} placeholders.';
COMMENT ON COLUMN contract_templates.is_default IS 'If true, this template is pre-selected when generating a contract.';
COMMENT ON COLUMN contract_templates.version IS 'Incremented on each edit so event_contracts can reference the version used.';

-- Only one default template per chef
CREATE UNIQUE INDEX idx_contract_templates_one_default
  ON contract_templates(chef_id)
  WHERE is_default = true;

-- Auto-update updated_at
CREATE TRIGGER trg_contract_templates_updated_at
  BEFORE UPDATE ON contract_templates
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- TABLE 2: EVENT CONTRACTS
-- One per event. Captures the rendered body (with merge fields already filled),
-- signing metadata, and audit trail.
-- ============================================

CREATE TABLE event_contracts (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id           UUID NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  chef_id            UUID NOT NULL REFERENCES chefs(id) ON DELETE CASCADE,
  client_id          UUID NOT NULL REFERENCES clients(id) ON DELETE RESTRICT,
  template_id        UUID REFERENCES contract_templates(id) ON DELETE SET NULL,

  -- Rendered body (merge fields already substituted — immutable after signing)
  body_snapshot      TEXT NOT NULL,

  -- Lifecycle
  status             contract_status NOT NULL DEFAULT 'draft',
  sent_at            TIMESTAMPTZ,
  viewed_at          TIMESTAMPTZ,
  signed_at          TIMESTAMPTZ,
  voided_at          TIMESTAMPTZ,
  void_reason        TEXT,

  -- Signature capture
  signature_data_url TEXT,   -- Base64 PNG data URL of drawn signature
  signer_ip_address  TEXT,
  signer_user_agent  TEXT,

  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_event_contracts_event    ON event_contracts(event_id);
CREATE INDEX idx_event_contracts_chef     ON event_contracts(chef_id, status);
CREATE INDEX idx_event_contracts_client   ON event_contracts(client_id);

COMMENT ON TABLE event_contracts IS 'Event-specific contracts generated from templates. Body is a frozen snapshot with merge fields substituted. Immutable after signing.';
COMMENT ON COLUMN event_contracts.body_snapshot IS 'Rendered Markdown body with all merge fields substituted at generation time. Never updated after signing.';
COMMENT ON COLUMN event_contracts.signature_data_url IS 'Base64-encoded PNG of the client canvas signature.';
COMMENT ON COLUMN event_contracts.signer_ip_address IS 'Client IP at time of signing — legal evidence.';

-- Auto-update updated_at
CREATE TRIGGER trg_event_contracts_updated_at
  BEFORE UPDATE ON event_contracts
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Prevent modification of a signed contract's body or signature
CREATE OR REPLACE FUNCTION prevent_signed_contract_mutation()
RETURNS TRIGGER AS $$
BEGIN
  IF OLD.status = 'signed' AND (
    NEW.body_snapshot     != OLD.body_snapshot OR
    NEW.signature_data_url != OLD.signature_data_url OR
    NEW.signed_at          != OLD.signed_at OR
    NEW.signer_ip_address  != OLD.signer_ip_address
  ) THEN
    RAISE EXCEPTION 'Signed contracts cannot be altered';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_event_contracts_immutable
  BEFORE UPDATE ON event_contracts
  FOR EACH ROW EXECUTE FUNCTION prevent_signed_contract_mutation();

-- ============================================
-- ROW LEVEL SECURITY
-- ============================================

ALTER TABLE contract_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_contracts    ENABLE ROW LEVEL SECURITY;

-- ---- contract_templates: chef-only ----

DROP POLICY IF EXISTS ct_chef_select ON contract_templates;
CREATE POLICY ct_chef_select ON contract_templates
  FOR SELECT USING (
    get_current_user_role() = 'chef' AND
    chef_id = get_current_tenant_id()
  );

DROP POLICY IF EXISTS ct_chef_insert ON contract_templates;
CREATE POLICY ct_chef_insert ON contract_templates
  FOR INSERT WITH CHECK (
    get_current_user_role() = 'chef' AND
    chef_id = get_current_tenant_id()
  );

DROP POLICY IF EXISTS ct_chef_update ON contract_templates;
CREATE POLICY ct_chef_update ON contract_templates
  FOR UPDATE USING (
    get_current_user_role() = 'chef' AND
    chef_id = get_current_tenant_id()
  );

DROP POLICY IF EXISTS ct_chef_delete ON contract_templates;
CREATE POLICY ct_chef_delete ON contract_templates
  FOR DELETE USING (
    get_current_user_role() = 'chef' AND
    chef_id = get_current_tenant_id()
  );

-- ---- event_contracts: chef full access ----

DROP POLICY IF EXISTS ec_chef_select ON event_contracts;
CREATE POLICY ec_chef_select ON event_contracts
  FOR SELECT USING (
    get_current_user_role() = 'chef' AND
    chef_id = get_current_tenant_id()
  );

DROP POLICY IF EXISTS ec_chef_insert ON event_contracts;
CREATE POLICY ec_chef_insert ON event_contracts
  FOR INSERT WITH CHECK (
    get_current_user_role() = 'chef' AND
    chef_id = get_current_tenant_id()
  );

DROP POLICY IF EXISTS ec_chef_update ON event_contracts;
CREATE POLICY ec_chef_update ON event_contracts
  FOR UPDATE USING (
    get_current_user_role() = 'chef' AND
    chef_id = get_current_tenant_id()
  );

-- Chef cannot hard-delete a signed contract
DROP POLICY IF EXISTS ec_chef_delete ON event_contracts;
CREATE POLICY ec_chef_delete ON event_contracts
  FOR DELETE USING (
    get_current_user_role() = 'chef' AND
    chef_id = get_current_tenant_id() AND
    status NOT IN ('signed')
  );

-- ---- event_contracts: client can view and sign their own ----

DROP POLICY IF EXISTS ec_client_select ON event_contracts;
CREATE POLICY ec_client_select ON event_contracts
  FOR SELECT USING (
    get_current_user_role() = 'client' AND
    client_id = get_current_client_id()
  );

-- Client can only update to mark viewed or sign (status, viewed_at, signed_at, signature fields)
DROP POLICY IF EXISTS ec_client_update ON event_contracts;
CREATE POLICY ec_client_update ON event_contracts
  FOR UPDATE USING (
    get_current_user_role() = 'client' AND
    client_id = get_current_client_id() AND
    status IN ('sent', 'viewed')   -- cannot re-sign or un-void
  );
