// After-Action Report (AAR) Template — Structured Debrief
// Standard post-event debrief used by every catering operation and military unit.
// The structure is the value — not the prose. AI can optionally add narrative.

// ── Types ──────────────────────────────────────────────────────────────────

export type AARReport = {
  title: string
  eventSummary: string
  whatWentWell: string[]
  whatToImprove: string[]
  financialReflection: string
  nextTimeList: string[]
  fullMarkdown: string
  generatedAt: string
}

// ── Input types ────────────────────────────────────────────────────────────

export type AARVars = {
  occasion: string
  eventDate: string
  guestCount: number
  clientName: string
  quotedPriceCents: number
  actualCostCents?: number // food + supply costs
  amountPaidCents?: number
  menuItems: string[]
  notes?: string // chef's own notes about how it went
}

// ── Helpers ────────────────────────────────────────────────────────────────

function formatDate(dateStr: string): string {
  try {
    return new Date(dateStr).toLocaleDateString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric',
    })
  } catch {
    return dateStr
  }
}

function formatCents(cents: number): string {
  return (
    '$' +
    (cents / 100).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
  )
}

// ── Template ───────────────────────────────────────────────────────────────

/**
 * Generates an after-action report from event data.
 * Structured template — the sections are the value.
 * AI can optionally add narrative prose to each section.
 */
export function generateAARTemplate(v: AARVars): AARReport {
  const title = `After-Action Report: ${v.occasion} — ${formatDate(v.eventDate)}`

  const eventSummary = [
    `**Event:** ${v.occasion}`,
    `**Date:** ${formatDate(v.eventDate)}`,
    `**Client:** ${v.clientName}`,
    `**Guests:** ${v.guestCount}`,
    `**Menu:** ${v.menuItems.length > 0 ? v.menuItems.join(', ') : 'Not recorded'}`,
    v.notes ? `**Chef Notes:** ${v.notes}` : null,
  ]
    .filter(Boolean)
    .join('\n')

  // Prompt the chef to fill these in — structure is the value
  const whatWentWell = [
    'Menu was well-received by guests',
    'Timing and service flow went as planned',
    'Kitchen cleanup was efficient',
  ]

  const whatToImprove = [
    'Review if any courses took longer than expected',
    'Check if portion sizes were appropriate for guest count',
    'Note any equipment that was missing or underperforming',
  ]

  // Financial reflection
  const revenue = v.amountPaidCents ?? v.quotedPriceCents
  const costs = v.actualCostCents ?? 0
  const profit = revenue - costs
  const foodCostPercent = revenue > 0 ? Math.round((costs / revenue) * 100) : 0

  let financialReflection: string
  if (costs > 0) {
    financialReflection = [
      `**Revenue:** ${formatCents(revenue)}`,
      `**Food/Supply Cost:** ${formatCents(costs)}`,
      `**Gross Profit:** ${formatCents(profit)}`,
      `**Food Cost %:** ${foodCostPercent}%`,
      '',
      foodCostPercent > 35
        ? `⚠️ Food cost is above the 35% target. Review ingredient sourcing or portion sizes.`
        : foodCostPercent > 25
          ? `✅ Food cost is within the healthy 25–35% range.`
          : `✅ Excellent food cost control — below 25%.`,
    ].join('\n')
  } else {
    financialReflection = [
      `**Revenue:** ${formatCents(revenue)}`,
      `**Food/Supply Cost:** Not tracked for this event`,
      '',
      `💡 Track food costs for future events to monitor profitability.`,
    ].join('\n')
  }

  const nextTimeList = [
    'Confirm final guest count 5 days before event',
    'Double-check allergen list against menu 48 hours before',
    'Pre-stage all equipment the night before (offsite events)',
    'Take photos of plated dishes before service',
    'Send thank-you email within 24 hours',
  ]

  // Assemble full markdown
  const fullMarkdown = [
    `# ${title}`,
    '',
    '## Event Summary',
    eventSummary,
    '',
    '## What Went Well',
    whatWentWell.map((w) => `- ${w}`).join('\n'),
    '',
    '## What to Improve',
    whatToImprove.map((w) => `- ${w}`).join('\n'),
    '',
    '## Financial Reflection',
    financialReflection,
    '',
    '## Next Time',
    nextTimeList.map((w) => `- [ ] ${w}`).join('\n'),
    '',
    '---',
    `*Generated by ChefFlow on ${new Date().toLocaleDateString('en-US')}. Edit freely — this is your debrief.*`,
  ].join('\n')

  return {
    title,
    eventSummary,
    whatWentWell,
    whatToImprove,
    financialReflection,
    nextTimeList,
    fullMarkdown,
    generatedAt: new Date().toISOString(),
  }
}
