/**
 * Q13: AI System Resilience
 *
 * The AI layer (Remy/Ollama) must fail transparently when the runtime is
 * offline. Silent failures that return empty responses or hallucinated
 * content are zero-hallucination violations.
 *
 * Tests:
 *
 * 1. THINK TOKEN STRIPPING: the simulation pipeline strips <think>...</think>
 *    tokens before JSON parsing. qwen3:4b bleeds thinking chains into
 *    message.content. Unstripped chains cause JSON.parse failures.
 *
 * 2. OFFLINE ERROR CLASS: OllamaOfflineError is importable from the correct
 *    path and is NOT exported from a 'use server' file (class exports from
 *    server files crash at runtime).
 *
 * 3. PRIVACY GATE: PII processing routes through Ollama (parseWithOllama),
 *    never through Gemini (parseWithAI). Structural check on key files.
 *
 * 4. NO RECIPE GENERATION: the restricted-actions file blocks AI recipe
 *    creation. Chef IP must never be generated by AI.
 *
 * 5. FORMULA > AI: no AI call is made for calculations that can be done
 *    deterministically (math, date arithmetic, status checks).
 *
 * Run: npx playwright test -c playwright.system-integrity.config.ts tests/system-integrity/q13-ai-resilience.spec.ts
 */
import { test, expect } from '@playwright/test'
import { readFileSync, existsSync } from 'fs'
import { resolve } from 'path'

const ROOT = process.cwd()

test.describe('Q13: AI system resilience', () => {
  // -------------------------------------------------------------------------
  // Test 1: Think token stripping is present in simulation pipeline
  // -------------------------------------------------------------------------
  test('think-token stripping is in simulation pipeline files', () => {
    const PIPELINE_FILES = [
      'lib/ai/simulation/scenario-generator.ts',
      'lib/ai/simulation/pipeline-runner.ts',
      'lib/ai/simulation/quality-evaluator.ts',
    ]

    const STRIP_PATTERN = /<think>/

    for (const rel of PIPELINE_FILES) {
      const filePath = resolve(ROOT, rel)
      if (!existsSync(filePath)) continue

      const src = readFileSync(filePath, 'utf-8')
      expect(STRIP_PATTERN.test(src), `${rel} must strip <think> tokens before JSON parsing`).toBe(
        true
      )
    }
  })

  // -------------------------------------------------------------------------
  // Test 2: OllamaOfflineError is in the correct (non-server-action) file
  // -------------------------------------------------------------------------
  test('OllamaOfflineError lives in lib/ai/ollama-errors.ts (not a use-server file)', () => {
    const errorFile = resolve(ROOT, 'lib/ai/ollama-errors.ts')
    expect(existsSync(errorFile), 'lib/ai/ollama-errors.ts must exist').toBe(true)

    const src = readFileSync(errorFile, 'utf-8')

    // Must export the class
    expect(src.includes('OllamaOfflineError'), 'OllamaOfflineError must be in this file').toBe(true)

    // Must NOT have 'use server' directive — class exports from server files crash
    expect(src).not.toMatch(/^['"]use server['"]/m)
  })

  // -------------------------------------------------------------------------
  // Test 3: Privacy gate — PII files use parseWithOllama, not parseWithAI
  // -------------------------------------------------------------------------
  test('PII-handling AI files use parseWithOllama (not parseWithAI/Gemini)', () => {
    const PII_FILES = [
      'lib/ai/parse-brain-dump.ts',
      'lib/ai/aar-generator.ts',
      'lib/ai/contract-generator.ts',
      'lib/ai/remy-actions.ts',
      'lib/ai/grocery-consolidation.ts',
    ]

    for (const rel of PII_FILES) {
      const filePath = resolve(ROOT, rel)
      if (!existsSync(filePath)) continue

      const src = readFileSync(filePath, 'utf-8')

      // Must use parseWithOllama
      expect(src.includes('parseWithOllama'), `${rel} must use parseWithOllama for PII data`).toBe(
        true
      )

      // Must NOT use parseWithAI directly (Gemini)
      // (parseWithAI is the Gemini wrapper — PII must not go through Gemini)
      const usesGemini = src.includes('parseWithAI') && !src.includes('// gemini-ok')
      expect(!usesGemini, `${rel} must not use parseWithAI (Gemini) for PII data`).toBe(true)
    }
  })

  // -------------------------------------------------------------------------
  // Test 4: Recipe generation is blocked in restricted-actions
  // -------------------------------------------------------------------------
  test('AI recipe generation is permanently blocked', () => {
    const restrictedFile = resolve(ROOT, 'lib/ai/agent-actions/restricted-actions.ts')
    if (!existsSync(restrictedFile)) return

    const src = readFileSync(restrictedFile, 'utf-8')

    expect(
      src.includes('create_recipe') || src.includes('agent.create_recipe'),
      'restricted-actions.ts must block agent.create_recipe'
    ).toBe(true)

    expect(
      src.includes('update_recipe') || src.includes('add_ingredient'),
      'restricted-actions.ts must block recipe mutation actions'
    ).toBe(true)
  })

  // -------------------------------------------------------------------------
  // Test 5: Input validation layer blocks recipe generation intent
  // -------------------------------------------------------------------------
  test('Remy input validation blocks recipe-generation intent', () => {
    const validationFile = resolve(ROOT, 'lib/ai/remy-input-validation.ts')
    if (!existsSync(validationFile)) return

    const src = readFileSync(validationFile, 'utf-8')

    // Must reference recipe blocking
    expect(
      src.includes('recipe') || src.includes('Recipe'),
      'remy-input-validation.ts must include recipe generation blocking'
    ).toBe(true)
  })

  // -------------------------------------------------------------------------
  // Test 6: Remy stream endpoint has auth gate
  // -------------------------------------------------------------------------
  test('Remy stream endpoint requires authentication', async ({ request: req }) => {
    const resp = await req.post('/api/remy/stream', {
      headers: { 'content-type': 'application/json' },
      data: JSON.stringify({ message: 'hello', surfaceId: 'dashboard' }),
    })

    // Unauthenticated must be rejected
    expect(
      [401, 403, 302, 307].includes(resp.status()),
      `Remy stream must reject unauthenticated requests, got ${resp.status()}`
    ).toBe(true)
  })

  // -------------------------------------------------------------------------
  // Test 7: AI dispatch layer exists (privacy gate infrastructure)
  // -------------------------------------------------------------------------
  test('AI dispatch layer files exist (privacy gate infrastructure)', () => {
    const DISPATCH_FILES = [
      'lib/ai/dispatch/classifier.ts',
      'lib/ai/dispatch/privacy-gate.ts',
      'lib/ai/dispatch/router.ts',
    ]

    let found = 0
    for (const rel of DISPATCH_FILES) {
      if (existsSync(resolve(ROOT, rel))) found++
    }

    expect(
      found,
      `At least 2 of 3 AI dispatch layer files must exist (found ${found})`
    ).toBeGreaterThanOrEqual(2)
  })
})
