'use server'

// Dietary Outreach Server Actions
// Sends pre-event dietary confirmation emails to individual guests.

import { requireChef } from '@/lib/auth/get-user'
import { createServerClient } from '@/lib/db/server'
import { sendEmail } from '@/lib/email/send'
import { DietaryConfirmationEmail } from '@/lib/email/templates/dietary-confirmation'
import { revalidatePath } from 'next/cache'
import type { GuestOutreachInfo } from './types'

const APP_URL = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3100'

/**
 * Send dietary outreach emails to all guests with email addresses for an event.
 * Creates dietary_outreach records with unique tokens. Skips guests already contacted.
 */
export async function sendDietaryOutreach(
  eventId: string
): Promise<{ success: boolean; sent: number; skipped: number; error?: string }> {
  const user = await requireChef()
  const db: any = createServerClient()

  // Fetch event details for the email
  const { data: event, error: eventErr } = await db
    .from('events')
    .select('id, occasion, event_date, client_id')
    .eq('id', eventId)
    .eq('tenant_id', user.tenantId!)
    .single()

  if (eventErr || !event) {
    return { success: false, sent: 0, skipped: 0, error: 'Event not found' }
  }

  // Fetch all guests for this event who have an email
  const { data: guests, error: guestErr } = await db
    .from('event_guests')
    .select('id, full_name, email, dietary_restrictions, allergies')
    .eq('event_id', eventId)
    .eq('tenant_id', user.tenantId!)
    .neq('email', null)

  if (guestErr) {
    return { success: false, sent: 0, skipped: 0, error: 'Failed to fetch guests' }
  }

  if (!guests || guests.length === 0) {
    return { success: false, sent: 0, skipped: 0, error: 'No guests with email addresses found' }
  }

  // Check existing outreach to avoid duplicates
  const { data: existingOutreach } = await db
    .from('dietary_outreach')
    .select('guest_id')
    .eq('event_id', eventId)
    .eq('tenant_id', user.tenantId!)

  const alreadySent = new Set((existingOutreach || []).map((r: any) => r.guest_id))

  let sent = 0
  let skipped = 0

  // Format event date for display
  const eventDate = new Date(event.event_date).toLocaleDateString('en-US', {
    weekday: 'long',
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  })

  for (const guest of guests) {
    if (alreadySent.has(guest.id)) {
      skipped++
      continue
    }

    if (!guest.email) {
      skipped++
      continue
    }

    // Insert outreach record (token auto-generated by DB default)
    const { data: outreach, error: insertErr } = await db
      .from('dietary_outreach')
      .insert({
        event_id: eventId,
        guest_id: guest.id,
        tenant_id: user.tenantId!,
        status: 'sent',
      })
      .select('id, token')
      .single()

    if (insertErr || !outreach) {
      skipped++
      continue
    }

    const confirmUrl = `${APP_URL}/dietary-confirm/${outreach.token}`

    // Send the email
    const emailSent = await sendEmail({
      to: guest.email,
      subject: `Please confirm your dietary needs for ${event.occasion || 'upcoming dinner'}`,
      react: DietaryConfirmationEmail({
        guestName: guest.full_name,
        occasion: event.occasion || 'dinner',
        eventDate,
        confirmUrl,
      }),
      isTransactional: true,
    })

    if (emailSent) {
      sent++
    } else {
      // Email failed but outreach record exists for tracking
      skipped++
    }
  }

  revalidatePath(`/events/${eventId}`)

  return { success: true, sent, skipped }
}

/**
 * Get dietary outreach status for all guests in an event.
 */
export async function getDietaryOutreachStatus(
  eventId: string
): Promise<{ success: boolean; guests: GuestOutreachInfo[]; error?: string }> {
  const user = await requireChef()
  const db: any = createServerClient()

  // Verify event belongs to this chef
  const { data: event, error: eventErr } = await db
    .from('events')
    .select('id')
    .eq('id', eventId)
    .eq('tenant_id', user.tenantId!)
    .single()

  if (eventErr || !event) {
    return { success: false, guests: [], error: 'Event not found' }
  }

  // Fetch all guests
  const { data: guests, error: guestErr } = await db
    .from('event_guests')
    .select('id, full_name, email, dietary_restrictions, allergies')
    .eq('event_id', eventId)
    .eq('tenant_id', user.tenantId!)

  if (guestErr || !guests) {
    return { success: false, guests: [], error: 'Failed to fetch guests' }
  }

  // Fetch outreach records
  const { data: outreachRecords } = await db
    .from('dietary_outreach')
    .select('guest_id, status, sent_at, responded_at')
    .eq('event_id', eventId)
    .eq('tenant_id', user.tenantId!)

  const outreachMap = new Map((outreachRecords || []).map((r: any) => [r.guest_id, r]))

  const result: GuestOutreachInfo[] = guests.map((guest: any) => {
    const outreach = outreachMap.get(guest.id) as any
    return {
      guest_id: guest.id,
      guest_name: guest.full_name,
      email: guest.email,
      status: outreach ? outreach.status : 'not_sent',
      sent_at: outreach?.sent_at || null,
      responded_at: outreach?.responded_at || null,
      dietary_restrictions: guest.dietary_restrictions || [],
      allergies: guest.allergies || [],
    }
  })

  return { success: true, guests: result }
}
