// Service Lifecycle Template Seeder
// Seeds the default ~150 checkpoints from the Service Lifecycle Blueprint.
// Idempotent: uses ON CONFLICT DO NOTHING. Safe to call multiple times.
// NOT a 'use server' file - called from both UI (via actions.ts) and Gmail sync pipeline.

import { createServerClient } from '@/lib/db/server'

interface CheckpointDef {
  stage_number: number
  stage_name: string
  checkpoint_key: string
  checkpoint_label: string
  sort_order: number
  is_required: boolean
  auto_detect_rule: string | null
  client_visible: boolean
  client_label: string | null
}

// ---------------------------------------------------------------------------
// Stage 1: Inquiry Received
// ---------------------------------------------------------------------------
const STAGE_1: CheckpointDef[] = [
  {
    stage_number: 1,
    stage_name: 'inquiry_received',
    checkpoint_key: 's1_date_captured',
    checkpoint_label: 'Inquiry date and time captured',
    sort_order: 1,
    is_required: false,
    auto_detect_rule: 'field_present:created_at',
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 1,
    stage_name: 'inquiry_received',
    checkpoint_key: 's1_source_tracked',
    checkpoint_label: 'Source tracked',
    sort_order: 2,
    is_required: false,
    auto_detect_rule: 'field_present:channel',
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 1,
    stage_name: 'inquiry_received',
    checkpoint_key: 's1_host_name',
    checkpoint_label: 'Host name captured',
    sort_order: 3,
    is_required: true,
    auto_detect_rule: 'field_present:contact_name',
    client_visible: true,
    client_label: 'Your name confirmed',
  },
  {
    stage_number: 1,
    stage_name: 'inquiry_received',
    checkpoint_key: 's1_host_email',
    checkpoint_label: 'Host email captured',
    sort_order: 4,
    is_required: true,
    auto_detect_rule: 'field_present:contact_email',
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 1,
    stage_name: 'inquiry_received',
    checkpoint_key: 's1_host_phone',
    checkpoint_label: 'Host phone captured',
    sort_order: 5,
    is_required: false,
    auto_detect_rule: 'field_present:contact_phone',
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 1,
    stage_name: 'inquiry_received',
    checkpoint_key: 's1_comm_channel',
    checkpoint_label: 'Preferred communication channel identified',
    sort_order: 6,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 1,
    stage_name: 'inquiry_received',
    checkpoint_key: 's1_event_date',
    checkpoint_label: 'Event date captured',
    sort_order: 7,
    is_required: true,
    auto_detect_rule: 'field_present:confirmed_date',
    client_visible: true,
    client_label: 'Date confirmed',
  },
  {
    stage_number: 1,
    stage_name: 'inquiry_received',
    checkpoint_key: 's1_guest_count',
    checkpoint_label: 'Guest count captured',
    sort_order: 8,
    is_required: true,
    auto_detect_rule: 'field_present:confirmed_guest_count',
    client_visible: true,
    client_label: 'Guest count confirmed',
  },
  {
    stage_number: 1,
    stage_name: 'inquiry_received',
    checkpoint_key: 's1_location',
    checkpoint_label: 'Event location captured',
    sort_order: 9,
    is_required: false,
    auto_detect_rule: 'field_present:confirmed_location',
    client_visible: true,
    client_label: 'Location confirmed',
  },
  {
    stage_number: 1,
    stage_name: 'inquiry_received',
    checkpoint_key: 's1_event_type',
    checkpoint_label: 'Event type identified',
    sort_order: 10,
    is_required: false,
    auto_detect_rule: 'field_present:confirmed_occasion',
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 1,
    stage_name: 'inquiry_received',
    checkpoint_key: 's1_how_heard',
    checkpoint_label: 'How they heard about you noted',
    sort_order: 11,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 1,
    stage_name: 'inquiry_received',
    checkpoint_key: 's1_initial_budget',
    checkpoint_label: 'Initial budget range mentioned',
    sort_order: 12,
    is_required: false,
    auto_detect_rule: 'field_present:confirmed_budget_cents',
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 1,
    stage_name: 'inquiry_received',
    checkpoint_key: 's1_initial_notes',
    checkpoint_label: 'Initial requests or special notes captured',
    sort_order: 13,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 1,
    stage_name: 'inquiry_received',
    checkpoint_key: 's1_auto_ack_sent',
    checkpoint_label: 'Auto-acknowledgment sent',
    sort_order: 14,
    is_required: false,
    auto_detect_rule: 'field_present:auto_responded_at',
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 1,
    stage_name: 'inquiry_received',
    checkpoint_key: 's1_personal_response_sent',
    checkpoint_label: 'Personal initial response sent',
    sort_order: 15,
    is_required: true,
    auto_detect_rule: 'field_present:first_response_at',
    client_visible: true,
    client_label: 'Chef responded',
  },
  {
    stage_number: 1,
    stage_name: 'inquiry_received',
    checkpoint_key: 's1_response_time_tracked',
    checkpoint_label: 'Response time tracked',
    sort_order: 16,
    is_required: false,
    auto_detect_rule: 'field_present:first_response_at',
    client_visible: false,
    client_label: null,
  },
]

// ---------------------------------------------------------------------------
// Stage 2: Discovery
// ---------------------------------------------------------------------------
const STAGE_2: CheckpointDef[] = [
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_guest_list',
    checkpoint_label: 'Full guest list collected',
    sort_order: 1,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_dietary_per_guest',
    checkpoint_label: 'Per-guest dietary restrictions collected',
    sort_order: 2,
    is_required: true,
    auto_detect_rule: 'field_present:confirmed_dietary_restrictions',
    client_visible: true,
    client_label: 'Dietary restrictions confirmed',
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_allergy_severity',
    checkpoint_label: 'Severity of allergies confirmed',
    sort_order: 3,
    is_required: true,
    auto_detect_rule: 'text_match:dietary',
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_children_attending',
    checkpoint_label: 'Children attending (ages, separate menu?)',
    sort_order: 4,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_dietary_confirmed_with_guests',
    checkpoint_label: 'Dietary confirmed directly with guests',
    sort_order: 5,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_cuisine_preferences',
    checkpoint_label: 'Cuisine preferences gathered',
    sort_order: 6,
    is_required: false,
    auto_detect_rule: 'text_match:cuisine_preference',
    client_visible: true,
    client_label: 'Menu preferences shared',
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_cuisine_dislikes',
    checkpoint_label: 'Cuisine dislikes or hard-no ingredients noted',
    sort_order: 7,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_favorite_restaurants',
    checkpoint_label: 'Favorite restaurants or dishes mentioned',
    sort_order: 8,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_previous_chef_experience',
    checkpoint_label: 'Previous private chef experiences discussed',
    sort_order: 9,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_adventure_level',
    checkpoint_label: 'Comfort level with adventurous food assessed',
    sort_order: 10,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_course_count',
    checkpoint_label: 'Course count discussed',
    sort_order: 11,
    is_required: false,
    auto_detect_rule: 'text_match:course_count',
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_service_style',
    checkpoint_label: 'Service style preference confirmed',
    sort_order: 12,
    is_required: false,
    auto_detect_rule: 'text_match:service_style',
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_budget_discussed',
    checkpoint_label: 'Budget discussed',
    sort_order: 13,
    is_required: false,
    auto_detect_rule: 'field_present:confirmed_budget_cents',
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_whats_included_explained',
    checkpoint_label: 'What is included in price explained',
    sort_order: 14,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_grocery_model_explained',
    checkpoint_label: 'Grocery cost model explained',
    sort_order: 15,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_gratuity_policy_communicated',
    checkpoint_label: 'Gratuity policy communicated',
    sort_order: 16,
    is_required: false,
    auto_detect_rule: 'text_match:gratuity',
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_client_expectations',
    checkpoint_label: 'Client expectations discussed',
    sort_order: 17,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_drinks_discussed',
    checkpoint_label: 'Drinks/bar expectations discussed',
    sort_order: 18,
    is_required: false,
    auto_detect_rule: 'text_match:drinks',
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_wine_pairing_interest',
    checkpoint_label: 'Wine/cocktail pairing interest level',
    sort_order: 19,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_beverage_budget',
    checkpoint_label: 'Beverage budget discussed',
    sort_order: 20,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_bar_setup',
    checkpoint_label: 'Bar setup needs discussed',
    sort_order: 21,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_kitchen_situation',
    checkpoint_label: 'Kitchen situation discussed',
    sort_order: 22,
    is_required: false,
    auto_detect_rule: 'text_match:kitchen',
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_kitchen_visit_needed',
    checkpoint_label: 'Kitchen visit needed?',
    sort_order: 23,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_dining_space',
    checkpoint_label: 'Dining space discussed',
    sort_order: 24,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_equipment_needs',
    checkpoint_label: 'Equipment needs assessed',
    sort_order: 25,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_parking_access',
    checkpoint_label: 'Parking and loading access discussed',
    sort_order: 26,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_special_occasion',
    checkpoint_label: 'Special occasion details captured',
    sort_order: 27,
    is_required: false,
    auto_detect_rule: 'field_present:confirmed_occasion',
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_surprise_element',
    checkpoint_label: 'Surprise element coordination',
    sort_order: 28,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_vibe_preferences',
    checkpoint_label: 'Vibe/atmosphere preferences discussed',
    sort_order: 29,
    is_required: false,
    auto_detect_rule: 'text_match:vibe',
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_dress_code',
    checkpoint_label: 'Dress code for chef/staff',
    sort_order: 30,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_table_presentation',
    checkpoint_label: 'Table setting/presentation expectations',
    sort_order: 31,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_vendor_coordination',
    checkpoint_label: 'Vendor coordination needed?',
    sort_order: 32,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_photo_social_consent',
    checkpoint_label: 'Photography/social media preferences',
    sort_order: 33,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_confidentiality',
    checkpoint_label: 'Confidentiality requirements',
    sort_order: 34,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_primary_contact',
    checkpoint_label: 'Primary contact person confirmed',
    sort_order: 35,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_comm_preferences',
    checkpoint_label: 'Communication preferences confirmed',
    sort_order: 36,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_response_expectations',
    checkpoint_label: 'Response time expectations set',
    sort_order: 37,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_tasting_offered',
    checkpoint_label: 'Tasting dinner offered',
    sort_order: 38,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_tasting_scheduled',
    checkpoint_label: 'Tasting date scheduled',
    sort_order: 39,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_tasting_completed',
    checkpoint_label: 'Tasting completed',
    sort_order: 40,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 2,
    stage_name: 'discovery',
    checkpoint_key: 's2_tasting_feedback',
    checkpoint_label: 'Tasting feedback received',
    sort_order: 41,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
]

// ---------------------------------------------------------------------------
// Stage 3: Quote
// ---------------------------------------------------------------------------
const STAGE_3: CheckpointDef[] = [
  {
    stage_number: 3,
    stage_name: 'quote',
    checkpoint_key: 's3_quote_drafted',
    checkpoint_label: 'Quote drafted',
    sort_order: 1,
    is_required: true,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 3,
    stage_name: 'quote',
    checkpoint_key: 's3_quote_sent',
    checkpoint_label: 'Quote sent to host',
    sort_order: 2,
    is_required: true,
    auto_detect_rule: 'inquiry_status:quoted',
    client_visible: true,
    client_label: 'Quote sent',
  },
  {
    stage_number: 3,
    stage_name: 'quote',
    checkpoint_key: 's3_quote_follow_up_sent',
    checkpoint_label: 'Quote follow-up sent',
    sort_order: 3,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 3,
    stage_name: 'quote',
    checkpoint_key: 's3_quote_reviewed',
    checkpoint_label: 'Quote reviewed by host',
    sort_order: 4,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 3,
    stage_name: 'quote',
    checkpoint_key: 's3_questions_answered',
    checkpoint_label: 'Questions answered',
    sort_order: 5,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 3,
    stage_name: 'quote',
    checkpoint_key: 's3_revisions_requested',
    checkpoint_label: 'Revisions requested',
    sort_order: 6,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 3,
    stage_name: 'quote',
    checkpoint_key: 's3_revised_quote_sent',
    checkpoint_label: 'Revised quote sent',
    sort_order: 7,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 3,
    stage_name: 'quote',
    checkpoint_key: 's3_quote_accepted',
    checkpoint_label: 'Quote accepted and confirmed',
    sort_order: 8,
    is_required: true,
    auto_detect_rule: 'inquiry_status:confirmed',
    client_visible: true,
    client_label: 'Quote accepted',
  },
  {
    stage_number: 3,
    stage_name: 'quote',
    checkpoint_key: 's3_deposit_terms_communicated',
    checkpoint_label: 'Deposit amount and terms communicated',
    sort_order: 9,
    is_required: false,
    auto_detect_rule: 'text_match:deposit',
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 3,
    stage_name: 'quote',
    checkpoint_key: 's3_deposit_invoice_sent',
    checkpoint_label: 'Deposit invoice sent',
    sort_order: 10,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 3,
    stage_name: 'quote',
    checkpoint_key: 's3_deposit_received',
    checkpoint_label: 'Deposit received',
    sort_order: 11,
    is_required: false,
    auto_detect_rule: null,
    client_visible: true,
    client_label: 'Deposit received',
  },
  {
    stage_number: 3,
    stage_name: 'quote',
    checkpoint_key: 's3_deposit_receipt_sent',
    checkpoint_label: 'Deposit confirmed and receipt sent',
    sort_order: 12,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
]

// ---------------------------------------------------------------------------
// Stage 4: Agreement
// ---------------------------------------------------------------------------
const STAGE_4: CheckpointDef[] = [
  {
    stage_number: 4,
    stage_name: 'agreement',
    checkpoint_key: 's4_agreement_drafted',
    checkpoint_label: 'Service agreement drafted',
    sort_order: 1,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 4,
    stage_name: 'agreement',
    checkpoint_key: 's4_cancellation_policy',
    checkpoint_label: 'Cancellation policy detailed',
    sort_order: 2,
    is_required: false,
    auto_detect_rule: 'text_match:cancellation_policy',
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 4,
    stage_name: 'agreement',
    checkpoint_key: 's4_reschedule_policy',
    checkpoint_label: 'Reschedule policy detailed',
    sort_order: 3,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 4,
    stage_name: 'agreement',
    checkpoint_key: 's4_liability_terms',
    checkpoint_label: 'Liability and insurance terms included',
    sort_order: 4,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 4,
    stage_name: 'agreement',
    checkpoint_key: 's4_kitchen_access_terms',
    checkpoint_label: 'Kitchen access terms included',
    sort_order: 5,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 4,
    stage_name: 'agreement',
    checkpoint_key: 's4_grocery_reimbursement',
    checkpoint_label: 'Grocery reimbursement formalized',
    sort_order: 6,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 4,
    stage_name: 'agreement',
    checkpoint_key: 's4_confidentiality_clause',
    checkpoint_label: 'Confidentiality/NDA clause included',
    sort_order: 7,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 4,
    stage_name: 'agreement',
    checkpoint_key: 's4_photo_rights',
    checkpoint_label: 'Photography rights addressed',
    sort_order: 8,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 4,
    stage_name: 'agreement',
    checkpoint_key: 's4_force_majeure',
    checkpoint_label: 'Force majeure clause included',
    sort_order: 9,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 4,
    stage_name: 'agreement',
    checkpoint_key: 's4_ip_clause',
    checkpoint_label: 'Intellectual property clause (chef retains recipe IP)',
    sort_order: 10,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 4,
    stage_name: 'agreement',
    checkpoint_key: 's4_agreement_sent',
    checkpoint_label: 'Agreement sent to client',
    sort_order: 11,
    is_required: false,
    auto_detect_rule: null,
    client_visible: true,
    client_label: 'Agreement sent',
  },
  {
    stage_number: 4,
    stage_name: 'agreement',
    checkpoint_key: 's4_agreement_reviewed',
    checkpoint_label: 'Agreement reviewed by client',
    sort_order: 12,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 4,
    stage_name: 'agreement',
    checkpoint_key: 's4_agreement_signed_client',
    checkpoint_label: 'Agreement signed by client',
    sort_order: 13,
    is_required: false,
    auto_detect_rule: null,
    client_visible: true,
    client_label: 'Agreement signed',
  },
  {
    stage_number: 4,
    stage_name: 'agreement',
    checkpoint_key: 's4_agreement_countersigned',
    checkpoint_label: 'Agreement countersigned by chef',
    sort_order: 14,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 4,
    stage_name: 'agreement',
    checkpoint_key: 's4_signed_copy_stored',
    checkpoint_label: 'Signed copy stored',
    sort_order: 15,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 4,
    stage_name: 'agreement',
    checkpoint_key: 's4_insurance_cert_provided',
    checkpoint_label: 'Insurance certificate provided to venue',
    sort_order: 16,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
]

// ---------------------------------------------------------------------------
// Stage 5: Menu Planning
// ---------------------------------------------------------------------------
const STAGE_5: CheckpointDef[] = [
  {
    stage_number: 5,
    stage_name: 'menu_planning',
    checkpoint_key: 's5_rough_draft_created',
    checkpoint_label: 'Rough draft menu created',
    sort_order: 1,
    is_required: true,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 5,
    stage_name: 'menu_planning',
    checkpoint_key: 's5_dietary_accounted',
    checkpoint_label: 'Menu accounts for all dietary restrictions',
    sort_order: 2,
    is_required: true,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 5,
    stage_name: 'menu_planning',
    checkpoint_key: 's5_draft_sent',
    checkpoint_label: 'Draft menu sent to host for feedback',
    sort_order: 3,
    is_required: true,
    auto_detect_rule: null,
    client_visible: true,
    client_label: 'Menu draft sent',
  },
  {
    stage_number: 5,
    stage_name: 'menu_planning',
    checkpoint_key: 's5_host_feedback_received',
    checkpoint_label: 'Host feedback received',
    sort_order: 4,
    is_required: false,
    auto_detect_rule: 'text_match:menu_feedback',
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 5,
    stage_name: 'menu_planning',
    checkpoint_key: 's5_menu_revised',
    checkpoint_label: 'Menu revised based on feedback',
    sort_order: 5,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 5,
    stage_name: 'menu_planning',
    checkpoint_key: 's5_course_timing_planned',
    checkpoint_label: 'Course timing and flow planned',
    sort_order: 6,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 5,
    stage_name: 'menu_planning',
    checkpoint_key: 's5_plating_decided',
    checkpoint_label: 'Plating style decided',
    sort_order: 7,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 5,
    stage_name: 'menu_planning',
    checkpoint_key: 's5_pairings_selected',
    checkpoint_label: 'Wine/cocktail pairings selected',
    sort_order: 8,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 5,
    stage_name: 'menu_planning',
    checkpoint_key: 's5_menu_descriptions_written',
    checkpoint_label: 'Menu descriptions written',
    sort_order: 9,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 5,
    stage_name: 'menu_planning',
    checkpoint_key: 's5_final_menu_confirmed',
    checkpoint_label: 'Final menu confirmed by host',
    sort_order: 10,
    is_required: true,
    auto_detect_rule: null,
    client_visible: true,
    client_label: 'Menu finalized',
  },
  {
    stage_number: 5,
    stage_name: 'menu_planning',
    checkpoint_key: 's5_final_menu_locked',
    checkpoint_label: 'Final menu locked',
    sort_order: 11,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 5,
    stage_name: 'menu_planning',
    checkpoint_key: 's5_menu_shared_guests',
    checkpoint_label: 'Menu shared with guests',
    sort_order: 12,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 5,
    stage_name: 'menu_planning',
    checkpoint_key: 's5_menu_cards_prepared',
    checkpoint_label: 'Menu cards prepared',
    sort_order: 13,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
]

// ---------------------------------------------------------------------------
// Stage 6: Pre-Service Logistics
// ---------------------------------------------------------------------------
const STAGE_6: CheckpointDef[] = [
  {
    stage_number: 6,
    stage_name: 'pre_service',
    checkpoint_key: 's6_final_guest_count',
    checkpoint_label: 'Final guest count confirmed',
    sort_order: 1,
    is_required: true,
    auto_detect_rule: null,
    client_visible: true,
    client_label: 'Final guest count locked',
  },
  {
    stage_number: 6,
    stage_name: 'pre_service',
    checkpoint_key: 's6_final_dietary_recheck',
    checkpoint_label: 'Final dietary re-check',
    sort_order: 2,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 6,
    stage_name: 'pre_service',
    checkpoint_key: 's6_final_menu_adjustments',
    checkpoint_label: 'Final menu adjustments',
    sort_order: 3,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 6,
    stage_name: 'pre_service',
    checkpoint_key: 's6_arrival_time_confirmed',
    checkpoint_label: 'Arrival time confirmed with host',
    sort_order: 4,
    is_required: true,
    auto_detect_rule: null,
    client_visible: true,
    client_label: 'Arrival time set',
  },
  {
    stage_number: 6,
    stage_name: 'pre_service',
    checkpoint_key: 's6_parking_confirmed',
    checkpoint_label: 'Parking logistics confirmed',
    sort_order: 5,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 6,
    stage_name: 'pre_service',
    checkpoint_key: 's6_confirmation_sent',
    checkpoint_label: 'Confirmation message sent to host',
    sort_order: 6,
    is_required: false,
    auto_detect_rule: 'text_match:confirmation',
    client_visible: true,
    client_label: 'Confirmation received',
  },
  {
    stage_number: 6,
    stage_name: 'pre_service',
    checkpoint_key: 's6_host_reminded',
    checkpoint_label: 'Host reminded of their responsibilities',
    sort_order: 7,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 6,
    stage_name: 'pre_service',
    checkpoint_key: 's6_shopping_list_built',
    checkpoint_label: 'Shopping list built from final menu',
    sort_order: 8,
    is_required: true,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 6,
    stage_name: 'pre_service',
    checkpoint_key: 's6_grocery_budget_approved',
    checkpoint_label: 'Grocery budget approved',
    sort_order: 9,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 6,
    stage_name: 'pre_service',
    checkpoint_key: 's6_sourcing_preferences',
    checkpoint_label: 'Sourcing preferences confirmed',
    sort_order: 10,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 6,
    stage_name: 'pre_service',
    checkpoint_key: 's6_substitution_protocol',
    checkpoint_label: 'Substitution protocol agreed',
    sort_order: 11,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 6,
    stage_name: 'pre_service',
    checkpoint_key: 's6_specialty_ordered',
    checkpoint_label: 'Specialty items ordered in advance',
    sort_order: 12,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 6,
    stage_name: 'pre_service',
    checkpoint_key: 's6_groceries_purchased',
    checkpoint_label: 'Groceries purchased',
    sort_order: 13,
    is_required: true,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 6,
    stage_name: 'pre_service',
    checkpoint_key: 's6_grocery_receipts_saved',
    checkpoint_label: 'Grocery receipts saved',
    sort_order: 14,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 6,
    stage_name: 'pre_service',
    checkpoint_key: 's6_items_verified',
    checkpoint_label: 'All items verified against shopping list',
    sort_order: 15,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 6,
    stage_name: 'pre_service',
    checkpoint_key: 's6_equipment_checklist',
    checkpoint_label: 'Equipment checklist prepared',
    sort_order: 16,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 6,
    stage_name: 'pre_service',
    checkpoint_key: 's6_equipment_packed',
    checkpoint_label: 'Equipment packed and loaded',
    sort_order: 17,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 6,
    stage_name: 'pre_service',
    checkpoint_key: 's6_rentals_arranged',
    checkpoint_label: 'Rentals arranged',
    sort_order: 18,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 6,
    stage_name: 'pre_service',
    checkpoint_key: 's6_staff_sourced',
    checkpoint_label: 'Staff sourced and confirmed',
    sort_order: 19,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 6,
    stage_name: 'pre_service',
    checkpoint_key: 's6_staff_confirmed',
    checkpoint_label: 'Staff confirmed',
    sort_order: 20,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 6,
    stage_name: 'pre_service',
    checkpoint_key: 's6_staff_briefed',
    checkpoint_label: 'Staff briefed on menu and service',
    sort_order: 21,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 6,
    stage_name: 'pre_service',
    checkpoint_key: 's6_staff_arrival_confirmed',
    checkpoint_label: 'Staff arrival time confirmed',
    sort_order: 22,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 6,
    stage_name: 'pre_service',
    checkpoint_key: 's6_prep_timeline_built',
    checkpoint_label: 'Prep timeline built',
    sort_order: 23,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 6,
    stage_name: 'pre_service',
    checkpoint_key: 's6_day_before_prep',
    checkpoint_label: 'Day-before prep completed',
    sort_order: 24,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 6,
    stage_name: 'pre_service',
    checkpoint_key: 's6_course_timeline_built',
    checkpoint_label: 'Course-by-course execution timeline built',
    sort_order: 25,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 6,
    stage_name: 'pre_service',
    checkpoint_key: 's6_vendor_synced',
    checkpoint_label: 'Vendor timelines aligned',
    sort_order: 26,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
]

// ---------------------------------------------------------------------------
// Stage 7: Payment
// ---------------------------------------------------------------------------
const STAGE_7: CheckpointDef[] = [
  {
    stage_number: 7,
    stage_name: 'payment',
    checkpoint_key: 's7_remaining_balance_calculated',
    checkpoint_label: 'Remaining balance calculated',
    sort_order: 1,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 7,
    stage_name: 'payment',
    checkpoint_key: 's7_grocery_costs_finalized',
    checkpoint_label: 'Grocery costs finalized',
    sort_order: 2,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 7,
    stage_name: 'payment',
    checkpoint_key: 's7_additional_charges_itemized',
    checkpoint_label: 'Additional charges itemized',
    sort_order: 3,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 7,
    stage_name: 'payment',
    checkpoint_key: 's7_credits_applied',
    checkpoint_label: 'Credits applied',
    sort_order: 4,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 7,
    stage_name: 'payment',
    checkpoint_key: 's7_final_invoice_sent',
    checkpoint_label: 'Final invoice sent',
    sort_order: 5,
    is_required: false,
    auto_detect_rule: null,
    client_visible: true,
    client_label: 'Invoice sent',
  },
  {
    stage_number: 7,
    stage_name: 'payment',
    checkpoint_key: 's7_payment_method_confirmed',
    checkpoint_label: 'Payment method confirmed',
    sort_order: 6,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 7,
    stage_name: 'payment',
    checkpoint_key: 's7_payment_due_communicated',
    checkpoint_label: 'Payment due date communicated',
    sort_order: 7,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 7,
    stage_name: 'payment',
    checkpoint_key: 's7_final_payment_received',
    checkpoint_label: 'Final payment received',
    sort_order: 8,
    is_required: true,
    auto_detect_rule: 'event_status:paid',
    client_visible: true,
    client_label: 'Payment completed',
  },
  {
    stage_number: 7,
    stage_name: 'payment',
    checkpoint_key: 's7_payment_receipt_sent',
    checkpoint_label: 'Payment receipt sent',
    sort_order: 9,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 7,
    stage_name: 'payment',
    checkpoint_key: 's7_grocery_receipts_shared',
    checkpoint_label: 'Grocery receipts shared with client',
    sort_order: 10,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 7,
    stage_name: 'payment',
    checkpoint_key: 's7_gratuity_received',
    checkpoint_label: 'Gratuity received',
    sort_order: 11,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 7,
    stage_name: 'payment',
    checkpoint_key: 's7_gratuity_distributed',
    checkpoint_label: 'Gratuity distributed to staff',
    sort_order: 12,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 7,
    stage_name: 'payment',
    checkpoint_key: 's7_tax_docs_prepared',
    checkpoint_label: 'Tax documentation prepared',
    sort_order: 13,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 7,
    stage_name: 'payment',
    checkpoint_key: 's7_financial_reconciliation',
    checkpoint_label: 'Financial reconciliation complete',
    sort_order: 14,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
]

// ---------------------------------------------------------------------------
// Stage 8: Service Day
// ---------------------------------------------------------------------------
const STAGE_8: CheckpointDef[] = [
  {
    stage_number: 8,
    stage_name: 'service_day',
    checkpoint_key: 's8_arrived_on_time',
    checkpoint_label: 'Arrived at venue on time',
    sort_order: 1,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 8,
    stage_name: 'service_day',
    checkpoint_key: 's8_venue_walkthrough',
    checkpoint_label: 'Venue walkthrough completed',
    sort_order: 2,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 8,
    stage_name: 'service_day',
    checkpoint_key: 's8_equipment_setup',
    checkpoint_label: 'Equipment unloaded and set up',
    sort_order: 3,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 8,
    stage_name: 'service_day',
    checkpoint_key: 's8_staff_arrived',
    checkpoint_label: 'Staff arrived and briefed',
    sort_order: 4,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 8,
    stage_name: 'service_day',
    checkpoint_key: 's8_welcome_interaction',
    checkpoint_label: 'Welcome interaction with host',
    sort_order: 5,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 8,
    stage_name: 'service_day',
    checkpoint_key: 's8_courses_executed',
    checkpoint_label: 'All courses executed on timeline',
    sort_order: 6,
    is_required: true,
    auto_detect_rule: 'event_status:completed',
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 8,
    stage_name: 'service_day',
    checkpoint_key: 's8_dietary_plates_correct',
    checkpoint_label: 'Dietary-restricted plates served correctly',
    sort_order: 7,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 8,
    stage_name: 'service_day',
    checkpoint_key: 's8_pacing_adjusted',
    checkpoint_label: 'Pacing adjusted based on guest energy',
    sort_order: 8,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 8,
    stage_name: 'service_day',
    checkpoint_key: 's8_realtime_adjustments',
    checkpoint_label: 'Real-time adjustments noted',
    sort_order: 9,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 8,
    stage_name: 'service_day',
    checkpoint_key: 's8_kitchen_cleaned',
    checkpoint_label: 'Kitchen cleaned to pre-arrival condition',
    sort_order: 10,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 8,
    stage_name: 'service_day',
    checkpoint_key: 's8_equipment_packed',
    checkpoint_label: 'All equipment packed',
    sort_order: 11,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 8,
    stage_name: 'service_day',
    checkpoint_key: 's8_trash_removed',
    checkpoint_label: 'Trash taken out',
    sort_order: 12,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 8,
    stage_name: 'service_day',
    checkpoint_key: 's8_leftovers_packaged',
    checkpoint_label: 'Leftovers packaged and labeled',
    sort_order: 13,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 8,
    stage_name: 'service_day',
    checkpoint_key: 's8_final_checkin_host',
    checkpoint_label: 'Final check-in with host',
    sort_order: 14,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 8,
    stage_name: 'service_day',
    checkpoint_key: 's8_departure_noted',
    checkpoint_label: 'Departure time noted',
    sort_order: 15,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
]

// ---------------------------------------------------------------------------
// Stage 9: Post-Service
// ---------------------------------------------------------------------------
const STAGE_9: CheckpointDef[] = [
  {
    stage_number: 9,
    stage_name: 'post_service',
    checkpoint_key: 's9_thank_you_sent',
    checkpoint_label: 'Thank you message sent',
    sort_order: 1,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 9,
    stage_name: 'post_service',
    checkpoint_key: 's9_personal_touch_included',
    checkpoint_label: 'Personal touch included',
    sort_order: 2,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 9,
    stage_name: 'post_service',
    checkpoint_key: 's9_photos_shared',
    checkpoint_label: 'Photos shared',
    sort_order: 3,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 9,
    stage_name: 'post_service',
    checkpoint_key: 's9_leftover_instructions',
    checkpoint_label: 'Leftover storage instructions sent',
    sort_order: 4,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 9,
    stage_name: 'post_service',
    checkpoint_key: 's9_review_requested',
    checkpoint_label: 'Review request sent',
    sort_order: 5,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 9,
    stage_name: 'post_service',
    checkpoint_key: 's9_review_link_sent',
    checkpoint_label: 'Review link provided',
    sort_order: 6,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 9,
    stage_name: 'post_service',
    checkpoint_key: 's9_review_received',
    checkpoint_label: 'Review received',
    sort_order: 7,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 9,
    stage_name: 'post_service',
    checkpoint_key: 's9_review_responded',
    checkpoint_label: 'Review responded to',
    sort_order: 8,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 9,
    stage_name: 'post_service',
    checkpoint_key: 's9_testimonial_permission',
    checkpoint_label: 'Testimonial permission requested',
    sort_order: 9,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 9,
    stage_name: 'post_service',
    checkpoint_key: 's9_negative_feedback_addressed',
    checkpoint_label: 'Negative feedback addressed',
    sort_order: 10,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 9,
    stage_name: 'post_service',
    checkpoint_key: 's9_payments_reconciled',
    checkpoint_label: 'All payments reconciled',
    sort_order: 11,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 9,
    stage_name: 'post_service',
    checkpoint_key: 's9_outstanding_balance_followed',
    checkpoint_label: 'Outstanding balance followed up',
    sort_order: 12,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 9,
    stage_name: 'post_service',
    checkpoint_key: 's9_grocery_reconciliation_shared',
    checkpoint_label: 'Grocery reconciliation shared',
    sort_order: 13,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 9,
    stage_name: 'post_service',
    checkpoint_key: 's9_after_action_notes',
    checkpoint_label: 'After-action notes captured',
    sort_order: 14,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 9,
    stage_name: 'post_service',
    checkpoint_key: 's9_guest_preferences_noted',
    checkpoint_label: 'Guest preferences noted for future',
    sort_order: 15,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 9,
    stage_name: 'post_service',
    checkpoint_key: 's9_venue_notes_updated',
    checkpoint_label: 'Venue notes updated',
    sort_order: 16,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 9,
    stage_name: 'post_service',
    checkpoint_key: 's9_staff_performance_noted',
    checkpoint_label: 'Staff performance noted',
    sort_order: 17,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 9,
    stage_name: 'post_service',
    checkpoint_key: 's9_time_tracking_completed',
    checkpoint_label: 'Time tracking completed',
    sort_order: 18,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 9,
    stage_name: 'post_service',
    checkpoint_key: 's9_profitability_calculated',
    checkpoint_label: 'Profitability calculated',
    sort_order: 19,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
]

// ---------------------------------------------------------------------------
// Stage 10: Client Lifecycle
// ---------------------------------------------------------------------------
const STAGE_10: CheckpointDef[] = [
  {
    stage_number: 10,
    stage_name: 'client_lifecycle',
    checkpoint_key: 's10_profile_updated',
    checkpoint_label: 'Client profile updated with all preferences',
    sort_order: 1,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 10,
    stage_name: 'client_lifecycle',
    checkpoint_key: 's10_client_tier_classified',
    checkpoint_label: 'Client tier classified',
    sort_order: 2,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 10,
    stage_name: 'client_lifecycle',
    checkpoint_key: 's10_preferred_menu_documented',
    checkpoint_label: 'Preferred menu styles documented',
    sort_order: 3,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 10,
    stage_name: 'client_lifecycle',
    checkpoint_key: 's10_comm_style_noted',
    checkpoint_label: 'Communication style noted',
    sort_order: 4,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 10,
    stage_name: 'client_lifecycle',
    checkpoint_key: 's10_key_dates_captured',
    checkpoint_label: 'Key dates captured (birthdays, anniversaries)',
    sort_order: 5,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 10,
    stage_name: 'client_lifecycle',
    checkpoint_key: 's10_household_changes_tracked',
    checkpoint_label: 'Household changes tracked',
    sort_order: 6,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 10,
    stage_name: 'client_lifecycle',
    checkpoint_key: 's10_rebooking_follow_up_sent',
    checkpoint_label: 'Rebooking follow-up sent',
    sort_order: 7,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 10,
    stage_name: 'client_lifecycle',
    checkpoint_key: 's10_seasonal_outreach_sent',
    checkpoint_label: 'Seasonal outreach sent',
    sort_order: 8,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 10,
    stage_name: 'client_lifecycle',
    checkpoint_key: 's10_anniversary_acknowledged',
    checkpoint_label: 'Anniversary of first booking acknowledged',
    sort_order: 9,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 10,
    stage_name: 'client_lifecycle',
    checkpoint_key: 's10_recurring_template_created',
    checkpoint_label: 'Recurring booking template created',
    sort_order: 10,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 10,
    stage_name: 'client_lifecycle',
    checkpoint_key: 's10_win_back_triggered',
    checkpoint_label: 'Win-back campaign triggered',
    sort_order: 11,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 10,
    stage_name: 'client_lifecycle',
    checkpoint_key: 's10_referral_requested',
    checkpoint_label: 'Referral request made',
    sort_order: 12,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 10,
    stage_name: 'client_lifecycle',
    checkpoint_key: 's10_referral_tracked',
    checkpoint_label: 'Referral tracked',
    sort_order: 13,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
  {
    stage_number: 10,
    stage_name: 'client_lifecycle',
    checkpoint_key: 's10_client_featured_marketing',
    checkpoint_label: 'Client featured in marketing',
    sort_order: 14,
    is_required: false,
    auto_detect_rule: null,
    client_visible: false,
    client_label: null,
  },
]

// ---------------------------------------------------------------------------
// All checkpoints combined
// ---------------------------------------------------------------------------
const ALL_CHECKPOINTS: CheckpointDef[] = [
  ...STAGE_1,
  ...STAGE_2,
  ...STAGE_3,
  ...STAGE_4,
  ...STAGE_5,
  ...STAGE_6,
  ...STAGE_7,
  ...STAGE_8,
  ...STAGE_9,
  ...STAGE_10,
]

// ---------------------------------------------------------------------------
// ensureTemplateSeeded - idempotent, safe to call from anywhere
// Uses admin client (no requireChef) so it works from Gmail sync pipeline.
// ---------------------------------------------------------------------------
export async function ensureTemplateSeeded(
  chefId: string
): Promise<{ success: boolean; checkpointCount: number }> {
  const db = createServerClient({ admin: true })

  // Check if already seeded (fast path)
  const { data: existing } = await db
    .from('service_lifecycle_templates')
    .select('id')
    .eq('chef_id', chefId)
    .limit(1)

  if (existing && existing.length > 0) {
    return { success: true, checkpointCount: ALL_CHECKPOINTS.length }
  }

  // Seed all checkpoints in a single batch INSERT for performance (~150 rows, one round-trip)
  const rows = ALL_CHECKPOINTS.map((cp) => ({
    chef_id: chefId,
    stage_number: cp.stage_number,
    stage_name: cp.stage_name,
    checkpoint_key: cp.checkpoint_key,
    checkpoint_label: cp.checkpoint_label,
    sort_order: cp.sort_order,
    is_active: true,
    is_required: cp.is_required,
    auto_detect_rule: cp.auto_detect_rule,
    client_visible: cp.client_visible,
    client_label: cp.client_label,
  }))

  await db.from('service_lifecycle_templates').upsert(rows, {
    onConflict: 'chef_id,checkpoint_key',
  })

  return { success: true, checkpointCount: ALL_CHECKPOINTS.length }
}

// Export for use by detector to know which rules exist
export { ALL_CHECKPOINTS }
export type { CheckpointDef }
