export type CronMonitorDefinition = {
  cronName: string
  routePath: string
  maxExpectedMinutes: number
  cadence: '5m' | '15m' | '30m' | 'hourly' | '6h' | 'daily'
  description: string
}

export const CRON_MONITOR_DEFINITIONS: CronMonitorDefinition[] = [
  {
    cronName: 'gmail-sync',
    routePath: '/api/gmail/sync',
    maxExpectedMinutes: 10,
    cadence: '5m',
    description: 'Gmail inbox sync sweep for connected chefs',
  },
  {
    cronName: 'integrations-pull',
    routePath: '/api/scheduled/integrations/pull',
    maxExpectedMinutes: 10,
    cadence: '5m',
    description: 'Pull pending integration events into the processing pipeline',
  },
  {
    cronName: 'social-publish',
    routePath: '/api/scheduled/social-publish',
    maxExpectedMinutes: 10,
    cadence: '5m',
    description: 'Publish queued social posts through connected adapters',
  },
  {
    cronName: 'wix-process',
    routePath: '/api/scheduled/wix-process',
    maxExpectedMinutes: 10,
    cadence: '5m',
    description: 'Retry queued or failed Wix submissions',
  },
  {
    cronName: 'ai-queue-drain',
    routePath: '/api/scheduled/ai-queue-drain',
    maxExpectedMinutes: 5,
    cadence: '15m',
    description: 'Ensure the background AI task worker poll loop is running',
  },
  {
    cronName: 'automations',
    routePath: '/api/scheduled/automations',
    maxExpectedMinutes: 30,
    cadence: '15m',
    description: 'Evaluate automation triggers and reminder rules',
  },
  {
    cronName: 'copilot',
    routePath: '/api/scheduled/copilot',
    maxExpectedMinutes: 30,
    cadence: '15m',
    description: 'Generate ops copilot planning runs for active tenants',
  },
  {
    cronName: 'email-history-scan',
    routePath: '/api/scheduled/email-history-scan',
    maxExpectedMinutes: 30,
    cadence: '15m',
    description: 'Process opted-in Gmail historical scan batches',
  },
  {
    cronName: 'passive-store-sync',
    routePath: '/api/scheduled/passive-store-sync',
    maxExpectedMinutes: 30,
    cadence: '15m',
    description: 'Passive storefront product freshness sync',
  },
  {
    cronName: 'call-reminders',
    routePath: '/api/scheduled/call-reminders',
    maxExpectedMinutes: 60,
    cadence: '30m',
    description: 'Send 24-hour and 1-hour scheduled call reminders',
  },
  {
    cronName: 'campaigns',
    routePath: '/api/scheduled/campaigns',
    maxExpectedMinutes: 120,
    cadence: 'hourly',
    description: 'Fire scheduled marketing campaigns',
  },
  {
    cronName: 'circle-digest',
    routePath: '/api/cron/circle-digest',
    maxExpectedMinutes: 120,
    cadence: 'hourly',
    description: 'Send hourly and daily Circle digests',
  },
  {
    cronName: 'event-progression',
    routePath: '/api/cron/event-progression',
    maxExpectedMinutes: 120,
    cadence: 'hourly',
    description: 'Advance event statuses from wall-clock time',
  },
  {
    cronName: 'integrations-retry',
    routePath: '/api/scheduled/integrations/retry',
    maxExpectedMinutes: 120,
    cadence: 'hourly',
    description: 'Retry failed integration events with a larger batch size',
  },
  {
    cronName: 'rsvp-reminders',
    routePath: '/api/scheduled/rsvp-reminders',
    maxExpectedMinutes: 120,
    cadence: 'hourly',
    description: 'Email RSVP reminder nudges before shared events',
  },
  {
    cronName: 'proactive-alerts',
    routePath: '/api/scheduled/proactive-alerts',
    maxExpectedMinutes: 120,
    cadence: 'hourly',
    description: 'Run Remy alert rules for all active tenants',
  },
  {
    cronName: 'scheduled-messages',
    routePath: '/api/scheduled/messages',
    maxExpectedMinutes: 30,
    cadence: '15m',
    description: 'Deliver due scheduled messages via email and other channels',
  },
  {
    cronName: 'stale-leads',
    routePath: '/api/scheduled/stale-leads',
    maxExpectedMinutes: 120,
    cadence: 'hourly',
    description: 'Alert chefs when marketplace leads sit untouched for 24 hours',
  },
  {
    cronName: 'stale-draft-cleanup',
    routePath: '/api/scheduled/stale-draft-cleanup',
    maxExpectedMinutes: 120,
    cadence: 'daily',
    description:
      'Delete stale inquiry reply drafts older than 3 days so fresh ones are regenerated',
  },
  {
    cronName: 'stale-ticket-cleanup',
    routePath: '/api/scheduled/stale-ticket-cleanup',
    maxExpectedMinutes: 120,
    cadence: 'hourly',
    description: 'Cancel verified stale pending event tickets and release reserved capacity',
  },
  {
    cronName: 'ticket-reconciliation',
    routePath: '/api/scheduled/ticket-reconciliation',
    maxExpectedMinutes: 120,
    cadence: 'hourly',
    description: 'Audit event ticket inventory against orders and reservations',
  },
  {
    cronName: 'follow-ups',
    routePath: '/api/scheduled/follow-ups',
    maxExpectedMinutes: 720,
    cadence: '6h',
    description: 'Notify chefs about overdue inquiry follow-ups',
  },
  {
    cronName: 'proactive-drafts',
    routePath: '/api/scheduled/proactive-drafts',
    maxExpectedMinutes: 720,
    cadence: '6h',
    description: 'Auto-generate reply drafts for inquiries awaiting chef response',
  },
  {
    cronName: 'reviews-sync',
    routePath: '/api/scheduled/reviews-sync',
    maxExpectedMinutes: 720,
    cadence: '6h',
    description: 'Sync active external review sources into ChefFlow',
  },
  {
    cronName: 'revenue-goals',
    routePath: '/api/scheduled/revenue-goals',
    maxExpectedMinutes: 720,
    cadence: '6h',
    description: 'Refresh revenue-goal milestones and weekly digest signals',
  },
  {
    cronName: 'revenue-forecast',
    routePath: '/api/scheduled/revenue-forecast',
    maxExpectedMinutes: 1440,
    cadence: 'daily',
    description: 'Persist 3-, 6-, and 12-month revenue forecast snapshots for each tenant',
  },
  {
    cronName: 'simulation-check',
    routePath: '/api/scheduled/simulation/check',
    maxExpectedMinutes: 720,
    cadence: '6h',
    description: 'Check whether a new tenant simulation run is due',
  },
  {
    cronName: 'service-readiness',
    routePath: '/api/scheduled/service-readiness',
    maxExpectedMinutes: 720,
    cadence: '6h',
    description: 'Refresh event service readiness simulations for active events',
  },
  {
    cronName: 'wellbeing-signals',
    routePath: '/api/scheduled/wellbeing-signals',
    maxExpectedMinutes: 720,
    cadence: '6h',
    description: 'Emit burnout, capacity, and education wellbeing signals',
  },
  {
    cronName: 'account-purge',
    routePath: '/api/cron/account-purge',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Purge deleted accounts after the grace period expires',
  },
  {
    cronName: 'db-backup',
    routePath: '/api/cron/backup-heartbeat',
    maxExpectedMinutes: 1440,
    cadence: 'daily',
    description: 'Automated database backup (dump, encrypt, verify, prune)',
  },
  {
    cronName: 'activity-cleanup',
    routePath: '/api/scheduled/activity-cleanup',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Clean up aged activity, notifications, and stale records',
  },
  {
    cronName: 'brand-monitor',
    routePath: '/api/cron/brand-monitor',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Scan brand mentions and record notable findings',
  },
  {
    cronName: 'cooling-alert',
    routePath: '/api/cron/cooling-alert',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Detect and notify on cooling inventory anomalies',
  },
  {
    cronName: 'daily-report',
    routePath: '/api/scheduled/daily-report',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Generate chef daily reports (email delivery opt-in)',
  },
  {
    cronName: 'developer-digest',
    routePath: '/api/cron/developer-digest',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Send the developer system-health digest',
  },
  {
    cronName: 'platform-observability-digest',
    routePath: '/api/cron/platform-observability-digest',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Send the platform observability digest',
  },
  {
    cronName: 'lifecycle',
    routePath: '/api/scheduled/lifecycle',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Expire stale workflows and send lifecycle reminders',
  },
  {
    cronName: 'loyalty-expiry',
    routePath: '/api/scheduled/loyalty-expiry',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Expire loyalty points and rewards on schedule',
  },
  {
    cronName: 'momentum-snapshot',
    routePath: '/api/cron/momentum-snapshot',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Persist daily chef momentum snapshots',
  },
  {
    cronName: 'morning-briefing',
    routePath: '/api/cron/morning-briefing',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Generate the deterministic morning briefing for each tenant',
  },
  {
    cronName: `open${'claw'}-polish`,
    routePath: `/api/cron/open${'claw'}-polish`,
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Run enrichment and data polish after sync',
  },
  {
    cronName: `open${'claw'}-sync`,
    routePath: `/api/cron/open${'claw'}-sync`,
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Ingest nightly data cartridge updates',
  },
  {
    cronName: 'price-sync',
    routePath: '/api/cron/price-sync',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Legacy nightly price sync',
  },
  {
    cronName: 'push-cleanup',
    routePath: '/api/scheduled/push-cleanup',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Remove stale push subscriptions and aged notification logs',
  },
  {
    cronName: 'quarterly-checkin',
    routePath: '/api/cron/quarterly-checkin',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Trigger quarterly business-health check-in reminders',
  },
  {
    cronName: 'raffle-draw',
    routePath: '/api/scheduled/raffle-draw',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Close and settle active raffle rounds',
  },
  {
    cronName: 'recall-check',
    routePath: '/api/cron/recall-check',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Scan FDA recalls against ingredient inventory',
  },
  {
    cronName: 'renewal-reminders',
    routePath: '/api/cron/renewal-reminders',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Send insurance and certification renewal reminders',
  },
  {
    cronName: 'rsvp-retention',
    routePath: '/api/scheduled/rsvp-retention',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Purge old RSVP exports and reminder retention data',
  },
  {
    cronName: 'sequences',
    routePath: '/api/scheduled/sequences',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Process marketing sequences and birthday enrollments',
  },
  {
    cronName: 'waitlist-sweep',
    routePath: '/api/scheduled/waitlist-sweep',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Sweep waitlist entries and notify newly open dates',
  },
  {
    cronName: 'client-reengagement',
    routePath: '/api/scheduled/client-reengagement',
    maxExpectedMinutes: 5,
    cadence: 'daily',
    description: 'Weekly re-engagement emails for dormant clients (60-90 day window)',
  },
  {
    cronName: 'inquiry-client-followup',
    routePath: '/api/scheduled/inquiry-client-followup',
    maxExpectedMinutes: 5,
    cadence: '6h',
    description: 'Follow-up email to clients with 48h+ unanswered inquiries',
  },
  {
    cronName: 'email-retry',
    routePath: '/api/cron/email-retry',
    maxExpectedMinutes: 15,
    cadence: '5m',
    description: 'Retry failed emails from the dead-letter queue',
  },
  {
    cronName: 'client-followup-rules',
    routePath: '/api/scheduled/client-followup-rules',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Evaluate chef-configured follow-up rules (birthday, dormancy)',
  },
  {
    cronName: 'dormancy-nudge',
    routePath: '/api/scheduled/dormancy-nudge',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Re-engagement emails for chefs inactive 30+ days',
  },
  {
    cronName: 'monitor',
    routePath: '/api/scheduled/monitor',
    maxExpectedMinutes: 120,
    cadence: 'hourly',
    description: 'Cron health monitor: staleness, error rates, alerts',
  },
  {
    cronName: 'simulation',
    routePath: '/api/scheduled/simulation',
    maxExpectedMinutes: 720,
    cadence: '6h',
    description: 'Run tenant simulation scenarios via AI',
  },
  {
    cronName: 'waitlist-directory-sweep',
    routePath: '/api/scheduled/waitlist-directory-sweep',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Match directory waitlist entries to discoverable chefs',
  },
  {
    cronName: 'booking-escalation',
    routePath: '/api/cron/booking-escalation',
    maxExpectedMinutes: 360,
    cadence: '6h',
    description: 'Send follow-up emails for open bookings with no chef response (48h and 7d)',
  },
]

export const CRON_MONITOR_DEFINITION_MAP = new Map(
  CRON_MONITOR_DEFINITIONS.map((definition) => [definition.cronName, definition])
)
