export type CronMonitorDefinition = {
  cronName: string
  routePath: string
  maxExpectedMinutes: number
  cadence: '5m' | '15m' | '30m' | 'hourly' | '6h' | 'daily'
  description: string
}

export const CRON_MONITOR_DEFINITIONS: CronMonitorDefinition[] = [
  {
    cronName: 'gmail-sync',
    routePath: '/api/gmail/sync',
    maxExpectedMinutes: 10,
    cadence: '5m',
    description: 'Gmail inbox sync sweep for connected chefs',
  },
  {
    cronName: 'integrations-pull',
    routePath: '/api/scheduled/integrations/pull',
    maxExpectedMinutes: 10,
    cadence: '5m',
    description: 'Pull pending integration events into the processing pipeline',
  },
  {
    cronName: 'social-publish',
    routePath: '/api/scheduled/social-publish',
    maxExpectedMinutes: 10,
    cadence: '5m',
    description: 'Publish queued social posts through connected adapters',
  },
  {
    cronName: 'wix-process',
    routePath: '/api/scheduled/wix-process',
    maxExpectedMinutes: 10,
    cadence: '5m',
    description: 'Retry queued or failed Wix submissions',
  },
  {
    cronName: 'automations',
    routePath: '/api/scheduled/automations',
    maxExpectedMinutes: 30,
    cadence: '15m',
    description: 'Evaluate automation triggers and reminder rules',
  },
  {
    cronName: 'copilot',
    routePath: '/api/scheduled/copilot',
    maxExpectedMinutes: 30,
    cadence: '15m',
    description: 'Generate ops copilot planning runs for active tenants',
  },
  {
    cronName: 'email-history-scan',
    routePath: '/api/scheduled/email-history-scan',
    maxExpectedMinutes: 30,
    cadence: '15m',
    description: 'Process opted-in Gmail historical scan batches',
  },
  {
    cronName: 'call-reminders',
    routePath: '/api/scheduled/call-reminders',
    maxExpectedMinutes: 60,
    cadence: '30m',
    description: 'Send 24-hour and 1-hour scheduled call reminders',
  },
  {
    cronName: 'campaigns',
    routePath: '/api/scheduled/campaigns',
    maxExpectedMinutes: 120,
    cadence: 'hourly',
    description: 'Fire scheduled marketing campaigns',
  },
  {
    cronName: 'circle-digest',
    routePath: '/api/cron/circle-digest',
    maxExpectedMinutes: 120,
    cadence: 'hourly',
    description: 'Send hourly and daily Circle digests',
  },
  {
    cronName: 'event-progression',
    routePath: '/api/cron/event-progression',
    maxExpectedMinutes: 120,
    cadence: 'hourly',
    description: 'Advance event statuses from wall-clock time',
  },
  {
    cronName: 'integrations-retry',
    routePath: '/api/scheduled/integrations/retry',
    maxExpectedMinutes: 120,
    cadence: 'hourly',
    description: 'Retry failed integration events with a larger batch size',
  },
  {
    cronName: 'rsvp-reminders',
    routePath: '/api/scheduled/rsvp-reminders',
    maxExpectedMinutes: 120,
    cadence: 'hourly',
    description: 'Email RSVP reminder nudges before shared events',
  },
  {
    cronName: 'stale-leads',
    routePath: '/api/scheduled/stale-leads',
    maxExpectedMinutes: 120,
    cadence: 'hourly',
    description: 'Alert chefs when marketplace leads sit untouched for 24 hours',
  },
  {
    cronName: 'follow-ups',
    routePath: '/api/scheduled/follow-ups',
    maxExpectedMinutes: 720,
    cadence: '6h',
    description: 'Notify chefs about overdue inquiry follow-ups',
  },
  {
    cronName: 'reviews-sync',
    routePath: '/api/scheduled/reviews-sync',
    maxExpectedMinutes: 720,
    cadence: '6h',
    description: 'Sync active external review sources into ChefFlow',
  },
  {
    cronName: 'revenue-goals',
    routePath: '/api/scheduled/revenue-goals',
    maxExpectedMinutes: 720,
    cadence: '6h',
    description: 'Refresh revenue-goal milestones and weekly digest signals',
  },
  {
    cronName: 'simulation-check',
    routePath: '/api/scheduled/simulation/check',
    maxExpectedMinutes: 720,
    cadence: '6h',
    description: 'Check whether a new tenant simulation run is due',
  },
  {
    cronName: 'wellbeing-signals',
    routePath: '/api/scheduled/wellbeing-signals',
    maxExpectedMinutes: 720,
    cadence: '6h',
    description: 'Emit burnout, capacity, and education wellbeing signals',
  },
  {
    cronName: 'account-purge',
    routePath: '/api/cron/account-purge',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Purge deleted accounts after the grace period expires',
  },
  {
    cronName: 'db-backup',
    routePath: '/api/cron/backup-heartbeat',
    maxExpectedMinutes: 1440,
    cadence: 'daily',
    description: 'Automated database backup (dump, encrypt, verify, prune)',
  },
  {
    cronName: 'activity-cleanup',
    routePath: '/api/scheduled/activity-cleanup',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Clean up aged activity, notifications, and stale records',
  },
  {
    cronName: 'brand-monitor',
    routePath: '/api/cron/brand-monitor',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Scan brand mentions and record notable findings',
  },
  {
    cronName: 'cooling-alert',
    routePath: '/api/cron/cooling-alert',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Detect and notify on cooling inventory anomalies',
  },
  {
    cronName: 'daily-report',
    routePath: '/api/scheduled/daily-report',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Generate and email chef daily reports',
  },
  {
    cronName: 'developer-digest',
    routePath: '/api/cron/developer-digest',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Send the developer system-health digest',
  },
  {
    cronName: 'platform-observability-digest',
    routePath: '/api/cron/platform-observability-digest',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Send the platform observability digest',
  },
  {
    cronName: 'lifecycle',
    routePath: '/api/scheduled/lifecycle',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Expire stale workflows and send lifecycle reminders',
  },
  {
    cronName: 'loyalty-expiry',
    routePath: '/api/scheduled/loyalty-expiry',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Expire loyalty points and rewards on schedule',
  },
  {
    cronName: 'momentum-snapshot',
    routePath: '/api/cron/momentum-snapshot',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Persist daily chef momentum snapshots',
  },
  {
    cronName: 'morning-briefing',
    routePath: '/api/cron/morning-briefing',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Generate the deterministic morning briefing for each tenant',
  },
  {
    cronName: 'openclaw-polish',
    routePath: '/api/cron/openclaw-polish',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Run OpenClaw enrichment and data polish after sync',
  },
  {
    cronName: 'openclaw-sync',
    routePath: '/api/cron/openclaw-sync',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Ingest nightly OpenClaw cartridge updates',
  },
  {
    cronName: 'price-sync',
    routePath: '/api/cron/price-sync',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Legacy nightly OpenClaw price sync',
  },
  {
    cronName: 'push-cleanup',
    routePath: '/api/scheduled/push-cleanup',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Remove stale push subscriptions and aged notification logs',
  },
  {
    cronName: 'quarterly-checkin',
    routePath: '/api/cron/quarterly-checkin',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Trigger quarterly business-health check-in reminders',
  },
  {
    cronName: 'raffle-draw',
    routePath: '/api/scheduled/raffle-draw',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Close and settle active raffle rounds',
  },
  {
    cronName: 'recall-check',
    routePath: '/api/cron/recall-check',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Scan FDA recalls against ingredient inventory',
  },
  {
    cronName: 'renewal-reminders',
    routePath: '/api/cron/renewal-reminders',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Send insurance and certification renewal reminders',
  },
  {
    cronName: 'rsvp-retention',
    routePath: '/api/scheduled/rsvp-retention',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Purge old RSVP exports and reminder retention data',
  },
  {
    cronName: 'sequences',
    routePath: '/api/scheduled/sequences',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Process marketing sequences and birthday enrollments',
  },
  {
    cronName: 'waitlist-sweep',
    routePath: '/api/scheduled/waitlist-sweep',
    maxExpectedMinutes: 2880,
    cadence: 'daily',
    description: 'Sweep waitlist entries and notify newly open dates',
  },
]

export const CRON_MONITOR_DEFINITION_MAP = new Map(
  CRON_MONITOR_DEFINITIONS.map((definition) => [definition.cronName, definition])
)
